### ISSUE TITLE
Investigate fail on cluster API integration tests

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10136]
|Wazuh version|Component|
|---|---|
| 4.3.0 | AIT |

The `GET /cluster/configuration/validation` fails sometimes due to an invalid configuration on one of the cluster nodes. We need to investigate what could be happening and how to prevent it.

<details>

<summary>Test report</summary>

```
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.5', 'Platform': 'Linux-5.4.0-1029-aws-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.9.0', 'pluggy': '0.13.1'}, 'Plugins': {'tavern': '1.0.0', 'metadata': '1.10.0', 'html': '2.0.1'}}
rootdir: /tmp/Test_integration_endpoints_B1309_test_files/api/test/integration, inifile: pytest.ini
plugins: tavern-1.0.0, metadata-1.10.0, html-2.0.1
collecting ... collected 45 items

test_cluster_endpoints.tavern.yaml::GET /cluster/local/config PASSED     [  2%]
test_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED      [  4%]
test_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED       [  6%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED            [  8%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[master-node] PASSED [ 11%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker1] PASSED   [ 13%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker2] PASSED   [ 15%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[ip] PASSED [ 17%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[name] PASSED [ 20%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[type] PASSED [ 22%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[version] PASSED [ 24%]
test_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED           [ 26%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED [ 28%]
test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation FAILED [ 31%]
test_cluster_endpoints.tavern.yaml::GET /cluster/api/config PASSED       [ 33%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED [ 35%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[master-node] PASSED [ 37%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker1] PASSED [ 40%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker2] PASSED [ 42%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[master-node] PASSED [ 44%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker1] PASSED [ 46%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker2] PASSED [ 48%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker1] PASSED [ 51%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker2] PASSED [ 53%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[master-node] PASSED [ 55%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker1] PASSED [ 57%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker2] PASSED [ 60%]
test_cluster_endpoints.tavern.yaml::GET /cluster/wrong_node/stats PASSED [ 62%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[master-node] PASSED [ 64%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker1] PASSED [ 66%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker2] PASSED [ 68%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[master-node] PASSED [ 71%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker1] PASSED [ 73%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker2] PASSED [ 75%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[master-node] PASSED [ 77%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker1] PASSED [ 80%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker2] PASSED [ 82%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[master-node] PASSED [ 84%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker1] PASSED [ 86%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker2] PASSED [ 88%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[master-node] PASSED [ 91%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker1] PASSED [ 93%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker2] PASSED [ 95%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED          [ 97%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/configuration PASSED [100%]

=================================== FAILURES ===================================
_ /tmp/Test_integration_endpoints_B1309_test_files/api/test/integration/test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjMxNjMxMTE4LCJleHAiOjE2MzE2MzIwMTgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AJ0hyY1obdmhSppuUXNhIiJQpvtkvgaZkP2cdBekQqWWIq8qIudBRp3-kYv_JDPm9nfz0eRPdLAXinRWqSPorcXqAd0LkcHJrL46Anpy9Krng9yCvMOEEkiI4BUSL6DtNOx51axOhFJwkBbz3OtEy1LGNwJ--l-qq-g3U0euS1kibazX'

Source test stage (line 783):
  - name: Request cluster validation
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/cluster/configuration/validation"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        nodes_list: 'worker1,worker2'
    response:
      status_code: 200
      json:
        error: !anyint
        data:
          affected_items:
            - name: worker1
              status: 'OK'
            - name: worker2
              status: 'OK'
          failed_items: []
          total_affected_items: 2
          total_failed_items: 0


Formatted stage:
  name: Request cluster validation
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjMxNjMxMTE4LCJleHAiOjE2MzE2MzIwMTgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AJ0hyY1obdmhSppuUXNhIiJQpvtkvgaZkP2cdBekQqWWIq8qIudBRp3-kYv_JDPm9nfz0eRPdLAXinRWqSPorcXqAd0LkcHJrL46Anpy9Krng9yCvMOEEkiI4BUSL6DtNOx51axOhFJwkBbz3OtEy1LGNwJ--l-qq-g3U0euS1kibazX
    method: GET
    params:
      nodes_list: worker1,worker2
    url: 'https://localhost:55000/cluster/configuration/validation'
    verify: false
  response:
    json:
      data:
        affected_items:
        - name: worker1
          status: OK
        - name: worker2
          status: OK
        failed_items: []
        total_affected_items: 2
        total_failed_items: 0
      error: !anyint ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Request cluster validation' failed:
    - List item(s) not present in response: [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}]
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:41 List item(s) not present in response: [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'af...n some nodes'} == {'data': {'af...7f13eb6a59a0>}
  Differing items:
  {'data': {'affected_items': [{'name': 'worker2', 'status': 'OK'}], 'failed_items': [{'error': {'code': 1908, 'message'...diation': 'Please, fix the corrupted files'}, 'id': ['worker1']}], 'total_affected_items': 1, 'total_failed_items': 1}} != {'data': {'affected_items': [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}], 'failed_items': [], 'total_affected_items': 2, 'total_failed_items': 0}}
  {'error': 2} != {'error': <tavern.util.loader.IntSentinel object at 0x7f13eb6a59a0>}
  Left contains 1 more item:
  {'message': 'Could not check v...
  
  ...Full output truncated (33 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_it...led_items': 1} == {'affected_it...led_items': 0}
  Differing items:
  {'affected_items': [{'name': 'worker2', 'status': 'OK'}]} != {'affected_items': [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}]}
  {'total_affected_items': 1} != {'total_affected_items': 2}
  {'total_failed_items': 1} != {'total_failed_items': 0}
  {'failed_items': [{'error': {'code': 1908, 'message': "Error validating configuration: No rule id or level specified f...e rules: 'etc/rules/new-rules_corrupted.xml'.", 'remediation': 'Please, fix the corrupted files'}, 'id': ['worker1']}]} != {'failed_items': []}
  Full diff:
    {...
  
  ...Full output truncated (26 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert [{'name': 'wo...tatus': 'OK'}] == [{'name': 'wo...tatus': 'OK'}]
  At index 0 diff: {'name': 'worker2', 'status': 'OK'} != {'name': 'worker1', 'status': 'OK'}
  Right contains one more item: {'name': 'worker2', 'status': 'OK'}
  Full diff:
  - [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}]
  + [{'name': 'worker2', 'status': 'OK'}]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 512, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(msg) from e
tavern.util.exceptions.KeyMismatchError: List item(s) not present in response: [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}]
=============================== warnings summary ===============================
/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/hooks.py:83
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/hooks.py:83: PytestDeprecationWarning: direct construction of YamlFile has been deprecated, please use YamlFile.from_parent
    return YamlFile(path, parent)

/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:233: 23 tests with warnings
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:233: PytestDeprecationWarning: direct construction of YamlItem has been deprecated, please use YamlItem.from_parent
    item = YamlItem(test_spec["test_name"], self, test_spec, self.fspath)

/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:61
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:61: PytestUnknownMarkWarning: Unknown pytest.mark.base_tests - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    pytest_marks.append(getattr(pytest.mark, m))

/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:182: 33 tests with warnings
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:182: PytestDeprecationWarning: direct construction of YamlItem has been deprecated, please use YamlItem.from_parent
    item_new = YamlItem(spec_new["test_name"], self, spec_new, self.fspath)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
- generated html file: file:///tmp/Test_integration_endpoints_B1309_test_files/api/test/integration/Test_integration_endpoints_B1309_test_cluster_endpoints.html -
=========================== short test summary info ============================
FAILED test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation
============ 1 failed, 44 passed, 58 warnings in 655.66s (0:10:55) =============
```

</details>

[Test logs](https://github.com/wazuh/wazuh/files/7168442/Test_integration_endpoints_B1309_test_cluster_endpoints_logs.1.zip)

**Comment by mcarmona99** [comment]
This issue is going to be solved [here](https://github.com/wazuh/wazuh/issues/10204).
