### ISSUE TITLE
Open Distro for Elasticsearch Failed to Start

### ISSUE THREAD

**Issue by Blockhouse2cool** [wazuh/wazuh#10171]
| 4.2.1 | Elasticsearch | Manager | Packages | Ubuntu 20.04.3 LTS | All-in-one deployment |
ELK Stack Info:

- filebeat/now 7.10.2 amd64 [installed,local]
- opendistroforelasticsearch-kibana/now 1.13.2 amd64 [installed,local]
- opendistroforelasticsearch/now 1.13.2-1 amd64 [installed,local]

As of now, Wazuh and Elasticsearch (Open Distro for Elasticsearch) are running, when I restart the Elasticsearch service, Elasticsearch fails to start. **Note**: I do have a stable snapshot where I am able to revert to a working version.

![image](https://user-images.githubusercontent.com/90863891/133665019-ae3b55dc-e33c-40fc-8514-4b6002e00280.png)

I initially thought it was some sort of file permission issue, but after comparing the following directories before and after the restart:

- /etc/elasticsearch
- /etc/default/elasticsearch
- /usr/share/elasticsearch/
- /var/lib/elasticsearch
- /var/log/elasticsearch

I noticed that nothing had changed (at least permission-wise).

I tried to list open files (lsof -i -P -n | grep -v "(ESTABLISHED)") before and after the restart and here's how they compare:

![image](https://user-images.githubusercontent.com/90863891/133665797-38468b30-7124-409a-a8ef-56a82257fb7f.png)

I can see that Java doesn't restart, I noticed it's using IPv6 where I thought I had it disabled on the system within the Grub configuration (GRUB_CMDLINE_LINUX="ipv6.disable=1"); so I removed that parameter and updated the Grub configuration, then disabled the Uncomplicated Firewall (UFW). After another restart of the Elasticsearch service, it still fails with the same error saying "Could not create the Java Virtual Machine."

I tried to tune Elasticsearch and the jvm.options using this guide: (https://documentation.wazuh.com/current/user-manual/elasticsearch/elastic_tuning.html#elastic-tuning) before a service restart, and that did not work. I ensured that I do not use more the 50% of my available RAM (16 GB to the VM and I have it set for 7 GB).

I've looked at various Elasticsearch issues on the Wazuh and the Elastic Github itself, but I found no resolution. If anyone has any idea what could be wrong or other areas I can troubleshoot, please let me know. Thanks in advance!

**Comment by Blockhouse2cool** [comment]
Fresh logs `cat /var/log/elasticsearch/wazuh-cluster.log` after a restart:

> [2021-09-16T16:25:00,837][WARN ][o.e.b.Natives            ] [node-1] unable to load JNA native support library, native methods will be disabled.
> java.lang.UnsatisfiedLinkError: /tmp/elasticsearch-3184164484282054169/jna3603684163502380860.tmp: /tmp/elasticsearch-3184164484282054169/jna3603684163502380860.tmp: failed to map segment from shared object
>         at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
>         at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383) ~[?:?]
>         at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227) ~[?:?]
>         at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169) ~[?:?]
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2407) ~[?:?]
>         at java.lang.Runtime.load0(Runtime.java:747) ~[?:?]
>         at java.lang.System.load(System.java:1857) ~[?:?]
>         at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018) ~[jna-5.5.0.jar:5.5.0 (b0)]
>         at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988) ~[jna-5.5.0.jar:5.5.0 (b0)]
>         at com.sun.jna.Native.<clinit>(Native.java:195) ~[jna-5.5.0.jar:5.5.0 (b0)]
>         at java.lang.Class.forName0(Native Method) ~[?:?]
>         at java.lang.Class.forName(Class.java:377) ~[?:?]
>         at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-7.10.2.jar:7.10.2]
>         at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:110) [elasticsearch-7.10.2.jar:7.10.2]
>         at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178) [elasticsearch-7.10.2.jar:7.10.2]
>         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) [elasticsearch-7.10.2.jar:7.10.2]
>         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) [elasticsearch-7.10.2.jar:7.10.2]
>         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) [elasticsearch-7.10.2.jar:7.10.2]
>         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.10.2.jar:7.10.2]
>         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) [elasticsearch-cli-7.10.2.jar:7.10.2]
>         at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.10.2.jar:7.10.2]
>         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) [elasticsearch-7.10.2.jar:7.10.2]
>         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.10.2.jar:7.10.2]
> [2021-09-16T16:25:00,890][WARN ][o.e.b.Natives            ] [node-1] cannot check if running as root because JNA is not available
> [2021-09-16T16:25:00,891][WARN ][o.e.b.Natives            ] [node-1] cannot install system call filter because JNA is not available
> [2021-09-16T16:25:00,891][WARN ][o.e.b.Natives            ] [node-1] cannot register console handler because JNA is not available
> [2021-09-16T16:25:00,893][WARN ][o.e.b.Natives            ] [node-1] cannot getrlimit RLIMIT_NPROC because JNA is not available
> [2021-09-16T16:25:00,894][WARN ][o.e.b.Natives            ] [node-1] cannot getrlimit RLIMIT_AS because JNA is not available
> [2021-09-16T16:25:00,894][WARN ][o.e.b.Natives            ] [node-1] cannot getrlimit RLIMIT_FSIZE because JNA is not available
> [2021-09-16T16:25:01,267][INFO ][o.e.n.Node               ] [node-1] version[7.10.2], pid[862], build[oss/deb/747e1cc71def077253878a59143c1f785afa92b9/2021-01-13T00:42:12.435326Z], OS[Linux/5.4.0-84-generic/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/15.0.1/15.0.1+9]
> [2021-09-16T16:25:01,269][INFO ][o.e.n.Node               ] [node-1] JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]
> [2021-09-16T16:25:01,270][INFO ][o.e.n.Node               ] [node-1] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms7g, -Xmx7g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/elasticsearch-3184164484282054169, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elasticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=file:///usr/share/elasticsearch/plugins/opendistro-performance-analyzer/pa_config/es_security.policy, -XX:MaxDirectMemorySize=3758096384, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=oss, -Des.distribution.type=deb, -Des.bundled_jdk=true]
> [2021-09-16T16:25:04,804][INFO ][c.a.o.s.s.t.OpenDistroSSLConfig] [node-1] SSL dual mode is disabled
> [2021-09-16T16:25:04,804][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [node-1] ES Config path is /etc/elasticsearch
> [2021-09-16T16:25:06,123][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [node-1] JVM supports TLSv1.3
> [2021-09-16T16:25:06,130][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [node-1] Config directory is /etc/elasticsearch/, from there the key- and truststore files are resolved relatively
> [2021-09-16T16:25:07,227][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [node-1] TLS Transport Client Provider : JDK
> [2021-09-16T16:25:07,227][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [node-1] TLS Transport Server Provider : JDK
> [2021-09-16T16:25:07,228][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [node-1] TLS HTTP Provider             : JDK
> [2021-09-16T16:25:07,228][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [node-1] Enabled TLS protocols for transport layer : [TLSv1.3, TLSv1.2, TLSv1.1]
> [2021-09-16T16:25:07,229][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [node-1] Enabled TLS protocols for HTTP layer      : [TLSv1.3, TLSv1.2, TLSv1.1]
> [2021-09-16T16:25:07,751][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [node-1] Clustername: wazuh-cluster
> [2021-09-16T16:25:07,767][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node-1] Directory /etc/elasticsearch/certs has insecure file permissions (should be 0700)
> [2021-09-16T16:25:07,768][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node-1] File /etc/elasticsearch/certs/admin.pem has insecure file permissions (should be 0600)
> [2021-09-16T16:25:07,768][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node-1] File /etc/elasticsearch/certs/elasticsearch-key.pem has insecure file permissions (should be 0600)
> [2021-09-16T16:25:07,769][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node-1] File /etc/elasticsearch/certs/elasticsearch.pem has insecure file permissions (should be 0600)
> [2021-09-16T16:25:07,769][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node-1] File /etc/elasticsearch/certs/root-ca.pem has insecure file permissions (should be 0600)
> [2021-09-16T16:25:07,770][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [node-1] File /etc/elasticsearch/.elasticsearch.keystore.initial_md5sum has insecure file permissions (should be 0600)
> [2021-09-16T16:25:10,283][INFO ][c.a.o.j.JobSchedulerPlugin] [node-1] Loaded scheduler extension: opendistro-index-management, index: .opendistro-ism-config
> [2021-09-16T16:25:10,545][INFO ][c.a.o.j.JobSchedulerPlugin] [node-1] Loaded scheduler extension: reports-scheduler, index: .opendistro-reports-definitions
> [2021-09-16T16:25:10,561][INFO ][c.a.o.j.JobSchedulerPlugin] [node-1] Loaded scheduler extension: opendistro_anomaly_detector, index: .opendistro-anomaly-detector-jobs
> [2021-09-16T16:25:10,566][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [aggs-matrix-stats]
> [2021-09-16T16:25:10,566][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [analysis-common]
> [2021-09-16T16:25:10,567][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [geo]
> [2021-09-16T16:25:10,567][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [ingest-common]
> [2021-09-16T16:25:10,567][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [ingest-geoip]
> [2021-09-16T16:25:10,568][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [ingest-user-agent]
> [2021-09-16T16:25:10,568][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [kibana]
> [2021-09-16T16:25:10,568][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [lang-expression]
> [2021-09-16T16:25:10,569][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [lang-mustache]
> [2021-09-16T16:25:10,569][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [lang-painless]
> [2021-09-16T16:25:10,569][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [mapper-extras]
> [2021-09-16T16:25:10,569][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [parent-join]
> [2021-09-16T16:25:10,570][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [percolator]
> [2021-09-16T16:25:10,570][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [rank-eval]
> [2021-09-16T16:25:10,570][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [reindex]
> [2021-09-16T16:25:10,571][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [repository-url]
> [2021-09-16T16:25:10,571][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [systemd]
> [2021-09-16T16:25:10,571][INFO ][o.e.p.PluginsService     ] [node-1] loaded module [transport-netty4]
> [2021-09-16T16:25:10,572][INFO ][o.e.p.PluginsService     ] [node-1] loaded plugin [opendistro-alerting]
> [2021-09-16T16:25:10,573][INFO ][o.e.p.PluginsService     ] [node-1] loaded plugin [opendistro-anomaly-detection]
> [2021-09-16T16:25:10,573][INFO ][o.e.p.PluginsService     ] [node-1] loaded plugin [opendistro-asynchronous-search]
> [2021-09-16T16:25:10,573][INFO ][o.e.p.PluginsService     ] [node-1] loaded plugin [opendistro-index-management]
> [2021-09-16T16:25:10,574][INFO ][o.e.p.PluginsService     ] [node-1] loaded plugin [opendistro-job-scheduler]
> [2021-09-16T16:25:10,574][INFO ][o.e.p.PluginsService     ] [node-1] loaded plugin [opendistro-knn]
> [2021-09-16T16:25:10,574][INFO ][o.e.p.PluginsService     ] [node-1] loaded plugin [opendistro-reports-scheduler]
> [2021-09-16T16:25:10,574][INFO ][o.e.p.PluginsService     ] [node-1] loaded plugin [opendistro-sql]
> [2021-09-16T16:25:10,575][INFO ][o.e.p.PluginsService     ] [node-1] loaded plugin [opendistro_security]
> [2021-09-16T16:25:10,605][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [node-1] Disabled https compression by default to mitigate BREACH attacks. You can enable it by setting 'http.compression: true' in elasticsearch.yml
> [2021-09-16T16:25:10,731][INFO ][o.e.e.NodeEnvironment    ] [node-1] using [1] data paths, mounts [[/ (/dev/mapper/ubuntu--vg-ubuntu--lv)]], net usable_space [165.7gb], net total_space [195.3gb], types [ext4]
> [2021-09-16T16:25:10,732][INFO ][o.e.e.NodeEnvironment    ] [node-1] heap size [7gb], compressed ordinary object pointers [true]
> [2021-09-16T16:25:19,817][INFO ][o.e.n.Node               ] [node-1] node name [node-1], node ID [rxpqFeJPSyKNZLk0FQinpw], cluster name [wazuh-cluster], roles [master, remote_cluster_client, data, ingest]
> [2021-09-16T16:25:20,809][WARN ][c.a.o.r.s.PluginSettings ] [node-1] reports:Failed to load /etc/elasticsearch/opendistro-reports-scheduler/reports-scheduler.yml
> [2021-09-16T16:25:26,838][WARN ][c.a.o.s.c.Salt           ] [node-1] If you plan to use field masking pls configure compliance salt e1ukloTsQlOgPquJ to be a random string of 16 chars length identical on all nodes
> [2021-09-16T16:25:26,918][INFO ][c.a.o.s.a.i.AuditLogImpl ] [node-1] Message routing enabled: true
> [2021-09-16T16:25:27,141][INFO ][c.a.o.s.f.OpenDistroSecurityFilter] [node-1] <NONE> indices are made immutable.
> [2021-09-16T16:25:28,201][INFO ][c.a.o.a.b.ADCircuitBreakerService] [node-1] Registered memory breaker.
> [2021-09-16T16:25:28,935][INFO ][o.e.t.NettyAllocator     ] [node-1] creating NettyAllocator with the following configs: [name=elasticsearch_configured, chunk_size=1mb, suggested_max_allocation_size=1mb, factors={es.unsafe.use_netty_default_chunk_and_page_size=false, g1gc_enabled=true, g1gc_region_size=4mb}]
> [2021-09-16T16:25:29,119][INFO ][o.e.d.DiscoveryModule    ] [node-1] using discovery type [zen] and seed hosts providers [settings]
> [2021-09-16T16:25:29,867][WARN ][o.e.g.DanglingIndicesState] [node-1] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
> [2021-09-16T16:25:30,766][INFO ][o.e.n.Node               ] [node-1] initialized
> [2021-09-16T16:25:30,767][INFO ][o.e.n.Node               ] [node-1] starting ...
> [2021-09-16T16:25:31,106][INFO ][o.e.t.TransportService   ] [node-1] publish_address {192.168.0.7:9300}, bound_addresses {[::]:9300}
> [2021-09-16T16:25:32,588][INFO ][o.e.b.BootstrapChecks    ] [node-1] bound or publishing to a non-loopback address, enforcing bootstrap checks
> [2021-09-16T16:25:32,592][ERROR][o.e.b.Bootstrap          ] [node-1] node validation exception
> [1] bootstrap checks failed
> [1]: system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk
> [2021-09-16T16:25:32,595][INFO ][o.e.n.Node               ] [node-1] stopping ...
> [2021-09-16T16:25:32,595][INFO ][c.a.o.s.a.r.AuditMessageRouter] [node-1] Closing AuditMessageRouter
> [2021-09-16T16:25:32,596][INFO ][c.a.o.s.a.s.SinkProvider ] [node-1] Closing InternalESSink
> [2021-09-16T16:25:32,596][INFO ][c.a.o.s.a.s.SinkProvider ] [node-1] Closing DebugSink
> [2021-09-16T16:25:32,643][INFO ][o.e.n.Node               ] [node-1] stopped
> [2021-09-16T16:25:32,643][INFO ][o.e.n.Node               ] [node-1] closing ...
> [2021-09-16T16:25:32,655][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-1] fatal error in thread [Thread-3], exiting
> java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
>         at org.elasticsearch.systemd.Libsystemd.lambda$static$0(Libsystemd.java:34) ~[?:?]
>         at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
>         at org.elasticsearch.systemd.Libsystemd.<clinit>(Libsystemd.java:33) ~[?:?]
>         at org.elasticsearch.systemd.SystemdPlugin.sd_notify(SystemdPlugin.java:126) ~[?:?]
>         at org.elasticsearch.systemd.SystemdPlugin.close(SystemdPlugin.java:152) ~[?:?]
>         at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74) ~[elasticsearch-core-7.10.2.jar:7.10.2]
>         at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116) ~[elasticsearch-core-7.10.2.jar:7.10.2]
>         at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:99) ~[elasticsearch-core-7.10.2.jar:7.10.2]
>         at org.elasticsearch.node.Node.close(Node.java:1024) ~[elasticsearch-7.10.2.jar:7.10.2]
>         at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74) ~[elasticsearch-core-7.10.2.jar:7.10.2]
>         at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116) ~[elasticsearch-core-7.10.2.jar:7.10.2]
>         at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:66) ~[elasticsearch-core-7.10.2.jar:7.10.2]
>         at org.elasticsearch.bootstrap.Bootstrap$4.run(Bootstrap.java:192) ~[elasticsearch-7.10.2.jar:7.10.2]

**Comment by Blockhouse2cool** [comment]
This issue occurs when you change your fstab file to mount the /tmp directory with the _noexec_ option. After removing that option and remounting the directory, I was able to restart Elasticsearch without issues. This was **not** a Wazuh or ELK Stack issue, it was my Ubuntu Configuration that broke Elasticsearch.
