### ISSUE TITLE
Investigate random fail in `GET /cluster/configuration/validation` endpoint

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10204]
| Wazuh version | Component |
|-|-|
| 4.3.0 | AIT |

One of the API integration tests failed during a PR check. It only failed once, but we need to investigate why.

## Artifacts

[Build artifacts](https://github.com/wazuh/wazuh/files/7195413/archive.zip)

## Test report

```
_ /tmp/Test_integration_endpoints_B1309_test_files/api/test/integration/test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjMxNjMxMTE4LCJleHAiOjE2MzE2MzIwMTgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AJ0hyY1obdmhSppuUXNhIiJQpvtkvgaZkP2cdBekQqWWIq8qIudBRp3-kYv_JDPm9nfz0eRPdLAXinRWqSPorcXqAd0LkcHJrL46Anpy9Krng9yCvMOEEkiI4BUSL6DtNOx51axOhFJwkBbz3OtEy1LGNwJ--l-qq-g3U0euS1kibazX'

Source test stage (line 783):
  - name: Request cluster validation
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/cluster/configuration/validation"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        nodes_list: 'worker1,worker2'
    response:
      status_code: 200
      json:
        error: !anyint
        data:
          affected_items:
            - name: worker1
              status: 'OK'
            - name: worker2
              status: 'OK'
          failed_items: []
          total_affected_items: 2
          total_failed_items: 0


Formatted stage:
  name: Request cluster validation
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjMxNjMxMTE4LCJleHAiOjE2MzE2MzIwMTgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AJ0hyY1obdmhSppuUXNhIiJQpvtkvgaZkP2cdBekQqWWIq8qIudBRp3-kYv_JDPm9nfz0eRPdLAXinRWqSPorcXqAd0LkcHJrL46Anpy9Krng9yCvMOEEkiI4BUSL6DtNOx51axOhFJwkBbz3OtEy1LGNwJ--l-qq-g3U0euS1kibazX
    method: GET
    params:
      nodes_list: worker1,worker2
    url: 'https://localhost:55000/cluster/configuration/validation'
    verify: false
  response:
    json:
      data:
        affected_items:
        - name: worker1
          status: OK
        - name: worker2
          status: OK
        failed_items: []
        total_affected_items: 2
        total_failed_items: 0
      error: !anyint ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Request cluster validation' failed:
    - List item(s) not present in response: [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}]
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:41 List item(s) not present in response: [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'af...n some nodes'} == {'data': {'af...7f13eb6a59a0>}
  Differing items:
  {'data': {'affected_items': [{'name': 'worker2', 'status': 'OK'}], 'failed_items': [{'error': {'code': 1908, 'message'...diation': 'Please, fix the corrupted files'}, 'id': ['worker1']}], 'total_affected_items': 1, 'total_failed_items': 1}} != {'data': {'affected_items': [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}], 'failed_items': [], 'total_affected_items': 2, 'total_failed_items': 0}}
  {'error': 2} != {'error': <tavern.util.loader.IntSentinel object at 0x7f13eb6a59a0>}
  Left contains 1 more item:
  {'message': 'Could not check v...
  
  ...Full output truncated (33 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_it...led_items': 1} == {'affected_it...led_items': 0}
  Differing items:
  {'affected_items': [{'name': 'worker2', 'status': 'OK'}]} != {'affected_items': [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}]}
  {'total_affected_items': 1} != {'total_affected_items': 2}
  {'total_failed_items': 1} != {'total_failed_items': 0}
  {'failed_items': [{'error': {'code': 1908, 'message': "Error validating configuration: No rule id or level specified f...e rules: 'etc/rules/new-rules_corrupted.xml'.", 'remediation': 'Please, fix the corrupted files'}, 'id': ['worker1']}]} != {'failed_items': []}
  Full diff:
    {...
  
  ...Full output truncated (26 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert [{'name': 'wo...tatus': 'OK'}] == [{'name': 'wo...tatus': 'OK'}]
  At index 0 diff: {'name': 'worker2', 'status': 'OK'} != {'name': 'worker1', 'status': 'OK'}
  Right contains one more item: {'name': 'worker2', 'status': 'OK'}
  Full diff:
  - [{'name': 'worker1', 'status': 'OK'}, {'name': 'worker2', 'status': 'OK'}]
  + [{'name': 'worker2', 'status': 'OK'}]
```

**Comment by Kondent** [comment]
## Update

I've been investigating this behavior and it seems like to be a race condition which rarely happens but needs to be fixed.
This race condition occurs between the deletion of a corrupted file and a cluster validation.
