### ISSUE TITLE
GET /cluster/:node/configuration/analysis/rules is responding with internal error even with default rules

### ISSUE THREAD

**Issue by kilpa** [wazuh/wazuh#10715]
|Wazuh version|Component|
|---|---|
| 4.2.4-rev | Wazuh API |

Hello!

There is a problem with `GET /cluster/wazuh-manager-master-us-east-1/configuration/analysis/rules` endpoint where the API responds with internal error message. Looking at the API logs I see a very strange error:

*/var/ossec/logs/api.log*
```
 2021/10/29 12:26:31 ERROR: Could not request component configuration: Data could not be received
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/configuration.py", line 790, in get_active_configuration
    rec_msg_ok, rec_msg = s.receive().decode().split(" ", 1)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 29869: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 256, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 230, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/rbac/decorators.py", line 406, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/manager.py", line 222, in get_config
    data = configuration.get_active_configuration(agent_id='000', component=component, configuration=config)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.4-py3.9.egg/wazuh/core/configuration.py", line 792, in get_active_configuration
    raise WazuhInternalError(1118, extra_message="Data could not be received")
wazuh.core.exception.WazuhInternalError: Error 1118 - Could not request component configuration: Data could not be received
2021/10/29 12:26:31 INFO: wazuh-kibana 10.222.18.7 "GET /cluster/wazuh-manager-master-us-east-1/configuration/analysis/rules" with parameters {} and body {} done in 0.052s: 500
```

I do not have the \0x85 (…) symbol used anywhere in my rules and even removing the symbol from all the Wazuh default rulesets, the error persists (see the Slack thread [here](https://wazuh.slack.com/archives/C0A933R8E/p1632992152410400))  

This error is reproducable on the latest docker image as well.

**Comment by Selutario** [comment]
Hello @kilpa!

Thank you very much for reporting this issue. I have tried to debug it and have found two different things:
- When trying to run `GET /manager/configuration/analysis/rules` (it is the same as `GET /cluster/{node_id}/configuration/{component}/{configuration}) on a clean install of Wazuh, I have gotten a segmentation fault in the analysisd service which is stopping it. I've reported it on https://github.com/wazuh/wazuh/issues/10729 and the team is already looking into it.
- When running the endpoint in a wazuh-docker that I have already upgraded on previous occasions, I do not get the segmentation fault but the error when decoding some characters that you have reported. This error does not seem to be related to characters within the ruleset but rather to some problem within `analysisd`. I have added information about it here: https://github.com/wazuh/wazuh/issues/10729#issuecomment-960618128

Both errors are likely related, although we will need to do more research. You can be aware of any news in this regard in the issue that I have mentioned before.

As I said, thank you very much for the report and sorry for the inconvenience.

Best regards,
Selu.

**Comment by Selutario** [comment]
The problem is already solved after fixing this issue:
- https://github.com/wazuh/wazuh/issues/10729
