### ISSUE TITLE
Segmentation fault in Analysisd

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#10729]
|Wazuh version|Component|Install method|Platform|
|---|---|---|---|---|
| 4.2.4+ | Analysisd | Manager | Ubuntu 20.04 |

## Description

While trying to reproduce what a user reported at #10715, I found a strange behavior. When sending this command:
- `getconfig rules`
to the analysis socket:
- `/var/ossec/queue/sockets/analysis`
a segmentation fault is being raised as it can be seen in the debug analysisd logs:
```
2021/11/04 08:11:02 wazuh-analysisd[1794] state.c:106 at w_analysisd_write_state(): DEBUG: Updating state file.
2021/11/04 08:11:07 wazuh-analysisd[1794] state.c:106 at w_analysisd_write_state(): DEBUG: Updating state file.
2021/11/04 08:11:12 wazuh-analysisd[1794] state.c:106 at w_analysisd_write_state(): DEBUG: Updating state file.
2021/11/04 08:11:17 wazuh-analysisd[1794] state.c:106 at w_analysisd_write_state(): DEBUG: Updating state file.
Segmentation fault (core dumped)
```

It can be reproduced by using this API endpoint: `GET /manager/configuration/analysis/rules`. This problem is not happening with other analysisd configs (`global`, `active_response`, `alerts`, `command`, `rules`, `decoders`, `internal`).

**Comment by Selutario** [comment]
## Issue update

I have been able to reproduce the segfault shown above in a clean v4.2.4 environment. However, I have carried out the same steps in a [wazuh-docker](https://github.com/wazuh/wazuh-docker) v4.2.0 environment that I have been updating from previous versions, and in this case, I do not get a segmentation fault but the following error reported by @kilpa at https://github.com/wazuh/wazuh/issues/10715:
```
File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/configuration.py", line 790, in get_active_configuration
    rec_msg_ok, rec_msg = s.receive().decode().split(" ", 1)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 29142: invalid start byte
```

I removed the `…` character (0x85) from the ruleset but the error is still happening. This is what I found at position 29142 of the wazuh-analysisd response:
![image](https://user-images.githubusercontent.com/23361101/140295867-e1305fd3-5401-4294-a0f5-db9142a45117.png)

I'm not sure if this could be related to the segfault, but I think it may be relevant. I attach analysisd's full answer in this file:
[getconfig_analysisd.txt](https://github.com/wazuh/wazuh/files/7473973/getconfig_analysisd.txt)

**Comment by vikman90** [comment]
## Backtrace

```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff7894350 in cJSON_strdup.isra.3.constprop.18 () from libwazuhext.so
#2  0x00007ffff789444d in add_item_to_object.constprop () from libwazuhext.so
#3  0x00007ffff7895614 in cJSON_AddStringToObject () from libwazuhext.so
#4  0x000055555556d499 in _getRulesListJSON (list=0x55555623fbe0, array=0x7fff0c046ac0) at analysisd/config_json.c:483
#5  0x000055555556bdcf in _getRulesListJSON (list=0x555555f6e640, array=0x7fff0c046100) at analysisd/config_json.c:242
#6  0x000055555556bdcf in _getRulesListJSON (list=0x555555efb780, array=0x7fff0c010c60) at analysisd/config_json.c:242
#7  0x000055555556bdcf in _getRulesListJSON (list=0x5555559825d0, array=0x7fff0c010bc0) at analysisd/config_json.c:242
#8  0x000055555556aac8 in getRulesConfig () at analysisd/config.c:297
#9  0x00005555555677bb in asyscom_getconfig (section=0x7fff0c000b6a "rules", output=0x7ffff7560eb8) at analysisd/asyscom.c:97
#10 0x0000555555567345 in asyscom_dispatch (command=0x7fff0c000b60 "getconfig", output=0x7ffff7560eb8) at analysisd/asyscom.c:34
#11 0x000055555556808e in asyscom_main (arg=0x0) at analysisd/asyscom.c:227
#12 0x00007ffff7745ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#13 0x00007ffff7675def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

## Rationale

I'm pretty sure this problem is due to reading variable `node->ruleinfo->same_field` instead of `node->ruleinfo->different_field` to scan the array `different_fields[]`.

**Comment by vikman90** [comment]
## Memory access issue

I've managed to fix this issue, but I've found the following memory access during my tests:

```
==5721== Conditional jump or move depends on uninitialised value(s)
==5721==    at 0x49663A3: add_item_to_object.constprop.14 (in /root/wazuh/src/libwazuhext.so)
==5721==    by 0x4967613: cJSON_AddStringToObject (in /root/wazuh/src/libwazuhext.so)
==5721==    by 0x121442: _getRulesListJSON (config_json.c:474)
==5721==    by 0x11FDCE: _getRulesListJSON (config_json.c:242)
==5721==    by 0x11FDCE: _getRulesListJSON (config_json.c:242)
==5721==    by 0x11FDCE: _getRulesListJSON (config_json.c:242)
==5721==    by 0x11EAC7: getRulesConfig (config.c:297)
==5721==    by 0x11B7BA: asyscom_getconfig (asyscom.c:97)
==5721==    by 0x11B344: asyscom_dispatch (asyscom.c:34)
==5721==    by 0x11C08D: asyscom_main (asyscom.c:227)
==5721==    by 0x50BBEA6: start_thread (pthread_create.c:477)
==5721==    by 0x51D2DEE: clone (clone.S:95)
==5721==  Uninitialised value was created by a stack allocation
==5721==    at 0x11FB90: _getRulesListJSON (config_json.c:190)
```

The loop that fills the rule object with members `same_` and `different_` does not expect flag `FIELD_DYNAMICS = 0x20000`, which causes out-of-bounds array access. This happens because **rules configuration reporting does not support `<same_field>` or `<different_field>`.
