### ISSUE TITLE
Review and fix syscheck API integration test

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10913]
|Component|
|---|
| API Integration Tests |

This issue is part of #10918 .

The `syscheck` API integration test is failing in the test case "Try to run a syscheck scan for a list of agents". In this test case, we expect to run a syscheck scan over a list of agents. The test is failing because the agent with ID 008 is not active by the time the scan starts.

Test failing in Wazuh `master` branch.

<details>

<summary>Error output</summary>

```
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM3MTA0MjI4LCJleHAiOjE2MzcxMDUxMjgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.Afu2oFr9BZlS3AdEIQt9U5Mofc5lRsJe3A-vtbaFW5FqAnlNdzHPXsfeQbUgSaNE2SMVQzgZk9KKMRTKPs9yZP_xAfj4LYRsYQf6gU8JMjzxJS94Bz6AmWovlhH9q6BYxoP5Qn8fA-Fy0TbJ3DG8kflxPGN_6gbs9KKiJRNbMeImuJCI'

Source test stage (line 514):
  - name: Try to run a syscheck scan for a list of agents
    request:
      verify: False
      method: PUT
      url: "{protocol:s}://{host:s}:{port:d}/syscheck"
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '000,002,004,006,008,010,012'
    response:
      status_code: 200
      json:
        error: 2
        data:
          affected_items:
            - '000'
            - '002'
            - '004'
            - '006'
            - '008'
          failed_items:
            - error:
                code: 1707
              id:
                - '010'
                - '012'
          total_affected_items: 5
          total_failed_items: 2


Formatted stage:
  name: Try to run a syscheck scan for a list of agents
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM3MTA0MjI4LCJleHAiOjE2MzcxMDUxMjgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.Afu2oFr9BZlS3AdEIQt9U5Mofc5lRsJe3A-vtbaFW5FqAnlNdzHPXsfeQbUgSaNE2SMVQzgZk9KKMRTKPs9yZP_xAfj4LYRsYQf6gU8JMjzxJS94Bz6AmWovlhH9q6BYxoP5Qn8fA-Fy0TbJ3DG8kflxPGN_6gbs9KKiJRNbMeImuJCI
    method: PUT
    params:
      agents_list: 000,002,004,006,008,010,012
    url: 'https://localhost:55000/syscheck'
    verify: false
  response:
    json:
      data:
        affected_items:
        - '000'
        - '002'
        - '004'
        - '006'
        - 008
        failed_items:
        - error:
            code: 1707
          id:
          - '010'
          - '012'
        total_affected_items: 5
        total_failed_items: 2
      error: 2
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Try to run a syscheck scan for a list of agents' failed:
    - List item(s) not present in response: ['008']
 -------------------------------Captured log call-------------------------------- 
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:41 List item(s) not present in response: ['008']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'af... some agents'} == {'data': {'af...}, 'error': 2}
  Omitting 1 identical items, use -vv to show
  Differing items:
  {'data': {'affected_items': ['000', '002', '004', '006'], 'failed_items': [{'error': {'code': 1707, 'message': 'Cannot...egistering and connecting agents'}, 'id': ['008', '010', '012']}], 'total_affected_items': 4, 'total_failed_items': 3}} != {'data': {'affected_items': ['000', '002', '004', '006', '008'], 'failed_items': [{'error': {'code': 1707}, 'id': ['010', '012']}], 'total_affected_items': 5, 'total_failed_items': 2}}
  Left contains 1 more item:
  {'message': 'Syscheck scan was not restarted on some agents'}
  Fu...
  
  ...Full output truncated (41 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_it...led_items': 3} == {'affected_it...led_items': 2}
  Differing items:
  {'total_affected_items': 4} != {'total_affected_items': 5}
  {'total_failed_items': 3} != {'total_failed_items': 2}
  {'failed_items': [{'error': {'code': 1707, 'message': 'Cannot send request, agent is not active', 'remediation': 'Plea...agent-connection.html to obtain more information on registering and connecting agents'}, 'id': ['008', '010', '012']}]} != {'failed_items': [{'error': {'code': 1707}, 'id': ['010', '012']}]}
  {'affected_items': ['000', '002', '004', '006']} != {'affected_items': ['000', '002', '004', '006', '008']}
  Full diff:
    {...
  
  ...Full output truncated (36 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert ['000', '002', '004', '006'] == ['000', '002'... '006', '008']
  Right contains one more item: '008'
  Full diff:
  - ['000', '002', '004', '006', '008']
  ?                            -------
  + ['000', '002', '004', '006']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 512, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(msg) from e
tavern.util.exceptions.KeyMismatchError: List item(s) not present in response: ['008']
```

</details>

We should review and fix this API integration test.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update
I've working on this and found out the possible related problem.
I'm doing a few tests to determine how to fix it. It could be a race condition between an agent restart and the test stage itself.

**Comment by Kondent** [comment]
# Issue Full Report

## API Integration Test Error Description
The agent `008` is disconnected at the same time the test stage `Try to run a **syscheck** scan for a list of agents` started.
```
{'failed_items': [{'error': {'code': 1707, 'message': 'Cannot send request, agent is not active', 'remediation': 'Plea...agent-connection.html to obtain more information on registering and connecting agents'}, 'id': ['008', '010', '012']}]} != {'failed_items': [{'error': {'code': 1707}, 'id': ['010', '012']}]}
```

## Error Analysis
* Agent version: `3.13`.
* Agent node must be running, otherwise the environment healthcheck would fail.
* Agent is not disconnected since the manager needs 30 minutes to set it as disconnected after the agent is stopped. This is strictly related with Wazuh 3.13.

After reviewing the agent logs I found out the following:
```log
2022/01/12 20:23:13 ossec-agentd: INFO: (4102): Connected to the server (nginx-lb/172.24.0.2:1514/tcp).
2022/01/12 20:23:13 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2022/01/12 20:23:17 ossec-agentd: INFO: (4102): Connected to the server (nginx-lb/172.24.0.2:1514/tcp).
2022/01/12 20:23:27 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2022/01/12 20:23:30 ossec-agentd: INFO: (4102): Connected to the server (nginx-lb/172.24.0.2:1514/tcp).
```
Now we know a race condition could be possible, if `PUT /syscheck` is executed at the same time this agent is restarting.

## Race Condition Analysis
After doing several tests, I determined that the agent is restarted because of a cluster synchronization of shared files.

```log
2022/01/12 20:23:05 INFO: [Worker worker1] [Integrity check] Finished in 0.006s. Received metadata of 33 files. Sync required.
2022/01/12 20:23:06 INFO: [Worker worker2] [Integrity check] Finished in 0.007s. Received metadata of 33 files. Sync required.
2022/01/12 20:23:14 INFO: [Worker worker1] [Integrity check] Finished in 0.004s. Received metadata of 49 files. Sync required.
2022/01/12 20:23:15 INFO: [Worker worker2] [Integrity check] Finished in 0.003s. Received metadata of 48 files. Sync required.
```

Under this development, I modified the manager entry point so all these changes to the shared files can be performed before the manager starts.
However, there are several Wazuh modules that need to be up and running at the moment this entrypoint is being executed:
* `wazuh-db`: used by a script located at `/tmp/configuration_files/master_only/`.
* `wazuh-clusterd`: needed for the synchronization process.
* `wazuh-apid`: used by a healthcheck inside the entrypoint.

Finally, all Wazuh modules will be handled by `supervisord`. So it's no needed to start Wazuh from the entrypoint.

**Working Branch: `fix/10913-fix-syscheck-ait`**


## Before - Results
<details>
<summary>Run 1</summary>

```
===> Agents:
======> env_wazuh-agent8_1:
2022/01/13 19:48:12 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2022/01/13 19:48:25 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent7_1:
2022/01/13 19:48:22 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2022/01/13 19:48:35 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent6_1:
2022/01/13 19:48:21 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2022/01/13 19:48:35 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent5_1:
2022/01/13 19:47:55 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent4_1:
2022/01/13 19:47:55 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent3_1:
2022/01/13 19:48:35 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent2_1:
2022/01/13 19:48:34 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent1_1:
2022/01/13 19:48:03 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.

===> Sync Time:
2022/01/13 19:48:04 INFO: [Worker worker2] [Integrity check] Finished in 0.009s. Received metadata of 33 files. Sync required.
2022/01/13 19:48:13 INFO: [Worker worker1] [Integrity check] Finished in 0.004s. Received metadata of 33 files. Sync required.
2022/01/13 19:48:13 INFO: [Worker worker2] [Integrity check] Finished in 0.004s. Received metadata of 48 files. Sync required.
2022/01/13 19:48:22 INFO: [Worker worker1] [Integrity check] Finished in 0.003s. Received metadata of 49 files. Sync required.

===> PUT /syscheck:
2022/01/13 19:49:13 INFO: testing 172.21.0.1 "PUT /syscheck" with parameters {"agents_list": "000"} and body {} done in 0.010s: 200
2022/01/13 19:49:13 INFO: testing 172.21.0.1 "PUT /syscheck" with parameters {"agents_list": "000,002,004,006,008,010,012"} and body {} done in 0.022s: 200
2022/01/13 19:49:20 INFO: testing 172.21.0.1 "PUT /syscheck" with parameters {} and body {} done in 0.033s: 200

===> 34 passed, 1 xpassed, 1 warnings in 99.65 seconds
```

</details>

<details>
<summary>Run 2</summary>

```
===> Agents:
======> env_wazuh-agent8_1:
2022/01/13 19:50:11 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent7_1:
2022/01/13 19:50:12 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent6_1:
2022/01/13 19:50:12 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent5_1:
2022/01/13 19:49:40 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent4_1:
2022/01/13 19:50:00 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent3_1:
2022/01/13 19:49:39 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent2_1:
2022/01/13 19:50:20 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent1_1:
2022/01/13 19:49:58 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
2022/01/13 19:50:09 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.

===> Sync Time:
2022/01/13 19:49:51 INFO: [Worker worker1] [Integrity check] Finished in 0.004s. Received metadata of 33 files. Sync required.
2022/01/13 19:49:59 INFO: [Worker worker2] [Integrity check] Finished in 0.005s. Received metadata of 33 files. Sync required.
2022/01/13 19:50:00 INFO: [Worker worker1] [Integrity check] Finished in 0.003s. Received metadata of 48 files. Sync required.
2022/01/13 19:50:08 INFO: [Worker worker2] [Integrity check] Finished in 0.003s. Received metadata of 47 files. Sync required.

===> PUT /syscheck:
2022/01/13 19:50:57 INFO: testing 172.22.0.1 "PUT /syscheck" with parameters {"agents_list": "000"} and body {} done in 0.010s: 200
2022/01/13 19:50:58 INFO: testing 172.22.0.1 "PUT /syscheck" with parameters {"agents_list": "000,002,004,006,008,010,012"} and body {} done in 0.022s: 200
2022/01/13 19:51:04 INFO: testing 172.22.0.1 "PUT /syscheck" with parameters {} and body {} done in 0.022s: 200

===> 34 passed, 1 xpassed, 1 warnings in 99.37 seconds
```

</details>

<details>
<summary>Run 3</summary>

```
===> Agents:
======> env_wazuh-agent8_1:
2022/01/13 19:51:27 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent7_1:
2022/01/13 19:51:26 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent6_1:
2022/01/13 19:51:51 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2022/01/13 19:52:04 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent5_1:
2022/01/13 19:52:05 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent4_1:
2022/01/13 19:51:24 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent3_1:
2022/01/13 19:52:04 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent2_1:
2022/01/13 19:52:03 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent1_1:
2022/01/13 19:52:03 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.

===> Sync Time:
2022/01/13 19:51:42 INFO: [Worker worker2] [Integrity check] Finished in 0.004s. Received metadata of 33 files. Sync required.
2022/01/13 19:51:43 INFO: [Worker worker1] [Integrity check] Finished in 0.003s. Received metadata of 33 files. Sync required.
2022/01/13 19:51:51 INFO: [Worker worker2] [Integrity check] Finished in 0.003s. Received metadata of 48 files. Sync required.
2022/01/13 19:51:52 INFO: [Worker worker1] [Integrity check] Finished in 0.005s. Received metadata of 47 files. Sync required.

===> PUT /syscheck:
2022/01/13 19:53:03 INFO: testing 172.23.0.1 "PUT /syscheck" with parameters {"agents_list": "000"} and body {} done in 0.010s: 200
2022/01/13 19:53:03 INFO: testing 172.23.0.1 "PUT /syscheck" with parameters {"agents_list": "000,002,004,006,008,010,012"} and body {} done in 0.022s: 200
2022/01/13 19:53:10 INFO: testing 172.23.0.1 "PUT /syscheck" with parameters {} and body {} done in 0.054s: 200
===> 34 passed, 1 xpassed, 1 warnings in 120.64 seconds
```

</details>


## After - Results
<details>
<summary>Run 1</summary>

```
===> Agents:
======> env_wazuh-agent8_1:
2022/01/13 19:33:39 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2022/01/13 19:33:52 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent7_1:
2022/01/13 19:33:53 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent6_1:
2022/01/13 19:33:37 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent5_1:
2022/01/13 19:33:52 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent4_1:
2022/01/13 19:33:42 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent3_1:
2022/01/13 19:33:41 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent2_1:
2022/01/13 19:33:51 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent1_1:
2022/01/13 19:33:40 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.

===> Sync Time:
2022/01/13 19:33:30 INFO: [Worker worker2] [Integrity check] Finished in 0.005s. Received metadata of 33 files. Sync required.
2022/01/13 19:33:30 INFO: [Worker worker1] [Integrity check] Finished in 0.004s. Received metadata of 33 files. Sync required.
2022/01/13 19:33:39 INFO: [Worker worker2] [Integrity check] Finished in 0.007s. Received metadata of 48 files. Sync required.
2022/01/13 19:33:40 INFO: [Worker worker1] [Integrity check] Finished in 0.003s. Received metadata of 47 files. Sync required.

===> PUT /syscheck:
2022/01/13 19:34:40 INFO: testing 192.168.240.1 "PUT /syscheck" with parameters {"agents_list": "000"} and body {} done in 0.011s: 200
2022/01/13 19:34:40 INFO: testing 192.168.240.1 "PUT /syscheck" with parameters {"agents_list": "000,002,004,006,008,010,012"} and body {} done in 0.023s: 200
2022/01/13 19:34:47 INFO: testing 192.168.240.1 "PUT /syscheck" with parameters {} and body {} done in 0.016s: 200

===> 35 passed, 1 warnings in 100.08 seconds
```

</details>

<details>
<summary>Run 2</summary>

```
===> Agents:
======> env_wazuh-agent8_1:
2022/01/13 19:35:34 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent7_1:
2022/01/13 19:35:19 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent6_1:
2022/01/13 19:35:18 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent5_1:
2022/01/13 19:35:37 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent4_1:
2022/01/13 19:35:26 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent3_1:
2022/01/13 19:35:26 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent2_1:
2022/01/13 19:35:35 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent1_1:
2022/01/13 19:35:35 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.

===> Sync Time:
2022/01/13 19:35:15 INFO: [Worker worker1] [Integrity check] Finished in 0.005s. Received metadata of 33 files. Sync required.
2022/01/13 19:35:15 INFO: [Worker worker2] [Integrity check] Finished in 0.005s. Received metadata of 33 files. Sync required.
2022/01/13 19:35:24 INFO: [Worker worker1] [Integrity check] Finished in 0.003s. Received metadata of 47 files. Sync required.
2022/01/13 19:35:24 INFO: [Worker worker2] [Integrity check] Finished in 0.005s. Received metadata of 47 files. Sync required.

===> PUT /syscheck:
2022/01/13 19:36:25 INFO: testing 172.18.0.1 "PUT /syscheck" with parameters {"agents_list": "000"} and body {} done in 0.010s: 200
2022/01/13 19:36:25 INFO: testing 172.18.0.1 "PUT /syscheck" with parameters {"agents_list": "000,002,004,006,008,010,012"} and body {} done in 0.023s: 200
2022/01/13 19:36:32 INFO: testing 172.18.0.1 "PUT /syscheck" with parameters {} and body {} done in 0.020s: 200

===>  35 passed, 1 warnings in 99.93 seconds
```

</details>

<details>
<summary>Run 3</summary>

```
===> Agents:
======> env_wazuh-agent8_1:
2022/01/13 19:37:04 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent7_1:
2022/01/13 19:37:03 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent6_1:
2022/01/13 19:37:07 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent5_1:
2022/01/13 19:37:06 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent4_1:
2022/01/13 19:37:15 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent3_1:
2022/01/13 19:37:13 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent2_1:
2022/01/13 19:37:13 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
======> env_wazuh-agent1_1:
2022/01/13 19:37:23 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.

===> Sync Time:
2022/01/13 19:37:00 INFO: [Worker worker1] [Integrity check] Finished in 0.007s. Received metadata of 33 files. Sync required.
2022/01/13 19:37:01 INFO: [Worker worker2] [Integrity check] Finished in 0.008s. Received metadata of 33 files. Sync required.
2022/01/13 19:37:09 INFO: [Worker worker1] [Integrity check] Finished in 0.022s. Received metadata of 41 files. Sync required.
2022/01/13 19:37:10 INFO: [Worker worker2] [Integrity check] Finished in 0.012s. Received metadata of 40 files. Sync required.

===> PUT /syscheck:
2022/01/13 19:38:16 INFO: testing 172.19.0.1 "PUT /syscheck" with parameters {"agents_list": "000"} and body {} done in 0.026s: 200
2022/01/13 19:38:16 INFO: testing 172.19.0.1 "PUT /syscheck" with parameters {"agents_list": "000,002,004,006,008,010,012"} and body {} done in 0.023s: 200
2022/01/13 19:38:23 INFO: testing 172.19.0.1 "PUT /syscheck" with parameters {} and body {} done in 0.017s: 200

===> 35 passed, 1 warnings in 105.87 seconds
```

</details>




# Conclusion
In my opinion, I think this could be an improvement. I reviewed that in almost every case the agent is restarted just once.
Plus, there's a better time diferrence between `PUT /syscheck` and the last restarted agent.

However, this situation could be handled in a better manner with a refactor of the healthchecks of our API integration test environment.

__Those tests were performed in a local environment__
