### ISSUE TITLE
Analysisd crashes with segmentation fault

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh#10911]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.4-rev | Analysisd | Manager | Sources/Packages | - |

Hello team,

We found that wazuh-analysisd crashes with a segmentation fault after loading the following Active response configuration to the Wazuh manager:

```
<active-response>
 <command>firewall-drop</command>
 <location>defined-agent</location>
 <agent_id>000</agent_id>
 <!--location>local</location-->
 <rules_id>5710</rules_id>
</active-response>
```

Segfault:

![image](https://user-images.githubusercontent.com/73501120/142661898-35b5454c-10ff-43fe-85e4-92a9191f9746.png)

Ossec.log:

```
2021/11/19 07:58:21 wazuh-analysisd: INFO: Connected to 'queue/alerts/ar' (active-response queue)
2021/11/19 07:58:23 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2021/11/19 07:58:31 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_centos8_linux.yml'
2021/11/19 07:58:31 sca: INFO: Security Configuration Assessment scan finished. Duration: 11 seconds.
2021/11/19 07:59:26 rootcheck: INFO: Ending rootcheck scan.
2021/11/19 08:00:44 wazuh-remoted: ERROR: (1320): Agent '000' not found.
2021/11/19 08:00:44 wazuh-remoted: ERROR: socketerr (not available).
2021/11/19 08:00:44 wazuh-remoted: ERROR: (1210): Queue 'queue/sockets/queue' not accessible: 'Connection refused'
2021/11/19 08:00:44 wazuh-remoted: ERROR: socketerr (not available).
2021/11/19 08:00:44 wazuh-remoted: ERROR: (1210): Queue 'queue/sockets/queue' not accessible: 'Bad file descriptor'
2021/11/19 08:00:44 wazuh-remoted: ERROR: socketerr (not available).
2021/11/19 08:00:44 wazuh-remoted: ERROR: (1210): Queue 'queue/sockets/queue' not accessible: 'Bad file descriptor'
2021/11/19 08:00:44 wazuh-remoted: ERROR: socketerr (not available).
2021/11/19 08:00:44 wazuh-remoted: ERROR: (1210): Queue 'queue/sockets/queue' not accessible: 'Bad file descriptor'
2021/11/19 08:00:44 wazuh-remoted: ERROR: socketerr (not available).
2021/11/19 08:00:44 wazuh-remoted: ERROR: (1210): Queue 'queue/sockets/queue' not accessible: 'Connection refused'
2021/11/19 08:00:46 wazuh-logcollector: ERROR: socketerr (not available).
2021/11/19 08:00:46 wazuh-logcollector: ERROR: Unable to send message to 'queue/sockets/queue' (wazuh-analysisd might be down). Attempting to reconnect.
2021/11/19 08:03:23 wazuh-syscheckd: ERROR: socketerr (not available).
2021/11/19 08:03:23 wazuh-syscheckd: ERROR: (1224): Error sending message to queue.
```
Please let me know if more information is needed.

Regards.

**Comment by vikman90** [comment]
## Backtrace

```
#0  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:77
#1  0x00007ffff75e1bd3 in __GI___strdup (s=0x55555580a <error: Cannot access memory at address 0x55555580a>) at strdup.c:41
#2  0x0000555555698711 in labels_dup (labels=0x55555580aef0) at shared/labels_op.c:195
#3  0x000055555557509d in w_copy_event_for_log (lf=0x7fff0c000b60, lf_cpy=0x7fff6c062e50) at analysisd/eventinfo.c:1143
#4  0x000055555559a4e9 in w_process_event_thread (id=0x1) at analysisd/analysisd.c:2135
#5  0x00007ffff75ce927 in start_thread (arg=<optimized out>) at pthread_create.c:435
#6  0x00007ffff765e9e4 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

Though we need to fix this issue, the right configuration to set an AR to run in the manager is:
```xml
<active-response>
  <command>firewall-drop</command>
  <location>server</location>
  <rules_id>5710</rules_id>
</active-response>
```
