### ISSUE TITLE
Review and fix RBAC black agent API integration test

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10914]
|Component|
|---|
| API Integration Tests |

The RBAC black agent API integration test is failing in the test case "Try to reconnect all agents (Partially allowed, user agnostic)". In this test case, we expect to reconnect all agents. The test is failing because the agent with ID 005 is not in the response and it should be. This agent may not be in the response because it is not active (we don't know this as the code related to non-active agents is excluded) as it was reconnected in the test case before this one.

There is a delay to avoid this race condition, maybe the delay is not enough to avoid it.

Test failing in Wazuh `master` branch.

<details>

<summary>Error output</summary>

```
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM3MTkwNjI4LCJleHAiOjE2MzcxOTE1MjgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbOTldLCJyYmFjX21vZGUiOiJibGFjayJ9.AWNfuDlgkG5MWw8s9wBgSdXNqELRG9bdZ6v0XbAP6Db-KZgfuCUa7Dkx687WKASinxgKftLcDQmhUTqRKjMacFC-AZhmBsJ46gYmln-q8Xgf57VRTQTDgWvlOF-wMM34sMJu4IwajdCGzDn8FZRHdEgtCFKP0pOIhyMhKil7wo2huJzw'
  reconnect_delay = '30'

Source test stage (line 1395):
  - name: Try to reconnect all agents (Partially allowed, user agnostic)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/reconnect"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      status_code: 200
      json:
        error: 0
        data:
          affected_items:
            - '003'
            - '005'
            - '007'
          failed_items: []
          total_affected_items: 3
          total_failed_items: 0
    delay_after: !float "{reconnect_delay}"


Formatted stage:
  delay_after: !float '30'
  name: Try to reconnect all agents (Partially allowed, user agnostic)
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM3MTkwNjI4LCJleHAiOjE2MzcxOTE1MjgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbOTldLCJyYmFjX21vZGUiOiJibGFjayJ9.AWNfuDlgkG5MWw8s9wBgSdXNqELRG9bdZ6v0XbAP6Db-KZgfuCUa7Dkx687WKASinxgKftLcDQmhUTqRKjMacFC-AZhmBsJ46gYmln-q8Xgf57VRTQTDgWvlOF-wMM34sMJu4IwajdCGzDn8FZRHdEgtCFKP0pOIhyMhKil7wo2huJzw
    method: PUT
    url: 'https://localhost:55000/agents/reconnect'
    verify: false
  response:
    json:
      data:
        affected_items:
        - '003'
        - '005'
        - '007'
        failed_items: []
        total_affected_items: 3
        total_failed_items: 0
      error: 0
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Try to reconnect all agents (Partially allowed, user agnostic)' failed:
    - List item(s) not present in response: ['005', '007']
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '403'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:41 List item(s) not present in response: ['005', '007']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'af...o all agents'} == {'data': {'af...}, 'error': 0}
  Omitting 1 identical items, use -vv to show
  Differing items:
  {'data': {'affected_items': ['003', '007'], 'failed_items': [], 'total_affected_items': 2, 'total_failed_items': 0}} != {'data': {'affected_items': ['003', '005', '007'], 'failed_items': [], 'total_affected_items': 3, 'total_failed_items': 0}}
  Left contains 1 more item:
  {'message': 'Force reconnect command was sent to all agents'}
  Full diff:
    {...
  
  ...Full output truncated (13 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_it...led_items': 0} == {'affected_it...led_items': 0}
  Omitting 2 identical items, use -vv to show
  Differing items:
  {'affected_items': ['003', '007']} != {'affected_items': ['003', '005', '007']}
  {'total_affected_items': 2} != {'total_affected_items': 3}
  Full diff:
    {
  -  'affected_items': ['003', '005', '007'],...
  
  ...Full output truncated (10 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert ['003', '007'] == ['003', '005', '007']
  At index 1 diff: '007' != '005'
  Right contains one more item: '007'
  Full diff:
  - ['003', '005', '007']
  ?         -------
  + ['003', '007']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 512, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(msg) from e
tavern.util.exceptions.KeyMismatchError: List item(s) not present in response: ['005', '007']
```

</details>

We should review and fix this API integration test.

Also, review this possible race condition in the non-RBAC API integration test and RBAC white.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue update

After discussing with the team, we agree that neither doing a refactor to the test nor creating new tests should be done. The solution should be delimiting the time that the agents should take to restart and therefore, updating the delays. To do this, we should also take into account that there should be a tradeoff between increasing delays and having realistic times that the agents should take to restart.

In order to investigate a reasonably new delay for the restart tests, we have been investigating the theoretical time the agent spends in the restart process (from being in an active status -> pending -> active).
First of all, and taking into account the issue https://github.com/wazuh/wazuh/issues/11287, we see that more or less, an agent is restarting for 10 seconds. This measurement has been done in a machine that is faster than the machines used in the Wazuh CI process. Therefore, this time could be used as a lower bound.

Apart from the 10 seconds taken to restart, the cluster synchronization process can take until 20 seconds: 10 of them trying to connect to the worker, and the other 10 seconds waiting for the agent's last keep alive.
After these statements, we can say that 30 is the maximum time spent to restart if the agent is installed in a machine faster than the ones used in the CI process. Therefore, we can say that **for the CI process, 30 could be the minimum time taken by the agent for the restart process** (lower bound).

It would be good to analyze the time spent by agents when talking about the restart process in the machines used in the Wazuh CI. In order to do this, we need the agents' logs left after performing the API integration tests. With these logs, we will be able to measure times and find a possible upper bound that will help us delimitate the new restart delay. This issue is going to be blocked until https://github.com/wazuh/wazuh/issues/11868 is solved (get logs after API integration tests are performed).

**Comment by mcarmona99** [comment]
## Issue update

As we saw in the last comment, we should investigate the time spent by agents when talking about the restart process in the machines used in the Wazuh CI process.
Right now, we know that for a machine with better specs than the ones used in CI (let's call it "usual machine"), the time taken by agents to restart is between 10 and 30 seconds. Theoretically, an agent installed in a machine used in the CI process will take from 30 to x seconds.

| AGENT RESTART PROCESS TIME | Usual | CI  |
|----------------------------|-------|-----|
| Lower bound                | 10s   | 30s |
| Upper bound                | 30s   | ?   |

In order to get a theoretical upper bound for the agent restart process time in the CI machines, I have replicated the test done in https://github.com/wazuh/wazuh/issues/11287#issuecomment-996716137.

> 1. Compiling and installing the version tested.
> 2. For a hundred times:
    1. Register the timestamp before restarting the agent.
    2. Restarting the agent using `service wazuh-agent restart`.
	3. Checking that the agent is connected with the manager searching for the `Active` string executing `/var/ossec/bin/agent_control -i {agent_id}` in the manager.
	4. Register the timestamp after checking that the agent is connected to the manager.
	5. Computing the difference between the timestamps and storing it.
> 3. Computing the mean value from the samples.

**Comment by mcarmona99** [comment]
## Issue update

The test mentioned in the last comment is giving the following result. Each line corresponds to a restart time (in seconds). Mean: 13.076298704147339s

<details>

<summary>100 restart times</summary>

```
14.01034688949585
10.355869054794312
11.237873077392578
10.893492937088013
10.660169839859009
17.360558032989502
9.993370056152344
10.498708009719849
9.958230018615723
10.668905019760132
9.830631971359253
9.796409845352173
11.254255056381226
10.826157093048096
17.09485387802124
73.2650408744812
16.89498782157898
11.110416173934937
10.846472978591919
11.066787958145142
17.632761001586914
9.515780925750732
10.78572702407837
11.098299980163574
10.43852686882019
10.682200908660889
10.32856297492981
8.802289009094238
10.85945200920105
10.735920906066895
17.400306940078735
10.22730302810669
11.368590831756592
11.129431962966919
17.228578805923462
11.068748950958252
11.16109299659729
10.54215693473816
16.93839693069458
11.179038047790527
11.094375848770142
10.702193975448608
17.146942853927612
11.036791801452637
11.278247117996216
10.787765979766846
16.614614963531494
10.763683080673218
9.229532957077026
9.792182922363281
10.71234679222107
10.731912851333618
11.108936071395874
9.424351930618286
11.047705888748169
10.680054903030396
16.95148015022278
11.034360885620117
11.222580909729004
10.467590093612671
11.125306844711304
16.07887101173401
10.61233901977539
10.894137144088745
9.972141981124878
10.573698043823242
11.263699054718018
16.894159078598022
10.86205005645752
11.108033180236816
9.888113021850586
10.423648118972778
11.58090090751648
17.8891179561615
71.73206090927124
9.996973991394043
10.893917083740234
17.240748167037964
10.530763149261475
10.729120969772339
11.065685987472534
17.059067010879517
11.005876064300537
10.631195068359375
9.768493890762329
11.485454082489014
18.146039962768555
9.621906995773315
10.863135814666748
10.736314058303833
11.244800090789795
17.15164804458618
8.917804956436157
10.89143705368042
10.298733949661255
11.00386095046997
10.573662996292114
10.819975137710571
16.973464012145996
10.507158994674683
```

</details>

As we can see, the times are a bit higher in this machine compared to a usual one. However, they are not as high as we expected (we set a lower bound of 30 seconds). In spite of the low time values, we have some values that are much higher than the mean value (71, 73, ...). We could investigate what is happening in these cases as they have to be the ones causing these random errors in the API integration test.

**Comment by mcarmona99** [comment]
## Issue update


In the investigation done in this issue, I talked about possible race conditions here https://github.com/wazuh/wazuh/issues/10914#issuecomment-1017482804 and I talked about the race condition caused by the agent restart process here https://github.com/wazuh/wazuh/issues/10914#issuecomment-1018675890. 

Apart from the possible race condition caused by the restart process, we also have a race condition caused by the reconnect process, as it was reported in the issue's body. The delay set after the reconnect processes could be updated to 60 since it is the maximum reconnect time used in the agents of our environment (default value):

```
...
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
...
```


Returning to the restart times, I have repeated the test done in the last comment. This time the machine used seems to be a bit slower than the one used in the last test, but this must not matter now since the aim of this second test is to see what is happening when high times (70-75) appear.

The 53rd restart took 81 seconds. Let's investigate what happened here.

<details>

<summary>53 restart processes</summary>

```
13.40173602104187s
17.643064975738525s
12.791105031967163s
19.593426942825317s
12.960288047790527s
14.277874946594238s
11.692333936691284s
11.92760705947876s
18.213926792144775s
14.584970951080322s
17.832245111465454s
16.980093955993652s
11.260054111480713s
13.08156418800354s
16.91365909576416s
13.797186851501465s
18.89007806777954s
12.44406509399414s
13.152014017105103s
10.954311847686768s
13.45639705657959s
22.429040908813477s
18.122264862060547s
22.233114004135132s
17.02528214454651s
11.074786901473999s
15.795125007629395s
10.889114141464233s
12.859668016433716s
11.814158201217651s
17.493037939071655s
20.20506000518799s
12.002084970474243s
16.715229034423828s
12.499322891235352s
18.743690967559814s
20.219413995742798s
20.032804012298584s
20.084728002548218s
12.172818899154663s
15.499892950057983s
13.580797910690308s
18.01806902885437s
9.895612001419067s
10.509468078613281s
10.794536828994751s
17.00654911994934s
10.968246936798096s
11.929614067077637s
20.656723976135254s
10.973610877990723s
16.582268953323364s
10.107517957687378s
81.45035696029663s
Restarted in more than 45 seconds (actual delay)!
```

</details>

Note that these restart times are measured from right before the agent is restarted until it is shown as active in the manager.

#### Generic restart

When restarting, the daemons are killed following this order:

```
Killing wazuh-modulesd... 
Killing wazuh-logcollector... 
Killing wazuh-syscheckd... 
Killing wazuh-agentd... 
Killing wazuh-execd... 
```


We can see how these processes are killed in the agent's `ossec.log`:

```
...
2022/01/25 11:08:04 wazuh-modulesd:syscollector[43640] wm_syscollector.c:203 at wm_sys_stop(): INFO: Stop received for Syscollector.
2022/01/25 11:08:04 wazuh-modulesd:syscollector[43640] wm_syscollector.c:191 at wm_sys_main(): INFO: Module finished.
2022/01/25 11:08:04 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 11:08:04 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 11:08:04 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 11:08:04 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2022/01/25 11:08:04 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
```


Right after these logs, the daemons are run again:

```
2022/01/25 11:08:04 wazuh-execd: INFO: Started (pid: 44566).
2022/01/25 11:08:05 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/01/25 11:08:05 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2022/01/25 11:08:05 wazuh-agentd: INFO: Version detected -> Linux |wazuh-agent2 |5.4.0-1029-aws |#30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 |x86_64 [Ubuntu|ubuntu: 20.04.1 LTS (Focal Fossa)] - Wazuh v4.3.0
2022/01/25 11:08:05 wazuh-agentd: INFO: Started (pid: 44584).
...
```

#### Restart that took more than 45 seconds

For the restart process that has taken more than 45 seconds, the following has been logged:


The restart started at **2022-01-25 12:54:37** and took **81.74397206306458s**. In other words, the restart started at **12:54:37** and ended at **12:55:58**.

If we have a look at the logs, the first signal received to kill a daemon was at **12:55:44**.

```
2022/01/25 12:54:30 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2022/01/25 12:54:53 rootcheck: INFO: Ending rootcheck scan.
2022/01/25 12:55:44 wazuh-agentd: WARNING: Server unavailable. Setting lock.
2022/01/25 12:55:44 wazuh-agentd: INFO: Closing connection to server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:55:44 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:55:44 wazuh-agentd: INFO: (4102): Connected to the server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:55:44 wazuh-agentd: INFO: Server responded. Releasing lock.
2022/01/25 12:55:44 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 12:55:45 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 12:55:45 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 12:55:45 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2022/01/25 12:55:45 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
```

After that, the daemons are run again. These are the logs until `12:55:58`:

```
2022/01/25 12:55:45 wazuh-execd: INFO: Started (pid: 191305).
2022/01/25 12:55:46 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/01/25 12:55:46 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2022/01/25 12:55:46 wazuh-agentd: INFO: Version detected -> Linux |wazuh-agent2 |5.4.0-1029-aws |#30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 |x86_64 [Ubuntu|ubuntu: 20.04.1 LTS (Focal Fossa)] - Wazuh v4.3.0
2022/01/25 12:55:46 wazuh-agentd: INFO: Started (pid: 191316).
2022/01/25 12:55:46 wazuh-agentd: INFO: Server IP Address: nginx-lb/172.18.0.3
2022/01/25 12:55:46 wazuh-agentd: INFO: Using AES as encryption method.
2022/01/25 12:55:46 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:55:46 wazuh-agentd: INFO: (4102): Connected to the server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:55:47 wazuh-syscheckd: WARNING: The check_unixaudit option is deprecated in favor of the SCA module.
2022/01/25 12:55:48 wazuh-syscheckd: INFO: Started (pid: 191335).
... (syscheckd info logs)
2022/01/25 12:55:48 rootcheck: INFO: Starting rootcheck scan.
2022/01/25 12:55:49 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2022/01/25 12:55:49 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/dpkg.log'.
2022/01/25 12:55:49 wazuh-logcollector: INFO: Monitoring output of command(360): df -P
2022/01/25 12:55:49 wazuh-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d
2022/01/25 12:55:49 wazuh-logcollector: INFO: Monitoring full output of command(360): last -n 20
2022/01/25 12:55:49 wazuh-logcollector: INFO: Started (pid: 191346).
2022/01/25 12:55:49 wazuh-modulesd: INFO: Started (pid: 191368).
2022/01/25 12:55:49 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2022/01/25 12:55:49 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2022/01/25 12:55:49 sca: INFO: Module started.
2022/01/25 12:55:49 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2022/01/25 12:55:49 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2022/01/25 12:55:49 sca: INFO: Starting Security Configuration Assessment scan.
2022/01/25 12:55:49 wazuh-modulesd:control: INFO: Starting control thread.
2022/01/25 12:55:49 wazuh-modulesd:syscollector: INFO: Module started.
2022/01/25 12:55:49 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/01/25 12:55:49 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2022/01/25 12:55:49 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/01/25 12:55:52 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
```

It seems that there is something wrong if we have a look at the `wazuh-agentd` logs. For a normal restart process, the following is logged:

<details>

<summary>Restart 1</summary>

```
2022/01/25 12:53:58 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 12:53:59 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/01/25 12:53:59 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2022/01/25 12:53:59 wazuh-agentd: INFO: Version detected -> Linux |wazuh-agent2 |5.4.0-1029-aws |#30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 |x86_64 [Ubuntu|ubuntu: 20.04.1 LTS (Focal Fossa)] - Wazuh v4.3.0
2022/01/25 12:53:59 wazuh-agentd: INFO: Started (pid: 188329).
2022/01/25 12:53:59 wazuh-agentd: INFO: Server IP Address: nginx-lb/172.18.0.3
2022/01/25 12:53:59 wazuh-agentd: INFO: Using AES as encryption method.
2022/01/25 12:53:59 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:53:59 wazuh-agentd: INFO: (4102): Connected to the server (nginx-lb/172.18.0.3:1514/tcp).
```

</details>

<details>

<summary>Restart 2</summary>

```
2022/01/25 12:54:10 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 12:54:12 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/01/25 12:54:12 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2022/01/25 12:54:12 wazuh-agentd: INFO: Version detected -> Linux |wazuh-agent2 |5.4.0-1029-aws |#30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 |x86_64 [Ubuntu|ubuntu: 20.04.1 LTS (Focal Fossa)] - Wazuh v4.3.0
2022/01/25 12:54:12 wazuh-agentd: INFO: Started (pid: 188785).
2022/01/25 12:54:12 wazuh-agentd: INFO: Server IP Address: nginx-lb/172.18.0.3
2022/01/25 12:54:12 wazuh-agentd: INFO: Using AES as encryption method.
2022/01/25 12:54:12 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:54:12 wazuh-agentd: INFO: (4102): Connected to the server (nginx-lb/172.18.0.3:1514/tcp).
```

</details>

<details>

<summary>Restart 3 (right before the conflictive restart)</summary>

```
2022/01/25 12:54:23 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 12:54:24 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/01/25 12:54:24 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2022/01/25 12:54:24 wazuh-agentd: INFO: Version detected -> Linux |wazuh-agent2 |5.4.0-1029-aws |#30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 |x86_64 [Ubuntu|ubuntu: 20.04.1 LTS (Focal Fossa)] - Wazuh v4.3.0
2022/01/25 12:54:24 wazuh-agentd: INFO: Started (pid: 189257).
2022/01/25 12:54:24 wazuh-agentd: INFO: Server IP Address: nginx-lb/172.18.0.3
2022/01/25 12:54:24 wazuh-agentd: INFO: Using AES as encryption method.
2022/01/25 12:54:24 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:54:24 wazuh-agentd: INFO: (4102): Connected to the server (nginx-lb/172.18.0.3:1514/tcp).
```

</details>

However, for the case that took more than 45 seconds, this is happening:

```
2022/01/25 12:55:44 wazuh-agentd: WARNING: Server unavailable. Setting lock.
2022/01/25 12:55:44 wazuh-agentd: INFO: Closing connection to server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:55:44 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:55:44 wazuh-agentd: INFO: (4102): Connected to the server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:55:44 wazuh-agentd: INFO: Server responded. Releasing lock.
2022/01/25 12:55:45 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2022/01/25 12:55:46 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/01/25 12:55:46 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2022/01/25 12:55:46 wazuh-agentd: INFO: Version detected -> Linux |wazuh-agent2 |5.4.0-1029-aws |#30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 |x86_64 [Ubuntu|ubuntu: 20.04.1 LTS (Focal Fossa)] - Wazuh v4.3.0
2022/01/25 12:55:46 wazuh-agentd: INFO: Started (pid: 191316).
2022/01/25 12:55:46 wazuh-agentd: INFO: Server IP Address: nginx-lb/172.18.0.3
2022/01/25 12:55:46 wazuh-agentd: INFO: Using AES as encryption method.
2022/01/25 12:55:46 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.18.0.3:1514/tcp).
2022/01/25 12:55:46 wazuh-agentd: INFO: (4102): Connected to the server (nginx-lb/172.18.0.3:1514/tcp).
```

As we can see, before trying to kill the `agentd` process, there is a `WARNING` log and after that, a server reconnection. The `WARNING` log appears 5 minutes after sending the restart command.

Why is this log being displayed?

The log is in the `SERVER_UNAV` variable and can be seen in the following snippet of `src/client-agent/notify.c`:

```
#ifndef ONEWAY_ENABLED
    /* Check if the server has responded */
    if ((curr_time - available_server) > agt->max_time_reconnect_try) {
        /* If response is not available, set lock and wait for it */
        mwarn(SERVER_UNAV);
        os_setwait();
        w_agentd_state_update(UPDATE_STATUS, (void *) GA_STATUS_NACTIVE);

        /* Send sync message */
        start_agent(0);

        minfo(SERVER_UP);
        os_delwait();
        w_agentd_state_update(UPDATE_STATUS, (void *) GA_STATUS_ACTIVE);
    }
#endif
```

The following may have happened: the agent was connected to the manager but as the WARNING log indicates, there was no response from the server.
`max_time_reconnect_try` is 60 by default (this can be seen in the agents' `ossec.conf` as it corresponds to the `time-reconnect` value). After those 60 seconds without a response, the agent is reconnected. In the meantime, the restart petition is enqueued which means that the restart petition was sent, but the agent does not restart until it is reconnected to the server.

Once the agent is reconnected (at 12:55:44, 67 seconds after the restart petition was sent), the restart process starts, taking between 15 and 20 seconds, as was commented above.

**12:55:58 - 12:54:37 = 81 secs (reconnection + restart )**


Right now, our delay has a value of 45. This delay is not covering the case I have just mentioned. The solution would be a new tavern function to verify the response with a dynamic delay. This dynamic delay, also considered a health check, will check in the agents' ossec.log if the **agentd** log indicating the daemon was killed is present after the timestamp where the petition to restart was sent. Apart from the dynamic delay, a static delay must be considered as after the possible race condition caused by this reconnection, the agents need time to restart (actual delay).

The delay used for the reconnect endpoints tests will also be removed in favor of a dynamic delay, looking for the `Closing connection` and `Connected to server` logs.
