### ISSUE TITLE
Investigate API timeout in RBAC white active response API integration test

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#11181]
|Wazuh version|Component|
|---|---|
| 4.4.0 | API Integration Test |

We have found a random error in one of our API integration tests.

The `test_rbac_white_active_response_endpoints` test is failing due to an API timeout.

Report:

<details>

<summary>pytest output</summary>

```
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.5', 'Platform': 'Linux-5.4.0-1029-aws-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.9.0', 'pluggy': '0.13.1'}, 'Plugins': {'tavern': '1.0.0', 'metadata': '1.10.0', 'html': '2.0.1'}}
rootdir: /tmp/Test_integration_endpoints_B1671_test_files/api/test/integration, inifile: pytest.ini
plugins: tavern-1.0.0, metadata-1.10.0, html-2.0.1
collecting ... collected 2 items

test_rbac_white_active_response_endpoints.tavern.yaml::PUT ACTIVE-RESPONSE OVER A LIST OF AGENTS FAILED [ 50%]
test_rbac_white_active_response_endpoints.tavern.yaml::PUT /active-response FAILED [100%]

=================================== FAILURES ===================================
_ /tmp/Test_integration_endpoints_B1671_test_files/api/test/integration/test_rbac_white_active_response_endpoints.tavern.yaml::PUT ACTIVE-RESPONSE OVER A LIST OF AGENTS _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM4MjI3MDA0LCJleHAiOjE2MzgyMjc5MDQsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbOTldLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AbZ1eZSDhQTB6y0HKDWZDoQjGuT0ZxroUk7ecv3LdZ0HhxpMLRT7diIK8RItnUWF3LNhDNAMhT8IOP_JHX957GDKAXj-wEGWiMyr8JVz_mK-GhzfgK1bsD8---z9BLTK9dd_uIfohr09UEBEaIf6ZjpKm13CCaMxT69xaUsPDGvGugK8'

Source test stage (line 53):
  - name: Send a message to a list of agents
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/active-response"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
        content-type: application/json
      json:
        command: "custom"
        custom: True
      params:
        agents_list: 002,004,005,007,010,011
    response:
      status_code: 200
      json:
        error: 2
        data:
          affected_items:
            - '004'
            - '007'
          failed_items:
            - error:
                code: 1707
              id:
                - '011'
            - error:
                code: 4000
              id:
                - '002'
                - '005'
                - '010'
          total_affected_items: 2
          total_failed_items: 4


Formatted stage:
  name: Send a message to a list of agents
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM4MjI3MDA0LCJleHAiOjE2MzgyMjc5MDQsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbOTldLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AbZ1eZSDhQTB6y0HKDWZDoQjGuT0ZxroUk7ecv3LdZ0HhxpMLRT7diIK8RItnUWF3LNhDNAMhT8IOP_JHX957GDKAXj-wEGWiMyr8JVz_mK-GhzfgK1bsD8---z9BLTK9dd_uIfohr09UEBEaIf6ZjpKm13CCaMxT69xaUsPDGvGugK8
      content-type: application/json
    json:
      command: custom
      custom: true
    method: PUT
    params:
      agents_list: 002,004,005,007,010,011
    url: 'https://localhost:55000/active-response'
    verify: false
  response:
    json:
      data:
        affected_items:
        - '004'
        - '007'
        failed_items:
        - error:
            code: 1707
          id:
          - '011'
        - error:
            code: 4000
          id:
          - '002'
          - '005'
          - '010'
        total_affected_items: 2
        total_failed_items: 4
      error: 2
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Send a message to a list of agents' failed:
    - Status code was 500, expected 200
    - Structure of returned data was different than expected  - Extra keys in response: {'title', 'dapi_errors', 'detail'} - Keys missing from response: {'data'} (expected = '{'error': 2, 'data': {'affected_items': ['004', '007'], 'failed_items': [{'error': {'code': 1707}, 'id': ['011']}, {'error': {'code': 4000}, 'id': ['002', '005', '010']}], 'total_affected_items': 2, 'total_failed_items': 4}}' (type = <class 'dict'>), actual = '{'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/cluster.log'}}, 'error': 3021}' (type = <class 'dict'>))
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '403'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:43 Status code was 500, expected 200
ERROR    tavern.response.base:base.py:41 Structure of returned data was different than expected  - Extra keys in response: {'title', 'dapi_errors', 'detail'} - Keys missing from response: {'data'} (expected = '{'error': 2, 'data': {'affected_items': ['004', '007'], 'failed_items': [{'error': {'code': 1707}, 'id': ['011']}, {'error': {'code': 4000}, 'id': ['002', '005', '010']}], 'total_affected_items': 2, 'total_failed_items': 4}}' (type = <class 'dict'>), actual = '{'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/cluster.log'}}, 'error': 3021}' (type = <class 'dict'>))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request',\n                                  'logfile': 'WAZUH_HOME/logs/cluster.log'}},\n 'detail': 'Timeout executing API request',\n 'error': 3021,\n 'title': 'Wazuh Internal Error'} == {'data': {'affected_items': ['004', '007'],\n          'failed_items': [{'error': {'code': 1707}, 'id': ['011']},\n                           {'error': {'code': 4000},\n                            'id': ['002', '005', '010']}],\n          'total_affected_items': 2,\n          'total_failed_items': 4},\n 'error': 2}
  Differing items:
  {'error': 3021} != {'error': 2}
  Left contains 3 more items:
  {'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request',
                                    'logfile': 'WAZUH_HOME/logs/cluster.log'}},
   'detail': 'Timeout executing API request',
   'title': 'Wazuh Internal Error'}
  Right contains 1 more item:
  {'data': {'affected_items': ['004', '007'],
            'failed_items': [{'error': {'code': 1707}, 'id': ['011']},
                             {'error': {'code': 4000},
                              'id': ['002', '005', '010']}],
            'total_affected_items': 2,
            'total_failed_items': 4}}
  Full diff:
    {
  +  'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request',
  +                                   'logfile': 'WAZUH_HOME/logs/cluster.log'}},
  +  'detail': 'Timeout executing API request',
  -  'data': {'affected_items': ['004',
  -                              '007'],
  -           'failed_items': [{'error': {'code': 1707},
  -                             'id': ['011']},
  -                            {'error': {'code': 4000},
  -                             'id': ['002',
  -                                    '005',
  -                                    '010']}],
  -           'total_affected_items': 2,
  -           'total_failed_items': 4},
  -  'error': 2,
  +  'error': 3021,
  ?           ++ +
  +  'title': 'Wazuh Internal Error',
    }

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 447, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(full_msg) from e
tavern.util.exceptions.KeyMismatchError: Structure of returned data was different than expected  - Extra keys in response: {'title', 'dapi_errors', 'detail'} - Keys missing from response: {'data'} (expected = '{'error': 2, 'data': {'affected_items': ['004', '007'], 'failed_items': [{'error': {'code': 1707}, 'id': ['011']}, {'error': {'code': 4000}, 'id': ['002', '005', '010']}], 'total_affected_items': 2, 'total_failed_items': 4}}' (type = <class 'dict'>), actual = '{'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/cluster.log'}}, 'error': 3021}' (type = <class 'dict'>))
_ /tmp/Test_integration_endpoints_B1671_test_files/api/test/integration/test_rbac_white_active_response_endpoints.tavern.yaml::PUT /active-response _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM4MjI3MDE1LCJleHAiOjE2MzgyMjc5MTUsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbOTldLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AUDgX_0Fq5lLCgZ9y3Mw83O0vV9NkSySNuRECzS1vcuAIjTZRPr6aG351ueuJPBInzpecUCmmfAxb5zpSWwcevVwAeapb0l3BPDUxoo3TTo5Uu7LuEEriPWdDmFmiM4mozv4aEE5qVbvxYIH1tBvssuh1WjCebvYlC3OKuXRH2-r6EXC'

Source test stage (line 137):
  - name: Runs an Active Response command on all agents
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/active-response"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
        content-type: application/json
      json:
        command: "restart-wazuh0"
        arguments: ["-", "null", "(from_the_server)", "(no_rule_id)"]
    response:
      status_code: 200
      json:
        error: 2
        data:
          affected_items: !anything
          failed_items:
            - error:
                code: 1707
              id:
                - '009'
                - '011'
            - error:
                code: 1750
              id:
                - '003'
          total_affected_items: 3
          total_failed_items: 3

Formatted stage:
  name: Runs an Active Response command on all agents
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM4MjI3MDE1LCJleHAiOjE2MzgyMjc5MTUsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbOTldLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AUDgX_0Fq5lLCgZ9y3Mw83O0vV9NkSySNuRECzS1vcuAIjTZRPr6aG351ueuJPBInzpecUCmmfAxb5zpSWwcevVwAeapb0l3BPDUxoo3TTo5Uu7LuEEriPWdDmFmiM4mozv4aEE5qVbvxYIH1tBvssuh1WjCebvYlC3OKuXRH2-r6EXC
      content-type: application/json
    json:
      arguments:
      - '-'
      - 'null'
      - (from_the_server)
      - (no_rule_id)
      command: restart-wazuh0
    method: PUT
    url: 'https://localhost:55000/active-response'
    verify: false
  response:
    json:
      data:
        affected_items: !anything ''
        failed_items:
        - error:
            code: 1707
          id:
          - 009
          - '011'
        - error:
            code: 1750
          id:
          - '003'
        total_affected_items: 3
        total_failed_items: 3
      error: 2
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Runs an Active Response command on all agents' failed:
    - Status code was 500, expected 200
    - Structure of returned data was different than expected  - Extra keys in response: {'title', 'dapi_errors', 'detail'} - Keys missing from response: {'data'} (expected = '{'error': 2, 'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f4fe990a430>, 'failed_items': [{'error': {'code': 1707}, 'id': ['009', '011']}, {'error': {'code': 1750}, 'id': ['003']}], 'total_affected_items': 3, 'total_failed_items': 3}}' (type = <class 'dict'>), actual = '{'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/cluster.log'}}, 'error': 3021}' (type = <class 'dict'>))
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:43 Status code was 500, expected 200
ERROR    tavern.response.base:base.py:41 Structure of returned data was different than expected  - Extra keys in response: {'title', 'dapi_errors', 'detail'} - Keys missing from response: {'data'} (expected = '{'error': 2, 'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f4fe990a430>, 'failed_items': [{'error': {'code': 1707}, 'id': ['009', '011']}, {'error': {'code': 1750}, 'id': ['003']}], 'total_affected_items': 3, 'total_failed_items': 3}}' (type = <class 'dict'>), actual = '{'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/cluster.log'}}, 'error': 3021}' (type = <class 'dict'>))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request',\n                                  'logfile': 'WAZUH_HOME/logs/cluster.log'}},\n 'detail': 'Timeout executing API request',\n 'error': 3021,\n 'title': 'Wazuh Internal Error'} == {'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f4fe990a430>,\n          'failed_items': [{'error': {'code': 1707}, 'id': ['009', '011']},\n                           {'error': {'code': 1750}, 'id': ['003']}],\n          'total_affected_items': 3,\n          'total_failed_items': 3},\n 'error': 2}
  Differing items:
  {'error': 3021} != {'error': 2}
  Left contains 3 more items:
  {'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request',
                                    'logfile': 'WAZUH_HOME/logs/cluster.log'}},
   'detail': 'Timeout executing API request',
   'title': 'Wazuh Internal Error'}
  Right contains 1 more item:
  {'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f4fe990a430>,
            'failed_items': [{'error': {'code': 1707}, 'id': ['009', '011']},
                             {'error': {'code': 1750}, 'id': ['003']}],
            'total_affected_items': 3,
            'total_failed_items': 3}}
  Full diff:
    {
  +  'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request',
  +                                   'logfile': 'WAZUH_HOME/logs/cluster.log'}},
  +  'detail': 'Timeout executing API request',
  -  'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f4fe990a430>,
  -           'failed_items': [{'error': {'code': 1707},
  -                             'id': ['009',
  -                                    '011']},
  -                            {'error': {'code': 1750},
  -                             'id': ['003']}],
  -           'total_affected_items': 3,
  -           'total_failed_items': 3},
  -  'error': 2,
  +  'error': 3021,
  ?           ++ +
  +  'title': 'Wazuh Internal Error',
    }

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 447, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(full_msg) from e
tavern.util.exceptions.KeyMismatchError: Structure of returned data was different than expected  - Extra keys in response: {'title', 'dapi_errors', 'detail'} - Keys missing from response: {'data'} (expected = '{'error': 2, 'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7f4fe990a430>, 'failed_items': [{'error': {'code': 1707}, 'id': ['009', '011']}, {'error': {'code': 1750}, 'id': ['003']}], 'total_affected_items': 3, 'total_failed_items': 3}}' (type = <class 'dict'>), actual = '{'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'unknown-node': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/cluster.log'}}, 'error': 3021}' (type = <class 'dict'>))
=============================== warnings summary ===============================
/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/hooks.py:83
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/hooks.py:83: PytestDeprecationWarning: direct construction of YamlFile has been deprecated, please use YamlFile.from_parent
    return YamlFile(path, parent)

/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:233
/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:233
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:233: PytestDeprecationWarning: direct construction of YamlItem has been deprecated, please use YamlItem.from_parent
    item = YamlItem(test_spec["test_name"], self, test_spec, self.fspath)

/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:61
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:61: PytestUnknownMarkWarning: Unknown pytest.mark.rbac_tests - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    pytest_marks.append(getattr(pytest.mark, m))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
- generated html file: file:///tmp/Test_integration_endpoints_B1671_test_files/api/test/integration/Test_integration_endpoints_B1671_test_rbac_white_active_response_endpoints.html -
=========================== short test summary info ============================
FAILED test_rbac_white_active_response_endpoints.tavern.yaml::PUT ACTIVE-RESPONSE OVER A LIST OF AGENTS
FAILED test_rbac_white_active_response_endpoints.tavern.yaml::PUT /active-response
================== 2 failed, 4 warnings in 260.63s (0:04:20) ===================
```

</details>

Logs:

[Test_integration_endpoints_B1671_test_rbac_white_active_response_endpoints_logs.zip](https://github.com/wazuh/wazuh/files/7649100/Test_integration_endpoints_B1671_test_rbac_white_active_response_endpoints_logs.1.zip)

The timeout mentioned can be seen in the api.log:

<details>

<summary>api.log</summary>

```
2021/11/29 23:00:18 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2021/11/29 23:00:19 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key
2021/11/29 23:00:19 INFO: Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt
2021/11/29 23:02:42 INFO: Listening on 0.0.0.0:55000..
2021/11/29 23:02:47 INFO: testing 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 2.655s: 200
2021/11/29 23:03:24 INFO: testing 172.20.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.516s: 200
2021/11/29 23:03:24 INFO: testing 172.20.0.1 "PUT /active-response" with parameters {"agents_list": "001"} and body {"command": "custom", "custom": true} done in 0.063s: 200
2021/11/29 23:03:24 INFO: testing 172.20.0.1 "PUT /active-response" with parameters {"agents_list": "002"} and body {"command": "restart-wazuh0", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"]} done in 0.043s: 403
2021/11/29 23:03:34 INFO: testing 172.20.0.1 "PUT /active-response" with parameters {"agents_list": "002,004,005,007,010,011"} and body {"command": "custom", "custom": true} done in 10.050s: 500
2021/11/29 23:03:35 INFO: testing 172.20.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.728s: 200
2021/11/29 23:03:45 INFO: testing 172.20.0.1 "PUT /active-response" with parameters {} and body {"command": "restart-wazuh0", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"]} done in 10.052s: 500
```

</details>

We should investigate the origin of this error and try to fix it.

NOTE: this issue was created after the merge of https://github.com/wazuh/wazuh/pull/10925 so no xfail marks are added to the API integration test cases related to this issue.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue update

The test is failing because the agent with ID 005 is not in the response and it should be. This agent may not be in the response because it is not active (we don't know this as the code related to non-active agents is excluded) as it was reconnected in the test case before this one. The test case that failed is the PUT /agents/reconnect test case.

First of all, we could think that this agent was not active from the beginning of the test.
The test case that failed was the one trying to reconnect agent 005. If agent 005 were not active from the beginning, a test before the one failing must have failed before. Let's check this.

Test cases working with agent with ID 005:

_**GET /agents -> the agent status is not tested
GET /agents/{agent_id}/key -> the agent status is not tested
GET /agents/outdated -> the agent status is not tested
DELETE /agents/{agent_id}/group/{group_id} -> the agent status is not tested
DELETE /agents/{agent_id}/group -> the agent status is not tested
PUT /agents/group?group_id={group_id} -> the agent status is not tested
PUT /agents/group/{group_id}/restart -> THE AGENT STATUS IS TESTED. This test would have failed if the agent was not active from the beginning.
...**_

We see that the agent was active when the test started because if not, the test would have failed before the PUT /agents/reconnect test case. Therefore, we discard the problem fixed in https://github.com/wazuh/wazuh/issues/10913 being the issue here.

As we saw above, there is a `PUT /agents/group/{group_id}/restart` endpoint test. This test case happens right before the `PUT /agents/reconnect` test, which is the one failing. In spite of the delay, the agent that was restarting could have a status different to active by the time the request to reconnect that agent is done.

To avoid this possible race condition, we could change the `PUT /agents/group/{group_id}/restart` endpoint test position so the request is done after the reconnect request.
This change will avoid a possible race condition but in fact, there are still a lot of race conditions with this agent's status since 005 is the only agent being restarted and reconnected. To improve this and avoid all the known race conditions, we could restart and/or reconnect a different agent each time. This will mean changes to the RBAC permissions.


The following agent IDs are used in actions for which delays are needed: 005, 009, 002, 006, 008, 010, 012.

The following agents are assigned to `group1`. Therefore, a restart due to configuration changes is needed: 009, 005.

`group1` configuration is updated. Therefore, a restart due to configuration changes is needed. This time, the `restart_delay` is not in the test. Adding it. This test case is also moved after the reconnect endpoint.

Agent 005 is reconnected, reconnected again (with 003 and 007), restarted due to conf changes, restarted because it is un group2, restarted, restarted again (with 003 and 007), restarted again, and restarted again when trying to restart agents in the three nodes.

As we can see, there is a really high probability for agent 005 to be non-active in one of these tests (and therefore, there is a high probability for the test to fail). We should consider changes on the RBAC permissions to restart different agents each time (as it was said before) (this will mean a refactor of this whole test), or creating new tests to separate these test cases.

Note that the test_agents and test_RBAC_black_agents should also be reviewed.

**Comment by vicferpoy** [comment]
# Issue update

After analyzing the code and errors from the logs, I believe there is no possible fix right now given the circunstances as we cannot reproduce it (it only happened once) and the information is not enough.

Normally, when the Wazuh API returns a timeout, it is logged in the `api.log`. In this case, the response was a timeout error but it was not logged:

```json
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master-node": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "error": 3021
}
```

```shellsession
2021/11/29 23:00:18 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2021/11/29 23:00:19 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key
2021/11/29 23:00:19 INFO: Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt
2021/11/29 23:02:42 INFO: Listening on 0.0.0.0:55000..
2021/11/29 23:02:47 INFO: testing 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 2.655s: 200
2021/11/29 23:03:24 INFO: testing 172.20.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.516s: 200
2021/11/29 23:03:24 INFO: testing 172.20.0.1 "PUT /active-response" with parameters {"agents_list": "001"} and body {"command": "custom", "custom": true} done in 0.063s: 200
2021/11/29 23:03:24 INFO: testing 172.20.0.1 "PUT /active-response" with parameters {"agents_list": "002"} and body {"command": "restart-wazuh0", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"]} done in 0.043s: 403
2021/11/29 23:03:34 INFO: testing 172.20.0.1 "PUT /active-response" with parameters {"agents_list": "002,004,005,007,010,011"} and body {"command": "custom", "custom": true} done in 10.050s: 500
2021/11/29 23:03:35 INFO: testing 172.20.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.728s: 200
2021/11/29 23:03:45 INFO: testing 172.20.0.1 "PUT /active-response" with parameters {} and body {"command": "restart-wazuh0", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"]} done in 10.052s: 500

```

This should be the `api.log` when the API timeouts:

```shellsession
2022/01/20 12:49:27 ERROR: Timeout executing API request
2022/01/20 12:49:27 INFO: wazuh 172.27.0.1 "PUT /active-response" with parameters {} and body {"arguments": ["string"], "command": "string", "custom": true, "alert": {"data": {}}} done in 10.055s: 500
```

That `ERROR` log entry is raised here (line 189):

https://github.com/wazuh/wazuh/blob/0e2da8a7ed14c5f92889d54ea42a845a4b456f6b/framework/wazuh/core/cluster/dapi/dapi.py#L175-L197

Considering that only `WazuhInternalErrors` do that, it means that whenever a timeout occurs on a worker node, it is captured here and raised as a `WazuhClusterError`, which inherits from `WazuhError`:

https://github.com/wazuh/wazuh/blob/0e2da8a7ed14c5f92889d54ea42a845a4b456f6b/framework/wazuh/core/cluster/master.py#L288-L296

This is related to https://github.com/wazuh/wazuh/issues/10364, but we should also study that code block as I believe we could not be handling that exception correctly. In addition to that, the `logfile` refers to `cluster.log`, which confirms that there was a timeout on one of the worker nodes.

To understand what could have happened, we would need the workers cluster logs, but that feature was later added in https://github.com/wazuh/wazuh/pull/11456. In my opinion, this issue should be closed and if this occurs again, a new issue with all the necessary information will be opened.

Regards,
Víctor

**Comment by Kondent** [comment]
LGTM
