### ISSUE TITLE
Error deploying Wazuh 4.3.0 in Bosh environment

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh#11265]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.0-rc1 | wazuh-clusterd | Manager | Sources | Ubuntu Bionic |

### Description:
Wazuh-clusterd is not starting in the manager/worker nodes. This is working with v4.2.5. The `wazuh-bosh` repository was bumped to 4.3.0 in order to test the install procedure.

The packages were generated from tag `v4.3.0-rc1` and uploaded to `packages-dev` bucket:
`https://packages-dev.wazuh.com/bosh/wazuh-manager-4.3.0.tar.gz`

The `wazuh-clusterd` daemon was started with the debug flag and these are the logs:
```
./bin/wazuh-clusterd -dd
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/wazuh-clusterd.py", line 15, in <module>
    from wazuh.core.utils import check_pid
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/__init__.py", line 10, in <module>
    from wazuh.core import common
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/common.py", line 228, in <module>
    cache_event = Event()
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/context.py", line 93, in Event
    return Event(ctx=self.get_context())
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/synchronize.py", line 324, in __init__
    self._cond = ctx.Condition(ctx.Lock())
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory
```

If the `-r` (run as root) flag is added it starts without errors. These are the complete logs included both scenarios (with and without root):
[cluster.log](https://github.com/wazuh/wazuh/files/7684969/cluster.log)

Seems like a permissions error for the `wazuh` user. 

The installation was tested manually (without Bosh) with the generated tar file in a fresh Ubuntu Bionic and it works fine.

**Comment by teddytpc1** [comment]
Hi @AdriiiPRodri.
This is the update after the changes we tested today.
1. A new 4.3.0 environment was deployed with Bosh.
2. The `wazuh-clusterd` daemon failed to start:
```
/var/ossec/bin/wazuh-clusterd -fdd
2021/12/13 17:44:12 DEBUG: [Cluster] [Main] Removing '/var/ossec/queue/cluster/'.
2021/12/13 17:44:12 DEBUG: [Cluster] [Main] Removed '/var/ossec/queue/cluster/'.
Starting cluster in foreground (pid: 10664)
2021/12/13 17:44:14 ERROR: [Cluster] [Main] Unhandled exception: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/wazuh-clusterd.py", line 199, in <module>
    asyncio.run(main_function(args, cluster_configuration, cluster_items, main_logger))
  File "/var/ossec/framework/python/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/ossec/framework/scripts/wazuh-clusterd.py", line 72, in master_main
    from wazuh.core.cluster import master, local_server
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/master.py", line 23, in <module>
    from wazuh.core.cluster.dapi import dapi
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 34, in <module>
    process_pool = ProcessPoolExecutor(max_workers=1)
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 642, in __init__
    self._call_queue = _SafeQueue(
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/queues.py", line 43, in __init__
    self._rlock = ctx.Lock()
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory
```
3. The `/dev/shm` directory permissions was changed from:
```
drwxrwx---  2 root vcap   40 Dec 13 17:44 .
```

To:
```
drwxrwxrwx  2 root vcap   40 Dec 13 17:44 .
```

4. The daemon was restarted again and started successfully:
```
/var/ossec/bin/wazuh-clusterd -fdd
2021/12/13 17:44:58 DEBUG: [Cluster] [Main] Removing '/var/ossec/queue/cluster/'.
2021/12/13 17:44:58 DEBUG: [Cluster] [Main] Removed '/var/ossec/queue/cluster/'.
Starting cluster in foreground (pid: 10686)
2021/12/13 17:45:00 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2021/12/13 17:45:00 DEBUG: [Local Server] [Keep alive] Calculating.
2021/12/13 17:45:00 DEBUG: [Local Server] [Keep alive] Calculated.
2021/12/13 17:45:00 INFO: [Master] [Main] Serving on ('0.0.0.0', 1516)
2021/12/13 17:45:00 DEBUG: [Master] [Keep alive] Calculating.
2021/12/13 17:45:00 DEBUG: [Master] [Keep alive] Calculated.
2021/12/13 17:45:00 INFO: [Master] [Local integrity] Starting.
2021/12/13 17:45:00 INFO: [Master] [Local integrity] Finished in 0.028s. Calculated metadata of 34 files.
2021/12/13 17:45:08 INFO: [Master] [Local integrity] Starting.
2021/12/13 17:45:08 INFO: [Master] [Local integrity] Finished in 0.009s. Calculated metadata of 34 files.
```

A final test will be executed updating the `wazuh-manager` `pre-start` script to add the `chmod` command to change the `/dev/shm` directory permissions.

**Comment by AdriiiPRodri** [comment]
Hello @teddytpc1,

I think it is a solution to test the new developments related to multiprocessing.

However, since there is a possibility that some user has the `fs.protected_regular` policy with value `1` or for any other reason cannot make use of `/dev/shm`, we are going to create a mechanism on the API and Cluster side to disable multiprocessing and display a warning message.

**Comment by davidjiglesias** [comment]
To be tested and fixed in https://github.com/wazuh/wazuh/issues/11347
