### ISSUE TITLE
Memory leaks found in Vulnerability Detector

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#11305]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-RC1 | Vulnerability Detector | Manager | Sources | Linux |

## Configuration

```xml
<ossec_config>
  <vulnerability-detector>
    <enabled>yes</enabled>

    <!-- RedHat OS vulnerabilities -->
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <update_interval>1h</update_interval>
    </provider>
  </vulnerability-detector>
</ossec_config>
```

## Report

- [ ] Direct leak of 54352 byte(s) in 1097 object(s) allocated from:
```
    #0 0x7fde80029c18 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:164
    #1 0x55c8f03eae28 in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3786
    #2 0x55c8f03e6d0d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3623
    #3 0x55c8f03f0f6d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4009
    #4 0x55c8f03f15f7 in wm_vuldet_oval_process wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4058
    #5 0x55c8f03f24c6 in wm_vuldet_index_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4173
    #6 0x55c8f03c7577 in wm_vuldet_sync_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:649
    #7 0x55c8f03de21f in wm_vuldet_update_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2667
    #8 0x55c8f03f4fd6 in wm_vuldet_check_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4504
    #9 0x55c8f03f5b71 in wm_vuldet_run_update wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4604
    #10 0x55c8f03fc9e1 in wm_vuldet_main wazuh_modules/vulnerability_detector/wm_vuln_detector.c:5129
    #11 0x7fde7f4ab926 in start_thread nptl/pthread_create.c:435
```
- [ ] Direct leak of 464 byte(s) in 29 object(s) allocated from:
```
    #0 0x7fde80029a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x55c8f03ea595 in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3771
    #2 0x55c8f03e6d0d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3623
    #3 0x55c8f03f0f6d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4009
    #4 0x55c8f03f15f7 in wm_vuldet_oval_process wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4058
    #5 0x55c8f03f24c6 in wm_vuldet_index_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4173
    #6 0x55c8f03c7577 in wm_vuldet_sync_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:649
    #7 0x55c8f03de21f in wm_vuldet_update_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2667
    #8 0x55c8f03f4fd6 in wm_vuldet_check_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4504
    #9 0x55c8f03f5b71 in wm_vuldet_run_update wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4604
    #10 0x55c8f03fc9e1 in wm_vuldet_main wazuh_modules/vulnerability_detector/wm_vuln_detector.c:5129
    #11 0x7fde7f4ab926 in start_thread nptl/pthread_create.c:435
```
- [ ] Direct leak of 185 byte(s) in 5 object(s) allocated from:
```
    #0 0x7fde7ffd09a7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55c8f03ee5e1 in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3939
    #2 0x55c8f03ed9ac in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3895
    #3 0x55c8f03ed84b in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3887
    #4 0x55c8f03ed9ac in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3895
    #5 0x55c8f03ed84b in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3887
    #6 0x55c8f03ec047 in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3830
    #7 0x55c8f03f0f6d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4009
    #8 0x55c8f03f15f7 in wm_vuldet_oval_process wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4058
    #9 0x55c8f03f24c6 in wm_vuldet_index_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4173
    #10 0x55c8f03c7577 in wm_vuldet_sync_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:649
    #11 0x55c8f03de21f in wm_vuldet_update_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2667
    #12 0x55c8f03f4fd6 in wm_vuldet_check_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4504
    #13 0x55c8f03f5b71 in wm_vuldet_run_update wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4604
    #14 0x55c8f03fc9e1 in wm_vuldet_main wazuh_modules/vulnerability_detector/wm_vuln_detector.c:5129
    #15 0x7fde7f4ab926 in start_thread nptl/pthread_create.c:435
```
- [ ] Direct leak of 185 byte(s) in 5 object(s) allocated from:
```
    #0 0x7fde7ffd09a7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55c8f03ee5e1 in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3939
    #2 0x55c8f03ed84b in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3887
    #3 0x55c8f03ec047 in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3830
    #4 0x55c8f03f0f6d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4009
    #5 0x55c8f03f15f7 in wm_vuldet_oval_process wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4058
    #6 0x55c8f03f24c6 in wm_vuldet_index_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4173
    #7 0x55c8f03c7577 in wm_vuldet_sync_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:649
    #8 0x55c8f03de21f in wm_vuldet_update_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2667
    #9 0x55c8f03f4fd6 in wm_vuldet_check_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4504
    #10 0x55c8f03f5b71 in wm_vuldet_run_update wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4604
    #11 0x55c8f03fc9e1 in wm_vuldet_main wazuh_modules/vulnerability_detector/wm_vuln_detector.c:5129
    #12 0x7fde7f4ab926 in start_thread nptl/pthread_create.c:435
```
- [ ] Direct leak of 185 byte(s) in 5 object(s) allocated from:
```
    #0 0x7fde7ffd09a7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55c8f03ee5e1 in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3939
    #2 0x55c8f03ed9ac in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3895
    #3 0x55c8f03ed84b in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3887
    #4 0x55c8f03ec047 in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3830
    #5 0x55c8f03f0f6d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4009
    #6 0x55c8f03f15f7 in wm_vuldet_oval_process wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4058
    #7 0x55c8f03f24c6 in wm_vuldet_index_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4173
    #8 0x55c8f03c7577 in wm_vuldet_sync_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:649
    #9 0x55c8f03de21f in wm_vuldet_update_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2667
    #10 0x55c8f03f4fd6 in wm_vuldet_check_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4504
    #11 0x55c8f03f5b71 in wm_vuldet_run_update wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4604
    #12 0x55c8f03fc9e1 in wm_vuldet_main wazuh_modules/vulnerability_detector/wm_vuln_detector.c:5129
    #13 0x7fde7f4ab926 in start_thread nptl/pthread_create.c:435
```
- [ ] Indirect leak of 31691 byte(s) in 5697 object(s) allocated from:
```
    #0 0x7fde7ffd09a7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55c8f03eaf9a in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3787
    #2 0x55c8f03e6d0d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3623
    #3 0x55c8f03f0f6d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4009
    #4 0x55c8f03f15f7 in wm_vuldet_oval_process wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4058
    #5 0x55c8f03f24c6 in wm_vuldet_index_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4173
    #6 0x55c8f03c7577 in wm_vuldet_sync_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:649
    #7 0x55c8f03de21f in wm_vuldet_update_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2667
    #8 0x55c8f03f4fd6 in wm_vuldet_check_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4504
    #9 0x55c8f03f5b71 in wm_vuldet_run_update wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4604
    #10 0x55c8f03fc9e1 in wm_vuldet_main wazuh_modules/vulnerability_detector/wm_vuln_detector.c:5129
    #11 0x7fde7f4ab926 in start_thread nptl/pthread_create.c:435
```
- [ ] Indirect leak of 200 byte(s) in 29 object(s) allocated from:
```
    #0 0x7fde7ffd09a7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55c8f03ea98a in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3776
    #2 0x55c8f03e6d0d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3623
    #3 0x55c8f03f0f6d in wm_vuldet_oval_xml_parser wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4009
    #4 0x55c8f03f15f7 in wm_vuldet_oval_process wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4058
    #5 0x55c8f03f24c6 in wm_vuldet_index_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4173
    #6 0x55c8f03c7577 in wm_vuldet_sync_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:649
    #7 0x55c8f03de21f in wm_vuldet_update_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2667
    #8 0x55c8f03f4fd6 in wm_vuldet_check_feed wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4504
    #9 0x55c8f03f5b71 in wm_vuldet_run_update wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4604
    #10 0x55c8f03fc9e1 in wm_vuldet_main wazuh_modules/vulnerability_detector/wm_vuln_detector.c:5129
    #11 0x7fde7f4ab926 in start_thread nptl/pthread_create.c:435
```

### Summary

AddressSanitizer: 87262 byte(s) leaked in 6867 allocation(s).

**Comment by alromeros** [comment]
**#11305 Update:**

Hi team,

After gathering information and testing _Vulnerability Detector_ with various code analyzers, we've come to the conclusion that the described memory leaks seem to be false positives.

#### Memory analysis:

The module has been tested with _Valgrind_ and _Address Sanitizer_, both with custom feeds and with **Red Hat**'s official feeds.

Both tools show reports with no "definitely lost" leaks, as shown in this _Valgrind_ sample:

>==193375== LEAK SUMMARY:
==193375==    definitely lost: 0 bytes in 0 blocks
==193375==    indirectly lost: 0 bytes in 0 blocks
==193375==      possibly lost: 3,824 bytes in 14 blocks
==193375==    still reachable: 2,082,028 bytes in 36,059 blocks
==193375==         suppressed: 0 bytes in 0 blocks
==193375== Reachable blocks (those to which a pointer was found) are not shown.

#### Static analysis:

Static analysis has also been tested with Scan-build, Coverity, and manually, showing no anomalous reports in the affected module.

This behavior leads us to think that there are no unidentified memory leaks in the functions described in the issue.

Best regards.
