### ISSUE TITLE
Database is locked (sqlite3 OperationalError) in cluster

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#11556]
|Wazuh version|Component|
|---|---|
| 4.3 | Cluster |

## Description

The following error in the cluster was found and reported by @alberpilot :
```
cat /var/ossec/logs/cluster.log 
2021/12/26 07:59:12 ERROR: [Cluster] [Main] Unhandled exception: (sqlite3.OperationalError) database is locked
[SQL: SELECT policies.id AS policies_id, policies.name AS policies_name, policies.policy AS policies_policy, policies.created_at AS policies_created_at 
FROM policies]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

The steps followed were:
1. Install wazuh (fresh installation).
2. Configure manager as worker node.
3. Start the worker but not the master node (so it is unable to connect).
4. Wait a (long) time to start the master.
5. After starting the master node, the above log was found in the worker's `cluster.log`.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Selutario** [comment]
## Issue update

For the error reported in this issue to occur in the clusterd process of a worker, it is necessary that the API is simultaneously writing or accessing the rbac database. In fact, it is strange that the error occurs since the API process is the first to start when running Wazuh and the clusterd process is the last, so the chances of both services trying to create the database at the same time are low.

In my tests I have not been able to reproduce the error even if I run the API and the cluster synchronously so that they both try to create the db at the same time. The only way to force the error has been if, in addition to running them at the same time, I reduce the timeout of sqlAlchemy.
```Python
# Start a session and set the default security elements
_auth_db_file = os.path.join(SECURITY_PATH, 'rbac.db')
_engine = create_engine('sqlite:///' + _auth_db_file, echo=False, connect_args={'timeout': 0.2})
```

The error appears in both the cluster:
```
# /var/ossec/bin/wazuh-clusterd -f
Starting cluster in foreground (pid: 39276)
2021/12/28 08:46:07 ERROR: [Cluster] [Main] Unhandled exception: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO users (username, password, allow_run_as, created_at) VALUES (?, ?, ?, ?)]
[parameters: ('wazuh-wui', 'pbkdf2:sha256:260000$VLmNTwp9Wwim0Z4p$ba4f16d16460ae742f3241f1d8248842f179f36fcadbb8cb2f8030c3b6388f68', 0, '2021-12-28 08:46:07.920430')]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

And the API:
<details>
<summary>API error log</summary>

```
# /var/ossec/bin/wazuh-apid -f
Starting API in foreground (pid: 60993)
Future exception was never retrieved
future: <Future finished exception=OperationalError('(sqlite3.OperationalError) database is locked')>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/api/scripts/wazuh-apid.py", line 25, in spawn_authentication_pool
    from wazuh import security  # noqa
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/security.py", line 9, in <module>
    from api.authentication import get_security_conf
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/authentication.py", line 22, in <module>
    from wazuh.core.cluster.dapi.dapi import DistributedAPI
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 26, in <module>
    from wazuh import agent
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/agent.py", line 21, in <module>
    from wazuh.rbac.decorators import expose_resources
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/decorators.py", line 15, in <module>
    from wazuh.rbac.orm import RolesManager, PoliciesManager, AuthenticationManager, RulesManager
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/orm.py", line 2449, in <module>
    _Base.metadata.create_all(_engine)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4315, in create_all
    bind._run_visitor(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2049, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1618, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
    return meth(obj, **kw)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 754, in visit_metadata
    [t for t in tables if self._can_create_table(t)]
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 754, in <listcomp>
    [t for t in tables if self._can_create_table(t)]
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 730, in _can_create_table
    return not self.checkfirst or not self.dialect.has_table(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1598, in has_table
    info = self._get_table_pragma(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/base.py", line 2063, in _get_table_pragma
    cursor = connection.execute(statement)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 976, in execute
    return self._execute_text(object_, multiparams, params)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1143, in _execute_text
    ret = self._execute_context(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: PRAGMA main.table_info("roles_rules")]
(Background on this error at: http://sqlalche.me/e/e3q8)
"""

The above exception was the direct cause of the following exception:

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: PRAGMA main.table_info("roles_rules")]
2021/12/28 08:58:36 INFO: Listening on 0.0.0.0:55000..
======== Running on https://0.0.0.0:55000 ========
(Press CTRL+C to quit)
```

</details>

The problem is because the code in charge of creating the database is not inside any function, so any service that imports `wazuh.rbac.orm` will try to create the DB:
https://github.com/wazuh/wazuh/blob/5408c25220ba7b1ecbeb3872065c997b6e1d5f10/framework/wazuh/rbac/orm.py#L2446-L2450

To fix this and other causes of the problem that could lead to the same error, the following actions will be taken:
- All the code that creates the db will be put into a new function.
- The function will only run in the parent API process.

Neither the API child processes nor the cluster service will attempt to create the db, so this error should not appear again. I will review in any case if memory increases in the API after this change.
