### ISSUE TITLE
Wazuh API issue

### ISSUE THREAD

**Issue by mark260486** [wazuh/wazuh#12126]
|4.2.5|Master|Manager|Packages|CentOS 8|

Hi, team!

We facing the strange issue with Master node: at February 5 Master node API failed completely and there is no logs for February 5 at all. Then was discovered that some agents became disconnected and some of them also start to re-register themselves.

We test this re-registering agents and find the following:
- manual registration goes well;
- log is then full of tries to connect to manager, and agent have Never connected state;
- network is fine - pings are going and registration works as well
This problem appears after failure at February 5.

One error we faced on Master at February 6 was related to this: https://github.com/wazuh/wazuh/issues/10360 and all log consist of this error records. We face this error now continously and can provide you information about it too.
And the following error was discovered at January 30 and it also was only one log record for this day, like at February 6:
```
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.5-py3.9.egg/wazuh/core/cluster/local_client.py", line 185, in send_api_request
    await asyncio.wait_for(self.protocol.response_available.wait(), timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.5-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 154, in distribute_function
    response = await self.forward_request()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.5-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 510, in forward_request
    response = await asyncio.shield(asyncio.gather(*[forward(node) for node in cleaned_valid_nodes]))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.5-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 419, in forward
    result = json.loads(await client.execute(b'dapi_forward',
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.5-py3.9.egg/wazuh/core/cluster/local_client.py", line 215, in execute
    result = await self.send_api_request(command, data, wait_for_complete)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.5-py3.9.egg/wazuh/core/cluster/local_client.py", line 188, in send_api_request
    raise exception.WazuhInternalError(3020)
wazuh.core.exception.WazuhInternalError: Error 3020 - Timeout sending request
```

Also right now we see that Master API works very slow, as it was highly loaded, but it's not. If you need more information, do not hesitate to ask. Thanks.

**Comment by mark260486** [comment]
Looks like there is problem in the cluster sync. Worker didn't know about new agent. We tried to register new agent directly to Master node and it works

**Comment by mark260486** [comment]
@palaciosjeremias asked for `/var/ossec/bin/cluster_control -i more`

```Cluster name: wazuh

Connected nodes (13):

    master-prod (MASTER_IP)
        Version: 4.2.5
        Type: master
        Active agents: 2

    worker-1 (WORKER_1_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 244
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:20.113829.
            Integrity check:
                Last integrity check: 2022-02-09 08:02:28.409712 - 2022-02-09 08:02:30.399221.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 808 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: 2022-02-09 08:10:26.042300 - 2022-02-09 08:10:27.636618.
                Number of synchronized chunks: 4.

    worker-2 (WORKER_2_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 249
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:04.468981.
            Integrity check:
                Last integrity check: 2022-02-09 08:07:02.863676 - 2022-02-09 08:07:05.911179.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 809 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: 2022-02-09 08:10:24.507710 - 2022-02-09 08:10:25.629964.
                Number of synchronized chunks: 4.

    worker-3 (WORKER_3_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 335
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:04.462258.
            Integrity check:
                Last integrity check: 2022-02-09 08:03:20.998277 - 2022-02-09 08:03:35.808523.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 808 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: 2022-02-09 08:10:25.600804 - 2022-02-09 08:10:27.465749.
                Number of synchronized chunks: 5.

    worker-4 (WORKER_4_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 50
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:19.267044.
            Integrity check:
                Last integrity check: 2022-02-09 08:06:26.912334 - 2022-02-09 08:06:29.461359.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 808 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: 2022-02-09 08:10:26.058076 - 2022-02-09 08:10:28.548748.
                Number of synchronized chunks: 1.

    worker-5 (WORKER_5_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 0
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:04.463006.
            Integrity check:
                Last integrity check: 2022-02-09 08:08:00.301286 - 2022-02-09 08:08:02.081595.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 809 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: n/a - n/a.
                Number of synchronized chunks: 0.

    worker-6 (WORKER_6_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 0
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:20.109426.
            Integrity check:
                Last integrity check: 2022-02-09 08:08:01.830886 - 2022-02-09 08:08:20.451663.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 809 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: n/a - n/a.
                Number of synchronized chunks: 0.

    worker-7 (WORKER_7_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 0
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:04.467368.
            Integrity check:
                Last integrity check: 2022-02-09 08:05:43.872905 - 2022-02-09 08:05:45.499157.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 808 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: n/a - n/a.
                Number of synchronized chunks: 0.

    worker-8 (WORKER_8_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 81
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:04.468465.
            Integrity check:
                Last integrity check: 2022-02-09 08:05:53.884937 - 2022-02-09 08:05:55.283602.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 808 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: 2022-02-09 08:10:21.579411 - 2022-02-09 08:10:22.666781.
                Number of synchronized chunks: 2.

    worker-9 (WORKER_9_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 255
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:18.137146.
            Integrity check:
                Last integrity check: 2022-02-09 08:05:53.884894 - 2022-02-09 08:06:03.227925.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 808 | Extra: 2 | Extra valid: 9.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: 2022-02-09 08:10:23.954273 - 2022-02-09 08:10:24.907013.
                Number of synchronized chunks: 4.

    worker-10 (WORKER_10_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 0
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:19.266269.
            Integrity check:
                Last integrity check: 2022-02-09 08:09:32.088271 - 2022-02-09 08:09:44.858909.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 809 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: n/a - n/a.
                Number of synchronized chunks: 0.

    worker-11 (WORKER_11_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 0
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:18.145259.
            Integrity check:
                Last integrity check: 2022-02-09 08:07:24.177242 - 2022-02-09 08:07:26.917171.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 809 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: n/a - n/a.
                Number of synchronized chunks: 0.

    worker-12 (WORKER_12_IP)
        Version: 4.2.5
        Type: worker
        Active agents: 0
        Status:
            Last keep Alive:
                Last received: 2022-02-09 08:10:04.467917.
            Integrity check:
                Last integrity check: 2022-02-09 08:09:02.654735 - 2022-02-09 08:09:04.520076.
                Permission to check integrity: False.
            Integrity sync:
                Last integrity synchronization: n/a - n/a.
                Synchronized files: Shared: 2 | Missing: 809 | Extra: 2 | Extra valid: 8.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: n/a - n/a.
                Number of synchronized chunks: 0.
```

**Comment by palaciosjeremias** [comment]
Hello @mark260486,
Were you able to collect the complete **cluster.log** file? It will help us to investigate the root cause of the problem.

Regarding your questions about the logs found:
The `Couldn't add multigroup 'default,windows,prod' to hash table` log, is expected. Remoted periodically updates a hash table with groups, if the group is already updated, it isn´t re-inserted and this DEBUG log is generated.
The cluster logs with messages like `Error in synchronization process` aren´t expected and they must be the reason for the impossibility of synchronizing the agents' keys and unchains the rejection of the newly registered agents.

**Comment by mark260486** [comment]
Hi, @palaciosjeremias ! Thanks for the reply!
Yes, clusterd log were up here. Post it once more:
```Worker logs

2022/02/08 14:02:14 ERROR: [Worker worker-1] [Main] Internal error processing request 'b'sync_m_c_e'': Error 3027 - Unknown received task name: 821803066
2022/02/08 14:02:14 ERROR: [Worker worker-1] [Main] Error in synchronization process: Error 3027 - Unknown received task name: 821803066


2022/02/08 14:08:43 INFO: [Worker worker-1] [Integrity check] Starting.
2022/02/08 14:08:44 INFO: [Worker worker-1] [Integrity check] Finished in 0.443s. Master didn't grant permission to synchronize.
2022/02/08 14:08:44 DEBUG: [Worker worker-1] [Main] Command received: 'b'file_upd''
2022/02/08 14:08:45 DEBUG: [Worker worker-1] [Main] Command received: 'b'file_upd''
2022/02/08 14:08:46 INFO: [Worker worker-1] [Agent-info sync] Starting.
2022/02/08 14:08:46 DEBUG: [Worker worker-1] [Main] Command received: 'b'file_upd''
2022/02/08 14:08:46 DEBUG: [Worker worker-1] [Agent-info sync] Permission to synchronize granted.
2022/02/08 14:08:46 DEBUG: [Worker worker-1] [Agent-info sync] Obtained 0 chunks of data in 0.000s.
2022/02/08 14:08:46 INFO: [Worker worker-1] [Agent-info sync] Finished in 0.241s (0 chunks sent).
2022/02/08 14:08:47 DEBUG: [Worker worker-1] [Main] Command received: 'b'file_upd''
2022/02/08 14:08:47 INFO: [Worker worker-1] [Keep Alive] Sucessful response from master: keepalive
2022/02/08 14:08:48 DEBUG: [Worker worker-1] [Main] Command received: 'b'file_upd''



Master logs

2022/02/08 14:24:37 ERROR: [Worker worker-2] [Main] Error 3016 - Received an error response: Error sending request: timeout expired.
2022/02/08 14:24:37 ERROR: [Worker worker-3] [Main] Error 3016 - Received an error response: Error sending request: timeout expired.

2022/02/08 14:23:50 ERROR: [Worker worker-4] [Main] Error sending files information: Error 3027 - Unknown received task name: 2230018460
2022/02/08 14:23:50 ERROR: [Worker worker-5] [Main] Error sending files information: Error 3027 - Unknown received task name: 3529031230

2022/02/08 14:20:37 ERROR: [Local 553057] [Main] Error during connection with '553057': [Errno 32] Broken pipe.
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)

2022/02/08 14:20:37 ERROR: [Local 664113] [Main] Error during connection with '664113': [Errno 32] Broken pipe.
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)
```

**Comment by palaciosjeremias** [comment]
Hello Mark,
I was referring to the complete cluser.log file (to have more context for the analysis). But I understand there aren´t any more logs than the copied in the issue. Right?

Regarding the cluster synchronization error:
The worker is rejecting the master command **sync_m_c_e** because it´s an older version of the command and in recent Wazuh versions, this command has changed to **syn_m_c_e**.
Are you using an installation from sources? Maybe branch 4.3?
How did you update Wazuh?
Did you update Wazuh master and Wazuh workers together?
It seems that you have a Wazuh master cluster older than the Wazuh worker cluster. The cluster should reject if the managers aren´t from the same version. But if you are using a compilation from branches, they could have different commit versions but have the same tagged version.

Let me know about this. 
Best regards.

**Comment by palaciosjeremias** [comment]
Hello Mark,
I got in contact with other co-workers and this is what I found:
The error **`Unknown received task name:`** is because exists a mechanism where the commands sent are held for a while to parse properly its response. But, these commands are held for a specific time, after that they are discarded.
When the synchronized file is big, it can take more than 120 seconds to be synced, and this timeout occurs, leading to the errors that you are observing.
To bypass this problem you can extend this synchronization time by changing **timeout_receiving_file** in **cluster.json** file, i.e.:
```
"communication":{
            "timeout_cluster_request": 20,
            "timeout_dapi_request": 200,
            "timeout_receiving_file": 380
        }
```
Let me know if this helps.
If you have further doubts please let me know.

Best regards.

**Comment by palaciosjeremias** [comment]
Hello @mark260486, were you able to check this? If you have further doubts please don´t hesitate to ask.
Best regards.

**Comment by mark260486** [comment]
Hi, @palaciosjeremias ! Sorry for the delay.

> I was referring to the complete cluser.log file (to have more context for the analysis). But I understand there aren´t any more logs than the copied in the issue. Right?
Unfortunately, yes.

Regarding to installation: we did install Wazuh from the repository as clean installation - no updates from the earlier versions.

We tried to increase timeout and this didn't help :(

Thanks for your job and time, i very appreciate it.

**Comment by palaciosjeremias** [comment]
Hello Mark.
Sorry for the delay.
Talking with other co-workers they inform me that other users with the same error required to extend even more the **timeout_receiving_file** settings. Can we try with 
```
"communication":{
            "timeout_cluster_request": 20,
            "timeout_dapi_request": 200,
            "timeout_receiving_file": 1000
        }
```
Increasing more this timeout could be difficult to test. But if you could extend it even more and test it, will bring us a good understanding of how much are your files taking to sync.
On the other hand, as you mention that there are more cluster logs in the **cluster.log**: Could provide us the complete log file for further investigation?

Let me add that we are working on this problem and its fix is being tracked with this issue https://github.com/wazuh/wazuh/issues/11945.

Best regards.

**Comment by palaciosjeremias** [comment]
Hello Mark,
Were you able to check this?
Best regards.

**Comment by mark260486** [comment]
Hi, @palaciosjeremias! Sorry for the delay.
Unfortunately, i'm not able to check this, because this problem happened on Prod and we already fixed it by redeploying of Master node. But this is not the solution we want to use for such problems.

Before redeploying we tried to increase clusterd timeout. It didn't help.

**Comment by palaciosjeremias** [comment]
I understand your point.
This issue is now being tracked [here](https://github.com/wazuh/wazuh/issues/11945) to bring a solution without the requirement of this workaround.

**Comment by mark260486** [comment]
Thanks a lot! I think we could close for now
