### ISSUE TITLE
Fix issues when compiling Python while installing Wazuh `4.3.0` from sources

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#12133]
|Wazuh version|
|---|
| 4.3 | 

## Description
We have encountered some problems while trying to install Wazuh **from sources** in a `Ubuntu 20.04` machine following [the documentation](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html).

First of all, the Python version that was being downloaded was `Python 3.9.6` instead of `Python 3.9.9`.

Also, having an environment with all the dependencies pointed by the documentation, and after executing `make deps PYTHON_SOURCE=yes` and `make TARGET=server PYTHON_SOURCE=yes INSTALLDIR=/var/ossec`, the following error appears when installing Wazuh using the `install.sh` script:

```
	LD_LIBRARY_PATH=/wazuh/src/external/cpython:/wazuh/src ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Traceback (most recent call last):
  File "<frozen zipimport>", line 520, in _get_decompress_func
ModuleNotFoundError: No module named 'zlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 568, in _get_data
  File "<frozen zipimport>", line 523, in _get_decompress_func
zipimport.ZipImportError: can't decompress data; zlib not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/wazuh/src/external/cpython/Lib/runpy.py", line 206, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/wazuh/src/external/cpython/Lib/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/wazuh/src/external/cpython/Lib/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 570, in _get_data
zipimport.ZipImportError: can't decompress data; zlib not available
Traceback (most recent call last):
  File "/wazuh/src/external/cpython/Lib/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/wazuh/src/external/cpython/Lib/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/wazuh/src/external/cpython/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/wazuh/src/external/cpython/Lib/ensurepip/__init__.py", line 210, in _main
    return _bootstrap(
  File "/wazuh/src/external/cpython/Lib/ensurepip/__init__.py", line 129, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/wazuh/src/external/cpython/Lib/ensurepip/__init__.py", line 38, in _run_pip
    return subprocess.run([sys.executable, "-c", code], check=True).returncode
  File "/wazuh/src/external/cpython/Lib/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/wazuh/src/external/cpython/python', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpbpocbuhb/setuptools-56.0.0-py3-none-any.whl\', \'/tmp/tmpbpocbuhb/pip-21.1.3-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpbpocbuhb\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make[1]: *** [Makefile:1266: install] Error 1
make[1]: Leaving directory '/wazuh/src/external/cpython'
make: *** [Makefile:2066: install_python] Error 2

```

After that, trying to execute the Wazuh embedded Python interpreter shows the following error message:
```
root@6d5afa40f23b:/var/ossec/framework/python/bin# ./python3
./python3: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

```

We have ensured that this is not happening with Wazuh `v4.2.5`. We must fix this to make sure that all the supported installation alternatives are working without issues.

## Tasks
- [x] Investigate the problem with Python compilation when installing from sources
- [x] Update the Python sources package downloaded by Wazuh `4.3.0` to `Python 3.9.9`

**Comment by noise-kngdm** [comment]
## Issue update
### Fixing Python package version
The package used was based on `Python 3.9.6` instead of `Python 3.9.9`, which is the version of the Python embedded interpreter Wazuh `4.3.0` will ship with. To fix that, we used the precompiled Python `3.9.9` package for `amd64` as a base to update a `Python 3.9.9` clean package to the Wazuh requirements. We also added all the updated dependencies, and then compressed the package and changed the wrong with the new one.

### Python compilation problems when installing from sources
After testing several different packages and Wazuh versions, we arrived at the conclusion that the [installing from sources](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html) guide is out-of-date since there are several dependencies missing which are needed to compile Python when the user specifies that option instead of using the pre-compiled packages.

Using a `ubuntu:20.04` docker image as a base container for our research, we had to install the following packages to successfully compile Wazuh and Python:

```
libssl-dev
lsb-core
zlib1g-dev libsqlite3-dev
pkg-config
```

We will open an issue in [wazuh-documentation](https://github.com/wazuh/wazuh-documentation) to fix this section of the documentation.
