### ISSUE TITLE
Cluster configuration isn't validated

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#1223]
Hello team,

There are a few cluster configuration fields that aren't validated:

* Node IP: validate that the node's IP isn't used in the configuration (https://github.com/wazuh/wazuh/issues/1181 https://github.com/wazuh/wazuh/issues/1177)
* Spaces aren't allowed in any field (https://github.com/wazuh/wazuh/issues/1176):
* Improve validation done here: 
    https://github.com/wazuh/wazuh/blob/0d73e273527102051a25b66ca607b68f79740b73/src/config/cluster-config.c#L48
* Port field must be an integer, otherwise the following error is shown when starting the cluster (no errors are shown in cluster.log):
    ```shellsession
    # /var/ossec/bin/wazuh-clusterd -fdd
    Traceback (most recent call last):
      File "/var/ossec/bin/wazuh-clusterd", line 243, in <module>
        cluster_config = read_config()
      File "/var/ossec/bin/../framework/wazuh/cluster/cluster.py", line 119, in read_config
        config_cluster['port'] = int(config_cluster['port'])
    ValueError: invalid literal for int() with base 10: '15bbbb16'
    ```
* `bind_addr` field shows the following message if an invalid value is used:
    ```
    2018-09-04 14:19:51,656 ERROR   : [Errno -2] Name or service not known
    ```
* No error is shown when `disabled` tag is missing in cluster (https://github.com/wazuh/wazuh/issues/1178).
* If a random value is used in the `disabled` tag, the following error takes place:
    ```
    2018-09-04 14:24:27,645 INFO    : [Master] PID: 10342
    2018-09-04 14:24:27,655 INFO    : [Master] Listening '0.0.0.0:1516'.
    2018-09-04 14:24:27,659 INFO    : [Master] [Internal-COM ]: Ready.
    2018-09-04 14:24:37,722 ERROR   : [Transport-Server] Error: 'global name 'Fernet' is not defined'.
    2018-09-04 14:24:37,725 ERROR   : [Master] Exiting. Reason: 'Unknown exception: 'MasterManagerHandler instance has no attribute 'name'''.
    ```
* If the cluster is disabled, no message is shown in the cluster.log. A message is only shown when running the cluster in foreground.

Best regards,
Marta

**Comment by pillarsdotnet** [comment]
Possibly related fix: #1636

**Comment by mgmacias95** [comment]
About this point "_If the cluster is disabled, no message is shown in the cluster.log. A message is only shown when running the cluster in foreground._". After some research I found out that this is not a bug. If the cluster is disabled, it's not even attempted to be started and therefore, no message is written to the log:

https://github.com/wazuh/wazuh/blob/32b72a76c363706edea21c7833a27c7782b0c460/src/init/ossec-server.sh#L312-L324
