### ISSUE TITLE
No proper error handling in cluster module on configurations errors

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#13130]
|Wazuh version|Component|
|---|---|
| 4.2.6-40221 | wazuh-cluster |

Hello Team,
The cluster is not managing properly the errors when some settings are wrong in the `ossec.conf` file.
Example, adding these lines to the end of the ossec.conf:
```
<!-- ossec_config>
 <!-- wodle name="aws-s3">
 </wodle -->
</ossec_config -->
```

This generates a conflict because the cluster reads this as a comment:
```
<!-- ossec_config>
 <!-- wodle name="aws-s3">
 </wodle -->
```
leaving an orphaned setting like this:
```
</ossec_config -->
```

And causing the following issue in the cluster:
```
# /var/ossec/bin/wazuh-control restart
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/xml/etree/ElementTree.py", line 1720, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 378, column 15

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.6-py3.9.egg/wazuh/core/configuration.py", line 480, in get_ossec_conf
    xml_data = load_wazuh_xml(conf_file)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.6-py3.9.egg/wazuh/core/utils.py", line 739, in load_wazuh_xml
    return ElementTree.fromstring(entities + '<root_tag>' + data + '</root_tag>')
  File "/var/ossec/framework/python/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
  File "/var/ossec/framework/python/lib/python3.9/xml/etree/ElementTree.py", line 1722, in feed
    self._raiseerror(v)
  File "/var/ossec/framework/python/lib/python3.9/xml/etree/ElementTree.py", line 1629, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 378, column 15

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.6-py3.9.egg/wazuh/core/cluster/utils.py", line 58, in read_cluster_config
    config_cluster = get_ossec_conf(section='cluster', conf_file=config_file)['cluster']
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.6-py3.9.egg/wazuh/core/configuration.py", line 485, in get_ossec_conf
    raise WazuhError(1101, extra_message=str(e))
wazuh.core.exception.WazuhError: Error 1101 - Requested component does not exist: not well-formed (invalid token): line 378, column 15

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh-apid.py", line 10, in <module>
    from api import alogging, configuration
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.2.6-py3.9.egg/api/alogging.py", line 11, in <module>
    from api.authentication import decode_token
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.2.6-py3.9.egg/api/authentication.py", line 23, in <module>
    from wazuh.core.cluster.dapi.dapi import DistributedAPI
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.6-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 26, in <module>
    from wazuh import agent
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.6-py3.9.egg/wazuh/agent.py", line 21, in <module>
    cluster_enabled = not read_cluster_config()['disabled']
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.6-py3.9.egg/wazuh/core/cluster/utils.py", line 65, in read_cluster_config
    raise WazuhError(3006, extra_message=e.message)
wazuh.core.exception.WazuhError: Error 3006 - Error reading cluster configuration: Requested component does not exist: not well-formed (invalid token): line 378, column 15
wazuh-apid: Configuration error. Exiting
```

This error should be better handled by the Wazuh Cluster module.
Thank you in advance.

**Comment by Selutario** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/13419
