### ISSUE TITLE
wazuh-apid error after update to 4.3.0

### ISSUE THREAD

**Issue by andresqueirolo** [wazuh/wazuh#13435]
Hi! after update from 4.2.6 to 4.3.0  I'm getting the following error:

```
May 12 17:58:01 wazuh_manager env[3201]: Configuration not valid. ERROR: 2000 - Some parameters are not expected in the configuration file (WAZUH_PATH/api/configuration/api.yaml): 'api/configuration/ssl/server.key' does not match '^[\\w\\-.]+$'.
```

```
[root@wazuh_manager aqueirolo]# /var/ossec/bin/wazuh-apid -r
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/configuration.py", line 129, in fill_dict
    validate(instance=config, schema=json_schema)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'api/configuration/ssl/server.key' does not match '^[\\w\\-.]+$'

Failed validating 'pattern' in schema['properties']['https']['properties']['key']:
    {'pattern': '^[\\w\\-.]+$', 'type': 'string'}

On instance['https']['key']:
    'api/configuration/ssl/server.key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh-apid.py", line 181, in <module>
    from api import alogging, configuration
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/alogging.py", line 12, in <module>
    from wazuh.core.wlogging import WazuhLogger
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/wlogging.py", line 7, in <module>
    from wazuh.core import common, utils
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/utils.py", line 32, in <module>
    from api import configuration
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/configuration.py", line 280, in <module>
    api_conf = read_yaml_config()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/configuration.py", line 263, in read_yaml_config
    configuration = fill_dict(default_conf, configuration, schema)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.0-py3.9.egg/api/configuration.py", line 131, in fill_dict
    raise APIError(2000, details=e.message)
api.api_exception.APIError: 2000 - Some parameters are not expected in the configuration file (WAZUH_PATH/api/configuration/api.yaml): 'api/configuration/ssl/server.key' does not match '^[\\w\\-.]+$'.
```

I check the file /var/ossec/api/configuration/api.yaml

```
[root@wazuh_manager aqueirolo]# cat /var/ossec/api/configuration/api.yaml
# USE THIS FILE AS A TEMPLATE. UNCOMMENT LINES TO APPLY CUSTOM CONFIGURATION

host: 0.0.0.0
port: 8080

# Set this option to "yes" in case the API is running behind a proxy server. Values: yes, no
# behind_proxy_server: no

# Advanced configuration

https:
  enabled: yes
  key: "api/configuration/ssl/server.key"
  cert: "api/configuration/ssl/server.crt"

```

```
[root@wazuh_manager aqueirolo]# ll /var/ossec/api/configuration/ssl/
total 8
-r--r--r-- 1 root wazuh 1651 Mar 13  2020 server.crt
-r--r--r-- 1 root wazuh 1679 Mar 13  2020 server.key
```

Some ideas?

**Comment by mcarmona99** [comment]
Hi @andresqueirolo ,

From Wazuh v4.3.0 on, for the API HTTPS private key and certificates, only the filename is configurable and it will be taken for granted that the given names exist under `WAZUH_PATH/api/configuration/ssl`.

In other words, the paths to the private key and certs files must be removed from your configuration in favor of just the name of these files.

You can find more information about this change in its relative pull request or issue. You can find the pull request in the [changelog entry for this change](https://github.com/wazuh/wazuh/blob/4.3/CHANGELOG.md#changed-2):

> Changed HTTPS options to use files instead of relative paths. (https://github.com/wazuh/wazuh/pull/11410)
