### ISSUE TITLE
Empty response for `GET /agents/{id}/stats/{comp}` in API `test_agent_GET_endpoints` test

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#13659]
This issue aims to investigate the following error in the `test_agent_GET_endpoints.tavern.yaml` API integration test.

<details>

<summary>Test result</summary>

```
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.5', 'Platform': 'Linux-5.4.0-1029-aws-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.9.0', 'pluggy': '0.13.1'}, 'Plugins': {'tavern': '1.0.0', 'metadata': '1.10.0', 'html': '2.0.1'}}
rootdir: /tmp/Test_integration_endpoints_B2401_test_files/api/test/integration, inifile: pytest.ini
plugins: tavern-1.0.0, metadata-1.10.0, html-2.0.1
collecting ... collected 92 items

test_agent_GET_endpoints.tavern.yaml::GET /agents PASSED                 [  1%]
test_agent_GET_endpoints.tavern.yaml::GET /agents with single agent id PASSED [  2%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/config/{component}/{configuration} PASSED [  3%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/config/{component}/{configuration} (only cluster configuration) PASSED [  4%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/group/is_sync PASSED [  5%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/key PASSED  [  6%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/stats/{component} FAILED [  7%]
test_agent_GET_endpoints.tavern.yaml::GET /groups PASSED                 [  8%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[md5] PASSED [  9%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha1] PASSED [ 10%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha224] PASSED [ 11%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha256] PASSED [ 13%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha384] PASSED [ 14%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha512] PASSED [ 15%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[blake2b] PASSED [ 16%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[blake2s] PASSED [ 17%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_224] PASSED [ 18%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_256] PASSED [ 19%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_384] PASSED [ 20%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_512] PASSED [ 21%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents PASSED [ 22%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[configSum] PASSED [ 23%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[dateAdd] PASSED [ 25%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[group] PASSED [ 26%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[id] PASSED [ 27%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[ip] PASSED [ 28%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[lastKeepAlive] PASSED [ 29%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[manager] PASSED [ 30%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[mergedSum] PASSED [ 31%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[name] PASSED [ 32%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[node_name] PASSED [ 33%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.arch] PASSED [ 34%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.build] PASSED [ 35%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.codename] PASSED [ 36%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.major] PASSED [ 38%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.minor] PASSED [ 39%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.name] PASSED [ 40%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.platform] PASSED [ 41%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.uname] PASSED [ 42%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.version] PASSED [ 43%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[registerIP] PASSED [ 44%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[status] PASSED [ 45%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[version] PASSED [ 46%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/configuration PASSED [ 47%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files PASSED [ 48%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[md5] PASSED [ 50%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha1] PASSED [ 51%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha224] PASSED [ 52%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha256] PASSED [ 53%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha384] PASSED [ 54%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha512] PASSED [ 55%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[blake2b] PASSED [ 56%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[blake2s] PASSED [ 57%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha3_224] PASSED [ 58%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha3_256] PASSED [ 59%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha3_384] PASSED [ 60%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha3_512] PASSED [ 61%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files/{filename}/json PASSED [ 63%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files/{filename}/xml PASSED [ 64%]
test_agent_GET_endpoints.tavern.yaml::GET /agents?name=agent_name PASSED [ 65%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group PASSED        [ 66%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[dateAdd] PASSED [ 67%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[id] PASSED [ 68%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[ip] PASSED [ 69%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[name] PASSED [ 70%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[node_name] PASSED [ 71%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[registerIP] PASSED [ 72%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[status] PASSED [ 73%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/outdated PASSED        [ 75%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct PASSED  [ 76%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[dateAdd] PASSED [ 77%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[id] PASSED [ 78%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[ip] PASSED [ 79%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[lastKeepAlive] PASSED [ 80%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[manager] PASSED [ 81%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[name] PASSED [ 82%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[node_name] PASSED [ 83%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.arch] PASSED [ 84%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.build] PASSED [ 85%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.codename] PASSED [ 86%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.major] PASSED [ 88%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.minor] PASSED [ 89%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.name] PASSED [ 90%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.platform] PASSED [ 91%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.uname] PASSED [ 92%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.version] PASSED [ 93%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[registerIP] PASSED [ 94%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[status] PASSED [ 95%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[version] PASSED [ 96%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/summary/status PASSED  [ 97%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/summary/os PASSED      [ 98%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/upgrade_result PASSED  [100%]

=================================== FAILURES ===================================
_ /tmp/Test_integration_endpoints_B2401_test_files/api/test/integration/test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/stats/{component} _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjU0MDg1NTM4LCJleHAiOjE2NTQwODY0MzgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AMoOMaimagMrEUaL8MT0sZkOKXWJBwGNasLlovNfvzI1vyA3X9m9lYBPC0kl2C9piAypyblzA4VjdM5msuruPVDFALcGVFA9mMyFaEgxW6gcqiOCajuoOhvrDQB73PEHkp8sK8l7q6qO7YnsgMqz4sIlsmPDDcqJeB3NedyCKHolyISB'

Source test stage (line 2225):
  - name: Get logcollector stats from agent 002
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/002/stats/logcollector"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      status_code: 200
      json:
        error: !anyint
        data:
          affected_items:
            - <<: *stats_response
          failed_items: []
          total_affected_items: 1
          total_failed_items: 0


Formatted stage:
  name: Get logcollector stats from agent 002
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjU0MDg1NTM4LCJleHAiOjE2NTQwODY0MzgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AMoOMaimagMrEUaL8MT0sZkOKXWJBwGNasLlovNfvzI1vyA3X9m9lYBPC0kl2C9piAypyblzA4VjdM5msuruPVDFALcGVFA9mMyFaEgxW6gcqiOCajuoOhvrDQB73PEHkp8sK8l7q6qO7YnsgMqz4sIlsmPDDcqJeB3NedyCKHolyISB
    method: GET
    url: 'https://localhost:55000/agents/002/stats/logcollector'
    verify: false
  response:
    json:
      data:
        affected_items:
        - global:
            end: !anystr ''
            files: !anything ''
            start: !anystr ''
          interval:
            end: !anystr ''
            files: !anything ''
            start: !anystr ''
        failed_items: []
        total_affected_items: 1
        total_failed_items: 0
      error: !anyint ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Get logcollector stats from agent 002' failed:
    - List item(s) not present in response: [{'global': {'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>, 'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>, 'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>}, 'interval': {'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>, 'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>, 'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>}}]
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:41 List item(s) not present in response: [{'global': {'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>, 'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>, 'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>}, 'interval': {'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>, 'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>, 'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>}}]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'affected_items': [{}],\n          'failed_items': [],\n          'total_affected_items': 1,\n          'total_failed_items': 0},\n 'error': 0,\n 'message': 'Statistical information for each agent was successfully read'} == {'data': {'affected_items': [{'global': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>,\n                                         'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,\n                                         'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>},\n                              'interval': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>,\n                                           'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,\n                                           'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>}}],\n          'failed_items': [],\n          'total_affected_items': 1,\n          'total_failed_items': 0},\n 'error': <tavern.util.loader.IntSentinel object at 0x7f40fcf3d430>}
  Differing items:
  {'data': {'affected_items': [{}], 'failed_items': [], 'total_affected_items': 1, 'total_failed_items': 0}} != {'data': {'affected_items': [{'global': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>, 'files': <t...ader.StrSentinel object at 0x7f40fcf408e0>}}], 'failed_items': [], 'total_affected_items': 1, 'total_failed_items': 0}}
  {'error': 0} != {'error': <tavern.util.loader.IntSentinel object at 0x7f40fcf3d430>}
  Left contains 1 more item:
  {'message': 'Statistical information for each agent was successfully read'}
  Full diff:
    {
  +  'data': {'affected_items': [{}],
  -  'data': {'affected_items': [{'global': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>,
  -                                          'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,
  -                                          'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>},
  -                               'interval': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>,
  -                                            'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,
  -                                            'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>}}],
              'failed_items': [],
              'total_affected_items': 1,
              'total_failed_items': 0},
  -  'error': <tavern.util.loader.IntSentinel object at 0x7f40fcf3d430>,
  +  'error': 0,
  +  'message': 'Statistical information for each agent was successfully read',
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_items': [{}],\n 'failed_items': [],\n 'total_affected_items': 1,\n 'total_failed_items': 0} == {'affected_items': [{'global': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>,\n                                'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,\n                                'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>},\n                     'interval': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>,\n                                  'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,\n                                  'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>}}],\n 'failed_items': [],\n 'total_affected_items': 1,\n 'total_failed_items': 0}
  Common items:
  {'failed_items': [], 'total_affected_items': 1, 'total_failed_items': 0}
  Differing items:
  {'affected_items': [{}]} != {'affected_items': [{'global': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>, 'files': <tavern.uti...ader.AnythingSentinel object at 0x7f40fdb5b400>, 'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>}}]}
  Full diff:
    {
  +  'affected_items': [{}],
  -  'affected_items': [{'global': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>,
  -                                 'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,
  -                                 'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>},
  -                      'interval': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>,
  -                                   'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,
  -                                   'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>}}],
     'failed_items': [],
     'total_affected_items': 1,
     'total_failed_items': 0,
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert [{}] == [{'global': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>,\n             'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,\n             'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>},\n  'interval': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>,\n               'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,\n               'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>}}]
  At index 0 diff: {} != {'global': {'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>, 'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>, 'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>}, 'interval': {'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>, 'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>, 'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>}}
  Full diff:
    [
  +  {},
  -  {'global': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>,
  -              'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,
  -              'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>},
  -   'interval': {'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>,
  -                'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>,
  -                'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>}},
    ]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 512, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(msg) from e
tavern.util.exceptions.KeyMismatchError: List item(s) not present in response: [{'global': {'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf405b0>, 'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf407f0>, 'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>}, 'interval': {'start': <tavern.util.loader.StrSentinel object at 0x7f40fcf408e0>, 'end': <tavern.util.loader.StrSentinel object at 0x7f40fcf40e20>, 'files': <tavern.util.loader.AnythingSentinel object at 0x7f40fdb5b400>}}]
=============================== warnings summary ===============================
/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/hooks.py:83
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/hooks.py:83: PytestDeprecationWarning: direct construction of YamlFile has been deprecated, please use YamlFile.from_parent
    return YamlFile(path, parent)

/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:233: 25 tests with warnings
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:233: PytestDeprecationWarning: direct construction of YamlItem has been deprecated, please use YamlItem.from_parent
    item = YamlItem(test_spec["test_name"], self, test_spec, self.fspath)

/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:182: 72 tests with warnings
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:182: PytestDeprecationWarning: direct construction of YamlItem has been deprecated, please use YamlItem.from_parent
    item_new = YamlItem(spec_new["test_name"], self, spec_new, self.fspath)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
- generated html file: file:///tmp/Test_integration_endpoints_B2401_test_files/api/test/integration/Test_integration_endpoints_B2401_test_agent_GET_endpoints.html -
=========================== short test summary info ============================
FAILED test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/stats/{component}
============ 1 failed, 91 passed, 98 warnings in 364.57s (0:06:04) =============
```

</details>

Details: [test_agent_GET_endpoints.zip](https://github.com/wazuh/wazuh/files/8814895/Test_integration_endpoints_B2401_test_agent_GET_endpoints.zip)

Logs: [test_agent_GET_endpoints_logs.zip](https://github.com/wazuh/wazuh/files/8814891/Test_integration_endpoints_B2401_test_agent_GET_endpoints_logs.zip)

It is a random error related to the `GET /agents/{agent_id}/stats/{component}` endpoint that was found in an API integration test run in the CI host. Wazuh branch: `master`

The agent was **002** and the component was **logcollector**.

The following function is the one in charge of getting the daemon stats from the core socket:

```python
def get_daemons_stats_from_socket(agent_id, daemon):
    """Get a daemon stats from an agent or manager.

    Parameters
    ----------
    agent_id: string
        Id of the agent to get stats from.
    daemon: string
        Name of the service to get stats from.

    Returns
    -------
    Dict
        Object with daemon's stats.
    """
    if not agent_id or not daemon:
        raise WazuhError(1307)

    sockets_path = os.path.join(common.WAZUH_PATH, "queue", "sockets")

    if str(agent_id).zfill(3) == '000':
        # Some daemons do not exist in agent 000
        if daemon in {'agent'}:
            raise WazuhError(1310)
        dest_socket = os.path.join(sockets_path, daemon)
        command = "getstate"
    else:
        dest_socket = os.path.join(sockets_path, "request")
        command = f"{str(agent_id).zfill(3)} {daemon} getstate"

    # Socket connection
    try:
        s = WazuhSocket(dest_socket)
    except Exception:
        raise WazuhInternalError(1121)

    # Send message
    s.send(command.encode())

    # Receive response
    try:
        rec_msg = s.receive().decode()
    except ValueError:
        raise WazuhInternalError(1118, extra_message="Data could not be received")

    s.close()

    # Format response
    try:
        data = json.loads(rec_msg)['data']
        data.update((k, utils.get_utc_strptime(data[k], "%Y-%m-%d %H:%M:%S").strftime(common.DATE_FORMAT))
                    for k, v in data.items() if k in {'last_keepalive', 'last_ack'})
        return data
    except Exception:
        rec_msg = rec_msg.split(" ", 1)[1]
        raise WazuhError(1117, extra_message=rec_msg)
```

We should replicate this error and investigate and fix it.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
# Issue update

After further investigation, we can assure this is not an issue that comes from the framework. I reproduced this situation simply restarting the agent service and requesting the `logcollector` stats:

```json
{
  "data": {
    "affected_items": [
      {}
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Statistical information for each agent was successfully read",
  "error": 0
}
```

It seems that the component cannot return its stats after a while when restarting the service. This matches with the logs given in the main post. Testing this in my own environment (with better specs than the CI host), I restarted the agent service at `10:06:06`. Half a minute later, `remoted` was able to return `logcollector` stats (last entry):

```
2022/07/19 10:06:49 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f598d logcollector getstate'
2022/07/19 10:06:56 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f598e logcollector getstate'
2022/07/19 10:07:00 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f598f logcollector getstate'
2022/07/19 10:07:04 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f5990 logcollector getstate'
2022/07/19 10:07:10 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f5991 logcollector getstate'
2022/07/19 10:07:15 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f5992 logcollector getstate'
2022/07/19 10:07:21 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f5993 logcollector getstate'
2022/07/19 10:07:26 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f5994 logcollector getstate'
2022/07/19 10:07:33 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f5995 logcollector getstate'
2022/07/19 10:07:41 wazuh-remoted[266] request.c:240 at req_dispatch(): DEBUG: Sending request: '#!-req 2a9f5996 logcollector getstate'
```

Since there aren't debug messages from `remoted` that can tell us when that information is ready, we need to discuss whether to increase the delay after restarting or consider this as a core issue.

**Comment by vicferpoy** [comment]
# Issue update

After discussing this issue with the team, we are marking the affected tests as `xfail` until the core team implements a new DEBUG log for `remoted` indicating that the different components statistics are ready to be retrieved.

**Comment by davidjiglesias** [comment]
With the changes done in the new stats module for Wazuh v4.4.0, this issue does not longer exist.
