### ISSUE TITLE
Docker listener doesn't show a human readable message when the docker service is not running. 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#13776]
After configuring the Wazuh docker listener, if the `docker` service is not running, the docker wodle shows the following errors: 
```
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: Traceback (most recent call last):
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     chunked=chunked,
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     conn.request(method, url, **httplib_request_kw)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 1254, in request
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self._send_request(method, url, body, headers, encode_chunked)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self.endheaders(body, encode_chunked=encode_chunked)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self._send_output(message_body, encode_chunked=encode_chunked)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self.send(msg)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 974, in send
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self.connect()
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     sock.connect(self.unix_socket)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: FileNotFoundError: [Errno 2] No such file or directory
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: 
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: During handling of the above exception, another exception occurred:
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: 
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: Traceback (most recent call last):
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     timeout=timeout
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 550, in increment
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     raise six.reraise(type(error), error, _stacktrace)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     raise value.with_traceback(tb)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     chunked=chunked,
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     conn.request(method, url, **httplib_request_kw)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 1254, in request
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self._send_request(method, url, body, headers, encode_chunked)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self.endheaders(body, encode_chunked=encode_chunked)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self._send_output(message_body, encode_chunked=encode_chunked)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self.send(msg)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/lib64/python3.6/http/client.py", line 974, in send
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self.connect()
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     sock.connect(self.unix_socket)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: 
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: During handling of the above exception, another exception occurred:
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: 
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: Traceback (most recent call last):
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     return self.version(api_version=False)["ApiVersion"]
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in version
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     return self._result(self._get(url), json=True)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     return f(self, *args, **kwargs)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 237, in _get
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     return self.get(url, **self._set_request_timeout(kwargs))
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in get
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     return self.request('GET', url, **kwargs)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     resp = self.send(prep, **send_kwargs)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     r = adapter.send(request, **kwargs)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     raise ConnectionError(err, request=request)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: 
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: During handling of the above exception, another exception occurred:
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: 
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: Traceback (most recent call last):
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "wodles/docker/DockerListener", line 146, in <module>
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     dl = DockerListener()
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "wodles/docker/DockerListener", line 43, in __init__
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self.client = docker.from_env()
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 101, in from_env
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     **kwargs_from_env(**kwargs)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 45, in __init__
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self.api = APIClient(*args, **kwargs)
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 197, in __init__
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     self._version = self._retrieve_server_version()
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:   File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR:     f'Error while fetching server API version: {e}'
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: ERROR: docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
2022/06/06 13:54:36 wazuh-modulesd:docker-listener: WARNING: Docker-listener finished unexpectedly (code 1). Retrying to run in next scheduled time...
```

The Docker wodle should show a human-readable error allowing understand that the service is not running. 

Regards, 
Alberto R

**Comment by CarlosRS9** [comment]
We have improved the Docker exception management and fixed the bug that caused the uncaught exception to fire. These are the results of the tests in Python 3.6 and Python 3.9.


## Python 3.6

To replicate this error the steps detailed in the previous message were followed, applying this DockerListener configuration:
```
  <wodle name="docker-listener">
    <interval>1m</interval>
    <attempts>5</attempts>
    <run_on_start>yes</run_on_start>
    <disabled>no</disabled>
  </wodle>
```

Once restarting Wazuh, this is the output present in the ossec.log:
```
2022/06/14 15:07:59 wazuh-modulesd[11463] main.c:94 at main(): DEBUG: Created new thread for the 'docker-listener' module.
2022/06/14 15:07:59 wazuh-modulesd:docker-listener[11463] wm_docker.c:45 at wm_docker_main(): INFO: Module docker-listener started.
2022/06/14 15:07:59 wazuh-modulesd:docker-listener[11463] wm_docker.c:58 at wm_docker_main(): INFO: Starting to listening Docker events.
2022/06/14 15:07:59 wazuh-modulesd:docker-listener[11463] wm_docker.c:62 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
```

Finally, this is the archives.log output:
```
/var/ossec/wodles/docker/DockerListener
{"integration": "docker", "docker": {"Wodle event": "Started"}}
Docker service is not running.
{"integration": "docker", "docker": {"Wodle event": "Docker service is not running"}}
Reconnecting...
```

As we can see, the exception is not present anymore and the module is attempting to reconnect to the Docker service.


## Python 3.9
