### ISSUE TITLE
API crashes when requesting large CDB lists

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#14020]
|Wazuh version|Component|
|---|---|
| 4.3.3-40315 | API |

Running a GET request on the  [/lists/files](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.cdb_list_controller.get_lists_files) endpoint results in a timeout and subsequent crash when the file is 213MB large with 6 million entries.

The analysis daemon works well with CDB lists of these sizes (and during these tests it was observed to correctly handle a file with 37.6 million entries and 1.2GB in size) which are useful for comparing values observed in events with threat intelligence information. 

The API also works well for a file with 1.2 million entries and 43MB in size. 

Reproduce by downloading or creating CDB lists with the sizes mentioned above and adding them to `/var/ossec/etc/lists` the requesting them through the API:
```
# curl -k -X GET "https://localhost:55000/lists/files/1M-malware-hashes" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [{"2d75cc1bf8e57872781f9cd04a529256": "", "00f538c3d410822e241486ca061a57ee": "", 
...
...
 "a1b22268acd738e8e9b5e5a9d842c183": ""}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "CDB list was returned", "error": 0}


curl -k -X GET "https://localhost:55000/lists/files/6M-malware-hashes" -H "Authorization: Bearer $TOKEN"
{"title": "Wazuh Internal Error", "detail": "API executor subprocess broke. A service restart may be needed", "dapi_errors": {"node01": {"error": "API executor subprocess broke. A service restart may be needed", "logfile": "WAZUH_HOME/logs/api.log"}}, "error": 901}

curl -k -X GET "https://localhost:55000/lists/files/37M-malware-hashes" -H "Authorization: Bearer $TOKEN"
{"title": "Wazuh Internal Error", "detail": "One of the API child processes terminated abruptly. The API process pool is not usable anymore. Please restart the Wazuh API", "dapi_errors": {"node01": {"error": "One of the API child processes terminated abruptly. The API process pool is not usable anymore. Please restart the Wazuh API", "logfile": "WAZUH_HOME/logs/api.log"}}, "error": 900}
```

The `api.log` file states:
```
2022/06/24 17:30:53 INFO: wazuh-wui 127.0.0.1 "GET /lists/files/1M-malware-hashes" with parameters {} and body {} done in 6.251s: 200
2022/06/24 17:31:10 ERROR: API executor subprocess broke. A service restart may be needed
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.3-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 287, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.3-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 293, in execute_local_request
    raise exception.WazuhInternalError(901)
wazuh.core.exception.WazuhInternalError: Error 901 - API executor subprocess broke. A service restart may be needed
2022/06/24 17:31:10 INFO: wazuh-wui 127.0.0.1 "GET /lists/files/6M-malware-hashes" with parameters {} and body {} done in 5.156s: 500
2022/06/24 17:31:23 ERROR: One of the API child processes terminated abruptly. The API process pool is not usable anymore. Please restart the Wazuh API
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.3-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 282, in execute_local_request
    task = loop.run_in_executor(pool, partial(self.run_local, self.f, self.f_kwargs,
  File "uvloop/loop.pyx", line 2695, in uvloop.loop.Loop.run_in_executor
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 681, in submit
    raise BrokenProcessPool(self._broken)
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.3-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 297, in execute_local_request
    raise exception.WazuhInternalError(900)
wazuh.core.exception.WazuhInternalError: Error 900 - One of the API child processes terminated abruptly. The API process pool is not usable anymore. Please restart the Wazuh API
2022/06/24 17:31:23 INFO: wazuh-wui 127.0.0.1 "GET /lists/files/37M-malware-hashes" with parameters {} and body {} done in 0.037s: 500
```

**Comment by vicferpoy** [comment]
I understand that, but this issue only comes with the JSON representation of the CDB list, as potentially every line in the file will add a new key to the JSON object. If the query parameter `raw=true` is added, the file content is returned without any timeouts and using the least amount of memory.

**Comment by vicferpoy** [comment]
# Issue update

Finally, we have decided to implement a small improvement for `4.4` and leave the whole fix (https://github.com/wazuh/wazuh/issues/14199) for later versions as it requires better design and planification.
