### ISSUE TITLE
`wazuh-apid` did not start correctly - embedded null byte

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#14089]
|Wazuh version|Component|System|
|---|---|---|
| 4.3.5-1 | wazuh-apid | CentOS 7 |

Starting the manager installed in `/opt` directory I have seen the following error in `wazuh-apid`:

```
ValueError: embedded null byte
wazuh-apid did not start correctly.
```

<details><summary>wazuh-control start output error</summary>

```
[root@centos7 centos]# yum localinstall wazuh-manager-4.3.5-1.x86_64.rpm -y
Loaded plugins: fastestmirror
Examining wazuh-manager-4.3.5-1.x86_64.rpm: wazuh-manager-4.3.5-1.x86_64
Marking wazuh-manager-4.3.5-1.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package wazuh-manager.x86_64 0:4.3.5-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================
 Package                Arch            Version            Repository                              Size
========================================================================================================
Installing:
 wazuh-manager          x86_64          4.3.5-1            /wazuh-manager-4.3.5-1.x86_64          436 M

Transaction Summary
========================================================================================================
Install  1 Package

Total size: 436 M
Installed size: 436 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wazuh-manager-4.3.5-1.x86_64                                                                                                                                                                    1/1 
  Verifying  : wazuh-manager-4.3.5-1.x86_64                                                         1/1 

Installed:
  wazuh-manager.x86_64 0:4.3.5-1                                                                        

Complete!
[root@centos7 centos]# /opt/ossec/bin/wazuh-control start
Starting Wazuh v4.3.5...
Traceback (most recent call last):
  File "/opt/ossec/api/scripts/wazuh-apid.py", line 206, in <module>
    import connexion
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/connexion/__init__.py", line 5, in <module>
    from .apis import AbstractAPI  # NOQA
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/connexion/apis/__init__.py", line 1, in <module>
    from .abstract import AbstractAPI  # NOQA
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/connexion/apis/abstract.py", line 13, in <module>
    from ..operations import make_operation
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/connexion/operations/__init__.py", line 1, in <module>
    from .abstract import AbstractOperation  # noqa
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/connexion/operations/abstract.py", line 9, in <module>
    from ..decorators.response import ResponseValidator
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/connexion/decorators/response.py", line 11, in <module>
    from .validation import ResponseBodyValidator
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/connexion/decorators/validation.py", line 6, in <module>
    import pkg_resources
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3268, in _initialize_master_working_set
    tuple(
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3269, in <genexpr>
    dist.activate(replace=False)
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2780, in activate
    fixup_namespace_packages(self.location)
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2293, in fixup_namespace_packages
    subpath = _handle_ns(package, path_item)
  File "/opt/ossec/framework/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2194, in _handle_ns
    loader = importer.find_spec(packageName).loader
  File "<frozen importlib._bootstrap_external>", line 1532, in find_spec
  File "<frozen importlib._bootstrap_external>", line 156, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 142, in _path_stat
ValueError: embedded null byte
wazuh-apid did not start correctly.
[root@centos7 centos]#
```

</details>

<details><summary>Additional outputs</summary>

```
[root@centos7 centos]# /opt/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.5"
WAZUH_REVISION="40317"
WAZUH_TYPE="server"
[root@centos7 centos]#
```

```
[root@centos7 centos]# /opt/ossec/bin/wazuh-clusterd -fdd
[root@centos7 centos]#
```

```
[root@centos7 centos]# /opt/ossec/bin/wazuh-apid -fdd
2022/06/29 15:58:58 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2022/06/29 15:58:58 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key
2022/06/29 15:58:58 INFO: Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt
Starting API in foreground
2022/06/29 15:59:02 INFO: Listening on 0.0.0.0:55000..
======== Running on https://0.0.0.0:55000/ ========
(Press CTRL+C to quit)
```

- After running the command above:

```
[root@centos7 centos]# ps aux | grep wazuh
root      2106  0.0  0.1  13000  1448 pts/0    S+   15:58   0:00 /bin/sh /opt/ossec/bin/wazuh-apid -fdd
wazuh     2112  3.8  9.5 639984 97300 pts/0    Sl+  15:58   0:04 /opt/ossec/framework/python/bin/python3 /opt/ossec/api/scripts/wazuh-apid.py -fdd
wazuh     2113  0.0  5.5 212348 55848 pts/0    S+   15:58   0:00 /opt/ossec/framework/python/bin/python3 /opt/ossec/api/scripts/wazuh-apid.py -fdd
wazuh     2116  0.0  5.6 297236 57196 pts/0    S+   15:58   0:00 /opt/ossec/framework/python/bin/python3 /opt/ossec/api/scripts/wazuh-apid.py -fdd
root      2173  0.0  0.0  12528   972 pts/1    R+   16:00   0:00 grep --color=auto wazuh
[root@centos7 centos]#
```

</details>

It was not possible to reproduce the error, there are no log files available.

Regards, Raúl.

**Comment by AdriiiPRodri** [comment]
## Status update
After multiple tests and attempts we have not been able to reproduce the error. We believe that this error may be directly related to the system where Wazuh is installed and the dependencies installed on it.

For testing we have started from CentOS 7 without any modification or dependency installed, we have used the system as it is, just we have installed `Openssl`.

When we installed Wazuh the YUM package manager installs the necessary dependencies for the proper functioning of the package, once installed Wazuh starts correctly, the API is functional as well as the Cluster and the libraries linked to the python embedded in Wazuh are correctly located (`/opt/ossec/lib/`) for this package, which is installed in `/opt`.

### Installation log
```
adriiiprodri@wazuh docker run -it --rm -v $(pwd):/pkg centos:7                         
[root@132f46125d82 /]# yum install ./pkg/wazuh-manager-4.3.5-1.x86_64.rpm 
Loaded plugins: fastestmirror, ovl
Examining ./pkg/wazuh-manager-4.3.5-1.x86_64.rpm: wazuh-manager-4.3.5-1.x86_64
Marking ./pkg/wazuh-manager-4.3.5-1.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package wazuh-manager.x86_64 0:4.3.5-1 will be installed
--> Processing Dependency: /sbin/service for package: wazuh-manager-4.3.5-1.x86_64
Determining fastest mirrors
 * base: mirror.airenetworks.es
 * extras: mirror.airenetworks.es
 * updates: mirror.airenetworks.es
base                                                                                                                                                                                           | 3.6 kB  00:00:00     
extras                                                                                                                                                                                         | 2.9 kB  00:00:00     
updates                                                                                                                                                                                        | 2.9 kB  00:00:00     
(1/4): base/7/x86_64/group_gz                                                                                                                                                                  | 153 kB  00:00:00     
(2/4): extras/7/x86_64/primary_db                                                                                                                                                              | 247 kB  00:00:00     
(3/4): base/7/x86_64/primary_db                                                                                                                                                                | 6.1 MB  00:00:00     
(4/4): updates/7/x86_64/primary_db                                                                                                                                                             |  16 MB  00:00:00     
--> Processing Dependency: /sbin/service for package: wazuh-manager-4.3.5-1.x86_64
--> Running transaction check
---> Package initscripts.x86_64 0:9.49.53-1.el7_9.1 will be installed
--> Processing Dependency: sysvinit-tools >= 2.87-5 for package: initscripts-9.49.53-1.el7_9.1.x86_64
--> Processing Dependency: iproute for package: initscripts-9.49.53-1.el7_9.1.x86_64
--> Running transaction check
---> Package iproute.x86_64 0:4.11.0-30.el7 will be installed
--> Processing Dependency: libmnl.so.0(LIBMNL_1.0)(64bit) for package: iproute-4.11.0-30.el7.x86_64
--> Processing Dependency: libxtables.so.10()(64bit) for package: iproute-4.11.0-30.el7.x86_64
--> Processing Dependency: libmnl.so.0()(64bit) for package: iproute-4.11.0-30.el7.x86_64
---> Package sysvinit-tools.x86_64 0:2.88-14.dsf.el7 will be installed
--> Running transaction check
---> Package iptables.x86_64 0:1.4.21-35.el7 will be installed
--> Processing Dependency: libnfnetlink.so.0()(64bit) for package: iptables-1.4.21-35.el7.x86_64
--> Processing Dependency: libnetfilter_conntrack.so.3()(64bit) for package: iptables-1.4.21-35.el7.x86_64
---> Package libmnl.x86_64 0:1.0.3-7.el7 will be installed
--> Running transaction check
---> Package libnetfilter_conntrack.x86_64 0:1.0.6-1.el7_3 will be installed
---> Package libnfnetlink.x86_64 0:1.0.1-4.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================================================================================================================
 Package                                                Arch                                   Version                                            Repository                                                     Size
======================================================================================================================================================================================================================
Installing:
 wazuh-manager                                          x86_64                                 4.3.5-1                                            /wazuh-manager-4.3.5-1.x86_64                                 436 M
Installing for dependencies:
 initscripts                                            x86_64                                 9.49.53-1.el7_9.1                                  updates                                                       440 k
 iproute                                                x86_64                                 4.11.0-30.el7                                      base                                                          805 k
 iptables                                               x86_64                                 1.4.21-35.el7                                      base                                                          432 k
 libmnl                                                 x86_64                                 1.0.3-7.el7                                        base                                                           23 k
 libnetfilter_conntrack                                 x86_64                                 1.0.6-1.el7_3                                      base                                                           55 k
 libnfnetlink                                           x86_64                                 1.0.1-4.el7                                        base                                                           26 k
 sysvinit-tools                                         x86_64                                 2.88-14.dsf.el7                                    base                                                           63 k

Transaction Summary
======================================================================================================================================================================================================================
Install  1 Package (+7 Dependent packages)

Total size: 438 M
Total download size: 1.8 M
Installed size: 442 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/base/packages/libmnl-1.0.3-7.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for libmnl-1.0.3-7.el7.x86_64.rpm is not installed
(1/7): libmnl-1.0.3-7.el7.x86_64.rpm                                                                                                                                                           |  23 kB  00:00:00     
Public key for initscripts-9.49.53-1.el7_9.1.x86_64.rpm is not installed
(2/7): initscripts-9.49.53-1.el7_9.1.x86_64.rpm                                                                                                                                                | 440 kB  00:00:00     
(3/7): iptables-1.4.21-35.el7.x86_64.rpm                                                                                                                                                       | 432 kB  00:00:00     
(4/7): iproute-4.11.0-30.el7.x86_64.rpm                                                                                                                                                        | 805 kB  00:00:00     
(5/7): libnfnetlink-1.0.1-4.el7.x86_64.rpm                                                                                                                                                     |  26 kB  00:00:00     
(6/7): libnetfilter_conntrack-1.0.6-1.el7_3.x86_64.rpm                                                                                                                                         |  55 kB  00:00:00     
(7/7): sysvinit-tools-2.88-14.dsf.el7.x86_64.rpm                                                                                                                                               |  63 kB  00:00:00     
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                 8.5 MB/s | 1.8 MB  00:00:00     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-9.2009.0.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Is this ok [y/N]: y
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : libmnl-1.0.3-7.el7.x86_64                                                                                                                                                                          1/8 
  Installing : libnfnetlink-1.0.1-4.el7.x86_64                                                                                                                                                                    2/8 
  Installing : libnetfilter_conntrack-1.0.6-1.el7_3.x86_64                                                                                                                                                        3/8 
  Installing : iptables-1.4.21-35.el7.x86_64                                                                                                                                                                      4/8 
  Installing : iproute-4.11.0-30.el7.x86_64                                                                                                                                                                       5/8 
  Installing : sysvinit-tools-2.88-14.dsf.el7.x86_64                                                                                                                                                              6/8 
  Installing : initscripts-9.49.53-1.el7_9.1.x86_64                                                                                                                                                               7/8 
  Installing : wazuh-manager-4.3.5-1.x86_64                                                                                                                                                                       8/8 
  Verifying  : wazuh-manager-4.3.5-1.x86_64                                                                                                                                                                       1/8 
  Verifying  : libnfnetlink-1.0.1-4.el7.x86_64                                                                                                                                                                    2/8 
  Verifying  : initscripts-9.49.53-1.el7_9.1.x86_64                                                                                                                                                               3/8 
  Verifying  : libmnl-1.0.3-7.el7.x86_64                                                                                                                                                                          4/8 
  Verifying  : libnetfilter_conntrack-1.0.6-1.el7_3.x86_64                                                                                                                                                        5/8 
  Verifying  : iproute-4.11.0-30.el7.x86_64                                                                                                                                                                       6/8 
  Verifying  : sysvinit-tools-2.88-14.dsf.el7.x86_64                                                                                                                                                              7/8 
  Verifying  : iptables-1.4.21-35.el7.x86_64                                                                                                                                                                      8/8 

Installed:
  wazuh-manager.x86_64 0:4.3.5-1                                                                                                                                                                                      

Dependency Installed:
  initscripts.x86_64 0:9.49.53-1.el7_9.1  iproute.x86_64 0:4.11.0-30.el7 iptables.x86_64 0:1.4.21-35.el7 libmnl.x86_64 0:1.0.3-7.el7 libnetfilter_conntrack.x86_64 0:1.0.6-1.el7_3 libnfnetlink.x86_64 0:1.0.1-4.el7
  sysvinit-tools.x86_64 0:2.88-14.dsf.el7

Complete!
```

### Checks
```
[root@4d649b8f5038 /]# /opt/ossec/bin/wazuh-control start
Starting Wazuh v4.3.5...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/07/01 09:35:02 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
[root@132f46125d82 /]# ls /opt/ossec/lib/
libdbsync.so  libpython3.9.so.1.0  librsync.so  libsyscollector.so  libsysinfo.so  libwazuhext.so  libwazuhshared.so
[root@132f46125d82 /]# /opt/ossec/bin/wazuh-apid -fdd
wazuh-apid: Orphan child process 1143 was terminated.
wazuh-apid: Orphan child process 1140 was terminated.
wazuh-apid: Orphan child process 1004 was terminated.
Starting API in foreground
2022/06/30 14:53:09 INFO: Listening on 0.0.0.0:55000..
======== Running on https://0.0.0.0:55000 ========
(Press CTRL+C to quit)
^C
[root@132f46125d82 /]# vi /opt/ossec/etc/ossec.conf 
[root@132f46125d82 /]# /opt/ossec/bin/wazuh-clusterd -fdd
2022/06/30 14:54:39 DEBUG: [Cluster] [Main] Removing '/opt/ossec/queue/cluster/'.
2022/06/30 14:54:39 DEBUG: [Cluster] [Main] Removed '/opt/ossec/queue/cluster/'.
Starting cluster in foreground (pid: 1287)
2022/06/30 14:54:39 INFO: [Local Server] [Main] Serving on /opt/ossec/queue/cluster/c-internal.sock
2022/06/30 14:54:39 DEBUG: [Local Server] [Keep alive] Calculating.
2022/06/30 14:54:39 DEBUG: [Local Server] [Keep alive] Calculated.
2022/06/30 14:54:39 INFO: [Master] [Main] Serving on ('0.0.0.0', 1516)
2022/06/30 14:54:39 DEBUG: [Master] [Keep alive] Calculating.
2022/06/30 14:54:39 DEBUG: [Master] [Keep alive] Calculated.
2022/06/30 14:54:39 INFO: [Master] [Local integrity] Starting.
2022/06/30 14:54:40 INFO: [Master] [Local integrity] Finished in 0.107s. Calculated metadata of 33 files.
2022/06/30 14:54:41 INFO: [Cluster] [Main] SIGINT received. Bye!
^C
```

### Python imports
```
[root@64b19bedc88e /]# /opt/ossec/framework/python/bin/python3          
Python 3.9.9 (main, Jun  8 2022, 15:34:33) 
[GCC 5.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import connexion
>>> import pkg_resources
```

**Comment by davidjiglesias** [comment]
After a lot of tries from different testers we were not able to replicate the problem.
