### ISSUE TITLE
wazuh-alerts-* [no results found]

### ISSUE THREAD

**Issue by kengees** [wazuh/wazuh#143]
Hello, i need yr help please, i'm a new member of wazuh, i've just follow the wzush online document 2.0 guide for system installation. The installation was done, i saw the "wazuh-monitoring-*" and "wazuh-alerts-*" index, but only "wazuh-monitoring-*" have data, but wazuh-alerts-* [no results found]. May you help me ?

thanks

**Comment by kengees** [comment]
Let me give you more infor, as the following:
File: 01-wazuh.conf
## Local Wazuh Manager - JSON file input
input {
   file {
       type => "wazuh-alerts"
       path => "/var/ossec/logs/alerts/alerts.json"
       codec => "json"
   }
}

**Comment by jnarvaezp** [comment]
hi @kengees,

Please attach the logstash log (/var/log/logstash/logstash-plain.log), and elasticsearch /var/log/elasticsearch/elasticsearch.log) to see a possible error.

Thank you

**Comment by kengees** [comment]
Thank you for your fast response and help, this is the file
[logstash-plain.zip](https://github.com/wazuh/wazuh/files/1076525/logstash-plain.zip)

**Comment by jnarvaezp** [comment]
Hi
Let's do these three actions
**Test elasticsearch** 
1. run this command `curl -XGET localhost:9200`, You get similar output 

```
{
  "name": "node1",
  "cluster_name": "ossec",
  "version": {
    "number": "2.1.1",
    "build_hash": "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp": "2015-12-15T13:05:55Z",
    "build_snapshot": false,
    "lucene_version": "5.3.1"
  },
  "tagline": "You Know, for Search"
}
```

2. Run this command  `curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'`, You get similar output 

```
{
  "cluster_name": "ossec",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 2,
  "number_of_data_nodes": 2,
  "active_primary_shards": 281,
  "active_shards": 562,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
```
3: stop and start service logstash 

when logstash stop( ej: systemclt stop logstsh), verify service has stopped with ps -aux|grep logstash, and start again de service.

Thanks

**Comment by kengees** [comment]
Hello, this is my result:

curl -XGET localhost:9200
{
  "name" : "39Wazh1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "KkKcT3UISviJ5lPWVJbbXA",
  "version" : {
    "number" : "5.4.1",
    "build_hash" : "2cfe0df",
    "build_date" : "2017-05-29T16:05:51.443Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  },
  "tagline" : "You Know, for Search"
}

curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "elasticsearch",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 15,
  "active_shards" : 15,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 15,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 50.0
}

initctl status logstash
logstash start/running, process 1008

ps aux | grep logstash
logstash  1008  7.5 11.9 4665696 469952 ?      SNsl Jun12 305:37 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Xmx1g -Xms256m -Xss2048k -Djffi.boot.library.path=/usr/share/logstash/vendor/jruby/lib/jni -Xbootclasspath/a:/usr/share/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/usr/share/logstash/vendor/jruby -Djruby.lib=/usr/share/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main /usr/share/logstash/lib/bootstrap/environment.rb logstash/runner.rb --path.settings /etc/logstash

initctl restart logstash
logstash start/running, process 19400

**Comment by jnarvaezp** [comment]
Hi,
after restart logstash, appear errors in /var/logs/logstash/logstash-plain.log ?

JN

**Comment by kengees** [comment]
[logstash-plain.zip](https://github.com/wazuh/wazuh/files/1076610/logstash-plain.zip)
i don't see any abnormal issue in logstash-plain.log

**Comment by jnarvaezp** [comment]
Hi, 

Are you installed Wazuh-Manager + ELK on the same server?
What OS version are you using, or Amazon AMI?

JN

**Comment by kengees** [comment]
Hi, 

Yes, I'm using Single-host architecture, It is CentOS 6.5 (64bits)

Ken

**Comment by jlruizmlg** [comment]
Hi @kengees please, take a look from the following link:

https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#logstash 

Please be sure you have done the step **3b** ```usermod -a -G ossec logstash```,  which is add Logstash group to Ossec group in order to give permissions to Logstash to read the file alerts.json.

**Comment by kengees** [comment]
Hi @jlruizmlg

   Thanks for your response, i did it.
   Following the online doc (2.0 version) from Wazuh website, I've installed three time already, but the problem still exist. The Wazuh-monitoring have result but wazuh-alert have nothing. So sad..... :(

Ken,

**Comment by kengees** [comment]
Hi all,

About the "Wazuh-alert" i think it should have some "Available Fields" auto appear in the left panel such as the "wazuh-monitor", but it doesn't has.

Ken,

**Comment by jlruizmlg** [comment]
HI @kengees looking your elasticsearch log i see one error, 

```
[2017-06-14T14:56:29,320][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/OWvah-AsQBKzy9Hk3VZDpg] update_mapping [config]
[2017-06-14T16:04:24,670][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [39Wazh1] failed to put mappings on indices [[[.kibana/OWvah-AsQBKzy9Hk3VZDpg]]], type [timelion-sheet]
java.lang.IllegalArgumentException: mapper [hits] cannot be changed from type [long] to [integer]
	at org.elasticsearch.index.mapper.MappedFieldType.checkTypeName(MappedFieldType.java:147) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.index.mapper.MappedFieldType.checkCompatibility(MappedFieldType.java:159) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:128) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.index.mapper.FieldTypeLookup.copyAndAddAll(FieldTypeLookup.java:94) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:398) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:334) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:266) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:311) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaData
```
Seems like the mapping have not been applied properly.

Try the next steps: 

1. Turn off logstash (and be sure logstash is off with ps axu | grep logstash)
2. Turn off Kibana (and be sure logstash is off with ps axu | grep kibana)
3. Remove Wazuh-app plugin with ```/usr/share/kibana/bin/kibana-plugin remove wazuh```
4. Remove all your index (because you don't have any information there) with ```curl -XDELETE localhost:9200/*```
5. Load Wazuh Elasticsearch template with the following command please note that this is **ONE** command so copy both lines and paste it the same time:
```
curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/master/server/startup/integration_files/template_file.json | \
curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
```
6. Insert sample alert please note that this is **ONE** command so copy both lines and paste it the same time:
```
curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/master/server/startup/integration_files/alert_sample.json | \
curl -XPUT "http://localhost:9200/wazuh-alerts-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @-
```
7. Install wazuh-app again: ```/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip``` , this operation can take a while in finish.

8. Start Kibana and Logstash again.

**Comment by kengees** [comment]
Hi @jlruizmlg

    Thanks, i did as you wrote, 

Step 1:  initctl stop logstash
logstash stop/waiting

ps aux|grep logstash
root      2391  0.0  0.0 103332   844 pts/0    S+   10:10   0:00 grep logstash

Step 2: /etc/init.d/kibana stop
kibana stopped.

ps aux|grep kibana
root      2409  0.0  0.0 103332   848 pts/0    S+   10:10   0:00 grep kibana

Step 3: /usr/share/kibana/bin/kibana-plugin remove wazuh
Removing wazuh...

curl -XDELETE http://localhost:9200/*
{"acknowledged":true}

curl -XGET http://localhost:9200/_cat/indices
--> all index were deleted

Step 4:
curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/master/server/startup/integration_files/template_file.json | \
> curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15547  100 15547    0     0  19160      0 --:--:-- --:--:-- --:--:-- 42594
{"acknowledged":true}

Step 5: 
curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/master/server/startup/integration_files/alert_sample.json | \
> curl -XPUT "http://localhost:9200/wazuh-alerts-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @-
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
102  1432  102  1432    0     0   2351      0 --:--:-- --:--:-- --:--:--  4546
{"_index":"wazuh-alerts-2017.06.16","_type":"wazuh","_id":"sample","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"created":true}

 curl -XGET http://localhost:9200/_cat/indices
yellow open wazuh-alerts-2017.06.16 N7dmMi5aT3G27H26QMm_gQ 5 1 0 0 260b 260b

Step 6:
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Transferring 16648679 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete

Step 7: /etc/init.d/kibana restart
Step 8: initctl start logstash

curl -XGET http://localhost:9200/_cat/indices
yellow open .kibana                     -Nu69ipMQLCRCcY0Imp2NA 5 1 113 1 179.4kb 179.4kb
yellow open wazuh-alerts-2017.06.16     N7dmMi5aT3G27H26QMm_gQ 5 1   2 0  37.3kb  37.3kb
yellow open wazuh-monitoring-2017.06.16 WWeZfJkMRBiYgm9dcu2R0A 5 1   3 0  14.9kb  14.9kb

**Comment by kengees** [comment]
This is the elasticsearch log from i delete the index untill rebuild them

[2017-06-16T10:11:30,514][INFO ][o.e.c.m.MetaDataDeleteIndexService] [39Wazh1] [wazuh-monitoring-2017.06.16/E5oE_XYWRvW9ldiRbdJe7w] deleting index
[2017-06-16T10:11:30,514][INFO ][o.e.c.m.MetaDataDeleteIndexService] [39Wazh1] [wazuh-monitoring-2017.06.15/pwE_Bz2fQ-2ho18zSo8p2g] deleting index
[2017-06-16T10:11:30,515][INFO ][o.e.c.m.MetaDataDeleteIndexService] [39Wazh1] [wazuh-monitoring-2017.06.12/_IPU5NGoS6W4EUksi_4H8A] deleting index
[2017-06-16T10:11:30,515][INFO ][o.e.c.m.MetaDataDeleteIndexService] [39Wazh1] [wazuh-alerts-2017.06.12/HHldpD4aRzGIT2qz9ezJiw] deleting index
[2017-06-16T10:11:30,515][INFO ][o.e.c.m.MetaDataDeleteIndexService] [39Wazh1] [.kibana/OWvah-AsQBKzy9Hk3VZDpg] deleting index
[2017-06-16T10:13:55,347][INFO ][o.e.c.m.MetaDataCreateIndexService] [39Wazh1] [wazuh-alerts-2017.06.16] creating index, cause [auto(bulk api)], templates [wazuh], shards [5]/[1], mappings [agent, wazuh]
[2017-06-16T10:13:55,995][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [wazuh-alerts-2017.06.16/N7dmMi5aT3G27H26QMm_gQ] update_mapping [wazuh]
[2017-06-16T10:20:58,997][INFO ][o.e.c.m.MetaDataCreateIndexService] [39Wazh1] [.kibana] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2017-06-16T10:20:59,534][INFO ][o.e.c.m.MetaDataCreateIndexService] [39Wazh1] [wazuh-monitoring-2017.06.16] creating index, cause [api], templates [wazuh], shards [5]/[1], mappings [agent, wazuh]
[2017-06-16T10:21:01,075][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] create_mapping [wazuh-setup]
[2017-06-16T10:21:01,191][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] create_mapping [index-pattern]
[2017-06-16T10:21:01,258][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] create_mapping [dashboard]
[2017-06-16T10:21:01,568][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] update_mapping [dashboard]
[2017-06-16T10:21:01,710][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] create_mapping [search]
[2017-06-16T10:21:01,760][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] create_mapping [visualization]
[2017-06-16T10:21:02,232][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] create_mapping [config]
[2017-06-16T10:21:03,624][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] update_mapping [config]
[2017-06-16T10:21:37,479][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] update_mapping [config]
[2017-06-16T10:22:38,044][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [39Wazh1] failed to put mappings on indices [[[.kibana/-Nu69ipMQLCRCcY0Imp2NA]]], type [timelion-sheet]
java.lang.IllegalArgumentException: mapper [hits] cannot be changed from type [long] to [integer]
        at org.elasticsearch.index.mapper.MappedFieldType.checkTypeName(MappedFieldType.java:147) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.mapper.MappedFieldType.checkCompatibility(MappedFieldType.java:159) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:128) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.mapper.FieldTypeLookup.copyAndAddAll(FieldTypeLookup.java:94) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:398) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:334) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:266) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:311) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:633) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:611) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:570) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:262) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-5.4.1.jar:5.4.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[2017-06-16T10:23:31,626][INFO ][o.e.c.m.MetaDataMappingService] [39Wazh1] [.kibana/-Nu69ipMQLCRCcY0Imp2NA] create_mapping [wazuh-configuration]

**Comment by jlruizmlg** [comment]
Hi @kengees sorry for the delay in my response,  seems like in CentOS 6, logstash use Upstart like service.

With upstart exists one [bug](https://bugs.launchpad.net/upstart/+bug/812870) where we cannot assign supplementary groups to user job processes.
This means, the command ```usermod -a -G ossec logstash``` doesn't apply here.

Please try the next steps:

1. Stop logstash service (and be sure logstash is off with ps axu | grep logstash)
2. Edith the file ```/etc/logstash/startup.options``` and in the line 30 change the LS_GROUP=logstash to LS_GROUP=ossec.
3. Update the service with the new parameters run the command ```/usr/share/logstash/bin/system-install```
4. Start Logstash again.

You can restart your manager if you want in order to create some alerts in your system and verify in Kibana.

**Comment by kengees** [comment]
Hi @jlruizmlg

     Thank you so much, i tried as you noted, but problem still exits. I think i will change to use CentOS 7. I hope that everything will be fine.

     Thanks all,

Ken

**Comment by jlruizmlg** [comment]
Hi @kengees 

Can you run this command? ```lsof /var/ossec/logs/alerts/alerts.json```
You should have two process reading this file, one ossec-analysisd and other java (which is logstash)

Can you confirm this two processes are running in your alerts.json?

**Comment by kengees** [comment]
Hi @jlruizmlg

Sure, this is the result:

lsof /var/ossec/logs/alerts/alerts.json
COMMAND    PID     USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
java      1019 logstash   60u   REG    8,3    17197 1710578 /var/ossec/logs/alerts/alerts.json
ossec-ana 2225    ossec    9w   REG    8,3    17197 1710578 /var/ossec/logs/alerts/alerts.json

Ken

**Comment by jlruizmlg** [comment]
Hi @kengees , this is the correct.

This is weird, all your configuration seems be correct, I'm curious why it may be happening, would you mind having a quick meeting with me to look your server?

Maybe your problem is a bug which has not been detected yet and we like to have a closer look closer look in your issue.

If you are ok with that, please send me a mail to jose (@) wazuh (.) com

**Comment by kengees** [comment]
Hi @jlruizmlg 

    I'm rebuilding it with CentOS 7, so the server was formatted. So sorry can't support you to check more this issue, i hope that it will be fine in CentOS7. 

   Thanks all

Ken

**Comment by jlruizmlg** [comment]
hi @kengees no problem, can you confirm if it's working with CentOS-7?

**Comment by kengees** [comment]
Hi @jlruizmlg 
 
    Not yet, i got a problem

 /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Transferring 16648679 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.4.2]; found [5.4.1]"

:(

Ken

**Comment by jlruizmlg** [comment]
@kengees yes, they release Kibana 5.4.2 a couple days ago, we are updating wazuhapp to work with this new version, in a couple hours should be ready, i will keep you post.

**Comment by kengees** [comment]
@jlruizmlg 

i just try change the version in the file name, i can download and install it ^^

/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuh
app-2.0_5.4.2.zip

**Comment by jlruizmlg** [comment]
@kengees this is not a release version, we are testing this version in our labs now, this is why is not public with the name wazuhapp.zip, or update in our github repositories.

You are our first beta-tester today. :)

**Comment by kengees** [comment]
oh really, that sound great :)

**Comment by kengees** [comment]
hi @jlruizmlg

That is great, good news

It works now

let me show you
![wazuh-centos7-5 4 2](https://user-images.githubusercontent.com/29446330/27374966-e9d1845c-5697-11e7-920f-9e5bc290b2af.jpg)

Ken

**Comment by jlruizmlg** [comment]
@kengees very good news! thanks for your patience with us!! try the app as well, should be work now.

**Comment by kengees** [comment]
@jlruizmlg

Thank you so much, this project is really great, i love it.

Will let you know the experience after testing.

Thanks again

Ken

**Comment by jlruizmlg** [comment]
@kengees cool, i will keep this issue open for one or two more days, waiting your news about your experience.

**Comment by kengees** [comment]
@jlruizmlg

    OK

Ken

**Comment by kengees** [comment]
hi @jlruizmlg

   I think this version is ok now, everything is fine: wazuh-alerts; wazuh-monitor; agent; 
manager, dashboards, ossec also. I don't find out any abnormal issue now. 

  I think people should use wazuh by CentOS7, this will be better.

  Once again, thank you so much and nice to meet you.

Ken

**Comment by jlruizmlg** [comment]
Perfect @kengees, thanks for your feedback,  please fell free to create as new issues as you need, nice to meet you too and welcome to our wazuh family! :)

**Comment by webboy47** [comment]
Hello,
I am facing certain issues, Wazuh-alerts are not shown in the wazuh app. My install is on debian9, ELK (all version 5.5.2). I have installed wazuh using /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.0_5.5.2.zip.
Any help will  be appreciated.
Best Regards.

**Comment by snaow** [comment]
Hi @webboy47,

If you agree, we can keep the conversation in your issue at https://github.com/wazuh/wazuh-kibana-app/issues/25

Best regards,
Pedro.
