### ISSUE TITLE
Filebeat Maximum of 1000 shards reached?

### ISSUE THREAD

**Issue by rwjack** [wazuh/wazuh#14652]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4301-1 | Filebeat? | Manager | Sources (unattended-installation.sh) | Debian 11 |

Hello,

I've been getting strange issues lately which I'm unsure how to resolve.
Wazuh simply stops showing any logs, but luckily they do get logged in `alerts.json`.

Looking around the interwebz yielded no valid solution, so I went hardcore and reverted the VM a week back. Worked like a charm (for a week) until the same issues appeared again today.

One noticeable issue that I also found on google forums:

`systemctl status filebeat`:
```
Aug 16 17:03:49 sierra filebeat[520]: 2022-08-16T17:03:49.797+0200        WARN        [elasticsearch]        elasticsearch/client.go:408        Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xc0b70a552f544e68, ext:354569171825743, loc:(*time.Location)(0x42417a0)}, Meta:{"pipeline":"filebeat-7.10.2-wazuh-alerts-pipeline"}, Fields:{"agent"
...
SNIP
...
{"type":"validation_exception","reason":"Validation Failed: 1: this action would add [3] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"}
```

I'm not sure why this is happening, though I'm sure there's a solution for it, if you knowledgeable folks wouldn't mind sharing :)

**Comment by rwjack** [comment]
I'm not sure what these indexes/indices are, but do I need all of them?

Is this a problem with too many logs in elasticsearch?

I would like to keep at least 6 months back, is there a simple way to do a cleanup? (delete if older than 6m) Also, not like disk space is currently an issue, these logs seem quite small in size, but is there an all in one cleanup script I could somehow make to clean data from elasticsearch, /var/ossec/logs and everywhere else there would be junk (anything older than 6m).

I got confused with wazuh-alerts indexes (being for alerts), and wazuh-monitoring indexes (as I understood something for agents?)

Do I need to keep both for a 6m period (if I want to keep 6 months worth of logs) or are they somehow different?

**Comment by s-ocando** [comment]
Hi @rwjack, 

The issue is due to the maximum number of shards, or units in which the Wazuh indexer distributes data, being reached. Each Wazuh indexer node can have up to 1000 shards.

To solve the issue, you may erase, close or reindex indices. Alternatively, you may increase the maximum number of shards, although this isn't recommended as it may bring performance issues.

To assure this issue does not happen again, you may set an index management policy that automatically deletes old indices. Check our [Wazuh index management blog](https://wazuh.com/blog/wazuh-index-management/) to learn more.

Also, If you have a single-node deployment, make sure that the number of shards per index `index.number_of_shards is` set to 1 in the `/etc/filebeat/wazuh-template.json`.

Regarding your question on how to clean data in the `/var/ossec/logs` directory, you can set a cron job. For example, the following one will delete all the `.gz` files older than 90 days at 00:45 everyday. You can customize it according to your needs.

```
45 0 * * * find /var/ossec/logs/ -name "*.gz" -type f -mtime +90 -exec rm -f {} \;
```

To answer your question about the wazuh-monitoring index, it stores data related to the Wazuh agents' status over time.  Check our [Wazuh indexer documentation](https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html) to learn more about the different Wazuh indices.

**Comment by T100D** [comment]
1000 shards is a default limit in ES/OS, I have searched for a parameter that can define the limit of days/shards one wants to keep data but not jet found it.

**Comment by T100D** [comment]
Reading on I found this that could summup and do the job:

https://wazuh.com/blog/wazuh-index-management/
https://www.reddit.com/r/Wazuh/comments/vwi82a/about_the_log_retention_management/

**Comment by rwjack** [comment]
Hey, thanks for the reply. I couldn't diagnose the issue, even after applying multiple fixes from relevant posts on the google group.

Ended up reinstalling to the latest version and applying policies from the start, hopefully nothing crashes and burns this time.

**Comment by rwjack** [comment]
@s-ocando I can't believe it happened again, Wazuh is not starting, even with the applied index management policies. 

Please tell me what can I do to get it back online?

```
× wazuh-dashboard.service - wazuh-dashboard
     Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-06-16 09:24:44 CEST; 1h 24min ago
   Duration: 2min 1.178s
    Process: 1969311 ExecStart=/usr/share/wazuh-dashboard/bin/opensearch-dashboards (code=exited, status=1/FAILURE)
   Main PID: 1969311 (code=exited, status=1/FAILURE)
        CPU: 6.674s

Jun 16 09:24:42 wazuh opensearch-dashboards[1969311]: {"type":"log","@timestamp":"2024-06-16T07:24:42Z","tags":["info","savedobjects-service"],"pid":1969311,"message":"Detected mapping change in \"properties.augment-vis\""}
Jun 16 09:24:42 wazuh opensearch-dashboards[1969311]: {"type":"log","@timestamp":"2024-06-16T07:24:42Z","tags":["info","savedobjects-service"],"pid":1969311,"message":"Creating index .kibana_5."}
Jun 16 09:24:42 wazuh opensearch-dashboards[1969311]: {"type":"log","@timestamp":"2024-06-16T07:24:42Z","tags":["error","opensearch","data"],"pid":1969311,"message":"[validation_exception]: Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"}
Jun 16 09:24:42 wazuh opensearch-dashboards[1969311]: {"type":"log","@timestamp":"2024-06-16T07:24:42Z","tags":["warning","savedobjects-service"],"pid":1969311,"message":"Unable to connect to OpenSearch. Error: validation_exception: [validation_exception] Reason: Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"}
Jun 16 09:24:42 wazuh opensearch-dashboards[1969311]: {"type":"log","@timestamp":"2024-06-16T07:24:42Z","tags":["fatal","root"],"pid":1969311,"message":"ResponseError: validation_exception: [validation_exception] Reason: Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open;\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21) {\n  meta: {\n    body: { error: [Object], status: 400 },\n    statusCode: 400,\n    headers: {\n      'content-type': 'application/json; charset=UTF-8',\n      'content-length': '379'\n    },\n    meta: {\n      context: null,\n      request: [Object],\n      name: 'opensearch-js',\n      connection: [Object],\n      attempts: 0,\n      aborted: false\n    }\n  }\n}"}
Jun 16 09:24:42 wazuh opensearch-dashboards[1969311]: {"type":"log","@timestamp":"2024-06-16T07:24:42Z","tags":["info","plugins-system"],"pid":1969311,"message":"Stopping all plugins."}
Jun 16 09:24:42 wazuh opensearch-dashboards[1969311]:  FATAL  {"error":{"root_cause":[{"type":"validation_exception","reason":"Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"}],"type":"validation_exception","reason":"Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"},"status":400}
Jun 16 09:24:44 wazuh systemd[1]: wazuh-dashboard.service: Main process exited, code=exited, status=1/FAILURE
Jun 16 09:24:44 wazuh systemd[1]: wazuh-dashboard.service: Failed with result 'exit-code'.
Jun 16 09:24:44 wazuh systemd[1]: wazuh-dashboard.service: Consumed 6.674s CPU time.
```

**Comment by rwjack** [comment]
I ran this to get Wazuh back online: https://medium.com/@m.muenz/getting-rid-of-max-shards-events-in-wazuh-ddac82ef1365

But that doesn't mean it won't fail on me again. Can someone help me review the indice policy?

Is it normal to have 20 pages worth of running jobs?

![image](https://github.com/wazuh/wazuh/assets/59068073/71a4b31d-60d1-437d-9a4b-c8e2c41223d6)

**Comment by T100D** [comment]
Did jou implement jobs to set indexes from warm to cold after x days and delete them after xx days?

It's not there by default.

**Comment by rwjack** [comment]
@T100D Rollup/Transform jobs? I see I have none... Could you please confirm what and where I would need to configure?

Here's my existing State management policy:
```json
{
    "id": "hq_log_retention",
    "seqNo": 0,
    "primaryTerm": 1,
    "policy": {
        "policy_id": "hq_log_retention",
        "description": "Wazuh index state management for OpenDistro to move indices into a cold state after 3 months and delete them after a year.",
        "last_updated_time": 1666855400821,
        "schema_version": 12,
        "error_notification": null,
        "default_state": "hot",
        "states": [
            {
                "name": "hot",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "replica_count": {
                            "number_of_replicas": 0
                        }
                    }
                ],
                "transitions": [
                    {
                        "state_name": "warm",
                        "conditions": {
                            "min_index_age": "32d"
                        }
                    }
                ]
            },
            {
                "name": "warm",
                "actions": [],
                "transitions": [
                    {
                        "state_name": "cold",
                        "conditions": {
                            "min_index_age": "92d"
                        }
                    }
                ]
            },
            {
                "name": "cold",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "read_only": {}
                    }
                ],
                "transitions": [
                    {
                        "state_name": "delete",
                        "conditions": {
                            "min_index_age": "366d"
                        }
                    }
                ]
            },
            {
                "name": "delete",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ],
        "ism_template": [
            {
                "index_patterns": [
                    "wazuh-statistics*",
                    "wazuh-alerts*",
                    "wazuh-monitoring*"
                ],
                "priority": 100,
                "last_updated_time": 1661940491734
            }
        ]
    }
}
```

**Comment by T100D** [comment]
Hi,

I have setup three management policies. This is done for a complete scripted setup on one singe server. All JSON.

**hot_cold_delete_workflow_statistics**

```
{
    "id": "hot_cold_delete_workflow_statistics",
    "seqNo": 719573,
    "primaryTerm": 4,
    "policy": {
        "policy_id": "hot_cold_delete_workflow_statistics",
        "description": "Wazuh index state management for OpenDistro to move indices into a cold state after 90 days and delete them after a year.",
        "last_updated_time": 1670428364908,
        "schema_version": 12,
        "error_notification": null,
        "default_state": "hot",
        "states": [
            {
                "name": "hot",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "replica_count": {
                            "number_of_replicas": 0
                        }
                    }
                ],
                "transitions": [
                    {
                        "state_name": "cold",
                        "conditions": {
                            "min_index_age": "31d"
                        }
                    }
                ]
            },
            {
                "name": "cold",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "read_only": {}
                    }
                ],
                "transitions": [
                    {
                        "state_name": "delete",
                        "conditions": {
                            "min_index_age": "62d"
                        }
                    }
                ]
            },
            {
                "name": "delete",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ],
        "ism_template": [
            {
                "index_patterns": [
                    "wazuh-statistics*"
                ],
                "priority": 100,
                "last_updated_time": 1668088736930
            }
        ]
    }
}
```

**hot_cold_delete_workflow_monitoring**

```
{
    "id": "hot_cold_delete_workflow_monitoring",
    "seqNo": 47567834,
    "primaryTerm": 31,
    "policy": {
        "policy_id": "hot_cold_delete_workflow_monitoring",
        "description": "Wazuh index state management for OpenDistro to move indices into a cold state after 90 days and delete them after a year.",
        "last_updated_time": 1707751724357,
        "schema_version": 18,
        "error_notification": null,
        "default_state": "hot",
        "states": [
            {
                "name": "hot",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "replica_count": {
                            "number_of_replicas": 0
                        }
                    }
                ],
                "transitions": [
                    {
                        "state_name": "cold",
                        "conditions": {
                            "min_index_age": "62d"
                        }
                    }
                ]
            },
            {
                "name": "cold",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "read_only": {}
                    }
                ],
                "transitions": [
                    {
                        "state_name": "delete",
                        "conditions": {
                            "min_index_age": "126d"
                        }
                    }
                ]
            },
            {
                "name": "delete",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ],
        "ism_template": [
            {
                "index_patterns": [
                    "wazuh-monitoring*"
                ],
                "priority": 100,
                "last_updated_time": 1668088736930
            }
        ]
    }
}

```

**hot_cold_delete_workflow**

```
{
    "id": "hot_cold_delete_workflow",
    "seqNo": 17224,
    "primaryTerm": 1,
    "policy": {
        "policy_id": "hot_cold_delete_workflow",
        "description": "Wazuh index state management for OpenDistro to move indices into a cold state after 90 days and delete them after a year.",
        "last_updated_time": 1668176816255,
        "schema_version": 12,
        "error_notification": null,
        "default_state": "hot",
        "states": [
            {
                "name": "hot",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "replica_count": {
                            "number_of_replicas": 0
                        }
                    }
                ],
                "transitions": [
                    {
                        "state_name": "cold",
                        "conditions": {
                            "min_index_age": "90d"
                        }
                    }
                ]
            },
            {
                "name": "cold",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "read_only": {}
                    }
                ],
                "transitions": [
                    {
                        "state_name": "delete",
                        "conditions": {
                            "min_index_age": "180d"
                        }
                    }
                ]
            },
            {
                "name": "delete",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ],
        "ism_template": [
            {
                "index_patterns": [
                    "wazuh-alerts*"
                ],
                "priority": 100,
                "last_updated_time": 1668088736930
            }
        ]
    }
}
```

**Comment by rwjack** [comment]
So you basically have the same thing as me, except I have all the index_patterns in a single policy, instead of having 3 separate ones, and I also see I go from hot->warm->cold->delete, whereas your policies go from hot->cold->delete.

It seems my policy does in fact run, but I do not understand how I managed to fill up 1000 shards again.

**Comment by T100D** [comment]
366 days time three is 1098 shards. Could it be that? I Looks like that range should be a thad lower, like 332 days.

Could be hard if you are handling whitin US laws that require 360 days retention.

**Comment by rwjack** [comment]
Oh damn, if that's the way it's calculated, then that makes total sense. I guess I should just look into increasing the number of shards to 1200.

But even when the indice is in a cold state, it consumes a shard? I have no idea how ES/Kibana works...

**Comment by T100D** [comment]
There is a rule that states 1GB for 20 shards, but then they are ~20GB each, on wazuh they are quite small.

Could be an idea to rotate weekly instead of daily. I dont know the backend of wazuh in this. I know and use elasticsearch as graylog backend.

This could help out. If i read this correctly then using different states does not do as much as lowering the priority of the shard.

https://www.elastic.co/blog/implementing-hot-warm-cold-in-elasticsearch-with-index-lifecycle-management

**Comment by rwjack** [comment]
closing because I don't care anymore.
