### ISSUE TITLE
API logtest Endpoint Throwing Error

### ISSUE THREAD

**Issue by mthbrown** [wazuh/wazuh#14705]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.6 | Wazuh RESTful API | Manager | Packages | OS version |

Hi,

I wanted to test a rule using `location` so I couldn't use `/var/ossec/bin/wazuh-logtest` and would have to use the REST API. I followed the steps mentioned [here](https://documentation.wazuh.com/current/user-manual/capabilities/wazuh-logtest/how-it-works.html#use-cases-test-log-from-restful-api) and was able to run the first `curl` command successfully. This is a test environment so creds aren't important:

```
# TOKEN=$(curl -s -u $WUSER:$WPASS -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
# echo $TOKEN
eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjYxMTYxMjg3LCJleHAiOjE2NjExNjIxODcsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AIzNaQceha8EZjDfIK1_xmp0Sl4VDk2JAHDDPp-4Quwha14Hp6V3kkN14NU8OtRy9T08LcbiY-_PijH84LzSeUy9AFnAWNfN7TFC2C9z5ROgbsnWrGa8X5sTOWuSPT4hDIeYcgg_o4_oM6gmJjuxQA60wFWWZytvKxm7Ytv1B3jAgKB-
```

and then:

```json
# curl -s -k -X GET "https://localhost:55000/" -H "Authorization: Bearer $TOKEN" | jq
{
  "data": {
    "title": "Wazuh API REST",
    "api_version": "4.3.6",
    "revision": 40318,
    "license_name": "GPL 2.0",
    "license_url": "https://github.com/wazuh/wazuh/blob/4.3/LICENSE",
    "hostname": "ubuntu2204.localdomain",
    "timestamp": "2022-08-22T09:43:05Z"
  },
  "error": 0
}
```

However, when I try to run the same `PUT` as in the documentation:

```
LOGTEST_REQ=$(echo '{'\
    '"event": "Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928",'\
    '"log_format": "syslog",'\
    '"location": "master->/var/log/syslog"'\
    '}')

curl -k -X PUT "https://localhost:55000/logtest" \
-H "Authorization: Bearer $TOKEN" \
-H  "Content-Type: application/json" \
-d "$LOGTEST_REQ"
```

I get the following error in the terminal:

```json
{
  "title": "Wazuh Internal Error",
  "detail": "Wazuh Internal Error",
  "remediation": "Please, check `WAZUH_HOME/logs/ossec.log`, `WAZUH_HOME/logs/cluster.log` and `WAZUH_HOME/logs/api.log` to get more information about the error",
  "dapi_errors": {
    "node01": {
      "error": "Unable to connect with socket: [Errno 111] Connection refused",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 1000
}
```

Looking at the logs (`api.log`), I see the following:

```
2022/08/22 09:28:49 ERROR: Error executing API request locally: Error 1013 - Unable to connect with socket: [Errno 111] Connection refused
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.6-py3.9.egg/wazuh/core/wazuh_socket.py", line 27, in _connect
    self.s.connect(self.path)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.6-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 243, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.6-py3.9.egg/wazuh/rbac/decorators.py", line 420, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.6-py3.9.egg/wazuh/logtest.py", line 40, in run_logtest
    response = send_logtest_msg(command='log_processing', parameters=local_vars)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.6-py3.9.egg/wazuh/core/logtest.py", line 31, in send_logtest_msg
    logtest_socket = WazuhSocketJSON(LOGTEST_SOCKET)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.6-py3.9.egg/wazuh/core/wazuh_socket.py", line 60, in __init__
    WazuhSocket.__init__(self, path)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.6-py3.9.egg/wazuh/core/wazuh_socket.py", line 22, in __init__
    self._connect()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.6-py3.9.egg/wazuh/core/wazuh_socket.py", line 29, in _connect
    raise WazuhException(1013, str(e))
wazuh.core.exception.WazuhException: Error 1013 - Unable to connect with socket: [Errno 111] Connection refused
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.6-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 288, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
wazuh.core.exception.WazuhException: Error 1013 - Unable to connect with socket: [Errno 111] Connection refused
2022/08/22 09:28:49 INFO: wazuh 127.0.0.1 "PUT /logtest" with parameters {} and body {"event": "Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928", "log_format": "syslog", "location": "master->/var/log/syslog"} done in 0.023s: 500
```

Everything else seems to be working fine but the `logtest` API endpoint and I see normal activity in `api.log` such as:

```
2022/08/22 09:45:00 INFO: wazuh 127.0.0.1 "GET /manager/stats/remoted" with parameters {"pretty": ""} and body {} done in 0.056s: 200
2022/08/22 09:45:00 INFO: wazuh 127.0.0.1 "GET /manager/stats/analysisd" with parameters {"pretty": ""} and body {} done in 0.037s: 200
2022/08/22 09:45:00 INFO: wazuh 127.0.0.1 "GET /cluster/status" with parameters {} and body {} done in 0.052s: 200
2022/08/22 09:45:00 INFO: wazuh 127.0.0.1 "GET /agents" with parameters {"offset": "0", "limit": "1", "q": "id!=000"} and body {} done in 0.026s: 200
2022/08/22 09:45:00 INFO: wazuh 127.0.0.1 "GET /agents" with parameters {"offset": "0", "limit": "500", "q": "id!=000"} and body {} done in 0.028s: 200
```

Any ideas? Thanks

**Comment by MiguelazoDS** [comment]
Hi @mthbrown, 

I was able to do that without issues. Do you have a firewall enabled in that environment? if so, we can try disabling it temporarily to verify if that is the cause. I'll keep taking a look at this, but it seems that something is blocking the communication with the logtest socket.

**Comment by mthbrown** [comment]
@MiguelazoDS This is a fresh install in a lab environment with a single node (I just used the single-node installation steps)

**Comment by mthbrown** [comment]
@MiguelazoDS I ended up re-installing it and it worked on a fresh installation so I'll close the issue. Thank you for your help
