### ISSUE TITLE
Make `wazuh_clusterd` return correct exit code when there is an exception

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#14852]
## Description

Currently, `wazuh-clusterd` binary does not return an error exit code when the process can't be run for any reason. For example, here we are importing an invalid module but the exit code is 0 (`ok`):
```
root@wazuh-master:/# /var/ossec/bin/wazuh-clusterd -f
Starting cluster in foreground (pid: 1605)
2022/09/13 09:20:41 ERROR: [Cluster] [Main] Unhandled exception: No module named 'no_exists'
root@wazuh-master:/# echo $?
0
root@wazuh-master:/# /var/ossec/bin/wazuh-clusterd   
root@wazuh-master:/# echo $?
0
```

As a consequence, when Wazuh is started, nothing is notified:
```
root@wazuh-master:/# service wazuh-manager start
Starting Wazuh v4.4.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/09/13 09:26:20 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.
```

Depending on where the error occurs, it can be taken as a configuration error even though it is not:
```
root@wazuh-master:/# /var/ossec/bin/wazuh-clusterd
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/wazuh_clusterd.py", line 228, in <module>
    main()
  File "/var/ossec/framework/scripts/wazuh_clusterd.py", line 150, in main
    import no_exists
ModuleNotFoundError: No module named 'no_exists'
root@wazuh-master:/# 
root@wazuh-master:/# echo $?
1
root@wazuh-master:/# 
root@wazuh-master:/# 
root@wazuh-master:/# service wazuh-manager start
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/wazuh_clusterd.py", line 228, in <module>
    main()
  File "/var/ossec/framework/scripts/wazuh_clusterd.py", line 150, in main
    import no_exists
ModuleNotFoundError: No module named 'no_exists'
wazuh-clusterd: Configuration error. Exiting
```

The wazuh-clusterd script should copy the behavior of wazuh-apid.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
## Status update

After studying the case, I have come to the conclusion that the way error codes are handled in the `wazuh_clusterd.py` script is actually correct. In fact, although getting any of these exceptions, a code other than 0 should be returned:
https://github.com/wazuh/wazuh/blob/e6f118b25780563d174d33ff0402a7b1b9f3ffcb/framework/scripts/wazuh_clusterd.py#L194-L205

This has no impact on the wazuh-control script since before reaching that point, the process is forked:
https://github.com/wazuh/wazuh/blob/e6f118b25780563d174d33ff0402a7b1b9f3ffcb/framework/scripts/wazuh_clusterd.py#L179-L181
and the parent process (the one `wazuh-control` knows about), dies with code 0:
https://github.com/wazuh/wazuh/blob/e6f118b25780563d174d33ff0402a7b1b9f3ffcb/framework/wazuh/core/pyDaemonModule.py#L25-L28

It means that if there is an error unrelated to the cluster configuration, the error will be raised within the `master_main` or `worker_main` async functions. By this time, `wazuh-control` already considers the process to be running.
https://github.com/wazuh/wazuh/blob/e6f118b25780563d174d33ff0402a7b1b9f3ffcb/framework/scripts/wazuh_clusterd.py#L193

This actually happens with the API process as well. If, for example, we set port 443 in its configuration, the API will not be able to start if it is not running as root because it is a privileged port. The process will die after booting, but wazuh-control considers it to be running correctly even though this is not the case:
```
root@wazuh-master:/# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.4.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/09/28 15:00:49 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.
```
Here is the `api.log` after starting:
```
root@wazuh-master:/# cat /var/ossec/logs/api.log 
2022/09/28 14:20:34 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2022/09/28 14:20:34 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key
2022/09/28 14:20:34 INFO: Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt
2022/09/28 15:00:55 INFO: Listening on 0.0.0.0:443..
2022/09/28 15:00:55 ERROR: [Errno 13] error while attempting to bind on address ('0.0.0.0', 443): permission denied
```

Therefore, the real difference in how the wazuh_apid.py and wazuh_clusterd.py scripts are handled at boot time is within `wazuh-server.sh` (`wazuh-control`), and not in the python scripts. As seen here, when the `clusterd` binary is started, it continues with the next item (service) in the loop:
https://github.com/wazuh/wazuh/blob/e6f118b25780563d174d33ff0402a7b1b9f3ffcb/src/init/wazuh-server.sh#L306-L318
Instead, wazuh-control checks the status of the API (and other services) repeatedly after starting it. If after 10 times the script is not running, it is marked as failed:
https://github.com/wazuh/wazuh/blob/e6f118b25780563d174d33ff0402a7b1b9f3ffcb/src/init/wazuh-server.sh#L351-L367

**Comment by Selutario** [comment]
## Status update

The reason why the status of `wazuh-clusterd` was not checked after starting the process is that it is marked as an optional service, and it is not checked whether optional services are running in the background after being started.
https://github.com/wazuh/wazuh/blob/e6f118b25780563d174d33ff0402a7b1b9f3ffcb/src/init/wazuh-server.sh#L351-L356

However, even if we remove `wazuh-clusted` from the optional services list, it is incorrectly estimated to be running after using `wazuh-control start`. Why does this happen? Because the way `wazuh-control` determines if a process has been started is by checking if a `pidfile` exists for it and, immediately afterward, if there really is a process with that PID.

The API's startup function is a normal function, which means that any failure within it (such as importing a non-existing module at the beginning), immediately raises an exception, deleting its pidfile (lines #L331-332 below) almost instantly. Therefore, by the time `wazuh-control` looks for said pidfile, it does not exist and it is considered that the API service could not be started:
https://github.com/wazuh/wazuh/blob/e6f118b25780563d174d33ff0402a7b1b9f3ffcb/api/scripts/wazuh-apid.py#L322-L332

On the other hand, the `wazuh-clusterd` process starts an asynchronous task, which takes 0.20s. Any exception that occurs inside, even at the beginning, will not be raised after 0.20s. Although it seems like a short time, it is enough for `wazuh-control` to find the `wazuh-clusterd` pidfile and ensure that it has been started correctly.

However, this problem could also occur in the API if for whatever reason `wazuh-control` finds its pidfile before it is cleared or, for example, when the API fails at least 0.20s after starting. In fact, we already reported this in the last status update. If we set port 443 in the API without running it as root, it fails (trying to use a privileged port) but `wazuh-control` says it was started.

## Conclusion

With this issue, we are looking to increase the reliability of `wazuh-control` when starting `wazuh-clusterd`. However, after the problems described here, we cannot apply a good solution but patches that could fail in any situation. In fact, the actual behavior of wazuh-control may be inconsistent.

Therefore, it is impossible to fix the problem by modifying the `wazuh-clusterd` script or even changing `wazuh-control`. The solution must be to create a service that actively monitors them all:
- https://github.com/wazuh/wazuh/issues/14918
