### ISSUE TITLE
Distributed API fails in worker nodes if there's no connection with master node

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#1486]
Hello team,

I noticed distributed API requests fail in worker nodes if there's no connection with a master node:
```shellsession
# echo '{"function":"/cluster/:node_id/info","arguments":{"node_id":"node01"},"ossec_pat                                                                                            h":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
DEBUG:wazuh.cluster.dapi.dapi:[DistributedAPI] Distributed API is enabled.
DEBUG:wazuh.cluster.internal_socket:[InternalSocketClient] Worker ID: 1174627793
INFO:wazuh.cluster.communication:[InternalSocket-Worker] [1174627793] Connected.
DEBUG:wazuh.cluster.internal_socket:[InternalSocket-Worker] [1174627793] Time sending request to internal socket se                                                                                            rver: 0.00185394287109s
INFO:wazuh.cluster.communication:[InternalSocket-Worker] [1174627793] Disconnected.
{"message": "Wazuh-Python Internal Error: 'unicode' object has no attribute 'get'", "error": 1000}
Traceback (most recent call last):
  File "/var/ossec/api/models/wazuh-api.py", line 163, in <module>
    data = dapi.distribute_function(request, pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 61, in distribute_function
    return execute_remote_request(input_json, pretty)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 139, in execute_remote_request
    data, error = __split_response_data(response)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 122, in __split_response_data
    if response.get('err'):
AttributeError: 'unicode' object has no attribute 'get'
```

The expected result should be:
```javascript
{"message": "Error sending request to the master: Trying to send and there is no connection with the server", "error": 3018}
```

Best regards,
Marta

**Comment by mgmacias95** [comment]
Done in #1487.

**Comment by YashMangla** [comment]
what configuration is required at worker node to connect with master node.
i did as defined in documentation but i'm getting such type of error..
`Error: Trying to send and there is no connection with the server`

**Comment by mgmacias95** [comment]
Hello @YashMangla,

Is port 1516 opened in your master node? Can you paste here your cluster configuration? Can you check if cluster is running in both worker and master? You can check it using
```shellsession
# ps aux | grep cluster
```

Best regards,
Marta
