### ISSUE TITLE
Error while upgrading an agent in Amazon Linux 2022 (through WPK)

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#14982]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.8 | WPK Upgrade | Manager | Packages | Amazon Linux 2022 |

## Description

An error was thrown while upgrading a Wazuh agent from `4.3.7` to `4.3.8` (using a Wazuh manager 4.3.8). Also, it was thrown during the manual testing performed in: https://github.com/wazuh/wazuh-qa/issues/3266 (upgrading from `4.3.7`, which was the latest version at that time, to `4.4.0`)

The OS architecture of the Wazuh agent is: `aarch64`, and the Wazuh manager architecture is: `x86_64`.

Also, this does not happen when using a `x86_64` agent package (the upgrade is made correctly).

## Steps to reproduce the error

<details><summary>Follow these steps to get the error message</summary>

1. Install the Wazuh manager (`v4.3.8` - current): 
```
rpm -ivh https://packages.wazuh.com/4.x/yum/wazuh-manager-4.3.8-1.x86_64.rpm
systemctl daemon-reload
systemctl enable wazuh-manager
systemctl start wazuh-manager
```
2. Install the Wazuh agent (`v4.3.7`):
```
rpm -ivh https://packages.wazuh.com/4.x/yum/wazuh-agent-4.3.7-2.aarch64.rpm
systemctl daemon-reload
systemctl enable wazuh-agent
sed -i 's/MANAGER_IP/172.31.83.218/g' /var/ossec/etc/ossec.conf                                                                      systemctl start wazuh-agent
```

<br>

> **The following steps should be followed in the agent (because this VM has the aarch64 architecture)**

3. Install the Python package:
```
python3 -m pip install cryptography
```
4. Install the dependencies:
```
yum install make gcc gcc-c++ python3 python3-policycoreutils automake autoconf libtool openssl-devel cmake -y; yum-config-manager --enable powertools; yum install libstdc++-static -y
```
5. Download and extract the latest version (commit 88bf15d at this moment):
```
curl -sL https://github.com/wazuh/wazuh/tarball/88bf15d2cbb2040e197e34a94dda0f71f607afad | tar zx
```
6. Modify the `./wazuh-wazuh-88bf15d/etc/preloaded-vars.conf` file uncommenting the following lines:
```
USER_LANGUAGE="en"
USER_NO_STOP="y"
USER_UPDATE="y"
USER_BINARYINSTALL="y"
```
7. Compile the project:
```
cd src/ && make deps TARGET=agent && make TARGET=agent
```
8. Delete unnecessary files:
```
cd ../
rm -rf doc wodles/oscap/content/* gen_ossec.sh add_localfiles.sh Jenkinsfile*
rm -rf src/{addagent,analysisd,client-agent,config,error_messages,external/*,headers,logcollector,monitord,os_auth,os_crypto,os_csyslogd,os_dbdos_execd}
rm -rf src/{os_integrator,os_maild,os_netos_regex,os_xml,os_zlib,remoted,reportd,shared,syscheckd,tests,update,wazuh_db,wazuh_modules}
rm -rf src/win32
rm -rf src/*.a
rm -rf etc/{decoders,lists,rules}
find etc/templates/* -maxdepth 0 -not -name "en" | xargs rm -rf
```
9. Overwrite the root CA:
```
cd /tmp
openssl req -x509 -new -nodes -newkey rsa:2048 -keyout wpk_root.key -out wpk_root.pem -batch
openssl req -new -nodes -newkey rsa:2048 -keyout wpkcert.key -out wpkcert.csr -subj '/C=US/ST=CA/O=Wazuh'
openssl x509 -req -days 365 -in wpkcert.csr -CA wpk_root.pem -CAkey wpk_root.key -out wpkcert.pem -CAcreateserial
cd -
cp -f /tmp/wpk_root.pem etc/wpk_root.pem
```
10. Compile the WPK package using the SSL certificate and key:
```
tools/agent-upgrade/wpkpack.py /tmp/myagent.wpk /tmp/wpkcert.pem /tmp/wpkcert.key *
```
11. Replace the current certificate. Copy the generated package and the upgrade script to the manager:
```
cp /tmp/wpk_root.pem /var/ossec/etc/
scp -i KEY-PATH /tmp/myagent.wpk user@ip:PATH
scp -i KEY-PATH ./upgrade.sh user@ip:PATH
```

**In the Manager:**
12. Change the upgrade script user and group:
```
# ls -l /tmp/upgrade.sh
-rwxrwxr-x. 1 user user 610 Sep 21 20:25 /tmp/upgrade.sh
# chown root /tmp/upgrade.sh
# chgrp root /tmp/upgrade.sh
# ls -l /tmp/upgrade.sh
-rwxrwxr-x. 1 root root 610 Sep 21 20:25 /tmp/upgrade.sh
```
13. Check if the agent is registered and active:
```
/var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: manager (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: agent, IP: any, Active
```
14. Run the following script:
```
/var/ossec/bin/agent_upgrade -a 001 -f /tmp/myagent.wpk -x /tmp/upgrade.sh
```

</details>

## Current result

<details><summary>The following error is thrown while upgrading the agent</summary>

```Bash
# /var/ossec/bin/agent_upgrade -a 001 -f /tmp/myagent.wpk -x /tmp/upgrade.sh
Agent information not found in database
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.8-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 243, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.8-py3.9.egg/wazuh/rbac/decorators.py", line 420, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.8-py3.9.egg/wazuh/agent.py", line 981, in upgrade_agents
    raise WazuhInternalError(error_code, cmd_error=True, extra_message=agent_result['message'])
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.8-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 288, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
Internal error:
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 220, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 186, in main
    result = send_command(function=upgrade_agents, command=create_command())
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 115, in send_command
    return raise_if_exc(pool.submit(run, dapi.distribute_function()).result())
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/util.py", line 293, in raise_if_exc
    _create_problem(obj)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/util.py", line 263, in _create_problem
    raise ProblemException(status=500 if not code else code, type=exc.type, title=exc.title, detail=exc.message,
connexion.exceptions.ProblemException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 227, in <module>
    if args.debug:
AttributeError: 'Namespace' object has no attribute 'debug'
```

</details>

## Expected result

The agent must be upgraded to `v4.3.8` without showing errors.

## Evidence

<details><summary>Check if the agent is registered and active</summary>

```Bash
# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: MANAGER (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: AGENT, IP: any, Active
```
</details>

<details><summary>Check if the agent requires an upgrade</summary>

```Bash
/var/ossec/bin/agent_upgrade -l
ID    Name                                Version
001   AGENT                               Wazuh v4.3.7

Total outdated agents: 1
```
</details>

<details><summary>Check the ACK sent by <code>wazuh-agentd</code></summary>

```Bash
# tail -F /var/ossec/logs/ossec.log | egrep -iE "ack|keep alive"
2022/09/21 20:38:37 wazuh-agentd[47161] notify.c:204 at run_notify(): DEBUG: Sending keep alive: #!-Linux |agent |ip.amzn2022.aarch64 |#1 SMP Wed Aug 17 23:50:18 UTC 2022 |aarch64 [Amazon Linux|amzn: 2022] - Wazuh v4.3.7 / ab73af41699f13fdd81903b5f23d8d00
2022/09/21 20:38:37 wazuh-agentd[47161] receiver.c:92 at receive_msg(): DEBUG: Received message: '#!-agent ack '
```

</details>

<details><summary>Check the agent information through the API</summary>

```Bash
# curl -k -X GET "https://localhost:55000/agents?pretty=true&agents_list=001&select=os.name,os.major,
os.minor,os.arch" -H  "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "os": {
               "major": "2022",
               "name": "Amazon Linux"
            },
            "id": "001"
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected agents information was returned",
   "error": 0
}
```
</details>

<details><summary>Check the agent info through the global database</summary>

```Bash
# sqlite3 /var/ossec/queue/db/global.db "SELECT OS_NAME, OS_MAJOR, OS_MINOR, OS_ARCH FROM AGENT WHERE ID = 1" -table
+--------------+----------+----------+---------+
|   os_name    | os_major | os_minor | os_arch |
+--------------+----------+----------+---------+
| Amazon Linux | 2022     |          |         |
+--------------+----------+----------+---------+
```
</details>

<details><summary><b>Extra:</b> Check the MANAGER info through the global database</summary>

```Bash
# sqlite3 /var/ossec/queue/db/global.db "SELECT OS_NAME, OS_MAJOR, OS_MINOR, OS_ARCH FROM AGENT WHERE ID = 0" -table
+--------------+----------+----------+---------+
|   os_name    | os_major | os_minor | os_arch |
+--------------+----------+----------+---------+
| Amazon Linux | 2022     |          | x86_64  |
+--------------+----------+----------+---------+
```
</details>

> Conclusion: It is possible that the error comes from the validation of the `os_arch` or `os_minor` fields.

**Comment by mauromalara** [comment]
Related issue: #12301

**Comment by vikman90** [comment]
@mauromalara This is likely related to #14109. Please try to upgrade to 4.4.0 and check if this issue persists.

Thanks!

**Comment by mauromalara** [comment]
@vikman90 I've tested this using a `4.4.0` development package in wazuh/wazuh-qa/issues/3266; this issue comes from manual testing.
