### ISSUE TITLE
Error in API call POST /agents/restart

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh#1506]
## Bug report

**OS**
_CentOS 7_

**Wazuh version**
_3.7.0_

**Wazuh API version**
_3.7.0_

**Install type**
_manager_

**Install method**
_sources_

**Log sample**

```python
# echo '{"function":"POST/agents/restart","arguments":{"agent_id":["001"]},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
DEBUG:wazuh.cluster.dapi.dapi:[DistributedAPI] Distributed API is enabled.
{"message": "Wazuh-Python Internal Error: 'list' object has no attribute 'split'", "error": 1000}
Traceback (most recent call last):
  File "/var/ossec/api/models/wazuh-api.py", line 163, in <module>
    data = dapi.distribute_function(request, pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 56, in distribute_function
    return forward_request(input_json, node_info['node'], pretty)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 191, in forward_request
    node_name, is_list = get_solver_node(input_json, master_name)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 223, in get_solver_node
    sort={'fields':['node_name'], 'order':'desc'})['items']
  File "/var/ossec/framework/wazuh/agent.py", line 804, in get_agents_overview
    data = db_query.run()
  File "/var/ossec/framework/wazuh/utils.py", line 831, in run
    self._add_filters_to_query()
  File "/var/ossec/framework/wazuh/utils.py", line 777, in _add_filters_to_query
    self._parse_filters()
  File "/var/ossec/framework/wazuh/utils.py", line 748, in _parse_filters
    self._parse_legacy_filters()
  File "/var/ossec/framework/wazuh/agent.py", line 139, in _parse_legacy_filters
    WazuhDBQuery._parse_legacy_filters(self)
  File "/var/ossec/framework/wazuh/utils.py", line 740, in _parse_legacy_filters
    for name, value in self.legacy_filters.items() for subvalue,i in zip(value.split(','), range(len(value.split(',')))) if not self._pass_filter(subvalue)]
AttributeError: 'list' object has no attribute 'split'
```

Bug description
----------------
API call POST /agents/restart doesn't work properly. It returns an internal Python exception.

**Comment by mgmacias95** [comment]
The error only happens when the Distributed API is enabled:
```python
# echo '{"function":"POST/agents/restart","arguments":{"agent_id":["001"]},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
DEBUG:wazuh.cluster.dapi.dapi:[DistributedAPI] Distributed API is enabled.
{"message": "Wazuh-Python Internal Error: 'list' object has no attribute 'split'", "error": 1000}
Traceback (most recent call last):
  File "/var/ossec/api/models/wazuh-api.py", line 163, in <module>
    data = dapi.distribute_function(request, pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 56, in distribute_function
    return forward_request(input_json, node_info['node'], pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 192, in forward_request
    node_name, is_list = get_solver_node(input_json, master_name)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 224, in get_solver_node
    sort={'fields':['node_name'], 'order':'desc'})['items']
  File "/var/ossec/framework/wazuh/agent.py", line 804, in get_agents_overview
    data = db_query.run()
  File "/var/ossec/framework/wazuh/utils.py", line 831, in run
    self._add_filters_to_query()
  File "/var/ossec/framework/wazuh/utils.py", line 777, in _add_filters_to_query
    self._parse_filters()
  File "/var/ossec/framework/wazuh/utils.py", line 748, in _parse_filters
    self._parse_legacy_filters()
  File "/var/ossec/framework/wazuh/agent.py", line 139, in _parse_legacy_filters
    WazuhDBQuery._parse_legacy_filters(self)
  File "/var/ossec/framework/wazuh/utils.py", line 740, in _parse_legacy_filters
    for name, value in self.legacy_filters.items() for subvalue,i in zip(value.split(','), range(len(value.split(',')))) if not self._pass_filter(subvalue)]
AttributeError: 'list' object has no attribute 'split'
# vim /var/ossec/framework/wazuh/cluster/cluster.json
# echo '{"function":"POST/agents/restart","arguments":{"agent_id":["001"]},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
DEBUG:wazuh.cluster.dapi.dapi:[DistributedAPI] Distributed API is disabled.
DEBUG:wazuh.cluster.dapi.dapi:[DistributedAPI] Time calculating request result: 0.0016930103302s
DEBUG:root:Total time: 0.00762605667114
DEBUG:root:Size of all received data: 182
{"data": {"msg": "Some agents were not restarted", "failed_ids": [{"id": "001", "error": {"message": "Agent does not exist: 001", "code": 1701}}], "affected_agents": []}, "error": 0}
```

**Comment by mgmacias95** [comment]
Done in #1510
