### ISSUE TITLE
Release 4.3.9 - Release Candidate 1 - Unit tests

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#15098]
|Main RC issue|Version|RC|Tag|Previous issue|
|---|---|---|---|---|
|#15090|4.3.9|1|[v4.3.9-rc1](https://github.com/wazuh/wazuh/releases/tag/v4.3.9-rc1)||

This issue aims to run all `C unit tests` for the current RC and report the results. Any failing test should be properly addressed with a new issue, detailing the error and the possible cause. Then, it will be determined if that fails is to be fixed immediately or marked as expected-fail if there is enough support and approval for it. In case a test is marked as expected-fail, the issue detailing the error should always be used as a reference in the test.

## Auditors' validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [x] @davidjiglesias

**Comment by chemamartinez** [comment]
## Data provider

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|🟢|
|sysInfoNetworkLinux_unit_test|🟢|
|sysInfoPackageLinuxParserRPM_unit_test|🟢|
|sysinfo_unit_test|🟢|
|sysInfoPackagesLinuxHelper_unit_test|🟢|
|Rpm_unit_test|🟢|
|sysInfoPackagesBerkeleyDB_unit_test|🟢|
|sysInfoPort_unit_test|🟢|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|99.3%|🟢|
|Functions|100.0%|🟢|

## Syscollector

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|🟢|
|syscollectorimp_unit_test|🟢|
|sys_normalizer_unit_test|🟢|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|99.0%|🟢|
|Functions|100.0%|🟢|

## Utilities

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|🟢|
|utils_unit_test|🟢|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|98.2%|🟢|
|Functions|94.6%|🟢|

## Rsync

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|🔴|
|rsync_unit_test|🟢|
|rsync_implementation_unit_test|🟢|

**cppcheck failed:**
```
root@ubuntu2204:~/wazuh/src# python3 build.py --cppcheck shared_modules/rsync
<shared_modules/rsync>=================== Running cppcheck    ===================<shared_modules/rsync>
b"/root/wazuh/src/shared_modules/rsync/src/rsyncImplementation.h:25:1: error: The one definition rule is violated, different classes/structs have the same name 'CJsonDeleter' [ctuOneDefinitionRuleViolation]\nstruct CJsonDeleter\n^\n/root/wazuh/src/shared_modules/rsync/testtool/agentEmulator.cpp:44:1: note: The one definition rule is violated, different classes/structs have the same name 'CJsonDeleter'\nstruct CJsonDeleter final\n^\n/root/wazuh/src/shared_modules/rsync/src/rsyncImplementation.h:25:1: note: The one definition rule is violated, different classes/structs have the same name 'CJsonDeleter'\nstruct CJsonDeleter\n^\n/root/wazuh/src/shared_modules/rsync/src/rsyncImplementation.cpp:273:25: error: Using argument ctx that points at uninitialized variable checksumCtx [ctuuninitvar]\n    const auto middle { ctx.size / 2 };\n                        ^\n/root/wazuh/src/shared_modules/rsync/src/rsyncImplementation.cpp:90:29: note: Calling function fillChecksum, 5th argument is uninitialized\n                fillChecksum(spDBSyncWrapper, jsStartParams, begin, end, checksumCtx);\n                            ^\n/root/wazuh/src/shared_modules/rsync/src/rsyncImplementation.cpp:273:25: note: Using argument ctx\n    const auto middle { ctx.size / 2 };\n                        ^\n"
[Cppcheck: FAILED]
Traceback (most recent call last):
  File "/root/wazuh/src/build.py", line 99, in <module>
    cmdLineParser.processArgs()
  File "/root/wazuh/src/build.py", line 79, in processArgs
    utils.runCppCheck(args.cppcheck)
  File "/root/wazuh/src/ci/utils.py", line 334, in runCppCheck
    raise ValueError(errorString)
ValueError: Error Running cppcheck: 0
```

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|99.6%|🟢|
|Functions|100.0%|🟢|

## DBsync

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|🔴|
|sqlite_unit_test|🟢|
|dbsync_unit_test|🟢|
|dbengine_unit_test|🟢|
|dbsyncPipelineFactory_unit_test|🟢|
|fim_integration_test|🟢|

**cppcheck failed:**
```
root@ubuntu2204:~/wazuh/src# python3 build.py --cppcheck shared_modules/dbsync
<shared_modules/dbsync>=================== Running cppcheck    ===================<shared_modules/dbsync>
b"/root/wazuh/src/shared_modules/dbsync/integrationTests/fim/fimIntegrationTest.cpp:30:1: error: The one definition rule is violated, different classes/structs have the same name 'CJsonDeleter' [ctuOneDefinitionRuleViolation]\nstruct CJsonDeleter final\n^\n/root/wazuh/src/shared_modules/dbsync/src/dbsync.cpp:25:1: note: The one definition rule is violated, different classes/structs have the same name 'CJsonDeleter'\nstruct CJsonDeleter\n^\n/root/wazuh/src/shared_modules/dbsync/integrationTests/fim/fimIntegrationTest.cpp:30:1: note: The one definition rule is violated, different classes/structs have the same name 'CJsonDeleter'\nstruct CJsonDeleter final\n^\n"
[Cppcheck: FAILED]
Traceback (most recent call last):
  File "/root/wazuh/src/build.py", line 99, in <module>
    cmdLineParser.processArgs()
  File "/root/wazuh/src/build.py", line 79, in processArgs
    utils.runCppCheck(args.cppcheck)
  File "/root/wazuh/src/ci/utils.py", line 334, in runCppCheck
    raise ValueError(errorString)
ValueError: Error Running cppcheck: 0
```

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|92.6%|🟢|
|Functions|96.7%|🟢|

## Linux agent unit tests

### Tests

|Test|Status|
|---|:-:|
|test_macos_log|🟢|
|test_read_macos|🟢|
|test_execd|🟢|
|test_get_command_by_name|🟢|
|test_wm_github|🟢|
|test_wm_office365|🟢|
|test_create_db|🟢|
|test_syscom|🟢|
|test_fim_diff_changes|🟢|
|test_run_realtime|🟢|
|test_syscheck_config|🟢|
|test_syscheck|🟢|
|test_fim_sync|🟢|
|test_run_check|🟢|
|test_fim_db|🟢|
|test_fim_db_files|🟢|
|test_audit_healthcheck|🟢|
|test_audit_rule_handling|🟢|
|test_syscheck_audit|🟢|
|test_audit_parse|🟢|
|test_list_op|🟢|
|test_file_op|🟢|
|test_integrity_op|🟢|
|test_rbtree_op|🟢|
|test_validate_op|🟢|
|test_string_op|🟢|
|test_expression|🟢|
|test_version_op|🟢|
|test_queue_op|🟢|
|test_queue_linked_op|🟢|
|test_agent_op|🟢|
|test_enrollment_op|🟢|
|test_time_op|🟢|
|test_buffer_op|🟢|
|test_utf8_op|🟢|
|test_log_builder|🟢|
|test_custom_output_search_replace|🟢|
|test_syscheck_op|🟢|
|test_audit_op|🟢|
|test_privsep_op|🟢|
|test_mq_op|🟢|
|test_remoted_op|🟢|
|test_atomic|🟢|
|test_url|🟢|
|test_sysinfo_utils|🟢|
|test_os_xml|🟢|
|test_os_regex|🟢|
|test_os_regex_execute|🟢|
|test_os_zlib|🟢|
|test_os_net|🟢|
|test_fluentd_forwarder|🟢|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|21.8%|11791 of 53991 lines|
|Functions|2.9%|640 of 21780 functions|
|Branches|13.9%|9423 of 67870 branches|

## Windows agent unit tests

### Tests

**Pending**

|Test|Status|
|---|:-:|
|test_create_db|⚫|
|test_syscom|⚫|
|test_fim_diff_changes|⚫|
|test_run_realtime|⚫|
|test_syscheck_config|⚫|
|test_syscheck|⚫|
|test_fim_sync|⚫|
|test_run_check|⚫|
|test_run_realtime_event|⚫|
|test_run_check_event|⚫|
|test_registry|⚫|
|test_events|⚫|
|test_fim_db|⚫|
|test_fim_db_files|⚫|
|test_fim_db_registries|⚫|
|test_win_whodata|⚫|
|test_list_op|⚫|
|test_file_op|⚫|
|test_integrity_op|⚫|
|test_rbtree_op|⚫|
|test_validate_op|⚫|
|test_string_op|⚫|
|test_expression|⚫|
|test_version_op|⚫|
|test_queue_op|⚫|
|test_queue_linked_op|⚫|
|test_agent_op|⚫|
|test_enrollment_op|⚫|
|test_time_op|⚫|
|test_buffer_op|⚫|
|test_utf8_op|⚫|
|test_log_builder|⚫|
|test_custom_output_search_replace|⚫|
|test_syscheck_op|⚫|
|test_atomic|⚫|
|test_url|⚫|
|test_sysinfo_utils|⚫|
|test_os_xml|⚫|
|test_os_regex|⚫|
|test_os_regex_execute|⚫|
|test_os_zlib|⚫|

## Linux Manager unit tests

### Tests

|Test|Status|
|---|:-:|
|test_syscheck_audit|🟢|
|test_audit_parse|🟢|
|test_list_op|🟢|
|test_file_op|🟢|
|test_integrity_op|🟢|
|test_rbtree_op|🟢|
|test_validate_op|🟢|
|test_string_op|🟢|
|test_expression|🟢|
|test_version_op|🟢|
|test_queue_op|🟢|
|test_queue_linked_op|🟢|
|test_agent_op|🟢|
|test_set_agent_group|🟢|
|test_enrollment_op|🟢|
|test_time_op|🟢|
|test_buffer_op|🟢|
|test_utf8_op|🟢|
|test_log_builder|🟢|
|test_custom_output_search_replace|🟢|
|test_bzip2_op|🟢|
|test_schedule_scan|🟢|
|test_rootcheck_op|🟢|
|test_fs_op|🟢|
|test_wazuhdb_op|🟢|
|test_syscheck_op|🟢|
|test_audit_op|🟢|
|test_privsep_op|🟢|
|test_mq_op|🟢|
|test_remoted_op|🟢|
|test_json-queue|🟢|
|test_bqueue|🟢|
|test_atomic|🟢|
|test_url|🟢|
|test_sysinfo_utils|🟢|
|test_os_xml|🟢|
|test_os_regex|🟢|
|test_os_regex_execute|🟢|
|test_os_zlib|🟢|
|test_os_net|🟢|
|test_fluentd_forwarder|🟢|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|32.8%|28915 of 88160 lines|
|Functions|5.9%|1342 of 22821 functions|
|Branches|21.5%|24081 of 112065 branches|
