### ISSUE TITLE
Can't uninstall agent in CentOS 9 Stream using yum

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#15208]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4 | libstdc++ | Agent | Packages | CentOS 9 Stream |

## Description

While testing on a CentOS 9 Stream agent, I found the following error when trying to uninstall the agent using `yum`:
```
# yum remove wazuh-agent
Traceback (most recent call last):
  File "/bin/yum", line 61, in <module>
    from dnf.cli import main
  File "/usr/lib/python3.9/site-packages/dnf/__init__.py", line 30, in <module>
    import dnf.base
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 29, in <module>
    import libdnf.transaction
  File "/usr/lib64/python3.9/site-packages/libdnf/__init__.py", line 11, in <module>
    from . import common_types
  File "/usr/lib64/python3.9/site-packages/libdnf/common_types.py", line 13, in <module>
    from . import _common_types
ImportError: /var/ossec/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib64/python3.9/site-packages/libdnf/_common_types.so)
```

This error has started to appear after merge the PR https://github.com/wazuh/wazuh/pull/14190 to the `4.4` branch.

To replicate it, simply install a v4.4 agent via a package using _yum_ ([test package](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-no.changes.x86_64.rpm)) and then try to uninstall it.

- Command used for installation: `yum install ./wazuh-agent-4.4.0-no.changes.x86_64.rpm`
- Command used for uninstallation: `yum remove wazuh-agent`

**Comment by Dwordcito** [comment]
@pereyra-m please RCA in this issue.

**Comment by pereyra-m** [comment]
## RCA

The vagrant box `almalinux/centos-stream-9` was used for the tests.

### Install/Uninstall Wazuh agent normally 

The same test package suggested in the issue was used for the test.
The process was successful.

![install](https://user-images.githubusercontent.com/65046601/197863181-e99ad318-9544-4a50-867a-b18a09e8da37.png)

![remove](https://user-images.githubusercontent.com/65046601/197863193-03a322bc-0475-4d83-98ed-e855c7d9d2a8.png)

### Forcing the issue

A similar error message was generated by renaming the system's libraries to make the OS unable to find them

```
[root@localhost vagrant]# find / -name "libstdc++.so*"
/var/ossec/lib/libstdc++.so.6
/usr/lib64/libstdc++.so.6
/usr/lib64/libstdc++.so.6.0.29
/usr/share/gdb/auto-load/usr/lib64/__pycache__/libstdc++.so.6.0.29-gdb.cpython-39.opt-1.pyc
/usr/share/gdb/auto-load/usr/lib64/__pycache__/libstdc++.so.6.0.29-gdb.cpython-39.pyc
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.29-gdb.py
[root@localhost vagrant]# mv /usr/lib64/libstdc++.so.6 /usr/lib64/libstdc++.so.6.back
[root@localhost vagrant]# mv /usr/lib64/libstdc++.so.6.0.29 /usr/lib64/libstdc++.so.6.0.29.back
``` 

![error](https://user-images.githubusercontent.com/65046601/197863975-e5a0d58b-82bd-425f-ad86-0e9b5fdb60e6.png)

We can also create a symbolic link to force the system to use the library located in `/var/ossec/lib/`

```
[root@localhost vagrant]# ln -s /var/ossec/lib/libstdc++.so.6 /usr/lib64/libstdc++.so.6
```

Resulting in the following error message, more similar to the original one

![remove_again](https://user-images.githubusercontent.com/65046601/197867741-cbed88d3-6756-43a3-8c1d-8e262f88d09a.png)

### Conclusions

It seems that some particular conditions in the host might generate this situation, but it isn't clear how this happened in the first place. More information of the original VM is required.

**Comment by pereyra-m** [comment]
### Update

New tests were carried out with the vagrant VM `"box" => "generic/centos9s"`.
The issue couldn't be reproduced

![centos9s_install.png](https://images.zenhubusercontent.com/5ecbcb7dec754c76c550d5ad/bfecf06e-64b1-4165-a5c3-235693fda461)

![centos9s_removal.png](https://images.zenhubusercontent.com/5ecbcb7dec754c76c550d5ad/b9213455-2eb4-4457-aa33-93bb95915792)

More tests in the original VM are being carried out.
