### ISSUE TITLE
`analysisd`: segfault found in 4.4 development branch

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#15296]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4 | Wazuh component | Manager/Agent | Packages/Sources | OS version |

The development demo environment (info) was spined up with the development package version 4.4.0 to detect possible bugs or improvements early. In this case, after working for a while, @teddytpc1 noticed that `analysisd` was not working and the following segfaults were founds:
**Master node**
```
Oct 28 19:03:09 ip-10-0-0-45 kernel: wazuh-analysisd[25286]: segfault at 8 ip 00007f623ee1301c sp 00007f622ffeed38 error 6 in libc-2.26.so[7f623ecc5000+1a4000]
Oct 31 14:27:03 wazuh-manager-master-0 kernel: wazuh-analysisd[2821]: segfault at 8 ip 00007fdeec15513b sp 00007fdedc7efd38 error 6 in libc-2.26.so[7fdeec007000+1a4000]
Oct 31 14:27:03 wazuh-manager-master-0 kernel: wazuh-analysisd[2820]: segfault at 8 ip 00007fdeec15513b sp 00007fdedcff0d38 error 6 in libc-2.26.so[7fdeec007000+1a4000]
Nov  1 04:36:05 wazuh-manager-master-0 kernel: wazuh-analysisd[16143]: segfault at 18 ip 00007fd4033ab01c sp 00007fd3f37edd38 error 6 in libc-2.26.so[7fd40325d000+1a4000]
```

**Worker node**
```
Oct 28 19:00:27 ip-10-0-0-49 kernel: wazuh-analysisd[17921]: segfault at 18 ip 00007fc7aa76501c sp 00007fc79f9e2d38 error 6 in libc-2.26.so[7fc7aa617000+1a4000]
Oct 31 14:11:48 wazuh-manager-worker-0 kernel: wazuh-analysisd[2769]: segfault at 18 ip 00007fbce123101c sp 00007fbccd7f9d38 error 6 in libc-2.26.so[7fbce10e3000+1a4000]
```

This is the environment `#1`, it has a master and worker node. Environment `#2` has only one Wazuh manager and this one has no segfaults. 

**Edit**: after spin up the daemon, a new segfault occurred:
```
Nov  7 00:56:02 wazuh-manager-master-0 kernel: wazuh-analysisd[18188]: segfault at 18 ip 00007ff00300401c sp 00007fefef7f5d38 error 6 in libc-2.26.so[7ff002eb6000+1a4000]
```

**Comment by chemamartinez** [comment]
Hi team,

Since the installed package of 4.4 was generated before merging the fix at https://github.com/wazuh/wazuh/issues/14923, we had the suspect that could be the same bug.

To verify that, we have replaced the `wazuh-analysisd` binary that was running in both master and worker with the same one but compiled with debug symbols. In addition, we attached `gdb` to the `wazuh-analysisd` process to be able to generate a coredump when crashed.

Steps to generate the coredump in the affected manager:
```
# 1. Install dependencies
yum install gdb gcc make git libtool automake autoconf curl wget

# 2. Checkout and build Wazuh from sources
git clone https://github.com/wazuh/wazuh -b 4.4
cd wazuh/src
make deps TARGET=server
make TARGET=server DEBUG=yes -j$(nproc)

# 3. Run the newly built Analysisd
systemctl stop wazuh-manager
cp -f wazuh-analysisd /var/ossec/bin/
systemctl start wazuh-manager

# 4. Set traps with GDB and save coredump
nohup gdb -p $(pidof wazuh-analysisd) -batch \
-ex 'handle SIGPIPE nostop' \
-ex continue \
-ex 'generate-core-file wazuh-analysisd.coredump' \
-ex 'info thread' \
-ex 'bt' &
```

Once the binary crashed again, we obtained the coredump. Here is attached along with the binary:
[wazuh-analysisd-debug.zip](https://github.com/wazuh/wazuh/files/9979569/wazuh-analysisd-debug.zip)

Analyzing the coredump we can see the following backtrace:
```
(gdb) bt
#0  0x00007fe69714501c in __memset_avx2_unaligned () from /lib64/libc.so.6
#1  0x00000000005387ac in OSRegex_Execute_ex (
    str=0x7fe66c071b3f "System: INFORMATION(16): Microsoft-Windows-Kernel-General: SYSTEM: NT AUTHORITY: EC2AMAZ-GI2P7FA: 33 \\??\\C:\\Users\\.NET v2.0\\ntuser.dat 415 19 ", reg=0x1301d80, regex_match=0x7fe6877edea0) at os_regex/os_regex_execute.c:109
#2  0x0000000000532248 in w_expression_match (expression=0x1301d60,
    str_test=0x7fe66c071b3f "System: INFORMATION(16): Microsoft-Windows-Kernel-General: SYSTEM: NT AUTHORITY: EC2AMAZ-GI2P7FA: 33 \\??\\C:\\Users\\.NET v2.0\\ntuser.dat 415 19 ", end_match=0x7fe6877ede28, regex_match=0x7fe6877edea0) at shared/expression.c:179
#3  0x00000000004406af in DecodeEvent (lf=0x7fe65901a9b0, rules_hash=0x23eaf10, decoder_match=0x7fe6877edea0, node=0x12bcfa0)
    at analysisd/decoders/decoder.c:175
#4  0x0000000000433977 in w_decode_event_thread (args=0x0) at analysisd/analysisd.c:1714
#5  0x00007fe6973ab44b in start_thread () from /lib64/libpthread.so.0
#6  0x00007fe6970e658f in clone () from /lib64/libc.so.6
```

In frame 1, we can see it crashes due to an incorrect value of the `prts_str_size` vector. Same as the bug mentioned in the issue above.
```
(gdb) frame 1
#1  0x00000000005387ac in OSRegex_Execute_ex (
    str=0x7fe66c071b3f "System: INFORMATION(16): Microsoft-Windows-Kernel-General: SYSTEM: NT AUTHORITY: EC2AMAZ-GI2P7FA: 33 \\??\\C:\\Users\\.NET v2.0\\ntuser.dat 415 19 ", reg=0x1301d80, regex_match=0x7fe6877edea0) at os_regex/os_regex_execute.c:109
109	            memset((void*)(*prts_str)[i], 0, (str_sizes) ? str_sizes->prts_str_size[i] : reg->d_size.prts_str_size[i]);
```

So, we can conclude that this crash is already fixed in 4.4 thanks to https://github.com/wazuh/wazuh/pull/15190.
