### ISSUE TITLE
Fix alphanumeric_symbols regex for certain SCA remediation fields

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#15465]
|Wazuh version|Component|
|---|---|
| 4.4.0 | API |

## Description

During the investigation of AIT burst failures (#15344), it was found that the defined regex to validate the remediation filter in the `/sca/{agent_id}/checks/{policy_id}` API endpoint does not cover every possible case, generating failures.

Remediation example that currently fails:
<details><summary>remediation field</summary>

    "If cron will be used to schedule and run aide check: Run the following command: # crontab -u root -e Add the following line to the crontab: 0 5 * * * /usr/bin/aide.wrapper --config /etc/aide/aide.conf --check OR If aidecheck.service and aidecheck.timer will be used to schedule and run aide check: Create or edit the file /etc/systemd/system/aidecheck.service and add the following lines: [Unit] Description=Aide Check [Service] Type=simple ExecStart=/usr/bin/aide.wrapper --config /etc/aide/aide.conf --check [Install] WantedBy=multi-user.target Create or edit the file /etc/systemd/system/aidecheck.timer and add the following lines: [Unit] Description=Aide check every day at 5AM [Timer] OnCalendar=*-*-* 05:00:00 Unit=aidecheck.service [Install] WantedBy=multi-user.target Run the following commands: # chown root:root /etc/systemd/system/aidecheck.* # chmod 0644 /etc/systemd/system/aidecheck.* # systemctl daemon-reload # systemctl enable aidecheck.service # systemctl --now enable aidecheck.timer"
</details>

The regex mentioned above is assigned to the `_symbols_alphanumeric_param` variable in the `validator.py` file and later used to define the `alphanumeric_symbols` format:

https://github.com/wazuh/wazuh/blob/6ce1be2ee623eb0775355882a261d1fe495cb38b/api/api/validator.py#L17

https://github.com/wazuh/wazuh/blob/6ce1be2ee623eb0775355882a261d1fe495cb38b/api/api/validator.py#L324-L326
  
The current regex version was introduced in #10745 and the format was defined for the `remediation` filter in #5462, so we can conclude that it is not a bug introduced during the development of the `4.4` branch.

The regex has to be reviewed and modified to match every expected case and avoid errors.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by EduLeon12** [comment]
New regex implemented:

```
^[\w,*<>!\-.+\s:/()\[\]\'\"|=~#]+$
```

This includes the symbol * that was causing the remediation file above to not match.

Regex test including * symbol:

![image](https://user-images.githubusercontent.com/60372646/221989685-2ef4a42a-da05-4f1d-b840-c9d9e1cf6543.png)

<details><summary>remediation field</summary>

    "If cron will be used to schedule and run aide check: Run the following command: # crontab -u root -e Add the following line to the crontab: 0 5 * * * /usr/bin/aide.wrapper --config /etc/aide/aide.conf --check OR If aidecheck.service and aidecheck.timer will be used to schedule and run aide check: Create or edit the file /etc/systemd/system/aidecheck.service and add the following lines: [Unit] Description=Aide Check [Service] Type=simple ExecStart=/usr/bin/aide.wrapper --config /etc/aide/aide.conf --check [Install] WantedBy=multi-user.target Create or edit the file /etc/systemd/system/aidecheck.timer and add the following lines: [Unit] Description=Aide check every day at 5AM [Timer] OnCalendar=*-*-* 05:00:00 Unit=aidecheck.service [Install] WantedBy=multi-user.target Run the following commands: # chown root:root /etc/systemd/system/aidecheck.* # chmod 0644 /etc/systemd/system/aidecheck.* # systemctl daemon-reload # systemctl enable aidecheck.service # systemctl --now enable aidecheck.timer"
</details>


Next steps:
- [ ] Discuss with the team possible remediation fields to further test implementation and other possible text not matching.
- [ ] Perform tests and do necessary changes.

**Comment by EduLeon12** [comment]
Unit test Results:

```
(ut-3.9-venv) eduardoleon@pop-os:~/git/wazuh$ PYTHONPATH=/home/eduardoleon/git/wazuh/api:/home/eduardoleon/git/wazuh/framework python3 -m pytest api/api
============================================== test session starts ===============================================
platform linux -- Python 3.9.9, pytest-7.0.1, pluggy-0.13.1
rootdir: /home/eduardoleon/git/wazuh/api
plugins: asyncio-0.18.1, aiohttp-1.0.4, trio-0.7.0, cov-3.0.0, anyio-3.6.2, metadata-2.0.2, html-3.0.0
asyncio: mode=auto
collected 544 items                                                                                              

api/api/controllers/test/test_active_response_controller.py .                                              [  0%]
api/api/controllers/test/test_agent_controller.py ...........................................              [  8%]
api/api/controllers/test/test_cdb_list_controller.py ......                                                [  9%]
api/api/controllers/test/test_ciscat_controller.py .                                                       [  9%]
api/api/controllers/test/test_cluster_controller.py ........................                               [ 13%]
api/api/controllers/test/test_decoder_controller.py .......                                                [ 15%]
api/api/controllers/test/test_default_controller.py .                                                      [ 15%]
api/api/controllers/test/test_experimental_controller.py ...............                                   [ 18%]
api/api/controllers/test/test_manager_controller.py ..................                                     [ 21%]
api/api/controllers/test/test_mitre_controller.py .......                                                  [ 22%]
api/api/controllers/test/test_overview_controller.py .                                                     [ 22%]
api/api/controllers/test/test_rootcheck_controller.py ....                                                 [ 23%]
api/api/controllers/test/test_rule_controller.py ........                                                  [ 25%]
api/api/controllers/test/test_sca_controller.py ..                                                         [ 25%]
api/api/controllers/test/test_security_controller.py ...................................................   [ 34%]
api/api/controllers/test/test_syscheck_controller.py ....                                                  [ 35%]
api/api/controllers/test/test_syscollector_controller.py .........                                         [ 37%]
api/api/controllers/test/test_task_controller.py .                                                         [ 37%]
api/api/controllers/test/test_vulnerability_controller.py ....                                             [ 38%]
api/api/models/test/test_model.py ...........................                                              [ 43%]
api/api/test/test_alogging.py ..................                                                           [ 46%]
api/api/test/test_authentication.py ...........                                                            [ 48%]
api/api/test/test_configuration.py ............................................                            [ 56%]
api/api/test/test_encoder.py ...                                                                           [ 56%]
api/api/test/test_middlewares.py ............                                                              [ 59%]
api/api/test/test_uri_parser.py ...                                                                        [ 59%]
api/api/test/test_util.py ..............................................                                   [ 68%]
api/api/test/test_validator.py ........................................................................... [ 81%]
..................................................................................................         [100%]


```

**Comment by EduLeon12** [comment]
## Test report

[integration_test_report.zip](https://github.com/wazuh/wazuh/files/10902985/integration_test_report.zip)

## Test results

---
| | | | | | |
|--|--|--|--|--|--|
| **Test name** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** | **Status** |
| *Integration Test* |
| test_agent_DELETE_endpoints.tavern.yaml    | 6 | 0 | 0 |  | :green_circle: |
| test_agent_GET_endpoints.tavern.yaml | 93 | 0 | 2 |  | :green_circle:  |
| test_agent_POST_endpoints.tavern.yaml | 9 | 0 | 1 |  | :red_circle: |
| test_agent_PUT_endpoints.tavern.yaml | 2 | 0 | 0 |  | :green_circle: |
| test_cluster_endpoints.tavern.yamll  | 49 | 0 | 0 |  | :green_circle: |
| test_experimental_endpoints.txt  | 12 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cluster_endpoints.tavern.yaml  | 19 | 0 | 0 |  | :green_circle: |
| test_rbac_black_sca_endpoints.tavern.yaml  | 2 | 0 | 0 |  | :green_circle: |
| test_rbac_black_security_endpoints.tavern.yaml | 25 | 0 | 0 |  | :green_circle: |
| test_rbac_white_sca_endpoints.tavern.yaml| 2 | 0 | 0 |  | :green_circle: |
| test_sca_endpoints.tavern.yaml| 45 | 1 | 0 |  | :green_circle: |

**Comment by EduLeon12** [comment]
Next step:
- [ ] Debug test_agent_POST_endpoints.tavern.yaml to analyze the failed test

**Comment by EduLeon12** [comment]
Integration test Updated with security endpoints 

## Test report

[integration_test_report_updated.zip](https://github.com/wazuh/wazuh/files/10913128/integration_test_report_updated.zip)

## Test results

---
| | | | | | |
|--|--|--|--|--|--|
| **Test name** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** | **Status** |
| *Integration Test* |
| test_agent_DELETE_endpoints.tavern.yaml    | 6 | 0 | 0 |  | :green_circle: |
| test_agent_GET_endpoints.tavern.yaml | 93 | 0 | 0 |  | :green_circle:  |
| test_agent_POST_endpoints.tavern.yaml | 6 | 0 | 0 |  | :green_circle: |
| test_agent_PUT_endpoints.tavern.yaml | 9 | 0 | 1 |  | :red_circle: |
| test_cluster_endpoints.tavern.yamll  | 49 | 0 | 1|  | :green_circle: |
| test_experimental_endpoints.txt  | 12 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cluster_endpoints.tavern.yaml  | 19 | 0 | 0 |  | :green_circle: |
| test_rbac_black_sca_endpoints.tavern.yaml  | 2 | 0 | 0 |  | :green_circle: |
| test_rbac_black_security_endpoints.tavern.yaml | 25 | 0 | 0 |  | :green_circle: |
| test_rbac_white_sca_endpoints.tavern.yaml| 2 | 0 | 0 |  | :green_circle: |
| test_sca_endpoints.tavern.yaml| 45 | 1 | 0 |  | :green_circle: |
| test_security_DELETE_endpoints.tavern.yaml  | 15 | 0 | 0 |  | :green_circle: |
| test_security_GET_endpoints.tavern.yaml | 11 | 0 | 2 |  | :green_circle:  |
| test_security_POST_endpoints.tavern.yaml | 68| 0 | 0 |  | :green_circle: |
| test_security_PUT_endpoints.tavern.yaml | 9 | 0 | 0 |  | :green_circle: |

**Comment by EduLeon12** [comment]
After debugging the Full test log for the failed **test_agent_PUT_endpoints.tavern.yaml** the error is in the following stage:

- Try to customly upgrade an agent selecting installer (WPK does not exist).

It was found there is an assertion error since expected response vs obtained response are opposites.
This can be seen in full_diff logged by tavern:

```
  Full diff:
    {
  -  'data': {'affected_items': [{'agent': '008',
  ?                              ^^^^^^^^^^^^^^^
  +  'data': {'affected_items': [],
  ?                              ^
  -                               'task_id': <tavern.util.loader.IntSentinel object at 0x7f55e4a49eb0>}],
  -           'failed_items': [],
  +           'failed_items': [{'error': {'code': 1820,
  +                                       'message': 'Upgrade procedure could not '
  +                                                  'start. Agent already '
  +                                                  'upgrading'},
  +                             'id': ['008']}],
  -           'total_affected_items': 1,
  ?                                   ^
  +           'total_affected_items': 0,
  ?                                   ^
  -           'total_failed_items': 0},
  ?                                 ^
  +           'total_failed_items': 1},
  ?                                 ^
  -  'message': <tavern.util.loader.StrSentinel object at 0x7f55e4a49df0>,
  +  'error': 1,
  +  'message': 'No upgrade task was created',
    }
```

But after testing locally, the error seems to be only when executed by tavern.

Local test info:

```
Local endpoint **/agents/upgrade_custom?agents_list=008&installer=upgrade.sh&file_path=/var/ossec/no_existant.wpk**  test response:

{
    "data": {
        "affected_items": [
            {
                "agent": "008",
                "task_id": 9
            }
        ],
        "total_affected_items": 1,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All upgrade tasks were created",
    "error": 0
}
```

Tavern Full test log: 

```
=================================== FAILURES ===================================
_ /home/eduardoleon/git/wazuh/api/test/integration/test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjAwMzExLCJleHAiOjE2NzgyMDEyMTEsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.ACA5cbDwOgqYZrQfEZiwlXrft_Dt0HQAJwkM_zuE0XGpVb8yZ8QFzs6MAkm8VYRlkfnxTbTOji1tpsvw1Hb8oeg2AdlCQTE5P5w6ZKLzLled_1iT4uXV47uy2D8VRHw8G99VH9upVrVTxVpJOwqAOM_Sh2q9HKCQb3EP5qJWOrZNGiCO'
  custom_wpk_path:s = '/var/ossec/test.wpk'

Source test stage (line 1237):
  - name: Try to customly upgrade an agent selecting installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '008'
        installer: upgrade.sh
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '008'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr


Formatted stage:
  name: Try to customly upgrade an agent selecting installer (WPK does not exist)
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MjAwMzExLCJleHAiOjE2NzgyMDEyMTEsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.ACA5cbDwOgqYZrQfEZiwlXrft_Dt0HQAJwkM_zuE0XGpVb8yZ8QFzs6MAkm8VYRlkfnxTbTOji1tpsvw1Hb8oeg2AdlCQTE5P5w6ZKLzLled_1iT4uXV47uy2D8VRHw8G99VH9upVrVTxVpJOwqAOM_Sh2q9HKCQb3EP5qJWOrZNGiCO
    method: PUT
    params:
      agents_list: 008
      file_path: '/var/ossec/test.wpk'
      installer: upgrade.sh
    url: 'https://localhost:55000/agents/upgrade_custom'
    verify: false
  response:
    json:
      data:
        affected_items:
        - agent: 008
          task_id: !anyint ''
        failed_items: []
        total_affected_items: 1
        total_failed_items: 0
      message: !anystr ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Try to customly upgrade an agent selecting installer (WPK does not exist)' failed:
    - Key mismatch: (expected["data"]["total_failed_items"] = '0' (type = <class 'int'>), actual["data"]["total_failed_items"] = '1' (type = <class 'int'>))
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '400'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:41 Key mismatch: (expected["data"]["total_failed_items"] = '0' (type = <class 'int'>), actual["data"]["total_failed_items"] = '1' (type = <class 'int'>))
Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'affected_items': [],\n          'failed_items': [{'error': {'code': 1820,\n                                      'message': 'Upgrade procedure could not '\n                                                 'start. Agent already '\n                                                 'upgrading'},\n                            'id': ['008']}],\n          'total_affected_items': 0,\n          'total_failed_items': 1},\n 'error': 1,\n 'message': 'No upgrade task was created'} == {'data': {'affected_items': [{'agent': '008',\n                              'task_id': <tavern.util.loader.IntSentinel object at 0x7f55e4a49eb0>}],\n          'failed_items': [],\n          'total_affected_items': 1,\n          'total_failed_items': 0},\n 'message': <tavern.util.loader.StrSentinel object at 0x7f55e4a49df0>}
  Differing items:
  {'data': {'affected_items': [], 'failed_items': [{'error': {'code': 1820, 'message': 'Upgrade procedure could not start. Agent already upgrading'}, 'id': ['008']}], 'total_affected_items': 0, 'total_failed_items': 1}} != {'data': {'affected_items': [{'agent': '008', 'task_id': <tavern.util.loader.IntSentinel object at 0x7f55e4a49eb0>}], 'failed_items': [], 'total_affected_items': 1, 'total_failed_items': 0}}
  {'message': 'No upgrade task was created'} != {'message': <tavern.util.loader.StrSentinel object at 0x7f55e4a49df0>}
  Left contains 1 more item:
  {'error': 1}
  Full diff:
    {
  -  'data': {'affected_items': [{'agent': '008',
  ?                              ^^^^^^^^^^^^^^^
  +  'data': {'affected_items': [],
  ?                              ^
  -                               'task_id': <tavern.util.loader.IntSentinel object at 0x7f55e4a49eb0>}],
  -           'failed_items': [],
  +           'failed_items': [{'error': {'code': 1820,
  +                                       'message': 'Upgrade procedure could not '
  +                                                  'start. Agent already '
  +                                                  'upgrading'},
  +                             'id': ['008']}],
  -           'total_affected_items': 1,
  ?                                   ^
  +           'total_affected_items': 0,
  ?                                   ^
  -           'total_failed_items': 0},
  ?                                 ^
  +           'total_failed_items': 1},
  ?                                 ^
  -  'message': <tavern.util.loader.StrSentinel object at 0x7f55e4a49df0>,
  +  'error': 1,
  +  'message': 'No upgrade task was created',
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_items': [],\n 'failed_items': [{'error': {'code': 1820,\n                             'message': 'Upgrade procedure could not start. '\n                                        'Agent already upgrading'},\n                   'id': ['008']}],\n 'total_affected_items': 0,\n 'total_failed_items': 1} == {'affected_items': [{'agent': '008',\n                     'task_id': <tavern.util.loader.IntSentinel object at 0x7f55e4a49eb0>}],\n 'failed_items': [],\n 'total_affected_items': 1,\n 'total_failed_items': 0}
  Differing items:
  {'total_failed_items': 1} != {'total_failed_items': 0}
  {'total_affected_items': 0} != {'total_affected_items': 1}
  {'affected_items': []} != {'affected_items': [{'agent': '008', 'task_id': <tavern.util.loader.IntSentinel object at 0x7f55e4a49eb0>}]}
  {'failed_items': [{'error': {'code': 1820, 'message': 'Upgrade procedure could not start. Agent already upgrading'}, 'id': ['008']}]} != {'failed_items': []}
  Full diff:
    {
  -  'affected_items': [{'agent': '008',
  -                      'task_id': <tavern.util.loader.IntSentinel object at 0x7f55e4a49eb0>}],
  -  'failed_items': [],
  ?    ^^^
  +  'affected_items': [],
  ?   + ^^^^
  +  'failed_items': [{'error': {'code': 1820,
  +                              'message': 'Upgrade procedure could not start. '
  +                                         'Agent already upgrading'},
  +                    'id': ['008']}],
  -  'total_affected_items': 1,
  ?                          ^
  +  'total_affected_items': 0,
  ?                          ^
  -  'total_failed_items': 0,
  ?                        ^
  +  'total_failed_items': 1,
  ?                        ^
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert 1 == 0
  +1
  -0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 546, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(
tavern.util.exceptions.KeyMismatchError: Key mismatch: (expected["data"]["total_failed_items"] = '0' (type = <class 'int'>), actual["data"]["total_failed_items"] = '1' (type = <class 'int'>))
=========================== short test summary info ============================
FAILED test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom

```


## Next steps:
- [ ] Discuss with the team the on how to address the tavern assertion error.

**Comment by EduLeon12** [comment]
## Update 

After investigating the current flow of how the module is configured, testing began to see how different parameters are used to initialize the module and how it affects the configuration files regarding priority.

Next Steps:

- [ ] Keep testing config behavior via module bash scripting.
- [ ] Analyze how the different configs are set when boto is used to start a session.
- [ ] After those result test solutions based on botocore Config object to avoid throttling.

**Comment by EduLeon12** [comment]
## Issue Update 

Error reported [here](https://github.com/wazuh/wazuh/issues/15465#issuecomment-1460172861) was fixed and merged [here](https://github.com/wazuh/wazuh/issues/16347).

Therefore tests will be relaunched to proceed with the closure of issue.


### API tests

```
(4.5-framework) eduardoleon@pop-os:~/git/wazuh$ PYTHONPATH=/home/eduardoleon/git/wazuh/api:/home/eduardoleon/git/wazuh/framework python3 -m pytest --disable-warnings api/api
======================================================= test session starts =======================================================
platform linux -- Python 3.9.9, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /home/eduardoleon/git/wazuh/api
plugins: aiohttp-0.3.0, trio-0.7.0, html-2.1.1, metadata-2.0.4, asyncio-0.15.1
collected 544 items                                                                                                               

api/api/controllers/test/test_active_response_controller.py .                                                               [  0%]
api/api/controllers/test/test_agent_controller.py ...........................................                               [  8%]
api/api/controllers/test/test_cdb_list_controller.py ......                                                                 [  9%]
api/api/controllers/test/test_ciscat_controller.py .                                                                        [  9%]
api/api/controllers/test/test_cluster_controller.py ........................                                                [ 13%]
api/api/controllers/test/test_decoder_controller.py .......                                                                 [ 15%]
api/api/controllers/test/test_default_controller.py .                                                                       [ 15%]
api/api/controllers/test/test_experimental_controller.py ...............                                                    [ 18%]
api/api/controllers/test/test_manager_controller.py ..................                                                      [ 21%]
api/api/controllers/test/test_mitre_controller.py .......                                                                   [ 22%]
api/api/controllers/test/test_overview_controller.py .                                                                      [ 22%]
api/api/controllers/test/test_rootcheck_controller.py ....                                                                  [ 23%]
api/api/controllers/test/test_rule_controller.py ........                                                                   [ 25%]
api/api/controllers/test/test_sca_controller.py ..                                                                          [ 25%]
api/api/controllers/test/test_security_controller.py ...................................................                    [ 34%]
api/api/controllers/test/test_syscheck_controller.py ....                                                                   [ 35%]
api/api/controllers/test/test_syscollector_controller.py .........                                                          [ 37%]
api/api/controllers/test/test_task_controller.py .                                                                          [ 37%]
api/api/controllers/test/test_vulnerability_controller.py ....                                                              [ 38%]
api/api/models/test/test_model.py ...........................                                                               [ 43%]
api/api/test/test_alogging.py ..................                                                                            [ 46%]
api/api/test/test_authentication.py ...........                                                                             [ 48%]
api/api/test/test_configuration.py ............................................                                             [ 56%]
api/api/test/test_encoder.py ...                                                                                            [ 56%]
api/api/test/test_middlewares.py ............                                                                               [ 59%]
api/api/test/test_uri_parser.py ...                                                                                         [ 59%]
api/api/test/test_util.py ..............................................                                                    [ 68%]
api/api/test/test_validator.py ............................................................................................ [ 85%]
.................................................................................                                           [100%]

================================================ 544 passed, 19 warnings in 2.22s =================================================
sys:1: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited

``` 


### Integration tests

After Relaunching the failing test.

```
(4.5-framework) eduardoleon@pop-os:~/git/wazuh/api/test/integration$ pytest -vv test_agent_PUT_endpoints.tavern.yaml
============================================================= test session starts ==============================================================
platform linux -- Python 3.9.9, pytest-7.2.2, pluggy-0.13.1 -- /home/eduardoleon/.pyenv/versions/4.5-framework/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.9.9', 'Platform': 'Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.2.2', 'pluggy': '0.13.1'}, 'Plugins': {'aiohttp': '0.3.0', 'tavern': '2.0.7', 'trio': '0.7.0', 'html': '2.1.1', 'metadata': '2.0.4', 'asyncio': '0.15.1'}}
rootdir: /home/eduardoleon/git/wazuh/api/test/integration, configfile: pytest.ini
plugins: aiohttp-0.3.0, tavern-2.0.7, trio-0.7.0, html-2.1.1, metadata-2.0.4, asyncio-0.15.1
collected 10 items                                                                                                                             

test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group PASSED                                                                           [ 10%]
test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration PASSED                                                        [ 20%]
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group/{group_id}/restart PASSED                                                        [ 30%]
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/reconnect PASSED                                                                       [ 40%]
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/restart PASSED                                                                         [ 50%]
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED                                                     [ 60%]
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED                                                              [ 70%]
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED                                                          [ 80%]
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/upgrade PASSED                                                                         [ 90%]
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom PASSED                                                       [100%]

=============================================================== warnings summary ===============================================================
test_agent_PUT_endpoints.tavern.yaml: 362 warnings
  /home/eduardoleon/.pyenv/versions/4.5-framework/lib/python3.9/site-packages/tavern/_core/schema/jsonschema.py:85: DeprecationWarning: Passing a schema to Validator.is_valid is deprecated and will be removed in a future release. Call validator.evolve(schema=new_schema).is_valid(...) instead.
    more_valid = [s for i, s in subschemas if validator.is_valid(instance, s)]

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================= 10 passed, 362 warnings in 629.17s (0:10:29) =================================================
```
