### ISSUE TITLE
 Release 4.4.0 - Alpha 1 - E2E UX tests - Elastic Stack installation

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#15526]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Elastic Stack installation|
| **Category**            |Installation|
| **Deployment option**   |Single indexer, server, and agent. Step by step|
| **Main release issue**  |https://github.com/wazuh/wazuh/issues/15505|
| **Main E2E UX test issue**  |https://github.com/wazuh/wazuh/issues/15519|
| **Release candidate #** |Alpha 1|

## Environment

| | | |
|-|-|-|
| **Component** | **OS** | **Installation** |
| Wazuh dashboard | Debian 10 | Step by step |
| Wazuh indexer | Debian 10 | Step by step |
| Wazuh server | Debian 10 | Step by step |
| Wazuh agent | Arch Linux| Step by step |

## Test description
Try latest version of Elastic Stack supported by our interface (Kibana plugin):
- Check that documentaiton steps work as intended.
- Check the WUI for any error or incorrect data
- Check that creation of new rules from the WUI works correctly
- Check that configuration of the manager from the WUI works correctly
- Check that the configuration/assignment of agent groups from the WUI works correctly 

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
| :red_circle:| [Environment installation(Elastic stack)](https://github.com/wazuh/wazuh/issues/15526#issuecomment-1332035496)|Typo in documentation, cluster error |https://github.com/wazuh/wazuh-documentation/issues/5781, https://github.com/wazuh/wazuh-kibana-app/issues/4938|
| :yellow_circle: |[General Check WUI](https://github.com/wazuh/wazuh/issues/15526#issuecomment-1332182752)|Different errors |https://github.com/wazuh/wazuh-packages/issues/1278, https://github.com/wazuh/wazuh-documentation/issues/5806|
| :green_circle:  |[Check creation of new rules from the WUI](https://github.com/wazuh/wazuh/issues/15526#issuecomment-1332466058)|||
| :yellow_circle: | [Check configuration of manager from WUI](https://github.com/wazuh/wazuh/issues/15526#issuecomment-1333646821) | Confusing interface ||
| :green_circle: | [Check configuration/assignment of groups from the WUI](https://github.com/wazuh/wazuh/issues/15526#issuecomment-1333657362) ||| 

All tests have passed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @wazuh/frontend 
- [x] @davidjiglesias

**Comment by verdx** [comment]
# :red_circle:   Check 0 - Environment installation 
### :yellow_circle: Elasticsearch installation
In the documentation, in the second step to `Elasticsearch installation and configuration`, the command called to download the configuration file is : 
```
curl -so /etc/elasticsearch/elasticsearch.yml https://packages.wazuh.com/4.3/tpl/elastic-basic/elasticsearch.yml
```
whith an incorrect url, it should be:
```
curl -so /etc/elasticsearch/elasticsearch.yml https://packages.wazuh.com/4.4/tpl/elastic-basic/elasticsearch.yml
```
Issue for documentation team commenting the typo: https://github.com/wazuh/wazuh-documentation/issues/5781

<details>

```
root@debian10:/home/vagrant# apt-get install lsb-release curl apt-transport-https zip unzip gnupg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnupg is already the newest version (2.2.12-1+deb10u2).
gnupg set to manually installed.
lsb-release is already the newest version (10.2019051400).
curl is already the newest version (7.64.0-4+deb10u3).
The following NEW packages will be installed:
  apt-transport-https unzip zip
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 555 kB of archives.
After this operation, 1,359 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian buster/main amd64 apt-transport-https all 1.8.2.3 [149 kB]
Get:2 http://security.debian.org/debian-security buster/updates/main amd64 unzip amd64 6.0-23+deb10u3 [172 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 zip amd64 3.0-11+b1 [234 kB]
Fetched 555 kB in 0s (1,973 kB/s)                         
Selecting previously unselected package apt-transport-https.
(Reading database ... 65394 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.2.3_all.deb ...
Unpacking apt-transport-https (1.8.2.3) ...
Selecting previously unselected package unzip.
Preparing to unpack .../unzip_6.0-23+deb10u3_amd64.deb ...
Unpacking unzip (6.0-23+deb10u3) ...
Selecting previously unselected package zip.
Preparing to unpack .../zip_3.0-11+b1_amd64.deb ...
Unpacking zip (3.0-11+b1) ...
Setting up apt-transport-https (1.8.2.3) ...
Setting up unzip (6.0-23+deb10u3) ...
Setting up zip (3.0-11+b1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for mime-support (3.62) ...
```

```
root@debian10:/home/vagrant# curl -s https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/elasticsearch.gpg --import && chmod 644 /usr/share/keyrings/elasticsearch.gpg
gpg: keyring '/usr/share/keyrings/elasticsearch.gpg' created
gpg: directory '/root/.gnupg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key D27D666CD88E42B4: public key "Elasticsearch (Elasticsearch Signing Key) <dev_ops@elasticsearch.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
root@debian10:/home/vagrant# echo "deb [signed-by=/usr/share/keyrings/elasticsearch.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-7.x.list
deb [signed-by=/usr/share/keyrings/elasticsearch.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main
```

```
root@debian10:/home/vagrant# apt-get update
Hit:1 http://deb.debian.org/debian buster InRelease
Get:2 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]        
Get:3 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
Get:4 https://artifacts.elastic.co/packages/7.x/apt stable InRelease [13.7 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main Sources [279 kB]
Get:6 https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages [106 kB]
Get:7 http://security.debian.org/debian-security buster/updates/main amd64 Packages [405 kB]
Get:8 http://security.debian.org/debian-security buster/updates/main Translation-en [217 kB]
Fetched 1,112 kB in 1s (1,025 kB/s)                             
Reading package lists... Done
root@debian10:/home/vagrant# apt-get install elasticsearch=7.17.6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  elasticsearch
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 308 MB of archives.
After this operation, 512 MB of additional disk space will be used.
Get:1 https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 elasticsearch amd64 7.17.6 [308 MB]
Fetched 308 MB in 1min 4s (4,792 kB/s)                                                                                                                                                                            
Selecting previously unselected package elasticsearch.
(Reading database ... 65432 files and directories currently installed.)
Preparing to unpack .../elasticsearch_7.17.6_amd64.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (7.17.6) ...
Setting up elasticsearch (7.17.6) ...
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
Created elasticsearch keystore in /etc/elasticsearch/elasticsearch.keystore
Processing triggers for systemd (241-7~deb10u8) ...
```

```
root@debian10:/home/vagrant# cat /usr/share/elasticsearch/instances.yml 
instances:
- name: "elasticsearch"
  ip:
  - "192.168.57.122"
- name: "filebeat"
  ip:
  - "192.168.57.123"
- name: "kibana"
  ip:
  - "192.168.57.124"
root@debian10:/home/vagrant# 
```

```
root@debian10:/home/vagrant# /usr/share/elasticsearch/bin/elasticsearch-certutil cert ca --pem --in instances.yml --keep-ca-key --out ~/certs.zip
Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: ParsingException[Failed to parse object: expecting token of type [START_OBJECT] but found [VALUE_STRING]];
	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1189)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1160)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:75)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:91)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:82)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
	at org.elasticsearch.xpack.security.cli.CertificateTool.main(CertificateTool.java:149)
Caused by: ParsingException[Failed to parse object: expecting token of type [START_OBJECT] but found [VALUE_STRING]]
	at org.elasticsearch.common.xcontent.XContentParserUtils.parsingException(XContentParserUtils.java:77)
	at org.elasticsearch.common.xcontent.XContentParserUtils.ensureExpectedToken(XContentParserUtils.java:70)
	at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:672)
	at org.elasticsearch.common.settings.Settings.access$400(Settings.java:75)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1185)
	... 10 more
root@debian10:/home/vagrant# 
```
</details>

**Comment by verdx** [comment]
# :yellow_circle: WUI Check
### - API problem
As contemplated in the documentation, in the first access attempt the user gets a screen like this:
![APIconnectionError](https://user-images.githubusercontent.com/61122643/204812771-5e6fabf0-3ef8-4e7f-8e1c-9342bf93e026.png)

Doing the changes specified in the documentation(changing a line in file `/usr/share/kibana/data/wazuh/config/wazuh.yml`) and restarting the Kibana service, the API works.  The solution should be given before the user opens the WUI for the first time, as it looks more like a not at all elegant patch.

**Comment by verdx** [comment]
# :green_circle: Check creation of rules from the WUI

### :green_circle: Creation of rule

<details>

The rule has been created with no problem

![rule_created](https://user-images.githubusercontent.com/61122643/204860101-7bf6e0e1-71a0-4a6e-b539-21fa906382cd.png)

![rulecreated](https://user-images.githubusercontent.com/61122643/204860090-d8732b24-8f2e-47d9-a986-32ec0bc2f7e6.png)

</details>

**Comment by verdx** [comment]
# :yellow_circle: Check configuration of manager from the WUI

<details>

The configuration can be accessed in `Management->Configuration->Edit Configuration`:

![ossecconf_changedemail](https://user-images.githubusercontent.com/61122643/205044791-8f2ca354-bfe1-431b-8873-8fb0cb072f2c.png)

The field `ossec_config->global->email_to` has been changed to `miguel.verdaguer@wazuh.com` and saved. As you can see here, the file is correctly changed and it has no interface problems.

```
root@debian101:/home/vagrant# cat /var/ossec/etc/ossec.conf | grep email
    <email_notification>no</email_notification>
    <email_from>wazuh@example.wazuh.com</email_from>
    <email_to>miguel.verdaguer@wazuh.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <email_alert_level>12</email_alert_level>
root@debian101:/home/vagrant# 
```

On the other hand, the configuration page is a little confusing, as it would seem as if you could change configurations from there. Each field is in what seems like a writing prompt, but they are not modifiable.

</details>

**Comment by verdx** [comment]
# :green_circle: Check configuration/assignment of groups from the GUI

<details>

![create_group](https://user-images.githubusercontent.com/61122643/205047179-7edf4886-f861-4352-94a0-f9ae1a60ef77.png)
![adding_agent](https://user-images.githubusercontent.com/61122643/205047182-5f5e8c1a-fcfa-40c8-b7e9-d720516c5323.png)
![remove_agent](https://user-images.githubusercontent.com/61122643/205047185-bf4451e2-b72a-4333-af3f-10b64e91afe5.png)

As can be seen in the console, the configuration shown in the previous screenshots has been correctly done and saved:

```
root@debian101:/home/vagrant# /var/ossec/bin/agent_groups -s -i 001
The agent 'archlinux' with ID '001' belongs to groups: test_group.
root@debian101:/home/vagrant# 
```

</details>
