### ISSUE TITLE
Release 4.4.0 - Alpha 1 - E2E UX tests - Configuration assessment

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#15541]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.
## Modules tests information

|||
|----------------------------------|------ |
| **Main release candidate issue** | #15505  |
| **Main E2E UX test issue** | #15519    |
| **Version**                      | 4.3.9 |
| **Release candidate #**          | Alpha 1   |
| **Tag**                          | [v4.4.0-alpha1](https://github.com/wazuh/wazuh/tree/v4.4.0-alpha1) |
| **Previous modules tests issue** | #15102  |

## Installation procedure

---

|  Component   | Installation type   | Installation procedure | System  |
|-------------|---------------|-------------|-------------|
|Wazuh server | Single node  | Installation assistant |Debian11|
|Indexer | Multinode  |  Installation assistant | Debian11|
|Dashboard | - | Installation assistant | Debian11|
|Agent |  |  Wazuh WUI one-liner deploy FQDN| Ubuntu 22.04, Red Hat Enterprise Linux 9, Windows 11|

https://github.com/wazuh/wazuh/issues/15102#issuecomment-1273004659

## Test description

For the selected Wazuh Agent OS:
- [x] Check that their respective SCA policies are applied properly
- [x] Use and activate a custom policy for any of them
- [x] Disable an used policy and confirm it is not used anymore
- [x] Push SCA config through centralized config and check it applies properly

https://github.com/wazuh/wazuh/issues/15541#issuecomment-1337576706

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | Test went as expected. |
| :red_circle:  | Test fails and must be addressed. |
| :yellow_circle:  | Test meet the goal but some improvements must be addressed for UX|

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
|:yellow_circle: |Validate the correct installation| When installing a wazuh server single-node, the following error is displayed |  https://github.com/wazuh/wazuh/issues/15541#issuecomment-1338264877 |
|:green_circle: |Check that their respective SCA policies are applied properly|--| 
|:green_circle: |Disable an used policy and confirm it is not used anymore|--|  |
|:green_circle: | Push SCA config through centralized config and check it applies properly|--|  |

## Auditors' validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @wazuh/watchdogs 
- [ ] @davidjiglesias

**Comment by fcaffieri** [comment]
# Installation Wazuh central components

## Wazuh Indexer Multi-node :green_circle: 

### Install and configure

<details>
<summary>config.yml</summary>

```
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: indexer-1
      ip: 172.16.1.111
    - name: indexer-2
      ip: 172.16.1.112

  server:
    - name: server-1
      ip: 172.16.1.110

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard-1
      ip: 172.16.1.113
```
</details>

<details>
<summary>Node 1: `indexer-1`</summary>

```
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# curl -sO https://packages-dev.wazuh.com/4.4/wazuh-install.sh
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# ls -ltr
total 152
-rw-r--r-- 1 root root 154555 dez  1 17:39 wazuh-install.sh
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# curl -sO https://packages-dev.wazuh.com/4.4/config.yml
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# nano config.yml 

```

#### Generate config files

```
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# bash wazuh-install.sh --generate-config-files -i
01/12/2022 17:41:29 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
01/12/2022 17:41:29 INFO: Verbose logging redirected to /var/log/wazuh-install.log
01/12/2022 17:41:30 WARNING: Hardware and system checks ignored.
01/12/2022 17:41:30 INFO: --- Configuration files ---
01/12/2022 17:41:30 INFO: Generating configuration files.
01/12/2022 17:41:31 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# ls -tlr
total 168
-rw-r--r-- 1 root root 154555 dez  1 17:39 wazuh-install.sh
-rw------- 1 root root  12298 dez  1 17:41 wazuh-install-files.tar

```

#### Install `indexer-1`

```
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# bash wazuh-install.sh --wazuh-indexer indexer-1 -i
01/12/2022 17:42:17 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
01/12/2022 17:42:17 INFO: Verbose logging redirected to /var/log/wazuh-install.log
01/12/2022 17:42:17 WARNING: Hardware and system checks ignored.
01/12/2022 17:42:21 INFO: --- Dependencies ----
01/12/2022 17:42:21 INFO: Installing apt-transport-https.
01/12/2022 17:42:22 INFO: Installing software-properties-common.
01/12/2022 17:42:32 INFO: Wazuh development repository added.
01/12/2022 17:42:32 INFO: --- Wazuh indexer ---
01/12/2022 17:42:32 INFO: Starting Wazuh indexer installation.
01/12/2022 17:43:22 INFO: Wazuh indexer installation finished.
01/12/2022 17:43:22 INFO: Wazuh indexer post-install configuration finished.
01/12/2022 17:43:22 INFO: Starting service wazuh-indexer.
01/12/2022 17:44:04 INFO: wazuh-indexer service started.
01/12/2022 17:44:04 INFO: Initializing Wazuh indexer cluster security settings.
01/12/2022 17:44:04 INFO: Wazuh indexer cluster initialized.
01/12/2022 17:44:04 INFO: Installation finished.

```

#### Copy files to all vm's

```

root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# scp wazuh-install-files.tar vagrant@172.16.1.110:/home/vagrant/
The authenticity of host '172.16.1.110 (172.16.1.110)' can't be established.
ECDSA key fingerprint is SHA256:fO9jAd+rAbJLkYXaeH553OzYlm+FrpVckaL5sZDWnks.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '172.16.1.110' (ECDSA) to the list of known hosts.
vagrant@172.16.1.110's password: 
wazuh-install-files.tar                                                                                                                       100%   12KB   3.7MB/s   00:00    
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# scp wazuh-install-files.tar vagrant@172.16.1.112:/home/vagrant/
The authenticity of host '172.16.1.112 (172.16.1.112)' can't be established.
ECDSA key fingerprint is SHA256:DXvGSpStMBWwsmRfeEODnc1J/6c8nT2t6Fv0oYPrp4A.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '172.16.1.112' (ECDSA) to the list of known hosts.
vagrant@172.16.1.112's password: 
wazuh-install-files.tar                                                                                                                       100%   12KB   3.1MB/s   00:00    
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# scp wazuh-install-files.tar vagrant@172.16.1.113:/home/vagrant/
The authenticity of host '172.16.1.113 (172.16.1.113)' can't be established.
ECDSA key fingerprint is SHA256:aIYSDTj9oTHSJhsyWSr3rNgKXj/3eeDulgxZLFsJ9Ww.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '172.16.1.113' (ECDSA) to the list of known hosts.
vagrant@172.16.1.113's password: 
wazuh-install-files.tar                                                                                                                       100%   12KB   8.0MB/s   00:00    

```

#### Start cluster

```
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# bash wazuh-install.sh --start-cluster -i
01/12/2022 17:47:52 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
01/12/2022 17:47:52 INFO: Verbose logging redirected to /var/log/wazuh-install.log
01/12/2022 17:47:53 WARNING: Hardware and system checks ignored.
01/12/2022 17:48:02 INFO: Wazuh indexer cluster security configuration initialized.
01/12/2022 17:48:10 INFO: Wazuh indexer cluster started.
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# tar -axf wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O | grep -P "\'admin\'" -A 1
  indexer_username: 'admin'
  indexer_password: 'y5I7NmcqNCifPUFgSTxp+kedzx55AXk.'
```

#### Status

```
  
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# curl -k -u admin:y5I7NmcqNCifPUFgSTxp+kedzx55AXk. https://172.16.1.111:9200
{
  "name" : "indexer-1",
  "cluster_name" : "wazuh-indexer-cluster",
  "cluster_uuid" : "TtuTcMNASmOeph5fpPvKIQ",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "6f6e84ebc54af31a976f53af36a5c69d474a5140",
    "build_date" : "2022-09-09T00:07:12.137133581Z",
    "build_snapshot" : false,
    "lucene_version" : "9.3.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}

```
</details>

<details>
<summary>Node 2: `indexer-2`</summary>

```
root@test-e2e-sca-indexer-node2-Debian11-112:/home/vagrant# bash wazuh-install.sh --wazuh-indexer indexer-2
bash: wazuh-install.sh: Arquivo ou diretório inexistente
root@test-e2e-sca-indexer-node2-Debian11-112:/home/vagrant# curl -sO https://packages-dev.wazuh.com/4.4/wazuh-install.sh
root@test-e2e-sca-indexer-node2-Debian11-112:/home/vagrant# bash wazuh-install.sh --wazuh-indexer indexer-2 -i
01/12/2022 17:46:05 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
01/12/2022 17:46:05 INFO: Verbose logging redirected to /var/log/wazuh-install.log
01/12/2022 17:46:06 WARNING: Hardware and system checks ignored.
01/12/2022 17:46:09 INFO: --- Dependencies ----
01/12/2022 17:46:09 INFO: Installing apt-transport-https.
01/12/2022 17:46:10 INFO: Installing software-properties-common.
01/12/2022 17:46:20 INFO: Wazuh development repository added.
01/12/2022 17:46:20 INFO: --- Wazuh indexer ---
01/12/2022 17:46:20 INFO: Starting Wazuh indexer installation.
01/12/2022 17:46:58 INFO: Wazuh indexer installation finished.
01/12/2022 17:46:58 INFO: Wazuh indexer post-install configuration finished.
01/12/2022 17:46:58 INFO: Starting service wazuh-indexer.
01/12/2022 17:47:12 INFO: wazuh-indexer service started.
01/12/2022 17:47:12 INFO: Initializing Wazuh indexer cluster security settings.
01/12/2022 17:47:12 INFO: Wazuh indexer cluster initialized.
01/12/2022 17:47:12 INFO: Installation finished.

```

#### Start cluster

```
root@test-e2e-sca-indexer-node2-Debian11-112:/home/vagrant# bash wazuh-install.sh --start-cluster -i
01/12/2022 17:48:17 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
01/12/2022 17:48:17 INFO: Verbose logging redirected to /var/log/wazuh-install.log
01/12/2022 17:48:19 WARNING: Hardware and system checks ignored.
01/12/2022 17:48:22 INFO: Wazuh indexer cluster security configuration initialized.
01/12/2022 17:48:29 INFO: Wazuh indexer cluster started.

```

#### Status

```
root@test-e2e-sca-indexer-node2-Debian11-112:/home/vagrant# tar -axf wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O | grep -P "\'admin\'" -A 1
  indexer_username: 'admin'
  indexer_password: 'y5I7NmcqNCifPUFgSTxp+kedzx55AXk.'
root@test-e2e-sca-indexer-node2-Debian11-112:/home/vagrant# curl -k -u admin:y5I7NmcqNCifPUFgSTxp+kedzx55AXk. https://172.16.1.112:9200
{
  "name" : "indexer-2",
  "cluster_name" : "wazuh-indexer-cluster",
  "cluster_uuid" : "TtuTcMNASmOeph5fpPvKIQ",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "6f6e84ebc54af31a976f53af36a5c69d474a5140",
    "build_date" : "2022-09-09T00:07:12.137133581Z",
    "build_snapshot" : false,
    "lucene_version" : "9.3.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}

```
</details>

<details>
<summary>Status Multinode Indexer</summary>

```
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# curl -k -u admin:y5I7NmcqNCifPUFgSTxp+kedzx55AXk. https://172.16.1.111:9200/_cluster/health?pretty
{
  "cluster_name" : "wazuh-indexer-cluster",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 2,
  "discovered_master" : true,
  "discovered_cluster_manager" : true,
  "active_primary_shards" : 7,
  "active_shards" : 12,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
root@test-e2e-sca-indexer-Debian11-111:/home/vagrant# 

```
</details>

---

## Wazuh Server Single-node :green_circle: 

### Install and configure

<details>

```
root@test-e2e-sca-server-Debian11-110:/home/vagrant# curl -sO https://packages-dev.wazuh.com/4.4/wazuh-install.sh
root@test-e2e-sca-server-Debian11-110:/home/vagrant# bash wazuh-install.sh --wazuh-server server-1 -i
01/12/2022 17:50:13 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
01/12/2022 17:50:13 INFO: Verbose logging redirected to /var/log/wazuh-install.log
01/12/2022 17:50:14 WARNING: Hardware and system checks ignored.
01/12/2022 17:50:18 INFO: --- Dependencies ----
01/12/2022 17:50:18 INFO: Installing apt-transport-https.
01/12/2022 17:50:19 INFO: Installing software-properties-common.
01/12/2022 17:50:27 INFO: Wazuh development repository added.
01/12/2022 17:50:28 INFO: --- Wazuh server ---
01/12/2022 17:50:28 INFO: Starting the Wazuh manager installation.
01/12/2022 17:51:10 INFO: Wazuh manager installation finished.
01/12/2022 17:51:10 INFO: Starting service wazuh-manager.
01/12/2022 17:51:26 INFO: wazuh-manager service started.
01/12/2022 17:51:26 INFO: Starting Filebeat installation.
01/12/2022 17:51:32 INFO: Filebeat installation finished.
01/12/2022 17:51:33 INFO: Filebeat post-install configuration finished.
01/12/2022 17:51:37 INFO: Starting service filebeat.
01/12/2022 17:51:38 INFO: filebeat service started.
01/12/2022 17:51:38 INFO: Installation finished.
root@test-e2e-sca-server-Debian11-110:/home/vagrant#
```
</details>

---

## Dashboard :green_circle: 

<details>
<summary>Install</summary>

```
root@test-e2e-sca-dashboard-Debian11-113:/home/vagrant# curl -sO https://packages-dev.wazuh.com/4.4/wazuh-install.sh
root@test-e2e-sca-dashboard-Debian11-113:/home/vagrant# ls -la
total 192
drwxr-xr-x 3 vagrant vagrant   4096 dez  1 17:47 .
drwxr-xr-x 3 root    root      4096 nov 15 05:47 ..
-rw-r--r-- 1 vagrant vagrant    220 nov 15 05:47 .bash_logout
-rw-r--r-- 1 vagrant vagrant   3526 nov 15 05:47 .bashrc
-rw-r--r-- 1 vagrant vagrant    807 nov 15 05:47 .profile
drwx------ 2 vagrant vagrant   4096 dez  1 17:37 .ssh
-rw------- 1 vagrant vagrant  12298 dez  1 17:45 wazuh-install-files.tar
-rw-r--r-- 1 root    root    154555 dez  1 17:47 wazuh-install.sh
root@test-e2e-sca-dashboard-Debian11-113:/home/vagrant# bash wazuh-install.sh --wazuh-dashboard dashboard-1 -i
01/12/2022 17:52:06 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
01/12/2022 17:52:06 INFO: Verbose logging redirected to /var/log/wazuh-install.log
01/12/2022 17:52:07 WARNING: Hardware and system checks ignored.
01/12/2022 17:52:10 INFO: --- Dependencies ----
01/12/2022 17:52:10 INFO: Installing apt-transport-https.
01/12/2022 17:52:11 INFO: Installing software-properties-common.
01/12/2022 17:52:20 INFO: Wazuh development repository added.
dashboard-1
01/12/2022 17:52:20 INFO: --- Wazuh dashboard ----
01/12/2022 17:52:20 INFO: Starting Wazuh dashboard installation.
01/12/2022 17:53:05 INFO: Wazuh dashboard installation finished.
01/12/2022 17:53:05 INFO: Wazuh dashboard post-install configuration finished.
01/12/2022 17:53:05 INFO: Starting service wazuh-dashboard.
01/12/2022 17:53:05 INFO: wazuh-dashboard service started.
01/12/2022 17:53:24 INFO: Initializing Wazuh dashboard web application.
01/12/2022 17:53:25 INFO: Wazuh dashboard web application initialized.
01/12/2022 17:53:25 INFO: --- Summary ---
01/12/2022 17:53:25 INFO: You can access the web interface https://172.16.1.113
    User: admin
    Password: y5I7NmcqNCifPUFgSTxp+kedzx55AXk.
01/12/2022 17:53:25 INFO: Installation finished.
root@test-e2e-sca-dashboard-Debian11-113:/home/vagrant#
```
![image](https://user-images.githubusercontent.com/89791732/205169306-e7283c66-0ce8-4ceb-a012-ebffe71891f0.png)
![image](https://user-images.githubusercontent.com/89791732/205169394-3da50002-6596-4b38-b00f-99aae5e9e5ef.png)

</details>

---

## Agents :green_circle: 

<details>
<summary>Install Ubuntu Jammy</summary>

```
root@test-e2e-sca-agent-Ubuntu22-114:/home/vagrant# curl -so wazuh-agent_4.4.0-1_amd64.deb https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_amd64.deb
root@test-e2e-sca-agent-Ubuntu22-114:/home/vagrant# WAZUH_MANAGER="172.16.1.110" apt-get install ./wazuh-agent_4.4.0-1_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'wazuh-agent' instead of './wazuh-agent_4.4.0-1_amd64.deb'
The following NEW packages will be installed:
  wazuh-agent
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/8,810 kB of archives.
After this operation, 29.6 MB of additional disk space will be used.
Get:1 /home/vagrant/wazuh-agent_4.4.0-1_amd64.deb wazuh-agent amd64 4.4.0-1 [8,810 kB]
Preconfiguring packages ...
Selecting previously unselected package wazuh-agent.
(Reading database ... 43570 files and directories currently installed.)
Preparing to unpack .../wazuh-agent_4.4.0-1_amd64.deb ...
Unpacking wazuh-agent (4.4.0-1) ...
Setting up wazuh-agent (4.4.0-1) ...
Scanning processes...                                                                                                                                                           
Scanning linux images...                                                                                                                                                        

Running kernel seems to be up-to-date.

root@test-e2e-sca-agent-Ubuntu22-114:/home/vagrant# 

root@test-e2e-sca-agent-Ubuntu22-114:/home/vagrant# 
root@test-e2e-sca-agent-Ubuntu22-114:/home/vagrant# systemctl daemon-reload
systemctl enable wazuh-agent
systemctl start wazuh-agent
Synchronizing state of wazuh-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable wazuh-agent
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-agent.service → /lib/systemd/system/wazuh-agent.service.
root@test-e2e-sca-agent-Ubuntu22-114:/home/vagrant# 

```
</details>

<details>
<summary>Red Hat 9</summary>

```
[root@test-e2e-sca-agent-RedHat9-115 vagrant]# curl -so wazuh-agent-4.4.0-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.4.0-1.x86_64.rpm
[root@test-e2e-sca-agent-RedHat9-115 vagrant]# ls -la
total 71156
drwx------. 4 vagrant vagrant     4096 Dec  1 21:13 .
drwxr-xr-x. 3 root    root        4096 Nov 27 00:01 ..
drwx------. 3 vagrant vagrant     4096 Nov 27 00:22 .ansible
-rw-r--r--. 1 vagrant vagrant      141 Aug  8 13:07 .bash_profile
-rw-r--r--. 1 vagrant vagrant      492 Aug  8 13:07 .bashrc
drwx------. 2 vagrant vagrant     4096 Dec  1 20:37 .ssh
-rw-r--r--. 1 vagrant vagrant 63883264 Nov 27 00:05 VBoxGuestAdditions.iso
-rw-r--r--. 1 vagrant vagrant        6 Nov 27 00:05 .vbox_version
-rw-r--r--. 1 root    root     8947922 Dec  1 21:13 wazuh-agent-4.4.0-1.x86_64.rpm
[root@test-e2e-sca-agent-RedHat9-115 vagrant]# WAZUH_MANAGER="172.16.1.110" yum install ./wazuh-agent-4.4.0-1.x86_64.rpm
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 0:08:54 ago on Thu 01 Dec 2022 09:06:19 PM UTC.
Dependencies resolved.
================================================================================================================================================================================
 Package                                     Architecture                           Version                                  Repository                                    Size
================================================================================================================================================================================
Installing:
 wazuh-agent                                 x86_64                                 4.4.0-1                                  @commandline                                 8.5 M

Transaction Summary
================================================================================================================================================================================
Install  1 Package

Total size: 8.5 M
Installed size: 25 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                        1/1 
  Running scriptlet: wazuh-agent-4.4.0-1.x86_64                                                                                                                             1/1 
  Installing       : wazuh-agent-4.4.0-1.x86_64                                                                                                                             1/1 
  Running scriptlet: wazuh-agent-4.4.0-1.x86_64                                                                                                                             1/1 
  Verifying        : wazuh-agent-4.4.0-1.x86_64                                                                                                                             1/1 
Installed products updated.

Installed:
  wazuh-agent-4.4.0-1.x86_64                                                                                                                                                    

Complete!
[root@test-e2e-sca-agent-RedHat9-115 vagrant]# systemctl daemon-reload
systemctl enable wazuh-agent
systemctl start wazuh-agent
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-agent.service → /usr/lib/systemd/system/wazuh-agent.service.
[root@test-e2e-sca-agent-RedHat9-115 vagrant]# sed -i "s/^enabled=1/enabled=0/" /etc/yum.repos.d/wazuh.repo
[root@test-e2e-sca-agent-RedHat9-115 vagrant]# 

```
</details>

<details>
<summary>Windows 11</summary>

![image](https://user-images.githubusercontent.com/89791732/205169848-2f85155d-38a5-4417-9f76-28b2e6761543.png)

</details>

<details>
<summary>Agents connection</summary>

```
root@test-e2e-sca-server-Debian11-110:/home/vagrant# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: test-e2e-sca-server-Debian11-110 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: test-e2e-sca-agent-RedHat9-115, IP: any, Active
   ID: 002, Name: test-e2e-sca-agent-Ubuntu22-114, IP: any, Active
   ID: 003, Name: test-e2e-sca-agent-Windows11, IP: any, Active

List of agentless devices:

root@test-e2e-sca-server-Debian11-110:/home/vagrant# 
```

![image](https://user-images.githubusercontent.com/89791732/205170532-c7bd92f5-7624-489b-b201-1522ff054d21.png)

</details>

**Comment by fcaffieri** [comment]
# Tests

## Check that their respective SCA policies are applied properly :green_circle: 

### Ubuntu 22 :green_circle: 
<details>

![image](https://user-images.githubusercontent.com/89791732/205675018-556652ab-627d-400f-bfe5-e3b0bc6cd2cf.png)

</details>

### RHEL 9 :green_circle: 
<details>

![image](https://user-images.githubusercontent.com/89791732/205675098-3dcc36bd-7243-4316-a023-ca302eb4aaac.png)

</details>

### Windows 11 :green_circle: 
<details>

![image](https://user-images.githubusercontent.com/89791732/205675157-906540d6-4ecb-448e-b70b-99e597f82012.png)

</details>

## Use and activate a custom policy for any of them :green_circle: 

### Ubuntu 22 :green_circle: 
<details>



</details>

### RHEL 9 :green_circle: 
<details>



</details>

### Windows 11 :green_circle: 
<details>



</details>

## Disable an used policy and confirm it is not used anymore :green_circle: 

### Ubuntu 22 :green_circle: 
<details>

- Configuration


- Log


</details>

### RHEL 9 :green_circle: 
<details>

- Configuration


- Log

</details>

### Windows 11 :green_circle: 
<details>

- Configuration


- Log

</details>

## Push SCA config through centralized config and check it applies properly :green_circle: 

### Ubuntu 22 :green_circle: 
<details>

- Configuration


- Log


</details>

### RHEL 9 :green_circle: 
<details>

- Configuration


- Log

</details>

### Windows 11 :green_circle: 
<details>

- Configuration


- Log

</details>

**Comment by fcaffieri** [comment]
# Instalation Wazuh server single node :yellow_circle:  

```
Error: 3013 - Cluster is not running, it might be disabled in `WAZUH_HOME/etc/ossec.conf`
    at createError (https://172.16.1.113/440/bundles/plugin/wazuh/wazuh.plugin.js:2:28658)
    at settle (https://172.16.1.113/440/bundles/plugin/wazuh/wazuh.plugin.js:8:19613)
    at XMLHttpRequest.onloadend (https://172.16.1.113/440/bundles/plugin/wazuh/wazuh.plugin.js:2:26451)
```
![image](https://user-images.githubusercontent.com/89791732/205755808-2d17027f-f39e-46b2-94be-63685f74626a.png)
![image](https://user-images.githubusercontent.com/89791732/205755861-b1dd7083-6b85-4a0e-a97e-cba86f0d6993.png)

**Comment by fcaffieri** [comment]
# Installation Agents with UI problems found :yellow_circle: 

# Windows 11

### Reported on issue: https://github.com/wazuh/wazuh-kibana-app/issues/4949

### UI
![image](https://user-images.githubusercontent.com/89791732/205182615-072dc948-5b8c-40de-9684-34dab33865fe.png)
![image](https://user-images.githubusercontent.com/89791732/205182679-16b1a477-1d0f-445d-9ae6-bcca57f0f5fc.png)
![image](https://user-images.githubusercontent.com/89791732/205182698-04de9e28-03ad-4f5f-a762-7d7e1f5b638c.png)

![image](https://user-images.githubusercontent.com/89791732/205664311-b794d02e-870b-48e8-8c22-48a13817130f.png)

![image](https://user-images.githubusercontent.com/89791732/205182516-80cdf84a-34e8-4c3a-8a4b-3ecb5708b68e.png)

# Install Ubuntu Jammy :yellow_circle: 

### Reported on issue: https://github.com/wazuh/wazuh-kibana-app/issues/4958

#### UI

The UI does not place the revision number:
![image](https://user-images.githubusercontent.com/89791732/205180316-816539a7-9de5-44fc-9a5f-960855207942.png)

![image](https://user-images.githubusercontent.com/89791732/205180466-d1e00a02-f9ab-4921-bd31-6f9be3277648.png)
![image](https://user-images.githubusercontent.com/89791732/205180503-9c737a49-e89a-4346-a3de-d44fe409d289.png)
![image](https://user-images.githubusercontent.com/89791732/205180531-c075a570-58f5-44bc-8f57-1a3b398fe005.png)
