### ISSUE TITLE
Unable to upgrade remotely agents Ubuntu 16.04 

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#1563]
Testing the new packages of Wazuh v3.7.0 the following issue appears when upgrading by WPK an agent v3.7.0 Ubuntu 16.04:

From the manager side:

```
# agent_upgrade -a 002 -r <url> -d
Manager version: v3.7.0
Agent version: v3.6.1
Agent new version: v3.7.0
WPK file already downloaded: /var/ossec/var/upgrade/wazuh_agent_v3.7.0_linux_x86_64.wpk - SHA1SUM: d9bf7df47145ac2a5aa82689e685daeac3c20e80
Upgrade PKG: wazuh_agent_v3.7.0_linux_x86_64.wpk (16732 KB)
MSG SENT: 002 com open wb wazuh_agent_v3.7.0_linux_x86_64.wpk
RESPONSE: ok
MSG SENT: 002 com lock_restart -1
RESPONSE: ok
Chunk size: 512 bytes
Sending: /var/ossec/var/upgrade/wazuh_agent_v3.7.0_linux_x86_64.wpk
Error 1715: Error sending WPK file: Maximum attempts exceeded
Traceback (most recent call last):
  File "/var/ossec/bin/agent_upgrade", line 165, in <module>
    main()
  File "/var/ossec/bin/agent_upgrade", line 119, in main
    rl_timeout=-1 if args.timeout == None else args.timeout, use_http=use_http)
  File "/var/ossec/bin/../framework/wazuh/agent.py", line 2200, in upgrade
    show_progress=show_progress, chunk_size=chunk_size, rl_timeout=rl_timeout, use_http=use_http)
  File "/var/ossec/bin/../framework/wazuh/agent.py", line 2131, in _send_wpk_file
    raise WazuhException(1715, data.replace("err ",""))
wazuh.exception.WazuhException: Error 1715 - Error sending WPK file: Maximum attempts exceeded
```

Errors on the agent side:
```
2018/10/04 09:04:33 ossec-agentd: WARNING: Unknown message received. No action defined.
2018/10/04 09:04:34 ossec-agentd: WARNING: Unknown message received. No action defined.
2018/10/04 09:04:35 ossec-agentd: WARNING: Unknown message received. No action defined.
2018/10/04 09:04:36 ossec-agentd: WARNING: Unknown message received. No action defined.
2018/10/04 09:04:37 ossec-agentd: WARNING: Unknown message received. No action defined.
2018/10/04 09:04:38 ossec-agentd: WARNING: Unknown message received. No action defined.
2018/10/04 09:04:39 ossec-agentd: WARNING: Unknown message received. No action defined.
2018/10/04 09:04:40 ossec-agentd: WARNING: Unknown message received. No action defined.
2018/10/04 09:04:41 ossec-agentd: WARNING: Unknown message received. No action defined.
2018/10/04 09:04:45 ossec-agentd: ERROR: Couldn't send response to manager: number of attempts exceeded.
2018/10/04 09:11:04 ossec-execd: ERROR: File '/var/ossec//var/incoming/wazuh_agent_v3.7.0_linux_x86_64.wpk' was opened. Closing.
```

**Comment by chemamartinez** [comment]
Outdated
