### ISSUE TITLE
Investigate cluster nodes not accepting connections despite being running

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#15846]
|Wazuh version|Component|
|---|---|
| 4.3.X | Wazuh cluster |

### Cluster
We have been reported that sometimes, cluster environments are not working as expected. According to reports, it seems that after upgrading (from v4.2.7 to v4.3.8 and from v4.3.8 to v4.3.10), the master node process seems to be running but binaries show otherwise:
```
[root@wazuh-manager-worker-0 /]# /var/ossec/bin/cluster_control -l
ERROR: Error 3012 - Cluster is not running
[root@wazuh-manager-worker-0 /]# service wazuh-manager status
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord is running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
```

If we look at the logs that have been provided, we see that the worker node has problems connecting to the master:
```
2022/11/16 10:06:11 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2022/11/16 10:06:11 ERROR: [Worker wazuh-manager-worker-0] [Main] Connection closed due to an unhandled error: [Errno 104] Connection reset by peer
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)

2022/11/16 10:06:21 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2022/11/16 10:06:21 ERROR: [Worker wazuh-manager-worker-0] [Main] Connection closed due to an unhandled error: [Errno 104] Connection reset by peer
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)

2022/11/16 10:06:32 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2022/11/16 10:06:32 ERROR: [Worker wazuh-manager-worker-0] [Main] Connection closed due to an unhandled error: [Errno 104] Connection reset by peer
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
```

Meanwhile, the master, despite being effectively running, does not even show any connection attempts in its logs:
```
2022/11/16 10:13:24 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:13:24 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:13:32 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:13:32 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:13:40 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:13:40 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:13:48 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:13:48 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:13:56 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:13:56 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:14:04 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:14:04 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:14:12 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:14:12 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:14:20 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:14:20 INFO: [Master] [Local integrity] Finished in 0.006s. Calculated metadata of 74 files.
2022/11/16 10:14:28 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:14:28 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:14:36 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:14:36 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:14:44 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:14:44 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:14:52 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:14:52 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:15:00 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:15:00 INFO: [Master] [Local integrity] Finished in 0.006s. Calculated metadata of 74 files.
2022/11/16 10:15:08 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:15:08 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:15:16 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:15:16 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:15:24 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:15:24 INFO: [Master] [Local integrity] Finished in 0.003s. Calculated metadata of 74 files.
2022/11/16 10:15:32 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:15:32 INFO: [Master] [Local integrity] Finished in 0.008s. Calculated metadata of 74 files.
2022/11/16 10:15:40 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:15:40 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:15:48 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:15:48 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:15:56 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:15:56 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:16:04 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:16:04 INFO: [Master] [Local integrity] Finished in 0.003s. Calculated metadata of 74 files.
2022/11/16 10:16:12 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:16:12 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:16:20 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:16:20 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:16:28 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:16:28 INFO: [Master] [Local integrity] Finished in 0.007s. Calculated metadata of 74 files.
2022/11/16 10:16:36 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:16:36 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:16:44 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:16:44 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:16:52 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:16:52 INFO: [Master] [Local integrity] Finished in 0.008s. Calculated metadata of 74 files.
2022/11/16 10:17:00 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:17:00 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:17:08 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:17:08 INFO: [Master] [Local integrity] Finished in 0.005s. Calculated metadata of 74 files.
2022/11/16 10:17:16 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:17:16 INFO: [Master] [Local integrity] Finished in 0.011s. Calculated metadata of 74 files.
2022/11/16 10:17:24 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:17:24 INFO: [Master] [Local integrity] Finished in 0.003s. Calculated metadata of 74 files.
2022/11/16 10:17:32 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:17:32 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:17:40 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:17:40 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
2022/11/16 10:17:48 INFO: [Master] [Local integrity] Starting.
2022/11/16 10:17:48 INFO: [Master] [Local integrity] Finished in 0.004s. Calculated metadata of 74 files.
```

Usually the solution has been to kill any remaining clusterd processes on the master node and start the cluster again. The question, therefore, is how the cluster ends up in this situation and how does it run without listening to any connection request. 

### Additional information
Similar situations have also been found after the upgrade but in the API, although the problem is likely to be completely different:
```
2022/11/16 11:11:45 ERROR: Error handling request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/connexion/apis/aiohttp_api.py", line 50, in problems_middleware
    response = yield from handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 108, in impl
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/middlewares.py", line 141, in response_postprocessing
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/middlewares.py", line 33, in set_user_name
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/middlewares.py", line 118, in security_middleware
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/middlewares.py", line 90, in request_logging
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/middlewares.py", line 38, in set_secure_headers
    resp = await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/aiohttp_cache/middleware.py", line 59, in cache_middleware
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/connexion/decorators/coroutine_wrappers.py", line 23, in wrapper
    connexion_response = yield from connexion_response
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/controllers/security_controller.py", line 58, in login_user
    token = generate_token(user_id=user, data=data.dikt)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/authentication.py", line 174, in generate_token
    return jwt.encode(payload, generate_keypair()[0], algorithm=JWT_ALGORITHM)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/authentication.py", line 93, in generate_keypair
    private_key, public_key = change_keypair()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.3.8-py3.9.egg/api/authentication.py", line 114, in change_keypair
    key_obj = ec.generate_private_key(ec.SECP521R1())
  File "/var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 325, in generate_private_key
    return ossl.generate_elliptic_curve_private_key(curve)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/backends/__init__.py", line 24, in _get_backend
  File "/var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
  File "/var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 18, in <module>
    from cryptography.hazmat.backends.openssl.dh import (
  File "/var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/dh.py", line 9, in <module>
    from cryptography.hazmat.primitives.asymmetric import dh
  File "/var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dh.py", line 9, in <module>
    from cryptography.hazmat.primitives import _serialization
  File "/var/ossec/framework/python/lib/python3.9/site-packages/cryptography/hazmat/primitives/_serialization.py", line 15, in <module>
    class PBES(utils.Enum):
AttributeError: module 'cryptography.utils' has no attribute 'Enum'
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
## Status update

I have tried to reproduce the problem described in this issue but without success. To do this, starting from a cluster environment with these characteristics:
- 1x Master node v4.2.7 (Ubuntu 20.04)
- 1x Worker node v4.2.7 (Ubuntu 20.04)

I have upgraded both nodes to v4.3.10 using the following command:
```
# apt-get install wazuh-manager
```

I repeated the process several times, but each time the worker reconnected to the master correctly without any intervention on my part. The problem reported in this issue occurred both times in the same environment, so I have asked for information on the procedure that was followed to update that specific environment. One of those steps is likely the trigger for this cluster problem.

**Comment by Selutario** [comment]
It seems that this has not happened again. If it did, we will reopen the issue.

**Comment by VigneshSahoo** [comment]
Hi @Selutario ,
This issue can be reproduced on Ubuntu 22.04.3 LTS and Ubuntu 20.04.6 LTS.
I have installed Wazuh using the command mentioned in the quickstart guide (curl -sO https://packages.wazuh.com/4.7/wazuh-install.sh && sudo bash ./wazuh-install.sh -a).

Below-mentioned services are not running!
wazuh-clusterd not running...
wazuh-maild not running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...

Manager is correctly installed, agent is also correctly installed and checked the logs and found no errors.
While one of my Linux clients is not reporting any events to the manager. That's when I checked this and found no solutions in the internet. 

Can you please take a look and get it fixed if needed?

**Comment by Selutario** [comment]
Hello @VigneshSahoo,

The services you mention are disabled by default, unless expressly enabled in the `ossec.conf`. Since your cluster is not enabled, it doesn't seem like your problem has anything to do with this issue. I recommend that you ask for help on any of the official Wazuh community channels:
- [Wazuh community](https://wazuh.com/community/)
