### ISSUE TITLE
`aws_account_alias` option missing in AWS services integration

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#15840]
|Component|
|---|
| Wazuh module for AWS (aws-s3) |

## Description
According to the Wazuh reference documentation for the AWS wodle, the integration supports the `aws_account_alias` configuration option for both, buckets and services:
- [bucket\aws_account_alias](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#bucket-aws-account-alias)
- [service\aws_account_alias](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#service-aws-account-alias)

However, looking at the code we can see that alias is only used in the buckets' integrations:
https://github.com/wazuh/wazuh/blob/0824af89e8a448866197751e867c8b3ad980dd0b/wodles/aws/aws_s3.py#L3621-L3628

But not in the services' integrations:
https://github.com/wazuh/wazuh/blob/0824af89e8a448866197751e867c8b3ad980dd0b/wodles/aws/aws_s3.py#L3666-L3680

## To do
The necessary changes should be applied so that `aws_account_alias` can be used in services in the same way that it can be used in bucket integrations.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests.
- [x] Changelog.
- [x] Documentation.

**Comment by javiersanchz** [comment]
## Update

I've been investigating how the `aws_account_alias` parameter is implemented in `aws_bucket`, and I started by adding the changes in `aws_service` to also include the parameter : 

https://github.com/wazuh/wazuh/blob/b208e34b4a6666a3534e696f1f4d18c7650498ee/wodles/aws/buckets_s3/aws_bucket.py#L89-L90

The code still needs additional parts to be added, testing its functionality on AWS, and modifying or adding tests within `test_aws_service` for verification

**Comment by javiersanchz** [comment]
## Update 

I was finishing implementing the `aws_account_alias` parameter for aws_service, which seems to accept the parameter well as shown in the following entry:


```console
2024/02/07 12:32:20 wazuh-modulesd:aws-s3[19441] wm_aws.c:701 at wm_aws_run_service(): DEBUG: Service: cloudwatchlogs(test-feature-15840)  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
```

But finally, the **error type (TypeError)** is displayed, specifying that a required positional argument `account_alias` is missing in the initialization of the `AWSService` class in `cloudwatchlogs.py`. It seems that even though it is implemented within the init of `cloudwatchlogs`, it does not receive this parameter correctly.

```console
2024/02/07 12:32:20 wazuh-modulesd:aws-s3[19441] wm_aws.c:701 at wm_aws_run_service(): DEBUG: Service: cloudwatchlogs(test-feature-15840)  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: +++ Error: AWSService.__init__() missing 1 required positional argument: 'account_alias'
Unknown error: AWSService.__init__() missing 1 required positional argument: 'account_alias'
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 194, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 127, in main
    service = service_type(reparse=options.reparse,
  File "/var/ossec/wodles/aws/services/cloudwatchlogs.py", line 137, in __init__
    aws_service.AWSService.__init__(self, db_table_name='cloudwatch_logs', service_name='cloudwatchlogs',
TypeError: AWSService.__init__() missing 1 required positional argument: 'account_alias'
```

**Comment by javiersanchz** [comment]
## Update 

After making changes to the AWS `unit tests`, all of them passed successfully. However, some additional changes had to be made in the code, which need to be tested before opening a PR 

```console
(unittest-env) wazuh@javier:~/Git/wazuh$ PYTHONPATH=/home/wazuh/Git/wazuh/api:/home/wazuh/Git/wazuh/framework python3 -m pytest wodles/aws/tests
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-0.13.1
rootdir: /home/wazuh/Git/wazuh/wodles/aws/tests
configfile: pytest.ini
plugins: metadata-3.0.0, aiohttp-1.0.4, html-2.1.1, trio-0.7.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 639 items                                                                                                                                                                                               

wodles/aws/tests/test_aws_bucket.py ....................................................................................................................................................................... [ 26%]
..........................................                                                                                                                                                                  [ 32%]
wodles/aws/tests/test_aws_s3.py ..................                                                                                                                                                          [ 35%]
wodles/aws/tests/test_aws_service.py ....                                                                                                                                                                   [ 36%]
wodles/aws/tests/test_cloudtrail.py ..                                                                                                                                                                      [ 36%]
wodles/aws/tests/test_cloudwatchlogs.py .....................................................                                                                                                               [ 44%]
wodles/aws/tests/test_config.py ..............................................................................                                                                                              [ 56%]
wodles/aws/tests/test_guardduty.py .................                                                                                                                                                        [ 59%]
wodles/aws/tests/test_inspector.py ......                                                                                                                                                                   [ 60%]
wodles/aws/tests/test_load_balancers.py ............                                                                                                                                                        [ 62%]
wodles/aws/tests/test_s3_log_handler.py ................                                                                                                                                                    [ 64%]
wodles/aws/tests/test_server_access.py .................................                                                                                                                                    [ 70%]
wodles/aws/tests/test_sqs_message_processor.py ........                                                                                                                                                     [ 71%]
wodles/aws/tests/test_sqs_queue.py .......                                                                                                                                                                  [ 72%]
wodles/aws/tests/test_tools.py ..................................                                                                                                                                           [ 77%]
wodles/aws/tests/test_umbrella.py ......                                                                                                                                                                    [ 78%]
wodles/aws/tests/test_vpcflow.py ...........................                                                                                                                                                [ 82%]
wodles/aws/tests/test_waf.py .......                                                                                                                                                                        [ 84%]
wodles/aws/tests/test_wazuh_integration.py ......................................................................................................                                                           [100%]

=============================================================================================== 639 passed in 2.63s ===============================================================================================

```

**Comment by javiersanchz** [comment]
## Update 

- I have been making changes and modifying parts of the code to display the `alias` parameter in the code.

- I have been conducting tests and checking how the code filters and displays the `aws_buckets` parameter.

- There is still a test of cloudwatchlogs pending modification.

Tests:

**ossec.conf:**

```console
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <remove_from_bucket>no</remove_from_bucket>
    <interval>1m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>

    <bucket type="cloudtrail">
        <name>wazuh-aws-wodle-cloudtrail</name>
        <aws_profile>default</aws_profile>
        <only_logs_after>2022-JAN-01</only_logs_after>
        <aws_account_alias>test-feature-cloudtrail</aws_account_alias>
    </bucket>

    <service type="cloudwatchlogs">
        <aws_profile>default</aws_profile>
        <aws_log_groups>4_6_test</aws_log_groups>
        <only_logs_after>2023-JAN-01</only_logs_after>
        <aws_account_alias>test-feature-15840</aws_account_alias>
        <regions>us-east-1</regions>
    </service>
  </wodle>
```


**ossec.conf :** 

```console
DEBUG: Agent 000 query: syscollector_processes save2 {"attributes":{"argvs":"wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile default --aws_account_alias test-feature-15840 --regions us-east-1 --aws_log_groups wazuh-cloudwatchlogs-integration-tests --debug 2","checksum":"xxxxxxxxxx","cmd":"/bin/sh","egroup":".......................
DEBUG: Sync sent: {"component":"syscollector_processes","data":{"attributes":{"argvs":"wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile default --aws_account_alias test-feature-15840 --regions us-east-1 --aws_log_groups wazuh-cloudwatchlogs-integration-tests --debug 2","checksum":"xxxxxxxxxxxxxxx","cmd":"/bin/sh...............

DEBUG: Service: cloudwatchlogs(test-feature-15840)  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
INFO: Executing Service Analysis: (Service: cloudwatchlogs, Account Alias: test-feature-15840, Profile: default)
DEBUG: Launching S3 Command: wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile default --aws_account_alias test-feature-15840 --regions us-east-1 --aws_log_groups wazuh-cloudwatchlogs-integration-tests --debug 2
2024/02/16 16:44:33 wazuh-modulesd:aws-s3[39478] wm_aws.c:171 at wm_aws_main(): INFO: Executing Service Analysis: (Service: cloudwatchlogs, Account Alias: test-feature-15840, Profile: default)
2024/02/16 16:44:33 wazuh-modulesd:aws-s3[39478] wm_aws.c:558 at wm_aws_run_service(): DEBUG: Create argument list
2024/02/16 16:44:33 wazuh-modulesd:aws-s3[39478] wm_aws.c:662 at wm_aws_run_service(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile default --aws_account_alias test-feature-15840 --regions us-east-1 --aws_log_groups wazuh-cloudwatchlogs-integration-tests --debug 2
2024/02/16 16:44:36 wazuh-modulesd:aws-s3[39478] wm_aws.c:703 at wm_aws_run_service(): DEBUG: Service: cloudwatchlogs(test-feature-15840)  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: only logs: None
DEBUG: Getting log streams for "wazuh-cloudwatchlogs-integration-tests" log group
DEBUG: Found "wazuh-cloudwatchlogs-integration-tests" log stream in wazuh-cloudwatchlogs-integration-tests
DEBUG: Getting data from DB for log stream "wazuh-cloudwatchlogs-integration-tests" in log group "wazuh-cloudwatchlogs-integration-tests"
DEBUG: Token: "f/xxxxxxxxxxxxxxxxx/s", start_time: "1708041600000", end_time: "1708041600039"
DEBUG: Getting CloudWatch logs from log stream "wazuh-cloudwatchlogs-integration-tests" in log group "wazuh-cloudwatchlogs-integration-tests" using token "f/xxxxxxxxxxxxxxxxx/s", start_time "1708041600040" and end_time "None"
DEBUG: +++ There are no new events in the "wazuh-cloudwatchlogs-integration-tests" group
DEBUG: Saving data for log group "wazuh-cloudwatchlogs-integration-tests" and log stream "wazuh-cloudwatchlogs-integration-tests".
DEBUG: The saved values are "{'token': 'f/xxxxxxxxxxxxxxxxxxxxxx/s', 'start_time': 1708041600000, 'end_time': 1708041600040}"
DEBUG: Some data already exists on DB for that key. Updating their values...
DEBUG: Purging the BD
DEBUG: Getting log streams for "wazuh-cloudwatchlogs-integration-tests" log group
DEBUG: Found "wazuh-cloudwatchlogs-integration-tests" log stream in wazuh-cloudwatchlogs-integration-tests
DEBUG: committing changes and closing the DB
```

**archive.json**

```console
{"timestamp":"2024-02-16T17:04:37.692+0000","agent":{"id":"000","name":"wazuh-master"},"manager":{"name":"wazuh-master"},"id":"1708103077.865921","cluster":{"name":"wazuh","node":"master-node"},"full_log":"{\"data\":{\"argvs\":\"wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile default --aws_account_alias test-feature-15840 --regions us-east-1 --aws_log_groups wazuh-cloudwatchlogs-integration-tests --debug 2\",\"checksum\":\"xxxxxxxxxx\",\"cmd\":\"/bin/sh\",\"egroup\":\"root\",\"euser\":\"root\",\"fgroup\":\"root\",\"name\":\"aws-.....................................},"location":"syscollector"}
```

**Comment by javiersanchz** [comment]
## Update


Working with the unit tests of `CloudWatchLogs`, I realized that the output I was expecting in the `test_aws_cloudwatchlogs_get_alerts_within_range` test code was completely different from what I was receiving. Therefore, the changes I had made in the code were not valid, even though they were displaying correctly in the services log output. When running the tests, I noticed:

```console
Expected Events: [{'timestamp': 1640996200000, 'message': 'someMsg', 'ingestionTime': 123}]
Received Events: [call({'integration': 'aws', 'aws': {'log_info': {'aws_account_alias': None}}}, dump_json=False)]
```

I was looking into how buckets work with this parameter and modifying CloudWatchLogs accordingly
