### ISSUE TITLE
Unable to compile agent on Arch Linux

### ISSUE THREAD

**Issue by AliceGrey** [wazuh/wazuh#15960]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10| dbsync | Agent | Sources | Linux 6.1.6-arch1-1 |

Steps to reproduce:
1. pacman --noconfirm -Syu curl gcc make sudo wget expect gnupg perl-base perl fakeroot python brotli automake autoconf libtool gawk libsigsegv nodejs base-devel inetutils cmake
2. curl -Ls https://github.com/wazuh/wazuh/archive/v4.3.10.tar.gz | tar zx
3. cd wazuh-4.3.10 && sudo ./install.sh
```
grep: /etc/redhat-release: No such file or directory
make build_sysinfo build_shared_modules build_syscollector
make[1]: Entering directory '/home/allie/Downloads/wazuh-4.3.10/src'
grep: /etc/redhat-release: No such file or directory
cd data_provider/ && mkdir -p build && cd build && cmake     .. && make
cd shared_modules/dbsync/ && mkdir -p build && cd build && cmake    .. && make
Traceback (most recent call last):
  File "/home/allie/.local/bin/cmake", line 5, in <module>
    from cmake import cmake
ModuleNotFoundError: No module named 'cmake'
Traceback (most recent call last):
  File "/home/allie/.local/bin/cmake", line 5, in <module>
    from cmake import cmake
ModuleNotFoundError: No module named 'cmake'
make[1]: *** [Makefile:1479: build_shared_modules] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1489: build_sysinfo] Error 1
make[1]: Leaving directory '/home/allie/Downloads/wazuh-4.3.10/src'
make: *** [Makefile:724: agent] Error 2
```
Cmake is installed and working
```
└[~/Downloads/wazuh-4.3.10]> cmake --version
cmake version 3.24.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
```
└[~/Downloads/wazuh-4.3.10]> python3
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cmake import cmake
>>> cmake
<function cmake at 0x7ff8965e53f0>
>>> 
```

**Comment by Dwordcito** [comment]
Hi, Could you share more details about your environment? With the following Dockerfile, the agent builds successfully in arch linux.

![image](https://user-images.githubusercontent.com/14300208/213972375-46a7bcb8-a4ec-48df-88fb-d830083c5719.png)

It seems strange to me that the cmake call is made against a python script, when it should be against the cmake binary. please print your PATH intern variable.
```

# Use arch linux as base image
FROM archlinux

# Install dependencies
RUN pacman -Syu --noconfirm curl gcc make sudo wget expect gnupg perl-base perl fakeroot python brotli automake autoconf libtool gawk libsigsegv nodejs base-devel inetutils cmake git

# Download Wazuh agent 4.3.10
RUN curl -Ls https://github.com/wazuh/wazuh/archive/v4.3.10.tar.gz | tar zx
```

**Comment by JoaquinGiaccio** [comment]
Hi, I had the same problem, I was able to work around it just deleting and installing the cmake python lib.

`pip uninstall cmake --break-system-packages`
`pip install cmake --break-system-packages`

**Comment by Callan-Breare** [comment]
I get a similar but for anything newer than 4.7.4 
![Screenshot](https://github.com/wazuh/wazuh/assets/147275646/ff2a16d7-9596-4df4-a5f2-7629233d43c6)

**Comment by Dwordcito** [comment]
@GabrielEValenzuela could you help here?, consider this(https://github.com/wazuh/wazuh/issues/15960#issuecomment-2150934832) as community

**Comment by Callan-Breare** [comment]
@Dwordcito just to add to this. If I it clone https://github.com/wazuh/wazuh.git, then cd into wazuh/src, then make deps, then make TARGET=agent it installs fine, however there is no version set so it never connects to the manager. If I do "git checkout [any version]" then cd to src and do the rest, it fails at the same point.

**Comment by GabrielEValenzuela** [comment]
Hi @Callan-Breare ! How are you?

This is solved easily fortunately, the new GCC version (14) has become more strict by default and treats any warning as an error, to solve this, we need to pass an extra flag.

Please, add the flag `-fpermissive` in the' Makefile' in this line. This should fix your issue.


https://github.com/wazuh/wazuh/blob/a5f51ad61af5abcf49186cd72d4d73c0c3927021/src/Makefile#L408

Nice weekend!

**Comment by Callan-Breare** [comment]
@GabrielEValenzuela thanks very much that worked. Have a nice weekend too!

**Comment by maxigor** [comment]
@GabrielEValenzuela thank u!!!
