### ISSUE TITLE
Fix test_agent_PUT_endpoints.tavern.yaml to avoid test race condition errors.

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#16347]
|Wazuh version|Component|
|---|---|
| 4.5 | API |

## Description

After launching the integration tests to try a change made in the API, it was found there is a race condition error in the **test_agent_PUT_endpoints.tavern.yaml** specifically between these two stages:

- Stage 1:

```
  - name: Try to customly upgrade an agent using default installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '008'
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '008'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr
```
- Stage 2:

```
  - name: Try to customly upgrade an agent selecting installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '008'
        installer: upgrade.sh
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '008'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr
```

Error message: 

```
{
   "code":1820,
   "message": "Upgrade procedure could not start. Agent already upgrading"
}
```

This error is caused because these stages are run consecutively and both try to upgrade the same agent.

One of the stages has to be reviewed and modified to avoid errors and return the expected response.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by EduLeon12** [comment]
## Issue Update

After changing the selected agent on the parameter list of the mentioned stages the integration test passed.

- test_agent_PUT_endpoints.tavern.yaml:

```
  - name: Try to customly upgrade an agent using default installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '005'
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '005'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr

  - name: Try to customly upgrade an agent selecting installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '008'
        installer: upgrade.sh
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '008'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr
``` 

- Test results:

```
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-5.4.3, py-1.11.0, pluggy-0.13.1 -- /home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.9', 'Platform': 'Linux-6.1.11-76060111-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '5.4.3', 'pluggy': '0.13.1'}, 'Plugins': {'tavern': '1.0.0', 'html': '2.1.1', 'metadata': '2.0.4'}}
rootdir: /home/eduardoleon/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: tavern-1.0.0, html-2.1.1, metadata-2.0.4
collecting ... collected 10 items

test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group/{group_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/reconnect PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/upgrade PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom PASSED
```

But also it was noted that this only works if the agent number on the agent list of the first stage **Try to customly upgrade an agent using default installer (WPK does not exist)** is lower than the agent number on the agent list of the second stage ****

Examples using different test_agent_PUT_endpoitns.tavern.yaml:

### Case 1
- stage 1 param: agents_list: '008'
- stage 2 param: agents_list: '004' 

---
  - name: Try to customly upgrade an agent using default installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '008'
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '008'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr

  - name: Try to customly upgrade an agent selecting installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '001'
        installer: upgrade.sh
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '001'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr
---

Test log:

```
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-5.4.3, py-1.11.0, pluggy-0.13.1 -- /home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.9', 'Platform': 'Linux-6.1.11-76060111-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '5.4.3', 'pluggy': '0.13.1'}, 'Plugins': {'tavern': '1.0.0', 'html': '2.1.1', 'metadata': '2.0.4'}}
rootdir: /home/eduardoleon/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: tavern-1.0.0, html-2.1.1, metadata-2.0.4
collecting ... collected 10 items

test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group/{group_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/reconnect PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/upgrade PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom FAILED

=================================== FAILURES ===================================
_ /home/eduardoleon/git/wazuh/api/test/integration/test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MzA5ODU4LCJleHAiOjE2NzgzMTA3NTgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AOLhwSdk6iVBXRqvrWgSF8DtpKUhLnjUP-dSsz5y4KQZggktn1N9f1hS6xCqh1zOYJPkpMk53B-HyzLB-0HxePS9AYRic5iOX4sJfE6221_J_q5mfL4Ws20lFO9nDXXtYFcjZNkAO6bw01lROxCeswLaPZR-KzlkMC6C2D-Sy2exPDUV'
  custom_wpk_path:s = '/var/ossec/test.wpk'

Source test stage (line 1237):
  - name: Try to customly upgrade an agent selecting installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '004'
        installer: upgrade.sh
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '004'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr


Formatted stage:
  name: Try to customly upgrade an agent selecting installer (WPK does not exist)
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MzA5ODU4LCJleHAiOjE2NzgzMTA3NTgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AOLhwSdk6iVBXRqvrWgSF8DtpKUhLnjUP-dSsz5y4KQZggktn1N9f1hS6xCqh1zOYJPkpMk53B-HyzLB-0HxePS9AYRic5iOX4sJfE6221_J_q5mfL4Ws20lFO9nDXXtYFcjZNkAO6bw01lROxCeswLaPZR-KzlkMC6C2D-Sy2exPDUV
    method: PUT
    params:
      agents_list: '004'
      file_path: '/var/ossec/test.wpk'
      installer: upgrade.sh
    url: 'https://localhost:55000/agents/upgrade_custom'
    verify: false
  response:
    json:
      data:
        affected_items:
        - agent: '004'
          task_id: !anyint ''
        failed_items: []
        total_affected_items: 1
        total_failed_items: 0
      message: !anystr ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Try to customly upgrade an agent selecting installer (WPK does not exist)' failed:
    - Key mismatch: (expected["data"]["total_affected_items"] = '1' (type = <class 'int'>), actual["data"]["total_affected_items"] = '0' (type = <class 'int'>))
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '400'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:41 Key mismatch: (expected["data"]["total_affected_items"] = '1' (type = <class 'int'>), actual["data"]["total_affected_items"] = '0' (type = <class 'int'>))
Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'affected_items': [],\n          'failed_items': [{'error': {'code': 1822,\n                                      'message': 'Current agent version is '\n                                                 'greater or equal'},\n                            'id': ['004']}],\n          'total_affected_items': 0,\n          'total_failed_items': 1},\n 'error': 1,\n 'message': 'No upgrade task was created'} == {'data': {'affected_items': [{'agent': '004',\n                              'task_id': <tavern.util.loader.IntSentinel object at 0x7f5973c89f70>}],\n          'failed_items': [],\n          'total_affected_items': 1,\n          'total_failed_items': 0},\n 'message': <tavern.util.loader.StrSentinel object at 0x7f5973c89eb0>}
  Differing items:
  {'data': {'affected_items': [], 'failed_items': [{'error': {'code': 1822, 'message': 'Current agent version is greater or equal'}, 'id': ['004']}], 'total_affected_items': 0, 'total_failed_items': 1}} != {'data': {'affected_items': [{'agent': '004', 'task_id': <tavern.util.loader.IntSentinel object at 0x7f5973c89f70>}], 'failed_items': [], 'total_affected_items': 1, 'total_failed_items': 0}}
  {'message': 'No upgrade task was created'} != {'message': <tavern.util.loader.StrSentinel object at 0x7f5973c89eb0>}
  Left contains 1 more item:
  {'error': 1}
  Full diff:
    {
  -  'data': {'affected_items': [{'agent': '004',
  ?                              ^^^^^^^^^^^^^^^
  +  'data': {'affected_items': [],
  ?                              ^
  -                               'task_id': <tavern.util.loader.IntSentinel object at 0x7f5973c89f70>}],
  -           'failed_items': [],
  +           'failed_items': [{'error': {'code': 1822,
  +                                       'message': 'Current agent version is '
  +                                                  'greater or equal'},
  +                             'id': ['004']}],
  -           'total_affected_items': 1,
  ?                                   ^
  +           'total_affected_items': 0,
  ?                                   ^
  -           'total_failed_items': 0},
  ?                                 ^
  +           'total_failed_items': 1},
  ?                                 ^
  -  'message': <tavern.util.loader.StrSentinel object at 0x7f5973c89eb0>,
  +  'error': 1,
  +  'message': 'No upgrade task was created',
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_items': [],\n 'failed_items': [{'error': {'code': 1822,\n                             'message': 'Current agent version is greater or '\n                                        'equal'},\n                   'id': ['004']}],\n 'total_affected_items': 0,\n 'total_failed_items': 1} == {'affected_items': [{'agent': '004',\n                     'task_id': <tavern.util.loader.IntSentinel object at 0x7f5973c89f70>}],\n 'failed_items': [],\n 'total_affected_items': 1,\n 'total_failed_items': 0}
  Differing items:
  {'affected_items': []} != {'affected_items': [{'agent': '004', 'task_id': <tavern.util.loader.IntSentinel object at 0x7f5973c89f70>}]}
  {'total_failed_items': 1} != {'total_failed_items': 0}
  {'failed_items': [{'error': {'code': 1822, 'message': 'Current agent version is greater or equal'}, 'id': ['004']}]} != {'failed_items': []}
  {'total_affected_items': 0} != {'total_affected_items': 1}
  Full diff:
    {
  -  'affected_items': [{'agent': '004',
  -                      'task_id': <tavern.util.loader.IntSentinel object at 0x7f5973c89f70>}],
  -  'failed_items': [],
  ?    ^^^
  +  'affected_items': [],
  ?   + ^^^^
  +  'failed_items': [{'error': {'code': 1822,
  +                              'message': 'Current agent version is greater or '
  +                                         'equal'},
  +                    'id': ['004']}],
  -  'total_affected_items': 1,
  ?                          ^
  +  'total_affected_items': 0,
  ?                          ^
  -  'total_failed_items': 0,
  ?                        ^
  +  'total_failed_items': 1,
  ?                        ^
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert 0 == 1
  +0
  -1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 546, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(
tavern.util.exceptions.KeyMismatchError: Key mismatch: (expected["data"]["total_affected_items"] = '1' (type = <class 'int'>), actual["data"]["total_affected_items"] = '0' (type = <class 'int'>))

```

### Case 2

- stage 1 param: agents_list: '008'
- stage 2 param: agents_list: '001' 

---
  - name: Try to customly upgrade an agent using default installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '008'
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '008'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr

  - name: Try to customly upgrade an agent selecting installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '001'
        installer: upgrade.sh
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '001'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr
---

Test log: 
```
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-5.4.3, py-1.11.0, pluggy-0.13.1 -- /home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.9', 'Platform': 'Linux-6.1.11-76060111-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '5.4.3', 'pluggy': '0.13.1'}, 'Plugins': {'tavern': '1.0.0', 'html': '2.1.1', 'metadata': '2.0.4'}}
rootdir: /home/eduardoleon/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: tavern-1.0.0, html-2.1.1, metadata-2.0.4
collecting ... collected 10 items

test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group/{group_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/reconnect PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/upgrade PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom FAILED

=================================== FAILURES ===================================
_ /home/eduardoleon/git/wazuh/api/test/integration/test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MzEwNTkxLCJleHAiOjE2NzgzMTE0OTEsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AZWJgYX2kXR8E9UpkrVI6rKSvcLEW-bxjy2Kt5aIstDzqAaj8_z45MP2hgMokvqI-wOpOagDAnkNsN4kE6X0UG_rAMWYX3EucNJJ0vtpDSq7DFC6JvqZRpvrv4P4UHlmS76fTekQp_3xh9iM0FTNhac_HOdYZvD1mML03OO6l1MSPHkI'
  custom_wpk_path:s = '/var/ossec/test.wpk'

Source test stage (line 1237):
  - name: Try to customly upgrade an agent selecting installer (WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade_custom"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '001'
        installer: upgrade.sh
        file_path: "{custom_wpk_path:s}"
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '001'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr


Formatted stage:
  name: Try to customly upgrade an agent selecting installer (WPK does not exist)
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjc4MzEwNTkxLCJleHAiOjE2NzgzMTE0OTEsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AZWJgYX2kXR8E9UpkrVI6rKSvcLEW-bxjy2Kt5aIstDzqAaj8_z45MP2hgMokvqI-wOpOagDAnkNsN4kE6X0UG_rAMWYX3EucNJJ0vtpDSq7DFC6JvqZRpvrv4P4UHlmS76fTekQp_3xh9iM0FTNhac_HOdYZvD1mML03OO6l1MSPHkI
    method: PUT
    params:
      agents_list: '001'
      file_path: '/var/ossec/test.wpk'
      installer: upgrade.sh
    url: 'https://localhost:55000/agents/upgrade_custom'
    verify: false
  response:
    json:
      data:
        affected_items:
        - agent: '001'
          task_id: !anyint ''
        failed_items: []
        total_affected_items: 1
        total_failed_items: 0
      message: !anystr ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Try to customly upgrade an agent selecting installer (WPK does not exist)' failed:
    - Key mismatch: (expected["data"]["total_failed_items"] = '0' (type = <class 'int'>), actual["data"]["total_failed_items"] = '1' (type = <class 'int'>))
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '400'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:41 Key mismatch: (expected["data"]["total_failed_items"] = '0' (type = <class 'int'>), actual["data"]["total_failed_items"] = '1' (type = <class 'int'>))
Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'affected_items': [],\n          'failed_items': [{'error': {'code': 1822,\n                                      'message': 'Current agent version is '\n                                                 'greater or equal'},\n                            'id': ['001']}],\n          'total_affected_items': 0,\n          'total_failed_items': 1},\n 'error': 1,\n 'message': 'No upgrade task was created'} == {'data': {'affected_items': [{'agent': '001',\n                              'task_id': <tavern.util.loader.IntSentinel object at 0x7f1d2cec9f70>}],\n          'failed_items': [],\n          'total_affected_items': 1,\n          'total_failed_items': 0},\n 'message': <tavern.util.loader.StrSentinel object at 0x7f1d2cec9eb0>}
  Differing items:
  {'data': {'affected_items': [], 'failed_items': [{'error': {'code': 1822, 'message': 'Current agent version is greater or equal'}, 'id': ['001']}], 'total_affected_items': 0, 'total_failed_items': 1}} != {'data': {'affected_items': [{'agent': '001', 'task_id': <tavern.util.loader.IntSentinel object at 0x7f1d2cec9f70>}], 'failed_items': [], 'total_affected_items': 1, 'total_failed_items': 0}}
  {'message': 'No upgrade task was created'} != {'message': <tavern.util.loader.StrSentinel object at 0x7f1d2cec9eb0>}
  Left contains 1 more item:
  {'error': 1}
  Full diff:
    {
  -  'data': {'affected_items': [{'agent': '001',
  ?                              ^^^^^^^^^^^^^^^
  +  'data': {'affected_items': [],
  ?                              ^
  -                               'task_id': <tavern.util.loader.IntSentinel object at 0x7f1d2cec9f70>}],
  -           'failed_items': [],
  +           'failed_items': [{'error': {'code': 1822,
  +                                       'message': 'Current agent version is '
  +                                                  'greater or equal'},
  +                             'id': ['001']}],
  -           'total_affected_items': 1,
  ?                                   ^
  +           'total_affected_items': 0,
  ?                                   ^
  -           'total_failed_items': 0},
  ?                                 ^
  +           'total_failed_items': 1},
  ?                                 ^
  -  'message': <tavern.util.loader.StrSentinel object at 0x7f1d2cec9eb0>,
  +  'error': 1,
  +  'message': 'No upgrade task was created',
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_items': [],\n 'failed_items': [{'error': {'code': 1822,\n                             'message': 'Current agent version is greater or '\n                                        'equal'},\n                   'id': ['001']}],\n 'total_affected_items': 0,\n 'total_failed_items': 1} == {'affected_items': [{'agent': '001',\n                     'task_id': <tavern.util.loader.IntSentinel object at 0x7f1d2cec9f70>}],\n 'failed_items': [],\n 'total_affected_items': 1,\n 'total_failed_items': 0}
  Differing items:
  {'total_failed_items': 1} != {'total_failed_items': 0}
  {'affected_items': []} != {'affected_items': [{'agent': '001', 'task_id': <tavern.util.loader.IntSentinel object at 0x7f1d2cec9f70>}]}
  {'failed_items': [{'error': {'code': 1822, 'message': 'Current agent version is greater or equal'}, 'id': ['001']}]} != {'failed_items': []}
  {'total_affected_items': 0} != {'total_affected_items': 1}
  Full diff:
    {
  -  'affected_items': [{'agent': '001',
  -                      'task_id': <tavern.util.loader.IntSentinel object at 0x7f1d2cec9f70>}],
  -  'failed_items': [],
  ?    ^^^
  +  'affected_items': [],
  ?   + ^^^^
  +  'failed_items': [{'error': {'code': 1822,
  +                              'message': 'Current agent version is greater or '
  +                                         'equal'},
  +                    'id': ['001']}],
  -  'total_affected_items': 1,
  ?                          ^
  +  'total_affected_items': 0,
  ?                          ^
  -  'total_failed_items': 0,
  ?                        ^
  +  'total_failed_items': 1,
  ?                        ^
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert 1 == 0
  +1
  -0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/lib/python3.9/site-packages/tavern/util/dict_util.py", line 546, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(
tavern.util.exceptions.KeyMismatchError: Key mismatch: (expected["data"]["total_failed_items"] = '0' (type = <class 'int'>), actual["data"]["total_failed_items"] = '1' (type = <class 'int'>))

```

**Comment by EduLeon12** [comment]
## Issue Update 

The error above was caused not because of the order of the agents between the stages but because agents 1 - 4 as described in the _docker-compose.yaml_ have the same version as their manager and agents 5 - 8 have a legacy version to allow updates.

That's why when using agents 1 - 4 the message on the error is:

```
{
   "error":{
      "code":1822,
      "message": "Current agent version is greater or equal"
   }
}
```

After testing the stage **Try to customly upgrade an agent selecting installer (WPK does not exist)** with agent numbers from 5 - 8 it was found that all agents except agent number 5 were previouslyused on a upgrade test scenario that's why using them will cause the following error:
 
```
{
   "error":{
      "code":1820,
      "message":"Upgrade procedure could not start.Agent already upgrading"
   }
}
```

And finally when agent number 5 is used the test passed without any issues.

```
==================================================== test session starts =====================================================
platform linux -- Python 3.9.9, pytest-5.4.3, py-1.11.0, pluggy-0.13.1 -- /home/eduardoleon/.pyenv/versions/3.9.9/envs/inttegration-3.9-venv/bin/python3.9
cachedir: .pytest_cache
metadata: {'Python': '3.9.9', 'Platform': 'Linux-6.1.11-76060111-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '5.4.3', 'pluggy': '0.13.1'}, 'Plugins': {'tavern': '1.0.0', 'html': '2.1.1', 'metadata': '2.0.4'}}
rootdir: /home/eduardoleon/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: tavern-1.0.0, html-2.1.1, metadata-2.0.4
collected 10 items

test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group/{group_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/reconnect PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/upgrade PASSED
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom PASSED

```
