### ISSUE TITLE
Test: Distributed API

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#1645]
---
name: 'Test: API'
about: Test suite for the API.

---

# Ruleset test

| Version | Revision | Branch |
| --- | --- | --- |
| x.y.z | rev | branch |

## Installation

- [ ] Install API in a cluster of two nodes. One of the nodes must be a custom directory install.
- [ ] Check API status is running in both nodes.

## Configuration

- [ ] Custom user, password and https working.

### Certificates and HTTPS

- [ ] Install certificates.
- [ ] Run query using HTTPS.

### Test mocha

Required tests:

- Agents.
- Decoders.
- Manager.
- Rootcheck.
- Rules.
- Syscheck.
- Syscollector.

Checks:

- [ ] Master node:
    - [ ] Ubuntu 18 / Python 2.
    - [ ] Ubuntu 18 / Python 3.
    - [ ] CentOS 7 / Python 2.
    - [ ] CentOS 7 / Python 3.
    - [ ] CentOS 6 / Python27.

- [ ] Worker node:
    - [ ] Ubuntu 18 / Python 2.
    - [ ] Ubuntu 18 / Python 3.
    - [ ] CentOS 7 / Python 2.
    - [ ] CentOS 7 / Python 3.
    - [ ] CentOS 6 / Python27.

**Comment by mgmacias95** [comment]
Distributed API calls in worker nodes aren't correctly executed. This is the error shown when a worker receives a distributed API call and is going to send a response:
```
2018-10-16 11:11:26,318 DEBUG   : [Worker] [Request-R  ]: 'dapi'.
2018-10-16 11:11:26,318 DEBUG   : [DistributedAPI] Receiving request: None 3218133057 {"function": "/syscollector/:agent_id/os", "arguments": {"agent_id": "001"}, "ossec_path": "/var/ossec", "from_cluster": true}
2018-10-16 11:11:26,321 DEBUG   : [DistributedAPI] Distributed API is enabled.
2018-10-16 11:11:26,329 DEBUG   : [DistributedAPI] Time calculating request result: 0.007344722747802734s
2018-10-16 11:11:26,373 ERROR   : [Transport-ClientHandler] Error sending string (dapi_res): Worker b'dapi_res-140346588612352 not found. Please, send me the reason first.
Traceback (most recent call last):
  File "/var/ossec/bin/../framework/wazuh/cluster/communication.py", line 348, in send_string
    raise Exception(data)
Exception: Worker b'dapi_res-140346588612352 not found. Please, send me the reason first
``` 

In master node, the following result is shown:
```javascript
# curl -u foo:bar "localhost:55000/syscollector/001/os?pretty"
{
   "error": 1000,
   "message": "No command was received"
}
```

**Comment by mgmacias95** [comment]
When running the master with python3 and the worker with python2, the following error is shown:
```python
2018-10-16 11:37:19,192 DEBUG   : [Transport-I] Forwarding request to master of cluster 'dapi_forward' - 'b'946440341 node02 {"function": "/syscollector/:agent_id/os", "ossec_path": "/var/ossec", "from_cluster": true, "arguments": {"agent_id": "001"}}''
2018-10-16 11:37:19,207 DEBUG   : [Master] [node02] [Request-R]: 'dapi_res'.
2018-10-16 11:37:19,209 DEBUG   : [Master] [node02] [Response-R]: 'ok'.
2018-10-16 11:37:19,209 INFO    : [APIResponseReceiverMaster]: Start.
2018-10-16 11:37:19,214 DEBUG   : [Master] [node02] [Request-R]: 'fwd_new'.
2018-10-16 11:37:20,217 DEBUG   : [Master] [node02] [Request-R]: 'fwd_upd'.
2018-10-16 11:37:20,218 ERROR   : [APIResponseReceiverMaster]: Unknown error in process_cmd: must be str, not bytes.
Traceback (most recent call last):
  File "/var/ossec/bin/../framework/wazuh/cluster/communication.py", line 889, in run
    self.process_cmd(command, data)
  File "/var/ossec/bin/../framework/wazuh/cluster/master.py", line 401, in process_cmd
    return self.forward_msg(requests[command], data)
  File "/var/ossec/bin/../framework/wazuh/cluster/master.py", line 387, in forward_msg
    self.worker_thread_id if not data else self.worker_thread_id + ' ' + data)
TypeError: must be str, not bytes
2018-10-16 11:37:20,239 DEBUG   : [InternalSocketServer] Cleaning handler threads. Start.
2018-10-16 11:37:20,239 DEBUG   : [InternalSocketServer] Cleaning handler threads. End.
2018-10-16 11:37:20,239 INFO    : [InternalSocketServer] [946440341]: Disconnected.
2018-10-16 11:37:20,319 DEBUG   : [Master] [node02] [Request-R]: 'fwd_end'.
2018-10-16 11:37:20,320 INFO    : [APIResponseReceiverMaster]: End.
2018-10-16 11:37:20,321 DEBUG   : [Master] [node02] [Request-R]: 'err-is'.
2018-10-16 11:37:20,321 DEBUG   : [Master] Internal socket error received: 946440341 Error sending string (dapi_res): Worker dapi_res-140701975017216 not found. Please, send me the reason first
```

**Comment by mgmacias95** [comment]
When doing a request from a worker node, the following error is shown in the master:
```python
2018-10-16 14:46:21,700 DEBUG   : [Transport-I] Forwarding request to master of cluster 'dapi_forward' - 'b'4071326539 node02 {"function": "/syscollector/:agent_id/os", "ossec_path": "/var/ossec", "from_cluster": true, "arguments": {"agent_id": "001"}}''
2018-10-16 14:46:21,702 DEBUG   : [InternalSocket-Worker] [4071326539] Time sending request to internal socket server: 0.0027167797088623047s
2018-10-16 14:46:21,746 DEBUG   : [Master] [node02] [Request-R]: 'dapi_res'.
2018-10-16 14:46:21,747 INFO    : [APIResponseReceiver]: Start.
2018-10-16 14:46:21,747 DEBUG   : [Master] [node02] [Response-R]: 'ok'.
2018-10-16 14:46:21,748 INFO    : [APIResponseReceiverMaster]: Start.
2018-10-16 14:46:21,749 DEBUG   : [Master] [node02] [Request-R]: 'fwd_new'.
2018-10-16 14:46:21,750 DEBUG   : [APIResponseReceiver] Received command: new_f_r
2018-10-16 14:46:21,750 DEBUG   : [APIResponseReceiver]: Receiving new string.
2018-10-16 14:46:21,750 DEBUG   : [Master] [node02] [Request-R]: 'fwd_upd'.
2018-10-16 14:46:21,852 DEBUG   : [APIResponseReceiver] Received command: update_f_r
2018-10-16 14:46:21,852 DEBUG   : [Master] [node02] [Request-R]: 'fwd_end'.
2018-10-16 14:46:21,852 DEBUG   : [APIResponseReceiver]: Updating string.
2018-10-16 14:46:21,853 ERROR   : [APIResponseReceiver]: 'must be str, not bytes'.
Traceback (most recent call last):
  File "/var/ossec/bin/../framework/wazuh/cluster/communication.py", line 942, in process_cmd
    self.update(data)
  File "/var/ossec/bin/../framework/wazuh/cluster/communication.py", line 1093, in update
    self.sting_received += chunk
TypeError: must be str, not bytes
2018-10-16 14:46:21,955 ERROR   : [APIResponseReceiver]: An error took place during request reception.
NoneType: None
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/var/ossec/bin/../framework/wazuh/cluster/communication.py", line 872, in run
    self.unlock_and_stop(reason="error", send_err_request=str(e))
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by mgmacias95** [comment]
The following API request is working in the master node but the following error is shown in worker node:
```javascript
# curl -u foo:bar "localhost:55000/agents/stats/distinct?pretty"
{
   "error": 2003,
   "message": "Error in database request: aggregate functions are not allowed in the GROUP BY clause"
}
# curl -u foo:bar "localhost:55000/agents/stats/distinct?pretty&search=linux"
{
   "error": 2003,
   "message": "Error in database request: misuse of aggregate: COUNT()"
}
```

**Comment by mgmacias95** [comment]
After doing the same distributed API call (`curl -u foo:bar "localhost:55000/agents/003/config/logcollector/localfile?pretty"`) in both worker and master node, a timeout was raised and the following error keeps showing in the master log all the time:
```
2018-10-17 16:53:15,588 INFO    : [APIResponseReceiver]: Worker is not connected. Waiting 2s
```
