### ISSUE TITLE
Unable to start Dashboard service

### ISSUE THREAD

**Issue by c0r3dump3d** [wazuh/wazuh#16470]
| Wazuh version | Component |Install type | Install method | Platform |
| -------------------- | --------------- | ------------- | ------------------- | ----------- |
| 4.3 | Dashboard | multinode | step by step | Alma Linux 8 |

| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
| ------------- | -------------------------| -------------------- | ------------------------- | --------------- |
|  wazuh-dashboard-4.3.10-1| Dashboard |Manager| Yum | AlmaLinux 8 |

Hi, I have tried to install the Wazuh Dashboard component and after I have completed all the steps and start the service I have this error:

```
/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:173
  throw generateError(state, message);
  ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 7, column 35:
    opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
                                      ^
    at generateError (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1073:9)
    at composeNode (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at load (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at Object.safeLoad (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
    at readYaml (/usr/share/wazuh-dashboard/node_modules/@osd/apm-config-loader/target/utils/read_config.js:38:38)
    at Object.exports.getConfigFromFiles (/usr/share/wazuh-dashboard/node_modules/@osd/apm-config-loader/target/utils/read_config.js:63:22)
```
The opensearch_dashboards.yml config file is:
```
server.host: 0.0.0.0
server.port: 443
opensearch.hosts: ["https://10.10.6.85:9200","https://10.10.6.86:9200","https://10.10.6.87:9200"] 
opensearch.ssl.verificationMode: certificate
opensearch.username:admin
opensearch.password:admin
opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wazuh


```
And the wazuh.yml config file is:

```
hosts:
  - default:
    url: https://10.10.6.82
    port: 55000
    username: wazuh-wui
    password: wazuh-wui
    run_as: false
```

**Comment by c0r3dump3d** [comment]
Ohh, nice, now it's working. Thank you very much.
