### ISSUE TITLE
MacOS Mojave and Segfault on ossec-agentd start

### ISSUE THREAD

**Issue by michaelplemmons** [wazuh/wazuh#1675]
## Bug report

**OS**
MacOS Mojave

**Wazuh version**
3.6.1

**Wazuh API version**
3.6.1

**Install type**
agent

**Install method**
packages

**Log sample**

```

2018/10/17 13:13:40 wazuh-modulesd: INFO: Process started.
2018/10/17 13:13:40 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2018/10/17 13:14:01 ossec-syscheckd: ERROR: (1210): Queue '/Library/Ossec/queue/ossec/queue' not accessible: 'Queue not found'.
2018/10/17 13:14:01 rootcheck: CRITICAL: (1211): Unable to access queue: '/Library/Ossec/queue/ossec/queue'. Giving up..
2018/10/17 13:14:01 wazuh-modulesd: ERROR: (1210): Queue '/Library/Ossec/queue/ossec/queue' not accessible: 'Queue not found'.
2018/10/17 13:14:07 ossec-logcollector: ERROR: (1210): Queue '/Library/Ossec/queue/ossec/queue' not accessible: 'Queue not found'.
2018/10/17 13:14:07 ossec-logcollector: CRITICAL: (1211): Unable to access queue: '/Library/Ossec/queue/ossec/queue'. Giving up..
2018/10/17 13:14:19 ossec-execd: INFO: (1314): Shutdown received. Deleting responses.
2018/10/17 13:14:19 ossec-execd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2018/10/17 13:14:51 ossec-execd: INFO: Started (pid: 1979).
2018/10/17 13:14:51 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2018/10/17 13:14:51 wazuh-modulesd: INFO: Process started.
2018/10/17 13:14:51 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2018/10/17 13:15:04 ossec-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2018/10/17 13:15:04 ossec-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2018/10/17 13:15:04 ossec-execd: INFO: (1314): Shutdown received. Deleting responses.
2018/10/17 13:15:04 ossec-execd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2018/10/17 13:54:40 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2018/10/17 13:55:20 ossec-agentd: DEBUG: Starting ...
2018/10/17 13:55:20 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60


Plemmons-MacBook-Pro:bin root# lldb ./ossec-agentd -- -df
(lldb) target create "./ossec-agentd"
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Current executable set to './ossec-agentd' (x86_64).
(lldb) settings set -- target.run-args  "-df"
(lldb) run
Process 4556 launched: './ossec-agentd' (x86_64)
2018/10/17 13:55:20 ossec-agentd: DEBUG: Starting ...
2018/10/17 13:55:20 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
Process 4556 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007fff72209712 libsystem_platform.dylib`_platform_strlen + 18
libsystem_platform.dylib`_platform_strlen:
->  0x7fff72209712 <+18>: pcmpeqb (%rdi), %xmm0
    0x7fff72209716 <+22>: pmovmskb %xmm0, %esi
    0x7fff7220971a <+26>: andq   $0xf, %rcx
    0x7fff7220971e <+30>: orq    $-0x1, %rax
Target 0: (ossec-agentd) stopped.
(lldb) quit
```

Bug description
----------------

When attempting to start the agent with ossec-control several services do not start up.  I then ran ossect-agentd -df to see any relevant output.  I only get a segfault.  I then run the process under LLDB and see a EXC_BAD_ACCESS error.

**Comment by chemamartinez** [comment]
Hi @michaelplemmons,

First of all, thanks for reporting this issue. It seems the function to extract the Mac OS version was failing when doesn't recognize the codename making the agent fall.

For the next released, version we contemplated to include Mojave to the list of available codenames, and also, this PR https://github.com/wazuh/wazuh/pull/1679 avoids this situation again.

Sorry for the inconvenience, we hope to release the new version as soon as possible, by including this fix and many interesting features.

Best regards,
Chema.

**Comment by michaelplemmons** [comment]
Thank you for the information.  Would you happen to know if the new version will be out in the next few weeks or months?  I ask because our Security person will probably want to know when we can install this software on all the Mojave computers we have.

**Comment by chemamartinez** [comment]
We are working hard to close all the details and test every component thoroughly. We hope in the next following days it will be ready.

To keep abreast of the latest news, every released version is announced in the [Wazuh mailing lists](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/wazuh), the [blog](https://blog.wazuh.com) as well as the twitter account of Wazuh.

**Comment by lukelee1987** [comment]
May I know how do I configure to monitor my macbook? The wazuh-agent is running on the macbook, but on the Kibana, it shows client not connected.
