### ISSUE TITLE
Wazuh UI not loading after update from 4.0 to 4.4.4

### ISSUE THREAD

**Issue by anthony-pepe** [wazuh/wazuh#17773]
|Wazuh version|Component|Install type|Install method|Platform|
|4.4.4|wazuh|Manager|---|Centos 7|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

I just updated from 4.0 to 4.4.4 & now my wazuh dashboard wont load properly.
Installation is the Wazuh Central Componented install/update on a Centos 7 system.
If I complete a system reboot of the system the dashboard will fail to load. If I attempt to manually start the wazuh dashboard, it goes into a running state but the webpage is stuck on "This site can't be reached"

**Comment by anthony-pepe** [comment]
[root@wazuh-server wazuh-user]# systemctl status wazuh-dashboard.service -l
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2023-07-06 20:31:14 UTC; 1h 11min ago
  Process: 362 ExecStart=/usr/share/wazuh-dashboard/bin/opensearch-dashboards -c /etc/wazuh-dashboard/opensearch_dashboards.yml (code=exited, status=1/FAILURE)
 Main PID: 362 (code=exited, status=1/FAILURE)

Jul 06 20:31:03 wazuh-server opensearch-dashboards[362]: {"type":"log","@timestamp":"2023-07-06T20:31:03Z","tags":["info","savedobjects-service"],"pid":362,"message":"Detected mapping change in \"properties.map\""}
Jul 06 20:31:04 wazuh-server opensearch-dashboards[362]: {"type":"log","@timestamp":"2023-07-06T20:31:04Z","tags":["info","savedobjects-service"],"pid":362,"message":"Detected mapping change in \"properties.map\""}
Jul 06 20:31:06 wazuh-server opensearch-dashboards[362]: {"type":"log","@timestamp":"2023-07-06T20:31:06Z","tags":["info","savedobjects-service"],"pid":362,"message":"Detected mapping change in \"properties.map\""}
Jul 06 20:31:08 wazuh-server opensearch-dashboards[362]: {"type":"log","@timestamp":"2023-07-06T20:31:08Z","tags":["info","savedobjects-service"],"pid":362,"message":"Detected mapping change in \"properties.map\""}
Jul 06 20:31:09 wazuh-server opensearch-dashboards[362]: {"type":"log","@timestamp":"2023-07-06T20:31:09Z","tags":["info","savedobjects-service"],"pid":362,"message":"Detected mapping change in \"properties.map\""}
Jul 06 20:31:11 wazuh-server opensearch-dashboards[362]: {"type":"log","@timestamp":"2023-07-06T20:31:11Z","tags":["error","opensearch","data"],"pid":362,"message":"[circuit_breaking_exception]: [parent] Data too large, data             for [<http_request>] would be [3987068416/3.7gb], which is larger than the limit of [3976619622/3.7gb], real usage: [3987068416/3.7gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b            ]"}
Jul 06 20:31:11 wazuh-server opensearch-dashboards[362]: {"type":"log","@timestamp":"2023-07-06T20:31:11Z","tags":["warning","savedobjects-service"],"pid":362,"message":"Unable to connect to OpenSearch. Error: circuit_breakin            g_exception: [circuit_breaking_exception] Reason: [parent] Data too large, data for [<http_request>] would be [3987068416/3.7gb], which is larger than the limit of [3976619622/3.7gb], real usage: [3987068416/3.7gb], new bytes             reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b]"}
Jul 06 20:31:12 wazuh-server opensearch-dashboards[362]: {"type":"log","@timestamp":"2023-07-06T20:31:11Z","tags":["fatal","root"],"pid":362,"message":"ResponseError: circuit_breaking_exception: [circuit_breaking_exception] R            eason: [parent] Data too large, data for [<http_request>] would be [3987068416/3.7gb], which is larger than the limit of [3976619622/3.7gb], real usage: [3987068416/3.7gb], new bytes reserved: [0/0b], usages [request=0/0b, fi            elddata=0/0b, in_flight_requests=0/0b]\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@op            ensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at process            TicksAndRejections (internal/process/task_queues.js:82:21) {\n  meta: {\n    body: { error: [Object], status: 429 },\n    statusCode: 429,\n    headers: {\n      'content-type': 'application/json; charset=UTF-8',\n      'cont            ent-length': '801'\n    },\n    meta: {\n      context: null,\n      request: [Object],\n      name: 'opensearch-js',\n      connection: [Object],\n      attempts: 0,\n      aborted: false\n    }\n  }\n}"}
Jul 06 20:31:12 wazuh-server opensearch-dashboards[362]: {"type":"log","@timestamp":"2023-07-06T20:31:12Z","tags":["info","plugins-system"],"pid":362,"message":"Stopping all plugins."}
Jul 06 20:31:13 wazuh-server opensearch-dashboards[362]: FATAL  {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [3987068416/3.7gb], which is l            arger than the limit of [3976619622/3.7gb], real usage: [3987068416/3.7gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b]","bytes_wanted":3987068416,"bytes_limit":3976619622,"durab            ility":"TRANSIENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [3987068416/3.7gb], which is larger than the limit of [3976619622/3.7gb], real usage: [3987068416/            3.7gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b]","bytes_wanted":3987068416,"bytes_limit":3976619622,"durability":"TRANSIENT"},"status":429}
[root@wazuh-server wazuh-user]# systemctl status wazuh-indexer -l
● wazuh-indexer.service - Wazuh-indexer
   Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2023-07-06 19:30:13 UTC; 2h 12min ago
     Docs: https://documentation.wazuh.com
 Main PID: 2798 (java)
   CGroup: /system.slice/wazuh-indexer.service
           └─2798 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encodi            ng=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.nu            mDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms3991m -Xmx3991m -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/t            mp/opensearch-14707351128366247908 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,ta            gs:filecount=32,filesize=64m -XX:MaxDirectMemorySize=2092957696 -Dopensearch.path.home=/usr/share/wazuh-indexer -Dopensearch.path.conf=/etc/wazuh-indexer -Dopensearch.distribution.type=rpm -Dopensearch.bundled_jdk=true -cp /u            sr/share/wazuh-indexer/lib/* org.opensearch.bootstrap.OpenSearch -p /run/wazuh-indexer/wazuh-indexer.pid --quiet

Jul 06 19:29:41 wazuh-server systemd-entrypoint[2798]: WARNING: A terminally deprecated method in java.lang.System has been called
Jul 06 19:29:41 wazuh-server systemd-entrypoint[2798]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/wazuh-indexer/lib/opensearch-2.6.0.jar)
Jul 06 19:29:41 wazuh-server systemd-entrypoint[2798]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
Jul 06 19:29:41 wazuh-server systemd-entrypoint[2798]: WARNING: System::setSecurityManager will be removed in a future release
Jul 06 19:29:43 wazuh-server systemd-entrypoint[2798]: WARNING: A terminally deprecated method in java.lang.System has been called
Jul 06 19:29:43 wazuh-server systemd-entrypoint[2798]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share/wazuh-indexer/lib/opensearch-2.6.0.jar)
Jul 06 19:29:43 wazuh-server systemd-entrypoint[2798]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
Jul 06 19:29:43 wazuh-server systemd-entrypoint[2798]: WARNING: System::setSecurityManager will be removed in a future release

**Comment by anthony-pepe** [comment]
Already increased /etc/wazuh-indexer/jvm.options
Was:
-Xms3991m
-Xmx3991m
Current:
-Xms4g
-Xmx4g

System currently has 4CPU, 8GB RAM

**Comment by anthony-pepe** [comment]
We have since did troubleshooting from suggestions in the Slack community.
We have increased the Ram to 24GB, still no luck.
I can provide updated logs or status checks if needed.
Going on 4 weeks now with no active SIEM.

**Comment by pereyra-m** [comment]
Closing this issue.
@efahnle solved it at https://wazuh.slack.com/archives/C0A933R8E/p1689087176707779

**Comment by bpbp-boop** [comment]
@pereyra-m Can you share the solution here please? I can't access that slack.

**Comment by pereyra-m** [comment]
Hi @bpbp-boop ! The message is too old.
Hello @efahnle , do you have the solution at hand?
