### ISSUE TITLE
Cluster control -a is broken in worker nodes

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#1871]
## Bug report

**OS**
Ubuntu 18. But I'm sure it happens in other OSs too.

**Wazuh version**
3.7.0

**Install type**
manager

**Install method**
sources

**Log sample**

```shellsession
# /var/ossec/bin/cluster_control -ad
DEBUG: [ClusterClient] Worker ID: 3479056328
INFO: [ClusterClient] [3479056328] Connected.
DEBUG: [ClusterClient] [3479056328] Time sending request to internal socket server: 0.006192684173583984s
DEBUG: Waiting response.
INFO: [Cluster] [API-R_3479056328]: Start.
DEBUG: [Cluster] [API-R_3479056328] Received command: new_f_r
DEBUG: [Cluster] [API-R_3479056328]: Receiving new string.
DEBUG: [Cluster] [API-R_3479056328] Received command: update_f_r
DEBUG: [Cluster] [API-R_3479056328]: Updating string.
DEBUG: [Cluster] [API-R_3479056328] Received command: end_f_r
DEBUG: [Cluster] [API-R_3479056328]: Complete string reception.
DEBUG: [Cluster] [API-R_3479056328]: Reception completed: (0.20s / 0.20317411422729492B)
DEBUG: [Cluster] [API-R_3479056328]: Data received.
INFO: [Cluster] [API-R_3479056328]: Result: Successfully.
ERROR: Error 1000 - Wazuh Internal Error: 'wait_for_complete'
Traceback (most recent call last):
  File "/var/ossec/bin/cluster_control", line 262, in <module>
    print_agents(args.filter_status, args.filter_node, is_master)
  File "/var/ossec/bin/cluster_control", line 149, in print_agents
    agents = get_agents(filter_status, filter_node, is_master)
  File "/var/ossec/bin/../framework/wazuh/cluster/control.py", line 106, in get_agents
    raise WazuhException(response['error'], response['message'])
wazuh.exception.WazuhException: Error 1000 - Wazuh Internal Error: 'wait_for_complete'
```

**Comment by mgmacias95** [comment]
Done in #1873.
