### ISSUE TITLE
Fix test_experimental_endpoints API integration test

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#18768]
## Description

The `test_experimental_endpoints.tavern.yaml` is failing in master due to an unexpected package `pypi` when calling `GET /experimental/syscollector/packages`

```console
Errors:
E   tavern.util.exceptions.TestFailError: Test 'Request' failed:
    - Status code was 500, expected 200
    - Structure of returned data was different than expected
...
'Response body does not conform to specification', 'detail': "'pypi' is not one of ['deb', 'rpm', 'win', 'pkg'].
...
Left contains 2 more items:
  {'detail': "'pypi' is not one of ['deb', 'rpm', 'win', 'pkg']. Failed "
             "validating 'enum' in "
             "schema['allOf'][1]['properties']['data']['allOf'][1]['properties']['affected_items']['items']['properties']['format']: "
             "{'description': 'Package format', 'enum': ['deb', 'rpm', 'win', "
             "'pkg'], 'type': 'string'}. On "
             "instance['data']['affected_items'][55]['format']: 'pypi'",
   'title': 'Response body does not conform to specification'}
``` 

Artifacts: [Test_integration_endpoints_B3809_test_experimental_endpoints.zip](https://github.com/wazuh/wazuh/files/12514722/Test_integration_endpoints_B3809_test_experimental_endpoints.zip)

<details><summary>Full log</summary>

```console
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.5', 'Platform': 'Linux-5.4.0-1029-aws-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.9.0', 'pluggy': '0.13.1'}, 'Plugins': {'tavern': '1.0.0', 'metadata': '1.10.0', 'html': '2.0.1'}}
rootdir: /tmp/Test_integration_endpoints_B3809_test_files/api/test/integration, inifile: pytest.ini
plugins: tavern-1.0.0, metadata-1.10.0, html-2.0.1
collecting ... collected 12 items

test_experimental_endpoints.tavern.yaml::DELETE /experimental/rootcheck PASSED [  8%]
test_experimental_endpoints.tavern.yaml::DELETE /experimental/syscheck PASSED [ 16%]
test_experimental_endpoints.tavern.yaml::GET /experimental/ciscat/results PASSED [ 25%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/hardware PASSED [ 33%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netaddr PASSED [ 41%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netiface PASSED [ 50%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/netproto PASSED [ 58%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/os PASSED [ 66%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/packages FAILED [ 75%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/ports PASSED [ 83%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/processes PASSED [ 91%]
test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/hotfixes PASSED [100%]

=================================== FAILURES ===================================
_ /tmp/Test_integration_endpoints_B3809_test_files/api/test/integration/test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/packages _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjkzODMxMTY2LCJleHAiOjE2OTM4MzIwNjYsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AaCXcQETFQHldVfCBtCudcHvwYLsrftzwLzOlgD31EVL26jIJMRcPKPLIMXKzj0E1c6lwzLlJR5gnA4-8B6BYMN3AaJpZ5JmlW5iQKc39Le_eWdz5gOnZkA5di73TMvMSoWb2vjf57aNb8waDR2SdZdDHXFGCbZZC1P7cec39kAW4gna'

Source test stage (line 486):
  - name: Request
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/experimental/syscollector/packages?wait_for_complete=true"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      status_code: 200
      json:
        error: !anyint
        data:
          affected_items: !anything
          failed_items: []
          total_affected_items: !anyint
          total_failed_items: 0


Formatted stage:
  name: Request
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjkzODMxMTY2LCJleHAiOjE2OTM4MzIwNjYsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AaCXcQETFQHldVfCBtCudcHvwYLsrftzwLzOlgD31EVL26jIJMRcPKPLIMXKzj0E1c6lwzLlJR5gnA4-8B6BYMN3AaJpZ5JmlW5iQKc39Le_eWdz5gOnZkA5di73TMvMSoWb2vjf57aNb8waDR2SdZdDHXFGCbZZC1P7cec39kAW4gna
    method: GET
    url: 'https://localhost:55000/experimental/syscollector/packages?wait_for_complete=true'
    verify: false
  response:
    json:
      data:
        affected_items: !anything ''
        failed_items: []
        total_affected_items: !anyint ''
        total_failed_items: 0
      error: !anyint ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Request' failed:
    - Status code was 500, expected 200
    - Structure of returned data was different than expected  - Extra keys in response: {'title', 'detail'} - Keys missing from response: {'error', 'data'} (expected = '{'error': <tavern.util.loader.IntSentinel object at 0x7faf67987d90>, 'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7faf68551400>, 'failed_items': [], 'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7faf67987eb0>, 'total_failed_items': 0}}' (type = <class 'dict'>), actual = '{'title': 'Response body does not conform to specification', 'detail': "'pypi' is not one of ['deb', 'rpm', 'win', 'pkg']. Failed validating 'enum' in schema['allOf'][1]['properties']['data']['allOf'][1]['properties']['affected_items']['items']['properties']['format']: {'description': 'Package format', 'enum': ['deb', 'rpm', 'win', 'pkg'], 'type': 'string'}. On instance['data']['affected_items'][55]['format']: 'pypi'"}' (type = <class 'dict'>))
------------------------------ Captured log call -------------------------------
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:43 Status code was 500, expected 200
ERROR    tavern.response.base:base.py:41 Structure of returned data was different than expected  - Extra keys in response: {'title', 'detail'} - Keys missing from response: {'error', 'data'} (expected = '{'error': <tavern.util.loader.IntSentinel object at 0x7faf67987d90>, 'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7faf68551400>, 'failed_items': [], 'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7faf67987eb0>, 'total_failed_items': 0}}' (type = <class 'dict'>), actual = '{'title': 'Response body does not conform to specification', 'detail': "'pypi' is not one of ['deb', 'rpm', 'win', 'pkg']. Failed validating 'enum' in schema['allOf'][1]['properties']['data']['allOf'][1]['properties']['affected_items']['items']['properties']['format']: {'description': 'Package format', 'enum': ['deb', 'rpm', 'win', 'pkg'], 'type': 'string'}. On instance['data']['affected_items'][55]['format']: 'pypi'"}' (type = <class 'dict'>))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'detail': "'pypi' is not one of ['deb', 'rpm', 'win', 'pkg']. Failed "\n           "validating 'enum' in "\n           "schema['allOf'][1]['properties']['data']['allOf'][1]['properties']['affected_items']['items']['properties']['format']: "\n           "{'description': 'Package format', 'enum': ['deb', 'rpm', 'win', "\n           "'pkg'], 'type': 'string'}. On "\n           "instance['data']['affected_items'][55]['format']: 'pypi'",\n 'title': 'Response body does not conform to specification'} == {'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7faf68551400>,\n          'failed_items': [],\n          'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7faf67987eb0>,\n          'total_failed_items': 0},\n 'error': <tavern.util.loader.IntSentinel object at 0x7faf67987d90>}
  Left contains 2 more items:
  {'detail': "'pypi' is not one of ['deb', 'rpm', 'win', 'pkg']. Failed "
             "validating 'enum' in "
             "schema['allOf'][1]['properties']['data']['allOf'][1]['properties']['affected_items']['items']['properties']['format']: "
             "{'description': 'Package format', 'enum': ['deb', 'rpm', 'win', "
             "'pkg'], 'type': 'string'}. On "
             "instance['data']['affected_items'][55]['format']: 'pypi'",
   'title': 'Response body does not conform to specification'}
  Right contains 2 more items:
  {'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7faf68551400>,
            'failed_items': [],
            'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7faf67987eb0>,
            'total_failed_items': 0},
   'error': <tavern.util.loader.IntSentinel object at 0x7faf67987d90>}
  Full diff:
    {
  -  'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7faf68551400>,
  -           'failed_items': [],
  -           'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7faf67987eb0>,
  -           'total_failed_items': 0},
  -  'error': <tavern.util.loader.IntSentinel object at 0x7faf67987d90>,
  +  'detail': "'pypi' is not one of ['deb', 'rpm', 'win', 'pkg']. Failed "
  +            "validating 'enum' in "
  +            "schema['allOf'][1]['properties']['data']['allOf'][1]['properties']['affected_items']['items']['properties']['format']: "
  +            "{'description': 'Package format', 'enum': ['deb', 'rpm', 'win', "
  +            "'pkg'], 'type': 'string'}. On "
  +            "instance['data']['affected_items'][55]['format']: 'pypi'",
  +  'title': 'Response body does not conform to specification',
    }

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 447, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(full_msg) from e
tavern.util.exceptions.KeyMismatchError: Structure of returned data was different than expected  - Extra keys in response: {'title', 'detail'} - Keys missing from response: {'error', 'data'} (expected = '{'error': <tavern.util.loader.IntSentinel object at 0x7faf67987d90>, 'data': {'affected_items': <tavern.util.loader.AnythingSentinel object at 0x7faf68551400>, 'failed_items': [], 'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7faf67987eb0>, 'total_failed_items': 0}}' (type = <class 'dict'>), actual = '{'title': 'Response body does not conform to specification', 'detail': "'pypi' is not one of ['deb', 'rpm', 'win', 'pkg']. Failed validating 'enum' in schema['allOf'][1]['properties']['data']['allOf'][1]['properties']['affected_items']['items']['properties']['format']: {'description': 'Package format', 'enum': ['deb', 'rpm', 'win', 'pkg'], 'type': 'string'}. On instance['data']['affected_items'][55]['format']: 'pypi'"}' (type = <class 'dict'>))
=============================== warnings summary ===============================
/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/hooks.py:83
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/hooks.py:83: PytestDeprecationWarning: direct construction of YamlFile has been deprecated, please use YamlFile.from_parent
    return YamlFile(path, parent)

/usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:233: 12 tests with warnings
  /usr/local/lib/python3.8/dist-packages/tavern/testutils/pytesthook/file.py:233: PytestDeprecationWarning: direct construction of YamlItem has been deprecated, please use YamlItem.from_parent
    item = YamlItem(test_spec["test_name"], self, test_spec, self.fspath)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
- generated html file: file:///tmp/Test_integration_endpoints_B3809_test_files/api/test/integration/Test_integration_endpoints_B3809_test_experimental_endpoints.html -
=========================== short test summary info ============================
FAILED test_experimental_endpoints.tavern.yaml::GET /experimental/syscollector/packages
============ 1 failed, 11 passed, 13 warnings in 383.20s (0:06:23) =============
```

</details>

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by javiersanchz** [comment]
## Update

- The error provided by test_experimental_endpoints.tavern.yaml in GET /experimental/syscollector/packages with the "pypi" format originates from https://github.com/wazuh/wazuh/pull/17982, where support for the "PyPI" package is added.

**Comment by javiersanchz** [comment]
## Update

- Another branch was created, and the pacman, apk, macports, and npm packages were also added, which were not present either
