### ISSUE TITLE
Investigate RBAC error in API integration test

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#18886]
|Wazuh version|Component|
|---|---|
| 4.6.0-alpha1 | API |

## Description
During the execution of the API integration tests, required for #18877, it was found that `test_rbac_white_all_endpoints.tavern.yaml::GET /groups` failed, having the following error:

```
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjk0MTEzNjI4LCJleHAiOjE2OTQxMTQ1MjgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbXSwicmJhY19tb2RlIjoid2hpdGUifQ.AGmK7mhfiU_MDVm_QYuBcULb_cPquQKtuFYVIqVchKPMw7nbK87CRTz3jLp98rRohWbaqFEOz6Dik64-D1CKP8ghAdzNZY2lwjadqJeF0xYt2pBy_OM3kkaAv3vN78L5E3AYguDyY8aZvkcSOp9FbTPuy3jinp-awIdzi_LNGTuZ5rI6'

Source test stage (line 1462):
  - name: Try to get all groups (generic)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/groups"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      <<: *empty_response


Formatted stage:
  name: Try to get all groups (generic)
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjk0MTEzNjI4LCJleHAiOjE2OTQxMTQ1MjgsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbXSwicmJhY19tb2RlIjoid2hpdGUifQ.AGmK7mhfiU_MDVm_QYuBcULb_cPquQKtuFYVIqVchKPMw7nbK87CRTz3jLp98rRohWbaqFEOz6Dik64-D1CKP8ghAdzNZY2lwjadqJeF0xYt2pBy_OM3kkaAv3vN78L5E3AYguDyY8aZvkcSOp9FbTPuy3jinp-awIdzi_LNGTuZ5rI6
    method: GET
    url: 'https://localhost:55000/groups'
    verify: false
  response:
    json:
      data:
        affected_items: []
        failed_items: []
        total_affected_items: 0
        total_failed_items: 0
      error: 0
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Try to get all groups (generic)' failed:
    - Key mismatch: (expected["data"]["total_affected_items"] = '0' (type = <class 'int'>), actual["data"]["total_affected_items"] = '4' (type = <class 'int'>))
 -------------------------------Captured log call-------------------------------- 
WARNING  tavern._plugins.rest.response:response.py:29 Unexpected status code '200'
ERROR    tavern.response.base:base.py:41 Key mismatch: (expected["data"]["total_affected_items"] = '0' (type = <class 'int'>), actual["data"]["total_affected_items"] = '4' (type = <class 'int'>))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'af...was returned'} == {'data': {'af...}, 'error': 0}
  Omitting 1 identical items, use -vv to show
  Differing items:
  {'data': {'affected_items': [{'configSum': 'ab73af41699f13fdd81903b5f23d8d00', 'count': 10, 'mergedSum': '4a8724b20dee...17076b5594699a19915d178a', 'name': 'group3'}], 'failed_items': [], 'total_affected_items': 4, 'total_failed_items': 0}} != {'data': {'affected_items': [], 'failed_items': [], 'total_affected_items': 0, 'total_failed_items': 0}}
  Left contains 1 more item:
  {'message': 'All selected groups information was returned'}
  Full diff:
    {...
  
  ...Full output truncated (27 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_it...led_items': 0} == {'affected_it...led_items': 0}
  Omitting 2 identical items, use -vv to show
  Differing items:
  {'affected_items': [{'configSum': 'ab73af41699f13fdd81903b5f23d8d00', 'count': 10, 'mergedSum': '4a8724b20dee0124ff965...': 'ab73af41699f13fdd81903b5f23d8d00', 'count': 4, 'mergedSum': 'ac734e0a17076b5594699a19915d178a', 'name': 'group3'}]} != {'affected_items': []}
  {'total_affected_items': 4} != {'total_affected_items': 0}
  Full diff:
    {
  -  'affected_items': [],...
  
  ...Full output truncated (24 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert 4 == 0
  +4
  -0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tavern/response/base.py", line 88, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 462, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/usr/local/lib/python3.8/dist-packages/tavern/util/dict_util.py", line 546, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(
tavern.util.exceptions.KeyMismatchError: Key mismatch: (expected["data"]["total_affected_items"] = '0' (type = <class 'int'>), actual["data"]["total_affected_items"] = '4' (type = <class 'int'>))
```

### Test results

[Test_integration_endpoints_B3825_test_rbac_white_all_endpoints.txt](https://github.com/wazuh/wazuh/files/12553028/Test_integration_endpoints_B3825_test_rbac_white_all_endpoints.txt)
[Test_integration_endpoints_B3825_test_rbac_white_all_endpoints.zip](https://github.com/wazuh/wazuh/files/12553029/Test_integration_endpoints_B3825_test_rbac_white_all_endpoints.zip)
[Test_integration_endpoints_B3825_test_rbac_white_all_endpoints_logs.zip](https://github.com/wazuh/wazuh/files/12553030/Test_integration_endpoints_B3825_test_rbac_white_all_endpoints_logs.zip)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by nico-stefani** [comment]
Possible duplicated in #16750

**Comment by nico-stefani** [comment]
Possible duplicated in #16750
