### ISSUE TITLE
Corrupted RBAC database when trying to create a user using the WUI

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#18900]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0 | RBAC | -- | Packages | Demo environment |

During the tests carried out in https://github.com/wazuh/wazuh/issues/18843#issuecomment-1711931130 issue, an error was found when trying to create a user from the WUI, obtaining an error `500 Internal Server Error`

The message indicates that the RBAC database is corrupt, this also happens when trying to create a new role

![image](https://github.com/wazuh/wazuh/assets/14913942/90058bf9-09b3-4ff8-a63f-c00950d4bba0)
![image](https://github.com/wazuh/wazuh/assets/14913942/a94ed13c-a908-4fb0-bddd-7a134f6d0cb1)

```
AxiosError: Wazuh API error: ERR_BAD_RESPONSE - Corrupted RBAC database
    at settle (https://demo.wazuh.info/46000/bundles/plugin/wazuh/wazuh.plugin.js:8:20234)
    at XMLHttpRequest.onloadend (https://demo.wazuh.info/46000/bundles/plugin/wazuh/wazuh.plugin.js:8:25708)
```

It was not possible to get the api.log file due to not enough space left in the device, but I could get some messages with `unknown_user`, all the messages were cataloged as INFO, and no ERROR was found

```
2023/09/08 13:55:00 INFO: wazuh 10.0.0.232 "GET /cluster/worker_01/stats/remoted" with parameters {} and body {} done in 0.043s: 200
2023/09/08 13:55:00 INFO: wazuh 10.0.0.232 "GET /cluster/worker_01/stats/analysisd" with parameters {} and body {} done in 0.038s: 200
2023/09/08 14:00:01 INFO:
```

```
2023/09/08 12:30:00 INFO: unknown_user 10.0.0.232 "GET /cluster/nodes" with parameters {"select": "name"} and body {} done in 0.003s: 401
2023/09/08 12:30:00 INFO: unknown_user 10.0.0.232 "GET /cluster/status" with parameters {} and body {} done in 0.003s: 401
2023/09/08 12:30:00 INFO: unknown_user 10.0.0.232 "GET /cluster/nodes" with parameters {"select": "name"} and body {} done in 0.004s: 401
2023/09/08 12:30:01 INFO: wazuh 10.0.0.232 "POST /security/user/authenticate" with parameters {} and body {} done in 1.398s: 200
```

**Comment by GGP1** [comment]
## Update

Tried replicating the issue by creating a user and a role and the requests were executed successfully

<details><summary><code>POST /security/users</code></summary>

```json
{
    "data": {
        "affected_items": [
            {
                "id": 100,
                "username": "yoda",
                "allow_run_as": false,
                "roles": []
            }
        ],
        "total_affected_items": 1,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "User was successfully created",
    "error": 0
}
```

</details>

<details><summary><code>POST /security/roles</code></summary>

```json
{
    "data": {
        "affected_items": [
            {
                "id": 100,
                "name": "jedi",
                "policies": [],
                "users": [],
                "rules": []
            }
        ],
        "total_affected_items": 1,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "Role was successfully created",
    "error": 0
}
```

</details>

<details><summary>api.log</summary>

```console
root@wazuh-master:/# tail -f /var/ossec/logs/api.log
2023/09/11 18:06:08 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2023/09/11 18:06:08 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key
2023/09/11 18:06:08 INFO: Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt
2023/09/11 18:06:08 INFO: Checking RBAC database integrity...
2023/09/11 18:06:08 INFO: RBAC database not found. Initializing
2023/09/11 18:06:21 INFO: /var/ossec/api/configuration/security/rbac.db database created successfully
2023/09/11 18:06:21 INFO: RBAC database integrity check finished successfully
2023/09/11 18:06:26 INFO: Listening on 0.0.0.0:55000..
2023/09/11 18:06:46 INFO: wazuh 172.22.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.327s: 200
2023/09/11 18:08:05 INFO: wazuh 172.22.0.1 "POST /security/roles" with parameters {"pretty": "false", "wait_for_complete": "false"} and body {"name": "jedi"} done in 0.072s: 200
2023/09/11 18:10:48 INFO: wazuh 172.22.0.1 "POST /security/users" with parameters {"pretty": "false", "wait_for_complete": "false"} and body {"username": "yoda", "password": "****"} done in 0.223s: 200
```

</details>

Even though the message mentions a corrupted database, the exception catched [sqlalchemy.exc.OperationalError](https://docs.sqlalchemy.org/en/20/core/exceptions.html#sqlalchemy.exc.OperationalError) may be _any_ error coming from `sqlite3`.

@rauldpm in the description you mention that there was not enough space left in the device. It could be that the operation could not be performed due to resources restrictions.

Have you tried adding users/roles in an environment without this particularity?

**Comment by GGP1** [comment]
## Update

Replicated the issue in an environment without disk space left and I received the same response as the mentioned in the issue description. 

The exception `sqlalchemy.exc.OperationalError` is in fact used to catch any kind of error coming from `sqlite3`. In this case, the exception is `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database or disk is full`

I tried detecting the error type using the exception message (similar to what's done [here](https://github.com/wazuh/wazuh/blob/17469f88206a90e54e0d5f6ee81a0a04996ada1f/framework/wazuh/core/database.py#L106)) but it contains the raw SQL call and the parameters used.

```
(sqlite3.OperationalError) database or disk is full
[SQL: INSERT INTO users (username, password, allow_run_as, created_at) VALUES (?, ?, ?, ?)]
[parameters: ('username3', 'pbkdf2:sha256:260000$VChY6COy1fghgsa4$aece0fddb889c2ea2bd8339ffee8a51d683e3de6a6e5f40a298b1e685a6a7a91', 0, '2023-09-13 13:16:46.572804')]
```

### Logs

```console
root@ip-172-31-63-60:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       9.6G  3.7G  5.9G  38% /
tmpfs           2.0G   80K  2.0G   1% /dev/shm
tmpfs           785M  856K  784M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/xvda15     105M  6.1M   99M   6% /boot/efi
tmpfs           393M  4.0K  393M   1% /run/user/1000
root@ip-172-31-63-60:/# fallocate -l 5.9GB dump
root@ip-172-31-63-60:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       9.6G  9.2G  309M  97% /
tmpfs           2.0G   80K  2.0G   1% /dev/shm
tmpfs           785M  856K  784M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/xvda15     105M  6.1M   99M   6% /boot/efi
tmpfs           393M  4.0K  393M   1% /run/user/1000
root@ip-172-31-63-60:/# fallocate -l 309M dump2
fallocate: fallocate failed: No space left on device
root@ip-172-31-63-60:/# fallocate -l 308M dump2
root@ip-172-31-63-60:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       9.6G  9.5G     0 100% /
tmpfs           2.0G   80K  2.0G   1% /dev/shm
tmpfs           785M  856K  784M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/xvda15     105M  6.1M   99M   6% /boot/efi
tmpfs           393M  4.0K  393M   1% /run/user/1000
root@ip-172-31-63-60:/# tail -f /var/ossec/logs/api.log
...
2023/09/13 12:41:55 ERROR: Corrupted RBAC database
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/var/ossec/framework/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database or disk is full
...
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database or disk is full
[SQL: INSERT INTO users (username, password, allow_run_as, created_at) VALUES (?, ?, ?, ?)]
[parameters: ('username3', 'pbkdf2:sha256:260000$TVrVQ9asx2ryV8pV$84bbf9ab61d8ac760287a00f303a85083882eaf9cf5aaecc9e391f8c3585717c', 0, '2023-09-13 12:41:55.299057')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.6.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 301, in execute_local_request
    raise exception.WazuhInternalError(2008)
wazuh.core.exception.WazuhInternalError: Error 2008 - Corrupted RBAC database
2023/09/13 12:41:55 INFO: wazuh 190.138.158.247 "POST /security/users" with parameters {"pretty": "false", "wait_for_complete": "false"} and body {"username": "username3", "password": "****"} done in 0.423s: 500
```

#### Request

`POST /security/users`

```json
{
  "username": "username3",
  "password": "xxx"
}
```
