### ISSUE TITLE
Release 4.6.0 - Alpha 1 - E2E UX tests - Wazuh Indexer

### ISSUE THREAD

**Issue by Ifex370** [wazuh/wazuh#18932]
## Updated

The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |  Wazuh Indexer   |
| **Category**            |    Installation        |
| **Deployment option**   |   Single Indexer, server and agent: Installation assistant       |
| **Main release issue**  |        https://github.com/wazuh/wazuh/issues/18836                                    |
| **Alpha 1 #** |                1                            |

## Environment

| | | |
|-|-|-|
| **Component** | **OS** | **Installation** |
| Wazuh dashboard | Fedora 37 x86_64 | Step by Step |
| Wazuh indexer | Fedora 37 x86_64 | Step by Step |
| Wazuh server | Fedora 37 x86_64 | Step by Step |
| Wazuh agent | Fedora 37 x86_64 | Step by Step |

## Test description

Best effort to test Wazuh indexer package. Think critically and at least review/test:
- Wazuh indexer package specs
- Indexer package size
- Indexer package metadata (description)
- Indexer package digital signature
- Installed files location, size and permissions
- Installation footprint (check that no unnecessary files are modified/broken in the file system. For example that operating system files do keep their right owner/pemissions and that the installer did not break the system.)
- Installed Wazuh indexer service
- Wazuh indexer logs when installed
- Wazuh indexer templates and indices created
- Wazuh indexer configuration (e.g. replicas are expected to be zero by default, how many shards per index,...) Try to compare and find anomalies with the previous Wazuh indexer version using appropiate E2E UX issue. Write down and report as much information as possible to allow comparison between versions using this issue.
- Wazuh indexer cluster node communication and configuration
- Wazuh indexer cluster status
- Wazuh indexer packages uninstallation procedure

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found here.

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
| :green_circle:  | [Environment installation](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712770961) |  |  |
| :green_circle:  | [Wazuh indexer package](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712789302) |  |  |
| :green_circle:  | [Wazuh indexer installed files location, size and permissions](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712793554) |  |  |
| 🟢   | [Wazuh indexer installation footprint](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712794270) |  |  |
| 🟢   | [Wazuh indexer installed service](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712799181) |  |  |
| :green_circle:  | [Wazuh indexer logs when installed](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712800106) |  |  |
| 🟢  | [Wazuh indexer templates and indices created](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712823789) |  |  |
| 🟢  | [Wazuh indexer configuration](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712826196) |  |  |
| 🟢  | [Wazuh indexer cluster node communication and configuration](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712829475) |  |  |
| 🟢  | [Wazuh indexer cluster status](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712829949) |  |  |
| :green_circle:  | [Wazuh indexer packages uninstallation procedure](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712830969) |  |  |
| 🟢   | [User experience](https://github.com/wazuh/wazuh/issues/18932#issuecomment-1712908630) | Usability | I did not experience any bottle necks with the dashboard, server, or indexer. |

All tests have passed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @davidjiglesias 
- [x] @wazuh/frontend

**Comment by Ifex370** [comment]
# Environment installation 🟢 

Each component was installed using the `Installation assistant`.

## Wazuh indexer

```shellsession
[root@fedora wazuhifeanyi]# yum install coreutils
Fedora 37 - x86_64 - Updates                                               91 kB/s |  14 MB     02:33    
Fedora Modular 37 - x86_64 - Updates                                      129 kB/s | 2.9 MB     00:23    
EL-37 - Wazuh                                                             727 kB/s |  19 MB     00:27    
Last metadata expiration check: 0:00:19 ago on Fri 08 Sep 2023 17:08:24.
Package coreutils-9.1-6.fc37.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

[root@fedora wazuhifeanyi]# echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages-dev.wazuh.com/pre-release/yum/\nprotect=1' | tee /etc/yum.repos.d/wazuh.repo
[wazuh]
gpgcheck=1
gpgkey=https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-$releasever - Wazuh
baseurl=https://packages-dev.wazuh.com/pre-release/yum/
protect=1
[root@fedora wazuhifeanyi]# 
[root@fedora wazuhifeanyi]# yum -y install wazuh-indexer
EL-37 - Wazuh                                                             2.6 kB/s | 3.4 kB     00:01    
Dependencies resolved.
==========================================================================================================
 Package                       Architecture           Version                 Repository             Size
==========================================================================================================
Installing:
 wazuh-indexer                 x86_64                 4.6.0-1                 wazuh                 673 M

Transaction Summary
==========================================================================================================
Install  1 Package

Total download size: 673 M
Installed size: 930 M
Downloading Packages:
wazuh-indexer-4.6.0-1.x86_64.rpm                                          1.5 MB/s | 673 MB     07:23    
----------------------------------------------------------------------------------------------------------
Total                                                                     1.5 MB/s | 673 MB     07:23     
EL-37 - Wazuh                                                             2.4 kB/s | 3.1 kB     00:01    
Importing GPG key 0x29111145:
 Userid     : "Wazuh.com (Wazuh Signing Key) <support@wazuh.com>"
 Fingerprint: 0DCF CA55 47B1 9D2A 6099 5060 96B3 EE5F 2911 1145
 From       : https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                  1/1 
  Running scriptlet: wazuh-indexer-4.6.0-1.x86_64                                                     1/1 
  Installing       : wazuh-indexer-4.6.0-1.x86_64 [==========================                       ] 1/1

  Installing       : wazuh-indexer-4.6.0-1.x86_64 [=======================================          ] 1/1
  Installing       : wazuh-indexer-4.6.0-1.x86_64 [========================================         ] 1/1
  Installing       : wazuh-indexer-4.6.0-1.x86_64                                                     1/1 
  Running scriptlet: wazuh-indexer-4.6.0-1.x86_64                                                     1/1 
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore

  Verifying        : wazuh-indexer-4.6.0-1.x86_64                                                     1/1 

Installed:
  wazuh-indexer-4.6.0-1.x86_64                                                                            

Complete!
```

**Comment by Ifex370** [comment]
# Wazuh indexer package 🟢 

## Package SPECs 🟢 

I could not identify any issue with the package SPEC. However, I don't have the expertise to assert everything is correct. 

```shellsession
[root@fedora wazuhifeanyi]# rpm -qa | grep wazuh
wazuh-indexer-4.6.0-1.x86_64

[root@fedora wazuhifeanyi]# rpm -qi wazuh-indexer-4.6.0-1.x86_64
Name        : wazuh-indexer
Version     : 4.6.0
Release     : 1
Architecture: x86_64
Install Date: Fri 08 Sep 2023 17:18:22
Group       : System Environment/Daemons
Size        : 974896391
License     : GPL
Signature   : RSA/SHA256, Wed 06 Sep 2023 22:58:32, Key ID 96b3ee5f29111145
Source RPM  : wazuh-indexer-4.6.0-1.src.rpm
Build Date  : Wed 06 Sep 2023 21:43:13
Build Host  : ip-172-31-23-228.ec2.internal
Packager    : Wazuh, Inc <info@wazuh.com>
Vendor      : Wazuh, Inc <info@wazuh.com>
URL         : https://www.wazuh.com/
Summary     : Wazuh indexer is a search and analytics engine for security-related data. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html
Description :
Wazuh indexer is a near real-time full-text search and analytics engine that gathers security-related data into one platform. This Wazuh central component indexes and stores alerts generated by the Wazuh server. Wazuh indexer can be configured as a single-node or multi-node cluster, providing scalability and high availability. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html
[root@fedora wazuhifeanyi]#

```

## Package size 🟢 

Total download size: 673 M

Installed size: 930 M

## Package metadata (description) 🟢 

Everything seems fine.

```
Summary     : Wazuh indexer is a search and analytics engine for security-related data. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html
Description :
Wazuh indexer is a near real-time full-text search and analytics engine that gathers security-related data into one platform. This Wazuh central component indexes and stores alerts generated by the Wazuh server. Wazuh indexer can be configured as a single-node or multi-node cluster, providing scalability and high availability. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html
```

## Package digital signature 🟢 

The package is signed and verified.

```shellsession
[root@fedora wazuh-indexer]# rpm --import https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH && rpm -Kv /etc/wazuh-indexer/wazuh-indexer-4.6.0-1.x86_64.rpm
/etc/wazuh-indexer/wazuh-indexer-4.6.0-1.x86_64.rpm:
    Header V3 RSA/SHA256 Signature, key ID 29111145: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V3 RSA/SHA256 Signature, key ID 29111145: OK
    MD5 digest: OK
[root@fedora wazuh-indexer]#
```

**Comment by Ifex370** [comment]
# Wazuh indexer installed files location, size and permissions 🟢 

Everything seems fine but I don't know this component in depth.

[wazuh-indexer-4.6.0 package files](https://github.com/wazuh/wazuh/files/12568129/wazuh-indexer-4.6.0-rc1.txt)

**Comment by Ifex370** [comment]
# Wazuh indexer installation footprint 🟢 

No evidence of the Wazuh Dashboard installer breaking the operating system was found.

In addition to some manual checks, no files with changed ownership could be found. 

```shellsession
[root@fedora wazuhifeanyi]# find /etc -user wazuh-indexer -not -regex ".*wazuh\-indexer.*" -name "*"
find /usr -user wazuh-indexer -not -regex ".*wazuh\-indexer.*" -name "*"
find /var -user wazuh-indexer -not -regex ".*wazuh\-indexer.*" -name "*"
find /bin -user wazuh-indexer -not -regex ".*wazuh\-indexer.*" -name "*"
find /etc -group wazuh-indexer -not -regex ".*wazuh\-indexer.*" -name "*"
find /usr -group wazuh-indexer -not -regex ".*wazuh\-indexer.*" -name "*"
find /var -group wazuh-indexer -not -regex ".*wazuh\-indexer.*" -name "*"
find /bin -group wazuh-indexer -not -regex ".*wazuh\-indexer.*" -name "*"
[root@fedora wazuhifeanyi]# 
```

**Comment by Ifex370** [comment]
# Wazuh indexer installed service 🟢 

The service was correctly installed, enabled and started.

```shellsession
[root@fedora wazuhifeanyi]# 
[root@fedora wazuhifeanyi]# systemctl status wazuh-indexer
● wazuh-indexer.service - Wazuh-indexer
     Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; preset: disabled)
     Active: active (running) since Fri 2023-09-08 17:23:58 WAT; 1 day 19h ago
       Docs: https://documentation.wazuh.com
   Main PID: 7971 (java)
      Tasks: 62 (limit: 4652)
     Memory: 705.1M
        CPU: 18min 19.834s
     CGroup: /system.slice/wazuh-indexer.service
             └─7971 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.c>

Sep 10 00:00:17 fedora systemd-entrypoint[7971]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelH>
Sep 10 00:00:17 fedora systemd-entrypoint[7971]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.ja>
Sep 10 00:00:17 fedora systemd-entrypoint[7971]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteCha>
Sep 10 00:00:17 fedora systemd-entrypoint[7971]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
Sep 10 00:00:17 fedora systemd-entrypoint[7971]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
Sep 10 00:00:17 fedora systemd-entrypoint[7971]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)

[root@fedora wazuhifeanyi]# 
[root@fedora wazuhifeanyi]# systemctl is-enabled wazuh-indexer
enabled
[root@fedora wazuhifeanyi]# 
[root@fedora wazuhifeanyi]# systemctl cat wazuh-indexer.service
# /usr/lib/systemd/system/wazuh-indexer.service
[Unit]
Description=Wazuh-indexer
Documentation=https://documentation.wazuh.com
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
RuntimeDirectory=wazuh-indexer
PrivateTmp=yes
Environment=OPENSEARCH_HOME=/usr/share/wazuh-indexer
Environment=OPENSEARCH_PATH_CONF=/etc/wazuh-indexer
Environment=PID_DIR=/run/wazuh-indexer
Environment=OPENSEARCH_SD_NOTIFY=true
EnvironmentFile=-/etc/sysconfig/wazuh-indexer

WorkingDirectory=/usr/share/wazuh-indexer

User=wazuh-indexer
Group=wazuh-indexer

ExecStart=/usr/share/wazuh-indexer/bin/systemd-entrypoint -p ${PID_DIR}/wazuh-indexer.pid --quiet

# StandardOutput is configured to redirect to journalctl since
# some error messages may be logged in standard output before
# wazuh-indexer logging system is initialized. Elasticsearch
# stores its logs in /var/log/wazuh-indexer and does not use
# journalctl by default. If you also want to enable journalctl
# logging, you can simply remove the "quiet" option from ExecStart.
StandardOutput=journal
StandardError=inherit

# Specifies the maximum file descriptor number that can be opened by this process
LimitNOFILE=65535

# Specifies the maximum number of processes
LimitNPROC=4096

# Specifies the maximum size of virtual memory
LimitAS=infinity

# Specifies the maximum file size
LimitFSIZE=infinity

# Disable timeout logic and wait until process is stopped
TimeoutStopSec=0

# SIGTERM signal is used to stop the Java process
KillSignal=SIGTERM

# Send the signal only to the JVM rather than its control group
KillMode=process

# Java process is never killed
SendSIGKILL=no

# When a JVM receives a SIGTERM signal it exits with code 143
SuccessExitStatus=143

# Allow a slow startup before the systemd notifier module kicks in to extend the timeout
TimeoutStartSec=180

[Install]
WantedBy=multi-user.target

[root@fedora wazuhifeanyi]#

```

**Comment by Ifex370** [comment]
# Wazuh indexer logs when installed 🟢 

No error was reported.

```shellsession
[root@fedora wazuhifeanyi]#

EL-37 - Wazuh                                                             2.6 kB/s | 3.4 kB     00:01    
Dependencies resolved.
==========================================================================================================
 Package                       Architecture           Version                 Repository             Size
==========================================================================================================
Installing:
 wazuh-indexer                 x86_64                 4.6.0-1                 wazuh                 673 M

Transaction Summary
==========================================================================================================
Install  1 Package

Total download size: 673 M
Installed size: 930 M
Downloading Packages:
wazuh-indexer-4.6.0-1.x86_64.rpm                                          1.5 MB/s | 673 MB     07:23    
----------------------------------------------------------------------------------------------------------
Total                                                                     1.5 MB/s | 673 MB     07:23     
EL-37 - Wazuh                                                             2.4 kB/s | 3.1 kB     00:01    
Importing GPG key 0x29111145:
 Userid     : "Wazuh.com (Wazuh Signing Key) <support@wazuh.com>"
 Fingerprint: 0DCF CA55 47B1 9D2A 6099 5060 96B3 EE5F 2911 1145
 From       : https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                  1/1 
  Running scriptlet: wazuh-indexer-4.6.0-1.x86_64                                                     1/1 
  Installing       : wazuh-indexer-4.6.0-1.x86_64 [==========================                       ] 1/1

  Installing       : wazuh-indexer-4.6.0-1.x86_64 [=======================================          ] 1/1
  Installing       : wazuh-indexer-4.6.0-1.x86_64 [========================================         ] 1/1
  Installing       : wazuh-indexer-4.6.0-1.x86_64                                                     1/1 
  Running scriptlet: wazuh-indexer-4.6.0-1.x86_64                                                     1/1 
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore

  Verifying        : wazuh-indexer-4.6.0-1.x86_64                                                     1/1 

Installed:
  wazuh-indexer-4.6.0-1.x86_64                                                                            

Complete! 

```

**Comment by Ifex370** [comment]
# Wazuh indexer templates and indices created 🔴 

## Created indices

The Wazuh indexer service refused to start, hence could not connect

```shellsession
[wazuhifeanyi@fedora ~]$ curl -u admin:admin -k https://192.168.56.139:9200/_cat/indices?pretty
curl: (7) Failed to connect to 192.168.56.139 port 9200 after 0 ms: Connection refused
[wazuhifeanyi@fedora ~]$
```

## Created templates

```shellsession
[wazuhifeanyi@fedora ~]$ curl -u admin:admin -k https://192.168.56.139:9200/_cat/templates?pretty
curl: (7) Failed to connect to 192.168.56.139 port 9200 after 0 ms: Connection refused
[wazuhifeanyi@fedora ~]$  
```

**Comment by Ifex370** [comment]
# Wazuh indexer configuration 🟢 

## `opensearch.yml` file

```shellsession
[root@fedora wazuhifeanyi]# cat /etc/wazuh-indexer/opensearch.yml
network.host: "192.168.56.139"
node.name: "node-1"
cluster.initial_master_nodes:
- "node-1"
#- "node-2"
#- "node-3"
cluster.name: "wazuh-cluster"
#discovery.seed_hosts:
#  - "node-1-ip"
#  - "node-2-ip"
#  - "node-3-ip"
node.max_local_storage_nodes: "3"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

### Option to allow Filebeat-oss 7.10.2 to work ###
compatibility.override_main_response_version: true
[root@fedora wazuhifeanyi]# 

```

## Shards

```shellsession
[root@fedora wazuhifeanyi]# curl -u admin:${PASSWORD} -k https://192.168.56.139:9200/_cat/shards?v=true
curl: (7) Failed to connect to 192.168.56.139 port 9200 after 0 ms: Connection refused
[root@fedora wazuhifeanyi]#
```

**Comment by Ifex370** [comment]
# Wazuh indexer cluster node communication and configuration 🔴 

## Configuration

```shellsession
[root@fedora wazuhifeanyi]# curl -u admin:admin -k https://192.168.56.139:9200/_nodes?pretty
curl: (7) Failed to connect to 192.168.56.139 port 9200 after 0 ms: Connection refused
[root@fedora wazuhifeanyi]# 
```

<details>

<summary>Endpoint response</summary>

```shellsession
[root@fedora wazuhifeanyi]# curl -u admin:admin -k https://192.168.56.139:9200/_nodes?pretty
curl: (7) Failed to connect to 192.168.56.139 port 9200 after 0 ms: Connection refused
[root@fedora wazuhifeanyi]# 
```

</details>

## Nodes state

```shellsession
[root@fedora wazuhifeanyi]# curl -u admin:admin -k https://192.168.56.139:9200/_cluster/state/nodes?pretty
curl: (7) Failed to connect to 192.168.56.139 port 9200 after 0 ms: Connection refused
[root@fedora wazuhifeanyi]# 
```

**Comment by Ifex370** [comment]
# Wazuh indexer cluster status 🔴 

```shellsession
[root@fedora wazuhifeanyi]# curl -u admin:admin -k https://192.168.56.139:9200/_cluster/health?pretty
curl: (7) Failed to connect to 192.168.56.139 port 9200 after 0 ms: Connection refused
[root@fedora wazuhifeanyi]# 
```

**Comment by Ifex370** [comment]
# Wazuh indexer packages uninstallation procedure 🟢 

```shellsession
[root@fedora wazuhifeanyi]# yum remove wazuh-indexer
systemctl status wazuh-indexer
rpm -qa | grep wazuh
No match for argument: wazuh-indexer
No packages marked for removal.
Dependencies resolved.
Nothing to do.
Complete!
× wazuh-indexer.service
     Loaded: not-found (Reason: Unit wazuh-indexer.service not found.)
     Active: failed (Result: exit-code) since Sun 2023-09-10 15:22:29 WAT; 11min ago
   Main PID: 12562 (code=exited, status=1/FAILURE)
        CPU: 11.318s

Sep 10 15:22:29 fedora systemd-entrypoint[12562]:         at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
Sep 10 15:22:29 fedora systemd-entrypoint[12562]:         at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin>
Sep 10 15:22:29 fedora systemd-entrypoint[12562]:         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native>
Sep 10 15:22:29 fedora systemd-entrypoint[12562]:         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeC>
Sep 10 15:22:29 fedora systemd-entrypoint[12562]:         <<<truncated>>>
Sep 10 15:22:29 fedora systemd-entrypoint[12562]: For complete error details, refer to the log at /var/log/wazuh-indexer/wazuh-cluster.log
Sep 10 15:22:29 fedora systemd[1]: wazuh-indexer.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 15:22:29 fedora systemd[1]: wazuh-indexer.service: Failed with result 'exit-code'.
Sep 10 15:22:29 fedora systemd[1]: Failed to start wazuh-indexer.service - Wazuh-indexer.
Sep 10 15:22:29 fedora systemd[1]: wazuh-indexer.service: Consumed 11.318s CPU time.
lines 1-16/16 (END)

```

**Comment by Ifex370** [comment]
# User experience 🔴 

I was not able to perform an agent enrolment after installing the Wazuh agent using the command:

```
cat > /etc/yum.repos.d/wazuh.repo << EOF
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-\$releasever - Wazuh
baseurl=https://packages-dev.wazuh.com/pre-release/yum/
protect=1
EOF

WAZUH_MANAGER="10.0.2.72" yum install wazuh-agent-4.6.0*

systemctl daemon-reload
systemctl enable wazuh-agent
systemctl start wazuh-agent
```

![image](https://github.com/wazuh/wazuh/assets/35229630/8971f9c0-8717-4c13-945d-94a22cb19321)

```
[root@fedora dnf]# systemctl status wazuh-agent
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; preset: disabled)
     Active: active (running) since Sun 2023-09-10 19:09:54 WAT; 3min 10s ago
      Tasks: 25 (limit: 4652)
     Memory: 17.2M
        CPU: 1.396s
     CGroup: /system.slice/wazuh-agent.service
             ├─4863 /var/ossec/bin/wazuh-execd
             ├─4883 /var/ossec/bin/wazuh-agentd
             ├─4910 /var/ossec/bin/wazuh-syscheckd
             ├─4924 /var/ossec/bin/wazuh-logcollector
             └─4943 /var/ossec/bin/wazuh-modulesd

Sep 10 19:09:47 fedora systemd[1]: Starting wazuh-agent.service - Wazuh agent...
Sep 10 19:09:47 fedora env[4833]: Starting Wazuh v4.6.0...
Sep 10 19:09:48 fedora env[4833]: Started wazuh-execd...
Sep 10 19:09:49 fedora env[4833]: Started wazuh-agentd...
Sep 10 19:09:50 fedora env[4833]: Started wazuh-syscheckd...
Sep 10 19:09:51 fedora env[4833]: Started wazuh-logcollector...
Sep 10 19:09:52 fedora env[4833]: Started wazuh-modulesd...
Sep 10 19:09:54 fedora env[4833]: Completed.
Sep 10 19:09:54 fedora systemd[1]: Started wazuh-agent.service - Wazuh agent.
lines 6-22/22 (END)
```

I also tried with previous agent versions, and another operating system (Ubuntu). I'm not sure where this issue comes from as the Wazuh manager listens for connections on port 1514 and 1515.

I also ensured to disable all firewalls.

** From the Wazuh Agent

```
[root@fedora dnf]# telnet 192.168.56.138 1514
Trying 192.168.56.138...
Connected to 192.168.56.138.
Escape character is '^]'.
^C
Connection closed by foreign host.
[root@fedora dnf]# 
[root@fedora dnf]# 
[root@fedora dnf]# telnet 192.168.56.138 1515
Trying 192.168.56.138...
Connected to 192.168.56.138.
Escape character is '^]'.
^CConnection closed by foreign host.
[root@fedora dnf]#

```

Wazuh Manager:

```
[root@fedora etc]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      677/systemd-resolve 
tcp        0      0 127.0.0.1:38515         0.0.0.0:*               LISTEN      4574/node           
tcp        0      0 127.0.0.54:53           0.0.0.0:*               LISTEN      677/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3953/sshd: /usr/sbi 
tcp        0      0 127.0.0.1:37055         0.0.0.0:*               LISTEN      4779/code-8b617bd08 
tcp        0      0 0.0.0.0:55000           0.0.0.0:*               LISTEN      8751/python3        
tcp        0      0 0.0.0.0:1514            0.0.0.0:*               LISTEN      8943/wazuh-remoted  
tcp        0      0 0.0.0.0:1515            0.0.0.0:*               LISTEN      8801/wazuh-authd    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      814/cupsd           
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      677/systemd-resolve 
tcp6       0      0 :::22                   :::*                    LISTEN      3953/sshd: /usr/sbi 
tcp6       0      0 ::1:631                 :::*                    LISTEN      814/cupsd           
tcp6       0      0 :::5355                 :::*                    LISTEN      677/systemd-resolve 
udp        0      0 127.0.0.54:53           0.0.0.0:*                           677/systemd-resolve 
udp        0      0 127.0.0.53:53           0.0.0.0:*                           677/systemd-resolve 
udp        0      0 127.0.0.1:323           0.0.0.0:*                           782/chronyd         
udp        0      0 0.0.0.0:47735           0.0.0.0:*                           708/avahi-daemon: r 
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           708/avahi-daemon: r 
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           677/systemd-resolve 
udp6       0      0 ::1:323                 :::*                                782/chronyd         
udp6       0      0 :::55646                :::*                                708/avahi-daemon: r 
udp6       0      0 :::5353                 :::*                                708/avahi-daemon: r 
udp6       0      0 :::5355                 :::*                                677/systemd-resolve 
[root@fedora etc]# 
```

**Comment by Ifex370** [comment]
All comments have been moved to the main issue: https://github.com/wazuh/wazuh/issues/18836
