### ISSUE TITLE
Double reading in the ms-graph configuration module

### ISSUE THREAD

**Issue by lsayanes** [wazuh/wazuh#19034]
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 4.8.0 | wazuh-modulesd | Manager |  Linux |

Working on this  [issue](https://github.com/wazuh/wazuh/issues/18202) I found a strange behavior when reading the configuration section of ms-graph, it is read twice and therefore it is allocated twice.

In `src/config/wmodules-ms-graph.c` I have added a minfo:
![Captura de pantalla 2023-09-15 a la(s) 17 50 18](https://github.com/wazuh/wazuh/assets/68856625/92e6e4b5-70ad-4027-ab26-883e232ab9ca)

**ossec.conf:**
```
 <ms-graph>
    <enabled>yes</enabled>
    <only_future_events>no</only_future_events>
    <curl_max_size>10M</curl_max_size>
    <run_on_start>no</run_on_start>
    <interval>1m</interval>
    <version>v1.0</version>
    <api_auth>
      <tenant_id>tenant_1</tenant_id>
      <client_id>client_1</client_id>
      <secret_value>secret_1</secret_value>
      <api_type>global</api_type>
    </api_auth>
    <resource>
      <name>auditLogs</name>
      <relationship>signIns</relationship>
    </resource>
  </ms-graph>
```

**Output:**
![Captura de pantalla 2023-09-15 a la(s) 17 52 51](https://github.com/wazuh/wazuh/assets/68856625/6251b19f-88c8-4f30-abd1-bc9b82210b9b)

**Attached log:**
[ossec.log](https://github.com/wazuh/wazuh/files/12623712/ossec.log)

**Comment by lsayanes** [comment]
I have tried again by setting `wazuh_modules.debug=2` and I see that the `wm_ms_graph_read()` function is called twice, I attach the log:
[ossec.log](https://github.com/wazuh/wazuh/files/12676679/ossec.log)

**Comment by lsayanes** [comment]
### Two instances of the modulesd daemons
As far as I have been able to verify, the `ms-graph` configuration is not being read twice, but rather two instances of the `modulesd` daemons are created (also `syscheckd`)

According to the backtrace in **GDB**, function calls for reading the configuration are executed only once:
```
(gdb) bt
#0  Read_MS_Graph (xml=0xfffffffff0e8, node=0xfffff6c15360, d1=0xaaaaaac682c0 <wmodules>) at config/wmodules-config.c:678
#1  0x0000aaaaaaad5354 in read_main_elements (xml=0xfffffffff0e8, modules=65536, node=0xfffff6c7a3c0, d1=0xaaaaaac682c0 <wmodules>, d2=0xfffffffff1e4) at config/config.c:263
#2  0x0000aaaaaaad5724 in ReadConfig (modules=65536, cfgfile=0xaaaaaabd6940 "etc/ossec.conf", d1=0xaaaaaac682c0 <wmodules>, d2=0xfffffffff1e4) at config/config.c:342
#3  0x0000aaaaaaab4a5c in wm_config () at wazuh_modules/wmodules.c:77
#4  0x0000aaaaaaab271c in wm_setup () at wazuh_modules/main.c:134
#5  0x0000aaaaaaab24c8 in main (argc=1, argv=0xfffffffff498) at wazuh_modules/main.c:82

```

Then I detected that two instances of these daemons were being launched. 
For this I have added a particular log function:

```
static int ms_count_read = 0;

void logcount(const char *name)
{

	char str[1024];
    
        sleep(1);
        sprintf(str, "/home/parallels/ms-log-%li.s", time(NULL));

	FILE *p = fopen(str, "w");
	if(p)
	{
		fprintf(p, "module::%s\tms_count_read:%d (address:%p)\n", name, ms_count_read, &ms_count_read);
		fclose(p);
	}

	ms_count_read++;
}
```
The purpose of this function was to log to a different file each time a configuration was read, increment the counter and save its address for verification that everything belonged to the same instance:

**sleep(1):**
	sleep of 1 second so that the same file is not overwritten

**sprintf(str, "/home/parallels/ms-log-%li.s", time(NULL));**
	I create in a specific location a .s file with time as identifier

**fprintf(p, "module::%s\tms_count_read:%d (address:%p)\n", name, ms_count_read, &ms_count_read);**
	I print the name of the module, the counter and its address


### The proof
I have placed the following calls:

At the end of `wm_ms_graph_read`:
```
       ...
	
       if (ms_graph->num_resources == 0) {
		merror(XML_NO_ELEM, XML_RESOURCE);
		return OS_NOTFOUND;
	}
logcount("ms-graph");  

	return OS_SUCCESS;
}
```



At the end of `Read_Vuln`:

```
   ...
    }

    wm_vuldet_enable_rhel_json_feed(updates);

    vuldet->flags.update = vuldet->flags.update | run_update;
logcount("vuln-detector");
    return 0;
}

```

At the end of `Read_Syscheck`:

```
            }
        } else if (!syscheck->allow_remote_prefilter_cmd) {
            mwarn(FIM_WARN_ALLOW_PREFILTER, prefilter_cmd, xml_allow_remote_prefilter_cmd);
        }
    }
logcount("syscheckd");
    return (0);
}

```

### Result:
![Captura de pantalla 2023-09-27 a la(s) 15 58 29](https://github.com/wazuh/wazuh/assets/68856625/1fb4af24-e518-4c60-ade4-c3e32c46db48)

```
parallels@ubuntu-22-04:~$ cat ms-log-16958410*
module::syscheckd	ms_count_read:0 (address:0xaaaac5b0bffc)
module::vuln-detector	ms_count_read:0 (address:0xaaaab26c62dc)
module::ms-graph	ms_count_read:1 (address:0xaaaab26c62dc)
module::syscheckd	ms_count_read:0 (address:0xaaaae202bffc)
module::vuln-detector	ms_count_read:0 (address:0xaaaade2562dc)
module::ms-graph	ms_count_read:1 (address:0xaaaade2562dc)
```
