### ISSUE TITLE
Wazuh Issue to get most active agent

### ISSUE THREAD

**Issue by sayanTlregtech** [wazuh/wazuh#19573]
I am getting the error 

An error occurred while trying to get the most active agent: 4004 - search_phase_execution_exception:

4004 - search_phase_execution_exception:

And also 

`null_pointer_exception
Cannot invoke "org.opensearch.search.aggregations.InternalAggregations.getSerializedSize()" because "reducePhase.aggregations" is null
Error
    at Fetch._callee3$ (https://wazuh.company.com/45202/bundles/core/core.entry.js:15:584549)
    at tryCatch (https://wazuh.tlregtech.com/45202/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:760622)
    at Generator.invoke [as _invoke] (https://wazuh.company.com/45202/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:764638)
    at Generator.next (https://wazuh.company.com/45202/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:761817)
    at fetch_asyncGeneratorStep (https://wazuh.company.com/45202/bundles/core/core.entry.js:15:577641)
    at _next (https://wazuh.company.com/45202/bundles/core/core.entry.js:15:577957)`

**Comment by Dgb7121** [comment]
Hi

I am also getting this below error.

An error occurred while trying to get the most active agent
4004 - search_phase_execution_exception
