### ISSUE TITLE
Update connexion dependency to the latest stable version

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#19574]
|Component|
|---|
|  Wazuh embedded Python interpreter |

## Description

During the development of #13267, it was concluded that an update on the `connexion` dependency was required to avoid the [deprecation warning messages](https://github.com/wazuh/wazuh/issues/13267#issuecomment-1468587021) consequence of using the version `2.6.0`. At first, the version was bumped to `2.7.0`, but the objective of avoiding near-future updates led to the use of the latest stable version (`2.14.2`) which produced the following error in the AITs:
<details><summary>test_agent_PUT_endpoints</summary>

    ============================= test session starts ==============================
    platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.2.0 -- /usr/bin/python3
    cachedir: .pytest_cache
    metadata: {'Python': '3.10.6', 'Platform': 'Linux-5.19.0-1028-aws-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.2.0'}, 'Plugins': {'asyncio': '0.18.1', 'html': '2.1.1', 'trio': '0.7.0', 'metadata': '3.0.0', 'tavern': '1.23.5', 'aiohttp': '1.0.4'}}
    rootdir: /tmp/Test_integration_endpoints_B3913_test_files/api/test/integration
    configfile: pytest.ini
    plugins: asyncio-0.18.1, html-2.1.1, trio-0.7.0, metadata-3.0.0, tavern-1.23.5, aiohttp-1.0.4
    asyncio: mode=auto
    collecting ... collected 10 items
    
    test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group PASSED           [ 10%]
    test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration FAILED [ 20%]
    test_agent_PUT_endpoints.tavern.yaml::PUT /agents/group/{group_id}/restart PASSED [ 30%]
    test_agent_PUT_endpoints.tavern.yaml::PUT /agents/reconnect PASSED       [ 40%]
    test_agent_PUT_endpoints.tavern.yaml::PUT /agents/restart PASSED         [ 50%]
    test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id} PASSED [ 60%]
    test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/restart PASSED [ 70%]
    test_agent_PUT_endpoints.tavern.yaml::PUT /agents/node/{node_id}/restart PASSED [ 80%]
    test_agent_PUT_endpoints.tavern.yaml::PUT /agents/upgrade PASSED         [ 90%]
    test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom PASSED [100%]
    
    =================================== FAILURES ===================================
    _ /tmp/Test_integration_endpoints_B3913_test_files/api/test/integration/test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration _
    Format variables:
      protocol:s = 'https'
      host:s = 'localhost'
      port:d = '55000'
      test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjk2NTI4MzUzLCJleHAiOjE2OTY1MjkyNTMsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AfpFJLzcq6j9NAD6HQEaBthm7m3aZuql_3qygdcqwNfIPFA0Nm3ywxb5Fll-LQDz3sT5lUnpvuWOgb1BDXZbCtv3ADDZtOHbJTQeq3YR6rAJLtXHmG75GlvA1-Zdit9IkSF96e2uEWy1nn9ZOGIWP8bNp-QxN_bmGFh8bcI5AH_nf5MY'
    
    Source test stage (line 278):
      - name: Try to update configuration using an empty file
        request:
          verify: False
          url: "{protocol:s}://{host:s}:{port:d}/groups/group1/configuration"
          method: PUT
          headers:
            Authorization: "Bearer {test_login_token}"
            content-type: "application/xml"
        response:
          status_code: 400
          json:
            error: 2007
    
    
    
    Formatted stage:
      name: Try to update configuration using an empty file
      request:
        headers:
          Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjk2NTI4MzUzLCJleHAiOjE2OTY1MjkyNTMsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AfpFJLzcq6j9NAD6HQEaBthm7m3aZuql_3qygdcqwNfIPFA0Nm3ywxb5Fll-LQDz3sT5lUnpvuWOgb1BDXZbCtv3ADDZtOHbJTQeq3YR6rAJLtXHmG75GlvA1-Zdit9IkSF96e2uEWy1nn9ZOGIWP8bNp-QxN_bmGFh8bcI5AH_nf5MY
          content-type: application/xml
        method: PUT
        url: 'https://localhost:55000/groups/group1/configuration'
        verify: false
      response:
        json:
          error: 2007
        status_code: 400
    
    Errors:
    E   tavern.util.exceptions.TestFailError: Test 'Try to update configuration using an empty file' failed:
        - Key mismatch: (expected["error"] = '2007' (type = <class 'int'>), actual["error"] = '1112' (type = <class 'int'>))
    ------------------------------ Captured log call -------------------------------
    ERROR    tavern.response.base:base.py:41 Key mismatch: (expected["error"] = '2007' (type = <class 'int'>), actual["error"] = '1112' (type = <class 'int'>))
    Traceback (most recent call last):
      File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
        assert actual_val == expected_val
    AssertionError: assert {'title': 'Bad Request', 'detail': 'Empty files are not supported', 'remediation': 'Please, provide another file', 'dapi_errors': {'master-node': {'error': 'Empty files are not supported'}}, 'error': 1112} == {'error': 2007}
      Differing items:
      {'error': 1112} != {'error': 2007}
      Left contains 4 more items:
      {'dapi_errors': {'master-node': {'error': 'Empty files are not supported'}},
       'detail': 'Empty files are not supported',
       'remediation': 'Please, provide another file',
       'title': 'Bad Request'}
      Full diff:
        {
      +  'dapi_errors': {'master-node': {'error': 'Empty files are not supported'}},
      +  'detail': 'Empty files are not supported',
      -  'error': 2007,
      ?            ---
      +  'error': 1112,
      ?           +++
      +  'remediation': 'Please, provide another file',
      +  'title': 'Bad Request',
        }
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
        assert actual_val == expected_val
    AssertionError: assert 1112 == 2007
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/response/base.py", line 97, in recurse_check_key_match
        check_keys_match_recursive(expected_block, block, [], strict)
      File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/util/dict_util.py", line 464, in check_keys_match_recursive
        check_keys_match_recursive(
      File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/util/dict_util.py", line 550, in check_keys_match_recursive
        raise exceptions.KeyMismatchError(
    tavern.util.exceptions.KeyMismatchError: Key mismatch: (expected["error"] = '2007' (type = <class 'int'>), actual["error"] = '1112' (type = <class 'int'>))
    =============================== warnings summary ===============================
    ../../../../../home/ubuntu/.local/lib/python3.10/site-packages/_pytest/nodes.py:642
      /home/ubuntu/.local/lib/python3.10/site-packages/_pytest/nodes.py:642: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
      See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
        return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)
    
    test_agent_PUT_endpoints.tavern.yaml: 10 warnings
      <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
    
    test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration
      /home/ubuntu/.local/lib/python3.10/site-packages/pytest_trio/plugin.py:62: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
        if issubclass(call.excinfo.type, trio.MultiError):
    
    -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
    - generated html file: file:///tmp/Test_integration_endpoints_B3913_test_files/api/test/integration/Test_integration_endpoints_B3913_test_agent_PUT_endpoints.html -
    =========================== short test summary info ============================
    FAILED test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration
    ============= 1 failed, 9 passed, 12 warnings in 823.19s (0:13:43) =============

</details>

The analysis of the error concluded that the used `connexion` version handles empty bodies differently than the previously used versions, so this issue aims to update said dependency as part of the #13265 epic, analyze the behavior change due to the version bump, and modify the related code to avoid similar errors.

> Note: this issue should be merged to the epic branch before #13267.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
# Issue Update

The dependency was updated in the `requirements.txt` file for the epic branch as mentioned [here](https://github.com/wazuh/wazuh/issues/13265#issuecomment-1746843919). The necessary changes were made in the controller functions that receive `body` as a parameter and in the AIT corresponding to the `test_agent_PUT_endpoints.tavern.yaml` test file.

**Comment by fdalmaup** [comment]
# Issue Update

Every API endpoint Integration Test has been run, here are the results:

## Test report
[archive.zip](https://github.com/wazuh/wazuh/files/12874330/archive.zip)


## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_DELETE_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_GET_endpoints.tavern.yaml | 93 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_POST_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_PUT_endpoints.tavern.yaml | 10 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cluster_endpoints.tavern.yaml | 49 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_decoder_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_default_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_experimental_endpoints.tavern.yaml | 11 | 0 | 0 | 0 | 1 |  | :red_circle: |
| test_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_manager_endpoints.tavern.yaml | 32 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_agent_endpoints.tavern.yaml | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cluster_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 7 |  | :red_circle: |
| test_rbac_black_decoder_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_experimental_endpoints.tavern.yaml | 11 | 0 | 0 | 0 | 1 |  | :red_circle: |
| test_rbac_black_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_manager_endpoints.tavern.yaml | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_rule_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_security_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_syscheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_syscollector_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_task_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_vulnerability_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_webhook_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_agent_endpoints.tavern.yaml | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_all_endpoints.tavern.yaml | 167 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_cluster_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 7 |  | :red_circle: |
| test_rbac_white_decoder_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_experimental_endpoints.tavern.yaml | 11 | 0 | 0 | 0 | 1 |  | :red_circle: |
| test_rbac_white_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_manager_endpoints.tavern.yaml | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_rule_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_security_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_syscheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_syscollector_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_task_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_vulnerability_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_webhook_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rule_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_sca_endpoints.tavern.yaml | 45 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_DELETE_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_GET_endpoints.tavern.yaml | 11 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_POST_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_PUT_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_syscheck_endpoints.tavern.yaml | 34 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_syscollector_endpoints.tavern.yaml | 157 | 0 | 0 | 0 | 2 |  | :red_circle: |
| test_task_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_vulnerability_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |

The errors found are not related to the modifications made or the update of the `connexion` version.

**Comment by fdalmaup** [comment]
# Issue Update

## `test_api` results
The `wazuh/tests/integration/test_api` tests were run successfully, and no errors were found nor modifications were needed:

```
/wazuh/tests/integration# pytest test_api/
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.0.0, testinfra-5.0.0, html-3.1.1
collected 61 items                                                                                                                                                                                                

test_api/test_config/test_DOS_blocking_system/test_DOS_blocking_system.py .                                                                                                                                 [  1%]
test_api/test_config/test_bruteforce_blocking_system/test_bruteforce_blocking_system.py .                                                                                                                   [  3%]
test_api/test_config/test_cache/test_cache.py ..                                                                                                                                                            [  6%]
test_api/test_config/test_cors/test_cors.py x.                                                                                                                                                              [  9%]
test_api/test_config/test_drop_privileges/test_drop_privileges.py ..                                                                                                                                        [ 13%]
test_api/test_config/test_experimental_features/test_experimental_features.py ..                                                                                                                            [ 16%]
test_api/test_config/test_host_port/test_host_port.py ....                                                                                                                                                  [ 22%]
test_api/test_config/test_https/test_https.py ..                                                                                                                                                            [ 26%]
test_api/test_config/test_jwt_token_exp_timeout/test_jwt_token_exp_timeout.py ..                                                                                                                            [ 29%]
test_api/test_config/test_logs/test_logs_format.py ........                                                                                                                                                 [ 42%]
test_api/test_config/test_max_upload_size/test_max_upload_size.py ...                                                                                                                                       [ 47%]
test_api/test_config/test_rbac/test_rbac_mode.py ..                                                                                                                                                         [ 50%]
test_api/test_config/test_request_timeout/test_request_timeout.py .                                                                                                                                         [ 52%]
test_api/test_middlewares/test_response_postprocessing.py ....                                                                                                                                              [ 59%]
test_api/test_middlewares/test_set_secure_headers.py .                                                                                                                                                      [ 60%]
test_api/test_rbac/test_add_old_resource.py ....                                                                                                                                                            [ 67%]
test_api/test_rbac/test_manage_admin_resource.py .......                                                                                                                                                    [ 78%]
test_api/test_rbac/test_policy_position.py .                                                                                                                                                                [ 80%]
test_api/test_rbac/test_remove_resource.py ....                                                                                                                                                             [ 86%]
test_api/test_rbac/test_remove_resources_relation.py ...                                                                                                                                                    [ 91%]
test_api/test_statistics/test_statistics_format.py .....                                                                                                                                                    [100%]

==================================================================================== 60 passed, 1 xfailed in 548.06s (0:09:08) ====================================================================================
```

**Comment by fdalmaup** [comment]
# Issue Update

Rebased the dev branch after the creation of the `4.8.0` branch and the fix made in #19756 and executed the involved tests:

<details><summary>test_rbac_white_cluster_endpoints.tavern.yaml</summary>

```console
pytest test_rbac_white_cluster_endpoints.tavern.yaml
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-0.13.1
rootdir: /home/fdalmau/git/wazuh/api/test/integration
configfile: pytest.ini
plugins: aiohttp-1.0.4, trio-0.7.0, metadata-2.0.2, tavern-1.23.5, asyncio-0.18.1, html-2.1.1
asyncio: mode=auto
collected 19 items                                                                                                                                                                             

test_rbac_white_cluster_endpoints.tavern.yaml ...................                                                                                                                        [100%]

======================================================================================= warnings summary =======================================================================================
../../../../../venv/integrationtest-env-3.10/lib/python3.10/site-packages/_pytest/nodes.py:642
  /home/fdalmau/venv/integrationtest-env-3.10/lib/python3.10/site-packages/_pytest/nodes.py:642: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)

test_rbac_white_cluster_endpoints.tavern.yaml: 19 warnings
  <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================= 19 passed, 20 warnings in 1717.38s (0:28:37) =========================================================================

```

</details>


<details><summary>test_rbac_black_cluster_endpoints.tavern.yaml</summary>

```console
pytest test_rbac_black_cluster_endpoints.tavern.yaml
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-0.13.1
rootdir: /home/fdalmau/git/wazuh/api/test/integration
configfile: pytest.ini
plugins: aiohttp-1.0.4, trio-0.7.0, metadata-2.0.2, tavern-1.23.5, asyncio-0.18.1, html-2.1.1
asyncio: mode=auto
collected 19 items                                                                                                                                                                             

test_rbac_black_cluster_endpoints.tavern.yaml ...................                                                                                                                        [100%]

======================================================================================= warnings summary =======================================================================================
../../../../../venv/integrationtest-env-3.10/lib/python3.10/site-packages/_pytest/nodes.py:642
  /home/fdalmau/venv/integrationtest-env-3.10/lib/python3.10/site-packages/_pytest/nodes.py:642: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)

test_rbac_black_cluster_endpoints.tavern.yaml: 19 warnings
  <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================= 19 passed, 20 warnings in 1228.76s (0:20:28) =========================================================================

```

</details>
