### ISSUE TITLE
Fix Syscollector Failure in API Integration Tests

### ISSUE THREAD

**Issue by javiersanchz** [wazuh/wazuh#19704]
|Wazuh version|Component|
|---|---|
| 4.7.0 | API |

## Description

 - During the release of API integration tests for Release 4.7.0 - Alpha 1, an error has occurred in the tests `test_syscollector_endpoints.tavern.yaml `and `test_experimental_endpoints.tavern.yaml` as seen here https://github.com/wazuh/wazuh/issues/19672#issuecomment-1765993625. 
 - It appears that both originate from `Syscollector` (`GET /syscollector/{agent_id}/packages`). When manually testing the endpoint, it works perfectly, indicating that the issue might be more related to the environment causing it to break.

 - Pasting the endpoint from the environment does not fail:
![image](https://github.com/wazuh/wazuh/assets/96108386/86527a61-8aa2-44f5-8c02-ca085c996acb)

 - It seems to be more related to a precondition that could be causing the failure.

Note:

 We were checking if the error could be related to https://github.com/wazuh/wazuh/issues/19612, but these errors occur when using the local `requirements-dev.txt` for `4.7.0` or `4.8.0` (due to the updated dependencies) or when running the AITs pipeline in `4.8.0` (due to the updated AMI containing the same dependencies). The errors described here are not related to that.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

I had an issue when trying to run the tests locally, the test timed out because the containers weren't initiated when using the `--nobuild` flag.

```console
...
ERROR test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hotfixes - subprocess.CalledProcessError: Command 'docker inspect env_wazuh-master_1 -f '{{json .State.Health.Status}}'' returned non-zero exit status 1.
================================================================== 161 warnings, 159 errors in 64.67s (0:01:04) ==================================================================
```

Running it without the flag worked and there was one failed case.

<details><summary>test_syscollector_endpoints.tavern.yaml</summary>

```console
(venv) gasti@pop-os:~/work/wazuh/api/test/integration$ pytest -vv test_syscollector_endpoints.tavern.yaml
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /home/gasti/work/wazuh/venv/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-6.2.0-76060200-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.0.0'}, 'Plugins': {'asyncio': '0.18.1', 'tavern': '1.23.5', 'trio': '0.7.0', 'html': '2.1.1', 'aiohttp': '1.0.4', 'metadata': '3.0.0'}}
rootdir: /home/gasti/work/wazuh/api/test/integration
configfile: pytest.ini
plugins: asyncio-0.18.1, tavern-1.23.5, trio-0.7.0, html-2.1.1, aiohttp-1.0.4, metadata-3.0.0
asyncio: mode=auto
collected 159 items                                                                                                                                                              

test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os PASSED                                                                                            [  0%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[architecture] PASSED                                                                     [  1%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[hostname] PASSED                                                                         [  1%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.codename] PASSED                                                                      [  2%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.major] PASSED                                                                         [  3%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.minor] PASSED                                                                         [  3%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.name] PASSED                                                                          [  4%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.platform] PASSED                                                                      [  5%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.version] PASSED                                                                       [  5%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[release] PASSED                                                                          [  6%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[scan.id] PASSED                                                                          [  6%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[scan.time] PASSED                                                                        [  7%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[sysname] PASSED                                                                          [  8%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[version] PASSED                                                                          [  8%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware PASSED                                                                                      [  9%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[cpu.cores] PASSED                                                                  [ 10%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[cpu.mhz] PASSED                                                                    [ 10%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[cpu.name] PASSED                                                                   [ 11%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[ram.free] PASSED                                                                   [ 11%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[ram.total] PASSED                                                                  [ 12%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[ram.usage] PASSED                                                                  [ 13%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[scan.id] PASSED                                                                    [ 13%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[scan.time] PASSED                                                                  [ 14%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages FAILED                                                                                      [ 15%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[architecture] PASSED                                                               [ 15%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[description] PASSED                                                                [ 16%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[format] PASSED                                                                     [ 16%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[name] PASSED                                                                       [ 17%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[priority] PASSED                                                                   [ 18%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[scan.id] PASSED                                                                    [ 18%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[scan.time] PASSED                                                                  [ 19%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[section] PASSED                                                                    [ 20%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[size] PASSED                                                                       [ 20%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[vendor] PASSED                                                                     [ 21%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages?{select}[version] PASSED                                                                    [ 22%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes PASSED                                                                                     [ 22%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[argvs] PASSED                                                                [ 23%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[cmd] PASSED                                                                  [ 23%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[egroup] PASSED                                                               [ 24%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[euser] PASSED                                                                [ 25%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[fgroup] PASSED                                                               [ 25%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[name] PASSED                                                                 [ 26%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[nice] PASSED                                                                 [ 27%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[nlwp] PASSED                                                                 [ 27%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[pgrp] PASSED                                                                 [ 28%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[pid] PASSED                                                                  [ 28%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[ppid] PASSED                                                                 [ 29%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[priority] PASSED                                                             [ 30%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[processor] PASSED                                                            [ 30%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[resident] PASSED                                                             [ 31%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[rgroup] PASSED                                                               [ 32%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[ruser] PASSED                                                                [ 32%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[scan.id] PASSED                                                              [ 33%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[session] PASSED                                                              [ 33%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[sgroup] PASSED                                                               [ 34%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[share] PASSED                                                                [ 35%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[size] PASSED                                                                 [ 35%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[start_time] PASSED                                                           [ 36%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[state] PASSED                                                                [ 37%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[stime] PASSED                                                                [ 37%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[suser] PASSED                                                                [ 38%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[tgid] PASSED                                                                 [ 38%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[tty] PASSED                                                                  [ 39%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[utime] PASSED                                                                [ 40%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/processes?{sort,select}[vm_size] PASSED                                                              [ 40%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/ports PASSED                                                                                         [ 41%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[inode] PASSED                                                                     [ 42%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[local.ip] PASSED                                                                  [ 42%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[local.port] PASSED                                                                [ 43%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[protocol] PASSED                                                                  [ 44%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[remote.ip] PASSED                                                                 [ 44%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[remote.port] PASSED                                                               [ 45%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[rx_queue] PASSED                                                                  [ 45%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[scan.id] PASSED                                                                   [ 46%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[scan.time] PASSED                                                                 [ 47%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[state] PASSED                                                                     [ 47%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/port?{sort,select}[tx_queue] PASSED                                                                  [ 48%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr PASSED                                                                                       [ 49%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[address] PASSED                                                                [ 49%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[broadcast] PASSED                                                              [ 50%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[iface] PASSED                                                                  [ 50%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[netmask] PASSED                                                                [ 51%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[proto] PASSED                                                                  [ 52%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[scan.id] PASSED                                                                [ 52%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto PASSED                                                                                      [ 53%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[dhcp] PASSED                                                                  [ 54%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[gateway] PASSED                                                               [ 54%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[iface] PASSED                                                                 [ 55%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[scan.id] PASSED                                                               [ 55%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[type] PASSED                                                                  [ 56%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface PASSED                                                                                      [ 57%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[mac] PASSED                                                                   [ 57%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[mtu] PASSED                                                                   [ 58%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[name] PASSED                                                                  [ 59%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[rx.bytes] PASSED                                                              [ 59%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[rx.dropped] PASSED                                                            [ 60%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[rx.errors] PASSED                                                             [ 61%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[rx.packets] PASSED                                                            [ 61%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[scan.id] PASSED                                                               [ 62%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[scan.time] PASSED                                                             [ 62%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[state] PASSED                                                                 [ 63%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[tx.bytes] PASSED                                                              [ 64%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[tx.dropped] PASSED                                                            [ 64%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[tx.errors] PASSED                                                             [ 65%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[tx.packets] PASSED                                                            [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[type] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os PASSED                                                                                            [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[architecture] PASSED                                                                     [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[hostname] PASSED                                                                         [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.codename] PASSED                                                                      [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.major] PASSED                                                                         [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.minor] PASSED                                                                         [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.name] PASSED                                                                          [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.platform] PASSED                                                                      [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[os.version] PASSED                                                                       [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[release] PASSED                                                                          [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[scan.id] PASSED                                                                          [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[scan.time] PASSED                                                                        [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[sysname] PASSED                                                                          [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/os?{select}[version] PASSED                                                                          [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware PASSED                                                                                      [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[cpu.cores] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[cpu.mhz] PASSED                                                                    [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[cpu.name] PASSED                                                                   [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[ram.free] PASSED                                                                   [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[ram.total] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[ram.usage] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[scan.id] PASSED                                                                    [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hardware?{select}[scan.time] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr PASSED                                                                                       [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[address] PASSED                                                                [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[broadcast] PASSED                                                              [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[iface] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[netmask] PASSED                                                                [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[proto] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netaddr?{sort,select}[scan.id] PASSED                                                                [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto PASSED                                                                                      [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[dhcp] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[gateway] PASSED                                                               [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[iface] PASSED                                                                 [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[scan.id] PASSED                                                               [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netproto?{sort,select}[type] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface PASSED                                                                                      [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[mac] PASSED                                                                   [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[mtu] PASSED                                                                   [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[name] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[rx.bytes] PASSED                                                              [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[rx.dropped] PASSED                                                            [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[rx.errors] PASSED                                                             [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[rx.packets] PASSED                                                            [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[scan.id] PASSED                                                               [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[scan.time] PASSED                                                             [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[state] PASSED                                                                 [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[tx.bytes] PASSED                                                              [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[tx.dropped] PASSED                                                            [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[tx.errors] PASSED                                                             [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[tx.packets] PASSED                                                            [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/netiface?{sort,select}[type] PASSED                                                                  [ 66%]
test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/hotfixes PASSED                                                                                      [ 67%]

==================================================================================== FAILURES ====================================================================================
___________________________ /home/gasti/work/wazuh/api/test/integration/test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages ___________________________
Format variables:

Source test stage (line 355):
  - name: Filter sort
    request:
      verify: False
      <<: *packages_request_003
      params:
        sort: -name
    response:
      verify_response_with:
        - function: tavern_utils:test_sort_response
          extra_kwargs:
            key: "name"
            reverse: true
      status_code: 200


Formatted stage:
  name: Filter sort
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjk3NTc5MDUwLCJleHAiOjE2OTc1Nzk5NTAsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AU2Vw7wBu0mt6O-hYLfYDOkSRNgY4dnOKRnHi7Nn4eykuP7g6Whmr4WSSVQWjMJtfweKHOOCgTsFdIfGH0rtphC3AILhG4RdP8yuDUdqaOnjaxa4Fznz9KO4Kk8JmP7Hkb6N8t6VRE9Q-dILo_PcT5rrTCRAM0XMpNix7SJJnWc5IxZb
    method: GET
    params:
      sort: -name
    url: 'https://localhost:55000/syscollector/003/packages'
    verify: false
  response:
    status_code: 200
    verify_response_with:
    - extra_kwargs:
        key: name
        reverse: true
      function: tavern_utils:test_sort_response

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Filter sort' failed:
    - Status code was 500, expected 200
    - Error calling validate function '<function test_sort_response at 0x7f5dffb1e820>':
        Traceback (most recent call last):
          File "/home/gasti/work/wazuh/venv/lib/python3.9/site-packages/tavern/response/base.py", line 152, in _maybe_run_validate_functions
            vf(response)
          File "/home/gasti/work/wazuh/venv/lib/python3.9/site-packages/tavern/util/extfunctions.py", line 98, in inner
            result = func(response, *args, **kwargs)
          File "/home/gasti/work/wazuh/api/test/integration/tavern_utils.py", line 194, in test_sort_response
            affected_items = response.json()['data']['affected_items']
        KeyError: 'data'
------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------
ERROR    tavern.response.base:base.py:43 Status code was 500, expected 200
ERROR    tavern.response.base:base.py:41 Error calling validate function '<function test_sort_response at 0x7f5dffb1e820>':
    Traceback (most recent call last):
      File "/home/gasti/work/wazuh/venv/lib/python3.9/site-packages/tavern/response/base.py", line 152, in _maybe_run_validate_functions
        vf(response)
      File "/home/gasti/work/wazuh/venv/lib/python3.9/site-packages/tavern/util/extfunctions.py", line 98, in inner
        result = func(response, *args, **kwargs)
      File "/home/gasti/work/wazuh/api/test/integration/tavern_utils.py", line 194, in test_sort_response
        affected_items = response.json()['data']['affected_items']
    KeyError: 'data'
Traceback (most recent call last):
  File "/home/gasti/work/wazuh/venv/lib/python3.9/site-packages/tavern/response/base.py", line 152, in _maybe_run_validate_functions
    vf(response)
  File "/home/gasti/work/wazuh/venv/lib/python3.9/site-packages/tavern/util/extfunctions.py", line 98, in inner
    result = func(response, *args, **kwargs)
  File "/home/gasti/work/wazuh/api/test/integration/tavern_utils.py", line 194, in test_sort_response
    affected_items = response.json()['data']['affected_items']
KeyError: 'data'
================================================================================ warnings summary ================================================================================
../../../venv/lib/python3.9/site-packages/pytest_aiohttp/plugin.py:28
  /home/gasti/work/wazuh/venv/lib/python3.9/site-packages/pytest_aiohttp/plugin.py:28: DeprecationWarning: The 'asyncio_mode' is 'legacy', switching to 'auto' for the sake of pytest-aiohttp backward compatibility. Please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)

../../../venv/lib/python3.9/site-packages/_pytest/nodes.py:642
  /home/gasti/work/wazuh/venv/lib/python3.9/site-packages/_pytest/nodes.py:642: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)

test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages
  /home/gasti/work/wazuh/venv/lib/python3.9/site-packages/pytest_trio/plugin.py:62: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
    if issubclass(call.excinfo.type, trio.MultiError):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================ short test summary info =============================================================================
FAILED test_syscollector_endpoints.tavern.yaml::GET /syscollector/{agent_id}/packages
============================================================= 1 failed, 158 passed, 3 warnings in 565.76s (0:09:25) ==============================================================
```

</details>

If I call the endpoint during the test I get a status 500 with the following message. It seems that there is a package with an empty name causing issues.

```json
{
    "title": "Response body does not conform to specification",
    "detail": "' ' is not one of ['allowed', 'same', 'foreign']. Failed validating 'enum' in schema['allOf'][1]['properties']['data']['allOf'][1]['properties']['affected_items']['items']['properties']['multiarch']: {'description': 'Whether the package has multi architecture support', 'enum': ['allowed', 'same', 'foreign'], 'type': 'string'}. On instance['data']['affected_items'][55]['multiarch']: ' '"
}
```

**Comment by GGP1** [comment]
## Update

All four tests fail because of invalid syscollector packages values.

I've taken a look at the database to check for its state and there are some rows that have the value ` ` (one space) in the `multiarch` column, whereas according to the spec, they should only have one of the following: `same`, `allowed`, `foreign` or `NULL`.

```sql
sqlite> SELECT name, quote(multiarch) FROM sys_programs;
name|quote(multiarch)
libicu66|'same'
ncurses-base|'foreign'
make|'allowed'
hostname|NULL
...
six|' '
enum34|' '
ipaddress|' '
supervisor|' '
cryptography|' '
```

Only agents from 001 to 004 (the ones using the `integration_test_wazuh-generic` image. [Dockerfile](https://github.com/wazuh/wazuh/blob/master/api/test/integration/env/base/agent/new.Dockerfile)) seem to have this problem, the others have a valid value on all their rows.

**Comment by nico-stefani** [comment]
LGTM
