### ISSUE TITLE
Fix error in indexer_connector_unit_tests

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#19971]
## Description

[Indexer_connector_unit_tests](https://github.com/wazuh/wazuh/actions/runs/6705386159/job/18221605990?pr=19948) started to fail in GitHub Actions

## DoD

- [ ] Issue has been fixed.
- [ ] Compliance with:
  - [ ] [RTR](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner/doc/rtr.md)
  - [ ] [GitHub Actions](https://github.com/wazuh/wazuh/actions/workflows/vulnerability-scanner-tests.yml)
- [ ] Add or Update any relevant documentation to reflect the changes made.

**Comment by Damian-Mangold** [comment]
Ther error persists https://github.com/wazuh/wazuh/actions/runs/6732638669/job/18299774324?pr=19982

**Comment by sebasfalcone** [comment]
## Update
The error was only reproducible on Github actions and did happen at random ([see tests](https://github.com/wazuh/wazuh/pull/19992#issue-1974446667))

From the error message we can obtain the following conclusion:
```
==4379==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f35faa61727 bp 0x7f35f3efb290 sp 0x7f35f3efa9f8 T4)
==4379==The signal is caused by a READ memory access.
==4379==Hint: address points to the zero page.
Errors while running CTest
    #0 0x7f35faa61726  (/lib/x86_64-linux-gnu/libc.so.6+0x188726)
    #1 0x7f35fd60d60d in __interceptor_getaddrinfo ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:2523
    #2 0x562a8210fa67 in int httplib::detail::create_socket<httplib::Server::create_server_socket(char const*, int, int, std::function<void (int)>) const::{lambda(int, addrinfo&)#1}>(char const*, char const*, int, int, int, bool, std::function<void (int)>, httplib::Server::create_server_socket(char const*, int, int, std::function<void (int)>) const::{lambda(int, addrinfo&)#1}) /home/runner/work/wazuh/wazuh/src/external/cpp-httplib/httplib.h:2548
    #3 0x562a820d9a8c in httplib::Server::create_server_socket(char const*, int, int, std::function<void (int)>) const /home/runner/work/wazuh/wazuh/src/external/cpp-httplib/httplib.h:5305
    #4 0x562a820d9fa1 in httplib::Server::bind_internal(char const*, int, int) /home/runner/work/wazuh/wazuh/src/external/cpp-httplib/httplib.h:5320
    #5 0x562a820cf312 in httplib::Server::bind_to_port(char const*, int, int) /home/runner/work/wazuh/wazuh/src/external/cpp-httplib/httplib.h:4946
    #6 0x562a820cf454 in httplib::Server::listen(char const*, int, int) /home/runner/work/wazuh/wazuh/src/external/cpp-httplib/httplib.h:4956
    #7 0x562a820ee2da in FakeOpenSearchServer::run() /home/runner/work/wazuh/wazuh/src/shared_modules/indexer_connector/tests/unit/fakeOpenSearchServer.hpp:84
    #8 0x562a8226f734 in void std::__invoke_impl<void, void (FakeOpenSearchServer::*)(), FakeOpenSearchServer*>(std::__invoke_memfun_deref, void (FakeOpenSearchServer::*&&)(), FakeOpenSearchServer*&&) /usr/include/c++/9/bits/invoke.h:73
    #9 0x562a8226ef3c in std::__invoke_result<void (FakeOpenSearchServer::*)(), FakeOpenSearchServer*>::type std::__invoke<void (FakeOpenSearchServer::*)(), FakeOpenSearchServer*>(void (FakeOpenSearchServer::*&&)(), FakeOpenSearchServer*&&) /usr/include/c++/9/bits/invoke.h:95
    #10 0x562a8226ea0d in void std::thread::_Invoker<std::tuple<void (FakeOpenSearchServer::*)(), FakeOpenSearchServer*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/include/c++/9/thread:244
    #11 0x562a8226e40e in std::thread::_Invoker<std::tuple<void (FakeOpenSearchServer::*)(), FakeOpenSearchServer*> >::operator()() /usr/include/c++/9/thread:251
    #12 0x562a8226daf8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (FakeOpenSearchServer::*)(), FakeOpenSearchServer*> > >::_M_run() /usr/include/c++/9/thread:195
    #13 0x7f35fb65ddf3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6df3)
    #14 0x7f35fcd0f608 in start_thread /build/glibc-BHL3KM/glibc-2.31/nptl/pthread_create.c:477
    #15 0x7f35fa9f8132 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132)
```

The error is watched by ASAN and is related to a segfault on an unknown address:
```
==4379==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f35faa61727 bp 0x7f35f3efb290 sp 0x7f35f3efa9f8 T4)
```

The call stack points to the library we use for testing with fake servers ([cpp-httplib](https://github.com/yhirose/cpp-httplib)) so the issue could be related to a bug in it

**Comment by Damian-Mangold** [comment]
As the error cannot be reproduced locally, is random, and was not repeated, I close the issue.
