### ISSUE TITLE
Fix warning in wazuh/rbac/tests/test_orm.py::test_get_all_roles_from_user unit test

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#20260]
|Wazuh version|Component|
|---|---|
| 4.9 | framework |

## Description
The following warning is raised by pytest when the framework unit tests are run.

```
wazuh/rbac/tests/test_orm.py::test_get_all_roles_from_user
  /home/marcelo/wazuh/wazuh/venv-3.10/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7f0e37505630>

  Traceback (most recent call last):
    File "/home/marcelo/wazuh/wazuh/venv-3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 732, in <lambda>
      lambda ref: _finalize_fairy(
    File "/home/marcelo/wazuh/wazuh/venv-3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1031, in _finalize_fairy
      fairy.dbapi_connection = fairy._connection_record = None  # type: ignore
  AttributeError: 'NoneType' object has no attribute 'dbapi_connection'

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

This warning is occurring due to an issue where under some garbage collection/exception scenarios the connection pool's cleanup routine would fail because of an unexpected state.

This bug corresponds to the SQLAlchemy source code and it was fixed in https://github.com/sqlalchemy/sqlalchemy/issues/10414 by this [commit](https://github.com/sqlalchemy/sqlalchemy/commit/061e7f8b62c0f4d37664393985a91cb4b8b0c79a).

I have created the issue https://github.com/wazuh/wazuh/issues/20443 to upgrade SQLAlchemy to `>=2.0.22`.

**Comment by GGP1** [comment]
## Update

The tests display no warnings after upgrading SQLAlchemy to `2.0.22`.

```console
(venv10) gasti@pop-os:~/work/wazuh$ pip install SQLAlchemy==2.0.22
Collecting SQLAlchemy==2.0.22
  Downloading SQLAlchemy-2.0.22-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.4 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in ./venv10/lib/python3.10/site-packages (from SQLAlchemy==2.0.22) (4.5.0)
Requirement already satisfied: greenlet!=0.4.17 in ./venv10/lib/python3.10/site-packages (from SQLAlchemy==2.0.22) (2.0.2)
Downloading SQLAlchemy-2.0.22-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 5.7 MB/s eta 0:00:00
Installing collected packages: SQLAlchemy
  Attempting uninstall: SQLAlchemy
    Found existing installation: SQLAlchemy 2.0.0
    Uninstalling SQLAlchemy-2.0.0:
      Successfully uninstalled SQLAlchemy-2.0.0
Successfully installed SQLAlchemy-2.0.22
(venv10) gasti@pop-os:~/work/wazuh$ python3 -m pytest framework/wazuh/rbac/tests/test_orm.py
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.3.0
rootdir: /home/gasti/work/wazuh/framework
configfile: pytest.ini
plugins: asyncio-0.18.1, tavern-1.23.5, trio-0.7.0, html-2.1.1, aiohttp-1.0.4, metadata-3.0.0
asyncio: mode=auto
collected 62 items                                                             

framework/wazuh/rbac/tests/test_orm.py ................................. [ 53%]
.............................                                                         [100%]

==================================== 62 passed in 29.76s ====================================
```
