### ISSUE TITLE
Review and fix `DEPS_VERSION = 24` embedded interpreter files

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#20482]
|Wazuh version|Component|
|---|---|
| 4.8.0 | Wazuh embedded interpreter |

## Description
During #20421, it was found that the `Modules/Setup` file found in the sources of the Wazuh embedded Python interpreter for `DEPS_VERSION=24` was not correctly modified so some modules are not correctly loaded in installation time and configurations to enable the SSL module and link it with the `libwazuhext.so` were not done.

We need to review the files of the embedded interpreter to discard that any other required change was not carried out and make the necessary modifications to avoid potential failures.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
# Issue Update

I have modified the file `Modules/Setup` accordingly and rebuilt the pre-compiled and compiled packages of the embedded interpreter for both `amd64` and `aarch64`. 

A proof that this modification was effective was found in the compilation process logs:
```console
The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                  _asyncio              _blake2            
_contextvars          _datetime             _elementtree       
_hashlib              _json                 _md5               
_pickle               _posixsubprocess      _sha1              
_sha256               _sha3                 _sha512            
_socket               _ssl                  fcntl              
grp                   pwd                   select             
time
```

Currently, I am analyzing a series of warnings found in the API logs when making the `POST /security/user/authenticate` request related to the upgrade of the `SQLAlchemy` carried out in #16679. The logs show the following: 
```log
# /var/ossec/bin/wazuh-apid -f -dd
Starting API in foreground
2023/11/28 16:52:55 INFO: Checking RBAC database integrity...
2023/11/28 16:52:55 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2023/11/28 16:52:55 INFO: RBAC database integrity check finished successfully
2023/11/28 16:53:06 INFO: Listening on 0.0.0.0:55000..
======== Running on https://0.0.0.0:55000 ========
(Press CTRL+C to quit)
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:434: SAWarning: Instance <Roles at 0x7f73e1a2e800> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'users': [user.id for user in self.users],
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:435: SAWarning: Instance <Roles at 0x7f73e1a2e800> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'rules': [rule.id for rule in self.rules]}
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:434: SAWarning: Instance <Roles at 0x7f73e1a2e860> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'users': [user.id for user in self.users],
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:435: SAWarning: Instance <Roles at 0x7f73e1a2e860> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'rules': [rule.id for rule in self.rules]}
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:434: SAWarning: Instance <Roles at 0x7f73e1a2e5f0> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'users': [user.id for user in self.users],
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:435: SAWarning: Instance <Roles at 0x7f73e1a2e5f0> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'rules': [rule.id for rule in self.rules]}
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:434: SAWarning: Instance <Roles at 0x7f73e1a2e590> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'users': [user.id for user in self.users],
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:435: SAWarning: Instance <Roles at 0x7f73e1a2e590> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'rules': [rule.id for rule in self.rules]}
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:434: SAWarning: Instance <Roles at 0x7f73e1a2dab0> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'users': [user.id for user in self.users],
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:435: SAWarning: Instance <Roles at 0x7f73e1a2dab0> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'rules': [rule.id for rule in self.rules]}
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:434: SAWarning: Instance <Roles at 0x7f73e1a2e020> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'users': [user.id for user in self.users],
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:435: SAWarning: Instance <Roles at 0x7f73e1a2e020> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'rules': [rule.id for rule in self.rules]}
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:434: SAWarning: Instance <Roles at 0x7f73e1a2df90> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'users': [user.id for user in self.users],
/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/orm.py:435: SAWarning: Instance <Roles at 0x7f73e1a2df90> is detached, dynamic relationship cannot return a correct result.   This warning will become a DetachedInstanceError in a future release.
  'rules': [rule.id for rule in self.rules]}
2023/11/28 16:53:10 INFO: wazuh 172.23.0.1 "POST /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.367s: 200
```

These are raised when the `preprocessor.get_permissions` function from the `wazuh/rbac` module is executed. Its origin was found to be the solution to this issue https://github.com/sqlalchemy/sqlalchemy/issues/6426 from `SQLAlchemy` `1.4`. In the version we were using (`1.3`), the failure was silent, but since `2.0` the warning message was added to aware the users.

**Comment by fdalmaup** [comment]
# Issue Update

The `Roles` instances that the messages mentioned are obtained in the following code section:
https://github.com/wazuh/wazuh/blob/2e86c7f02d8d14875d01b141a218d91de9abfb10/framework/wazuh/rbac/auth_context.py#L58-L61

Nevertheless, the `to_dict` method is not executed until the resulting iterator from the `map` is used:
https://github.com/wazuh/wazuh/blob/2e86c7f02d8d14875d01b141a218d91de9abfb10/framework/wazuh/rbac/auth_context.py#L65-L75

The first context manager (`orm.RolesManager`) is closed after obtaining `roles_list` and so is its inner `session`. So, when each instance is evaluated in the `for` loop of line 68, its inner state is [detached](https://docs.sqlalchemy.org/en/20/glossary.html#term-detached) and raises the `SAWarning`. 

To fix this, the `roles_list` assignation was modified by making it a list to obtain every role eagerly and not lazily in the mentioned loop. 

```log
root@714e8eb431f0:/# /var/ossec/bin/wazuh-apid -f -dd
wazuh-apid: Orphan child process 1338 was terminated.
wazuh-apid: Orphan child process 1341 was terminated.
wazuh-apid: Orphan child process 1337 was terminated.
wazuh-apid: Orphan child process 1344 was terminated.
Starting API in foreground
2023/11/29 15:06:37 INFO: Checking RBAC database integrity...
2023/11/29 15:06:37 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2023/11/29 15:06:37 INFO: RBAC database integrity check finished successfully
2023/11/29 15:06:40 INFO: Listening on 0.0.0.0:55000..
======== Running on https://0.0.0.0:55000 ========
(Press CTRL+C to quit)
2023/11/29 15:06:41 INFO: wazuh-wui 172.20.0.1 "POST /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.368s: 200
```

## UTs
### API
<details><summary>Framework</summary>

```console
$ pytest api/api
====================================================================== test session starts ======================================================================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/fdalmau/git/wazuh/api/api
configfile: pytest.ini
plugins: cov-3.0.0, aiohttp-1.0.4, trio-0.7.0, anyio-3.6.2, metadata-2.0.2, tavern-1.23.5, asyncio-0.18.1, html-2.1.1
asyncio: mode=auto
collected 560 items                                                                                                                                             

api/api/controllers/test/test_active_response_controller.py .                                                                                             [  0%]
api/api/controllers/test/test_agent_controller.py ............................................                                                            [  8%]
api/api/controllers/test/test_cdb_list_controller.py ......                                                                                               [  9%]
api/api/controllers/test/test_ciscat_controller.py .                                                                                                      [  9%]
api/api/controllers/test/test_cluster_controller.py ........................                                                                              [ 13%]
api/api/controllers/test/test_decoder_controller.py .......                                                                                               [ 14%]
api/api/controllers/test/test_default_controller.py .                                                                                                     [ 15%]
api/api/controllers/test/test_event_controller.py .                                                                                                       [ 15%]
api/api/controllers/test/test_experimental_controller.py ...............                                                                                  [ 17%]
api/api/controllers/test/test_manager_controller.py ..................                                                                                    [ 21%]
api/api/controllers/test/test_mitre_controller.py .......                                                                                                 [ 22%]
api/api/controllers/test/test_overview_controller.py .                                                                                                    [ 22%]
api/api/controllers/test/test_rootcheck_controller.py ....                                                                                                [ 23%]
api/api/controllers/test/test_rule_controller.py ........                                                                                                 [ 24%]
api/api/controllers/test/test_sca_controller.py ..                                                                                                        [ 25%]
api/api/controllers/test/test_security_controller.py ...................................................                                                  [ 34%]
api/api/controllers/test/test_syscheck_controller.py ....                                                                                                 [ 34%]
api/api/controllers/test/test_syscollector_controller.py .........                                                                                        [ 36%]
api/api/controllers/test/test_task_controller.py .                                                                                                        [ 36%]
api/api/controllers/test/test_vulnerability_controller.py ....                                                                                            [ 37%]
api/api/models/test/test_model.py ..............................                                                                                          [ 42%]
api/api/test/test_alogging.py ......................                                                                                                      [ 46%]
api/api/test/test_authentication.py ...........                                                                                                           [ 48%]
api/api/test/test_configuration.py .............................................                                                                          [ 56%]
api/api/test/test_encoder.py ...                                                                                                                          [ 57%]
api/api/test/test_middlewares.py ...............                                                                                                          [ 59%]
api/api/test/test_uri_parser.py ...                                                                                                                       [ 60%]
api/api/test/test_util.py ..............................................                                                                                  [ 68%]
api/api/test/test_validator.py .......................................................................................................................... [ 90%]
......................................................                                                                                                    [100%]

====================================================================== 560 passed in 3.39s ======================================================================
```

</details>



<details><summary>Framework</summary>

```console
$ pytest framework/
====================================================================== test session starts ======================================================================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/fdalmau/git/wazuh/framework
configfile: pytest.ini
plugins: cov-3.0.0, aiohttp-1.0.4, trio-0.7.0, anyio-3.6.2, metadata-2.0.2, tavern-1.23.5, asyncio-0.18.1, html-2.1.1
asyncio: mode=auto
collected 2206 items                                                                                                                                            

framework/scripts/tests/test_agent_groups.py ..............                                                                                               [  0%]
framework/scripts/tests/test_agent_upgrade.py ...............                                                                                             [  1%]
framework/scripts/tests/test_cluster_control.py ......                                                                                                    [  1%]
framework/scripts/tests/test_rbac_control.py .........                                                                                                    [  1%]
framework/scripts/tests/test_wazuh_clusterd.py .......                                                                                                    [  2%]
framework/scripts/tests/test_wazuh_logtest.py ......................                                                                                      [  3%]
framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................................                                                                     [  4%]
framework/wazuh/core/cluster/tests/test_client.py ................                                                                                        [  5%]
framework/wazuh/core/cluster/tests/test_cluster.py ...................................                                                                    [  7%]
framework/wazuh/core/cluster/tests/test_common.py ....................................................................................                    [ 10%]
framework/wazuh/core/cluster/tests/test_control.py ......                                                                                                 [ 11%]
framework/wazuh/core/cluster/tests/test_local_client.py ..............                                                                                    [ 11%]
framework/wazuh/core/cluster/tests/test_local_server.py ........................                                                                          [ 12%]
framework/wazuh/core/cluster/tests/test_master.py ...............................................                                                         [ 15%]
framework/wazuh/core/cluster/tests/test_server.py .............................                                                                           [ 16%]
framework/wazuh/core/cluster/tests/test_utils.py ............                                                                                             [ 16%]
framework/wazuh/core/cluster/tests/test_worker.py ..................................                                                                      [ 18%]
framework/wazuh/core/tests/test_active_response.py ....................                                                                                   [ 19%]
framework/wazuh/core/tests/test_agent.py ................................................................................................................ [ 24%]
.....................................                                                                                                                     [ 26%]
framework/wazuh/core/tests/test_cdb_list.py ......................................                                                                        [ 27%]
framework/wazuh/core/tests/test_common.py .........                                                                                                       [ 28%]
framework/wazuh/core/tests/test_configuration.py .......................................................................                                  [ 31%]
framework/wazuh/core/tests/test_database.py .............                                                                                                 [ 32%]
framework/wazuh/core/tests/test_decoder.py ................                                                                                               [ 32%]
framework/wazuh/core/tests/test_exception.py ..........                                                                                                   [ 33%]
framework/wazuh/core/tests/test_input_validator.py ...                                                                                                    [ 33%]
framework/wazuh/core/tests/test_logtest.py ..                                                                                                             [ 33%]
framework/wazuh/core/tests/test_manager.py ................                                                                                               [ 34%]
framework/wazuh/core/tests/test_mitre.py .............                                                                                                    [ 34%]
framework/wazuh/core/tests/test_pyDaemonModule.py .....                                                                                                   [ 34%]
framework/wazuh/core/tests/test_results.py ........................................                                                                       [ 36%]
framework/wazuh/core/tests/test_rootcheck.py .............                                                                                                [ 37%]
framework/wazuh/core/tests/test_rule.py .......................                                                                                           [ 38%]
framework/wazuh/core/tests/test_sca.py .............................                                                                                      [ 39%]
framework/wazuh/core/tests/test_security.py .............                                                                                                 [ 40%]
framework/wazuh/core/tests/test_stats.py .................                                                                                                [ 41%]
framework/wazuh/core/tests/test_syscheck.py .......                                                                                                       [ 41%]
framework/wazuh/core/tests/test_syscollector.py ...                                                                                                       [ 41%]
framework/wazuh/core/tests/test_task.py ........                                                                                                          [ 41%]
framework/wazuh/core/tests/test_utils.py ................................................................................................................ [ 46%]
......................................................................................................................................................... [ 53%]
..............                                                                                                                                            [ 54%]
framework/wazuh/core/tests/test_vulnerability.py ..                                                                                                       [ 54%]
framework/wazuh/core/tests/test_wazuh_queue.py .......................                                                                                    [ 55%]
framework/wazuh/core/tests/test_wazuh_socket.py ....................                                                                                      [ 56%]
framework/wazuh/core/tests/test_wdb.py ...............................                                                                                    [ 57%]
framework/wazuh/core/tests/test_wlogging.py ............                                                                                                  [ 58%]
framework/wazuh/rbac/tests/test_auth_context.py ..                                                                                                        [ 58%]
framework/wazuh/rbac/tests/test_decorators.py ........................................................................................................... [ 63%]
..                                                                                                                                                        [ 63%]
framework/wazuh/rbac/tests/test_default_configuration.py .........................................................                                        [ 66%]
framework/wazuh/rbac/tests/test_orm.py ..............................................................                                                     [ 68%]
framework/wazuh/rbac/tests/test_preprocessor.py ...........                                                                                               [ 69%]
framework/wazuh/tests/test_active_response.py ............                                                                                                [ 69%]
framework/wazuh/tests/test_agent.py ..................................................................................................................... [ 75%]
.....                                                                                                                                                     [ 75%]
framework/wazuh/tests/test_cdb_list.py .....................................................                                                              [ 77%]
framework/wazuh/tests/test_ciscat.py .................................                                                                                    [ 79%]
framework/wazuh/tests/test_cluster.py ..........                                                                                                          [ 79%]
framework/wazuh/tests/test_decoder.py ..........................................................                                                          [ 82%]
framework/wazuh/tests/test_event.py ....                                                                                                                  [ 82%]
framework/wazuh/tests/test_group.py .......                                                                                                               [ 83%]
framework/wazuh/tests/test_logtest.py ......                                                                                                              [ 83%]
framework/wazuh/tests/test_manager.py ....................................                                                                                [ 84%]
framework/wazuh/tests/test_mitre.py .......                                                                                                               [ 85%]
framework/wazuh/tests/test_rootcheck.py ..................................................                                                                [ 87%]
framework/wazuh/tests/test_rule.py ..........................................................................                                             [ 90%]
framework/wazuh/tests/test_sca.py ...........                                                                                                             [ 91%]
framework/wazuh/tests/test_security.py .......................................................................                                            [ 94%]
framework/wazuh/tests/test_stats.py ...............                                                                                                       [ 95%]
framework/wazuh/tests/test_syscheck.py .........................                                                                                          [ 96%]
framework/wazuh/tests/test_syscollector.py ............                                                                                                   [ 96%]
framework/wazuh/tests/test_task.py ............................                                                                                           [ 98%]
framework/wazuh/tests/test_vulnerability.py ........................................                                                                      [100%]

======================================================================= warnings summary ========================================================================
wazuh/rbac/tests/test_orm.py::test_get_all_rules_from_role
  /home/fdalmau/venv/unittest-env-3.10/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function _ConnectionRecord.checkout.<locals>.<lambda> at 0x7f995f9e65f0>
  
  Traceback (most recent call last):
    File "/home/fdalmau/venv/unittest-env-3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 732, in <lambda>
      lambda ref: _finalize_fairy(
    File "/home/fdalmau/venv/unittest-env-3.10/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1031, in _finalize_fairy
      fairy.dbapi_connection = fairy._connection_record = None  # type: ignore
  AttributeError: 'NoneType' object has no attribute 'dbapi_connection'
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================== 2206 passed, 1 warning in 294.91s (0:04:54) ==========================================================
```

</details>

**Comment by fdalmaup** [comment]
# AITs 

## Test report
[AITsReport.zip](https://github.com/wazuh/wazuh/files/13504962/AITsReport.zip)

## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_DELETE_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_GET_endpoints.tavern.yaml | 96 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_POST_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_PUT_endpoints.tavern.yaml | 10 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cluster_endpoints.tavern.yaml | 49 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_decoder_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_default_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_manager_endpoints.tavern.yaml | 32 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_agent_endpoints.tavern.yaml | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cluster_endpoints.tavern.yaml | 19 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_decoder_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_manager_endpoints.tavern.yaml | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_rule_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_security_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_syscheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_syscollector_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_task_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_vulnerability_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_webhook_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_agent_endpoints.tavern.yaml | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_all_endpoints.tavern.yaml | 167 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_cluster_endpoints.tavern.yaml | 19 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_decoder_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_manager_endpoints.tavern.yaml | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_rule_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_security_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_syscheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_syscollector_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_task_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_vulnerability_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_webhook_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rule_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_sca_endpoints.tavern.yaml | 45 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_DELETE_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_GET_endpoints.tavern.yaml | 11 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_POST_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_PUT_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_syscheck_endpoints.tavern.yaml | 34 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_syscollector_endpoints.tavern.yaml | 159 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_task_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_vulnerability_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_webhook_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
