### ISSUE TITLE
Fix Vulnerability Endpoints integration test

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#20799]
|Wazuh version|Component|
|---|---|
| 4.7.2 | API |

## Description
The `test_vulnerability_endpoints.tavern.yaml` tests, specifically the one related to the `GET /vulnerability/{agent_id}` endpoint, is failing in the `4.7.2` branch. As tested in #20468 and #20240, it does not fail for the `4.7.1` or `4.7.0` versions. 

<details><summary>Detailed failure</summary>

```console
$ pytest -vv test_vulnerability_endpoints.tavern.yaml
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.8.10, pytest-7.3.1, pluggy-0.13.1 -- /home/fdalmau/venv/integrationtest-env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '7.3.1', 'py': '1.11.0', 'pluggy': '0.13.1'}, 'Plugins': {'aiohttp': '1.0.4', 'trio': '0.7.0', 'metadata': '2.0.2', 'tavern': '1.23.5', 'asyncio': '0.18.1', 'html': '2.1.1'}}
rootdir: /home/fdalmau/git/wazuh/api/test/integration
configfile: pytest.ini
plugins: aiohttp-1.0.4, trio-0.7.0, metadata-2.0.2, tavern-1.23.5, asyncio-0.18.1, html-2.1.1
asyncio: mode=auto
collected 4 items                                                                                                                                                                                                 

test_vulnerability_endpoints.tavern.yaml::GET /vulnerability/{agent_id} FAILED                                                                                                                              [ 25%]
test_vulnerability_endpoints.tavern.yaml::GET /vulnerability/001/last_scan PASSED                                                                                                                           [ 50%]
test_vulnerability_endpoints.tavern.yaml::GET /vulnerability/{agent_id}/summary/{field} PASSED                                                                                                              [ 75%]
test_vulnerability_endpoints.tavern.yaml::PUT /vulnerability PASSED                                                                                                                                         [100%]

==================================================================================================== FAILURES =====================================================================================================
______________________________________________ /home/fdalmau/git/wazuh/api/test/integration/test_vulnerability_endpoints.tavern.yaml::GET /vulnerability/{agent_id} _______________________________________________
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzAyNDk5NjEyLCJleHAiOjE3MDI1MDA1MTIsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.ACiGDiqzTbQUKYUh8ce32Yvs66dstT8T0c9T76M1eBeuqFFUCpHQr3G0_2GQn3sFy2ancv7SGfhIDon1kEEtLmWKAa9dYiAydabF_PojTkXQ7hu_caoSmKL3pep9yFtaq6zcHZcw9Nlsmhwrgi6bm4l18OvZ-ZSRbUIR6ZJssb_t7Tdm'

Source test stage (line 6):
  - name: Get agent's vulnerabilities (limit and offset)
    request: &vulnerability_request_001
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/vulnerability/001"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        offset: 5
        limit: 1
    response:
      status_code: 200
      json:
        error: 0
        data:
          affected_items:
            - cve: !anystr
              version: !anystr
              architecture: !anystr
              name: !anystr
              type: !anystr
              status: !anystr
              cvss2_score: !anything
              cvss3_score: !anything
              detection_time: !anystr
              severity: !anystr
              external_references: !anylist
              condition: !anystr
              title: !anystr
              published: !anystr
          failed_items: []
          total_affected_items: !anyint
          total_failed_items: 0
      save:
        json:
          expected_cve: data.affected_items[0].cve
          expected_version: data.affected_items[0].version
          expected_architecture: data.affected_items[0].architecture
          expected_name: data.affected_items[0].name
          expected_type: data.affected_items[0].type
          expected_status: data.affected_items[0].status
          expected_cvss2_score: data.affected_items[0].cvss2_score
          expected_cvss3_score: data.affected_items[0].cvss3_score
          expected_detection_time: data.affected_items[0].detection_time
          expected_severity: data.affected_items[0].severity
          expected_external_references: data.affected_items[0].external_references
          expected_condition: data.affected_items[0].condition
          expected_title: data.affected_items[0].title
          expected_published: data.affected_items[0].published


Formatted stage:
  name: Get agent's vulnerabilities (limit and offset)
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzAyNDk5NjEyLCJleHAiOjE3MDI1MDA1MTIsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.ACiGDiqzTbQUKYUh8ce32Yvs66dstT8T0c9T76M1eBeuqFFUCpHQr3G0_2GQn3sFy2ancv7SGfhIDon1kEEtLmWKAa9dYiAydabF_PojTkXQ7hu_caoSmKL3pep9yFtaq6zcHZcw9Nlsmhwrgi6bm4l18OvZ-ZSRbUIR6ZJssb_t7Tdm
    method: GET
    params:
      limit: 1
      offset: 5
    url: 'https://localhost:55000/vulnerability/001'
    verify: false
  response:
    json:
      data:
        affected_items:
        - architecture: !anystr ''
          condition: !anystr ''
          cve: !anystr ''
          cvss2_score: !anything ''
          cvss3_score: !anything ''
          detection_time: !anystr ''
          external_references: !anylist ''
          name: !anystr ''
          published: !anystr ''
          severity: !anystr ''
          status: !anystr ''
          title: !anystr ''
          type: !anystr ''
          version: !anystr ''
        failed_items: []
        total_affected_items: !anyint ''
        total_failed_items: 0
      error: 0
    save:
      json:
        expected_architecture: data.affected_items[0].architecture
        expected_condition: data.affected_items[0].condition
        expected_cve: data.affected_items[0].cve
        expected_cvss2_score: data.affected_items[0].cvss2_score
        expected_cvss3_score: data.affected_items[0].cvss3_score
        expected_detection_time: data.affected_items[0].detection_time
        expected_external_references: data.affected_items[0].external_references
        expected_name: data.affected_items[0].name
        expected_published: data.affected_items[0].published
        expected_severity: data.affected_items[0].severity
        expected_status: data.affected_items[0].status
        expected_title: data.affected_items[0].title
        expected_type: data.affected_items[0].type
        expected_version: data.affected_items[0].version
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Get agent's vulnerabilities (limit and offset)' failed:
    - List item(s) not present in response: [{'cve': <tavern.util.loader.StrSentinel object at 0x7f01da06d430>, 'version': <tavern.util.loader.StrSentinel object at 0x7f01da06d070>, 'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>, 'name': <tavern.util.loader.StrSentinel object at 0x7f01da06d490>, 'type': <tavern.util.loader.StrSentinel object at 0x7f01da06d4f0>, 'status': <tavern.util.loader.StrSentinel object at 0x7f01da06d520>, 'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'cvss3_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'detection_time': <tavern.util.loader.StrSentinel object at 0x7f01da06d5b0>, 'severity': <tavern.util.loader.StrSentinel object at 0x7f01da06d760>, 'external_references': <tavern.util.loader.ListSentinel object at 0x7f01da06d9a0>, 'condition': <tavern.util.loader.StrSentinel object at 0x7f01da06d910>, 'title': <tavern.util.loader.StrSentinel object at 0x7f01da06d310>, 'published': <tavern.util.loader.StrSentinel object at 0x7f01da06d820>}]
------------------------------------------------------------------------------------------------ Captured log call ------------------------------------------------------------------------------------------------
ERROR    tavern.response.base:base.py:41 List item(s) not present in response: [{'cve': <tavern.util.loader.StrSentinel object at 0x7f01da06d430>, 'version': <tavern.util.loader.StrSentinel object at 0x7f01da06d070>, 'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>, 'name': <tavern.util.loader.StrSentinel object at 0x7f01da06d490>, 'type': <tavern.util.loader.StrSentinel object at 0x7f01da06d4f0>, 'status': <tavern.util.loader.StrSentinel object at 0x7f01da06d520>, 'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'cvss3_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'detection_time': <tavern.util.loader.StrSentinel object at 0x7f01da06d5b0>, 'severity': <tavern.util.loader.StrSentinel object at 0x7f01da06d760>, 'external_references': <tavern.util.loader.ListSentinel object at 0x7f01da06d9a0>, 'condition': <tavern.util.loader.StrSentinel object at 0x7f01da06d910>, 'title': <tavern.util.loader.StrSentinel object at 0x7f01da06d310>, 'published': <tavern.util.loader.StrSentinel object at 0x7f01da06d820>}]
Traceback (most recent call last):
  File "/home/fdalmau/venv/integrationtest-env/lib/python3.8/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'affected_items': [], 'total_affected_items': 0, 'total_failed_items': 0, 'failed_items': []}, 'message': 'No vulnerabilities were returned', 'error': 0} == {'error': 0, 'data': {'affected_items': [{'cve': <tavern.util.loader.StrSentinel object at 0x7f01da06d430>, 'version': <tavern.util.loader.StrSentinel object at 0x7f01da06d070>, 'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>, 'name': <tavern.util.loader.StrSentinel object at 0x7f01da06d490>, 'type': <tavern.util.loader.StrSentinel object at 0x7f01da06d4f0>, 'status': <tavern.util.loader.StrSentinel object at 0x7f01da06d520>, 'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'cvss3_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'detection_time': <tavern.util.loader.StrSentinel object at 0x7f01da06d5b0>, 'severity': <tavern.util.loader.StrSentinel object at 0x7f01da06d760>, 'external_references': <tavern.util.loader.ListSentinel object at 0x7f01da06d9a0>, 'condition': <tavern.util.loader.StrSentinel object at 0x7f01da06d910>, 'title': <tavern.util.loader.StrSentinel object at 0x7f01da06d310>, 'published': <tavern.util.loader.StrSentinel object at 0x7f01da06d820>}], 'failed_items': [], 'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f01da06d2e0>, 'total_failed_items': 0}}
  Common items:
  {'error': 0}
  Differing items:
  {'data': {'affected_items': [], 'failed_items': [], 'total_affected_items': 0, 'total_failed_items': 0}} != {'data': {'affected_items': [{'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>, 'condition': ...tems': [], 'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f01da06d2e0>, 'total_failed_items': 0}}
  Left contains 1 more item:
  {'message': 'No vulnerabilities were returned'}
  Full diff:
    {
  +  'data': {'affected_items': [],
  -  'data': {'affected_items': [{'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>,
  -                               'condition': <tavern.util.loader.StrSentinel object at 0x7f01da06d910>,
  -                               'cve': <tavern.util.loader.StrSentinel object at 0x7f01da06d430>,
  -                               'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>,
  -                               'cvss3_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>,
  -                               'detection_time': <tavern.util.loader.StrSentinel object at 0x7f01da06d5b0>,
  -                               'external_references': <tavern.util.loader.ListSentinel object at 0x7f01da06d9a0>,
  -                               'name': <tavern.util.loader.StrSentinel object at 0x7f01da06d490>,
  -                               'published': <tavern.util.loader.StrSentinel object at 0x7f01da06d820>,
  -                               'severity': <tavern.util.loader.StrSentinel object at 0x7f01da06d760>,
  -                               'status': <tavern.util.loader.StrSentinel object at 0x7f01da06d520>,
  -                               'title': <tavern.util.loader.StrSentinel object at 0x7f01da06d310>,
  -                               'type': <tavern.util.loader.StrSentinel object at 0x7f01da06d4f0>,
  -                               'version': <tavern.util.loader.StrSentinel object at 0x7f01da06d070>}],
              'failed_items': [],
  -           'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f01da06d2e0>,
  +           'total_affected_items': 0,
              'total_failed_items': 0},
     'error': 0,
  +  'message': 'No vulnerabilities were returned',
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fdalmau/venv/integrationtest-env/lib/python3.8/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_items': [], 'total_affected_items': 0, 'total_failed_items': 0, 'failed_items': []} == {'affected_items': [{'cve': <tavern.util.loader.StrSentinel object at 0x7f01da06d430>, 'version': <tavern.util.loader.StrSentinel object at 0x7f01da06d070>, 'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>, 'name': <tavern.util.loader.StrSentinel object at 0x7f01da06d490>, 'type': <tavern.util.loader.StrSentinel object at 0x7f01da06d4f0>, 'status': <tavern.util.loader.StrSentinel object at 0x7f01da06d520>, 'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'cvss3_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'detection_time': <tavern.util.loader.StrSentinel object at 0x7f01da06d5b0>, 'severity': <tavern.util.loader.StrSentinel object at 0x7f01da06d760>, 'external_references': <tavern.util.loader.ListSentinel object at 0x7f01da06d9a0>, 'condition': <tavern.util.loader.StrSentinel object at 0x7f01da06d910>, 'title': <tavern.util.loader.StrSentinel object at 0x7f01da06d310>, 'published': <tavern.util.loader.StrSentinel object at 0x7f01da06d820>}], 'failed_items': [], 'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f01da06d2e0>, 'total_failed_items': 0}
  Common items:
  {'failed_items': [], 'total_failed_items': 0}
  Differing items:
  {'affected_items': []} != {'affected_items': [{'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>, 'condition': <tavern.u...ntinel object at 0x7f01da06d430>, 'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, ...}]}
  {'total_affected_items': 0} != {'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f01da06d2e0>}
  Full diff:
    {
  +  'affected_items': [],
  -  'affected_items': [{'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>,
  -                      'condition': <tavern.util.loader.StrSentinel object at 0x7f01da06d910>,
  -                      'cve': <tavern.util.loader.StrSentinel object at 0x7f01da06d430>,
  -                      'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>,
  -                      'cvss3_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>,
  -                      'detection_time': <tavern.util.loader.StrSentinel object at 0x7f01da06d5b0>,
  -                      'external_references': <tavern.util.loader.ListSentinel object at 0x7f01da06d9a0>,
  -                      'name': <tavern.util.loader.StrSentinel object at 0x7f01da06d490>,
  -                      'published': <tavern.util.loader.StrSentinel object at 0x7f01da06d820>,
  -                      'severity': <tavern.util.loader.StrSentinel object at 0x7f01da06d760>,
  -                      'status': <tavern.util.loader.StrSentinel object at 0x7f01da06d520>,
  -                      'title': <tavern.util.loader.StrSentinel object at 0x7f01da06d310>,
  -                      'type': <tavern.util.loader.StrSentinel object at 0x7f01da06d4f0>,
  -                      'version': <tavern.util.loader.StrSentinel object at 0x7f01da06d070>}],
     'failed_items': [],
  -  'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f01da06d2e0>,
  +  'total_affected_items': 0,
     'total_failed_items': 0,
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fdalmau/venv/integrationtest-env/lib/python3.8/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert [] == [{'cve': <tavern.util.loader.StrSentinel object at 0x7f01da06d430>, 'version': <tavern.util.loader.StrSentinel object at 0x7f01da06d070>, 'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>, 'name': <tavern.util.loader.StrSentinel object at 0x7f01da06d490>, 'type': <tavern.util.loader.StrSentinel object at 0x7f01da06d4f0>, 'status': <tavern.util.loader.StrSentinel object at 0x7f01da06d520>, 'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'cvss3_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'detection_time': <tavern.util.loader.StrSentinel object at 0x7f01da06d5b0>, 'severity': <tavern.util.loader.StrSentinel object at 0x7f01da06d760>, 'external_references': <tavern.util.loader.ListSentinel object at 0x7f01da06d9a0>, 'condition': <tavern.util.loader.StrSentinel object at 0x7f01da06d910>, 'title': <tavern.util.loader.StrSentinel object at 0x7f01da06d310>, 'published': <tavern.util.loader.StrSentinel object at 0x7f01da06d820>}]
  Right contains one more item: {'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>, 'condition': <tavern.util.loader.StrSentin...Sentinel object at 0x7f01da06d430>, 'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, ...}
  Full diff:
    [
  +  ,
  -  {'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>,
  -   'condition': <tavern.util.loader.StrSentinel object at 0x7f01da06d910>,
  -   'cve': <tavern.util.loader.StrSentinel object at 0x7f01da06d430>,
  -   'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>,
  -   'cvss3_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>,
  -   'detection_time': <tavern.util.loader.StrSentinel object at 0x7f01da06d5b0>,
  -   'external_references': <tavern.util.loader.ListSentinel object at 0x7f01da06d9a0>,
  -   'name': <tavern.util.loader.StrSentinel object at 0x7f01da06d490>,
  -   'published': <tavern.util.loader.StrSentinel object at 0x7f01da06d820>,
  -   'severity': <tavern.util.loader.StrSentinel object at 0x7f01da06d760>,
  -   'status': <tavern.util.loader.StrSentinel object at 0x7f01da06d520>,
  -   'title': <tavern.util.loader.StrSentinel object at 0x7f01da06d310>,
  -   'type': <tavern.util.loader.StrSentinel object at 0x7f01da06d4f0>,
  -   'version': <tavern.util.loader.StrSentinel object at 0x7f01da06d070>},
    ]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fdalmau/venv/integrationtest-env/lib/python3.8/site-packages/tavern/response/base.py", line 97, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/home/fdalmau/venv/integrationtest-env/lib/python3.8/site-packages/tavern/util/dict_util.py", line 464, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/fdalmau/venv/integrationtest-env/lib/python3.8/site-packages/tavern/util/dict_util.py", line 464, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/fdalmau/venv/integrationtest-env/lib/python3.8/site-packages/tavern/util/dict_util.py", line 516, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(msg) from e
tavern.util.exceptions.KeyMismatchError: List item(s) not present in response: [{'cve': <tavern.util.loader.StrSentinel object at 0x7f01da06d430>, 'version': <tavern.util.loader.StrSentinel object at 0x7f01da06d070>, 'architecture': <tavern.util.loader.StrSentinel object at 0x7f01da06d460>, 'name': <tavern.util.loader.StrSentinel object at 0x7f01da06d490>, 'type': <tavern.util.loader.StrSentinel object at 0x7f01da06d4f0>, 'status': <tavern.util.loader.StrSentinel object at 0x7f01da06d520>, 'cvss2_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'cvss3_score': <tavern.util.loader.AnythingSentinel object at 0x7f01da92dd60>, 'detection_time': <tavern.util.loader.StrSentinel object at 0x7f01da06d5b0>, 'severity': <tavern.util.loader.StrSentinel object at 0x7f01da06d760>, 'external_references': <tavern.util.loader.ListSentinel object at 0x7f01da06d9a0>, 'condition': <tavern.util.loader.StrSentinel object at 0x7f01da06d910>, 'title': <tavern.util.loader.StrSentinel object at 0x7f01da06d310>, 'published': <tavern.util.loader.StrSentinel object at 0x7f01da06d820>}]
================================================================================================ warnings summary =================================================================================================
../../../../../venv/integrationtest-env/lib/python3.8/site-packages/_pytest/nodes.py:642
  /home/fdalmau/venv/integrationtest-env/lib/python3.8/site-packages/_pytest/nodes.py:642: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)

test_vulnerability_endpoints.tavern.yaml::GET /vulnerability/{agent_id}
  /home/fdalmau/venv/integrationtest-env/lib/python3.8/site-packages/pytest_trio/plugin.py:62: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
    if issubclass(call.excinfo.type, trio.MultiError):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================= short test summary info =============================================================================================
FAILED test_vulnerability_endpoints.tavern.yaml::GET /vulnerability/{agent_id}
============================================================================== 1 failed, 3 passed, 2 warnings in 3826.81s (1:03:46) ===============================================================================

```

</details>

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
In the logs from the master node of the test environment, the following message was found:
```
wazuh-modulesd:vulnerability-detector: ERROR: (5502): Could not load the CVE OVAL for 'FOCAL'. 'XMLERR: Attribute '?' has no value.'
```

This was fixed for `4.7.1` in PR #20580. Nevertheless, the changes have not been bumped yet to `4.7.2`. Once these are merged into the mentioned branch, the failure should not occur anymore.
