### ISSUE TITLE
Add, upgrade and remove packages required by connexion and uvicorn 

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#20795]
|Wazuh version|Component|
|---|---|
| 4.9 | API |

## Description
The upgrade to connexion version 3.0 has new package dependencies that should be integrated in the wazuh embedded installation package:

- NEW: uvicorn and its new dependencies.
- UPGRADE: connexion package and its new dependencies.
- REMOVE: aiohttp package and its exclusive dependencies.

This is the pipdeptree output of a running configuration:

```
./python3 -m pipdeptree
api==4.9.0
asn1crypto==1.3.0
async-timeout==4.0.2
azure-storage-blob==2.1.0
├── azure-common [required: >=1.1.5, installed: 1.1.25]
└── azure-storage-common [required: ~=2.1, installed: 2.1.0]
    ├── azure-common [required: >=1.1.5, installed: 1.1.25]
    ├── cryptography [required: Any, installed: 41.0.4]
    │   └── cffi [required: >=1.12, installed: 1.15.1]
    │       └── pycparser [required: Any, installed: 2.21]
    ├── python-dateutil [required: Any, installed: 2.8.1]
    │   └── six [required: >=1.5, installed: 1.16.0]
    └── requests [required: Any, installed: 2.31.0]
        ├── certifi [required: >=2017.4.17, installed: 2023.7.22]
        ├── charset-normalizer [required: >=2,<4, installed: 2.0.4]
        ├── idna [required: >=2.5,<4, installed: 2.9]
        └── urllib3 [required: >=1.21.1,<3, installed: 1.26.5]
boto3==1.17.85
├── botocore [required: >=1.20.85,<1.21.0, installed: 1.20.85]
│   ├── jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.5]
│   ├── python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   └── urllib3 [required: >=1.25.4,<1.27, installed: 1.26.5]
├── jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.5]
└── s3transfer [required: >=0.4.0,<0.5.0, installed: 0.4.2]
    └── botocore [required: >=1.12.36,<2.0a.0, installed: 1.20.85]
        ├── jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.5]
        ├── python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
        │   └── six [required: >=1.5, installed: 1.16.0]
        └── urllib3 [required: >=1.25.4,<1.27, installed: 1.26.5]
chardet==3.0.4
clickclick==20.10.2
├── click [required: >=4.0, installed: 8.1.3]
└── PyYAML [required: >=3.11, installed: 5.4.1]
connexion==3.0.5
├── asgiref [required: >=3.4, installed: 3.7.2]
│   └── typing-extensions [required: >=4, installed: 4.5.0]
├── httpx [required: >=0.23, installed: 0.25.2]
│   ├── anyio [required: Any, installed: 4.1.0]
│   │   ├── exceptiongroup [required: >=1.0.2, installed: 1.2.0]
│   │   ├── idna [required: >=2.8, installed: 2.9]
│   │   └── sniffio [required: >=1.1, installed: 1.3.0]
│   ├── certifi [required: Any, installed: 2023.7.22]
│   ├── httpcore [required: ==1.*, installed: 1.0.2]
│   │   ├── certifi [required: Any, installed: 2023.7.22]
│   │   └── h11 [required: >=0.13,<0.15, installed: 0.14.0]
│   ├── idna [required: Any, installed: 2.9]
│   └── sniffio [required: Any, installed: 1.3.0]
├── inflection [required: >=0.3.1, installed: 0.3.1]
├── Jinja2 [required: >=3.0.0, installed: 3.0.0]
│   └── MarkupSafe [required: >=2.0.0rc2, installed: 2.1.2]
├── jsonschema [required: >=4.0.1, installed: 4.20.0]
│   ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   ├── jsonschema-specifications [required: >=2023.03.6, installed: 2023.11.2]
│   │   └── referencing [required: >=0.31.0, installed: 0.31.1]
│   │       ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   │       └── rpds-py [required: >=0.7.0, installed: 0.13.2]
│   ├── referencing [required: >=0.28.4, installed: 0.31.1]
│   │   ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   │   └── rpds-py [required: >=0.7.0, installed: 0.13.2]
│   └── rpds-py [required: >=0.7.1, installed: 0.13.2]
├── python-multipart [required: >=0.0.5, installed: 0.0.6]
├── PyYAML [required: >=5.1, installed: 5.4.1]
├── requests [required: >=2.27, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2023.7.22]
│   ├── charset-normalizer [required: >=2,<4, installed: 2.0.4]
│   ├── idna [required: >=2.5,<4, installed: 2.9]
│   └── urllib3 [required: >=1.21.1,<3, installed: 1.26.5]
├── starlette [required: >=0.27,<0.33, installed: 0.32.0.post1]
│   └── anyio [required: >=3.4.0,<5, installed: 4.1.0]
│       ├── exceptiongroup [required: >=1.0.2, installed: 1.2.0]
│       ├── idna [required: >=2.8, installed: 2.9]
│       └── sniffio [required: >=1.1, installed: 1.3.0]
├── typing-extensions [required: >=4, installed: 4.5.0]
└── Werkzeug [required: >=2.2.1, installed: 2.2.3]
    └── MarkupSafe [required: >=2.1.1, installed: 2.1.2]
content-size-limit-asgi==0.1.5
Cython==0.29.21
defusedxml==0.6.0
docker==6.0.0
├── packaging [required: >=14.0, installed: 20.9]
│   └── pyparsing [required: >=2.0.2, installed: 2.4.7]
├── requests [required: >=2.26.0, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2023.7.22]
│   ├── charset-normalizer [required: >=2,<4, installed: 2.0.4]
│   ├── idna [required: >=2.5,<4, installed: 2.9]
│   └── urllib3 [required: >=1.21.1,<3, installed: 1.26.5]
├── urllib3 [required: >=1.26.0, installed: 1.26.5]
└── websocket-client [required: >=0.32.0, installed: 0.57.0]
    └── six [required: Any, installed: 1.16.0]
docker-pycreds==0.4.0
└── six [required: >=1.4.0, installed: 1.16.0]
docutils==0.15.2
envparse==0.2.0
Flask==2.2.5
├── click [required: >=8.0, installed: 8.1.3]
├── itsdangerous [required: >=2.0, installed: 2.0.0]
├── Jinja2 [required: >=3.0, installed: 3.0.0]
│   └── MarkupSafe [required: >=2.0.0rc2, installed: 2.1.2]
└── Werkzeug [required: >=2.2.2, installed: 2.2.3]
    └── MarkupSafe [required: >=2.1.1, installed: 2.1.2]
frozenlist==1.2.0
future==0.18.3
google-cloud-pubsub==2.7.1
├── google-api-core [required: >=1.26.0,<3.0.0dev, installed: 1.30.0]
│   ├── google-auth [required: >=1.25.0,<2.0dev, installed: 1.28.0]
│   │   ├── cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
│   │   ├── pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
│   │   │   └── pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
│   │   ├── rsa [required: >=3.1.4,<5, installed: 4.7.2]
│   │   │   └── pyasn1 [required: >=0.1.3, installed: 0.4.8]
│   │   ├── setuptools [required: >=40.3.0, installed: 65.5.1]
│   │   └── six [required: >=1.9.0, installed: 1.16.0]
│   ├── googleapis-common-protos [required: >=1.6.0,<2.0dev, installed: 1.51.0]
│   │   └── protobuf [required: >=3.6.0, installed: 3.19.6]
│   ├── packaging [required: >=14.3, installed: 20.9]
│   │   └── pyparsing [required: >=2.0.2, installed: 2.4.7]
│   ├── protobuf [required: >=3.12.0, installed: 3.19.6]
│   ├── pytz [required: Any, installed: 2020.1]
│   ├── requests [required: >=2.18.0,<3.0.0dev, installed: 2.31.0]
│   │   ├── certifi [required: >=2017.4.17, installed: 2023.7.22]
│   │   ├── charset-normalizer [required: >=2,<4, installed: 2.0.4]
│   │   ├── idna [required: >=2.5,<4, installed: 2.9]
│   │   └── urllib3 [required: >=1.21.1,<3, installed: 1.26.5]
│   ├── setuptools [required: >=40.3.0, installed: 65.5.1]
│   └── six [required: >=1.13.0, installed: 1.16.0]
├── grpc-google-iam-v1 [required: >=0.12.3,<0.13dev, installed: 0.12.3]
│   ├── googleapis-common-protos [required: >=1.5.2,<2.0.0dev, installed: 1.51.0]
│   │   └── protobuf [required: >=3.6.0, installed: 3.19.6]
│   └── grpcio [required: >=1.0.0,<2.0.0dev, installed: 1.58.0]
├── grpcio [required: >=1.38.1,<2.0dev, installed: 1.58.0]
├── libcst [required: >=0.3.10, installed: 0.3.20]
│   ├── PyYAML [required: >=5.2, installed: 5.4.1]
│   ├── typing-extensions [required: >=3.7.4.2, installed: 4.5.0]
│   └── typing-inspect [required: >=0.4.0, installed: 0.7.1]
│       ├── mypy-extensions [required: >=0.3.0, installed: 0.4.3]
│       └── typing-extensions [required: >=3.7.4, installed: 4.5.0]
├── packaging [required: >=14.3, installed: 20.9]
│   └── pyparsing [required: >=2.0.2, installed: 2.4.7]
└── proto-plus [required: >=1.7.1, installed: 1.19.0]
    └── protobuf [required: >=3.12.0, installed: 3.19.6]
google-cloud-storage==1.39.0
├── google-auth [required: >=1.11.0,<2.0dev, installed: 1.28.0]
│   ├── cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
│   ├── pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
│   │   └── pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
│   ├── rsa [required: >=3.1.4,<5, installed: 4.7.2]
│   │   └── pyasn1 [required: >=0.1.3, installed: 0.4.8]
│   ├── setuptools [required: >=40.3.0, installed: 65.5.1]
│   └── six [required: >=1.9.0, installed: 1.16.0]
├── google-cloud-core [required: >=1.4.1,<2.0dev, installed: 1.7.1]
│   ├── google-api-core [required: >=1.21.0,<2.0.0dev, installed: 1.30.0]
│   │   ├── google-auth [required: >=1.25.0,<2.0dev, installed: 1.28.0]
│   │   │   ├── cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
│   │   │   ├── pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
│   │   │   │   └── pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
│   │   │   ├── rsa [required: >=3.1.4,<5, installed: 4.7.2]
│   │   │   │   └── pyasn1 [required: >=0.1.3, installed: 0.4.8]
│   │   │   ├── setuptools [required: >=40.3.0, installed: 65.5.1]
│   │   │   └── six [required: >=1.9.0, installed: 1.16.0]
│   │   ├── googleapis-common-protos [required: >=1.6.0,<2.0dev, installed: 1.51.0]
│   │   │   └── protobuf [required: >=3.6.0, installed: 3.19.6]
│   │   ├── packaging [required: >=14.3, installed: 20.9]
│   │   │   └── pyparsing [required: >=2.0.2, installed: 2.4.7]
│   │   ├── protobuf [required: >=3.12.0, installed: 3.19.6]
│   │   ├── pytz [required: Any, installed: 2020.1]
│   │   ├── requests [required: >=2.18.0,<3.0.0dev, installed: 2.31.0]
│   │   │   ├── certifi [required: >=2017.4.17, installed: 2023.7.22]
│   │   │   ├── charset-normalizer [required: >=2,<4, installed: 2.0.4]
│   │   │   ├── idna [required: >=2.5,<4, installed: 2.9]
│   │   │   └── urllib3 [required: >=1.21.1,<3, installed: 1.26.5]
│   │   ├── setuptools [required: >=40.3.0, installed: 65.5.1]
│   │   └── six [required: >=1.13.0, installed: 1.16.0]
│   ├── google-auth [required: >=1.24.0,<2.0dev, installed: 1.28.0]
│   │   ├── cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
│   │   ├── pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
│   │   │   └── pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
│   │   ├── rsa [required: >=3.1.4,<5, installed: 4.7.2]
│   │   │   └── pyasn1 [required: >=0.1.3, installed: 0.4.8]
│   │   ├── setuptools [required: >=40.3.0, installed: 65.5.1]
│   │   └── six [required: >=1.9.0, installed: 1.16.0]
│   └── six [required: >=1.12.0, installed: 1.16.0]
├── google-resumable-media [required: >=1.3.0,<2.0dev, installed: 1.3.1]
│   ├── google-crc32c [required: >=1.0,<2.0dev, installed: 1.1.2]
│   └── six [required: >=1.4.0, installed: 1.16.0]
└── requests [required: >=2.18.0,<3.0.0dev, installed: 2.31.0]
    ├── certifi [required: >=2017.4.17, installed: 2023.7.22]
    ├── charset-normalizer [required: >=2,<4, installed: 2.0.4]
    ├── idna [required: >=2.5,<4, installed: 2.9]
    └── urllib3 [required: >=1.21.1,<3, installed: 1.26.5]
hiredis==2.2.3
importlib-metadata==6.8.0
└── zipp [required: >=0.5, installed: 3.3.2]
more-itertools==8.2.0
openapi-spec-validator==0.7.1
├── jsonschema [required: >=4.18.0,<5.0.0, installed: 4.20.0]
│   ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   ├── jsonschema-specifications [required: >=2023.03.6, installed: 2023.11.2]
│   │   └── referencing [required: >=0.31.0, installed: 0.31.1]
│   │       ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   │       └── rpds-py [required: >=0.7.0, installed: 0.13.2]
│   ├── referencing [required: >=0.28.4, installed: 0.31.1]
│   │   ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   │   └── rpds-py [required: >=0.7.0, installed: 0.13.2]
│   └── rpds-py [required: >=0.7.1, installed: 0.13.2]
├── jsonschema-path [required: >=0.3.1,<0.4.0, installed: 0.3.2]
│   ├── pathable [required: >=0.4.1,<0.5.0, installed: 0.4.3]
│   ├── PyYAML [required: >=5.1, installed: 5.4.1]
│   ├── referencing [required: >=0.28.0,<0.32.0, installed: 0.31.1]
│   │   ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   │   └── rpds-py [required: >=0.7.0, installed: 0.13.2]
│   └── requests [required: >=2.31.0,<3.0.0, installed: 2.31.0]
│       ├── certifi [required: >=2017.4.17, installed: 2023.7.22]
│       ├── charset-normalizer [required: >=2,<4, installed: 2.0.4]
│       ├── idna [required: >=2.5,<4, installed: 2.9]
│       └── urllib3 [required: >=1.21.1,<3, installed: 1.26.5]
├── lazy-object-proxy [required: >=1.7.1,<2.0.0, installed: 1.9.0]
└── openapi-schema-validator [required: >=0.6.0,<0.7.0, installed: 0.6.2]
    ├── jsonschema [required: >=4.19.1,<5.0.0, installed: 4.20.0]
    │   ├── attrs [required: >=22.2.0, installed: 23.1.0]
    │   ├── jsonschema-specifications [required: >=2023.03.6, installed: 2023.11.2]
    │   │   └── referencing [required: >=0.31.0, installed: 0.31.1]
    │   │       ├── attrs [required: >=22.2.0, installed: 23.1.0]
    │   │       └── rpds-py [required: >=0.7.0, installed: 0.13.2]
    │   ├── referencing [required: >=0.28.4, installed: 0.31.1]
    │   │   ├── attrs [required: >=22.2.0, installed: 23.1.0]
    │   │   └── rpds-py [required: >=0.7.0, installed: 0.13.2]
    │   └── rpds-py [required: >=0.7.1, installed: 0.13.2]
    ├── jsonschema-specifications [required: >=2023.5.2,<2024.0.0, installed: 2023.11.2]
    │   └── referencing [required: >=0.31.0, installed: 0.31.1]
    │       ├── attrs [required: >=22.2.0, installed: 23.1.0]
    │       └── rpds-py [required: >=0.7.0, installed: 0.13.2]
    └── rfc3339-validator [required: Any, installed: 0.1.4]
        └── six [required: Any, installed: 1.16.0]
pathlib==1.0.1
pip==23.0.1
pipdeptree==2.13.1
psutil==5.9.0
pyarrow==13.0.0
└── numpy [required: >=1.16.6, installed: 1.26.0]
pyarrow-hotfix==0.5
python-jose==3.1.0
├── ecdsa [required: <1.0, installed: 0.16.1]
│   └── six [required: >=1.9.0, installed: 1.16.0]
├── pyasn1 [required: Any, installed: 0.4.8]
├── rsa [required: Any, installed: 4.7.2]
│   └── pyasn1 [required: >=0.1.3, installed: 0.4.8]
└── six [required: <2.0, installed: 1.16.0]
python-json-logger==2.0.2
secure==0.3.0
SQLAlchemy==2.0.0
├── greenlet [required: !=0.4.17, installed: 2.0.2]
└── typing-extensions [required: >=4.2.0, installed: 4.5.0]
tabulate==0.8.9
uvicorn==0.24.0.post1
├── click [required: >=7.0, installed: 8.1.3]
├── h11 [required: >=0.8, installed: 0.14.0]
└── typing-extensions [required: >=4.0, installed: 4.5.0]
uvloop==0.17.0
wazuh==4.9.0
wheel==0.38.4
xmltodict==0.12.0
yarl==1.7.0
├── idna [required: >=2.0, installed: 2.9]
└── multidict [required: >=4.0, installed: 5.2.0]
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by mhamra** [comment]
### UPDATE
<details>
<summary>New packages</summary>

```
asgiref                   3.7.2
asn1crypto                1.3.0
docker-pycreds            0.4.0
exceptiongroup            1.2.0
h11                       0.14.0
httpcore                  1.0.2
httpx                     0.26.0
jsonschema-path           0.3.2
jsonschema-specifications 2023.11.2
lazy-object-proxy         1.10.0
openapi-schema-validator  0.6.2
pathable                  0.4.3
python-multipart          0.0.6
referencing               0.31.1
rfc3339-validator         0.1.4
rpds-py                   0.15.2
sniffio                   1.3.0
starlette                 0.32.0.post1
uvicorn                   0.24.0.post1
```
</details>

<details>
<summary>Packages to be removed</summary>

```
aiohttp                  3.8.5
aiohttp-cache            2.2.0
aiohttp-cors             0.7.0
aiohttp-jinja2           1.5.1
aioredis                 1.3.1
aiosignal                1.2.0
asn1crypto               1.3.0
async-timeout            4.0.2
envparse                 0.2.0
Flask                    2.2.5
hiredis                  2.2.3
itsdangerous             2.0.0
```
</details>

**Comment by RamosFe** [comment]
## Update

I continue with the upgrade and addition of the packages detailed above.

**Comment by RamosFe** [comment]
## Update

During the installation in an AMD machine, the following error appeared

```

ERROR: Could not find a version that satisfies the requirement anyio (from httpx) (from versions: none)
ERROR: No matching distribution found for anyio
make: *** [install_dependencies] Error 1
chcon: can't apply partial context to unlabeled file ‘/var/ossec/lib/libjemalloc.so.2’
chcon: can't apply partial context to unlabeled file ‘/var/ossec/lib/librouter.so’
chcon: can't apply partial context to unlabeled file ‘/var/ossec/lib/libcontent_manager.so’
chcon: can't apply partial context to unlabeled file ‘/var/ossec/lib/libvulnerability_scanner.so’
chcon: can't apply partial context to unlabeled file ‘/var/ossec/lib/libindexer_connector.so’
chcon: can't apply partial context to unlabeled file ‘/var/ossec/lib/librocksdb.so.8’
```

I continued investigating if there was an error in the package selection or if there were missing dependencies from the Issue description.

**Comment by RamosFe** [comment]
## Update
### Packages changes
After reviewing the dependency tree the following changes were made:
- `asn1crypto` was deleted.
- `anyo` 4.1.0 was added due to being a dependency of `starlette` and `httpx`.

### Final Changes
The final changes are the following:

<details>
<summary>New packages</summary>

```
anyo                        4.1.0
asgiref                   3.7.2
content-size-limit-asgi   0.1.5
docker-pycreds            0.4.0
exceptiongroup            1.2.0
h11                       0.14.0
httpcore                  1.0.2
httpx                     0.26.0
jsonschema-path           0.3.2
jsonschema-specifications 2023.11.2
lazy-object-proxy         1.10.0
openapi-schema-validator  0.6.2
pathable                  0.4.3
python-multipart          0.0.6
referencing               0.31.1
rfc3339-validator         0.1.4
rpds-py                   0.15.2
sniffio                   1.3.0
starlette                 0.32.0.post1
uvicorn                   0.24.0.post1
```
</details>

<details>
<summary>Packages to be removed</summary>

```
aiohttp                  3.8.5
aiohttp-cache            2.2.0
aiohttp-cors             0.7.0
aiohttp-jinja2           1.5.1
aioredis                 1.3.1
aiosignal                1.2.0
asn1crypto               1.3.0
async-timeout            4.0.2
envparse                 0.2.0
Flask                    2.2.5
hiredis                  2.2.3
itsdangerous             2.0.0
```
</details>

</details>

<details>
<summary>Packages to upgrade and unmodified</summary>

#### The packaged uncommented should be upgraded to higher versions.

```
attrs                     23.1.0
# azure-common              1.1.25 
# azure-storage-blob        2.1.0
# azure-storage-common      2.1.0
# boto3                     1.17.85
# botocore                  1.20.85
# cachetools                4.1.0
# certifi                   2023.7.22
# cffi                      1.15.1
# chardet                   3.0.4
# charset-normalizer        2.0.4
# click                     8.1.3
# clickclick                20.10.2
connexion                 3.0.5
# cryptography              41.0.4
Cython                    0.29.36
# defusedxml                0.6.0
# docker                    6.0.0
# docker-pycreds            0.4.0
# docutils                  0.15.2
# ecdsa                     0.16.1
# frozenlist                1.2.0
# future                    0.18.3
# google-api-core           1.30.0
# google-auth               1.28.0
# google-cloud-core         1.7.1
# google-cloud-pubsub       2.7.1
# google-cloud-storage      1.39.0
# google-crc32c             1.1.2
# google-resumable-media    1.3.1
# googleapis-common-protos  1.51.0
# greenlet                  2.0.2
# grpc-google-iam-v1        0.12.3
# grpcio                    1.58.0
# idna                      2.9
importlib-metadata        6.8.0
# inflection                0.3.1
# Jinja2                    3.0.0
# jmespath                  0.9.5
jsonschema                4.20.0
# libcst                    0.3.20
# MarkupSafe                2.1.2
# more-itertools            8.2.0
# multidict                 5.2.0
# mypy-extensions           0.4.3
# numpy                     1.26.0
openapi-spec-validator    0.7.1
# packaging                 20.9
# pathlib                   1.0.1
# pip                       23.3.1
# proto-plus                1.19.0
# protobuf                  3.19.6
# psutil                    5.9.0
# pyarrow                   13.0.0
# pyarrow-hotfix            0.5
# pyasn1                    0.4.8
# pyasn1-modules            0.2.8
# pycparser                 2.21
# pyparsing                 2.4.7
# python-dateutil           2.8.1
# python-jose               3.1.0
# python-json-logger        2.0.2
# pytz                      2020.1
# PyYAML                    5.4.1
# requests                  2.31.0
# rsa                       4.7.2
# s3transfer                0.4.2
secure                    0.3.0
# setuptools                69.0.2
# six                       1.16.0
# SQLAlchemy                2.0.0
# tabulate                  0.8.9
# typing_extensions         4.5.0
# typing-inspect            0.7.1
# urllib3                   1.26.5
# uvloop                    0.17.0
# websocket-client          0.57.0
# Werkzeug                  2.2.3
# wheel                     0.41.3
# xmltodict                 0.12.0
# yarl                      1.7.0
# zipp                      3.3.2
```
</details>

### Build
The installation in `x86` was successful but the API didn´t start due to the following error:

```
Starting Wazuh v4.9.0...
Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh-apid.py", line 344, in <module>
    from api import error_handler, __path__ as api_path
  File "/var/ossec/framework/python/lib/python3.10/site-packages/api/error_handler.py", line 12, in <module>
    from api.middlewares import ip_block, ip_stats, LOGIN_ENDPOINT, RUN_AS_LOGIN_ENDPOINT
  File "/var/ossec/framework/python/lib/python3.10/site-packages/api/middlewares.py", line 27, in <module>
    from api.authentication import generate_keypair, JWT_ALGORITHM
  File "/var/ossec/framework/python/lib/python3.10/site-packages/api/authentication.py", line 25, in <module>
    from wazuh.core.cluster.dapi.dapi import DistributedAPI
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 25, in <module>
    import wazuh.core.manager
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/manager.py", line 17, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
wazuh-apid did not start correctly.
``` 

This is because the code has not yet been migrated from `aiohttp` to `uvicorn`, as described in the following Issue - https://github.com/wazuh/wazuh/issues/21651. Until this migrated is finished, we should block the package creation.

**Comment by Selutario** [comment]
This issue will be affected by the issue below, which is being carried out in 4.8.0:
- https://github.com/wazuh/wazuh/issues/22202
