### ISSUE TITLE
Wazuh Indexer doesn't start 

### ISSUE THREAD

**Issue by pulpon6** [wazuh/wazuh#20865]
|4.7.0-1|Wazuh-indexer|StepbyStep|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

**Comment by pulpon6** [comment]
wazuh-indexer.service - Wazuh-indexer
   Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/wazuh-indexer.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Wed 2023-12-13 12:48:37 CST; 54min ago
     Docs: https://documentation.wazuh.com/
 Main PID: 175761 (code=exited, status=1/FAILURE)
dic 13 12:48:37 wazuh systemd-entrypoint[175761]:         at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
dic 13 12:48:37 wazuh systemd-entrypoint[175761]:         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
dic 13 12:48:37 wazuh systemd-entrypoint[175761]:         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
dic 13 12:48:37 wazuh systemd-entrypoint[175761]:         at org.opensearch.cli.Command.main(Command.java:101)
dic 13 12:48:37 wazuh systemd-entrypoint[175761]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
dic 13 12:48:37 wazuh systemd-entrypoint[175761]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)
dic 13 12:48:37 wazuh systemd-entrypoint[175761]: For complete error details, refer to the log at /var/log/wazuh-indexer/wazuh-cluster.log
dic 13 12:48:37 wazuh systemd[1]: wazuh-indexer.service: Main process exited, code=exited, status=1/FAILURE
dic 13 12:48:37 wazuh systemd[1]: wazuh-indexer.service: Failed with result 'exit-code'.
dic 13 12:48:37 wazuh systemd[1]: Failed to start Wazuh-indexer.

**Comment by pulpon6** [comment]
![image](https://github.com/wazuh/wazuh/assets/76466949/7453b7a6-9c86-48ba-a43b-6e30c760ddca)

**Comment by pulpon6** [comment]
![image](https://github.com/wazuh/wazuh/assets/76466949/7883180e-fe7a-4754-9926-21d6acdc8e50)

**Comment by pulpon6** [comment]
grep -iE 'error|warn' /var/log/wazuh-indexer/wazuh-cluster.log

![image](https://github.com/wazuh/wazuh/assets/76466949/2dad59ea-4997-4a3a-a8b6-179ab1422e49)

**Comment by dsal319** [comment]
has there been any update to this? I am having the same issue.

**Comment by AlexRuiz7** [comment]
Can you check the logs for errors only? All these warnings are not providing any useful information.
