### ISSUE TITLE
Fix `test_upload_configuration` API integration test

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#21401]
|Wazuh version|Component|
|---|---|
| 4.9.0 | Wazuh API test |

## Description

During [merge 4.8.2 into master](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397), multiple API integration tests failed after running `test_upload_configuration`:
```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /home/runner/work/wazuh/wazuh/tests/integration, configfile: pytest.ini
plugins: html-3.1.1, metadata-3.0.0
collected 63 items / 3 deselected / 60 selected

test_api/test_config/test_DOS_blocking_system/test_DOS_blocking_system.py . [  1%]
                                                                         [  1%]
test_api/test_config/test_bruteforce_blocking_system/test_bruteforce_blocking_system.py . [  3%]
                                                                         [  3%]
test_api/test_config/test_cache/test_cache.py ..                         [  6%]
test_api/test_config/test_cors/test_cors.py x.                           [ 10%]
test_api/test_config/test_drop_privileges/test_drop_privileges.py ..     [ 13%]
test_api/test_config/test_experimental_features/test_experimental_features.py . [ [15](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:16)%]
.                                                                        [ [16](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:17)%]
test_api/test_config/test_host_port/test_host_port.py ....               [ [23](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:24)%]
test_api/test_config/test_https/test_https.py ..                         [ [26](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:27)%]
test_api/test_config/test_jwt_token_exp_timeout/test_jwt_token_exp_timeout.py . [ [28](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:29)%]
.                                                                        [ [30](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:31)%]
test_api/test_config/test_logs/test_logs_format.py ........              [ 43%]
test_api/test_config/test_rbac/test_rbac_mode.py ..                      [ 46%]
test_api/test_config/test_request_timeout/test_request_timeout.py .      [ 48%]
test_api/test_config/test_upload_configuration/test_upload_configuration.py . [ 50%]
E                                                                        [ 51%]
test_api/test_middlewares/test_response_postprocessing.py EEEE           [ 58%]
test_api/test_middlewares/test_set_secure_headers.py E                   [ 60%]
test_api/test_rbac/test_add_old_resource.py EEEE                         [ 66%]
test_api/test_rbac/test_manage_admin_resource.py EEEEEEE                 [ 78%]
test_api/test_rbac/test_policy_position.py E                             [ 80%]
test_api/test_rbac/test_remove_resource.py EEEE                          [ 86%]
test_api/test_rbac/test_remove_resources_relation.py EEE                 [ 91%]
test_api/test_statistics/test_statistics_format.py .....                 [100%]

==================================== ERRORS ====================================
```

It seems the mentioned test updates the configuration but does not restore it after finishing, so the manager where it runs stays with this:
```XML
<ossec_config>
  <remote>
    <connection>secure</connection>
    <port>1514</port>
  </remote>
</ossec_config>
```

We need to add a fixture in order to make a backup of the configuration file and restore it after the test is completed.

<details>
<summary>Full output</summary>

```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /home/runner/work/wazuh/wazuh/tests/integration, configfile: pytest.ini
plugins: html-3.1.1, metadata-3.0.0
collected 63 items / 3 deselected / 60 selected

test_api/test_config/test_DOS_blocking_system/test_DOS_blocking_system.py . [  1%]
                                                                         [  1%]
test_api/test_config/test_bruteforce_blocking_system/test_bruteforce_blocking_system.py . [  3%]
                                                                         [  3%]
test_api/test_config/test_cache/test_cache.py ..                         [  6%]
test_api/test_config/test_cors/test_cors.py x.                           [ 10%]
test_api/test_config/test_drop_privileges/test_drop_privileges.py ..     [ 13%]
test_api/test_config/test_experimental_features/test_experimental_features.py . [ [15](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:16)%]
.                                                                        [ [16](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:17)%]
test_api/test_config/test_host_port/test_host_port.py ....               [ 23%]
test_api/test_config/test_https/test_https.py ..                         [ 26%]
test_api/test_config/test_jwt_token_exp_timeout/test_jwt_token_exp_timeout.py . [ 28%]
.                                                                        [ 30%]
test_api/test_config/test_logs/test_logs_format.py ........              [ 43%]
test_api/test_config/test_rbac/test_rbac_mode.py ..                      [ 46%]
test_api/test_config/test_request_timeout/test_request_timeout.py .      [ 48%]
test_api/test_config/test_upload_configuration/test_upload_configuration.py . [ 50%]
E                                                                        [ 51%]
test_api/test_middlewares/test_response_postprocessing.py EEEE           [ 58%]
test_api/test_middlewares/test_set_secure_headers.py E                   [ 60%]
test_api/test_rbac/test_add_old_resource.py EEEE                         [ 66%]
test_api/test_rbac/test_manage_admin_resource.py EEEEEEE                 [ 78%]
test_api/test_rbac/test_policy_position.py E                             [ 80%]
test_api/test_rbac/test_remove_resource.py EEEE                          [ 86%]
test_api/test_rbac/test_remove_resources_relation.py EEE                 [ 91%]
test_api/test_statistics/test_statistics_format.py .....                 [100%]

==================================== ERRORS ====================================
____ ERROR at setup of test_upload_configuration[UPLOAD_TWO_BLOCKS_CONFIG] _____

    control_service('start', daemon=daemon)
/usr/local/lib/python3.10/dist-packages/wazuh_testing/utils/services.py:152: in control_service
    subprocess.check_call(start_process)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/var/ossec/bin/wazuh-apid'],), kwargs = {}, retcode = 1
cmd = ['/var/ossec/bin/wazuh-apid']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/var/ossec/bin/wazuh-apid']' returned non-zero exit status 1.

/usr/lib/python3.10/subprocess.py:369: CalledProcessError
---------------------------- Captured stderr setup -----------------------------
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/configuration.py", line 639, in get_ossec_conf
    data = {section: data[section]}
KeyError: 'global'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh-apid.py", line 270, in <module>
    from api.signals import modify_response_headers, register_background_tasks
  File "/var/ossec/framework/python/lib/python3.10/site-packages/api/signals.py", line [17](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:18), in <module>
    from wazuh.core.manager import query_update_check_service
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/manager.py", line 32, in <module>
    CTI_URL = get_ossec_conf(section=GLOBAL_KEY).get(GLOBAL_KEY, {}).get('cti-url', 'https://cti.wazuh.com')
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/configuration.py", line 644, in get_ossec_conf
    raise WazuhError(1106, extra_message=e.args[0])
wazuh.core.exception.WazuhError: Error 1106 - Requested section not present in configuration: global
------------------------------ Captured log setup ------------------------------
DEBUG    wazuh_testing:conftest.py:[23](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:24)7 Restarting wazuh-apid
ERROR    wazuh_testing:conftest.py:[24](https://github.com/wazuh/wazuh/actions/runs/7491904565/job/20395644712?pr=21397#step:7:25)6 Command '['/var/ossec/bin/wazuh-apid']' returned non-zero exit status 1.
=========================== short test summary info ============================
```

</details>

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Created a fixture to backup the Wazuh configuration and added it to the conflicting test.
