### ISSUE TITLE
Bug in API when trying to read `Update check` config

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#21402]
|Wazuh version|Component|
|---|---|
| 4.8.0 | Wazuh API |

## Description

While reviewing some failing tests in https://github.com/wazuh/wazuh/pull/21397, I found out that the API is unable to start when the configuration is not complete, for instance:
```XML
# cat /var/ossec/etc/ossec.conf 
<ossec_config>
  <remote>
    <connection>secure</connection>
    <port>1514</port>
  </remote>
</ossec_config>
``` 

This happens when the API is started:
```
# /var/ossec/bin/wazuh-apid -f
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/configuration.py", line 639, in get_ossec_conf
    data = {section: data[section]}
KeyError: 'global'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh-apid.py", line 270, in <module>
    from api.signals import modify_response_headers, register_background_tasks
  File "/var/ossec/framework/python/lib/python3.10/site-packages/api/signals.py", line 17, in <module>
    from wazuh.core.manager import query_update_check_service
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/manager.py", line 32, in <module>
    CTI_URL = get_ossec_conf(section=GLOBAL_KEY).get(GLOBAL_KEY, {}).get('cti-url', 'https://cti.wazuh.com')
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/configuration.py", line 644, in get_ossec_conf
    raise WazuhError(1106, extra_message=e.args[0])
wazuh.core.exception.WazuhError: Error 1106 - Requested section not present in configuration: global
```

We need to catch this exception to ignore it and use the default value for the `cti-url` instead, but the API should still start as other services do with the mentioned configuration:
```
# /var/ossec/bin/wazuh-control status
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Handled the exception thrown because of the configuration missing the CTI fields. Validated that the API starts correctly when no values are specified and added the corresponding unit tests.
