### ISSUE TITLE
Analyze and add special characters processing in AWS Custom Logs Buckets integration

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#22220]
| Affected integration |
|---|
| AWS |

## Description

The Custom Logs Buckets integration provided by our AWS integration outputs the following error when trying to fetch some specific object keys that belong to log files present in S3 buckets:
```log
DEBUG: The message is: \{'Records': [\{'eventVersion': '2.1', 'eventSource': 'aws:s3', 'awsRegion': 'us-east-1', 'eventTime': '2024-02-26T00:00:01.182Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': \{'principalId': 'AWS:...'\}, 'requestParameters': \{'sourceIPAddress': '0.0.0.0'\}, 'responseElements': \{'x-amz-request-id': '...', 'x-amz-id-2': '...'\}, 's3': \{'s3SchemaVersion': '1.0', 'configurationId': ...', 'bucket': \{'name': 'BUCKET', 'ownerIdentity': \{'principalId': '...'\}, 'arn': 'arn:aws:s3:::BUCKET'\}, 'object': \{'key': '<prefix>/2024-02-26T00%3A00%3A01.121539146Z.json', 'size': 1585, 'eTag': '...', 'versionId': '...', 'sequencer': '...'\}\}\}]\}\
DEBUG: +++ Error: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.\
Unknown error: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.\
Traceback (most recent call last):\
  File "/var/ossec/wodles/aws/aws-s3.py", line 4246, in <module>\
    main(sys.argv[1:])\
  File "/var/ossec/wodles/aws/aws-s3.py", line 4233, in main\
    asl_queue.sync_events()\
  File "/var/ossec/wodles/aws/aws-s3.py", line 3793, in sync_events\
    self.bucket_handler.process_file(message["route"])\
  File "/var/ossec/wodles/aws/aws-s3.py", line 3589, in process_file\
    formatted_logs = self.obtain_logs(bucket=bucket_path, log_path=log_path)\
  File "/var/ossec/wodles/aws/aws-s3.py", line 3542, in obtain_logs\
    with self.decompress_file(bucket, log_key=log_path) as f:\
  File "/var/ossec/wodles/aws/aws-s3.py", line 673, in decompress_file\
    raw_object = io.BytesIO(self.client.get_object(Bucket=bucket, Key=log_key)['Body'].read())\
  File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call\
    return self._make_api_call(operation_name, kwargs)\
  File "/var/ossec/framework/python/lib/python3.9/site-packages/botocore/client.py", line 705, in _make_api_call\
    raise error_class(parsed_response, operation_name)\
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.}
```

After some research, the error is due to the processing of file names that contain some specific characters, as stated in the [AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html), that require special handling.

We should analyze if modifications are possible in our current implementation to fetch any object from S3 buckets, regardless of the characters that may be present, and carry out the necessary changes,  or if this is not possible due to a limitation in the AWS SDK currently used.

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by fdalmaup** [comment]
# Issue Update

The uploaded message to the SQS Queue, when an object is created in an S3 bucket, contains the object key name value URL encoded as mentioned in the [S3 Event message structure documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html). The user is responsible for uploading objects according to the documentation mentioned in the issue's description, since it may happen as shown in the example, the code was modified to decode the key name value with the `urllib.parse.unquote` method.

<details><summary>Manual execution output after modifications</summary>

```log
# /var/ossec/wodles/aws/aws-s3 --subscriber buckets --queue SQS-QUEUE-NAME --aws_profile dev --debug 3
DEBUG: +++ Debug mode on - Level: 3
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: The SQS queue is: https://queue.amazonaws.com/123456789123/SQS-QUEUE-NAME
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: Retrieving messages from: SQS-QUEUE-NAME
DEBUG: The raw message is: ...
DEBUG: The message is: {'Records': [{'eventVersion': '2.1', 'eventSource': 'aws:s3', 'awsRegion': 'REGION', 'eventTime': '2024-03-20T19:03:09.169Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': 'AWS:REDACTED'}, 'requestParameters': {'sourceIPAddress': '0.0.0.0'}, 'responseElements': {'x-amz-request-id': 'QDJ5J958GNJQG8R5', 'x-amz-id-2': 'jZNmZhlKxVNkyFLqAvAyjwetZEZCvIPpoqoZlR8nUeQfx9lrSCyAQw2GW51I4lpkM2DGITbxxvcPbqiyvmgUwdaGTMdkQBNA'}, 's3': {'s3SchemaVersion': '1.0', 'configurationId': 'Log collection', 'bucket': {'name': 'BUCKET-NAME', 'ownerIdentity': {'principalId': 'PRINCIPAL-ID'}, 'arn': 'arn:aws:s3:::BUCKET-NAME'}, 'object': {'key': '2024-02-26T00%3A00%3A01.json', 'size': 42, 'eTag': '0ce9768e6b5e494a4bd56ef09ff87d8d', 'sequencer': '0065FB32ED1EEE8938'}}}]}
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "2024-02-26T00:00:01.json", "s3bucket": "BUCKET-NAME"}, "example": "2024-02-26T00:00:01 test log", "source": "custom"}}
DEBUG: Message deleted from queue: SQS-QUEUE-NAME
DEBUG: Retrieving messages from: SQS-QUEUE-NAME
DEBUG: The raw message is: ...
DEBUG: The message is: {'Records': [{'eventVersion': '2.1', 'eventSource': 'aws:s3', 'awsRegion': 'REGION', 'eventTime': '2024-03-20T19:03:19.605Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': 'AWS:REDACTED'}, 'requestParameters': {'sourceIPAddress': '0.0.0.0'}, 'responseElements': {'x-amz-request-id': '76CGY2HRE76M4WSH', 'x-amz-id-2': 'ihoUAXUm9HR7jIi0kkVLcrMzN/wF5vSmsHSFjQ2YNkTXe88hZPpIdGHY+wQzI/NO8bSuu6dh8hYEZ9VAdMVMeliMqi0XmRdg'}, 's3': {'s3SchemaVersion': '1.0', 'configurationId': 'Log collection', 'bucket': {'name': 'BUCKET-NAME', 'ownerIdentity': {'principalId': 'PRINCIPAL-ID'}, 'arn': 'arn:aws:s3:::BUCKET-NAME'}, 'object': {'key': '2024-02-26T00%3A00%2501.json', 'size': 42, 'eTag': '0ce9768e6b5e494a4bd56ef09ff87d8d', 'sequencer': '0065FB32F78EA5E54F'}}}]}
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "2024-02-26T00:00%01.json", "s3bucket": "BUCKET-NAME"}, "example": "2024-02-26T00:00:01 test log", "source": "custom"}}
DEBUG: Message deleted from queue: SQS-QUEUE-NAME
DEBUG: Retrieving messages from: SQS-QUEUE-NAME
```

</details>

The Unit Tests related to this code section were added in https://github.com/wazuh/wazuh/pull/20111 pointing to branch `master` (in that moment representing the `4.9.0` version). Because of that the new test case containing a key with a value requiring the URL decoding cannot be added in `4.8.2`.
