### ISSUE TITLE
Investigate a strange behavior with the integrity check

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#22516]
## Description

During the execution of #22498, we observe a strange behavior with the `Integrity Check`.

```
2024/03/13 15:54:30 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2024/03/13 15:54:38 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Error asking for permission: Error 3020 - Timeout sending request: syn_i_w_m_p
2024/03/13 15:54:40 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2024/03/13 15:54:50 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2024/03/13 15:55:00 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2024/03/13 15:55:07 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Error asking for permission: Error 3020 - Timeout sending request: syn_i_w_m_p
2024/03/13 15:55:10 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Main] Successfully connected to master.
```

When a the worker is not connected to the master, none of its tasks should be running. However, as seen above, `Integrity check` timeouts are being logged while the connection has not yet occurred. Furthermore, these timeouts continue to occur from this moment until the end of the execution, even though the Integrity check task is occurring successfully:

```
2024/03/13 15:56:04 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Permission to synchronize granted.
2024/03/13 15:56:04 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Starting.
2024/03/13 15:56:04 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Compressing 'files_metadata.json' of 34 files.
2024/03/13 15:56:04 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Sending zip file.
2024/03/13 15:56:04 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Zip file sent.
2024/03/13 15:56:04 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Main] Command received: 'b'syn_m_c_ok''
2024/03/13 15:56:04 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Finished in 0.009s. Sync not required.
2024/03/13 15:56:05 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Error asking for permission: Error 3020 - Timeout sending request: syn_i_w_m_p
```

We need to investigate and try to replicate this behavior and see what's going on.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
# Issue Update

- I have tried to replicate the error in a small cluster of a master and a worker. Manually stopping the master and checking the `cluster.log` file did not show the error messages mentioned in the description. 
- No differences that may have generated the misbehavior were found at the moment when comparing the `v4.7.3` version, which did not have the mentioned error, and the one that presented the error `v4.8.0-beta4`.
- The `Error asking for permission: Error 3020 - Timeout sending request: syn_i_w_m_p` message is raised in `wazuh.core.cluster.common.SyncTask.request_permission`. The method is called in the `WorkerHandler.sync_integrity` method via an instance of `wazuh.core.cluster.common.SyncFiles` which inherits from `SyncTask`.

**Comment by fdalmaup** [comment]
# Issue Update

The `Integrity check` task works as follows:
- Asks permission from the master
- Sends a zip file (`compressed_data`) containing the has of the files that must remain synchronized.
- Receives a zip file from the master which may contain only the same hashes if the files are synced or the hashes and the files that require to be created/updated.
- Finally, the `compressed_data` file is deleted.

After reviewing the complete set of logs with the team, it was found that before the errors mentioned in the description, the following error was logged:
```log
2024/03/13 15:53:20 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B486_manager_12] [Integrity check] Error synchronizing integrity: [Errno 2] No such file or directory: '/var/ossec/queue/cluster/CLUSTER-Workload_benchmarks_metrics_B486_manager_12/CLUSTER-Workload_benchmarks_metrics_B486_manager_12-1710345200.262538-2c3270a7fdbb43128ba75094831cfd43.zip'
```
This error was raised in the `SyncFiles.sync` method. Considering this, the error was forced by putting a `sleep()` inside said method and stopping the master node. The result was the replication of the issue's description error:
<details><summary>cluster.log filtered by </summary>

```log
2024/03/18 13:52:45 INFO: [Worker 7196062a79c9] [Main] The master closed the connection
024/03/18 13:52:45 DEBUG: [Worker 7196062a79c9] [Main] Removing '/var/ossec/queue/cluster/7196062a79c9'.
2024/03/18 13:52:45 DEBUG: [Worker 7196062a79c9] [Main] Removed '/var/ossec/queue/cluster/7196062a79c9'.
2024/03/18 13:52:45 ERROR: [Worker 7196062a79c9] [Integrity check] Error synchronizing integrity: [Errno 2] No such file or directory: '/var/ossec/queue/cluster/7196062a79c9/7196062a79c9-1710780751.566399-d853aa1cbc96439c8ca67569eebf6915.zip'
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 1464, in sync
    await asyncio.sleep(30)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/worker.py", line 535, in sync_integrity
    await integrity_check.sync(files={}, files_metadata=self.server.integrity_control,
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 1492, in sync
    os.unlink(compressed_data)
FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/queue/cluster/7196062a79c9/7196062a79c9-1710780751.566399-d853aa1cbc96439c8ca67569eebf6915.zip'
2024/03/18 13:52:55 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2024/03/18 13:52:55 DEBUG: [Local Server] [Keep alive] Calculating.
2024/03/18 13:52:55 DEBUG: [Local Server] [Keep alive] Calculated.
2024/03/18 13:52:55 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/client.py", line 99, in start
    transport, protocol = await self.loop.create_connection(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.18.0.3', 1516)
2024/03/18 13:53:05 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/client.py", line 99, in start
    transport, protocol = await self.loop.create_connection(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.18.0.3', 1516)
2024/03/18 13:53:15 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/client.py", line 99, in start
    transport, protocol = await self.loop.create_connection(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.18.0.3', 1516)
2024/03/18 13:53:25 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/client.py", line 99, in start
    transport, protocol = await self.loop.create_connection(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.18.0.3', 1516)
2024/03/18 13:53:34 ERROR: [Worker 7196062a79c9] [Integrity check] Error asking for permission: Error 3020 - Timeout sending request: syn_i_w_m_p
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 44, in read
    await self.received_response.wait()
  File "/var/ossec/framework/python/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 530, in send_request
    response_data = await asyncio.wait_for(response.read(),
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 1371, in request_permission
    result = await self.server.send_request(command=self.cmd + b'_p', data=b'')
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 536, in send_request
    raise exception.WazuhClusterError(3020, extra_message=command.decode())
wazuh.core.exception.WazuhClusterError: Error 3020 - Timeout sending request: syn_i_w_m_p
2024/03/18 13:53:35 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/client.py", line 99, in start
    transport, protocol = await self.loop.create_connection(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.18.0.3', 1516)
2024/03/18 13:53:45 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/client.py", line 99, in start
    transport, protocol = await self.loop.create_connection(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.18.0.3', 1516)
2024/03/18 13:53:55 DEBUG: [Local Server] [Keep alive] Calculating.
2024/03/18 13:53:55 DEBUG: [Local Server] [Keep alive] Calculated.
2024/03/18 13:53:55 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/client.py", line 99, in start
    transport, protocol = await self.loop.create_connection(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.18.0.3', 1516)
2024/03/18 13:54:03 ERROR: [Worker 7196062a79c9] [Integrity check] Error asking for permission: Error 3020 - Timeout sending request: syn_i_w_m_p
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 44, in read
    await self.received_response.wait()
  File "/var/ossec/framework/python/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 530, in send_request
    response_data = await asyncio.wait_for(response.read(),
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 1371, in request_permission
    result = await self.server.send_request(command=self.cmd + b'_p', data=b'')
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 536, in send_request
    raise exception.WazuhClusterError(3020, extra_message=command.decode())
wazuh.core.exception.WazuhClusterError: Error 3020 - Timeout sending request: syn_i_w_m_p
2024/03/18 13:54:05 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/client.py", line 99, in start
    transport, protocol = await self.loop.create_connection(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/var/ossec/framework/python/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/var/ossec/framework/python/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.18.0.3', 1516)
2024/03/18 13:54:15 INFO: [Worker 7196062a79c9] [Main] Successfully connected to master.
2024/03/18 13:54:24 DEBUG: [Worker 7196062a79c9] [Integrity check] Permission to synchronize granted.
2024/03/18 13:54:24 INFO: [Worker 7196062a79c9] [Integrity check] Starting.
2024/03/18 13:54:24 DEBUG: [Worker 7196062a79c9] [Integrity check] Compressing 'files_metadata.json' of 34 files.
2024/03/18 13:54:24 DEBUG: [Worker 7196062a79c9] [Integrity check] Sending zip file.
2024/03/18 13:54:24 DEBUG: [Worker 7196062a79c9] [Integrity check] Zip file sent.
2024/03/18 13:54:24 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'syn_m_c_ok''
2024/03/18 13:54:24 INFO: [Worker 7196062a79c9] [Integrity check] Finished in 0.058s. Sync not required.
2024/03/18 13:54:25 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Permission to synchronize granted.
2024/03/18 13:54:25 INFO: [Worker 7196062a79c9] [Agent-info sync] Starting.
2024/03/18 13:54:25 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Obtained 1 chunks of data in 0.002s.
2024/03/18 13:54:25 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Sending chunks.
2024/03/18 13:54:25 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'syn_m_a_e''
2024/03/18 13:54:25 INFO: [Worker 7196062a79c9] [Agent-info sync] Finished in -10799.966s. Updated 1 chunks.
2024/03/18 13:54:32 ERROR: [Worker 7196062a79c9] [Integrity check] Error asking for permission: Error 3020 - Timeout sending request: syn_i_w_m_p
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 44, in read
    await self.received_response.wait()
  File "/var/ossec/framework/python/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 530, in send_request
    response_data = await asyncio.wait_for(response.read(),
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 1371, in request_permission
    result = await self.server.send_request(command=self.cmd + b'_p', data=b'')
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 536, in send_request
    raise exception.WazuhClusterError(3020, extra_message=command.decode())
wazuh.core.exception.WazuhClusterError: Error 3020 - Timeout sending request: syn_i_w_m_p
2024/03/18 13:54:35 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Permission to synchronize granted.
2024/03/18 13:54:35 INFO: [Worker 7196062a79c9] [Agent-info sync] Starting.
2024/03/18 13:54:35 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Obtained 1 chunks of data in 0.002s.
2024/03/18 13:54:35 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Sending chunks.
2024/03/18 13:54:35 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'syn_m_a_e''
2024/03/18 13:54:35 INFO: [Worker 7196062a79c9] [Agent-info sync] Finished in -10799.969s. Updated 1 chunks.
2024/03/18 13:54:36 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'new_str''
2024/03/18 13:54:36 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'str_upd''
2024/03/18 13:54:36 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'syn_g_m_w''
2024/03/18 13:54:36 INFO: [Worker 7196062a79c9] [Agent-groups recv] Starting.
2024/03/18 13:54:36 DEBUG: [Worker 7196062a79c9] [Agent-groups recv] 1/1 chunks updated in wazuh-db in 0.004s.
2024/03/18 13:54:36 DEBUG: [Worker 7196062a79c9] [Agent-groups recv] Obtained 1 chunks of data in 0.001s.
2024/03/18 13:54:36 DEBUG: [Worker 7196062a79c9] [Agent-groups recv] The checksum of both databases match. 
2024/03/18 13:54:36 INFO: [Worker 7196062a79c9] [Agent-groups recv] Finished in 0.023s. Updated 1 chunks.
2024/03/18 13:54:45 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Permission to synchronize granted.
2024/03/18 13:54:45 INFO: [Worker 7196062a79c9] [Agent-info sync] Starting.
2024/03/18 13:54:45 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Obtained 1 chunks of data in 0.002s.
2024/03/18 13:54:45 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Sending chunks.
2024/03/18 13:54:45 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'syn_m_a_e''
2024/03/18 13:54:45 INFO: [Worker 7196062a79c9] [Agent-info sync] Finished in -10799.972s. Updated 1 chunks.
2024/03/18 13:54:46 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'new_str''
2024/03/18 13:54:46 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'str_upd''
2024/03/18 13:54:46 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'syn_g_m_w''
2024/03/18 13:54:46 INFO: [Worker 7196062a79c9] [Agent-groups recv] Starting.
2024/03/18 13:54:46 DEBUG: [Worker 7196062a79c9] [Agent-groups recv] 1/1 chunks updated in wazuh-db in 0.010s.
2024/03/18 13:54:46 DEBUG: [Worker 7196062a79c9] [Agent-groups recv] Obtained 1 chunks of data in 0.002s.
2024/03/18 13:54:46 DEBUG: [Worker 7196062a79c9] [Agent-groups recv] The checksum of both databases match. 
2024/03/18 13:54:46 INFO: [Worker 7196062a79c9] [Agent-groups recv] Finished in 0.027s. Updated 1 chunks.
2024/03/18 13:54:55 DEBUG: [Local Server] [Keep alive] Calculating.
2024/03/18 13:54:55 DEBUG: [Local Server] [Keep alive] Calculated.
2024/03/18 13:54:55 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Permission to synchronize granted.
2024/03/18 13:54:55 INFO: [Worker 7196062a79c9] [Agent-info sync] Starting.
2024/03/18 13:54:55 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Obtained 1 chunks of data in 0.001s.
2024/03/18 13:54:55 DEBUG: [Worker 7196062a79c9] [Agent-info sync] Sending chunks.
2024/03/18 13:54:55 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'syn_m_a_e''
2024/03/18 13:54:55 INFO: [Worker 7196062a79c9] [Agent-info sync] Finished in -10799.977s. Updated 1 chunks.
2024/03/18 13:54:56 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'new_str''
2024/03/18 13:54:56 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'str_upd''
2024/03/18 13:54:56 DEBUG: [Worker 7196062a79c9] [Main] Command received: 'b'syn_g_m_w''
2024/03/18 13:54:56 INFO: [Worker 7196062a79c9] [Agent-groups recv] Starting.
2024/03/18 13:54:56 DEBUG: [Worker 7196062a79c9] [Agent-groups recv] 1/1 chunks updated in wazuh-db in 0.010s.
2024/03/18 13:54:56 DEBUG: [Worker 7196062a79c9] [Agent-groups recv] Obtained 1 chunks of data in 0.001s.
2024/03/18 13:54:56 DEBUG: [Worker 7196062a79c9] [Agent-groups recv] The checksum of both databases match. 
2024/03/18 13:54:56 INFO: [Worker 7196062a79c9] [Agent-groups recv] Finished in 0.022s. Updated 1 chunks.
2024/03/18 13:55:01 ERROR: [Worker 7196062a79c9] [Integrity check] Error asking for permission: Error 3020 - Timeout sending request: syn_i_w_m_p
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 44, in read
    await self.received_response.wait()
  File "/var/ossec/framework/python/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 530, in send_request
    response_data = await asyncio.wait_for(response.read(),
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 1371, in request_permission
    result = await self.server.send_request(command=self.cmd + b'_p', data=b'')
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 536, in send_request
    raise exception.WazuhClusterError(3020, extra_message=command.decode())
wazuh.core.exception.WazuhClusterError: Error 3020 - Timeout sending request: syn_i_w_m_p
```

</details>

After reviewing the code and the execution flow a solution was developed and now the `FileNotFoundError` exception is captured. The origin of the problem seemed to be the following: 
- The `Worker` adds the `sync_integrity` task from `WorkerHandler` as part of its tasks to be executed asynchronously having the `SyncFiles.sync` as part of the instructions.
- When the connection to the master is lost, the file corresponding to `compressed_data` is deleted as part of the code of `WorkerHandler.connection_lost` method (added in https://github.com/wazuh/wazuh/pull/17886). This generated the file deletion inside `SyncFiles.sync` to raise the found exception, which did not allow for the task to be canceled due to it ending with an error and left it trying to send commands to the master with the `request_permission` method.
