### ISSUE TITLE
Unit tests for vulnerability scanner don't pass 

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#22570]
|Wazuh version|Component|Install type|Install method|Platform|Source|Previous|
|---|---|---|---|---|--|--|
| 4.8.0-beta4 | Unit tests | Manager | Sources | Ubuntu 22 | #22527 | #21819|

### Commands

```shell
make deps
make TARGET=server DEBUG=1 TEST=1
./wazuh_modules/vulnerability_detection/test_wm_vulnerability_detection 
```

### Result

Case 1:
```
[==========] tests_configuration: Running 12 test(s).
[ RUN      ] test_read_custom_cti_url_full_configuration
2024/03/15 12:01:07 unset: ERROR: (1226): Error reading XML file 'etc/ossec.conf':  (line 0).
```

Case 2:
```
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
```

[result-ctest.txt](https://github.com/wazuh/wazuh/files/14617275/result-ctest.txt)

**Comment by MiguelazoDS** [comment]
Unable to reproduce this error with ctest 

![image](https://github.com/wazuh/wazuh/assets/13010397/13bdd96c-57dc-4329-bc67-90263441828b)
![image](https://github.com/wazuh/wazuh/assets/13010397/186d8fd1-5d62-4f14-9272-885aca65733c)

The issue https://github.com/wazuh/wazuh/issues/22527 reports that there are no errors for test_wm_vulnerability_detection what mean that running with ctest passed. 

![image](https://github.com/wazuh/wazuh/assets/13010397/6993a78a-f9cb-47f5-ac8f-db264ab5838e)

From a random PR the test are executed with ctest 
https://github.com/wazuh/wazuh/pull/22621/checks?check_run_id=22906056859

There are errors for vulnerability_scanner_unit_tests (but they are not the same as test_wm_vulnerability_detection)

![image](https://github.com/wazuh/wazuh/assets/13010397/02fa23a2-024a-4f4e-8a8e-7876db2027e2)

**Comment by MiguelazoDS** [comment]
# Update 

Unable to reproduce vulnerability_scanner_unit_tests failing test 

![image](https://github.com/wazuh/wazuh/assets/13010397/9bb356c2-7bc8-433f-9320-4946fe7fd000)

**Comment by MiguelazoDS** [comment]
An error was found related to the path length during the initialization of sun_path (size 108) 

```
9: ==55777==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffef97f0660 at pc 0x7f400931fe67 bp 0x7ffef97f01f0 sp 0x7ffef97ef998
9: WRITE of size 122 at 0x7ffef97f0660 thread T0
9:     #0 0x7f400931fe66 in __interceptor_memmove ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:810
9:     #1 0x5584015e45da in char* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<char>(char const*, char const*, char*) /usr/include/c++/11/bits/stl_algobase.h:431
9:     #2 0x5584015c248e in char* std::__copy_move_a2<false, char const*, char*>(char const*, char const*, char*) /usr/include/c++/11/bits/stl_algobase.h:495
9:     #3 0x5584015655f7 in char* std::__copy_move_a1<false, char const*, char*>(char const*, char const*, char*) /usr/include/c++/11/bits/stl_algobase.h:522
9:     #4 0x558401519126 in char* std::__copy_move_a<false, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char*>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char*) /usr/include/c++/11/bits/stl_algobase.h:529
9:     #5 0x5584014bf5eb in char* std::copy<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char*>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char*) /usr/include/c++/11/bits/stl_algobase.h:620
9:     #6 0x558401b1cfcf in UnixAddress::address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/shared_modules/utils/socketWrapper.hpp:85
9:     #7 0x558401b233e8 in SocketServer<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&) /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/shared_modules/utils/socketServer.hpp:132
9:     #8 0x558401bb07e3 in FetchAllAgentsFromGlobalDBTest::SetUp() /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/wazuh_modules/vulnerability_scanner/tests/unit/fetchAllAgentsFromGlobalDb_test.hpp:41
9:     #9 0x558402424494 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/src/gtest.cc:2607
9:     #10 0x55840241d096 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/src/gtest.cc:2643
9:     #11 0x5584023f1ff7 in testing::Test::Run() /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/src/gtest.cc:2677
9:     #12 0x5584023f2aff in testing::TestInfo::Run() /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/src/gtest.cc:2861
9:     #13 0x5584023f3406 in testing::TestSuite::Run() /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/src/gtest.cc:3015
9:     #14 0x558402403318 in testing::internal::UnitTestImpl::RunAllTests() /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/src/gtest.cc:5855
9:     #15 0x55840242541b in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/src/gtest.cc:2607
9:     #16 0x55840241e162 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/src/gtest.cc:2643
9:     #17 0x558402401a80 in testing::UnitTest::Run() /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/src/gtest.cc:5438
9:     #18 0x558401bf92ba in RUN_ALL_TESTS() /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/external/googletest/googletest/include/gtest/gtest.h:2490
9:     #19 0x558401bf8f73 in main /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/wazuh_modules/vulnerability_scanner/tests/unit/main.cpp:17
9:     #20 0x7f400585fd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
9:     #21 0x7f400585fe3f in __libc_start_main_impl ../csu/libc-start.c:392
9:     #22 0x558400cbc724 in _start (/home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/build/wazuh_modules/vulnerability_scanner/tests/unit/vulnerability_scanner_unit_tests+0x9795724)
9: 
9: Address 0x7ffef97f0660 is located in stack of thread T0 at offset 384 in frame
9:     #0 0x558401b22c03 in SocketServer<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&) /home/vagrant/wazuh-tools/testing/wazuh-v4.8.0-beta4/src/shared_modules/utils/socketServer.hpp:121
9: 
9:   This frame has 4 object(s):
9:     [48, 56) '<unknown>'
9:     [80, 120) '<unknown>'
9:     [160, 200) '<unknown>'
9:     [240, 384) 'unixAddressBuilder' (line 130) <== Memory access at offset 384 overflows this variable
9: HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
9:       (longjmp and C++ exceptions *are* supported)
9: SUMMARY: AddressSanitizer: stack-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:810 in __interceptor_memmove
9: Shadow bytes around the buggy address:
9:   0x10005f2f6070: 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 f2
9:   0x10005f2f6080: f2 f2 00 f3 f3 f3 00 00 00 00 00 00 00 00 00 00
9:   0x10005f2f6090: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
9:   0x10005f2f60a0: f1 f1 00 f2 f2 f2 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2
9:   0x10005f2f60b0: 00 00 00 00 00 f2 f2 f2 f2 f2 00 00 00 00 00 00
9: =>0x10005f2f60c0: 00 00 00 00 00 00 00 00 00 00 00 00[f3]f3 f3 f3
9:   0x10005f2f60d0: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
9:   0x10005f2f60e0: 00 00 f1 f1 f1 f1 00 f2 f2 f2 f8 f8 f2 f2 00 00
9:   0x10005f2f60f0: 00 00 f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00
9:   0x10005f2f6100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
9:   0x10005f2f6110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
9: Shadow byte legend (one shadow byte represents 8 application bytes):
9:   Addressable:           00
9:   Partially addressable: 01 02 03 04 05 06 07 
9:   Heap left redzone:       fa
9:   Freed heap region:       fd
9:   Stack left redzone:      f1
9:   Stack mid redzone:       f2
9:   Stack right redzone:     f3
9:   Stack after return:      f5
9:   Stack use after scope:   f8
9:   Global redzone:          f9
9:   Global init order:       f6
9:   Poisoned by user:        f7
9:   Container overflow:      fc
9:   Array cookie:            ac
9:   Intra object redzone:    bb
9:   ASan internal:           fe
9:   Left alloca redzone:     ca
9:   Right alloca redzone:    cb
9:   Shadow gap:              cc
9: ==55777==ABORTING
 9/11 Test  #9: vulnerability_scanner_unit_tests ........***Failed    7.86 sec
```
