### ISSUE TITLE
Exception in ASGI application when bearer token is not included

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#22735]
|Component|
|---|
| Wazuh API |

## Description
It seems there is an error when the Bearer token is not included:
```
# curl -k -X GET "https://localhost:55000/?pretty=true" -H "Authorization: Bearer  "  
Internal Server Error
```
API log output:
```
2024/04/04 10:37:05 ERROR: Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
  |     yield
  |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/var/ossec/framework/python/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/var/ossec/framework/python/lib/python3.10/contextlib.py", line 153, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/_utils.py", line 88, in collapse_excgroups
    |     raise exc
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/api/middlewares.py", line 236, in dispatch
    |     await access_log(ConnexionRequest.from_starlette_request(request), response, prev_time)
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/api/middlewares.py", line 83, in access_log
    |     auth_type, user_passw = AbstractSecurityHandler.get_auth_header_value(request)
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/connexion/security.py", line 140, in get_auth_header_value
    |     raise OAuthProblem(detail="Invalid authorization header")
    | connexion.exceptions.OAuthProblem: 401: Invalid authorization header
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/var/ossec/framework/python/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/_utils.py", line 88, in collapse_excgroups
    raise exc
  File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/api/middlewares.py", line 236, in dispatch
    await access_log(ConnexionRequest.from_starlette_request(request), response, prev_time)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/api/middlewares.py", line 83, in access_log
    auth_type, user_passw = AbstractSecurityHandler.get_auth_header_value(request)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/connexion/security.py", line 140, in get_auth_header_value
    raise OAuthProblem(detail="Invalid authorization header")
connexion.exceptions.OAuthProblem: 401: Invalid authorization header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/var/ossec/framework/python/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/connexion/apps/abstract.py", line 284, in __call__
    return await self.middleware(scope, receive, send)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/connexion/middleware/main.py", line 501, in __call__
    await self.app(scope, receive, send)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    await response(scope, receive, send)
TypeError: 'coroutine' object is not callable
``` 

## To do
This case should be correctly handled so it behaves the same way as before (this example below is **4.7.3**):
```
# curl -k -X GET "https://localhost:55000/?pretty=true" -H "Authorization: Bearer  "
{"title": "Unauthorized", "detail": "No authorization token provided"}
```
api.log:
```
2024/04/04 10:50:18 INFO: unknown_user 127.0.0.1 "GET /" with parameters {"pretty": "true"} and body {} done in 0.001s: 401
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Updated the `WazuhAccessLoggerMiddleware` middleware position and logged unauthorized request attempts.

**Comment by GGP1** [comment]
## Update

Modified the middleware position back to `BEFORE_EXCEPTION`, handled the middleware exception when reading the Authorization header value and added a unit test.
