### ISSUE TITLE
Connexion 3.0 - Failed IT - Groups configuration

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#22743]
|Wazuh version|Component|
|---|---|
| 4.9 | API |

## Description

In the run of the tests for Issue https://github.com/wazuh/wazuh/issues/20795 the following error appeared in the integration tests for the endpoint `PUT /groups/{group_id}/configuration`:

```
=================================== FAILURES ===================================
_ /tmp/Test_integration_endpoints_B4426_test_files/api/test/integration/test_agent_PUT_endpoints.tavern.yaml::PUT /groups/{group_id}/configuration _
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzEyMjIzNTExLCJleHAiOjE3MTIyMjQ0MTEsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.Ab9h65PWLAS3OEw37oH-4xDW7Mymc4QvNox9qJ2Qwz6vzB04is3eY5QFflvB1CqTyXCI3g0RJQCY7ZjPMgBry0YJAQS5FgEub4IP-rh6NmsKTFJGOGeCKKLmmFgUsfSEtrbEljppIiirHjwCZAyOPC-y1ISLpZ6Oeo9lfyVaWz8yJT3F'

Source test stage (line 278):
  - name: Try to update configuration using an empty file
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/groups/group1/configuration"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
        content-type: "application/xml"
    response:
      status_code: 400
      json:
        error: 1112



Formatted stage:
  name: Try to update configuration using an empty file
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzEyMjIzNTExLCJleHAiOjE3MTIyMjQ0MTEsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.Ab9h65PWLAS3OEw37oH-4xDW7Mymc4QvNox9qJ2Qwz6vzB04is3eY5QFflvB1CqTyXCI3g0RJQCY7ZjPMgBry0YJAQS5FgEub4IP-rh6NmsKTFJGOGeCKKLmmFgUsfSEtrbEljppIiirHjwCZAyOPC-y1ISLpZ6Oeo9lfyVaWz8yJT3F
      content-type: application/xml
    method: PUT
    url: 'https://localhost:55000/groups/group1/configuration'
    verify: false
  response:
    json:
      error: 1112
    status_code: 400

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Try to update configuration using an empty file' failed:
    - Key mismatch: (expected["error"] = '1112' (type = <class 'int'>), actual["error"] = '1912' (type = <class 'int'>))
------------------------------ Captured log call -------------------------------
ERROR    tavern.response.base:base.py:41 Key mismatch: (expected["error"] = '1112' (type = <class 'int'>), actual["error"] = '1912' (type = <class 'int'>))
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'detail': 'B...Request', ...} == {'error': 1112}
  Differing items:
  {'error': 1912} != {'error': 1112}
  Left contains 4 more items:
  {'detail': 'Body is empty',
   'remediation': 'Please, check the content of the file to be uploaded',
   'title': 'Bad Request',
   'type': 'about:blank'}...
  
  ...Full output truncated (11 lines hidden), use '-vv' to show

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert 1912 == 1112

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/response/base.py", line 97, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/util/dict_util.py", line 464, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tavern/util/dict_util.py", line 550, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(
tavern.util.exceptions.KeyMismatchError: Key mismatch: (expected["error"] = '1112' (type = <class 'int'>), actual["error"] = '1912' (type = <class 'int'>))
```

**Comment by GGP1** [comment]
## Update

Changed the test case expected error code.
