### ISSUE TITLE
SYSCOLLECTOR Test Fails for Windows Agents

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#22853]
## Description

Related to https://github.com/wazuh/wazuh/issues/22823

During the tests of [Release 4.8.0 - Beta 5 - Integration tests](https://github.com/wazuh/wazuh/issues/22823) I have detected an error in Windows Agent.

![image](https://github.com/wazuh/wazuh/assets/54536265/956c9761-45b4-443a-b567-4da0529fc502)

<details>
  <summary>Pipeline Logs</summary>
  <br/>

```console
11:54:47  TASK [Launch windows pytests] **************************************************
11:54:47  task path: /home/ec2-user/workspace/Test_integration/quality/tests/integration/test_integration.yaml:37
11:54:47  fatal: [ID2_B46780_Test_integration_windows_agent]: FAILED! => {
11:54:47      "ansible_async_watchdog_pid": 1760,
11:54:47      "ansible_job_id": "743694548092.3548",
11:54:47      "changed": true,
11:54:47      "cmd": "powershell.exe -",
11:54:47      "delta": "0:04:57.644994",
11:54:47      "end": "2024-04-08 09:54:34.831352",
11:54:47      "failed_when_result": true,
11:54:47      "finished": 1,
11:54:47      "rc": 1,
11:54:47      "results_file": "C:\\Users\\Jenkins\\.ansible_async\\743694548092.3548",
11:54:47      "start": "2024-04-08 09:49:37.186358",
11:54:47      "started": 1
11:54:47  }
11:54:47  
11:54:47  MSG:
11:54:47  
11:54:47  non-zero return code
11:54:47  Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/windows/win_stat.ps1
11:54:47  Pipelining is enabled.
11:54:47  <172.31.9.145> ESTABLISH WINRM CONNECTION FOR USER: Jenkins on PORT 5986 TO 172.31.9.145
11:54:47  EXEC (via pipeline wrapper)
11:54:50  <172.31.9.145> FETCH "C:\tmp\Test_integration_B46780_20240408095436\pytest_plain_report.txt" TO "/home/ec2-user/workspace/Test_integration/windows_agent_tests_Test_integration_B46780_20240408095436.txt"
11:54:51  
```

```console
11:54:59  Playbook run took 0 days, 0 hours, 5 minutes, 27 seconds
11:54:59  FATAL: command execution failed
11:54:59  hudson.AbortException: Ansible playbook execution failed
11:54:59  	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:262)
11:54:59  	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:430)
11:54:59  	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:351)
11:54:59  	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
11:54:59  	at hudson.security.ACL.impersonate2(ACL.java:449)
11:54:59  	at hudson.security.ACL.impersonate(ACL.java:461)
11:54:59  	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
11:54:59  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
11:54:59  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
11:54:59  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
11:54:59  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
11:54:59  	at java.base/java.lang.Thread.run(Thread.java:829)
11:54:59  [Pipeline] echo
11:54:59  hudson.AbortException: Ansible playbook execution failed
11:54:59  
11:54:59  [Pipeline] }
11:54:59  [Pipeline] // stage
11:54:59  [Pipeline] }
11:54:59  Failed in branch windows_agent
```

</details>

<details>
  <summary>Errors in Logs</summary>
  <br/>

```console
E TimeoutError: Could not find this event in None: ERROR: Invalid content for tag 'scan_on_start' at module 'syscollector'.

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:465: TimeoutError
-----------------------------Captured stdout setup------------------------------
The Wazuh service is starting. The Wazuh service was started successfully.
-----------------------------Captured stderr setup------------------------------
2024-04-08 09:50:38,740 - wazuh_testing - DEBUG - Wazuh control set to True 2024-04-08 09:50:38,740 - wazuh_testing - DEBUG - Ignore error set to True 2024-04-08 09:50:38,740 - wazuh_testing - DEBUG - Restarting wazuh using wazuh-control
-------------------------------Captured log setup-------------------------------
DEBUG wazuh_testing:conftest.py:1028 Wazuh control set to True DEBUG wazuh_testing:conftest.py:1032 Ignore error set to True DEBUG wazuh_testing:conftest.py:1041 Restarting wazuh using wazuh-control
------------------------------Captured stderr call------------------------------
2024-04-08 09:50:45,967 - wazuh_testing - ERROR - Could not find this event in None: ERROR: Invalid content for tag 'scan_on_start' at module 'syscollector'. 2024-04-08 09:50:45,967 - wazuh_testing - ERROR - Results accumulated: 0 2024-04-08 09:50:45,967 - wazuh_testing - ERROR - Results expected: 1
-------------------------------Captured log call--------------------------------
ERROR wazuh_testing:monitoring.py:461 Could not find this event in None: ERROR: Invalid content for tag 'scan_on_start' at module 'syscollector'. ERROR wazuh_testing:monitoring.py:462 Results accumulated: 0 ERROR wazuh_testing:monitoring.py:464 Results expected: 1
----------------------------Captured stderr teardown----------------------------
2024-04-08 09:50:46,620 - wazuh_testing - DEBUG - Stopping wazuh using wazuh-control
-----------------------------Captured log teardown------------------------------
DEBUG wazuh_testing:conftest.py:1062 Stopping wazuh using wazuh-control
```

```console
E TimeoutError: Could not find this event in None: ERROR: Invalid content for tag 'hardware' at module 'syscollector'.

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:465: TimeoutError
-----------------------------Captured stdout setup------------------------------
The Wazuh service is starting. The Wazuh service was started successfully.
-----------------------------Captured stderr setup------------------------------
2024-04-08 09:50:46,652 - wazuh_testing - DEBUG - Wazuh control set to True 2024-04-08 09:50:46,653 - wazuh_testing - DEBUG - Ignore error set to True 2024-04-08 09:50:46,653 - wazuh_testing - DEBUG - Restarting wazuh using wazuh-control
-------------------------------Captured log setup-------------------------------
DEBUG wazuh_testing:conftest.py:1028 Wazuh control set to True DEBUG wazuh_testing:conftest.py:1032 Ignore error set to True DEBUG wazuh_testing:conftest.py:1041 Restarting wazuh using wazuh-control
------------------------------Captured stderr call------------------------------
2024-04-08 09:50:53,770 - wazuh_testing - ERROR - Could not find this event in None: ERROR: Invalid content for tag 'hardware' at module 'syscollector'. 2024-04-08 09:50:53,771 - wazuh_testing - ERROR - Results accumulated: 0 2024-04-08 09:50:53,771 - wazuh_testing - ERROR - Results expected: 1
-------------------------------Captured log call--------------------------------
ERROR wazuh_testing:monitoring.py:461 Could not find this event in None: ERROR: Invalid content for tag 'hardware' at module 'syscollector'. ERROR wazuh_testing:monitoring.py:462 Results accumulated: 0 ERROR wazuh_testing:monitoring.py:464 Results expected: 1
----------------------------Captured stderr teardown----------------------------
2024-04-08 09:50:54,305 - wazuh_testing - DEBUG - Stopping wazuh using wazuh-control
-----------------------------Captured log teardown------------------------------
DEBUG wazuh_testing:conftest.py:1062 Stopping wazuh using wazuh-control
```

```console
E TimeoutError: Could not find this event in None: ERROR: Invalid content for tag 'os' at module 'syscollector'.

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:465: TimeoutError
-----------------------------Captured stdout setup------------------------------
The Wazuh service is starting. The Wazuh service was started successfully.
-----------------------------Captured stderr setup------------------------------
2024-04-08 09:50:54,337 - wazuh_testing - DEBUG - Wazuh control set to True 2024-04-08 09:50:54,337 - wazuh_testing - DEBUG - Ignore error set to True 2024-04-08 09:50:54,337 - wazuh_testing - DEBUG - Restarting wazuh using wazuh-control
-------------------------------Captured log setup-------------------------------
DEBUG wazuh_testing:conftest.py:1028 Wazuh control set to True DEBUG wazuh_testing:conftest.py:1032 Ignore error set to True DEBUG wazuh_testing:conftest.py:1041 Restarting wazuh using wazuh-control
------------------------------Captured stderr call------------------------------
2024-04-08 09:51:01,425 - wazuh_testing - ERROR - Could not find this event in None: ERROR: Invalid content for tag 'os' at module 'syscollector'. 2024-04-08 09:51:01,425 - wazuh_testing - ERROR - Results accumulated: 0 2024-04-08 09:51:01,425 - wazuh_testing - ERROR - Results expected: 1
-------------------------------Captured log call--------------------------------
ERROR wazuh_testing:monitoring.py:461 Could not find this event in None: ERROR: Invalid content for tag 'os' at module 'syscollector'. ERROR wazuh_testing:monitoring.py:462 Results accumulated: 0 ERROR wazuh_testing:monitoring.py:464 Results expected: 1
----------------------------Captured stderr teardown----------------------------
2024-04-08 09:51:01,976 - wazuh_testing - DEBUG - Stopping wazuh using wazuh-control
-----------------------------Captured log teardown------------------------------
DEBUG wazuh_testing:conftest.py:1062 Stopping wazuh using wazuh-control
```

```console
E TimeoutError: Could not find this event in None: ERROR: Invalid content for tag 'ports' at module 'syscollector'.

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:465: TimeoutError
-----------------------------Captured stdout setup------------------------------
The Wazuh service is starting. The Wazuh service was started successfully.
-----------------------------Captured stderr setup------------------------------
2024-04-08 09:51:15,828 - wazuh_testing - DEBUG - Wazuh control set to True 2024-04-08 09:51:15,828 - wazuh_testing - DEBUG - Ignore error set to True 2024-04-08 09:51:15,828 - wazuh_testing - DEBUG - Restarting wazuh using wazuh-control
-------------------------------Captured log setup-------------------------------
DEBUG wazuh_testing:conftest.py:1028 Wazuh control set to True DEBUG wazuh_testing:conftest.py:1032 Ignore error set to True DEBUG wazuh_testing:conftest.py:1041 Restarting wazuh using wazuh-control
------------------------------Captured stderr call------------------------------
2024-04-08 09:51:22,958 - wazuh_testing - ERROR - Could not find this event in None: ERROR: Invalid content for tag 'ports' at module 'syscollector'. 2024-04-08 09:51:22,958 - wazuh_testing - ERROR - Results accumulated: 0 2024-04-08 09:51:22,958 - wazuh_testing - ERROR - Results expected: 1
-------------------------------Captured log call--------------------------------
ERROR wazuh_testing:monitoring.py:461 Could not find this event in None: ERROR: Invalid content for tag 'ports' at module 'syscollector'. ERROR wazuh_testing:monitoring.py:462 Results accumulated: 0 ERROR wazuh_testing:monitoring.py:464 Results expected: 1
----------------------------Captured stderr teardown----------------------------
2024-04-08 09:51:23,508 - wazuh_testing - DEBUG - Stopping wazuh using wazuh-control
-----------------------------Captured log teardown------------------------------
DEBUG wazuh_testing:conftest.py:1062 Stopping wazuh using wazuh-control
```

```console
E TimeoutError: Could not find this event in None: ERROR: Invalid content for attribute 'all' at module 'syscollector'.

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:465: TimeoutError
-----------------------------Captured stdout setup------------------------------
The Wazuh service is starting. The Wazuh service was started successfully.
-----------------------------Captured stderr setup------------------------------
2024-04-08 09:51:23,540 - wazuh_testing - DEBUG - Wazuh control set to True 2024-04-08 09:51:23,540 - wazuh_testing - DEBUG - Ignore error set to True 2024-04-08 09:51:23,540 - wazuh_testing - DEBUG - Restarting wazuh using wazuh-control
-------------------------------Captured log setup-------------------------------
DEBUG wazuh_testing:conftest.py:1028 Wazuh control set to True DEBUG wazuh_testing:conftest.py:1032 Ignore error set to True DEBUG wazuh_testing:conftest.py:1041 Restarting wazuh using wazuh-control
------------------------------Captured stderr call------------------------------
2024-04-08 09:51:30,658 - wazuh_testing - ERROR - Could not find this event in None: ERROR: Invalid content for attribute 'all' at module 'syscollector'. 2024-04-08 09:51:30,658 - wazuh_testing - ERROR - Results accumulated: 0 2024-04-08 09:51:30,658 - wazuh_testing - ERROR - Results expected: 1
-------------------------------Captured log call--------------------------------
ERROR wazuh_testing:monitoring.py:461 Could not find this event in None: ERROR: Invalid content for attribute 'all' at module 'syscollector'. ERROR wazuh_testing:monitoring.py:462 Results accumulated: 0 ERROR wazuh_testing:monitoring.py:464 Results expected: 1
----------------------------Captured stderr teardown----------------------------
2024-04-08 09:51:30,807 - wazuh_testing - DEBUG - Stopping wazuh using wazuh-control
-----------------------------Captured log teardown------------------------------
DEBUG wazuh_testing:conftest.py:1062 Stopping wazuh using wazuh-control
```

```console
E TimeoutError: Could not find this event in None: ERROR: Invalid content for tag 'processes' at module 'syscollector'.

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:465: TimeoutError
-----------------------------Captured stdout setup------------------------------
The Wazuh service is starting. The Wazuh service was started successfully.
-----------------------------Captured stderr setup------------------------------
2024-04-08 09:51:30,862 - wazuh_testing - DEBUG - Wazuh control set to True 2024-04-08 09:51:30,862 - wazuh_testing - DEBUG - Ignore error set to True 2024-04-08 09:51:30,862 - wazuh_testing - DEBUG - Restarting wazuh using wazuh-control
-------------------------------Captured log setup-------------------------------
DEBUG wazuh_testing:conftest.py:1028 Wazuh control set to True DEBUG wazuh_testing:conftest.py:1032 Ignore error set to True DEBUG wazuh_testing:conftest.py:1041 Restarting wazuh using wazuh-control
------------------------------Captured stderr call------------------------------
2024-04-08 09:51:37,999 - wazuh_testing - ERROR - Could not find this event in None: ERROR: Invalid content for tag 'processes' at module 'syscollector'. 2024-04-08 09:51:37,999 - wazuh_testing - ERROR - Results accumulated: 0 2024-04-08 09:51:37,999 - wazuh_testing - ERROR - Results expected: 1
-------------------------------Captured log call--------------------------------
ERROR wazuh_testing:monitoring.py:461 Could not find this event in None: ERROR: Invalid content for tag 'processes' at module 'syscollector'. ERROR wazuh_testing:monitoring.py:462 Results accumulated: 0 ERROR wazuh_testing:monitoring.py:464 Results expected: 1
----------------------------Captured stderr teardown----------------------------
2024-04-08 09:51:38,548 - wazuh_testing - DEBUG - Stopping wazuh using wazuh-control
-----------------------------Captured log teardown------------------------------
DEBUG wazuh_testing:conftest.py:1062 Stopping wazuh using wazuh-control
```

```console
E TimeoutError: Could not find this event in None: ERROR: Invalid content for tag 'disabled' at module 'syscollector'.

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:465: TimeoutError
-----------------------------Captured stdout setup------------------------------
The Wazuh service is starting. The Wazuh service was started successfully.
-----------------------------Captured stderr setup------------------------------
2024-04-08 09:51:38,586 - wazuh_testing - DEBUG - Wazuh control set to True 2024-04-08 09:51:38,586 - wazuh_testing - DEBUG - Ignore error set to True 2024-04-08 09:51:38,586 - wazuh_testing - DEBUG - Restarting wazuh using wazuh-control
-------------------------------Captured log setup-------------------------------
DEBUG wazuh_testing:conftest.py:1028 Wazuh control set to True DEBUG wazuh_testing:conftest.py:1032 Ignore error set to True DEBUG wazuh_testing:conftest.py:1041 Restarting wazuh using wazuh-control
------------------------------Captured stderr call------------------------------
2024-04-08 09:51:45,724 - wazuh_testing - ERROR - Could not find this event in None: ERROR: Invalid content for tag 'disabled' at module 'syscollector'. 2024-04-08 09:51:45,724 - wazuh_testing - ERROR - Results accumulated: 0 2024-04-08 09:51:45,724 - wazuh_testing - ERROR - Results expected: 1
-------------------------------Captured log call--------------------------------
ERROR wazuh_testing:monitoring.py:461 Could not find this event in None: ERROR: Invalid content for tag 'disabled' at module 'syscollector'. ERROR wazuh_testing:monitoring.py:462 Results accumulated: 0 ERROR wazuh_testing:monitoring.py:464 Results expected: 1
----------------------------Captured stdout teardown----------------------------
The Wazuh service was stopped successfully.
----------------------------Captured stderr teardown----------------------------
2024-04-08 09:51:46,273 - wazuh_testing - DEBUG - Stopping wazuh using wazuh-control
-----------------------------Captured log teardown------------------------------
DEBUG wazuh_testing:conftest.py:1062 Stopping wazuh using wazuh-control
```

```console
E TimeoutError: Could not find this event in None: DEBUG: Starting Syscollector.

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:465: TimeoutError
-----------------------------Captured stdout setup------------------------------
The Wazuh service is starting. The Wazuh service was started successfully.
-----------------------------Captured stderr setup------------------------------
2024-04-08 09:53:30,088 - wazuh_testing - DEBUG - Wazuh control set to True 2024-04-08 09:53:30,089 - wazuh_testing - DEBUG - Ignore error set to True 2024-04-08 09:53:30,089 - wazuh_testing - DEBUG - Restarting wazuh using wazuh-control
-------------------------------Captured log setup-------------------------------
DEBUG wazuh_testing:conftest.py:1028 Wazuh control set to True DEBUG wazuh_testing:conftest.py:1032 Ignore error set to True DEBUG wazuh_testing:conftest.py:1041 Restarting wazuh using wazuh-control
------------------------------Captured stderr call------------------------------
2024-04-08 09:54:34,348 - wazuh_testing - ERROR - Could not find this event in None: DEBUG: Starting Syscollector. 2024-04-08 09:54:34,348 - wazuh_testing - ERROR - Results accumulated: 0 2024-04-08 09:54:34,348 - wazuh_testing - ERROR - Results expected: 1
-------------------------------Captured log call--------------------------------
ERROR wazuh_testing:monitoring.py:461 Could not find this event in None: DEBUG: Starting Syscollector. ERROR wazuh_testing:monitoring.py:462 Results accumulated: 0 ERROR wazuh_testing:monitoring.py:464 Results expected: 1
----------------------------Captured stderr teardown----------------------------
2024-04-08 09:54:34,448 - wazuh_testing - DEBUG - Stopping wazuh using wazuh-control 2024-04-08 09:54:34,475 - wazuh_testing - DEBUG - Restore local_internal_option to {}
-----------------------------Captured log teardown------------------------------
DEBUG wazuh_testing:conftest.py:1062 Stopping wazuh using wazuh-control DEBUG wazuh_testing:conftest.py:669 Restore local_internal_option to {}
```

</details>

## Evidences

- Build: https://ci.wazuh.info/job/Test_integration/46780/
- Evidence: [agent_windows_html_report_Test_integration_B46780.zip](https://github.com/wazuh/wazuh/files/14919221/agent_windows_html_report_Test_integration_B46780.zip)
- Artifacts: [Artifacts.tar.gz](https://github.com/wazuh/wazuh/files/14928691/Artifacts.tar.gz)
- Console: [consoleText.txt](https://github.com/wazuh/wazuh/files/14928703/consoleText.txt)

**Comment by Dwordcito** [comment]
@sebasfalcone take a look at this and check if this is an it issue or a product issue.

**Comment by Dwordcito** [comment]
Timebox to rca 11/04

**Comment by rafabailon** [comment]
@sebasfalcone It seems that there was already an issue marked as `qa_known` about this [Syscollector scanning IT fails for Windows agents](https://github.com/wazuh/wazuh-qa/issues/4230) I am closing this issue.
