### ISSUE TITLE
AWS Security Lake - Source Version 2

### ISSUE THREAD

**Issue by kclinden** [wazuh/wazuh#22880]
| Affected integration |
|---|
| AWS|

## Description
When integrating with AWS Security Lake with [Source Version 2](https://docs.aws.amazon.com/security-lake/latest/userguide/subscriber-query-examples2.html) I am getting the following error:
```
DEBUG: Processing file aws/SH_FINDINGS/2.0/region=us-west-2/accountId=123456789000/eventDay=20240410/6cc7641e31d4d10209bed021dd7ebe35.gz.parquet in aws-security-data-lake-us-east-1-txlvnteculqdhzkmgk89pghsxqrlmu
DEBUG: +++ Error: Object of type datetime is not JSON serializable
Unknown error: Object of type datetime is not JSON serializable
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 4250, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 4237, in main
    asl_queue.sync_events()
  File "/var/ossec/wodles/aws/aws-s3.py", line 3797, in sync_events
    self.bucket_handler.process_file(message["route"])
  File "/var/ossec/wodles/aws/aws-s3.py", line 3667, in process_file
    events_in_file = self.obtain_logs(bucket=message_body['bucket_path'],
  File "/var/ossec/wodles/aws/aws-s3.py", line 3655, in obtain_logs
    events.append(json.dumps(j))
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/var/ossec/framework/python/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/ossec/framework/python/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/var/ossec/framework/python/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
[root@wazuh-manager-0 logs]# vim /var/ossec/wodles/aws/aws-s3.py[root@wazuh-manager-0 logs]# vim /var/ossec/wodles/aws/aws-s3.py
```

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by Selutario** [comment]
Thank you for these reports @kclinden, we will review this.

**Comment by fdalmaup** [comment]
# Issue Update

- Replicated the error using the 2.0 source version.
- According to the traceback, the problem was related to a certain field from the parquet file being transformed into a `datetime` object that the `json.dumps` could not serialize. The fix includes `str` as the default applied function to use for those objects not present in the [conversion table](https://docs.python.org/3/library/json.html#py-to-json-table).
- Although the fix works (tested by modifying the module in the `4.8.0` due to https://github.com/wazuh/wazuh/issues/23672 required to use the module in the `master` branch), we should review if the Security Lake rules should be modified or extended taking into account the new version.

**Comment by davidjiglesias** [comment]
>Although the fix works (tested by modifying the module in the 4.8.0 due to https://github.com/wazuh/wazuh/issues/23672 required to use the module in the master branch), we should review if the Security Lake rules should be modified or extended taking into account the new version.

Go ahead with the fix to ensure we are compatible with Source version 2 as well as maintain compatibility with Source version 1, ignoring ruleset for now.

**Comment by javiersanchz** [comment]
## Update

The mentioned issue was reproduced again using a `2.0` file as a test.

```console
DEBUG: Processing file aws/VPC_FLOW/2.0/xxxxxxxb49.gz.parquet in aws-security-data-lake-xxxxxxxx
DEBUG: +++ Error: Object of type datetime is not JSON serializable
ERROR: Unknown error: Object of type datetime is not JSON serializable
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 207, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 194, in main
    subscriber_queue.sync_events()
  File "/var/ossec/wodles/aws/subscribers/sqs_queue.py", line 140, in sync_events
    self.bucket_handler.process_file(message["route"])
  File "/var/ossec/wodles/aws/subscribers/s3_log_handler.py", line 306, in process_file
    events_in_file = self.obtain_logs(bucket=message_body['bucket_path'],
  File "/var/ossec/wodles/aws/subscribers/s3_log_handler.py", line 294, in obtain_logs
    events.append(json.dumps(j))
  File "/var/ossec/framework/python/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/var/ossec/framework/python/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/ossec/framework/python/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/var/ossec/framework/python/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

Once the change was added, the same file containing version `2.0` and another with version `1.0` were processed again to verify the correct operation of both:

### v2.0

```console
DEBUG: Processing file aws/VPC_FLOW/2.0/region=xxxxxx/accountId=16xxxxx23/eventDay=20xxxx7/00c7ddxxxxxxxx.gz.parquet in aws-security-data-lake-xxxxxxx
DEBUG: Found 4786 events in file aws/VPC_FLOW/2.0/region=xxxxxx/xxxxxxxxx/eventDay=20xxxxxxx/00c7dd6fcxxxxxx.gz.parquet
DEBUG: "{\"metadata\": {\"product\": {\"version\": \"5\", \"name\": \"Amazon VPC\", \"feature\": {\"name\": \"Flowlogs\"}, \"vendor_name\": \"AWS\"}, \"profiles\": [\"cloud\", \"security_control\", \"datetime\"], \"version\": \"1.1.0\"}, \"cloud\": {\"account\": {\"uid\": \"1661xxxxx\"}, \"region\": \"xxxxxx\", \"zone\": \"xxxxxxz1\", \"provider\": \"AWS\"}, \"src_endpoint\": {\"port\": xxxx, \"svc_name\": \"-\", \"ip\": \"3xxxxxx\", \"intermediate_ips\": null, \"interface_uid\": null, \"vpc_uid\": null, \"instance_uid\": null, \"subnet_uid\": null}, \"dst_endpoint\": {\"port\": xxxx, \"svc_name\": \"-\", \"ip\": \"xxxxxx\", \"intermediate_ips\": null, \"interface_uid\": \"eni-020d28863xxxxxd\", \"vpc_uid\": \"vpc-069217xxxxx\", \"instance_uid\": \"i-0f88dxxxxa\", \"subnet_uid\": \"subnet-0b04a5xxxx\"}, \"connection_info\": {\"protocol_num\": 6, \"tcp_flags\": 2, \"protocol_ver\": \"IPv4\", \"boundary_id\": 99, \"boundary\": null, \"direction_id\": 1, \"direction\": \"Inbound\"}, \"traffic\": {\"packets\": 1, \"bytes\": 44}, \"time\": 1716826xxxx, \"time_dt\": \"2024-05-27 16:09:18+00:00\", \"start_time_dt\": \"2024-05-27 16:09:18+00:00\", \"end_time_dt\": \"2024-05-27 16:10:13+00:00\", \"status_code\": \"OK\", \"severity_id\": 1, \"severity\": \"Informational\", \"class_name\": \"Network Activity\", \"class_uid\": 4001, \"category_name\": \"Network Activity\", \"category_uid\": 4, \"activity_name\": \"Refuse\", \"activity_id\": 5, \"action\": \"Denied\", \"action_id\": 2, \"disposition\": \"Blocked\", \"type_uid\": 400105, \"type_name\": \"Network Activity: Refuse\", \"accountid\": null, \"region\": null, \"asl_version\": null, \"unmapped\": [[\"sublocation_id\", \"-\"], [\"sublocation_type\", \"-\"]], \"observables\": [{\"name\": \"dst_endpoint.instance_uid\", \"value\": \"i-0f88dxxxxxx\", \"type\": \"Resource UID\", \"type_id\": 10}, {\"name\": \"dst_endpoint.ip\", \"value\": \"10.0.xxxxx\", \"type\": \"IP Address\", \"type_id\": 2}, {\"name\": \"src_endpoint.ip\", \"value\": \"35.20xxxxx\", \"type\": \"IP Address\", \"type_id\": 2}]}"
...
```


### v1.0

```console
DEBUG: Processing file aws/VPC_FLOW/1.0/region=xxxxx/xxxxxxx/eventDay=xxxxx/08c5c9280xxxxxxx.gz.parquet in aws-security-data-lake-us-east-1-gxxxxxxxx
DEBUG: Found 184 events in file aws/VPC_FLOW/1.0/region=xxxxxx/xxxxxxxx/eventDay=xxxxxx/08c5c9280xxxxxxxxxa.gz.parquet
DEBUG: "{\"metadata\": {\"product\": {\"version\": \"5\", \"name\": \"Amazon VPC\", \"feature\": {\"name\": \"Flowlogs\"}, \"vendor_name\": \"AWS\"}, \"profiles\": [\"cloud\", \"security_control\"], \"version\": \"1.0.0-rc.2\"}, \"cloud\": {\"account_uid\": \"xxxxxxx\", \"region\": \"xxxxxx\", \"zone\": \"xxxxxx\", \"provider\": \"AWS\"}, \"src_endpoint\": {\"port\": xxxxxx, \"svc_name\": \"-\", \"ip\": \"xxxxxx\", \"intermediate_ips\": null, \"interface_uid\": null, \"vpc_uid\": null, \"instance_uid\": null, \"subnet_uid\": null}, \"dst_endpoint\": {\"port\": xxxx, \"svc_name\": \"-\", \"ip\": \"xxxxx\", \"intermediate_ips\": null, \"interface_uid\": \"eni-0ecxxxxx\", \"vpc_uid\": \"vpc-024049xxxxx\", \"instance_uid\": \"-\", \"subnet_uid\": \"subnet-0643a47c65c6fc80e\"}, \"connection_info\": {\"protocol_num\": 6, \"tcp_flags\": 2, \"protocol_ver\": \"IPv4\", \"boundary_id\": 99, \"boundary\": null, \"direction_id\": 1, \"direction\": \"Inbound\"}, \"traffic\": {\"packets\": 1, \"bytes\": 44}, \"time\": 1698966263000, \"start_time\": 1698966263000, \"end_time\": 1698966270000, \"status_code\": \"OK\", \"severity_id\": 1, \"severity\": \"Informational\", \"class_name\": \"Network Activity\", \"class_uid\": 4001, \"category_name\": \"Network Activity\", \"category_uid\": 4, \"activity_name\": \"Traffic\", \"activity_id\": 6, \"disposition\": \"Allowed\", \"disposition_id\": 1, \"type_uid\": 400xxxxx, \"type_name\": \"Network Activity: Traffic\", \"unmapped\": [[\"sublocation_id\", \"-\"], [\"sublocation_type\", \"-\"]]}"
...
```

As you can see, after adding the change, both types are processed correctly and the error `'Error: Object of type datetime is not JSON serializable' is not raised`

**Comment by javiersanchz** [comment]
## Update

### Unit_test 

```console
(unittest-env) wazuh@javier:~/Git/wazuh$ PYTHONPATH=/home/wazuh/Git/wazuh/api:/home/wazuh/Git/wazuh/framework python3 -m pytest wodles/aws/tests
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.4.0
rootdir: /home/wazuh/Git/wazuh/wodles/aws/tests
configfile: pytest.ini
plugins: anyio-4.3.0, aiohttp-1.0.4, trio-0.8.0, html-2.1.1, metadata-3.1.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 599 items                                                                                                                                                                                        

wodles/aws/tests/test_aws_bucket.py ................................................................................................................................................................ [ 26%]
...........................................                                                                                                                                                          [ 33%]
wodles/aws/tests/test_aws_s3.py ......................                                                                                                                                               [ 37%]
wodles/aws/tests/test_aws_service.py ....                                                                                                                                                            [ 38%]
wodles/aws/tests/test_cloudtrail.py ..                                                                                                                                                               [ 38%]
wodles/aws/tests/test_cloudwatchlogs.py .....................................................                                                                                                        [ 47%]
wodles/aws/tests/test_config.py ..............................................................................                                                                                       [ 60%]
wodles/aws/tests/test_guardduty.py .................                                                                                                                                                 [ 63%]
wodles/aws/tests/test_inspector.py ......                                                                                                                                                            [ 64%]
wodles/aws/tests/test_load_balancers.py ............                                                                                                                                                 [ 66%]
wodles/aws/tests/test_s3_log_handler.py .......................                                                                                                                                      [ 70%]
wodles/aws/tests/test_server_access.py .................................                                                                                                                             [ 75%]
wodles/aws/tests/test_sqs_message_processor.py ........                                                                                                                                              [ 76%]
wodles/aws/tests/test_sqs_queue.py .......                                                                                                                                                           [ 78%]
wodles/aws/tests/test_tools.py ..................................                                                                                                                                    [ 83%]
wodles/aws/tests/test_umbrella.py ......                                                                                                                                                             [ 84%]
wodles/aws/tests/test_vpcflow.py .....................                                                                                                                                               [ 88%]
wodles/aws/tests/test_waf.py .......                                                                                                                                                                 [ 89%]
wodles/aws/tests/test_wazuh_integration.py ...............................................................                                                                                           [100%]

=========================================================================================== 599 passed in 2.95s ============================================================================================
(unittest-env) wazuh@javier:~/Git/wazuh$ PYTHONPATH=/home/wazuh/Git/wazuh/api:/home/wazuh/Git/wazuh/framework python3 -m pytest wodles/aws/tests/test_s3_log_handler.py 
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.4.0
rootdir: /home/wazuh/Git/wazuh/wodles/aws/tests
configfile: pytest.ini
plugins: anyio-4.3.0, aiohttp-1.0.4, trio-0.8.0, html-2.1.1, metadata-3.1.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 23 items                                                                                                                                                                                         

wodles/aws/tests/test_s3_log_handler.py .......................                                                                                                                                      [100%]

============================================================================================ 23 passed in 0.21s ============================================================================================
```

**Comment by javiersanchz** [comment]
## Update

A test was added to verify that no exception is thrown when the event contains a `datetime`.

**Comment by javiersanchz** [comment]
## Update

We can observe in these examples, one before the change and another after, that the events both before and after the changes maintain the output format as `string` (in `JSON format`). 
This includes the metadata and detailed information of the events, which remain consistent in both cases. The module continues to send the events correctly to `Analysisd`, with no alterations in the structure or processing of the events. 
Therefore, we can conclude that the module is still functioning as expected without affecting the flow of information to `Analysisd`


Before the changes:

```console
...
DEBUG: Processing file aws/S3_DATA/1.0/region=xxxxxxx/accountId=xxxxxxxxx/eventDay=xxxxxxxx/xxxxxxx97b10ecd612928f1ebae972.gz.parquet in aws-security-data-lake-xxxx-xxxxx
DEBUG: Found 1 events in file aws/S3_DATA/1.0/region=xxxxx/accountId=xxxxxxx/eventDay=xxxxxxx/2xxxxxb10ecdxxxx1ebae972.gz.parquet
DEBUG: "{\"metadata\": {\"product\": {\"version\": \"1.10\", \"name\": \"CloudTrail\", \"vendor_name\": \"AWS\", \"feature\": {\"name\": \"Data\"}}, \"uid\": \"xxxxxxxxx\", \"profiles\": [\"cloud\"], \"version\": \"1.0.0-rc.2\"}, \"time\": 1726832335000, \"cloud\": {\"region\": \"xxxxxx\", \"provider\": \"AWS\"}, \"api\": {\"response\": null, \"operation\": \"PutObject\", \"version\": null, \"service\": {\"name\": \"s3.amazonaws.com\"}, \"request\": {\"uid\": \"xxxxxxxx\"}}, \"dst_endpoint\": null, \"actor\": {\"user\": {\"type\": \"AWSService\", \"name\": null, \"uid\": null, \"uuid\": null, \"account_uid\": null, \"credential_uid\": null}, \"session\": null, \"invoked_by\": \"securitylake.amazonaws.com\", \"idp\": null}, \"http_request\": {\"user_agent\": \"securitylake.amazonaws.com\"}, \"src_endpoint\": {\"uid\": \"vpce-xxxxxxxx\", \"ip\": null, \"domain\": \"securitylake.amazonaws.com\"}, \"resources\": [{\"uid\": \"arn:aws:s3:::aws-security-data-lake-xxxxxxxxhg3rhig0/aws/S3_DATA/1.0/region=xxxxxx/accountId=xxxxxxxx/eventDay=20240920/d0c9079dxxxxxxx.gz.parquet\", \"account_uid\": null, \"type\": \"AWS::S3::Object\"}, {\"uid\": \"arn:aws:s3xxxxxxxx0\", \"account_uid\": \"xxxxxx\", \"type\": \"AWS::S3::Bucket\"}], \"class_name\": \"API Activity\", \"class_uid\": 3005, \"category_name\": \"Audit Activity\", \"category_uid\": 3, \"severity_id\": 1, \"severity\": \"Informational\", \"user\": null, \"activity_name\": \"Update\", \"activity_id\": 3, \"type_uid\": xxxxxx, \"type_name\": \"API Activity: Update\", \"status\": \"Success\", \"status_id\": 1, \"mfa\": null, \"unmapped\": [[\"additionalEventData.SSEApplied\", \"Default_SSE_S3\"], [\"requestParameters.x-amz-acl\", \"bucket-owner-full-control\"], [\"additionalEventData.SignatureVersion\", \"SigV4\"], [\"additionalEventData.CipherSuite\", \"TLS_AES_128_GCM_SHA256\"], [\"additionalEventData.bytesTransferredOut\", \"0\"], [\"additionalEventData.x-amz-id-2\", \"3fBK5VQxxxxxxxxx+cw=\"], [\"readOnly\", \"false\"], [\"eventType\", \"AwsApiCall\"], [\"requestParameters.Host\", \"aws-security-data-lakexxxxxxxx.s3.amazonaws.com\"], [\"additionalEventData.AuthenticationMethod\", \"AuthHeader\"], [\"sharedEventID\", \"xxxxxxx\"], [\"requestParameters.key\", \"aws/S3_DATA/1.0/region=xxxxxxx/accountId=xxxxxxx/eventDay=20240xxxxx/d0xxxxxxx154087a5.gz.parquet\"], [\"requestParameters.bucketName\", \"aws-security-data-lake-xxxxxxxxhg3rhig0\"], [\"responseElements.x-amz-server-side-encryption\", \"AES256\"], [\"recipientAccountId\", \"xxxxxxxx\"], [\"managementEvent\", \"false\"], [\"additionalEventData.bytesTransferredIn\", \"26842\"]]}"
DEBUG: 1 events sent to Analysisd
DEBUG: Message deleted from queue: AmazonSecurityLake-005xxxxxxxxx-Main-Queue
```


After the changes:

```console
DEBUG: Processing file aws/S3_DATA/1.0/region=xxxxxxx/accountId=xxxxxxxxx/eventDay=xxxxxxxx/xxxxxxx97b10ecd612928f1ebae972.gz.parquet in aws-security-data-lake-xxxx-xxxxx
DEBUG: Found 35 events in file aws/S3_DATA/1.0/region=xxxxx/accountId=xxxxxxx/eventDay=xxxxxxx/2xxxxxb10ecdxxxx1ebae972.gz.parquet
...
DEBUG: "{\"metadata\": {\"product\": {\"version\": \"1.10\", \"name\": \"CloudTrail\", \"vendor_name\": \"AWS\", \"feature\": {\"name\": \"Data\"}}, \"uid\": \"xxxxxxxxx\", \"profiles\": [\"cloud\"], \"version\": \"1.0.0-rc.2\"}, \"time\": 1726832335000, \"cloud\": {\"region\": \"xxxxxx\", \"provider\": \"AWS\"}, \"api\": {\"response\": null, \"operation\": \"PutObject\", \"version\": null, \"service\": {\"name\": \"s3.amazonaws.com\"}, \"request\": {\"uid\": \"xxxxxxxx\"}}, \"dst_endpoint\": null, \"actor\": {\"user\": {\"type\": \"AWSService\", \"name\": null, \"uid\": null, \"uuid\": null, \"account_uid\": null, \"credential_uid\": null}, \"session\": null, \"invoked_by\": \"securitylake.amazonaws.com\", \"idp\": null}, \"http_request\": {\"user_agent\": \"securitylake.amazonaws.com\"}, \"src_endpoint\": {\"uid\": \"vpce-xxxxxxxx\", \"ip\": null, \"domain\": \"securitylake.amazonaws.com\"}, \"resources\": [{\"uid\": \"arn:aws:s3:::aws-security-data-lake-xxxxxxxxhg3rhig0/aws/S3_DATA/1.0/region=xxxxxx/accountId=xxxxxxxx/eventDay=20240920/d0c9079dxxxxxxx.gz.parquet\", \"account_uid\": null, \"type\": \"AWS::S3::Object\"}, {\"uid\": \"arn:aws:s3xxxxxxxx0\", \"account_uid\": \"xxxxxx\", \"type\": \"AWS::S3::Bucket\"}], \"class_name\": \"API Activity\", \"class_uid\": 3005, \"category_name\": \"Audit Activity\", \"category_uid\": 3, \"severity_id\": 1, \"severity\": \"Informational\", \"user\": null, \"activity_name\": \"Update\", \"activity_id\": 3, \"type_uid\": xxxxxx, \"type_name\": \"API Activity: Update\", \"status\": \"Success\", \"status_id\": 1, \"mfa\": null, \"unmapped\": [[\"additionalEventData.SSEApplied\", \"Default_SSE_S3\"], [\"requestParameters.x-amz-acl\", \"bucket-owner-full-control\"], [\"additionalEventData.SignatureVersion\", \"SigV4\"], [\"additionalEventData.CipherSuite\", \"TLS_AES_128_GCM_SHA256\"], [\"additionalEventData.bytesTransferredOut\", \"0\"], [\"additionalEventData.x-amz-id-2\", \"3fBK5VQxxxxxxxxx+cw=\"], [\"readOnly\", \"false\"], [\"eventType\", \"AwsApiCall\"], [\"requestParameters.Host\", \"aws-security-data-lakexxxxxxxx.s3.amazonaws.com\"], [\"additionalEventData.AuthenticationMethod\", \"AuthHeader\"], [\"sharedEventID\", \"xxxxxxx\"], [\"requestParameters.key\", \"aws/S3_DATA/1.0/region=xxxxxxx/accountId=xxxxxxx/eventDay=20240xxxxx/d0xxxxxxx154087a5.gz.parquet\"], [\"requestParameters.bucketName\", \"aws-security-data-lake-xxxxxxxxhg3rhig0\"], [\"responseElements.x-amz-server-side-encryption\", \"AES256\"], [\"recipientAccountId\", \"xxxxxxxx\"], [\"managementEvent\", \"false\"], [\"additionalEventData.bytesTransferredIn\", \"26842\"]]}"
DEBUG: 35 events sent to Analysisd
DEBUG: Message deleted from queue: AmazonSecurityLake-005xxxxxxxxx-Main-Queue
```
