### ISSUE TITLE
Wazuh Dashboard Failes to start with YAMLException: duplicated mapping key

### ISSUE THREAD

**Issue by ejaiken** [wazuh/wazuh#23125]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3-1 | wazuh-dashboard| Manager | packages.wazuh.com/4.x/yum/ | RHEL8.8 |

Changes before it service broke:
* Enabling github in the dashboard. 
* Shutdown the server instance gracefully, upgraded the instance type (aws) with larger compute.
  * Sever came up fine except for the wazuh-dashboard.service.
* None of the Wazuh or dashboard configurations were modified.
  * installation defaults: opensearch_dashboards.yml
  * installation defaults: wazuh.yml

Syslog error:

v16.20.0
    /usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:173
     throw generateError(state, message);
     ^
    YAMLException: duplicated mapping key at line 18, column 1:
       opensearch_security.cookie.secur ...
       ^
       at generateError (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
       at throwError (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
       at storeMappingPair (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:335:7)
       at readBlockMapping (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1098:9)
       at composeNode (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
       at readDocument (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
       at loadDocuments (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
       at load (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
       at Object.safeLoad (/usr/share/wazuh-dashboard/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
       at readYaml (/usr/share/wazuh-dashboard/node_modules/@osd/apm-config-loader/target/utils/read_config.js:37:38) {
     reason: 'duplicated mapping key',
     mark: Mark {
       name: null,
       buffer: 'server.host: 0.0.0.0\n' +
         'opensearch.hosts: https://127.0.0.1:9200\n' +
         'server.port: 443\n' +
         'opensearch.ssl.verificationMode: certificate\n' +
         '#opensearch.username: kibanaserver\n' +
         '#opensearch.password: kibanaserver\n' +
         'opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]\n' +
         'opensearch_security.multitenancy.enabled: false\n' +
         'opensearch_security.readonly_mode.roles: ["kibana_read_only"]\n' +
         'server.ssl.enabled: true\n' +
         'server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh-dashboard-key.pem"\n' +
         'server.ssl.certificate: "/etc/wazuh-dashboard/certs/wazuh-dashboard.pem"\n' +
         'opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]\n' +
         'uiSettings.overrides.defaultRoute: /app/wazuh\n' +
         'opensearch_security.cookie.secure: true\n' +
         'opensearch_security.session.ttl: 7200000\n' +
         'opensearch_security.cookie.ttl: 7200000\n' +
         'opensearch_security.cookie.secure: true\n' +
         'opensearch_security.session.keepalive: true\n' +
         '\x00',
       position: 791,
       line: 17,
       column: 0
     }
    }
   systemd[1]: wazuh-dashboard.service: Main process exited, code=exited, status=1/FAILURE
   systemd[1]: wazuh-dashboard.service: Failed with result 'exit-code'.

**Comment by cherouize** [comment]
it does the same for my wazuh.yml configuration file that i had to specify myself through a volume

the entrypoint.sh is adding a new "hosts" key in my wazuh.yml 

'opensearch_security.cookie.secure: true\n' + is duplicated here, soooo check your configuration file or maybe try to LOCK the permissions so wazuh cannot change it but it could raise an error -_-
