### ISSUE TITLE
Modify agent_upgrade script to avoid error due to unsuccessful upgrade

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#23218]
## Description

It was found that when the `framework/scripts/agent_upgrade.py` script is run and the upgrade command raises an exception, it breaks the execution with an uncaught exception since this is not contemplated and always expects a result with the `failed _items` list:

```python
Agent information not found in database
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.7.3-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 241, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.7.3-py3.9.egg/wazuh/rbac/decorators.py", line 494, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.7.3-py3.9.egg/wazuh/agent.py", line 1208, in upgrade_agents
    raise WazuhInternalError(error_code, cmd_error=True, extra_message=agent_result['message'])
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.7.3-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 287, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
wazuh.core.exception.WazuhInternalError: Error 1816 - Agent information not found in database
Internal error: 'WazuhInternalError' object has no attribute 'failed_items'
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 242, in <module>
    run(main())
  File "/var/ossec/framework/python/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 213, in main
    not args.silent and len(result.failed_items.keys()) > 0 and print("Agents that cannot be upgraded:")
AttributeError: 'WazuhInternalError' object has no attribute 'failed_items'
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Applied changes to capture exceptions that were thrown inside the distributed functions and updated the unit tests.

**Comment by GGP1** [comment]
## Update

[Clarified](https://github.com/wazuh/wazuh/pull/24341#issuecomment-2196718148) that the failed checks are not related to the changes.
