### ISSUE TITLE
Vulnerability Detector fails to identify ARM centOS vulnerabilities in End-to-End tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#23326]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.8.0-rc1 | Vulnerability Detection | Manager | Packages | Ubuntu22 |

### Description

In [Release 4.8.0 - RC 1 - Vulnerability Detection E2E tests](https://github.com/wazuh/wazuh/issues/23299) it has been detected that the vulnerability detector does detect any vulnerability for centOS7 ARM agent (agent4 in the provided report).

### Evidences

**Report**: https://github.com/wazuh/wazuh/files/15234960/Test_e2e_system_284_test_vulnerability_detector.zip

> [!NOTE]
> Currently tests are being launched enabling modulesd debug. Further evidence will be provided on this issue as soon as possible

**Comment by Dwordcito** [comment]
After some testing around this behavior, we discover a race condition in the timeout algorithm in the wazuh-db query. All queue scans are still waiting for this condition that never ends. But if you restart the wazuh manager, the scanning continues and reports the agent vulnerabilities.

This will be solved at https://github.com/wazuh/wazuh/issues/23301 

```
Thread 45 (Thread 0x7e970ad6f640 (LWP 22053) "wazuh-modulesd"):
#0  futex_wait (private=0, expected=2, futex_word=0x7e9716f07b58 <TScanAgentList<TScanContext<OsDataCache, GlobalData>, AbstractHandler<std::shared_ptr<TScanContext<OsDataCache, GlobalData> > > >::scanAgentPackages(AgentData const&)::wdbSocketWrapper+120>) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x7e9716f07b58 <TScanAgentList<TScanContext<OsDataCache, GlobalData>, AbstractHandler<std::shared_ptr<TScanContext<OsDataCache, GlobalData> > > >::scanAgentPackages(AgentData const&)::wdbSocketWrapper+120>, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007e9723498002 in lll_mutex_lock_optimized (mutex=0x7e9716f07b58 <TScanAgentList<TScanContext<OsDataCache, GlobalData>, AbstractHandler<std::shared_ptr<TScanContext<OsDataCache, GlobalData> > > >::scanAgentPackages(AgentData const&)::wdbSocketWrapper+120>) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x7e9716f07b58 <TScanAgentList<TScanContext<OsDataCache, GlobalData>, AbstractHandler<std::shared_ptr<TScanContext<OsDataCache, GlobalData> > > >::scanAgentPackages(AgentData const&)::wdbSocketWrapper+120>) at ./nptl/pthread_mutex_lock.c:93
#4  0x00007e9716aaa439 in ?? () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#5  0x00007e9716aaa9d8 in std::mutex::lock() () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#6  0x00007e9716ae50b4 in std::scoped_lock<std::mutex>::scoped_lock(std::mutex&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#7  0x00007e9716acb144 in SocketDBWrapper::initializeSocket()::{lambda(char const*, unsigned int, char const*, unsigned int)#1}::operator()(char const*, unsigned int, char const*, unsigned int) const () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#8  0x00007e9716af9b2b in std::_Function_handler<void (char const*, unsigned int, char const*, unsigned int), SocketDBWrapper::initializeSocket()::{lambda(char const*, unsigned int, char const*, unsigned int)#1}>::_M_invoke(std::_Any_data const&, char const*&&, unsigned int&&, char const*&&, unsigned int&&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#9  0x00007e9716afa43d in std::function<void (char const*, unsigned int, char const*, unsigned int)>::operator()(char const*, unsigned int, char const*, unsigned int) const () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#10 0x00007e9716ae5c30 in SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}::operator()() const::{lambda(int, char const*, unsigned int, char const*, unsigned int)#1}::operator()(int, char const*, unsigned int, char const*, unsigned int) const () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#11 0x00007e9716b108ac in std::_Function_handler<void (int, char const*, unsigned int, char const*, unsigned int), SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}::operator()() const::{lambda(int, char const*, unsigned int, char const*, unsigned int)#1}>::_M_invoke(std::_Any_data const&, int&&, char const*&&, unsigned int&&, char const*&&, unsigned int&&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#12 0x00007e9716b109fc in std::function<void (int, char const*, unsigned int, char const*, unsigned int)>::operator()(int, char const*, unsigned int, char const*, unsigned int) const () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#13 0x00007e9716afa88e in Socket<OSPrimitives, SizeHeaderProtocol>::read(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#14 0x00007e9716ae5a5c in SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}::operator()() const () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#15 0x00007e9716bb9183 in void std::__invoke_impl<void, SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}>(std::__invoke_other, SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}&&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#16 0x00007e9716bb41a2 in std::__invoke_result<SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}>::type std::__invoke<SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (cha--Type <RET> for more, q to quit, c to continue without paging--
r const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}>(SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}&&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#17 0x00007e9716badc36 in void std::thread::_Invoker<std::tuple<SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#18 0x00007e9716ba810e in std::thread::_Invoker<std::tuple<SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}> >::operator()() () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#19 0x00007e9716b9ea7a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::connect(std::function<void (char const*, unsigned int, char const*, unsigned int)> const&, std::function<void ()> const&, int)::{lambda()#1}> > >::_M_run() () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#20 0x00007e9718ece410 in ?? () from /var/ossec/bin/../lib/libstdc++.so.6
#21 0x00007e9723494ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#22 0x00007e9723526850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 41 (Thread 0x7e96fcbd1640 (LWP 22043) "wazuh-modulesd"):
#0  __futex_abstimed_wait_common64 (private=128, cancel=true, abstime=0x0, op=265, expected=22053, futex_word=0x7e970ad6f910) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=128, abstime=0x0, clockid=0, expected=22053, futex_word=0x7e970ad6f910) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7e970ad6f910, expected=22053, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=128) at ./nptl/futex-internal.c:139
#3  0x00007e9723496624 in __pthread_clockjoin_ex (threadid=139187187021376, thread_return=0x0, clockid=0, abstime=0x0, block=<optimized out>) at ./nptl/pthread_join_common.c:105
#4  0x00007e9718ece623 in std::thread::join() () from /var/ossec/bin/../lib/libstdc++.so.6
#5  0x00007e9716ae6204 in SocketClient<Socket<OSPrimitives, SizeHeaderProtocol>, EpollWrapper>::stop() () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#6  0x00007e9716acc07d in SocketDBWrapper::query(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#7  0x00007e9716ba0924 in TScanAgentList<TScanContext<OsDataCache, GlobalData>, AbstractHandler<std::shared_ptr<TScanContext<OsDataCache, GlobalData> > > >::scanAgentPackages(AgentData const&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#8  0x00007e9716b8eb7c in TScanAgentList<TScanContext<OsDataCache, GlobalData>, AbstractHandler<std::shared_ptr<TScanContext<OsDataCache, GlobalData> > > >::handleRequest(std::shared_ptr<TScanContext<OsDataCache, GlobalData> >) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#9  0x00007e9716b14512 in AbstractHandler<std::shared_ptr<TScanContext<OsDataCache, GlobalData> > >::handleRequest(std::shared_ptr<TScanContext<OsDataCache, GlobalData> >) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#10 0x00007e9716b9022b in TBuildAllAgentListContext<TScanContext<OsDataCache, GlobalData> >::handleRequest(std::shared_ptr<TScanContext<OsDataCache, GlobalData> >) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#11 0x00007e9716aff582 in _ZNK17TScanOrchestratorI12TScanContextI11OsDataCache10GlobalDataE20TFactoryOrchestratorI15TPackageScannerI20TDatabaseFeedManagerI16IndexerConnector13PolicyManager15ContentRegister16RouterSubscriber17UNIXSocketRequestN5Utils15TRocksDBWrapperIN7rocksdb2DBEEEES3_S2_E32TEventPackageAlertDetailsBuilderISH_S3_E26TScanOsAlertDetailsBuilderISH_S3_E20TEventDetailsBuilderISH_S3_E18TAlertClearBuilderISH_S3_E10TOsScannerISH_S3_15SocketDBWrapperE15TCleanInventoryIS3_15AbstractHandlerISt10shared_ptrIS3_EEE21TEventDeleteInventoryIS3_E21TEventInsertInventoryIS3_E18TScanInventorySyncIS3_E16TClearSendReportIS3_22TThreadEventDispatcherINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1D_St8functionIFvRSt5queueIS1D_St5dequeIS1D_SaIS1D_EEEEE12RocksDBQueueIS1D_S1D_ENSC_10TSafeQueueIS1D_S1D_S1O_EEEE16TEventSendReportIS3_S1R_E14TResultIndexerIS7_S3_ESH_S7_S3_25TBuildAllAgentListContextIS3_E32TBuildSingleAgentListInfoContextIS3_E20TCleanAgentInventoryIS3_SY_E14TScanAgentListIS3_SY_E20TGlobalSyncInventoryIS7_S3_EESY_S7_SH_SS_12OSPrimitivesLi60EE3runESt7variantIJPKN18SyscollectorDeltas5DeltaEPKN27SyscollectorSynchronization7SyncMsgEPKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorS1D_blmdSaNS2K_14adl_serializerES2N_IhSaIhEEEEEERKNSE_13PinnableSliceEb () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#12 0x00007e9716ae9d22 in _ZNK17TScanOrchestratorI12TScanContextI11OsDataCache10GlobalDataE20TFactoryOrchestratorI15TPackageScannerI20TDatabaseFeedManagerI16IndexerConnector13PolicyManager15ContentRegister16RouterSubscriber17UNIXSocketRequestN5Utils15TRocksDBWrapperIN7rocksdb2DBEEEES3_S2_E32TEventPackageAlertDetailsBuilderISH_S3_E26TScanOsAlertDetailsBuilderISH_S3_E20TEventDetailsBuilderISH_S3_E18TAlertClearBuilderISH_S3_E10TOsScannerISH_S3_15SocketDBWrapperE15TCleanInventoryIS3_15AbstractHandlerISt10shared_ptrIS3_EEE21TEventDeleteInventoryIS3_E21TEventInsertInventoryIS3_E18TScanInventorySyncIS3_E16TClearSendReportIS3_22TThreadEventDispatcherINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1D_St8functionIFvRSt5queueIS1D_St5dequeIS1D_SaIS1D_EEEEE12RocksDBQueueIS1D_S1D_ENSC_10TSafeQueueIS1D_S1D_S1O_EEEE16TEventSendReportIS3_S1R_E14TResultIndexerIS7_S3_ESH_S7_S3_25TBuildAllAgentListContextIS3_E32TBuildSingleAgentListInfoContextIS3_E20TCleanAgentInventoryIS3_SY_E14TScanAgentListIS3_SY_E20TGlobalSyncInventoryIS7_S3_EESY_S7_SH_SS_12OSPrimitivesLi60EE12processEventERKNSE_13PinnableSliceEb () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#13 0x00007e9716aa5529 in ?? () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#14 0x00007e9716aa7e2e in ?? () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#15 0x00007e9716b14b9b in std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>::operator()(std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&) const () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#16 0x00007e9716affcdb in TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >::dispatch() () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#17 0x00007e9716bb90ed in void std::__invoke_impl<void, void (TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >::*)(), TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >*>(std::__invoke_memfun_deref, void (TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >::*&&)(), TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >*&&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#18 0x00007e9716bb40f7 in std::__invoke_result<void (TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >::*)(), TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >*>::type std::__invoke<void (TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >::*)(), TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >*>(void (TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >::*&&)(), TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >*&&) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#19 0x00007e9716badbd9 in void std::thread::_Invoker<std::tuple<void (TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >::*)(), TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#20 0x00007e9716ba80da in std::thread::_Invoker<std::tuple<void (TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >::*)(), TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >*> >::operator()() () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#21 0x00007e9716b9ea3a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >::*)(), TThreadEventDispatcher<rocksdb::Slice, rocksdb::PinnableSlice, std::function<void (std::queue<rocksdb::PinnableSlice, std::deque<rocksdb::PinnableSlice, std::allocator<rocksdb::PinnableSlice> > >&)>, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice>, Utils::TSafeQueue<rocksdb::Slice, rocksdb::PinnableSlice, RocksDBQueue<rocksdb::Slice, rocksdb::PinnableSlice> > >*> > >::_M_run() () from /var/ossec/bin/../lib/libvulnerability_scanner.so
#22 0x00007e9718ece410 in ?? () from /var/ossec/bin/../lib/libstdc++.so.6
#23 0x00007e9723494ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#24 0x00007e9723526850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
