### ISSUE TITLE
Error: circuit_breaking_exception

### ISSUE THREAD

**Issue by XandorMaker** [wazuh/wazuh#23537]
| 4.7.4 | 40717 | Wazuh Dashboard | master node | cluster config| Ubuntu LTS 22.04 |

Was working fine bat after slave node finished disk space and i erased some syslog logs in /var/log directory dashboard started to do multiple errors. 

Tried to edit /etc/wazuh-indexer/jvm.options

actual parameter is: 
-Xms4g
-Xmx4g
on master node

Version: 2.8.0
Build: 47402
Error
    at Fetch._callee3$ (https://wazuh.local.ego.energy/47402/bundles/core/core.entry.js:15:585158)
    at tryCatch (https://wazuh.local.ego.energy/47402/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910)
    at Generator.invoke [as _invoke] (https://wazuh.local.ego.energy/47402/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790926)
    at Generator.next (https://wazuh.local.ego.energy/47402/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105)
    at fetch_asyncGeneratorStep (https://wazuh.local.ego.energy/47402/bundles/core/core.entry.js:15:578070)
    at _next (https://wazuh.local.ego.energy/47402/bundles/core/core.entry.js:15:578386)

**Comment by XandorMaker** [comment]
Looks like solved by editing /etc/wazuh-indexer/jvm.options
setting this to: 
-Xms4g
-Xmx4g

<img width="497" alt="image" src="https://github.com/wazuh/wazuh/assets/5004895/72c86750-1efe-4f37-b7c5-8c6fea8b63f8">


Yet logs are not incoming.
![image](https://github.com/wazuh/wazuh/assets/5004895/4fead21f-6c5d-452c-8dd5-badaa890029a)

is there some other possible issue? paint

**Comment by XandorMaker** [comment]
Some additional info:

> root@onpremises01Worker:/var/ossec/bin# ./verify-agent-conf
> 
> verify-agent-conf: Verifying [etc/shared/default/agent.conf]
> verify-agent-conf: OK
> 
> verify-agent-conf: Verifying [etc/shared/AWS/agent.conf]
> verify-agent-conf: OK
> 
> verify-agent-conf: Verifying [etc/shared/onpremises/agent.conf]
> verify-agent-conf: OK
> 

Also events actually incoming, bat why in the world it is "disconnected" in the dashboard???
![image](https://github.com/wazuh/wazuh/assets/5004895/3a05347a-bf40-4de8-b641-756e17cf050c)
