### ISSUE TITLE
Error in Custom Logs Buckets when CSV file exceeds certain size

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#23554]
| Affected integration |
|---|
| AWS Custom Logs Buckets |

## Description

It was found that the AWS Custom Logs Buckets integration fails when a CSV file exceeds a certain size, showing the following message:
```console
# /var/ossec/wodles/aws/aws-s3 --subscriber buckets --queue QUEUE --aws_profile dev --debug 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: The SQS queue is: https://queue.amazonaws.com/123456789012/QUEUE
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: Retrieving messages from: QUEUE
DEBUG: The message is: {'Records': ...}
DEBUG: +++ Log file does not contain JSON objects. Trying with other formats.
DEBUG: +++ Log file is CSV formatted.
DEBUG: +++ Error: Could not determine delimiter
Unknown error: Could not determine delimiter
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 3547, in obtain_logs
    return [dict(event.get('detail', event), source="custom")
  File "/var/ossec/wodles/aws/aws-s3.py", line 3547, in <listcomp>
    return [dict(event.get('detail', event), source="custom")
  File "/var/ossec/wodles/aws/aws-s3.py", line 3485, in _json_event_generator
    json_data, json_index = decoder.raw_decode(data)
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 4246, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 4233, in main
    asl_queue.sync_events()
  File "/var/ossec/wodles/aws/aws-s3.py", line 3793, in sync_events
    self.bucket_handler.process_file(message["route"])
  File "/var/ossec/wodles/aws/aws-s3.py", line 3589, in process_file
    formatted_logs = self.obtain_logs(bucket=bucket_path, log_path=log_path)
  File "/var/ossec/wodles/aws/aws-s3.py", line 3555, in obtain_logs
    dialect = csv.Sniffer().sniff(f.read(1024))
  File "/var/ossec/framework/python/lib/python3.9/csv.py", line 187, in sniff
    raise Error("Could not determine delimiter")
_csv.Error: Could not determine delimiter
```

The error is related to the `dialect = csv.Sniffer().sniff(f.read(1024))` line, specifically with the argument passed to the `sniff` method (used to determine the delimiter). It should receive a data sample that should not depend on the size of the file, being the header sufficient for this (which can be obtained with `f.readline()`).

The objective is to modify the mentioned line, manually testing the module with files of different sizes. 

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by fdalmaup** [comment]
# Issue Update

- The required modification was carried out but the error described in #23672 was found and the fix is required before moving forward with the current issue. The issue is put On hold until the fix is merged.

**Comment by fdalmaup** [comment]
# Issue Update

Rebased the dev branch and tested the module's behavior:
<details><summary>Manual execution</summary>

```
root@16f4ded61804:/# /var/ossec/wodles/aws/aws-s3 --subscriber buckets --queue QUEUE --aws_profile dev --debug 3
DEBUG: +++ Debug mode on - Level: 3
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: The SQS queue is: https://sqs.us-east-1.amazonaws.com/ACCOUNT_ID/QUEUE
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: Retrieving messages from: QUEUE
DEBUG: The raw message is: {'Messages': ...}
DEBUG: The message is: {'Records': [...]}
DEBUG: +++ Log file does not contain JSON objects. Trying with other formats.
DEBUG: +++ Log file is CSV formatted.
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "56962", "dstport": "4444", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953802", "end": "1674953814", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "58431", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953802", "end": "1674953814", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "62000", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953837", "end": "1674953844", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "58996", "dstport": "80", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953837", "end": "1674953844", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "52890", "dstport": "6379", "protocol": "6", "packets": "1", "bytes": "60", "start": "1674953861", "end": "1674953862", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "45201", "dstport": "8091", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953891", "end": "1674953907", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "12919", "dstport": "30111", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953891", "end": "1674953907", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "15000", "dstport": "21314", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953891", "end": "1674953907", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "49000", "dstport": "1080", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953943", "end": "1674953944", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "19867", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "1274", "dstport": "34161", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "57635", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "0", "dstport": "0", "protocol": "1", "packets": "1", "bytes": "36", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "52349", "dstport": "135", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "57635", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "0", "dstport": "0", "protocol": "1", "packets": "1", "bytes": "36", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "52349", "dstport": "135", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "57635", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "0", "dstport": "0", "protocol": "1", "packets": "1", "bytes": "36", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "52349", "dstport": "135", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "57635", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "0", "dstport": "0", "protocol": "1", "packets": "1", "bytes": "36", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "52349", "dstport": "135", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "57635", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "0", "dstport": "0", "protocol": "1", "packets": "1", "bytes": "36", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "52349", "dstport": "135", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "57635", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "0", "dstport": "0", "protocol": "1", "packets": "1", "bytes": "36", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-LONG_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "52349", "dstport": "135", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953952", "end": "1674953979", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: Message deleted from queue: QUEUE
DEBUG: Retrieving messages from: QUEUE
DEBUG: The raw message is: {'Messages': ...}
DEBUG: The message is: {'Records': [...]}
DEBUG: +++ Log file does not contain JSON objects. Trying with other formats.
DEBUG: +++ Log file is CSV formatted.
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-SHORT_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "56962", "dstport": "4444", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953802", "end": "1674953814", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: Message deleted from queue: QUEUE
DEBUG: Retrieving messages from: QUEUE
DEBUG: The raw message is: {'Messages': ...}
DEBUG: The message is: {'Records': [...]}
DEBUG: +++ Log file does not contain JSON objects. Trying with other formats.
DEBUG: +++ Log file is CSV formatted.
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-MEDIUM_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "56962", "dstport": "4444", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953802", "end": "1674953814", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-MEDIUM_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "58431", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953802", "end": "1674953814", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-MEDIUM_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "62000", "dstport": "23", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953837", "end": "1674953844", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-MEDIUM_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "58996", "dstport": "80", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953837", "end": "1674953844", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-MEDIUM_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "52890", "dstport": "6379", "protocol": "6", "packets": "1", "bytes": "60", "start": "1674953861", "end": "1674953862", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-MEDIUM_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "45201", "dstport": "8091", "protocol": "6", "packets": "1", "bytes": "40", "start": "1674953891", "end": "1674953907", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: +++ The "None" regex did not find a match in the "None" field. The event will be processed.
DEBUG: {"integration": "aws", "aws": {"log_info": {"log_file": "vpcflowlogs_sa-east-1_fl-MEDIUM_FILE.log.gz", "s3bucket": "QUEUE"}, "version": "2", "account-id": "ACCOUNT_ID", "interface-id": "eni-0a776670483cc4c52", "srcaddr": "...", "dstaddr": "...", "srcport": "12919", "dstport": "30111", "protocol": "6", "packets": "1", "bytes": "44", "start": "1674953891", "end": "1674953907", "action": "REJECT", "log-status": "OK", "source": "custom"}}
DEBUG: Message deleted from queue: QUEUE
DEBUG: Retrieving messages from: QUEUE
DEBUG: The raw message is: {'ResponseMetadata': {'RequestId': '0f1c3d31-6ba3-59a7-be23-62222ed7cc67', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '0f1c3d31-6ba3-59a7-be23-62222ed7cc67', 'date': 'Thu, 18 Jul 2024 16:31:04 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '2', 'connection': 'keep-alive'}, 'RetryAttempts': 0}}
```

</details>

The number of events sent to Analysisd was verified using the `logall` option and counting the logs in the `/var/ossec/logs/archives/archives.log` file which matched the number of `DEBUG: {"integration": "aws"...` messages from the execution above:

```
root@16f4ded61804:/# grep aws /var/ossec/logs/archives/archives.log | wc -l
37
```

**Comment by fdalmaup** [comment]
# Execution in a Wazuh Agent using Python 3.8

<details><summary>Agent's Python version</summary>

```
root@80727f7720ae:/# /usr/bin/env python3 --version
Python 3.8.10
root@80727f7720ae:/# head /var/ossec/wodles/aws/aws-s3 
#!/usr/bin/env python3
```

</details>

<details><summary>ossec.conf</summary>

```xml
<wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>1h</interval>
    <run_on_start>yes</run_on_start>
    <subscriber type="buckets">
        <sqs_name>QUEUE_NAME</sqs_name>
        <aws_profile>dev</aws_profile>
    </subscriber>
</wodle>
```

</details>


<details><summary>ossec.log</summary>

```
2024/07/19 10:05:09 wazuh-modulesd:aws-s3[27629] wm_aws.c:62 at wm_aws_main(): INFO: Module AWS started
2024/07/19 10:05:09 wazuh-modulesd:aws-s3[27629] wm_aws.c:84 at wm_aws_main(): INFO: Starting fetching of logs.
2024/07/19 10:05:09 wazuh-modulesd:aws-s3[27629] wm_aws.c:196 at wm_aws_main(): INFO: Executing Subscriber fetch: (Type and SQS: buckets QUEUE_NAME)
2024/07/19 10:05:09 wazuh-modulesd:aws-s3[27629] wm_aws.c:707 at wm_aws_run_subscriber(): DEBUG: Create argument list
2024/07/19 10:05:09 wazuh-modulesd:aws-s3[27629] wm_aws.c:786 at wm_aws_run_subscriber(): DEBUG: Launching S3 Subscriber Command: wodles/aws/aws-s3 --subscriber buckets --queue QUEUE_NAME --aws_profile dev --debug 2
2024/07/19 10:05:33 wazuh-modulesd:aws-s3[27629] wm_aws.c:827 at wm_aws_run_subscriber(): DEBUG: Subscriber: buckets QUEUE_NAME  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: The SQS queue is: https://sqs.us-east-1.amazonaws.com/ACCOUNT_ID/QUEUE_NAME
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: Retrieving messages from: QUEUE_NAME
DEBUG: The message is: {'Records': [...]}
DEBUG: +++ Log file does not contain JSON objects. Trying with other formats.
DEBUG: +++ Log file is CSV formatted.
DEBUG: Message deleted from queue: QUEUE_NAME
DEBUG: Retrieving messages from: QUEUE_NAME
DEBUG: The message is: {'Records': [...]}
DEBUG: The message is: {'Records': [...]}
DEBUG: +++ Log file does not contain JSON objects. Trying with other formats.
DEBUG: +++ Log file is CSV formatted.
DEBUG: Message deleted from queue: QUEUE_NAME
DEBUG: +++ Log file does not contain JSON objects. Trying with other formats.
DEBUG: +++ Log file is CSV formatted.
DEBUG: Message deleted from queue: QUEUE_NAME
DEBUG: Retrieving messages from: QUEUE_NAME
2024/07/19 10:05:33 wazuh-modulesd:aws-s3[27629] wm_aws.c:201 at wm_aws_main(): INFO: Fetching logs finished.
2024/07/19 10:05:33 wazuh-modulesd:aws-s3[27629] wm_aws.c:80 at wm_aws_main(): DEBUG: Sleeping until: 2024/07/19 11:05:09
```

</details>

The number of logs found in the `/var/ossec/logs/archives/archives.log` file was the same as the one found [here](https://github.com/wazuh/wazuh/issues/23554#issuecomment-2237058873).

**Comment by fdalmaup** [comment]
ETA extended until August 16, reason: 
- The team is working on higher-priority tasks.
