### ISSUE TITLE
node_name error using the API

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#2365]
When the `agent-info` file of an agent is empty, `wazuh-modulesd` inserts an empty value in the `node_name` colum of the `agent` table. The API needs to know that value to send the request to the proper manager.

The API is able to handle the `unknown` value for the `node_name` column, that is the default value when the table is created: https://github.com/wazuh/wazuh/blob/v3.7.2/src/wazuh_db/schema_global.sql#L27. So, that column must not be updated if the new value is empty/null. 

Trace:

```
/syscheck/006/last_scan?pretty
{
   "error": 1000,
   "message": "'node_name'"
}
```

```
# echo '{"function":"/syscheck/:agent_id/last_scan","arguments":{"agent_id":"006","wait_for_complete":false},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
DEBUG:wazuh.cluster.dapi.dapi:[Cluster] [D API        ] Distributed API is enabled.
{"message": "Wazuh-Python Internal Error: 'node_name'", "error": 1000}
Traceback (most recent call last):
  File "/var/ossec/api/models/wazuh-api.py", line 171, in <module>
    data = dapi.distribute_function(request, pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 61, in distribute_function
    return forward_request(input_json, node_info['node'], pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 198, in forward_request
    node_name, is_list = get_solver_node(input_json, master_name)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 245, in get_solver_node
    node_name = Agent.get_agent(input_json['arguments']['agent_id'], select=select_node)['node_name']
KeyError: 'node_name'
```

```
sqlite> select * from agent where id=006;
id|name|ip|internal_key|os_name|os_version|os_major|os_minor|os_codename|os_build|os_platform|os_uname|os_arch|version|config_sum|merged_sum|manager_host|node_name|date_add|last_keepalive|status|fim_offset|reg_offset|group
6|agent1|any|2**********************b3|||||||||||||||2019-01-09 17:17:14|2019-01-09 17:17:40|empty|0|0|026836
```

```
# cat /var/ossec/queue/agent-info/agent1-any

```

The agent is shown as `Disconnected` by `agent_control` and `cluster_control`.

**Comment by snaow** [comment]
Ping @wazuh/core 

`agent-info` is emtpy and status is `Disconnected` and `keep_alive` has a value.
