### ISSUE TITLE
Exception raised when a cluster node is disconnected from the master. Then the node connection isn't accepted

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#2367]
**OS**
_CentOS7_

**Wazuh version**
_3.8.0_

**Install method**
_packages_

**Python version**
_3.6_

**Log sample**

```
2019-01-16 09:38:37,082 CRITICAL: [Master ] [WorkerChecks] [node03]: Last keep alive is higher than allowed maximum. Disconnecting.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/var/ossec/bin/../framework/wazuh/cluster/master.py", line 698, in run
    for worker, worker_info in self.master.get_connected_workers().items():
RuntimeError: dictionary changed size during iteration
```
```
2019-01-16 09:41:13,596 INFO    : [Master ] [node03]: Connected.
...
2019-01-16 09:43:10,033 ERROR   : [Master ] Error accepting connection from 10.0.0.102: Incoming connection from '10.0.0.102' rejected: There is already a node with the same ID ('node03') connected.
2019-01-16 09:43:10,034 INFO    : [Master ] Connection with 10.0.0.102 closed.
```

Bug description
----------------
If the worker node lose his connection for 2 minutes at least the master node disconnect the worker node. Then the exception is raised.
After that the worker node recover his connection but the master doesn't accept the messages because it has a node registered with that IP

**Comment by Skeptor** [comment]
I've tried to change the line 698 of `/var/ossec/framework/wazuh/cluster/master.py` by advise of @mgmacias95 to replace `self.master.get_connected_workers().items()` with `self.master.get_connected_workers().copy().items()` and the exception is solved.
 Also i'm testing the solution and the worker node reconnects to the master
