### ISSUE TITLE
Review and fix subscriber type related classes in the AWS module

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#23672]
| Affected integration |
|---|
| AWS |

## Description

After #18680, the AWS deprecated plain text authentication method was removed. This method generated a high level of coupling in many of the `WazuhIntegration` subclasses, having every authentication-related method a pair of parameters for the `access key` and `secret key`, e.g. the `AWSSQSQueue` class:
https://github.com/wazuh/wazuh/blob/9709e57d92d611612c3f7eb178caf8638d73bf2e/wodles/aws/subscribers/sqs_queue.py#L51

This causes the module to fail when using the `subscriber` type:

```
root@3bff16b44fa8:/# /var/ossec/wodles/aws/aws-s3 --subscriber buckets --queue queue --aws_profile dev --debug 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Error: WazuhIntegration.get_sts_client() takes 2 positional arguments but 4 were given
Unknown error: WazuhIntegration.get_sts_client() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 199, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 172, in main
    asl_queue = subscribers.sqs_queue.AWSSQSQueue(
  File "/var/ossec/wodles/aws/subscribers/sqs_queue.py", line 51, in __init__
    self.sts_client = self.get_sts_client(None, None, profile)
TypeError: WazuhIntegration.get_sts_client() takes 2 positional arguments but 4 were given

```

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by RamosFe** [comment]
## Update

Started the code review of the AWS module.

**Comment by RamosFe** [comment]
## Update

Deleted the extra arguments and fixed some Unit Tests that expected 3 arguments instead of the profile.

Results:
```bash
(env) federamos@pop-os:~/Documents/Wazuh/Repositories/wazuh/wodles/aws$ PYTHONPATH=/home/federamos/Documents/Wazuh/Repositories/wazuh/framework/:/home/federamos/Documents/Wazuh/Repositories/wazuh/api pytest tests/test_sqs_queue.py 
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.5.0
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh/wodles/aws/tests
configfile: pytest.ini
plugins: asyncio-0.18.1, html-2.1.1, metadata-3.1.1, cov-4.1.0, tavern-1.23.5, anyio-4.1.0, trio-0.8.0
asyncio: mode=auto
collected 7 items                                                                                                                                                                                                                       

tests/test_sqs_queue.py .......                                                                                                                                                                                                   [100%]

=========================================================================================================== warnings summary ============================================================================================================
../../env/lib/python3.10/site-packages/botocore/httpsession.py:18
  /home/federamos/Documents/Wazuh/Repositories/wazuh/env/lib/python3.10/site-packages/botocore/httpsession.py:18: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================================================================================== 7 passed, 1 warning in 0.23s ======================================================================================================
``

**Comment by RamosFe** [comment]
## Update

After being OOO, I continue with the changes to make the SQS IT tests run without any errors. Waiting for the results to send this issue to review.

**Comment by RamosFe** [comment]
## Update

After running the IT with the changes of this branch, no errores were found related to the changes of this Issue.
- Master branch AWS IT https://github.com/wazuh/wazuh/actions/runs/9780109200/job/27000961563
- This Issue branch AWS IT https://github.com/wazuh/wazuh/actions/runs/9779020522/job/26997209104

> One difference was found between both executions, an error appeared due to exceding the VPC API Call limit 
> ```
> botocore.exceptions.ClientError: An error occurred (VpcLimitExceeded) when calling the CreateVpc operation: The maximum number of VPCs has been reached.
> ```
