### ISSUE TITLE
Increase AIT delay after restart

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#23728]
## Description
Some [AIT](https://github.com/wazuh/wazuh/pull/23199/checks?check_run_id=25489515070) failed in the Connexion 3.0 PR again. It seems that after any restart, the API is taking a long time to be ready again:
```
2024/05/28 08:19:07 INFO: testing 172.18.0.1 "PUT /manager/restart" with parameters {} and body {} done in 0.054s: 200
2024/05/28 08:19:42 INFO: Shutdown wazuh-apid server.
2024/05/28 08:19:49 INFO: Checking RBAC database integrity...
2024/05/28 08:19:49 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/05/28 08:19:49 INFO: RBAC database integrity check finished successfully
```

As a consequence, stages where a restart is performed end up failing. We need to re-order those stages so that restart is performed as few times as possible while increasing the delay after restart.

Here are the artifacts of the build: [artifacts.zip](https://github.com/wazuh/wazuh/files/15472429/artifacts.zip)

Also, `test_manager_endpoints.tavern.yaml::GET /manager/logs` seems to be consistently failing even when run in a local environment:
<details>
<summary>test_manager_endpoints.tavern.yaml</summary>

```
(python310) selu@selu-pc:~/Git/wazuh/api/test/integration$ pytest -vv test_manager_endpoints.tavern.yaml --nobuild
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0 -- /home/selu/venv/python310/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.10.12', 'Platform': 'Linux-5.15.0-107-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.1.2', 'pluggy': '1.3.0'}, 'Plugins': {'metadata': '3.0.0', 'asyncio': '0.18.1', 'html': '3.1.1', 'anyio': '4.3.0', 'aiohttp': '1.0.4', 'trio': '0.7.0', 'tavern': '1.23.5', 'cov': '5.0.0'}}
rootdir: /home/selu/Git/wazuh/api/test/integration, configfile: pytest.ini
plugins: metadata-3.0.0, asyncio-0.18.1, html-3.1.1, anyio-4.3.0, aiohttp-1.0.4, trio-0.7.0, tavern-1.23.5, cov-5.0.0
asyncio: mode=auto
collected 35 items                                                                                                                                                                                           

test_manager_endpoints.tavern.yaml::GET /manager/status PASSED                                                                                                                                         [  2%]
test_manager_endpoints.tavern.yaml::GET /manager/info PASSED                                                                                                                                           [  5%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[alerts] PASSED                                                                                                                [  8%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[auth] PASSED                                                                                                                  [ 11%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[cis-cat] PASSED                                                                                                               [ 14%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[cluster] PASSED                                                                                                               [ 17%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[command] PASSED                                                                                                               [ 20%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[global] PASSED                                                                                                                [ 22%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[localfile] PASSED                                                                                                             [ 25%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[osquery] PASSED                                                                                                               [ 28%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[remote] PASSED                                                                                                                [ 31%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[rootcheck] PASSED                                                                                                             [ 34%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[ruleset] PASSED                                                                                                               [ 37%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[sca] PASSED                                                                                                                   [ 40%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[syscheck] PASSED                                                                                                              [ 42%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[syscollector] PASSED                                                                                                          [ 45%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[vulnerability-detection] PASSED                                                                                               [ 48%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[indexer] PASSED                                                                                                               [ 51%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration PASSED                                                                                                                                  [ 54%]
test_manager_endpoints.tavern.yaml::GET /manager/daemons/stats PASSED                                                                                                                                  [ 57%]
test_manager_endpoints.tavern.yaml::GET /manager/stats PASSED                                                                                                                                          [ 60%]
test_manager_endpoints.tavern.yaml::GET /manager/stats/hourly PASSED                                                                                                                                   [ 62%]
test_manager_endpoints.tavern.yaml::GET /manager/stats/weekly PASSED                                                                                                                                   [ 65%]
test_manager_endpoints.tavern.yaml::GET /manager/stats/analysisd PASSED                                                                                                                                [ 68%]
test_manager_endpoints.tavern.yaml::GET /manager/stats/remoted PASSED                                                                                                                                  [ 71%]
test_manager_endpoints.tavern.yaml::GET /manager/api/config PASSED                                                                                                                                     [ 74%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration/validation (OK) PASSED                                                                                                                  [ 77%]
test_manager_endpoints.tavern.yaml::GET /manager/configuration/{component}/{configuration} PASSED                                                                                                      [ 80%]
test_manager_endpoints.tavern.yaml::PUT /manager/configuration PASSED                                                                                                                                  [ 82%]
test_manager_endpoints.tavern.yaml::GET /manager/version/check PASSED                                                                                                                                  [ 85%]
test_manager_endpoints.tavern.yaml::GET /manager/version/check with update_check disabled PASSED                                                                                                       [ 88%]
test_manager_endpoints.tavern.yaml::GET /manager/version/check with update check service error PASSED                                                                                                  [ 91%]
test_manager_endpoints.tavern.yaml::GET /manager/logs FAILED                                                                                                                                           [ 94%]
test_manager_endpoints.tavern.yaml::GET /manager/logs/summary PASSED                                                                                                                                   [ 97%]
test_manager_endpoints.tavern.yaml::PUT /manager/restart PASSED                                                                                                                                        [100%]

================================================================================================== FAILURES ==================================================================================================
______________________________________________________ /home/selu/Git/wazuh/api/test/integration/test_manager_endpoints.tavern.yaml::GET /manager/logs _______________________________________________________
Format variables:
  protocol:s = 'https'
  host:s = 'localhost'
  port:d = '55000'
  test_login_token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzE2OTEwNzIxLCJleHAiOjE3MTY5MTE2MjEsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AJnsizc4Ne1z8OIqyiEBBAUYkqQFJ9T1r5zH9nnZoLlr3i_udN97AEStEuZc67Y6ulVfKxLVIm2xY_eqFO-g5CstAetzKmGy0OZhmGcDezkyaXxpTL8OCfq__doDL8iUlujDaTHWmMPQdejX1GlBWebgDz2TUlAF6geJUqyMdtBeiAER'

Source test stage (line 1569):
  - name: Filters -> offset=3, level=debug, limit=4
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/manager/logs"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        limit: 4
        offset: 3
        level: debug
    response:
        status_code: 200
        json:
          error: 0
          data:
            affected_items:
              - <<: *manager_log
              - <<: *manager_log
              - <<: *manager_log
              - <<: *manager_log
            failed_items: []
            total_affected_items: !anyint
            total_failed_items: 0



Formatted stage:
  name: Filters -> offset=3, level=debug, limit=4
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzE2OTEwNzIxLCJleHAiOjE3MTY5MTE2MjEsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.AJnsizc4Ne1z8OIqyiEBBAUYkqQFJ9T1r5zH9nnZoLlr3i_udN97AEStEuZc67Y6ulVfKxLVIm2xY_eqFO-g5CstAetzKmGy0OZhmGcDezkyaXxpTL8OCfq__doDL8iUlujDaTHWmMPQdejX1GlBWebgDz2TUlAF6geJUqyMdtBeiAER
    method: GET
    params:
      level: debug
      limit: 4
      offset: 3
    url: 'https://localhost:55000/manager/logs'
    verify: false
  response:
    json:
      data:
        affected_items:
        - description: !anystr ''
          level: !anystr ''
          tag: !anystr ''
          timestamp: !anystr ''
        - description: !anystr ''
          level: !anystr ''
          tag: !anystr ''
          timestamp: !anystr ''
        - description: !anystr ''
          level: !anystr ''
          tag: !anystr ''
          timestamp: !anystr ''
        - description: !anystr ''
          level: !anystr ''
          tag: !anystr ''
          timestamp: !anystr ''
        failed_items: []
        total_affected_items: !anyint ''
        total_failed_items: 0
      error: 0
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Filters -> offset=3, level=debug, limit=4' failed:
    - List item(s) not present in response: [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}, {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}, {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}, {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}]
--------------------------------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------------------------------
ERROR    tavern.response.base:base.py:41 List item(s) not present in response: [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}, {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}, {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}, {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}]
Traceback (most recent call last):
  File "/home/selu/venv/python310/lib/python3.10/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'data': {'affected_items': [],\n          'failed_items': [],\n          'total_affected_items': 0,\n          'total_failed_items': 0},\n 'error': 0,\n 'message': 'Could not read logs'} == {'data': {'affected_items': [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n                              'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n                              'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n                              'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},\n                             {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n                              'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n                              'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n                              'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},\n                             {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n                              'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n                              'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n                              'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},\n                             {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n                              'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n                              'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n                              'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}],\n          'failed_items': [],\n          'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f0a2b6410c0>,\n          'total_failed_items': 0},\n 'error': 0}
  Common items:
  {'error': 0}
  Differing items:
  {'data': {'affected_items': [], 'failed_items': [], 'total_affected_items': 0, 'total_failed_items': 0}} != {'data': {'affected_items': [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tave...tems': [], 'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f0a2b6410c0>, 'total_failed_items': 0}}
  Left contains 1 more item:
  {'message': 'Could not read logs'}
  Full diff:
    {
  +  'data': {'affected_items': [],
  -  'data': {'affected_items': [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -                               'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -                               'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -                               'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
  -                              {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -                               'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -                               'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -                               'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
  -                              {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -                               'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -                               'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -                               'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
  -                              {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -                               'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -                               'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -                               'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}],
              'failed_items': [],
  -           'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f0a2b6410c0>,
  +           'total_affected_items': 0,
              'total_failed_items': 0},
     'error': 0,
  +  'message': 'Could not read logs',
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/selu/venv/python310/lib/python3.10/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert {'affected_items': [],\n 'failed_items': [],\n 'total_affected_items': 0,\n 'total_failed_items': 0} == {'affected_items': [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n                     'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n                     'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n                     'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},\n                    {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n                     'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n                     'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n                     'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},\n                    {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n                     'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n                     'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n                     'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},\n                    {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n                     'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n                     'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n                     'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}],\n 'failed_items': [],\n 'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f0a2b6410c0>,\n 'total_failed_items': 0}
  Common items:
  {'failed_items': [], 'total_failed_items': 0}
  Differing items:
  {'total_affected_items': 0} != {'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f0a2b6410c0>}
  {'affected_items': []} != {'affected_items': [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.l...loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}]}
  Full diff:
    {
  +  'affected_items': [],
  -  'affected_items': [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -                      'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -                      'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -                      'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
  -                     {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -                      'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -                      'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -                      'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
  -                     {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -                      'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -                      'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -                      'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
  -                     {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -                      'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -                      'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -                      'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}],
     'failed_items': [],
  -  'total_affected_items': <tavern.util.loader.IntSentinel object at 0x7f0a2b6410c0>,
  +  'total_affected_items': 0,
     'total_failed_items': 0,
    }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/selu/venv/python310/lib/python3.10/site-packages/tavern/util/dict_util.py", line 406, in check_keys_match_recursive
    assert actual_val == expected_val
AssertionError: assert [] == [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n  'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n  'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n  'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},\n {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n  'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n  'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n  'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},\n {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n  'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n  'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n  'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},\n {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,\n  'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,\n  'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,\n  'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}]
  Right contains 4 more items, first extra item: {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel ob...l.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}
  Full diff:
    [
  +  ,
  -  {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -   'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -   'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -   'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
  -  {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -   'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -   'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -   'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
  -  {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -   'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -   'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -   'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
  -  {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>,
  -   'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>,
  -   'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>,
  -   'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>},
    ]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/selu/venv/python310/lib/python3.10/site-packages/tavern/response/base.py", line 97, in recurse_check_key_match
    check_keys_match_recursive(expected_block, block, [], strict)
  File "/home/selu/venv/python310/lib/python3.10/site-packages/tavern/util/dict_util.py", line 464, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/selu/venv/python310/lib/python3.10/site-packages/tavern/util/dict_util.py", line 464, in check_keys_match_recursive
    check_keys_match_recursive(
  File "/home/selu/venv/python310/lib/python3.10/site-packages/tavern/util/dict_util.py", line 516, in check_keys_match_recursive
    raise exceptions.KeyMismatchError(msg) from e
tavern.util.exceptions.KeyMismatchError: List item(s) not present in response: [{'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}, {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}, {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}, {'description': <tavern.util.loader.StrSentinel object at 0x7f0a2b641540>, 'level': <tavern.util.loader.StrSentinel object at 0x7f0a2b641480>, 'tag': <tavern.util.loader.StrSentinel object at 0x7f0a2b641c30>, 'timestamp': <tavern.util.loader.StrSentinel object at 0x7f0a2b640730>}]
============================================================================================== warnings summary ==============================================================================================
../../../../../venv/python310/lib/python3.10/site-packages/_pytest/nodes.py:633
  /home/selu/venv/python310/lib/python3.10/site-packages/_pytest/nodes.py:633: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)

test_manager_endpoints.tavern.yaml: 35 warnings
  <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead

test_manager_endpoints.tavern.yaml::GET /manager/logs
  /home/selu/venv/python310/lib/python3.10/site-packages/pytest_trio/plugin.py:62: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
    if issubclass(call.excinfo.type, trio.MultiError):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================================== short test summary info ===========================================================================================
FAILED test_manager_endpoints.tavern.yaml::GET /manager/logs
=========================================================================== 1 failed, 34 passed, 37 warnings in 274.01s (0:04:34) ============================================================================
```

</details> 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

The connexion 3.0 epic branch did not contain the changes from https://github.com/wazuh/wazuh/pull/23375 which were merged in 4.8.0 so I applied them to make log tests more stable. I also moved the CTI tests order to avoid a restart to disable the update check service and increased the delay after the restart from 50 seconds to 90.
