### ISSUE TITLE
Release 4.8.1 - RC 2 - Vulnerability Detection performance test

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#24504]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release stage issue**     |             https://github.com/wazuh/wazuh/issues/24417                   |
| **Main Vulnerability Detection tests issue**     |        https://github.com/wazuh/wazuh/issues/24464                      |
| **Version**                          |                   4.8.1                         |
| **Release stage**              |                   RC 2                      |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.8.1-rc2                                |
| **Previous Vulnerability performance tests issue**      |       https://github.com/wazuh/wazuh/issues/23982                     |

## Description

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads: high, medium, and low. This comparative analysis will provide a comprehensive understanding of the current status of the vulnerability detection module and will help identify any unexpected behavior.

### Methodology

Utilizing the CLUSTER-Workload_benchmarks_metrics pipeline to execute specified test cases automatically. Results will be manually analyzed and shared with the development team for validation adjustments.

### Test Cases

| Case | Description | Workers | Indexers |  Agents | EPS  | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- | --- |--- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 60  | 100 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 60 | 100 | 3h |
| Very High Activity | Simulate a large-scale environment with significant activity | 25 | 3 | 50000 | 1 | 60 | 100 | 1h |

**Considerations**

- `KIBANA_API_REQUESTS` should be enabled
- `EXTRA_LOAD_API_REQUESTS` should be enabled
- Due to the current operation of the simulator and how it does the EPS distribution with the frequency, we can expect the actual EPS to be about half, so it is necessary to set twice as much.

### Conclusion :red_circle: 

**New issues**

- https://github.com/wazuh/wazuh/issues/24546
- https://github.com/wazuh/wazuh/issues/24547
- https://github.com/wazuh/wazuh-qa/issues/5565

    
**Known issues**
- https://github.com/wazuh/wazuh/issues/8480
- https://github.com/wazuh/wazuh-indexer/issues/71
- https://github.com/wazuh/wazuh-packages/issues/2519
- https://github.com/wazuh/wazuh-packages/issues/1582
- https://github.com/wazuh/wazuh-packages/issues/1511
- https://github.com/wazuh/wazuh-packages/issues/1511

**Comment by Rebits** [comment]
- **Medium activity**: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/566/

**Comment by Rebits** [comment]
# Medium Activity :yellow_circle:

**Build**: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/566/
**Report**:  [artifacts.zip](https://github.com/user-attachments/files/16165230/artifacts.zip)
**Comparision with**: Compared with https://github.com/wazuh/wazuh/issues/23982#issuecomment-2160536342

***

## Logs :yellow_circle:
 
### Summary

**Known issues**
- https://github.com/wazuh/wazuh/issues/8480
- https://github.com/wazuh/wazuh-indexer/issues/71
- https://github.com/wazuh/wazuh-packages/issues/2519
- https://github.com/wazuh/wazuh-packages/issues/1582
- https://github.com/wazuh/wazuh-packages/issues/1511
- https://github.com/wazuh/wazuh-packages/issues/1511

***


## Metrics :green_circle: 

No abnormal behavior was detected. 

## Global Statistics :green_circle:

No abnormal behavior was detected. 

### Vulnerabilities State :green_circle:

No abnormal behavior was detected. 

***

### Alerts :green_circle:

No abnormal behavior was detected.

**Comment by Rebits** [comment]
# High Activity :yellow_circle:   
      
**Build**: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/569/
**Report**:  [artifacts.zip](https://github.com/user-attachments/files/16175718/artifacts.zip)
**Comparision**: https://github.com/wazuh/wazuh/issues/23982#issuecomment-2160539516


***

## Logs :yellow_circle:
 
### Summary

**Known issues**
- https://github.com/wazuh/wazuh/issues/8480
- https://github.com/wazuh/wazuh-indexer/issues/71
- https://github.com/wazuh/wazuh-packages/issues/2519
- https://github.com/wazuh/wazuh-packages/issues/1582
- https://github.com/wazuh/wazuh-packages/issues/1511
- https://github.com/wazuh/wazuh-packages/issues/1511


<details>

<summary> Master :yellow_circle: </summary>

- No username and password were set in the keystore. Expected
```
indexer-connector: WARNING: No username and password found in the keystore, using default values.
```

- Reported https://github.com/wazuh/wazuh/issues/8480
```
wazuh-remoted: ERROR: (1320): Agent '000' not found.
```

</details>
 
<details>

<summary> Worker 1 :yellow_circle: </summary> 

- No username and password were set in the keystore. Expected
```
indexer-connector: WARNING: No username and password found in the keystore, using default values.
indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-3-218.ec2.internal', 
```

- Expected in performance tests
```
wazuh-analysisd: WARNING: Syscollector decoder queue is full.
```

</details>


<details>

<summary> Worker 2 :yellow_circle: </summary>



- No username and password were set in the keystore. Expected
```
indexer-connector: WARNING: No username and password found in the keystore, using default values.
ndexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-13-219.ec2.internal', 
```

- Expected in performance tests
```
wazuh-analysisd: WARNING: Syscollector decoder queue is full.

```


</details>



<details>

<summary> Indexer 1 :red_circle: </summary>

- Opensearch related warning. Expected
```
[2024-07-08T17:09:11,828][WARN ][o.o.g.DanglingIndicesState] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_0] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
``` 

- Currently researching
```
[2024-07-08T17:09:15,006][INFO ][o.o.c.c.JoinHelper       ] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_0] failed to join {CLUSTER-Workload_benchmarks_metrics_B566_indexer_1}{0ARiGTijTQ65CStHLBXkHQ}{B0Crtj5JSUqI-j35mJpE0g}{172.31.10.85}{172.31.10.85:9300}{dimr}{shard_indexing_pressure_enabled=true} with JoinRequest{sourceNode={CLUSTER-Workload_benchmarks_metrics_B566_indexer_0}{0xkcRFZ8SYWctRwthVCdrA}{YxgDsb2hRtKxZJLb9IGrmQ}{172.31.3.133}{172.31.3.133:9300}{dimr}{shard_indexing_pressure_enabled=true}, minimumTerm=0, optionalJoin=Optional[Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={CLUSTER-Workload_benchmarks_metrics_B566_indexer_0}{0xkcRFZ8SYWctRwthVCdrA}{YxgDsb2hRtKxZJLb9IGrmQ}{172.31.3.133}{172.31.3.133:9300}{dimr}{shard_indexing_pressure_enabled=true}, targetNode={CLUSTER-Workload_benchmarks_metrics_B566_indexer_1}{0ARiGTijTQ65CStHLBXkHQ}{B0Crtj5JSUqI-j35mJpE0g}{172.31.10.85}{172.31.10.85:9300}{dimr}{shard_indexing_pressure_enabled=true}}]}
org.opensearch.transport.RemoteTransportException: [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1][172.31.10.85:9300][internal:cluster/coordination/join]
Caused by: org.opensearch.cluster.coordination.CoordinationStateRejectedException: incoming term 1 does not match current term 2
	at org.opensearch.cluster.coordination.CoordinationState.handleJoin(CoordinationState.java:269) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.handleJoin(Coordinator.java:1188) ~[opensearch-2.10.0.jar:2.10.0]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.opensearch.cluster.coordination.Coordinator.processJoinRequest(Coordinator.java:657) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.lambda$handleJoinRequest$7(Coordinator.java:620) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.transport.ClusterConnectionManager.connectToNode(ClusterConnectionManager.java:138) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TransportService.connectToNode(TransportService.java:493) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TransportService.connectToNode(TransportService.java:473) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.handleJoinRequest(Coordinator.java:602) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.JoinHelper.lambda$new$1(JoinHelper.java:209) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceivedDecorate(SecuritySSLRequestHandler.java:215) ~[?:?]
	at org.opensearch.security.transport.SecurityRequestHandler.messageReceivedDecorate(SecurityRequestHandler.java:315) ~[?:?]
	at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceived(SecuritySSLRequestHandler.java:163) ~[?:?]
	at org.opensearch.security.OpenSearchSecurityPlugin$7$1.messageReceived(OpenSearchSecurityPlugin.java:763) ~[?:?]
	at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:113) ~[?:?]
	at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) ~[?:?]
	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:454) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.10.0.jar:2.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

```

- Opensearch related warning. Expected
```
[2024-07-08T17:09:15,193][WARN ][o.o.p.c.s.h.ConfigOverridesClusterSettingHandler] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_0] Config override setting update called with empty string. Ignoring.
``` 


- Opensearch related error. Expected
```
[2024-07-08T17:09:16,228][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_0] Failure no such index [.opendistro_security] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
``` 


</details>


<details>

<summary> Indexer 2 :red_circle: </summary>


- Currently researching
```
{172.31.10.85:9300}{dimr}{shard_indexing_pressure_enabled=true}}]}
org.opensearch.transport.RemoteTransportException: [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1][172.31.10.85:9300][internal:cluster/coordination/join]
Caused by: org.opensearch.cluster.coordination.CoordinationStateRejectedException: became follower
	at org.opensearch.cluster.coordination.JoinHelper$CandidateJoinAccumulator.lambda$close$3(JoinHelper.java:649) [opensearch-2.10.0.jar:2.10.0]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) [?:?]
	at org.opensearch.cluster.coordination.JoinHelper$CandidateJoinAccumulator.close(JoinHelper.java:649) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.becomeFollower(Coordinator.java:755) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.onFollowerCheckRequest(Coordinator.java:354) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.FollowersChecker$2.doRun(FollowersChecker.java:228) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.10.0.jar:2.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```


- Opensearch related error. Expected
```
[2024-07-08T17:09:15,198][WARN ][o.o.p.c.s.h.ConfigOverridesClusterSettingHandler] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1] Config override setting update called with empty string. Ignoring.
```

- Opensearch related error. Expected
```
[2024-07-08T17:09:15,927][WARN ][o.o.o.i.ObservabilityIndex] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1] message: index [.opensearch-observability/PI7PqE2bSNWP0rT_oCPRvw] already exists
``` 

- Opensearch related error. Expected
``` 
[2024-07-08T17:09:16,162][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1] Failure no such index [.opendistro_security] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
``` 

- Opensearch related error. Expected
```
[2024-07-08T17:09:12,824][WARN ][o.o.s.p.SQLPlugin        ] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1] Master key is a required config for using create and update datasource APIs. Please set plugins.query.datasources.encryption.masterkey config in opensearch.yml in all the cluster nodes. More details can be found here: https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/datasources.rst#master-key-config-for-encrypting-credential-information
```


</details>


<details>

<summary> Dashboard :green_circle:  </summary>

No unexpected warnings/errors

</details>


<details>

<summary> Tools :green_circle: </summary>

No unexpected warnings/errors

</details>




***


## Metrics :green_circle: 

**Summary**

<details>

<summary> Master :red_circle:  </summary>

There are significant discrepancies in CPU and memory usage. It appears to be related to a data collection process. Upon closer examination, the pattern does not align, suggesting that the metrics gathering in version 4.8.0 did not function as expected. We should disregard the CPU usage from certain modules at the beginning.


</details>

<details>

<summary> Worker 1 :red_circle: </summary>

Duplicated usage of memory and file descriptors


</details>


<details>

<summary> Worker 2 :red_circle: </summary>

Duplicated usage of memory and file descriptors


</details>



<details>

<summary> Indexer 1 :green_circle:  </summary>

No abnormal behaviour

</details>


<details>

<summary> Indexer 2 :green_circle: </summary>

No abnormal behavior



</details>


<details>

<summary> Dashboard :green_circle:  </summary>

No abnormal behavior

</details>


## Statistics :green_circle:

**Summary**

<details>

<summary> Master :green_circle:  </summary>

No abnormal behavior was detected. 

</details>

<details>

<summary> Worker 1 :green_circle: </summary>

No abnormal behavior was detected. 


</details>


<details>

<summary> Worker 2 :green_circle: </summary>


No abnormal behavior was detected. 

</details>


## Vulnerabilities State :green_circle:

No abnormal behavior was detected. 

## Alerts :green_circle:
 
No abnormal behavior was detected.

**Comment by Rebits** [comment]
# Very High Activity :yellow_circle:    
      
**Build**: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/570/
**Report**:  
- [Artifact1.zip](https://github.com/user-attachments/files/16176888/Artifact1.zip)
- [Artifact2.zip](https://github.com/user-attachments/files/16176900/Artifact2.zip)
- [Artifact3.zip](https://github.com/user-attachments/files/16176907/Artifact3.zip)

**Comparision**: https://github.com/wazuh/wazuh/issues/23982#issuecomment-2160540345


***

## Logs :yellow_circle:
 
### Summary

**Known issues**
- https://github.com/wazuh/wazuh/issues/8480
- https://github.com/wazuh/wazuh-indexer/issues/71
- https://github.com/wazuh/wazuh-packages/issues/2519
- https://github.com/wazuh/wazuh-packages/issues/1582
- https://github.com/wazuh/wazuh-packages/issues/1511
- https://github.com/wazuh/wazuh-packages/issues/1511
- https://github.com/wazuh/wazuh-packages/issues/1968


<details>

<summary> Master :yellow_circle: </summary>

- No username and password were set in the keystore. Expected
```
indexer-connector: WARNING: No username and password found in the keystore, using default values.
```

- Reported https://github.com/wazuh/wazuh/issues/8480
```
wazuh-remoted: ERROR: (1320): Agent '000' not found.
```

</details>
 
<details>

<summary> Worker 1 :yellow_circle: </summary> 

- No username and password were set in the keystore. Expected
```
indexer-connector: WARNING: No username and password found in the keystore, using default values.
indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-3-218.ec2.internal', 
```

- Expected in performance tests
```
wazuh-analysisd: WARNING: Syscollector decoder queue is full.
```

</details>


<details>

<summary> Worker 2 :yellow_circle: </summary>



- No username and password were set in the keystore. Expected
```
indexer-connector: WARNING: No username and password found in the keystore, using default values.
ndexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-13-219.ec2.internal', 
```

- Expected in performance tests
```
wazuh-analysisd: WARNING: Syscollector decoder queue is full.

```


</details>



<details>

<summary> Indexer 1 :yellow_circle: </summary>

- Opensearch related warning. Expected
```
[2024-07-08T17:09:11,828][WARN ][o.o.g.DanglingIndicesState] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_0] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
``` 

- Known issue https://github.com/wazuh/wazuh-packages/issues/1968
```
org.opensearch.transport.RemoteTransportException: [CLUSTER-Workload_benchmarks_metrics_B569_indexer_1][172.31.15.132:9300][internal:cluster/coordination/join]
Caused by: org.opensearch.cluster.coordination.CoordinationStateRejectedException: incoming term 1 does not match current term 2
	at org.opensearch.cluster.coordination.CoordinationState.handleJoin(CoordinationState.java:269) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.handleJoin(Coordinator.java:1188) ~[opensearch-2.10.0.jar:2.10.0]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.opensearch.cluster.coordination.Coordinator.processJoinRequest(Coordinator.java:657) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.lambda$handleJoinRequest$7(Coordinator.java:620) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) ~[opensearch-core-2.10.0.jar:2.10.0]
	at org.opensearch.transport.ClusterConnectionManager.connectToNode(ClusterConnectionManager.java:138) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TransportService.connectToNode(TransportService.java:493) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.TransportService.connectToNode(TransportService.java:473) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.handleJoinRequest(Coordinator.java:602) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.JoinHelper.lambda$new$1(JoinHelper.java:209) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceivedDecorate(SecuritySSLRequestHandler.java:215) ~[?:?]
	at org.opensearch.security.transport.SecurityRequestHandler.messageReceivedDecorate(SecurityRequestHandler.java:315) ~[?:?]
	at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceived(SecuritySSLRequestHandler.java:163) ~[?:?]
	at org.opensearch.security.OpenSearchSecurityPlugin$7$1.messageReceived(OpenSearchSecurityPlugin.java:763) ~[?:?]
	at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:113) ~[?:?]
	at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) ~[?:?]
	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:454) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.10.0.jar:2.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

```

- Opensearch related warning. Expected
```
[2024-07-08T17:09:15,193][WARN ][o.o.p.c.s.h.ConfigOverridesClusterSettingHandler] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_0] Config override setting update called with empty string. Ignoring.
``` 
 

- Opensearch related error. Expected
```
[2024-07-08T17:09:16,228][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_0] Failure no such index [.opendistro_security] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
``` 


</details>


<details>

<summary> Indexer 2 :yellow_circle: </summary>


- Known issue https://github.com/wazuh/wazuh-packages/issues/1968
```
org.opensearch.transport.RemoteTransportException: [CLUSTER-Workload_benchmarks_metrics_B569_indexer_1][172.31.15.132:9300][internal:cluster/coordination/join]
Caused by: org.opensearch.cluster.coordination.CoordinationStateRejectedException: became follower
	at org.opensearch.cluster.coordination.JoinHelper$CandidateJoinAccumulator.lambda$close$3(JoinHelper.java:649) [opensearch-2.10.0.jar:2.10.0]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) [?:?]
	at org.opensearch.cluster.coordination.JoinHelper$CandidateJoinAccumulator.close(JoinHelper.java:649) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.becomeFollower(Coordinator.java:755) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.Coordinator.onFollowerCheckRequest(Coordinator.java:354) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.cluster.coordination.FollowersChecker$2.doRun(FollowersChecker.java:228) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.10.0.jar:2.10.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.10.0.jar:2.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```


- Opensearch related error. Expected
```
[2024-07-08T17:09:15,198][WARN ][o.o.p.c.s.h.ConfigOverridesClusterSettingHandler] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1] Config override setting update called with empty string. Ignoring.
```

- Opensearch related error. Expected
```
[2024-07-08T17:09:15,927][WARN ][o.o.o.i.ObservabilityIndex] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1] message: index [.opensearch-observability/PI7PqE2bSNWP0rT_oCPRvw] already exists
``` 

- Opensearch related error. Expected
``` 
[2024-07-08T17:09:16,162][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1] Failure no such index [.opendistro_security] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
``` 

- Opensearch related error. Expected
```
[2024-07-08T17:09:12,824][WARN ][o.o.s.p.SQLPlugin        ] [CLUSTER-Workload_benchmarks_metrics_B566_indexer_1] Master key is a required config for using create and update datasource APIs. Please set plugins.query.datasources.encryption.masterkey config in opensearch.yml in all the cluster nodes. More details can be found here: https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/datasources.rst#master-key-config-for-encrypting-credential-information
```


</details>


<details>

<summary> Dashboard :green_circle:  </summary>

No unexpected warnings/errors

</details>


<details>

<summary> Tools :green_circle: </summary>

No unexpected warnings/errors

</details>




***


## Metrics :green_circle: 
 
**Summary**

<details>

<summary> Master :red_circle:  </summary>

There are significant discrepancies in CPU and memory usage. It appears to be related to a data collection process. Upon closer examination, the pattern does not align, suggesting that the metrics gathering in version 4.8.0 did not function as expected. We should disregard the CPU usage from certain modules at the beginning.


</details>

<details>

<summary> Worker 1 :red_circle: </summary>

Duplicated usage of memory and file descriptors

</details>


<details>

<summary> Worker 2 :red_circle: </summary>

Duplicated usage of memory and file descriptors

</details>



<details>

<summary> Indexer 1 :green_circle:  </summary>

No abnormal behavior

</details>


<details>

<summary> Indexer 2 :green_circle: </summary>

No abnormal behavior



</details>


<details>

<summary> Dashboard :green_circle:  </summary>

No abnormal behavior

</details>


## Statistics :green_circle:

**Summary**

<details>

<summary> Master :green_circle:  </summary>

No abnormal behavior was detected. 

</details>

<details>

<summary> Worker 1 :green_circle: </summary>

No abnormal behavior was detected. 

</details>


<details>

<summary> Worker 2 :green_circle: </summary>


No abnormal behavior was detected. 

</details>


## Vulnerabilities State :green_circle:

No abnormal behavior was detected. 
![wazuh-vulnerabilities_api_stats_Total Vulnerabilities](https://github.com/wazuh/wazuh/assets/11089305/2b708b6b-4ff0-4d6c-8b19-c434cb7b01f3)

## Alerts :green_circle:
 
No abnormal behavior was detected.    
 
![wazuh-alerts_api_stats_Different alerts](https://github.com/wazuh/wazuh/assets/11089305/d28da5d6-ccea-4a81-81ec-c3551a306fde)
![wazuh-alerts_api_stats_Total alerts](https://github.com/wazuh/wazuh/assets/11089305/c5cd8e87-3ea6-4e08-b64d-ef18910fe954)

**Comment by rafabailon** [comment]
### LGTM
