### ISSUE TITLE
Security Hub 

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#24945]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-alpha3 | AWS Security Hub Integration | Agent | - | - |

## Description

During the E2E testing on 2.9.0-Alpha3 test of [AWS Security Hub integration](https://github.com/wazuh/wazuh/issues/24864), the following configuration was applied to a Wazuh Agent on a Debian 12 to retrieve events from the AWS queue:

<details><summary>/root/.aws/credentials file</summary>

```console
[default]
aws_access_key_id=XXXXXX
aws_secret_access_key=YYYYYYY
region=us-east-1
```

</details>

<details><summary>ossec.conf</summary>
```console
<wodle name="aws-s3">
      <disabled>no</disabled>
      <interval>5m</interval>
      <run_on_start>yes</run_on_start>
      <subscriber type="security_hub">
          <sqs_name>security-hub-rules-testing</sqs_name>
          <aws_profile>default</aws_profile>
      </subscriber>
  </wodle>
```console



```
The following error is present in the ossec.log file:

<details></summary>
```console
2024/07/26 00:48:10 wazuh-modulesd:aws-s3[8019] wmodules-aws.c:522 at wm_aws_read(): DEBUG: Found a subscriber tag
2024/07/26 00:48:10 wazuh-modulesd:aws-s3[8019] wmodules-aws.c:538 at wm_aws_read(): DEBUG: Creating first subscriber structure
2024/07/26 00:48:10 wazuh-modulesd:aws-s3[8019] wmodules-aws.c:566 at wm_aws_read(): DEBUG: Loop through child nodes
2024/07/26 00:48:10 wazuh-modulesd:aws-s3[8019] wmodules-aws.c:569 at wm_aws_read(): DEBUG: Parse child node: sqs_name
2024/07/26 00:48:10 wazuh-modulesd:aws-s3[8019] wmodules-aws.c:569 at wm_aws_read(): DEBUG: Parse child node: aws_profile
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wmodules-aws.c:522 at wm_aws_read(): DEBUG: Found a subscriber tag
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wmodules-aws.c:538 at wm_aws_read(): DEBUG: Creating first subscriber structure
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wmodules-aws.c:566 at wm_aws_read(): DEBUG: Loop through child nodes
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wmodules-aws.c:569 at wm_aws_read(): DEBUG: Parse child node: sqs_name
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wmodules-aws.c:569 at wm_aws_read(): DEBUG: Parse child node: aws_profile
2024/07/26 00:48:14 wazuh-modulesd[8119] main.c:95 at main(): DEBUG: Created new thread for the 'aws-s3' module.
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:62 at wm_aws_main(): INFO: Module AWS started
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:84 at wm_aws_main(): INFO: Starting fetching of logs.
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:196 at wm_aws_main(): INFO: Executing Subscriber fetch: (Type and SQS: security_hub security-hub-rules-testing)
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:727 at wm_aws_run_subscriber(): DEBUG: Create argument list
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:806 at wm_aws_run_subscriber(): DEBUG: Launching S3 Subscriber Command: wodles/aws/aws-s3 --subscriber security_hub --queue security-hub-rules-testing --aws_profile default --debug 2
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:821 at wm_aws_run_subscriber(): WARNING: Subscriber: security_hub security-hub-rules-testing  -  Returned exit code 1
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:825 at wm_aws_run_subscriber(): WARNING: Subscriber: security_hub security-hub-rules-testing  -  Unknown error.
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:845 at wm_aws_run_subscriber(): DEBUG: Subscriber: security_hub security-hub-rules-testing  -  OUTPUT: Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3", line 38, in <module>
  File "/var/ossec/wodles/aws/buckets_s3/__init__.py", line 5, in <module>
    from buckets_s3 import aws_bucket
  File "/var/ossec/wodles/aws/buckets_s3/aws_bucket.py", line 7, in <module>
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:201 at wm_aws_main(): INFO: Fetching logs finished.
2024/07/26 00:48:14 wazuh-modulesd:aws-s3[8119] wm_aws.c:80 at wm_aws_main(): DEBUG: Sleeping until: 2024/07/26 00:53:14
```
</details>

The same account and configuration were used in a Wazuh Manager, and the manager was able to retrieve events from the queue.

**Comment by ncvicchi** [comment]
There were prerequisited not installed.
