### ISSUE TITLE
Wazuh API not listening to IPV6 connections

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh#24981]
|Wazuh version|Component|
|---|---|
| 4.8.0 | Wazuh API |

## Description

Hi team, I made some tests trying to connect to Wazuh API using IPV6 and it seems the API is not listening to IPV6 connections.

### Evidence

Connections made with telnet to IPV4 are listened to, but when using IPV6 they're not.

```

error: 2024/07/31 10:5:59: wazuh-api:makeRequest: connect ECONNREFUSED ::1:55000
info: 2024/07/31 10:10:0: Cron-scheduler: {"message":"connect ECONNREFUSED ::1:55000","stack":"Error: connect ECONNREFUSED ::1:55000\n    at Function.AxiosError.from (/usr/share/wazuh-dashboard/plugins/wazuh/node_modules/axios/lib/core/AxiosError.js:89:14)\n    at RedirectableRequest.handleRequestError (/usr/share/wazuh-dashboard/plugins/wazuh/node_modules/axios/lib/adapters/http.js:606:25)\n    at RedirectableRequest.emit (node:events:513:28)\n    at RedirectableRequest.emit (node:domain:489:12)\n    at ClientRequest.eventHandlers.<computed> (/usr/share/wazuh-dashboard/plugins/wazuh/node_modules/follow-redirects/index.js:14:24)\n    at ClientRequest.emit (node:events:513:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"url":"https://ip6-localhost:55000/manager/stats/remoted","method":"get","data":"{}","params":{}}}
info: 2024/07/31 10:10:0: Cron-scheduler: {"message":"connect ECONNREFUSED ::1:55000","stack":"Error: connect ECONNREFUSED ::1:55000\n    at Function.AxiosError.from (/usr/share/wazuh-dashboard/plugins/wazuh/node_modules/axios/lib/core/AxiosError.js:89:14)\n    at RedirectableRequest.handleRequestError (/usr/share/wazuh-dashboard/plugins/wazuh/node_modules/axios/lib/adapters/http.js:606:25)\n    at RedirectableRequest.emit (node:events:513:28)\n    at RedirectableRequest.emit (node:domain:489:12)\n    at ClientRequest.eventHandlers.<computed> (/usr/share/wazuh-dashboard/plugins/wazuh/node_modules/follow-redirects/index.js:14:24)\n    at ClientRequest.emit (node:events:513:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"url":"https://ip6-localhost:55000/manager/stats/analysisd","method":"get","data":"{}","params":{}}}
root@ubuntu-jammy:/home/vagrant# telnet
telnet> ^C
root@ubuntu-jammy:/home/vagrant# telnet localhost 55000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^CConnection closed by foreign host.
root@ubuntu-jammy:/home/vagrant# telnet 127.0.0.1 55000
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
^CConnection closed by foreign host.
root@ubuntu-jammy:/home/vagrant# telnet ::1 55000
Trying ::1...
telnet: Unable to connect to remote host: Connection refused
root@ubuntu-jammy:/home/vagrant# telnet ip6-localhost 55000
Trying ::1...
telnet: Unable to connect to remote host: Connection refused

```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by nico-stefani** [comment]
Maybe this https://github.com/encode/uvicorn/discussions/1529 helps

**Comment by nico-stefani** [comment]
# Update

At a glance, the API is listening for IPV4 and IPV6 when we tried with curl

* v4
```
curl -k -H  "Authorization: Bearer $TOKEN" https://127.0.0.1:55050/
{"data": {"title": "Wazuh API REST", "api_version": "4.9.1", "revision": 40910, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/v4.9.1/LICENSE", "hostname": "wazuh-master", "timestamp": "2024-08-13T16:44:47Z"}, "error": 0}
```

* v6

```
curl -k -H  "Authorization: Bearer $TOKEN" 'https://[::1]:55050/'
{"data": {"title": "Wazuh API REST", "api_version": "4.9.1", "revision": 40910, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/v4.9.1/LICENSE", "hostname": "wazuh-master", "timestamp": "2024-08-13T16:45:55Z"}, "error": 0}
```

* API Logs
```console
root@wazuh-master:/var/ossec# wpy api/scripts/wazuh_apid.py -f -r
2024/08/13 16:45:36 INFO: Starting API in foreground
2024/08/13 16:45:36 INFO: Starting API as root
2024/08/13 16:45:36 INFO: Checking RBAC database integrity...
2024/08/13 16:45:36 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/08/13 16:45:36 INFO: RBAC database integrity check finished successfully
2024/08/13 16:45:39 INFO: Listening on 0.0.0.0:55000.
2024/08/13 16:45:39 INFO: Getting installation UID...
2024/08/13 16:45:39 INFO: Getting updates information...
2024/08/13 16:45:50 INFO: wazuh 172.18.0.1 "GET /" with parameters {} and body {} done in 2.345s: 200
2024/08/13 16:45:55 INFO: wazuh 172.18.0.1 "GET /" with parameters {} and body {} done in 0.011s: 200
```

**Comment by nico-stefani** [comment]
# Update

I've been able to reproduce the problem executing the command within the container running the API.

```console
root@wazuh-master:/# telnet -6 ::1 55000
Trying ::1...
telnet: Unable to connect to remote host: Connection refused
```

```console
root@wazuh-master:/# curl -k -H  "Authorization: Bearer $TOKEN" 'https://[::1]:55000/'
curl: (7) Failed to connect to ::1 port 55000 after 0 ms: Connection refused
```

After enabling the double stack the connections can be made.

```console
root@wazuh-master:/# telnet -6 ::1 55000
Trying ::1...
Connected to ::1.
Escape character is '^]'.
```

```console
root@wazuh-master:/# curl -k -H  "Authorization: Bearer $TOKEN" 'https://[::1]:55000/'
{"data": {"title": "Wazuh API REST", "api_version": "4.9.1", "revision": 40910, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/v4.9.1/LICENSE", "hostname": "wazuh-master", "timestamp": "2024-08-14T12:27:28Z"}, "error": 0}
```

```console
root@wazuh-master:/# curl -k -H  "Authorization: Bearer $TOKEN" https://127.0.0.1:55000/
{"data": {"title": "Wazuh API REST", "api_version": "4.9.1", "revision": 40910, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/v4.9.1/LICENSE", "hostname": "wazuh-master", "timestamp": "2024-08-14T12:28:02Z"}, "error": 0}
```

<details><summary>API Logs</summary>
<p>

```console
root@wazuh-master:/var/ossec# wpy api/scripts/wazuh_apid.py -f -r
2024/08/14 12:27:04 INFO: Starting API in foreground
2024/08/14 12:27:04 INFO: Starting API as root
2024/08/14 12:27:04 INFO: Checking RBAC database integrity...
2024/08/14 12:27:04 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/08/14 12:27:04 INFO: RBAC database integrity check finished successfully
2024/08/14 12:27:07 INFO: Listening on ['0.0.0.0', '::']:55000.
2024/08/14 12:27:07 INFO: Getting installation UID...
2024/08/14 12:27:07 INFO: Getting updates information...
2024/08/14 12:27:22 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.269s: 200
2024/08/14 12:27:28 INFO: wazuh ::1 "GET /" with parameters {} and body {} done in 2.293s: 200
2024/08/14 12:28:02 INFO: wazuh 127.0.0.1 "GET /" with parameters {} and body {} done in 0.010s: 200
```
</p>
</details>

**Comment by nico-stefani** [comment]
# Update

I've been fixing and debugging IT's and AIT's. I've opened https://github.com/wazuh/qa-integration-framework/pull/222 for a small change.
