### ISSUE TITLE
Cluster v3.9.0 revision

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#2522]
After testing the new cluster (https://github.com/wazuh/wazuh/issues/2520) I found some issues:

### Bug 1
The health check shows 1 node more than the current nodes:
![image](https://user-images.githubusercontent.com/1523318/52228069-adb2a800-28b1-11e9-9c8d-a5aaf3f65577.png)

### Bug 2

If there is a bad line in the client.keys of a worker, the client.key will not be updated.

![image](https://user-images.githubusercontent.com/1523318/52228212-100ba880-28b2-11e9-9da3-2fa5de911bb0.png)

![image](https://user-images.githubusercontent.com/1523318/52228224-169a2000-28b2-11e9-8814-b8e06a6938a5.png)

If there is a non-recoverable error (an error that is not fixed in the next sychronization round), the cluster must update the client.keys always.

Another example: Removing the client.keys file.

![image](https://user-images.githubusercontent.com/1523318/52228346-70024f00-28b2-11e9-958e-7948cb5780a7.png)

### Bug 3
The worker closes the session unexpectedly.

Test:
1. worker: connected and working properly.
2. worker: cp client.keys client.keys.backup.
3. worker: rm client.keys.
4. worker: wait a few sync rounds.
5. worker: cp client.keys.backup client.keys

```
2019-02-04 18:14:57,054 ERROR   : [Worker worker-1] [Main           ] Error processing missing file '/etc/client.keys': [Errno 2] No such file or directory: '/var/ossec/etc/client.keys'
2019-02-04 18:14:57,054 ERROR   : [Worker worker-1] [Main           ] Found errors: 0 overwriting, 1 creating and 0 removing
2019-02-04 18:14:57,054 INFO    : [Worker worker-1] [Main           ] Updating files: End.
2019-02-04 18:15:16,915 INFO    : [Worker worker-1] [Keep Alive     ] b'Sucessful response from master: keepalive'
2019-02-04 18:15:16,921 INFO    : [Worker worker-1] [Agent info     ] Starting to send agent status files
2019-02-04 18:15:16,923 INFO    : [Worker worker-1] [Agent info     ] Permission to synchronize granted.
2019-02-04 18:15:16,924 INFO    : [Worker worker-1] [Agent info     ] Compressing files
2019-02-04 18:15:16,926 INFO    : [Worker worker-1] [Agent info     ] Sending compressed file to master
2019-02-04 18:15:16,930 INFO    : [Worker worker-1] [Agent info     ] Worker files sent to master.
2019-02-04 18:15:17,055 INFO    : [Worker worker-1] [Main           ] The server closed the connection
```

### Improvements 1
Improve logs:
- Review usage of master / worker / client / none. Avoid client and none.
- DAPI call logs: Limit information.
- Some logs start with `b'`
- Show in a log the number of removed agents.

### Improvements 2
We should reduce some default values in the cluster.json file due to the good performance of this cluster.
```
    "intervals":{
        "worker": {
            "sync_integrity": 20,
            "sync_files": 60,
            "keep_alive": 60,
            "connection_retry": 10,
            "ask_for_permission": 5,
            "max_failed_keepalive_attempts": 2
        },

        "master": {
            "recalculate_integrity": 15,
            "check_worker_lastkeepalive": 60,
            "max_allowed_time_without_keepalive": 120
        },
```

**Comment by jesuslinares** [comment]
Pending improvements:

@BraulioV:
- [ ] Python path: /var/ossec/framework/python
- [ ] Wrappers: The path must be relative to the script location.
- [ ] Wrapper for wodles/pulgins:
  - agents: Python script
  - manager: wrapper
- [ ] Update documentation

**Comment by mgmacias95** [comment]
Hello @jesuslinares,

Thank you so much for all this feedback 😄! Let me address it one by one.

### Bug 1
It was counting the master too, in purpose:
https://github.com/wazuh/wazuh/blob/e5b11c095beb560907f8dcdb2ef3acca8fc02fca/framework/wazuh/cluster/master.py#L452
This fix is just to remove that `+ 1` part. 
Fixed in 211dc5b51a6b140ca11cb8fdd4c246b58b033278.

### Bug 2
The worker was analyzing the received client.keys in order to remove agent files from agents removed in master node. The worker always expected the client.keys to be correct.
Fixed in 8c391fd3ec78df5fbc073561de2be6715c213d07.

Also, the client.keys was always expected to exist and have correct permissions. That made the cluster unable to update it if it was removed. Fixed in 0597c3ba415b9a638e7c768dc1f1c57da7d09ae6.

### Bug 3
I haven't been able to find the root of this bug. I have tried executing the cluster in foreground and that worked:
```
2019-02-05 17:12:04,655 DEBUG2  : [Worker worker-1] [Main           ] Processing file /etc/client.keys
2019-02-05 17:12:04,656 ERROR   : [Worker worker-1] [Main           ] Error processing missing file '/etc/client.keys': [Errno 2] No such file or directory: '/var/ossec/etc/client.keys'
Traceback (most recent call last):
  File "/var/ossec/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/worker.py", line 196, in update_master_files_in_worker
    overwrite_or_create_files(filename, data)
  File "/var/ossec/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/worker.py", line 181, in overwrite_or_create_files
    tmp_dir=tmp_path, whoami='worker')
  File "/var/ossec/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/cluster.py", line 299, in _update_file
    _check_removed_agents(new_content.decode().split('\n'))
  File "/var/ossec/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/cluster.py", line 501, in _check_removed_agents
    with open("{0}/etc/client.keys".format(common.ossec_path)) as ck:
FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/etc/client.keys'
2019-02-05 17:12:04,658 DEBUG   : [Worker worker-1] [Main           ] Received 0 shared files to update from master.
2019-02-05 17:12:04,658 ERROR   : [Worker worker-1] [Main           ] Found errors: 0 overwriting, 1 creating and 0 removing
NoneType: None
2019-02-05 17:12:04,658 INFO    : [Worker worker-1] [Main           ] Updating files: End.
2019-02-05 17:12:24,505 DEBUG   : [Local Server   ] [Keep alive     ] Calculating.
2019-02-05 17:12:24,506 DEBUG   : [Local Server   ] [Keep alive     ] Calculated.
2019-02-05 17:12:24,557 INFO    : [Worker worker-1] [Agent info     ] Starting to send agent status files
2019-02-05 17:12:24,559 INFO    : [Worker worker-1] [Keep Alive     ] b'Sucessful response from master: keepalive'
2019-02-05 17:12:24,559 INFO    : [Worker worker-1] [Agent info     ] Permission to synchronize granted.
2019-02-05 17:12:24,559 INFO    : [Worker worker-1] [Agent info     ] Compressing files
2019-02-05 17:12:24,561 INFO    : [Worker worker-1] [Agent info     ] Sending compressed file to master
2019-02-05 17:12:24,566 INFO    : [Worker worker-1] [Agent info     ] Worker files sent to master.
2019-02-05 17:12:24,568 DEBUG2  : [Worker worker-1] [Agent info     ] Time synchronizing agent statuses: 0.011551380157470703 s
2019-02-05 17:12:24,651 INFO    : [Worker worker-1] [Integrity      ] Permission to synchronize granted.
2019-02-05 17:12:24,651 INFO    : [Worker worker-1] [Integrity      ] Compressing files
2019-02-05 17:12:24,655 INFO    : [Worker worker-1] [Integrity      ] Sending compressed file to master
2019-02-05 17:12:24,660 INFO    : [Worker worker-1] [Integrity      ] Worker files sent to master.
2019-02-05 17:12:24,662 DEBUG   : [Worker worker-1] [Integrity      ] Time synchronizing integrity: 0.017168283462524414 s
```

But when it's executied in background it doesn't:
```
2019-02-05 17:14:23,156 DEBUG2  : [Worker worker-1] [Main           ] Processing file /etc/client.keys
2019-02-05 17:14:23,156 ERROR   : [Worker worker-1] [Main           ] Error processing missing file '/etc/client.keys': [Errno 2] No such file or directory: '/var/ossec/etc/client.keys'
Traceback (most recent call last):
  File "/var/ossec/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/worker.py", line 196, in update_master_files_in_worker
    overwrite_or_create_files(filename, data)
  File "/var/ossec/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/worker.py", line 181, in overwrite_or_create_files
    tmp_dir=tmp_path, whoami='worker')
  File "/var/ossec/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/cluster.py", line 299, in _update_file
    _check_removed_agents(new_content.decode().split('\n'))
  File "/var/ossec/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/cluster.py", line 501, in _check_removed_agents
    with open("{0}/etc/client.keys".format(common.ossec_path)) as ck:
FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/etc/client.keys'
2019-02-05 17:14:23,159 DEBUG   : [Worker worker-1] [Main           ] Received 0 shared files to update from master.
2019-02-05 17:14:23,159 ERROR   : [Worker worker-1] [Main           ] Found errors: 0 overwriting, 1 creating and 0 removing
NoneType: None
2019-02-05 17:14:23,159 INFO    : [Worker worker-1] [Main           ] Updating files: End.
2019-02-05 17:14:42,991 DEBUG   : [Local Server   ] [Keep alive     ] Calculating.
2019-02-05 17:14:42,991 DEBUG   : [Local Server   ] [Keep alive     ] Calculated.
2019-02-05 17:14:43,056 INFO    : [Worker worker-1] [Agent info     ] Starting to send agent status files
2019-02-05 17:14:43,058 INFO    : [Worker worker-1] [Keep Alive     ] b'Sucessful response from master: keepalive'
2019-02-05 17:14:43,059 INFO    : [Worker worker-1] [Agent info     ] Permission to synchronize granted.
2019-02-05 17:14:43,059 INFO    : [Worker worker-1] [Agent info     ] Compressing files
2019-02-05 17:14:43,062 INFO    : [Worker worker-1] [Agent info     ] Sending compressed file to master
2019-02-05 17:14:43,067 INFO    : [Worker worker-1] [Agent info     ] Worker files sent to master.
2019-02-05 17:14:43,070 DEBUG2  : [Worker worker-1] [Agent info     ] Time synchronizing agent statuses: 0.0136260986328125 s
2019-02-05 17:14:43,144 INFO    : [Worker worker-1] [Main           ] The server closed the connection
```

I'll keep working to get as much information as possible about this bug so it can be fixed.

### Log improvements
Log improvements have been made in commits 30080daf047990053b1c4f0d3e0cec72b4c50ace, c3b74f0fd8bbfde840eedbc4f969405be38de66d and 7b866af139922079bbe3900620507271797f9657.

* Log message when removing agents in worker nodes
```
2019-02-05 15:44:22,467 INFO    : [Cluster        ] [Main           ] Removing files from 2 agents
2019-02-05 15:44:22,468 INFO    : [Cluster        ] [Main           ] Agents to remove: 002, 001
2019-02-05 15:44:22,698 INFO    : [Cluster        ] [Main           ] Agent files removed
```

* Decoded bytes log messages (this removes `b'` in some log messages):
```
2019-02-05 15:48:42,339 INFO    : [Worker worker-1] [Keep Alive     ] Sucessful response from master: keepalive
```

* DAPI log message showing all details about a request is now showed at debug level:
```
2019-02-05 15:50:01,313 DEBUG   : [Cluster        ] [D API          ] Received request: b'worker-1*864260 {"function": "/cluster/:node_id/status", "arguments": {"node_id": "master", "wait_for_complete": false}, "ossec_path": "/var/ossec", "from_cluster": false}'
2019-02-05 15:50:01,313 INFO    : [Cluster        ] [D API          ] Receiving request: /cluster/:node_id/status
```

* Log message when a worker is disconnected from master:
```
2019-02-05 15:59:46,060 INFO    : [Worker worker-1] [Main           ] Connection lost.
````
```
2019-02-05 15:59:46,060 INFO    : [Worker worker-1] [Main           ] The master closed the connection
```

Best regards,
Marta

**Comment by jesuslinares** [comment]
Bugs found:
- Agents removal is not propagated to worker nodes. Fixed.
- The worker closes the session unexpectedly (bug 3). Fixed.
- Remove unused settings in cluster.json. Fixed.
- Pretty error when using cluster_control and the cluster is disabled. Fixed.
- Remove temporary files. Fixed.
- Race condition when the 2 synchronization processes have the same interval. Fixed.
- Change `Connection lost.` log. Fixed.
- Change `Main` tag for the following kind of logs:
```
2019-02-07 16:59:56,244 WARNING : [Cluster        ] [Main           ] Could not parse client.keys file: [Errno 2] No such file or directory: '/var/ossec/etc/client.keys'
```
- Error propagating a new group. Fixed.
- Improve unhandled exceptions. Fixed.

**Comment by jesuslinares** [comment]
Pending:
- Change `Main` log when there are errors.
- Remove API warning regarding python.
- Run manual tests.

**Comment by jesuslinares** [comment]
Pending:
* Some agent files are not removed.
* Sources installation: make clean-deps doesn't remove pyhon.
* Sources installation: Do not use remote pip. Install the pip packages locally.
* Sources installation: Do not install "tests" file if possible.
* Run manual tests.
* Embedded python for 32 bits (MV/Docker).
* Test upgrades

**Comment by mgmacias95** [comment]
Hello @jesuslinares,

Today I have tested all use cases described in https://github.com/wazuh/wazuh/issues/2520 using `/opt/ossec` debian packages.

I have found several bugs, which have been fixed in the following PRs:
* Logging tags weren't clear in worker nodes. Instead of showing the synchronization process they showed a _main_ tag. Fixed in https://github.com/wazuh/wazuh/pull/2541.
* When there are `agent-info` files with an owner different than `ossec` to be updated, the cluster showed an error in the log when updating the file. Fixed in https://github.com/wazuh/wazuh/pull/2542.
* Some agent related files weren't removed in worker nodes when an agent was removed in the master: https://github.com/wazuh/wazuh/pull/2546.

There is also some bugs I wasn't able to fix:
* When an agent is re-registered (that means, it's removed and registered again) its previous group before being removed isn't remembered.
* It's not possible to filter by multiple values using `,` in `cluster_control` binary:
    ```shellsession
    root@worker-1:/home/vagrant# /opt/ossec/bin/cluster_control -l -fn master,worker-1
    ERROR: Node does not exist
    root@worker-1:/home/vagrant# /opt/ossec/bin/cluster_control -l -fn master worker-1
    NAME      TYPE    VERSION  ADDRESS
    worker-1  worker  3.9.0    172.17.0.101
    master    master  3.9.0    172.17.0.100
    ```
    ```shellsession
    root@worker-1:/home/vagrant/GitHub/wazuh-api# /opt/ossec/bin/cluster_control -i -fn master,worker-1
    Cluster name: wazuh

    Last completed synchronization for connected nodes (0):

    root@worker-1:/home/vagrant/GitHub/wazuh-api# /opt/ossec/bin/cluster_control -i -fn master worker-1
    Cluster name: wazuh

    Last completed synchronization for connected nodes (1):
        worker-1 (172.17.0.101): Integrity: 2019-02-08 11:30:52.822996 | Agents-info: 2019-02-08 11:30:51.865203 | Agent-groups: n/a | Last keep alive: 2019-02-08 11:30:51.570523.
    ```
   But it is possible to filter using `,` in `cluster_control -a`:
    ```shellsession
    root@worker-1:/home/vagrant/GitHub/wazuh-api# /opt/ossec/bin/cluster_control -a -fs Active Pending -fn worker-1
    ID   NAME     IP            STATUS  VERSION       NODE NAME
    000  master   127.0.0.1     Active  Wazuh v3.9.0  master
    002  agent-1  172.17.0.201  Active  Wazuh v3.8.2  master
    003  agent-2  172.17.0.202  Active  Wazuh v3.8.2  worker-1
    root@worker-1:/home/vagrant/GitHub/wazuh-api# /opt/ossec/bin/cluster_control -a -fs Active Pending -fn worker-1,master
    ID   NAME     IP            STATUS  VERSION       NODE NAME
    000  master   127.0.0.1     Active  Wazuh v3.9.0  master
    002  agent-1  172.17.0.201  Active  Wazuh v3.8.2  master
    003  agent-2  172.17.0.202  Active  Wazuh v3.8.2  worker-1
    root@worker-1:/home/vagrant/GitHub/wazuh-api# /opt/ossec/bin/cluster_control -a -fs Active Pending -fn worker-1 master
    ID   NAME     IP            STATUS  VERSION       NODE NAME
    000  master   127.0.0.1     Active  Wazuh v3.9.0  master
    002  agent-1  172.17.0.201  Active  Wazuh v3.8.2  master
    003  agent-2  172.17.0.202  Active  Wazuh v3.8.2  worker-1
    ```

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello @jesuslinares,

I have been testing the cluster in a bigger environment (5 nodes and 805 agents). I have found that:
* Agent groups files are always sent from workers to master, despite group assignments weren't changed:
    ```
    2019-02-11 11:17:06,286 INFO    : [Worker wazuh-cluster-client3] [Integrity      ] Analyzing worker integrity: Received 818 files to check.
    ```
* Trying to synchronize a 1GB file among all workers led to a `No space left` in device state. Removing the big files fixes the issue (the cluster goes back to normal):
    ```
    2019-02-11 11:03:37,968 ERROR   : [Cluster        ] [Main           ] [Cluster] Error 3001 - Error creating zip file: [Errno 28] No space left on device
    2019-02-11 11:03:37,972 ERROR   : [Worker wazuh-cluster-client3] [Main           ] Can't close the ZIP file while there is an open writing handle on it. Close the writing handle before closing the zip.
    2019-02-11 11:04:00,855 INFO    : [Worker wazuh-cluster-client3] [Integrity      ] Waiting to receive zip file from worker
    2019-02-11 11:04:00,861 ERROR   : [Worker wazuh-cluster-client3] [Main           ] Error processing request 'b'new_file'': [Errno 28] No space left on device: '/var/ossec/queue/cluster/wazuh-cluster-client3/wazuh-cluster-client3-1549883040.8528743-9770376333621401.zip'
    2019-02-11 11:04:00,868 ERROR   : [Worker wazuh-cluster-client3] [Main           ] [Errno 13] Permission denied: '/var/ossecErrordir'
    ```
* A `KeyError` exception is raised if there is an error during file reception:
    ```
    2019-02-11 11:33:34,983 DEBUG   : [Worker wazuh-cluster-client2] [Main           ] Command received: b'sync_i_w_m_p'
    2019-02-11 11:33:34,983 DEBUG   : [Worker wazuh-cluster-client2] [Main           ] Command received: b'sync_a_w_m_e'
    2019-02-11 11:33:34,983 ERROR   : [Worker wazuh-cluster-client2] [Main           ] Error processing request 'b'sync_a_w_m_e'': 'Error'
    Traceback (most recent call last):
      File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/common.py", line 381, in dispatch
        command, payload = self.process_request(command, payload)
      File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/master.py", line 97, in process_request
        return self.end_receiving_integrity_checksums(data.decode())
      File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/master.py", line 244, in end_receiving_integrity_checksums
        return super().end_receiving_file(task_and_file_names)
      File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/common.py", line 554, in end_receiving_file
        self.sync_tasks[task_name].filename = common.ossec_path + filename
    KeyError: 'Error'
    ```
* I have been able to use `agent_groups` binary in a worker node even though an exception should be raised:
    ```shellsession
    # /var/ossec/bin/agent_groups -l
    INFO: Deprecated node type 'client'. Using 'worker' instead.
    Groups (2):
      default (804)
      mygr (4)
    Unassigned agents: 0.
    ```

Best regards,
Marta
