### ISSUE TITLE
Wazuh API/wazuh-apid failing to start after 4.8.2 -> 4.9.0 update: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by iasdeoupxe** [wazuh/wazuh#25604]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Wazuh API/wazuh-apid | Manager | Packages | Debian 12.7 |

After updating an existing working Wazuh installation from 4.8.2 to 4.9.0 the start of the Wazuh API/wazuh-apid is failing and the following can be seen in the `/var/ossec/logs/api.log` logs:

```
2024/09/05 20:39:56 INFO: Starting API in foreground
2024/09/05 20:39:56 INFO: Checking RBAC database integrity...
2024/09/05 20:39:56 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/09/05 20:39:56 INFO: RBAC database integrity check finished successfully
2024/09/05 20:39:59 ERROR: [Errno 13] Permission denied
```

for testing purposes i have also tried to start the daemon manually via:

```
# /var/ossec/bin/wazuh-apid -f -d -d
```

giving this:

```
2024/09/05 22:25:31 INFO: Starting API in foreground
2024/09/05 22:25:31 INFO: Checking RBAC database integrity...
2024/09/05 22:25:31 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/09/05 22:25:31 INFO: RBAC database integrity check finished successfully
2024/09/05 22:25:35 ERROR: [Errno 13] Permission denied
Internal error when trying to start the Wazuh API. [Errno 13] Permission denied
```

When starting it as root it seems it is starting successfully:

```
# /var/ossec/bin/wazuh-apid -f -d -d -r
2024/09/05 22:28:58 INFO: Starting API in foreground
2024/09/05 22:28:58 INFO: Starting API as root
2024/09/05 22:28:58 INFO: Checking RBAC database integrity...
2024/09/05 22:28:58 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/09/05 22:28:58 INFO: RBAC database integrity check finished successfully
2024/09/05 22:29:01 INFO: Listening on 0.0.0.0:55000.
2024/09/05 22:29:01 INFO: Getting installation UID...
2024/09/05 22:29:01 INFO: Getting updates information...
```

so this seems to be indeed some kind of permission issue. But it is not clear (due to the lack of into in the Permission denied message) what kind of permission issue this is:

1. Some TLS certificate file / path issue?
2. Some log file / path issue?
3. Port / interface listening issue?
4. Something else?

**Comment by iasdeoupxe** [comment]
Adding the following to `/var/ossec/api/configuration/api.yaml`:

```
logs:
  level: "debug2"
```

and restarting `wazuh-manager` yields this:

```
2024/09/05 22:37:38 ERROR: [Errno 13] Permission denied 
Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh_apid.py", line 234, in start
    uvicorn.run(app, **params)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/var/ossec/framework/python/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/var/ossec/framework/python/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/var/ossec/framework/python/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/var/ossec/framework/python/lib/python3.10/site-packages/uvicorn/config.py", line 430, in load
    self.ssl: Optional[ssl.SSLContext] = create_ssl_context(
  File "/var/ossec/framework/python/lib/python3.10/site-packages/uvicorn/config.py", line 121, in create_ssl_context 
    ctx.load_cert_chain(certfile, keyfile, get_password)
PermissionError: [Errno 13] Permission denied
```

**Comment by iasdeoupxe** [comment]
Is this maybe due to the following usage of the server certs below? Any chances to improve the error message to include the file which has the permission issues?

```
# ls -la /var/ossec/api/configuration/ssl/
total 8
drwxrwx--- 2 root wazuh 4096 Nov  4  2022 .
drwxrwx--- 4 root wazuh 4096 Sep  5 22:41 ..
lrwxrwxrwx 1 root root    50 Nov  4  2022 ca.crt -> /etc/letsencrypt/live/example.com/chain.pem
lrwxrwxrwx 1 root root    54 Nov  4  2022 server.crt -> /etc/letsencrypt/live/example.com/fullchain.pem
lrwxrwxrwx 1 root root    52 Nov  4  2022 server.key -> /etc/letsencrypt/live/example.com/privkey.pem
```

**Comment by freibuis** [comment]
@iasdeoupxe were you able to fix this. I have the exact same issue. same setup same logs same permission issues

**Comment by freibuis** [comment]
I was able to fix my issue by copying the lets encrpt files into the `/var/ossec/api/configuration/ssl` and chown wazuh:wazuh

I used to use symlinks before.. it seems some thing broken in the upgrade from 4.8 -> 4.9


I think this is a bug. we should be able to use a symlink to the letsencrypt live directory and have letseencrypt to restart wazuh-manager 
other wise you will have to have manually setup a post letsencrypt process that stops wazuh, copies the certs chown the files then start the manager again...  this is terrible design

**Comment by iasdeoupxe** [comment]
@freibuis Thanks for posting the possible workaround. Seems i forgot to post mine which is to add the following to `/var/ossec/api/configuration`:

```
drop_privileges: no
```

Note: Seems ugly and and a security risk so only a workaround.

**Comment by Relianco** [comment]
> Is this maybe due to the following usage of the server certs below? Any chances to improve the error message to include the file which has the permission issues?
> 
> ```
> # ls -la /var/ossec/api/configuration/ssl/
> total 8
> drwxrwx--- 2 root wazuh 4096 Nov  4  2022 .
> drwxrwx--- 4 root wazuh 4096 Sep  5 22:41 ..
> lrwxrwxrwx 1 root root    50 Nov  4  2022 ca.crt -> /etc/letsencrypt/live/example.com/chain.pem
> lrwxrwxrwx 1 root root    54 Nov  4  2022 server.crt -> /etc/letsencrypt/live/example.com/fullchain.pem
> lrwxrwxrwx 1 root root    52 Nov  4  2022 server.key -> /etc/letsencrypt/live/example.com/privkey.pem
> ```

Your issue is that the certs are owned by root, while wazuh-api is running as wazuh:wazuh by default (drop_privileges: yes).

One solution would be to add a renew_hook to your [renewalparams] /etc/letsencrypt/renewal/$YOURDOMAIN.conf

renew_hook = /etc/letsencrypt/renewal/waz-cert.sh

Then in waz-cert.sh:
- copy ssl certificates from /etc/letsencrypt/live/$YOURDOMAIN/ to /var/ossec/api/configuration/ssl
- chown -R wazuh:wazuh /var/ossec/api/configuration/ssl
- restart wazuh-manager

**Comment by iasdeoupxe** [comment]
Yes, thanks for posting. I know how to work around this, the main problem is more that the wazuh-api doesn't throw any meaningful info to actually know the reason why the permission error happened (it even didn't included any note on which file).

To solve this at least the error message should be improved / extended so you don't need to spend work on debugging like i had to actually determine the reason of this problem.

**Comment by Relianco** [comment]
> Yes, thanks for posting. I know how to work around this, the main problem is more that the wazuh-api doesn't throw any meaningful info to actually know the reason why the permission error happened (it even didn't included any note on which file).
> 
> To solve this at least the error message should be improved / extended so you don't need to spend work on debugging like i had to actually determine the reason of this problem.

For sure thanks for clarifying. Interestingly enough I found your post in trying to get a LE certificate to work with the API as well, and in my experience, the lack of log information was also an issue. 

It seems the files needed to be owned by wazuh:wazuh, and chmod 440 (in case that helps anyone else).

`fullchain.pem -> /var/ossec/api/configuration/ssl/server.crt`
`privkey.pem -> /var/ossec/api/configuration/ssl/server.key`

In the api.yaml:
```https:
  enabled: yes
  key: "server.key"
  cert: "server.crt"
  use_ca: False
  ca: "ca.crt"
  ssl_protocol: "auto"
  ssl_ciphers: ""
```

I couldn't get TLSv1.3 to work as an ssl cipher in the config file and setting TLSv1.2 seems to disable TLSv1.3 but maybe setting ssl_ciphers would workaround that as well.
