### ISSUE TITLE
Wazuh Indexer Failed to start with error Values less than -1 bytes are not supported: -2696937472b

### ISSUE THREAD

**Issue by bayusky** [wazuh/wazuh#25849]
|Wazuh version|Component|Install type|Install method|Platform|
| 4.7.2-1| indexer | All in one nodes | Assisted Installation | Ubuntu 22.04 | 

Yesterday, suddenly wazuh-indexer is failed to create new index. Then, when I restarted the Indexer, its failed and get Values error.
Here is the wazuh-indexer-cluster.log

```
[2024-09-21T01:58:09,809][INFO ][o.o.n.Node               ] [node-dc] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms6g, -Xmx6g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-6945932947927724226, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/wazuh-indexer, -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=file:///etc/wazuh-indexer/opensearch-performance-analyzer/opensearch_security.policy, --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=file:///usr/share/wazuh-indexer/plugins/opendistro-performance-analyzer/pa_config/es_security.policy, -XX:MaxDirectMemorySize=3221225472, -Dopensearch.path.home=/usr/share/wazuh-indexer, -Dopensearch.path.conf=/etc/wazuh-indexer, -Dopensearch.distribution.type=rpm, -Dopensearch.bundled_jdk=true]
[2024-09-21T01:58:12,351][INFO ][o.o.s.s.t.SSLConfig      ] [node-dc] SSL dual mode is disabled
[2024-09-21T01:58:12,352][INFO ][o.o.s.OpenSearchSecurityPlugin] [node-dc] OpenSearch Config path is /etc/wazuh-indexer
[2024-09-21T01:58:13,119][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node-dc] JVM supports TLSv1.3
[2024-09-21T01:58:13,125][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node-dc] Config directory is /etc/wazuh-indexer/, from there the key- and truststore files are resolved relatively
[2024-09-21T01:58:14,243][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node-dc] TLS Transport Client Provider : JDK
[2024-09-21T01:58:14,244][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node-dc] TLS Transport Server Provider : JDK
[2024-09-21T01:58:14,244][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node-dc] TLS HTTP Provider             : JDK
[2024-09-21T01:58:14,245][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node-dc] Enabled TLS protocols for transport layer : [TLSv1.3, TLSv1.2]
[2024-09-21T01:58:14,245][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node-dc] Enabled TLS protocols for HTTP layer      : [TLSv1.2]
[2024-09-21T01:58:14,261][INFO ][o.o.s.OpenSearchSecurityPlugin] [node-dc] Clustername: wazuh-indexer-cluster
[2024-09-21T01:58:14,273][WARN ][o.o.s.OpenSearchSecurityPlugin] [node-dc] File /etc/wazuh-indexer/opensearch-security/roles.yml has insecure file permissions (should be 0600)
[2024-09-21T01:58:14,274][WARN ][o.o.s.OpenSearchSecurityPlugin] [node-dc] File /etc/wazuh-indexer/opensearch-security/internal_users.yml has insecure file permissions (should be 0600)
[2024-09-21T01:58:14,274][WARN ][o.o.s.OpenSearchSecurityPlugin] [node-dc] File /etc/wazuh-indexer/opensearch-security/roles_mapping.yml has insecure file permissions (should be 0600)
[2024-09-21T01:58:15,775][INFO ][o.o.p.c.c.PluginSettings ] [node-dc] Trying to create directory /dev/shm/performanceanalyzer/.
[2024-09-21T01:58:15,777][INFO ][o.o.p.c.c.PluginSettings ] [node-dc] Config: metricsLocation: /dev/shm/performanceanalyzer/, metricsDeletionInterval: 1, httpsEnabled: false, cleanup-metrics-db-files: true, batch-metrics-retention-period-minutes: 7, rpc-port: 9650, webservice-port 9600
[2024-09-21T01:58:17,416][INFO ][o.o.i.r.ReindexPlugin    ] [node-dc] ReindexPlugin reloadSPI called
[2024-09-21T01:58:17,419][INFO ][o.o.i.r.ReindexPlugin    ] [node-dc] Unable to find any implementation for RemoteReindexExtension
[2024-09-21T01:58:17,526][INFO ][o.o.j.JobSchedulerPlugin ] [node-dc] Loaded scheduler extension: opendistro_anomaly_detector, index: .opendistro-anomaly-detector-jobs
[2024-09-21T01:58:17,631][INFO ][o.o.j.JobSchedulerPlugin ] [node-dc] Loaded scheduler extension: reports-scheduler, index: .opendistro-reports-definitions
[2024-09-21T01:58:17,634][INFO ][o.o.j.JobSchedulerPlugin ] [node-dc] Loaded scheduler extension: opendistro-index-management, index: .opendistro-ism-config
[2024-09-21T01:58:17,729][INFO ][o.o.j.JobSchedulerPlugin ] [node-dc] Loaded scheduler extension: observability, index: .opensearch-observability-job
[2024-09-21T01:58:17,750][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [aggs-matrix-stats]
[2024-09-21T01:58:17,751][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [analysis-common]
[2024-09-21T01:58:17,752][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [geo]
[2024-09-21T01:58:17,753][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [ingest-common]
[2024-09-21T01:58:17,753][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [ingest-geoip]
[2024-09-21T01:58:17,755][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [ingest-user-agent]
[2024-09-21T01:58:17,756][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [lang-expression]
[2024-09-21T01:58:17,757][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [lang-mustache]
[2024-09-21T01:58:17,757][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [lang-painless]
[2024-09-21T01:58:17,758][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [mapper-extras]
[2024-09-21T01:58:17,759][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [opensearch-dashboards]
[2024-09-21T01:58:17,759][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [parent-join]
[2024-09-21T01:58:17,760][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [percolator]
[2024-09-21T01:58:17,760][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [rank-eval]
[2024-09-21T01:58:17,761][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [reindex]
[2024-09-21T01:58:17,762][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [repository-url]
[2024-09-21T01:58:17,763][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [search-pipeline-common]
[2024-09-21T01:58:17,763][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [systemd]
[2024-09-21T01:58:17,764][INFO ][o.o.p.PluginsService     ] [node-dc] loaded module [transport-netty4]
[2024-09-21T01:58:17,765][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-alerting]
[2024-09-21T01:58:17,766][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-anomaly-detection]
[2024-09-21T01:58:17,767][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-asynchronous-search]
[2024-09-21T01:58:17,767][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-cross-cluster-replication]
[2024-09-21T01:58:17,768][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-geospatial]
[2024-09-21T01:58:17,769][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-index-management]
[2024-09-21T01:58:17,769][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-job-scheduler]
[2024-09-21T01:58:17,770][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-knn]
[2024-09-21T01:58:17,771][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-ml]
[2024-09-21T01:58:17,772][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-neural-search]
[2024-09-21T01:58:17,772][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-notifications]
[2024-09-21T01:58:17,773][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-notifications-core]
[2024-09-21T01:58:17,774][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-observability]
[2024-09-21T01:58:17,774][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-performance-analyzer]
[2024-09-21T01:58:17,775][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-reports-scheduler]
[2024-09-21T01:58:17,779][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-security]
[2024-09-21T01:58:17,780][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-security-analytics]
[2024-09-21T01:58:17,780][INFO ][o.o.p.PluginsService     ] [node-dc] loaded plugin [opensearch-sql]
[2024-09-21T01:58:17,924][INFO ][o.o.s.OpenSearchSecurityPlugin] [node-dc] Disabled https compression by default to mitigate BREACH attacks. You can enable it by setting 'http.compression: true' in opensearch.yml
[2024-09-21T01:58:17,937][INFO ][o.o.e.ExtensionsManager  ] [node-dc] ExtensionsManager initialized
[2024-09-21T01:58:18,011][INFO ][o.o.e.NodeEnvironment    ] [node-dc] using [1] data paths, mounts [[/ (/dev/vda1)]], net usable_space [104.7gb], net total_space [494gb], types [ext4]
[2024-09-21T01:58:18,012][INFO ][o.o.e.NodeEnvironment    ] [node-dc] heap size [6gb], compressed ordinary object pointers [true]
[2024-09-21T01:58:19,055][INFO ][o.o.n.Node               ] [node-dc] node name [node-dc], node ID [4ngMWBc3SzKMIefE0rKqgQ], cluster name [wazuh-indexer-cluster], roles [ingest, remote_cluster_client, data, master]
[2024-09-21T01:58:26,174][ERROR][o.o.b.Bootstrap          ] [node-dc] Exception
java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -2696937472b
        at org.opensearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:90) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.knn.index.KNNSettings.parseknnMemoryCircuitBreakerValue(KNNSettings.java:383) ~[?:?]
        at org.opensearch.knn.index.KNNSettings$1.lambda$new$0(KNNSettings.java:240) ~[?:?]
        at org.opensearch.common.settings.Setting.get(Setting.java:479) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.common.settings.Setting.get(Setting.java:473) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.common.settings.Setting.get(Setting.java:619) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.common.settings.AbstractScopedSettings.get(AbstractScopedSettings.java:792) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.knn.index.KNNSettings.getSettingValue(KNNSettings.java:306) ~[?:?]
        at org.opensearch.knn.index.KNNSettings.getCircuitBreakerLimit(KNNSettings.java:355) ~[?:?]
        at org.opensearch.knn.index.memory.NativeMemoryCacheManager.initialize(NativeMemoryCacheManager.java:74) ~[?:?]
        at org.opensearch.knn.index.memory.NativeMemoryCacheManager.<init>(NativeMemoryCacheManager.java:55) ~[?:?]
        at org.opensearch.knn.index.memory.NativeMemoryCacheManager.getInstance(NativeMemoryCacheManager.java:65) ~[?:?]
        at org.opensearch.knn.index.KNNCircuitBreaker.initialize(KNNCircuitBreaker.java:58) ~[?:?]
        at org.opensearch.knn.plugin.KNNPlugin.createComponents(KNNPlugin.java:200) ~[?:?]
        at org.opensearch.node.Node.lambda$new$16(Node.java:778) ~[opensearch-2.8.0.jar:2.8.0]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at org.opensearch.node.Node.<init>(Node.java:792) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:381) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) [opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) [opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) [opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) [opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) [opensearch-cli-2.8.0.jar:2.8.0]
        at org.opensearch.cli.Command.main(Command.java:101) [opensearch-cli-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) [opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) [opensearch-2.8.0.jar:2.8.0]
[2024-09-21T01:58:26,186][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [node-dc] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -2696937472b
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.8.0.jar:2.8.0]
        at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.8.0.jar:2.8.0]
Caused by: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -2696937472b
        at org.opensearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:90) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.knn.index.KNNSettings.parseknnMemoryCircuitBreakerValue(KNNSettings.java:383) ~[?:?]
        at org.opensearch.knn.index.KNNSettings$1.lambda$new$0(KNNSettings.java:240) ~[?:?]
        at org.opensearch.common.settings.Setting.get(Setting.java:479) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.common.settings.Setting.get(Setting.java:473) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.common.settings.Setting.get(Setting.java:619) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.common.settings.AbstractScopedSettings.get(AbstractScopedSettings.java:792) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.knn.index.KNNSettings.getSettingValue(KNNSettings.java:306) ~[?:?]
        at org.opensearch.knn.index.KNNSettings.getCircuitBreakerLimit(KNNSettings.java:355) ~[?:?]
        at org.opensearch.knn.index.memory.NativeMemoryCacheManager.initialize(NativeMemoryCacheManager.java:74) ~[?:?]
        at org.opensearch.knn.index.memory.NativeMemoryCacheManager.<init>(NativeMemoryCacheManager.java:55) ~[?:?]
        at org.opensearch.knn.index.memory.NativeMemoryCacheManager.getInstance(NativeMemoryCacheManager.java:65) ~[?:?]
        at org.opensearch.knn.index.KNNCircuitBreaker.initialize(KNNCircuitBreaker.java:58) ~[?:?]
        at org.opensearch.knn.plugin.KNNPlugin.createComponents(KNNPlugin.java:200) ~[?:?]
        at org.opensearch.node.Node.lambda$new$16(Node.java:778) ~[opensearch-2.8.0.jar:2.8.0]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at org.opensearch.node.Node.<init>(Node.java:792) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:381) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.8.0.jar:2.8.0]
        ... 6 more
```

What I want to Highlight is this error
```
[2024-09-21T01:58:18,011][INFO ][o.o.e.NodeEnvironment    ] [node-dc] using [1] data paths, mounts [[/ (/dev/vda1)]], net usable_space [104.7gb], net total_space [494gb], types [ext4]
[2024-09-21T01:58:18,012][INFO ][o.o.e.NodeEnvironment    ] [node-dc] heap size [6gb], compressed ordinary object pointers [true]
[2024-09-21T01:58:19,055][INFO ][o.o.n.Node               ] [node-dc] node name [node-dc], node ID [4ngMWBc3SzKMIefE0rKqgQ], cluster name [wazuh-indexer-cluster], roles [ingest, remote_cluster_client, data, master]
[2024-09-21T01:58:26,174][ERROR][o.o.b.Bootstrap          ] [node-dc] Exception
java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -2696937472b
        at org.opensearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:90) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.knn.index.KNNSettings.parseknnMemoryCircuitBreakerValue(KNNSettings.java:383) ~[?:?]
        at org.opensearch.knn.index.KNNSettings$1.lambda$new$0(KNNSettings.java:240) ~[?:?]
```

Values less than -1 bytes

Here is my jvm options
![image](https://github.com/user-attachments/assets/fa5f5165-1131-4e56-9eea-af963cd470c4)

My resources
![image](https://github.com/user-attachments/assets/ccad17a3-29ca-4631-8e5a-5647f77c1a15)

**Comment by bayusky** [comment]
Nevermind, already solved. Wazuh indexer got Memorylimit by systemd, so it's only see 1GB of RAM. And when I add more JVM heap, larger negative numbers too. The solution is, I add line MemoryMax to wazuh-indexer.service on systemd, do daemon-reload, and it's active again. Here's the configuration

![image](https://github.com/user-attachments/assets/11e3aef5-9d49-4fe3-a772-7d275dec5892)
