### ISSUE TITLE
MemoryError in agent_upgrade when using big values for --chunk_size parameter

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#2589]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.x | Manager | Packages/Sources | any |

Hi team,

if you run `agent_upgrade` using big values for `--chunk_size`, the process fails with no error. If you run it again enabling debug mode, a `MemoryError` appears, which looks an unhandled exception. Here you can see the logs:

```
[root@fedora28 vagrant]# /var/ossec/bin/agent_upgrade -a 002 -v v3.8.1 -F -c 4456194594
Internal error:
[root@fedora28 vagrant]# /var/ossec/bin/agent_upgrade -a 002 -v v3.8.1 -F -c 4456194594 -d
Manager version: v3.8.2
Agent version: v3.8.2
Agent new version: v3.8.1
WPK file already downloaded: /var/ossec/var/upgrade/wazuh_agent_v3.8.1_linux_x86_64.wpk - SHA1SUM: 54c55d50f9d88df937fb2b40a4eeec17cbc6ce24
Upgrade PKG: wazuh_agent_v3.8.1_linux_x86_64.wpk (17008 KB)
MSG SENT: 002 com open wb wazuh_agent_v3.8.1_linux_x86_64.wpk
RESPONSE: ok
MSG SENT: 002 com lock_restart -1
RESPONSE: ok
Chunk size: 4456194594 bytes
Sending: /var/ossec/var/upgrade/wazuh_agent_v3.8.1_linux_x86_64.wpk
Internal error:
Traceback (most recent call last):
  File "/var/ossec/bin/agent_upgrade", line 166, in <module>
    main()
  File "/var/ossec/bin/agent_upgrade", line 120, in main
    rl_timeout=-1 if args.timeout == None else args.timeout, use_http=use_http)
  File "/var/ossec/bin/../framework/wazuh/agent.py", line 2215, in upgrade
    show_progress=show_progress, chunk_size=chunk_size, rl_timeout=rl_timeout, use_http=use_http)
  File "/var/ossec/bin/../framework/wazuh/agent.py", line 2137, in _send_wpk_file
    bytes_read = file.read(chunk_size)
MemoryError
[root@fedora28 vagrant]# cat /etc/ossec-init.conf
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.8.2"
REVISION="3814"
DATE="Wed Jan 30 12:15:49 UTC 2019"
TYPE="server"
[root@fedora28 vagrant]#
 ```

In addition, it seems that you can introduce any value to this parameter.

Best regards,
Braulio.

**Comment by BraulioV** [comment]
Hi again,

there's another problem related with this issue. A big chunk_size can also produce an error in https://github.com/wazuh/wazuh/blob/317e61e1bf5a39988e8c58517bce2e52b6b121d8/src/shared/request_op.c#L24 trying to allocate memory:
```shellsession
2019/02/13 08:30:22 ossec-remoted: CRITICAL: (1102): Could not acquire memory due to [(12)-(Cannot allocate memory)].
```
This error completely shuts down `ossec-remoted`.

Regards.

**Comment by BraulioV** [comment]
Hi,

this issue was fixed in https://github.com/wazuh/wazuh/pull/2594.

Best regards.
