### ISSUE TITLE
wazuh-modulesd segfault 4.9.0 Debian 12

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25897]
## Description

A user through a community channel reports a segfault in wazuh-modulesd 4.9.0.

```
wazuh-modulesd[2292497]: segfault at 0 ip 00007f93df47872b sp 00007f93a2df4b20 error 4 in libjemalloc.so.2[7f93df400000+8c000] likely on CPU 5 (core 5, socket 0)
Code: ff 00 4d 89 fe 4c 8b ad 38 fe ff ff 48 81 c2 40 0e 00 00 48 89 95 10 fe ff ff 0f 1f 44 00 00 49 8b 5d 00 48 8d 35 95 95 21 00 <44> 8b 3b 41 81 e7 ff 0f 00 00 44 89 bd 28 fe ff ff 45 89 fc 4e 8b
wazuh-modulesd[2301306]: segfault at 0 ip 00007f0a02e53e63 sp 00007f09c85e0260 error 4 in libjemalloc.so.2[7f0a02e00000+8c000] likely on CPU 0 (core 0, socket 0)
Code: 53 21 fc ff 48 83 c4 18 c3 0f 1f 40 00 66 2e 0f 1f 84 00 00 00 00 00 41 57 41 56 41 55 49 89 f5 41 54 55 48 89 fd 48 83 ec 10 <48> 8b 06 48 8d 15 53 de 23 00 25 ff 0f 00 00 4c 8b 24 c2 48 8d 35

```

## DoD
- [x] RCA
- [x] Fix issue
- [x] Add tests

**Comment by Dwordcito** [comment]
The user in his environment specifies that he has some errors related to databases, like this:

```
2024/09/24 06:41:09 wazuh-modulesd:vulnerability-scanner: ERROR: Error updating feed: [json.exception.out_of_range.401] array index 17 is out of range, trying to re-download the feed.
```

This happens when an update is stopped forcibly or because of https://github.com/wazuh/wazuh/issues/24967

It also indicates that the update is slow(more than one hour) when processing the offline feed (in GitHub Actions environments this takes 20 minutes), but well it depends on the user's infrastructure, This may cause the issue described in: https://github.com/wazuh/wazuh/issues/24967


```
[Tue Sep 24 09:17:00 2024] wazuh-modulesd[2418005]: segfault at 0 ip 00007fc883db75d3 sp 00007fc84dbdade0 error 4 in libvulnerability_scanner.so[7fc883800000+74d000] likely on CPU 8 (core 8, socket 0) 
```

**Comment by Dwordcito** [comment]
The user shared log information with us, which are not conclusive, he informs us that the problem seems to be in shutdown(which makes it less severe.), anyway we gave him a package that contains the debug symbols, and we gave him the guide to generate a coredump in debian so that this file is passed to us and we can reach the log line with the problem.

**Comment by Dwordcito** [comment]
The deployment by the user will be carried out by the user on Monday, therefore he will send us this that day to be able to process the RCA.

**Comment by Dwordcito** [comment]
We were able to get the coredump with the problem that caused it and it is a race condition.

Basically in an LRU cache, a RW Lock was being used, which was in R, when there were operations that modified an STL container, this caused access to be broken between different consumers of the LRU cache.

```
#0  0x00007f7363853e63 in ?? () from /var/ossec/bin/../lib/libjemalloc.so.2
#1  0x00007f736380edcd in ?? () from /var/ossec/bin/../lib/libjemalloc.so.2
#2  0x00007f735a1bd38c in __gnu_cxx::new_allocator<std::_List_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::deallocate (
    this=0x7f735a574798 <Singleton<OsDataCache<SocketDBWrapper> >::instance()::s_instance+56>, __p=0x7f733142eb60) at /usr/local/gcc-9.4.0/include/c++/9.4.0/ext/new_allocator.h:128
#3  0x00007f735a1b6670 in std::allocator_traits<std::allocator<std::_List_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::deallocate (
    __a=..., __p=0x7f733142eb60, __n=1) at /usr/local/gcc-9.4.0/include/c++/9.4.0/bits/alloc_traits.h:469
#4  0x00007f735a1b0c90 in std::__cxx11::_List_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_put_node (this=0x7f735a574798 <Singleton<OsDataCache<SocketDBWrapper> >::instance()::s_instance+56>, __p=0x7f733142eb60)
    at /usr/local/gcc-9.4.0/include/c++/9.4.0/bits/stl_list.h:442
#5  0x00007f735a1b1417 in std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_erase (this=0x7f735a574798 <Singleton<OsDataCache<SocketDBWrapper> >::instance()::s_instance+56>, __position=...)
    at /usr/local/gcc-9.4.0/include/c++/9.4.0/bits/stl_list.h:1926
#6  0x00007f735a1b1d1a in std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::remove (this=0x7f735a574798 <Singleton<OsDataCache<SocketDBWrapper> >::instance()::s_instance+56>, __value=...)
    at /usr/local/gcc-9.4.0/include/c++/9.4.0/bits/list.tcc:349
#7  0x00007f735a1af439 in LRUCache<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Os>::refreshKey (
    this=0x7f735a574768 <Singleton<OsDataCache<SocketDBWrapper> >::instance()::s_instance+8>, key=...)
    at /build_wazuh/manager/wazuh-manager-4.9.0/src/shared_modules/utils/cacheLRU.hpp:141
#8  0x00007f735a1ab069 in LRUCache<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Os>::getValue (
    this=0x7f735a574768 <Singleton<OsDataCache<SocketDBWrapper> >::instance()::s_instance+8>, key=...)
    at /build_wazuh/manager/wazuh-manager-4.9.0/src/shared_modules/utils/cacheLRU.hpp:84
```
![image](https://github.com/user-attachments/assets/d7d20bcb-0f58-4f6f-9985-b98e37338f99)

**Comment by Dwordcito** [comment]
Code to reproduce the error:

```cpp
#include <nlohmann/json.hpp>
#include <iostream>
#include <mutex>
#include <shared_mutex>
#include <string>
#include <thread>
#include <list>
#include <map>
#include <optional>

template<typename KeyType, typename ValueType>
class LRUCache final
{
public:

    explicit LRUCache(const size_t capacity)
        : m_capacity(capacity) {};

    void insertKey(const KeyType& key, const ValueType& value)
    {
        if (m_map.size() >= m_capacity)
        {
            // Cache is full, remove the least recently used item (the back of the list)
            const auto& lruKey = m_list.back();
            m_map.erase(lruKey);
            m_list.pop_back();
        }

        // Insert the new key-value pair into the cache
        m_map[key] = value;
        // Move the new item to the front of the list (most recently used)
        refreshKey(key);
    }

    std::optional<ValueType> getValue(const KeyType& key)
    {
        // Check if the key exists in the cache
        if (m_map.find(key) != m_map.end())
        {
            // Move the accessed item to the front of the list (most recently used)
            refreshKey(key);
            return m_map[key];
        }
        return {};
    }

    bool isFull() const
    {
        return m_map.size() == m_capacity;
    }

    bool isHit(const KeyType& key) const
    {
        return m_map.find(key) != m_map.end();
    }

    void forEach(std::function<void(const KeyType&, const ValueType&)> handler) const
    {
        for (const auto& [key, value] : m_map)
        {
            handler(key, value);
        }
    }

private:
    std::map<KeyType, ValueType> m_map; ///< The internal map storing key-value pairs.
    std::list<KeyType> m_list;          ///< The list to manage the order of keys (LRU order).
    size_t m_capacity;                  ///< The maximum capacity of the cache.

    void refreshKey(const KeyType& key)
    {
        m_list.remove(key);
        m_list.emplace_front(key);
    }
};

template<typename T>
class Singleton
{
public:
    static T& instance()
    {
        static T s_instance;
        return s_instance;
    }

protected:
    Singleton() = default;
    virtual ~Singleton() = default;
    Singleton(const Singleton&) = delete;
    Singleton& operator=(const Singleton&) = delete;
};

struct Os final
{
    std::string hostName;       ///< Hostname of the agent.
    std::string architecture;   ///< Architecture of the agent.
    std::string name;           ///< Name of operating system.
    std::string codeName;       ///< Code name of the operating system.
    std::string majorVersion;   ///< Major version of the operating system.
    std::string minorVersion;   ///< Minor version of the operating system.
    std::string patch;          ///< Patch of the operating system.
    std::string build;          ///< Build of the operating system.
    std::string platform;       ///< Platform of the operating system.
    std::string version;        ///< Version of the operating system.
    std::string release;        ///< Release of the operating system.
    std::string displayVersion; ///< Display version of the operating system.
    std::string sysName;        ///< System name of the operating system.
    std::string kernelVersion;  ///< Version of the kernel operating system.
    std::string kernelRelease;  ///< Release of the kernel operating system.
    std::string cpeName;        ///< CPE name of the operating system.
};

class OsDataCache final : public Singleton<OsDataCache>
{
private:
    LRUCache<std::string, Os> m_osData {10};
    std::shared_mutex m_mutex;

    Os getOsDataFromWdb(const std::string& agentId) const
    {
        nlohmann::json response = R"(
            [
                {
                    "hostname": "exampleHost",
                    "architecture": "x86_64",
                    "os_name": "Linux",
                    "os_codename": "buster",
                    "os_major": "4",
                    "os_minor": "19",
                    "os_patch": "0",
                    "os_build": "1",
                    "os_platform": "Debian",
                    "os_version": "4.19.0-1",
                    "os_release": "buster",
                    "os_display_version": "4.19.0-1-buster",
                    "sysname": "Linux",
                    "version": "4.19.0-1-amd64",
                    "release": "buster",
                    "cpe_name": "cpe:/o:debian:debian_linux:10"
                }
            ]
        )"_json;

        Os osData;
        const auto& data = response.at(0);

        osData.hostName = data.value("hostname", "");
        osData.architecture = data.value("architecture", "");
        osData.name = data.value("os_name", "");
        osData.codeName = data.value("os_codename", "");
        osData.majorVersion = data.value("os_major", "");
        osData.minorVersion = data.value("os_minor", "");
        osData.patch = data.value("os_patch", "");
        osData.build = data.value("os_build", "");
        osData.platform = data.value("os_platform", "");
        osData.version = data.value("os_version", "");
        osData.release = data.value("os_release", "");
        osData.displayVersion = data.value("os_display_version", "");
        osData.sysName = data.value("sysname", "");
        osData.kernelVersion = data.value("version", "");
        osData.kernelRelease = data.value("release", "");
        osData.cpeName = data.value("cpe_name", "");

        return osData;
    }

public:
    Os getOsData(const std::string& agentId)
    {
        std::shared_lock lock(m_mutex);
        if (auto value = m_osData.getValue(agentId); value)
        {
            return *value;
        }
        // This may throw an exception that will be captured by the caller method.
        const auto osData = getOsDataFromWdb(agentId);
        m_osData.insertKey(agentId, osData);
        return osData;
    }


    Os getOsDataFix(const std::string& agentId)
    {
        const auto getValue = [this](const std::string& agentIdValue) -> std::optional<Os>
        {
            std::scoped_lock lock(m_mutex);
            if (auto value = m_osData.getValue(agentIdValue); value)
            {
                return *value;
            }
            return std::nullopt;
        };

        if (const auto osData = getValue(agentId); osData != std::nullopt)
        {
            return *osData;
        }

        const auto osData = getOsDataFromWdb(agentId);
        setOsData(agentId, osData);
        return osData;
    }

    void setOsData(const std::string& agentId, const Os& osData)
    {
        std::scoped_lock lock(m_mutex);
        m_osData.insertKey(agentId, osData);
    }
};

void getOsDataThread()
{
    while (1)
    {
        // Random number for the agentid between 1 and 2048
        std::string agentId = std::to_string(rand() % 20 + 1);
        auto osData = OsDataCache::instance().getOsData(agentId);
    }
}

void setOsDataThread()
{
    while (1)
    {
        // Random number for the agentid between 1 and 2048
        std::string agentId = std::to_string(rand() % 20 + 1);
        // Dummy Os data to set.
        Os osData;
        osData.hostName = "exampleHost";
        osData.architecture = "x86_64";
        OsDataCache::instance().setOsData(agentId, osData);
    }
}

int main()
{
    // Launch threads to get and set data concurrently.
    std::thread thread1(getOsDataThread);
    std::thread thread2(getOsDataThread);
    std::thread thread3(getOsDataThread);
    std::thread thread4(getOsDataThread);
    std::thread thread5(getOsDataThread);
    std::thread thread6(setOsDataThread);

    // Wait for threads to finish.
    thread1.join();
    thread2.join();

    return 0;
}
```
