### ISSUE TITLE
Dashboard fails to load CDB lists due to ERR_BAD_REQUEST 

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#25909]
## Description

A [community](https://github.com/wazuh/community/issues/26270) user has reported that they followed the configuration described in [this post](https://wazuh.com/blog/building-ioc-files-for-threat-intelligence-with-wazuh-xdr/), which creates a CDB list with malicious URLs. The issue they are facing is that when attempting to access the CDB lists from the dashboard, they receive the following error:

```
Wazuh API error: ERR_BAD_REQUEST - Bad format in CDB list /var/ossec/etc/lists/mal-url-list
RequestError: Wazuh API error: ERR_BAD_REQUEST - Bad format in CDB list /var/ossec/etc/lists/mal-url-list
    at settle (https://192.168.68.59/47402/bundles/plugin/wazuh/wazuh.plugin.js:8:20234)
    at XMLHttpRequest.onloadend (https://192.168.68.59/47402/bundles/plugin/wazuh/wazuh.plugin.js:8:25708)
```

This error causes the view to "break," and none of the other lists are displayed.

Additionally, I have observed that the manager interprets and constructs the list correctly:

```
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:637 at main(): DEBUG: Reading the lists file: 'etc/lists/audit-keys'
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:637 at main(): DEBUG: Reading the lists file: 'etc/lists/amazon/aws-eventnames'
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:637 at main(): DEBUG: Reading the lists file: 'etc/lists/security-eventchannel'
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:637 at main(): DEBUG: Reading the lists file: 'etc/lists/mal-url-list'
2024/05/27 17:01:30 wazuh-analysisd[26656] analysisd.c:666 at main(): DEBUG: Building CDB lists.
```

Since the manager does not report any error in the list's content, it would be advisable to investigate if there is an issue loading the mal-url-list from the dashboard. The list is a plain text file, so why does the error message refer to XML?

I am attaching the list for you to analyze and conduct any necessary tests.

[mal-url-list.zip](https://github.com/user-attachments/files/15764578/mal-url-list.zip)

**Comment by DamianNud** [comment]
## Update

I could reproduce the issue locally:

```
$ curl -k -X PUT "https://localhost:55000/lists/files/mal-url-list" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/octet-stream" -d "/wp-admin/admin-ajax.php?action=ajax_get&route_name=get_doctor_details&clinic_id=%7B\"id\":\"1\"%7D&props_doctor_id=1,2)+AND+(SELECT+42+FROM+(SELECT(SLEEP(6)))b:" | jq
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1800,
          "message": "Bad format in CDB list {path}"
        },
        "id": [
          "etc/lists/mal-url-list"
        ]
      }
    ]
  },
  "message": "Could not upload CDB list file",
  "error": 1
}
``` 

When executing the `PUT /lists/files/{filename}` endpoint, the `put_file()` function is executed ([source](https://github.com/wazuh/wazuh/blob/48a7ee78dbae8cf9c318072f86ccc293e4347d8e/api/api/controllers/cdb_list_controller.py#L126)), which in turn calls the `upload_list_file()` function ([source](https://github.com/wazuh/wazuh/blob/48a7ee78dbae8cf9c318072f86ccc293e4347d8e/framework/wazuh/cdb_list.py#L114)) that validates the content of the file by calling the `validate_cdb_list()` function ([source](https://github.com/wazuh/wazuh/blob/48a7ee78dbae8cf9c318072f86ccc293e4347d8e/framework/wazuh/core/cdb_list.py#L207)), and the problem there seems to be that the lines that cause the upload to fail are not matching with the regex that is defined in the validation function, as in can be seen here:

![Screenshot](https://github.com/user-attachments/assets/4cead2ef-f77f-4b8a-9316-84eecdfd6914)

By removing the colon (`:`) and the double quotes (`"`) from the `[^:\"\s]` part, the lines match, but I would like to have a better understanding of why those characters were added there in the first place.

**Comment by DamianNud** [comment]
## Update

The [documentation](https://documentation.wazuh.com/current/user-manual/ruleset/cdb-list.html) about CDB lists states that if the colon character (`:`) is part of the key (or the value, I assume), then it must be surrounded with double quotes (`"`). So, I modified the validation to consider the case of multiple colons or double quotes as part of the key-value pair, and by also changing the conflicting lines (adding said double quotes) to comply with the definition, they matched with the regex mentioned above, as it can be seen here:

![Screenshot](https://github.com/user-attachments/assets/4ec5fecb-2829-4fef-8f51-d137e68f6cc6)

However, I found an issue related to the `get_list_from_file()` function ([source](https://github.com/wazuh/wazuh/blob/48a7ee78dbae8cf9c318072f86ccc293e4347d8e/framework/wazuh/core/cdb_list.py#L145)) used to get the key-value pair from each line, as it uses the `split(':')` method or the `split_key_value_with_quotes()` method ([source](https://github.com/wazuh/wazuh/blob/48a7ee78dbae8cf9c318072f86ccc293e4347d8e/framework/wazuh/core/cdb_list.py#L78)), depending if there are double quotes or not, which would mean not being consistent (and maybe robust) with the definition regarding the multiple double quotes and colons. In that case, the same regex could be used to get the key-value pair from each line, by benefiting from the capture groups.

Besides, I noticed that the documentation states that keys must be unique, but that constraint is not being validated when the file is being uploaded. I could successfully upload a file with a repeated key:

```
$ cat repeated-list 
key1:value1
key1:value2

$ FILE=$(cat repeated-list)

$ curl -k -X PUT "https://localhost:55000/lists/files/repeated-list" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/octet-stream" -d "$FILE" | jq
{
  "data": {
    "affected_items": [
      "etc/lists/repeated-list"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list file uploaded successfully",
  "error": 0
}
```

I think this fix might mean having to modify more than just the regex and it has to be analyzed and discussed.

**Comment by DamianNud** [comment]
## Update

As the objective of this issue is fixing the access to the lists, the API management of the CDB lists needs to be fixed, which means fixing the upload validation executed by the `PUT /lists/files/{filename}` endpoint as well as the listing of the elements of a list executed by the `GET /lists/files/{filename}` and the `GET /lists` endpoints.

To achieve said objectives, I modified the regex used for the validation and tried using it in the `get_list_from_file()` function ([source](https://github.com/wazuh/wazuh/blob/48a7ee78dbae8cf9c318072f86ccc293e4347d8e/framework/wazuh/core/cdb_list.py#L145)), to manage the retrieval of the key-value pairs in a list. I was able to successfully upload and list the elements of a CDB list (by fixing the syntax according to the definition) with were found to cause the issue:

```
$ FILE=$(cat mal-url-list-fixed)

$ curl -k -X PUT "https://localhost:55000/lists/files/mal-url-list-fixed" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/octet-stream" -d "$FILE" | jq
{
  "data": {
    "affected_items": [
      "etc/lists/mal-url-list-fixed"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list file uploaded successfully",
  "error": 0
}

$ curl -k -X GET "https://localhost:55000/lists/files/mal-url-list-fixed" -H "Authorization: Bearer $TOKEN" | jq
{
  "data": {
    "affected_items": [
      {
        "/plugins/editors/jckeditor/plugins/jtreelink/dialogs/links.php?extension=menu&view=menu&parent=\"%20UNION%20SELECT%20NULL,NULL,CONCAT_WS(0x203a20,USER(),DATABASE(),VERSION(),md5(999999999)),NULL,NULL,NULL,NULL,NULL--%20aa": "",
        "/wp-login.php": "",
        "/?rest_route=/wc/v3/wishlist/remove_product/1&item_id=0%20union%20select%20sleep(5)%20--%20g": "",
        "/human.aspx?Username=SQL%27%3BINSERT+INTO+activesessions+(SessionID)+values+(%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27);UPDATE+activesessions+SET+Username=(select+Username+from+users+order+by+permission+desc+limit+1)+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27;UPDATE+activesessions+SET+LoginName=%27test@test.com%27+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27;UPDATE+activesessions+SET+RealName=%27test@test.com%27+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27;UPDATE+activesessions+SET+InstId=%271234%27+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27;UPDATE+activesessions+SET+IpAddress=%27198.46.192.22%27+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27;UPDATE+activesessions+SET+LastTouch=%272099-06-10+09:30:00%27+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27;UPDATE+activesessions+SET+DMZInterface=%2710%27+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27;UPDATE+activesessions+SET+Timeout=%2760%27+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27;UPDATE+activesessions+SET+ResilNode=%2710%27+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27;UPDATE+activesessions+SET+AcctReady=%271%27+WHERE+SessionID=%272ejAca7pZcgFHWWXtNMQR8wWZ6P%27%23": ""
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list was returned",
  "error": 0
}
```

This still needs more testing, but using the same regex for validation as for retrieving the key-value pairs could be the solution, also helping with the checking for repeated keys.

**Comment by DamianNud** [comment]
## Update

I created a Draft PR with the changes proposed above, using the new regex to validate the upload and retrieval of a CDB list, and also added a check which validates that all the keys in a file are unique to comply with the definition.

I tested uploading and retrieving a CDB list with repeated keys previous to the change:

```
$ cat repeated-list
key1:value1
key1:value2

$ FILE=$(cat repeated-list)

$ curl -k -X PUT "https://localhost:55000/lists/files/repeated-list" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/octet-stream" -d "$FILE" | jq
{
  "data": {
    "affected_items": [
      "etc/lists/repeated-list"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list file uploaded successfully",
  "error": 0
}

$ curl -k -X GET "https://localhost:55000/lists/files/repeated-list" -H "Authorization: Bearer $TOKEN" | jq
{
  "data": {
    "affected_items": [
      {
        "key1": "value2"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list was returned",
  "error": 0
}
```

As it can be seen, the file is uploaded successfully and when retrieving the CDB list it only shows the second element.

**Comment by fdalmaup** [comment]
For this issue, we need to be careful not to introduce any vulnerability related to the CDB lists' contents (i.e. accepting any character combination) or a new behavior to the current implementation. We must adjust to what is mentioned in the documentation:
- users,
- file hashes (not file paths), 
- IP addresses (IPv4 and IPv6),
- domain names,
- MAC addresses,
- simple URL paths

**Comment by javiersanchz** [comment]
## Update


- I was reading everything mentioned in the threads and the changes that had been proposed.

- Finally, it will be added to version `4.11.0`.

- I started working on the possible changes and testing for it.

**Comment by javiersanchz** [comment]
## Update

- I was testing in an environment the allowed and not allowed values according to our current code.

- I was reviewing the documentation about Wazuh's CDB lists to see if we were complying with what is mentioned there.

- I was testing changes to the handling of the CDB list, accepting characters like those mentioned in the issue.

- I will document everything tomorrow

**Comment by javiersanchz** [comment]
## Update

I was running some tests in an environment.

Using the following line as in previous updates:

`/wp-admin/admin-ajax.php?action=ajax_get&route_name=get_doctor_details&clinic_id=%7B\"id\":\"1\"%7D&props_doctor_id=1,2)+AND+(SELECT+42+FROM+(SELECT(SLEEP(6)))b:`

```console
root@wazuh-master:/# cat test_file
/wp-admin/admin-ajax.php?action=ajax_get&route_name=get_doctor_details&clinic_id=%7B\"id\":\"1\"%7D&props_doctor_id=1,2)+AND+(SELECT+42+FROM+(SELECT(SLEEP(6)))b:

root@wazuh-master:/# curl -k -X PUT "https://localhost:55000/lists/files/test_file" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/octet-stream" -d @test_file | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   422  100   261  100   161   4358   2688 --:--:-- --:--:-- --:--:--  7152
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1800,
          "message": "Bad format in CDB list {path}"
        },
        "id": [
          "etc/lists/test_file"
        ]
      }
    ]
  },
  "message": "Could not upload CDB list file",
  "error": 1
}
```

This returns the error mentioned: `1800 Bad format in CDB list {path}`

This is due to:

1. The value is missing double quotes `""`.

2. It contains invalid characters such as `/, ?, &, %, +, ), (` which are not accepted unless enclosed in double quotes.

If we add double quotes `""` to this same line, it is processed correctly:

```console
root@wazuh-master:/# cat test_file3
"/wp-admin/admin-ajax.php?action=ajax_get&route_name=get_doctor_details&clinic_id=%7B\"id\":\"1\"%7D&props_doctor_id=1,2)+AND+(SELECT+42+FROM+(SELECT(SLEEP(6)))b":

root@wazuh-master:/# curl -k -X PUT "https://localhost:55000/lists/files/test_file3" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/octet-stream" -d @test_file | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   359  100   188  100   171   3356   3053 --:--:-- --:--:-- --:--:--  6527
{
  "data": {
    "affected_items": [
      "etc/lists/test_file3"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list file uploaded successfully",
  "error": 0
}
```

This is because, although it contains special characters, they are enclosed in double quotes, which are accepted in such cases. As mentioned in the documentation, it is allowed to add a `key:` only.

Testing was also done by slightly modifying the key and adding a value (`key:value`), and it was processed correctly since the special characters are also enclosed in double quotes:


```console
root@wazuh-master:/# cat test_file
"/wp-admin/admin-ajax.php?action=ajax_get&route_name=get_doctor_details&clinic_id={\"id\":\"1\"}&props_doctor_id=1,2)+AND+(SELECT+42+FROM+(SELECT(SLEEP(6)))b":"some_value"

root@wazuh-master:/# curl -k -X PUT "https://localhost:55000/lists/files/test_file" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/octet-stream" -d @test_file | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   358  100   187  100   171   3047   2786 --:--:-- --:--:-- --:--:--  5868
{
  "data": {
    "affected_items": [
      "etc/lists/test_file"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "CDB list file uploaded successfully",
  "error": 0
}
```

As mentioned in the previous update https://github.com/wazuh/wazuh/issues/25909#issuecomment-2565469419, our CDB list should accept:

- users,
- file hashes (not file paths),
- IP addresses (IPv4 and IPv6),
- domain names,
- MAC addresses,
- simple URL paths as the one mentioned in the [Building IoC files for threat intelligence with Wazuh XDR blogpost](https://wazuh.com/blog/building-ioc-files-for-threat-intelligence-with-wazuh-xdr/)

(since we need to avoid introducing any vulnerability related to the content of the CDB lists.)

Our current regex allows keys without quotes if they are simple.

### Required format based on the regex:

**1. Keys without quotes:**
- They can only contain:

- Letters` (a-z, A-Z)`.
- Numbers `(0-9)`.
- Hyphens `(-)`.
- Underscores `(_)`.

Valid examples:
```
key:value
user1:admin
```

**2. Keys with quotes:**
- They can contain any special character if they are enclosed in double quotes

 Valid examples:

```
"complex:key/with/specials":"value"
"/path/to/resource":"allowed"
```


**3. Mandatory separator:**
- There must be a `":"` separating the key from the value.


**4. Allowed value:**
- It can be with or without double quotes:

- Without quotes: Alphanumeric and hyphens.
- With quotes: Any allowed special character.

Based on our documentation https://documentation.wazuh.com/current/user-manual/ruleset/cdb-list.html, we are correctly addressing the requirements mentioned above.

- Having control over special characters by requiring quotation marks for keys with special characters reduces the risk of malicious entries (such as SQL injections) being incorrectly interpreted and maintaining robust formatting, ensuring that all entries follow a defined and expected structure.

- Perhaps we could mention in the documentation that to include special characters, we must enclose them in double quotes, since only the colon `:` character is currently mentioned.

- From my point of view, the requirements are met, and proper control and order over the CDB List are maintained, so I would leave it as it is currently.

**Comment by RamosFe** [comment]
## Review

The analysis was conducted accurately and justified throughout the updates in the issue. LGTM 🚀

**Comment by nico-stefani** [comment]
LGTM

**Comment by wirehack7** [comment]
Seems this is not 100% solved.
When I try with something like that: `"C:\\WINDOWS\\system32\\WerFault.exe":` it fails:

```
Could not upload CDB list file (1800) - Bad format in CDB list {path}
```
