### ISSUE TITLE
Investigate and fix the error related to the batcher

### ISSUE THREAD

**Issue by javiersanchz** [wazuh/wazuh#26086]
|Objective|
|---|
| https://github.com/wazuh/wazuh/issues/22677 |

## Description

It was found that `wazuh-comms-apid` is failing and returns an error upon starting:

```console
wazuh@javier:~$ docker logs 1af9f7494a5d
2024/10/01 10:27:45 wazuh-db[51] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2024/10/01 10:27:45 wazuh-db[51] main.c:125 at main(): DEBUG: Wazuh home directory: /var/ossec
2024/10/01 10:27:45 wazuh-remoted[56] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2024/10/01 10:27:45 wazuh-remoted[56] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2024/10/01 10:27:45 wazuh-remoted[56] main.c:148 at main(): DEBUG: This is not a worker
2024/10/01 10:27:45 wazuh-modulesd:router: INFO: Loaded router module.
2024/10/01 10:27:45 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
Starting Wazuh v5.0.0...
wazuh-comms-apid did not start correctly.
```

```console
root@wazuh-master:/# /var/ossec/bin/wazuh-control restart
...
Wazuh v5.0.0 Stopped
Starting Wazuh v5.0.0...
wazuh-comms-apid did not start correctly.
```

```console
root@wazuh-master:/var/ossec# bin/wazuh-control status | grep "comms"
wazuh-comms-apid not running...
```
When running `/var/ossec/bin/wazuh-comms-apid -f`, we encountered an infinite loop with the following error: 

<details>

```console
2024/10/01 10:39:23 ERROR: Error with MuxDemuxQueue run: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/batcher/mux_demux.py", line 174, in run
    item = self.queue.internal_response_from_demux()
  File "<string>", line 2, in internal_response_from_demux
  File "/var/ossec/framework/python/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/var/ossec/framework/python/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/var/ossec/framework/python/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/var/ossec/framework/python/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
^CException ignored in atexit callback: <function _exit_function at 0x7225cf3b9bd0>
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/multiprocessing/util.py", line 357, in _exit_function
2024/10/01 10:39:23 INFO: MuxDemuxQueue pid 6237 - received signal SIGINT
```

</details>

This indicates that at some point in the flow, the communication between processes in `MuxDemuxQueue` failed, suggesting that:

- The receiving process was either unavailable or disconnected before the sending operation could be completed. The connection was closed for some reason, such as a failure or interruption, before the data could be processed correctly

**Comment by GGP1** [comment]
## Update

Reproduced the error, fixed some issues during the batcher process creation and signal handling and validated that everything worked as expected after the changes.
