### ISSUE TITLE
Issue Regarding MITRE ATT&CK

### ISSUE THREAD

**Issue by himuura** [wazuh/wazuh#26288]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

{"WAZUH_VERSION":"v4.9.0"},{"WAZUH_REVISION":"40907"},{"WAZUH_TYPE":"server"}
 OS:
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"

Wazuh-Dashboard - MITRE ATT&CK module

Hey! First of all i don't think it's a bug per se but rather something weird with the update.
Updated wazuh today to v.4.9.0, some shards failed, that's fine, but whenever i open an entry in the Mitre ATT&CK of a given agent i receive an error:

![image](https://github.com/user-attachments/assets/6aa5242d-6862-4b55-a5b0-5afd82614187)
![image](https://github.com/user-attachments/assets/51837525-e2c8-4061-ab0f-9fe09a12239b)

To be fair, while updating through apt update, i DID NOT replace the files with the newer ones so i think something must be broken on the config files.
Can anyone lend me a hand?

**Comment by himuura** [comment]
Adding some logs:
Oct 11 16:49:57 srv-wazuh opensearch-dashboards[702]: {"type":"response","@timestamp":"2024-10-11T15:49:57Z","tags":[],"pid":702,"method":"get","statusCode":200,"req":{"url":"/ui/logos/
wazuh_mark_on_light.svg","method":"get","headers":{"host":"MY_IP_ADDRESS","connection":"keep-alive","sec-ch-ua-platform":"\"Windows\"","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64;
 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","sec-ch-ua":"\"Google Chrome\";v=\"129\", \"Not=A?Brand\";v=\"8\", \"Chromium\";v=\"129\"","sec-ch-ua-mobile
":"?0","accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","sec-fetch-site":"same-origin","sec-fetch-mode":"no-cors","sec-fetch-dest":"image","referer":"https://
MY_IP_ADDRESS/app/endpoints-summary","accept-encoding":"gzip, deflate, br, zstd","accept-language":"pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"REMOTE_ACCESS_IP_ADDRESS","userAgent":"Moz
illa/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","referer":"https://MY_IP_ADDRESS/app/endpoints-summary"},"res":{"statusCode
":200,"responseTime":5,"contentLength":9},"message":"GET /ui/logos/wazuh_mark_on_light.svg 200 5ms - 9.0B"}
Oct 11 16:50:13 srv-wazuh opensearch-dashboards[702]: {"type":"response","@timestamp":"2024-10-11T15:50:13Z","tags":[],"pid":702,"method":"post","statusCode":200,"req":{"url":"/elastic/
alerts","method":"post","headers":{"host":"MY_IP_ADDRESS","connection":"keep-alive","content-length":"420","sec-ch-ua-platform":"\"Windows\"","sec-ch-ua":"\"Google Chrome\";v=\"129\", \
"Not=A?Brand\";v=\"8\", \"Chromium\";v=\"129\"","sec-ch-ua-mobile":"?0","id":"default","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chr
ome/129.0.0.0 Safari/537.36","accept":"application/json, text/plain, */*","content-type":"application/json","pattern":"wazuh-alerts-*","osd-xsrf":"kibana","origin":"https://MY_IP_ADDRES
S","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://MY_IP_ADDRESS/app/endpoints-summary","accept-encoding":"gzip, deflate, br, zstd","a
ccept-language":"pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"REMOTE_ACCESS_IP_ADDRESS","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrom
e/129.0.0.0 Safari/537.36","referer":"https://MY_IP_ADDRESS/app/endpoints-summary"},"res":{"statusCode":200,"responseTime":45,"contentLength":9},"message":"POST /elastic/alerts 200 45ms
 - 9.0B"}
Oct 11 16:50:18 srv-wazuh opensearch-dashboards[702]: {"type":"error","@timestamp":"2024-10-11T15:50:18Z","tags":[],"pid":702,"level":"error","error":{"message":"Internal Server Error",
"name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/wazuh-dashboard/src/core/server/http/router/response_adapter.js:127:19)\n    at Hapi
ResponseAdapter.toHapiResponse (/usr/share/wazuh-dashboard/src/core/server/http/router/response_adapter.js:83:19)\n    at HapiResponseAdapter.handle (/usr/share/wazuh-dashboard/src/core
/server/http/router/response_adapter.js:79:17)\n    at Router.handle (/usr/share/wazuh-dashboard/src/core/server/http/router/router.js:175:34)\n    at processTicksAndRejections (node:in
ternal/process/task_queues:95:5)\n    at handler (/usr/share/wazuh-dashboard/src/core/server/http/router/router.js:140:50)\n    at exports.Manager.execute (/usr/share/wazuh-dashboard/no
de_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/shar
e/wazuh-dashboard/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._ex
ecute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"https://MY_IP_ADDRESS/utils/logs/ui","message":"Internal Server Error"}
Oct 11 16:50:18 srv-wazuh opensearch-dashboards[702]: {"type":"response","@timestamp":"2024-10-11T15:50:18Z","tags":[],"pid":702,"method":"post","statusCode":500,"req":{"url":"/utils/lo
gs/ui","method":"post","headers":{"host":"MY_IP_ADDRESS","connection":"keep-alive","content-length":"1086","sec-ch-ua-platform":"\"Windows\"","sec-ch-ua":"\"Google Chrome\";v=\"129\", \
"Not=A?Brand\";v=\"8\", \"Chromium\";v=\"129\"","sec-ch-ua-mobile":"?0","id":"default","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chr
ome/129.0.0.0 Safari/537.36","accept":"application/json, text/plain, */*","content-type":"application/json","pattern":"wazuh-alerts-*","osd-xsrf":"kibana","origin":"https://MY_IP_ADDRES
S","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://MY_IP_ADDRESS/app/endpoints-summary","accept-encoding":"gzip, deflate, br, zstd","a
ccept-language":"pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7"},"remoteAddress":"REMOTE_ACCESS_IP_ADDRESS","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrom
e/129.0.0.0 Safari/537.36","referer":"https://MY_IP_ADDRESS/app/endpoints-summary"},"res":{"statusCode":500,"responseTime":14,"contentLength":9},"message":"POST /utils/logs/ui 500 14ms
- 9.0B"}
Oct 11 16:50:19 srv-wazuh opensearch-dashboards[702]: {"type":"response","@timestamp":"2024-10-11T15:50:18Z","tags":[],"pid":702,"method":"post","statusCode":200,"req":{"url":"/api/chec
k-stored-api","method":"post","headers":{"host":"MY_IP_ADDRESS","connection":"keep-alive","content-length":"16","sec-ch-ua-platform":"\"Windows\"","user-agent":"Mozilla/5.0 (Windows NT
10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","accept":"application/json, text/plain, */*","sec-ch-ua":"\"Google Chrome\";v=\"129\", \"Not=A?B
rand\";v=\"8\", \"Chromium\";v=\"129\"","content-type":"application/json","sec-ch-ua-mobile":"?0","osd-xsrf":"kibana","origin":"https://MY_IP_ADDRESS","sec-fetch-site":"same-origin","se
c-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://MY_IP_ADDRESS/app/endpoints-summary","accept-encoding":"gzip, deflate, br, zstd","accept-language":"pt-PT,pt;q=0.9,en-US
;q=0.8,en;q=0.7"},"remoteAddress":"REMOTE_ACCESS_IP_ADDRESS","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","referer":
"https://MY_IP_ADDRESS/app/endpoints-summary"},"res":{"statusCode":200,"responseTime":669,"contentLength":9},"message":"POST /api/check-stored-api 200 669ms - 9.0B"}

**Comment by himuura** [comment]
Can anyone lend a hand? I have no clue...spent lots of hours around this issue and cannot figure it out.
Any ideas would be greatly appreciated.

**Comment by agregorian** [comment]
I have the same problem!

**Comment by himuura** [comment]
> I have the same problem!

New update to wazuh did not solve the issue, i opened an issue in the wazuh-dashboard section of github. Give your feedback there, my dude.
https://github.com/wazuh/wazuh-dashboard/issues/357

**Comment by candrews67** [comment]
Using Docker and have same problem.

**Comment by Wang-YLi** [comment]
I have the same problem!
