### ISSUE TITLE
Internal user can't see the Vulnerability Detection page

### ISSUE THREAD

**Issue by OndrejSerek** [wazuh/wazuh#26280]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8 | Wazuh dashboard | Manager/Agent | wazuh-install.sh | Debian 12 |

Hello,
I am struggling to see the vulnerability detection dashboard for other users. It is stuck on the loading screen forever - with the searching circle. As an admin_user I can see it well, everything is working, I am getting vulnerabilities from all agents as I should (I have read and applied the 4.8 update guide for new configurations). But I have created two other users and I can't see the vulnerability detection page for both of these users. It just shows loading screens. 

![image](https://github.com/user-attachments/assets/bb059074-3de9-482f-8b11-6b32b88381be)

**Chrome Dev tools tab network:**
This is what I am getting when requesting the /api/saved_objects/index-pattern/wazuh-states-vulnerabilities-*
{
    "statusCode": 403,
    "error": "Forbidden",
    "message": "no permissions for [indices:data/write/update] and User [name=test_user, backend_roles=[], requestedTenant=null]: security_exception: [security_exception] Reason: no permissions for [indices:data/write/update] and User [name=test_user, backend_roles=[], requestedTenant=null]"
}

**Chrome Dev tools tab console:**  
Uncaught (in promise) Error: Error selecting index pattern: Error
    at vulnerabilities_data_source_VulnerabilitiesDataSource.select (wazuh.chunk.3.js:1:1435392)
    at async PatternDataSourceSelector.selectDataSource (wazuh.chunk.3.js:1:1500428)
    at async PatternDataSourceSelector.getSelectedDataSource (wazuh.chunk.3.js:1:1500883)
    at async wazuh.chunk.3.js:1:1515995

**Steps to reproduce:**
1. Create a new user via guide https://documentation.wazuh.com/current/user-manual/user-administration/rbac.html#use-case-give-a-user-permissions-to-read-and-manage-a-group-of-agents
2. Add the new user a permission for the wazuh-states-vulnerabilities index
![image](https://github.com/user-attachments/assets/db7c2abc-d060-4648-a8a7-3bc56c787bb8)

**Expected result:**
I expect to see the vulnerability detection page for user test_user in the same way as for the admin user (shown in the image).
![image](https://github.com/user-attachments/assets/7cd66218-417e-4f60-98e4-87c35ee96f72)

**Important**
Please note that I have also tried to read the index via Index manager DevTools and I received the correct results (as you can see in the image), so I know that I have set up the permissions for this user (test_user) correctly. I have also tried to add the test_user the permission indices:data/write/update as suggested by chrome network dev tools, but with no progress.
![image](https://github.com/user-attachments/assets/80383f00-6b70-4752-8472-48c7e3850d8c)

**Comment by OndrejSerek** [comment]
The bug was solved with the upgrade to the 4.9.1 version. The issue was the duplicate of the https://github.com/wazuh/wazuh-dashboard-plugins/pull/6993.
