### ISSUE TITLE
Update RBAC decorators to get information from the indexer

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#26350]
## Description

During the development of https://github.com/wazuh/wazuh/issues/26077, I noticed that it is currently not possible to make requests without having `wazuh-db` running.

This is the error I get

<details><summary>Error</summary>

```console
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 262, in execute_local_request
    task = self.run_local(self.f, self.f_kwargs, self.rbac_permissions, self.broadcasting,
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 235, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/decorators.py", line 457, in wrapper
    allow = _match_permissions(req_permissions=req_permissions, rbac_mode=rbac.get()['rbac_mode'])
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/decorators.py", line 277, in _match_permissions
    _single_processor(req_resources, rbac.get().get(req_action, dict()), allow_match)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/decorators.py", line 219, in _single_processor
    expanded_resource = _expand_resource(user_resource)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/decorators.py", line 38, in _expand_resource
    return expand_group(value)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/common.py", line 101, in wrapper
    result = func(*args, **kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/agent.py", line 1227, in expand_group
    wdb_conn = WazuhDBConnection()
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/wdb.py", line 150, in __init__
    raise WazuhInternalError(2005, e)
wazuh.core.exception.WazuhInternalError: Error 2005 - [Errno 2] No such file or directory
```

</details>

The reason for it being that RBAC decorators still get the agents and groups information from that source

https://github.com/wazuh/wazuh/blob/918f693384cb80e465ea5e024985a3a1d6ddac9f/framework/wazuh/core/agent.py#L1213-L1251

We should update all RBAC-related functions to obtain this information from the indexer instead.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Applied the changes necessary to obtain the information from the indexer. There's one unit test file failing because of the event loop, solving this is the only thing left to do.
