### ISSUE TITLE
Wazuh-Dashboard service doesn't start

### ISSUE THREAD

**Issue by sureshkachwa** [wazuh/wazuh#26386]
Wazuh version: 4.9.1
Component: Wazuh-Dashboard
Install type: All components are deployed in a single VM
Install method: Script based
Platform: Ubuntu 22.04.4 LTS

Here is the thing, it was working before making SSO changes, below is the document I followed
https://documentation.wazuh.com/current/user-manual/user-administration/single-sign-on/administrator/google.html

**##systemctl status wazuh-dashboard.service##, below is the output**
```root@wazuh:~# systemctl status wazuh-dashboard.service
× wazuh-dashboard.service - wazuh-dashboard
     Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-10-17 03:49:06 UTC; 1 day 4h ago
    Process: 405448 ExecStart=/usr/share/wazuh-dashboard/bin/opensearch-dashboards (code=exited, status=1/FAILURE)
   Main PID: 405448 (code=exited, status=1/FAILURE)
        CPU: 4.101s

Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at ReplaySubject._subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/ReplaySubject.js:80:28)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at ReplaySubject.Observable._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:44:25)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at ReplaySubject.Subject._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subject.js:102:51)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at ReplaySubject.Observable.subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:30:22)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber.shareReplayOperation (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/shareReplay.js:53:32)
Oct 17 03:49:06 wazuh systemd[1]: wazuh-dashboard.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 03:49:06 wazuh systemd[1]: wazuh-dashboard.service: Failed with result 'exit-code'.
Oct 17 03:49:06 wazuh systemd[1]: wazuh-dashboard.service: Consumed 4.101s CPU time.```

**##journalctl -u wazuh-dashboard -n 100 --no-pager##, output below:**
```Sep 26 05:12:52 wazuh systemd[1]: wazuh-dashboard.service: Consumed 4.249s CPU time.
Sep 26 05:13:58 wazuh systemd[1]: Started wazuh-dashboard.
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]: {"type":"log","@timestamp":"2024-09-26T05:14:01Z","tags":["info","plugins-service"],"pid":199172,"message":"Plugin \"dataSourceManagement\" has been disabled since the following direct or transitive dependencies are missing or disabled: [dataSource]"}
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]: {"type":"log","@timestamp":"2024-09-26T05:14:01Z","tags":["info","plugins-service"],"pid":199172,"message":"Plugin \"applicationConfig\" is disabled."}
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]: {"type":"log","@timestamp":"2024-09-26T05:14:01Z","tags":["info","plugins-service"],"pid":199172,"message":"Plugin \"cspHandler\" is disabled."}
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]: {"type":"log","@timestamp":"2024-09-26T05:14:01Z","tags":["info","plugins-service"],"pid":199172,"message":"Plugin \"dataSource\" is disabled."}
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]: {"type":"log","@timestamp":"2024-09-26T05:14:01Z","tags":["info","plugins-service"],"pid":199172,"message":"Plugin \"visTypeXy\" is disabled."}
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]: {"type":"log","@timestamp":"2024-09-26T05:14:01Z","tags":["fatal","root"],"pid":199172,"message":"Error: ENOENT: no such file or directory, open '/etc/wazuh-dashboard/certs/dashboard-key.pem'\n    at Object.openSync (node:fs:596:3)\n    at readFileSync (node:fs:464:35)\n    at readFile (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:170:31)\n    at new SslConfig (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:130:18)\n    at new HttpConfig (/usr/share/wazuh-dashboard/src/core/server/http/http_config.js:174:16)\n    at MapSubscriber.project (/usr/share/wazuh-dashboard/src/core/server/http/http_service.js:67:177)\n    at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at CombineLatestSubscriber.notifyNext (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/observable/combineLatest.js:97:34)\n    at InnerSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/InnerSubscriber.js:28:21)\n    at InnerSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at ReplaySubject._subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/ReplaySubject.js:80:28)\n    at ReplaySubject.Observable._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:44:25)\n    at ReplaySubject.Subject._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subject.js:102:51)\n    at ReplaySubject.Observable.subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:30:22)\n    at MapSubscriber.shareReplayOperation (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/shareReplay.js:53:32) {\n  errno: -2,\n  syscall: 'open',\n  code: 'ENOENT',\n  path: '/etc/wazuh-dashboard/certs/dashboard-key.pem'\n}"}
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]: Error: ENOENT: no such file or directory, open '/etc/wazuh-dashboard/certs/dashboard-key.pem'
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at Object.openSync (node:fs:596:3)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at readFileSync (node:fs:464:35)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at readFile (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:170:31)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at new SslConfig (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:130:18)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at new HttpConfig (/usr/share/wazuh-dashboard/src/core/server/http/http_config.js:174:16)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at MapSubscriber.project (/usr/share/wazuh-dashboard/src/core/server/http/http_service.js:67:177)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:49:35)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at CombineLatestSubscriber.notifyNext (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/observable/combineLatest.js:97:34)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at InnerSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at InnerSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at DistinctUntilChangedSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at ReplaySubject._subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/ReplaySubject.js:80:28)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at ReplaySubject.Observable._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:44:25)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at ReplaySubject.Subject._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subject.js:102:51)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at ReplaySubject.Observable.subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:30:22)
Sep 26 05:14:01 wazuh opensearch-dashboards[199172]:     at MapSubscriber.shareReplayOperation (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/shareReplay.js:53:32)
Sep 26 05:14:01 wazuh systemd[1]: wazuh-dashboard.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 05:14:01 wazuh systemd[1]: wazuh-dashboard.service: Failed with result 'exit-code'.
Sep 26 05:14:01 wazuh systemd[1]: wazuh-dashboard.service: Consumed 4.197s CPU time.
Oct 17 03:39:11 wazuh systemd[1]: Started wazuh-dashboard.
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]: {"type":"log","@timestamp":"2024-10-17T03:39:15Z","tags":["info","plugins-service"],"pid":405192,"message":"Plugin \"dataSourceManagement\" has been disabled since the following direct or transitive dependencies are missing or disabled: [dataSource]"}
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]: {"type":"log","@timestamp":"2024-10-17T03:39:15Z","tags":["info","plugins-service"],"pid":405192,"message":"Plugin \"applicationConfig\" is disabled."}
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]: {"type":"log","@timestamp":"2024-10-17T03:39:15Z","tags":["info","plugins-service"],"pid":405192,"message":"Plugin \"cspHandler\" is disabled."}
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]: {"type":"log","@timestamp":"2024-10-17T03:39:15Z","tags":["info","plugins-service"],"pid":405192,"message":"Plugin \"dataSource\" is disabled."}
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]: {"type":"log","@timestamp":"2024-10-17T03:39:15Z","tags":["info","plugins-service"],"pid":405192,"message":"Plugin \"visTypeXy\" is disabled."}
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]: {"type":"log","@timestamp":"2024-10-17T03:39:15Z","tags":["fatal","root"],"pid":405192,"message":"Error: ENOENT: no such file or directory, open '/etc/wazuh-dashboard/certs/dashboard-key.pem'\n    at Object.openSync (node:fs:596:3)\n    at readFileSync (node:fs:464:35)\n    at readFile (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:170:31)\n    at new SslConfig (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:130:18)\n    at new HttpConfig (/usr/share/wazuh-dashboard/src/core/server/http/http_config.js:174:16)\n    at MapSubscriber.project (/usr/share/wazuh-dashboard/src/core/server/http/http_service.js:67:177)\n    at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at CombineLatestSubscriber.notifyNext (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/observable/combineLatest.js:97:34)\n    at InnerSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/InnerSubscriber.js:28:21)\n    at InnerSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at ReplaySubject._subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/ReplaySubject.js:80:28)\n    at ReplaySubject.Observable._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:44:25)\n    at ReplaySubject.Subject._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subject.js:102:51)\n    at ReplaySubject.Observable.subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:30:22)\n    at MapSubscriber.shareReplayOperation (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/shareReplay.js:53:32) {\n  errno: -2,\n  syscall: 'open',\n  code: 'ENOENT',\n  path: '/etc/wazuh-dashboard/certs/dashboard-key.pem'\n}"}
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]: Error: ENOENT: no such file or directory, open '/etc/wazuh-dashboard/certs/dashboard-key.pem'
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at Object.openSync (node:fs:596:3)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at readFileSync (node:fs:464:35)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at readFile (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:170:31)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at new SslConfig (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:130:18)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at new HttpConfig (/usr/share/wazuh-dashboard/src/core/server/http/http_config.js:174:16)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at MapSubscriber.project (/usr/share/wazuh-dashboard/src/core/server/http/http_service.js:67:177)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:49:35)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at CombineLatestSubscriber.notifyNext (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/observable/combineLatest.js:97:34)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at InnerSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at InnerSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at DistinctUntilChangedSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at ReplaySubject._subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/ReplaySubject.js:80:28)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at ReplaySubject.Observable._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:44:25)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at ReplaySubject.Subject._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subject.js:102:51)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at ReplaySubject.Observable.subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:30:22)
Oct 17 03:39:15 wazuh opensearch-dashboards[405192]:     at MapSubscriber.shareReplayOperation (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/shareReplay.js:53:32)
Oct 17 03:39:15 wazuh systemd[1]: wazuh-dashboard.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 03:39:15 wazuh systemd[1]: wazuh-dashboard.service: Failed with result 'exit-code'.
Oct 17 03:39:15 wazuh systemd[1]: wazuh-dashboard.service: Consumed 4.175s CPU time.
Oct 17 03:49:03 wazuh systemd[1]: Started wazuh-dashboard.
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]: {"type":"log","@timestamp":"2024-10-17T03:49:06Z","tags":["info","plugins-service"],"pid":405448,"message":"Plugin \"dataSourceManagement\" has been disabled since the following direct or transitive dependencies are missing or disabled: [dataSource]"}
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]: {"type":"log","@timestamp":"2024-10-17T03:49:06Z","tags":["info","plugins-service"],"pid":405448,"message":"Plugin \"applicationConfig\" is disabled."}
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]: {"type":"log","@timestamp":"2024-10-17T03:49:06Z","tags":["info","plugins-service"],"pid":405448,"message":"Plugin \"cspHandler\" is disabled."}
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]: {"type":"log","@timestamp":"2024-10-17T03:49:06Z","tags":["info","plugins-service"],"pid":405448,"message":"Plugin \"dataSource\" is disabled."}
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]: {"type":"log","@timestamp":"2024-10-17T03:49:06Z","tags":["info","plugins-service"],"pid":405448,"message":"Plugin \"visTypeXy\" is disabled."}
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]: {"type":"log","@timestamp":"2024-10-17T03:49:06Z","tags":["fatal","root"],"pid":405448,"message":"Error: ENOENT: no such file or directory, open '/etc/wazuh-dashboard/certs/dashboard-key.pem'\n    at Object.openSync (node:fs:596:3)\n    at readFileSync (node:fs:464:35)\n    at readFile (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:170:31)\n    at new SslConfig (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:130:18)\n    at new HttpConfig (/usr/share/wazuh-dashboard/src/core/server/http/http_config.js:174:16)\n    at MapSubscriber.project (/usr/share/wazuh-dashboard/src/core/server/http/http_service.js:67:177)\n    at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at CombineLatestSubscriber.notifyNext (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/observable/combineLatest.js:97:34)\n    at InnerSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/InnerSubscriber.js:28:21)\n    at InnerSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at ReplaySubject._subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/ReplaySubject.js:80:28)\n    at ReplaySubject.Observable._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:44:25)\n    at ReplaySubject.Subject._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subject.js:102:51)\n    at ReplaySubject.Observable.subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:30:22)\n    at MapSubscriber.shareReplayOperation (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/shareReplay.js:53:32) {\n  errno: -2,\n  syscall: 'open',\n  code: 'ENOENT',\n  path: '/etc/wazuh-dashboard/certs/dashboard-key.pem'\n}"}
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]: Error: ENOENT: no such file or directory, open '/etc/wazuh-dashboard/certs/dashboard-key.pem'
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at Object.openSync (node:fs:596:3)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at readFileSync (node:fs:464:35)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at readFile (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:170:31)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at new SslConfig (/usr/share/wazuh-dashboard/src/core/server/http/ssl_config.js:130:18)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at new HttpConfig (/usr/share/wazuh-dashboard/src/core/server/http/http_config.js:174:16)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber.project (/usr/share/wazuh-dashboard/src/core/server/http/http_service.js:67:177)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:49:35)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at CombineLatestSubscriber.notifyNext (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/observable/combineLatest.js:97:34)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at InnerSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at InnerSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at DistinctUntilChangedSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber._next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/map.js:55:26)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber.Subscriber.next (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subscriber.js:66:18)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at ReplaySubject._subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/ReplaySubject.js:80:28)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at ReplaySubject.Observable._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:44:25)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at ReplaySubject.Subject._trySubscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Subject.js:102:51)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at ReplaySubject.Observable.subscribe (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/Observable.js:30:22)
Oct 17 03:49:06 wazuh opensearch-dashboards[405448]:     at MapSubscriber.shareReplayOperation (/usr/share/wazuh-dashboard/node_modules/rxjs/internal/operators/shareReplay.js:53:32)
Oct 17 03:49:06 wazuh systemd[1]: wazuh-dashboard.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 03:49:06 wazuh systemd[1]: wazuh-dashboard.service: Failed with result 'exit-code'.
Oct 17 03:49:06 wazuh systemd[1]: wazuh-dashboard.service: Consumed 4.101s CPU time.```

**Comment by SirStephanikus** [comment]
It clearly shows you the issue:

`Error: ENOENT: no such file or directory, open '/etc/wazuh-dashboard/certs/dashboard-key.pem'`

**Comment by sureshkachwa** [comment]
Ok, so here is the thing, see the outputs below, opensearch_dashboard.yml doesn't have any field referring to dashboard-key.pem

**cat /etc/systemd/system/wazuh-dashboard.service**
```[Unit]
Description=wazuh-dashboard

[Service]
Type=simple
User=wazuh-dashboard
Group=wazuh-dashboard
EnvironmentFile=-/etc/default/wazuh-dashboard
EnvironmentFile=-/etc/sysconfig/wazuh-dashboard
ExecStart=/usr/share/wazuh-dashboard/bin/opensearch-dashboards
WorkingDirectory=/usr/share/wazuh-dashboard

[Install]
WantedBy=multi-user.target
```
**grep -r "dashboard-key.pem" /etc/wazuh-dashboard/**
```/etc/wazuh-dashboard/opensearch_dashboards.yml:server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
/etc/wazuh-dashboard/opensearch_dashboards.yml_bkp:server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
```

**cat /etc/wazuh-dashboard/opensearch_dashboards.yml**
```server.host: 0.0.0.0
opensearch.hosts: https://127.0.0.1:9200
server.port: 443
opensearch.ssl.verificationMode: certificate
# opensearch.username: kibanaserver
# opensearch.password: kibanaserver
opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/wazuh-dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wz-home
opensearch_security.cookie.secure: true
opensearch_security.auth.type: "saml"
server.xsrf.allowlist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout", "/_opendistro/_security/saml/acs/idpinitiated"]
```

**Comment by DevDorrejo** [comment]
create symbolic link, with the name, wazuh only change the name of the cert, creating a link will solve the issue.
