### ISSUE TITLE
Unhandled exception during event dispatch

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#26452]
## Description

This issue aims to fix an unhandled exception during the IPC event parsing in the server side (broker).

Basically we discover the next backtrace:

```gdb
terminate called recursively
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdef7d700 (LWP 24951)]
0x00007ffff5ef3387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install wazuh-manager-4.8.2-0.debug.x86_64
```

```gdb
(gdb) bt
#0  0x00007ffff5ef3387 in raise () from /lib64/libc.so.6
#1  0x00007ffff5ef4a78 in abort () from /lib64/libc.so.6
#2  0x00007fffee815a72 in __gnu_cxx::__verbose_terminate_handler() () from /var/ossec/bin/../lib/../lib/libstdc++.so.6
#3  0x00007fffee813b66 in ?? () from /var/ossec/bin/../lib/../lib/libstdc++.so.6
#4  0x00007fffee813bd1 in std::terminate() () from /var/ossec/bin/../lib/../lib/libstdc++.so.6
#5  0x00007fffee813e24 in __cxa_throw () from /var/ossec/bin/../lib/../lib/libstdc++.so.6
#6  0x00007fffee80a8c4 in std::__throw_out_of_range(char const*) () from /var/ossec/bin/../lib/../lib/libstdc++.so.6
#7  0x00007fffefb69ce1 in std::__detail::_Map_base<int, std::pair<int const, std::shared_ptr<Socket<OSPrimitives, AppendHeaderProtocol> > >, std::allocator<std::pair<int const, std::shared_ptr<Socket<OSPrimitives, AppendHeaderProtocol> > > >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::at (this=0x7ffff301c500, __k=@0x7fffdef7b51c: 179) at /usr/local/gcc-9.4.0/include/c++/9.4.0/bits/hashtable_policy.h:750
#8  0x00007fffefb5f2a1 in std::unordered_map<int, std::shared_ptr<Socket<OSPrimitives, AppendHeaderProtocol> >, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, std::shared_ptr<Socket<OSPrimitives, AppendHeaderProtocol> > > > >::at (this=0x7ffff301c500, __k=@0x7fffdef7b51c: 179) at /usr/local/gcc-9.4.0/include/c++/9.4.0/bits/unordered_map.h:1003
#9  0x00007fffefb537ef in SocketServer<Socket<OSPrimitives, AppendHeaderProtocol>, EpollWrapper>::getClient (this=0x7ffff301c4c0, fd=179)
    at /build_wazuh/rpmbuild/BUILD/wazuh-manager-4.8.2/src/shared_modules/utils/socketServer.hpp:46
#10 0x00007fffefb4e62e in SocketServer<Socket<OSPrimitives, AppendHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&)::{lambda()#1}::operator()() const (this=0x7ffff301c4c0) at /build_wazuh/rpmbuild/BUILD/wazuh-manager-4.8.2/src/shared_modules/utils/socketServer.hpp:174
#11 0x00007fffefb8e1be in std::__invoke_impl<void, SocketServer<Socket<OSPrimitives, AppendHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&)::{lambda()#1}>(std::__invoke_other, SocketServer<Socket<OSPrimitives, AppendHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&)::{lambda()#1}&&) (__f=<unknown type in /var/ossec/bin/../lib/../lib/librouter.so, CU 0xd3cb4, DIE 0x16413e>) at /usr/local/gcc-9.4.0/include/c++/9.4.0/bits/invoke.h:60
#12 0x00007fffefb8e06f in std::__invoke<SocketServer<Socket<OSPrimitives, AppendHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&)::{lambda()#1}>(std::__invoke_result&&, (SocketServer<Socket<OSPrimitives, AppendHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&)::{lambda()#1}&&)...) (__fn=<unknown type in /var/ossec/bin/../lib/../lib/librouter.so, CU 0xd3cb4, DIE 0x16444d>) at /usr/local/gcc-9.4.0/include/c++/9.4.0/bits/invoke.h:95
#13 0x00007fffefb8df38 in std::thread::_Invoker<std::tuple<SocketServer<Socket<OSPrimitives, AppendHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x7ffff30c8558) at /usr/local/gcc-9.4.0/include/c++/9.4.0/thread:244
#14 0x00007fffefb8dca4 in std::thread::_Invoker<std::tuple<SocketServer<Socket<OSPrimitives, AppendHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&)::{lambda()#1}> >::operator()() (this=0x7ffff30c8558) at /usr/local/gcc-9.4.0/include/c++/9.4.0/thread:251
#15 0x00007fffefb8da0e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<SocketServer<Socket<OSPrimitives, AppendHeaderProtocol>, EpollWrapper>::listen(std::function<void (int, char const*, unsigned int, char const*, unsigned int)> const&)::{lambda()#1}> > >::_M_run() (this=0x7ffff30c8550) at /usr/local/gcc-9.4.0/include/c++/9.4.0/thread:195
#16 0x00007fffee83d580 in ?? () from /var/ossec/bin/../lib/../lib/libstdc++.so.6
#17 0x00007ffff6292ea5 in start_thread () from /lib64/libpthread.so.0
#18 0x00007ffff5fbbb0d in clone () from /lib64/libc.so.6
```

**Comment by Dwordcito** [comment]
Delayed, waiting target branch.

**Comment by Dwordcito** [comment]
Delayed, waiting target branch.
