### ISSUE TITLE
Release 4.10.0 - Alpha 2 - Workload benchmarks metrics

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#26457]
The following issue aims to run all `workload benchmarks` for the current release candidate, report the results, and open new issues for any encountered errors.

## Workload benchmarks metrics information
|                                               |                                            |
|-----------------------------------------------|--------------------------------------------|
| **Main release candidate issue**              |                       #26425                     |
| **Version**                                   |                4.10.0                            |
| **Release candidate #**                       |               Alpha 2                             |
| **Tag**                                       |              [v4.10.0-alpha2](https://github.com/wazuh/wazuh/tree/v4.10.0-alpha2)                               |
| **Previous Workload benchmarks metrics issue**|          #26204                                  |

## Test configuration
All tests will be run and workload performance metrics will be obtained for the following clustered environment configurations:

|                   |                    |
|-------------------|--------------------|
| **# Agents**      | **# Worker nodes** |
|        50.000           |           25         |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

The pipeline could not be executed due to errors in the testing environment. For a detailed conclusion and report on the cluster performance metrics please refer to [Issue comment](https://github.com/wazuh/wazuh/issues/26457#issuecomment-2434739995).

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @fdalmaup 
- [ ] @wazuh/devel-qa

**Comment by nico-stefani** [comment]
# Update

https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/764/

**Comment by fdalmaup** [comment]
# Update

The two builds run for the `v4.10.0-alpha2` version testing ([765](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/765/) and [768](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/768)) failed with similar errors:

<details><summary>765</summary>

```
[2024-10-21T22:04:44.402Z] [Pipeline] // stage
[2024-10-21T22:04:44.425Z] [Pipeline] stage
[2024-10-21T22:04:44.427Z] [Pipeline] { (Clean workspace)
[2024-10-21T22:04:44.643Z] [Pipeline] cleanWs
[2024-10-21T22:04:44.650Z] [WS-CLEANUP] Deleting project workspace...
[2024-10-21T22:04:44.650Z] [WS-CLEANUP] Deferred wipeout is used...
[2024-10-21T22:04:44.656Z] [WS-CLEANUP] done
[2024-10-21T22:04:44.859Z] [Pipeline] }
[2024-10-21T22:04:45.267Z] [Pipeline] // stage
[2024-10-21T22:04:45.280Z] [Pipeline] }
[2024-10-21T22:04:45.687Z] [Pipeline] // node
[2024-10-21T22:04:45.710Z] [Pipeline] End of Pipeline
[2024-10-21T22:04:45.732Z] Also:   hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-21T22:04:45.732Z] Also:   hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-21T22:04:45.732Z] 		at org.wazuh.ECSTask.run(ECSTask.groovy:219)
[2024-10-21T22:04:45.732Z] 		at ___cps.transform___(Native Method)
[2024-10-21T22:04:45.732Z] 		at jdk.internal.reflect.GeneratedConstructorAccessor2243670.newInstance(Unknown Source)
[2024-10-21T22:04:45.732Z] Also:   hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-21T22:04:45.732Z] 		at org.wazuh.ECSTask.run(ECSTask.groovy:219)
[2024-10-21T22:04:45.732Z] 		at ___cps.transform___(Native Method)
[2024-10-21T22:04:45.732Z] 		at jdk.internal.reflect.GeneratedConstructorAccessor2243670.newInstance(Unknown Source)
[2024-10-21T22:04:45.732Z] Also:   hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-21T22:04:45.732Z] 		at org.wazuh.ECSTask.run(ECSTask.groovy:219)
[2024-10-21T22:04:45.732Z] 		at ___cps.transform___(Native Method)
[2024-10-21T22:04:45.732Z] 		at jdk.internal.reflect.GeneratedConstructorAccessor2243670.newInstance(Unknown Source)
[2024-10-21T22:04:45.732Z] hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-21T22:04:45.732Z] 	at org.wazuh.ECSTask.run(ECSTask.groovy:219)
[2024-10-21T22:04:45.732Z] 	at ___cps.transform___(Native Method)
[2024-10-21T22:04:45.732Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-21T22:04:45.732Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-10-21T22:04:45.732Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-21T22:04:45.732Z] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-10-21T22:04:45.732Z] 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
[2024-10-21T22:04:45.732Z] 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
[2024-10-21T22:04:45.732Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
[2024-10-21T22:04:45.732Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
[2024-10-21T22:04:45.732Z] 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
[2024-10-21T22:04:45.732Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
[2024-10-21T22:04:45.732Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
[2024-10-21T22:04:45.732Z] 	at jdk.internal.reflect.GeneratedMethodAccessor1465.invoke(Unknown Source)
[2024-10-21T22:04:45.732Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-10-21T22:04:45.732Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-10-21T22:04:45.732Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2024-10-21T22:04:45.732Z] 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
[2024-10-21T22:04:45.732Z] 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
[2024-10-21T22:04:45.732Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
[2024-10-21T22:04:45.732Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
[2024-10-21T22:04:45.732Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
[2024-10-21T22:04:45.732Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
[2024-10-21T22:04:45.732Z] 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
[2024-10-21T22:04:45.732Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
[2024-10-21T22:04:45.732Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
[2024-10-21T22:04:45.732Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
[2024-10-21T22:04:45.732Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:403)
[2024-10-21T22:04:45.732Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:97)
[2024-10-21T22:04:45.732Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:315)
[2024-10-21T22:04:45.732Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:279)
[2024-10-21T22:04:45.732Z] 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
[2024-10-21T22:04:45.732Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-10-21T22:04:45.732Z] 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
[2024-10-21T22:04:45.732Z] 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
[2024-10-21T22:04:45.732Z] 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
[2024-10-21T22:04:45.732Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-10-21T22:04:45.732Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-10-21T22:04:45.732Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-10-21T22:04:45.732Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-10-21T22:04:45.732Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-10-21T22:04:45.810Z] Finished: FAILURE
```

</details>


<details><summary>768</summary>

```
[2024-10-23T17:55:53.939Z] [Pipeline] // stage
[2024-10-23T17:55:53.956Z] [Pipeline] stage
[2024-10-23T17:55:53.959Z] [Pipeline] { (Clean workspace)
[2024-10-23T17:55:54.173Z] [Pipeline] cleanWs
[2024-10-23T17:55:54.181Z] [WS-CLEANUP] Deleting project workspace...
[2024-10-23T17:55:54.181Z] [WS-CLEANUP] Deferred wipeout is used...
[2024-10-23T17:55:54.190Z] [WS-CLEANUP] done
[2024-10-23T17:55:54.391Z] [Pipeline] }
[2024-10-23T17:55:54.811Z] [Pipeline] // stage
[2024-10-23T17:55:54.824Z] [Pipeline] }
[2024-10-23T17:55:55.258Z] [Pipeline] // node
[2024-10-23T17:55:55.285Z] [Pipeline] End of Pipeline
[2024-10-23T17:55:55.309Z] Also:   hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-23T17:55:55.309Z] 		at org.wazuh.ECSTask.run(ECSTask.groovy:219)
[2024-10-23T17:55:55.309Z] 		at ___cps.transform___(Native Method)
[2024-10-23T17:55:55.309Z] 		at jdk.internal.reflect.GeneratedConstructorAccessor2243961.newInstance(Unknown Source)
[2024-10-23T17:55:55.309Z] Also:   hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-23T17:55:55.309Z] 		at org.wazuh.ECSTask.run(ECSTask.groovy:219)
[2024-10-23T17:55:55.309Z] 		at ___cps.transform___(Native Method)
[2024-10-23T17:55:55.309Z] 		at jdk.internal.reflect.GeneratedConstructorAccessor2243961.newInstance(Unknown Source)
[2024-10-23T17:55:55.309Z] Also:   hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-23T17:55:55.309Z] 		at org.wazuh.ECSTask.run(ECSTask.groovy:219)
[2024-10-23T17:55:55.309Z] 		at ___cps.transform___(Native Method)
[2024-10-23T17:55:55.309Z] 		at jdk.internal.reflect.GeneratedConstructorAccessor2243961.newInstance(Unknown Source)
[2024-10-23T17:55:55.309Z] Also:   hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-23T17:55:55.309Z] 		at org.wazuh.ECSTask.run(ECSTask.groovy:219)
[2024-10-23T17:55:55.309Z] 		at ___cps.transform___(Native Method)
[2024-10-23T17:55:55.309Z] 		at jdk.internal.reflect.GeneratedConstructorAccessor2243961.newInstance(Unknown Source)
[2024-10-23T17:55:55.309Z] hudson.remoting.ProxyException: org.wazuh.JenkinsException: Error deploying task.
[2024-10-23T17:55:55.309Z] 	at org.wazuh.ECSTask.run(ECSTask.groovy:219)
[2024-10-23T17:55:55.309Z] 	at ___cps.transform___(Native Method)
[2024-10-23T17:55:55.309Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-23T17:55:55.309Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-10-23T17:55:55.309Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-23T17:55:55.309Z] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-10-23T17:55:55.309Z] 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
[2024-10-23T17:55:55.309Z] 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
[2024-10-23T17:55:55.309Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
[2024-10-23T17:55:55.309Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
[2024-10-23T17:55:55.309Z] 	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
[2024-10-23T17:55:55.309Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
[2024-10-23T17:55:55.309Z] 	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
[2024-10-23T17:55:55.309Z] 	at jdk.internal.reflect.GeneratedMethodAccessor1465.invoke(Unknown Source)
[2024-10-23T17:55:55.309Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-10-23T17:55:55.309Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-10-23T17:55:55.309Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2024-10-23T17:55:55.309Z] 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
[2024-10-23T17:55:55.309Z] 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
[2024-10-23T17:55:55.309Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
[2024-10-23T17:55:55.309Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
[2024-10-23T17:55:55.309Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
[2024-10-23T17:55:55.309Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
[2024-10-23T17:55:55.309Z] 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
[2024-10-23T17:55:55.309Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
[2024-10-23T17:55:55.309Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
[2024-10-23T17:55:55.309Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
[2024-10-23T17:55:55.309Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:403)
[2024-10-23T17:55:55.309Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:97)
[2024-10-23T17:55:55.309Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:315)
[2024-10-23T17:55:55.309Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:279)
[2024-10-23T17:55:55.309Z] 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
[2024-10-23T17:55:55.309Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-10-23T17:55:55.309Z] 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
[2024-10-23T17:55:55.309Z] 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
[2024-10-23T17:55:55.309Z] 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
[2024-10-23T17:55:55.309Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-10-23T17:55:55.309Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-10-23T17:55:55.309Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-10-23T17:55:55.309Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-10-23T17:55:55.309Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-10-23T17:55:55.380Z] Finished: FAILURE
```

</details>

These errors were also seen in https://github.com/wazuh/wazuh/issues/26477#issuecomment-2431822550 and the https://github.com/wazuh/wazuh-jenkins/issues/7051 issue was opened to review the pipeline behavior. 

Since it is not related to the platform behavior but to a testing environment problem, the pipeline launch will be carried out in the `Alpha3` stage once this is solved.
