### ISSUE TITLE
Wazuh Agent: Azure integration not working for 4.10.0 Alpha 2 (Azure module execution failure)

### ISSUE THREAD

**Issue by ofvyn** [wazuh/wazuh#26523]
|Wazuh version|Component|Test |Failure type|Description|Install method|
|-------------|-----------|-----------|----------|----------------|--------|
| 4.10.0 Alpha 2 | Wazuh server| Azure integration for Graph & Storage on Wazuh Agent |Error code 1 was thrown for Storage| Same Credentials and similar configurations used for Wazuh server configuration were used but did not work on the agent| Amazon Linux 2 x86_64|

**Comment by fdalmaup** [comment]
# Update

The problem seems to be related to the Python version that needs to be manually installed, e.g. Python 3.8, that does not contain the required SQLite library installed:

```
bash-4.2# /usr/local/bin/python3.8
Python 3.8.12 (default, Oct 28 2024, 15:28:31) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by fdalmaup** [comment]
# Update
Successfully achieved the module's execution after installing Python using the OS `python3.8` package.

<details><summary>Agent system info</summary>

```console
bash-4.2# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```

</details>


<details><summary>Python and dependencies installation</summary>

```
amazon-linux-extras install python3.8 -y
python3.8 -m ensurepip
python3.8 -m pip install --upgrade pip
bash-4.2# python3
Python 3.8.16 (default, May 21 2024, 18:54:47) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
bash-4.2# pip3 install azure-storage-blob==12.20.0 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateutil==2.8.1 requests==2.25.1 certifi==2022.12.07 chardet==3.0.4 idna==2.9 urllib3==1.26.18 SQLAlchemy==2.0.23 pytz==2020.1
Collecting azure-storage-blob==12.20.0
  Downloading azure_storage_blob-12.20.0-py3-none-any.whl.metadata (26 kB)
Collecting azure-storage-common==2.1.0
  Downloading azure_storage_common-2.1.0-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting azure-common==1.1.25
  Downloading azure_common-1.1.25-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting cryptography==3.3.2
  Downloading cryptography-3.3.2-cp36-abi3-manylinux2010_x86_64.whl.metadata (5.1 kB)
Collecting cffi==1.14.4
  Downloading cffi-1.14.4-cp38-cp38-manylinux1_x86_64.whl.metadata (1.2 kB)
Collecting pycparser==2.20
  Downloading pycparser-2.20-py2.py3-none-any.whl.metadata (907 bytes)
Collecting six==1.14.0
  Downloading six-1.14.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting python-dateutil==2.8.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting requests==2.25.1
  Downloading requests-2.25.1-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting certifi==2022.12.07
  Downloading certifi-2022.12.7-py3-none-any.whl.metadata (2.9 kB)
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting idna==2.9
  Downloading idna-2.9-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting urllib3==1.26.18
  Downloading urllib3-1.26.18-py2.py3-none-any.whl.metadata (48 kB)
Collecting SQLAlchemy==2.0.23
  Downloading SQLAlchemy-2.0.23-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting pytz==2020.1
  Downloading pytz-2020.1-py2.py3-none-any.whl.metadata (21 kB)
Collecting azure-core>=1.28.0 (from azure-storage-blob==12.20.0)
  Downloading azure_core-1.31.0-py3-none-any.whl.metadata (39 kB)
Collecting typing-extensions>=4.6.0 (from azure-storage-blob==12.20.0)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting isodate>=0.6.1 (from azure-storage-blob==12.20.0)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Collecting greenlet!=0.4.17 (from SQLAlchemy==2.0.23)
  Downloading greenlet-3.1.1-cp38-cp38-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading azure_storage_blob-12.20.0-py3-none-any.whl (392 kB)
Downloading azure_storage_common-2.1.0-py2.py3-none-any.whl (47 kB)
Downloading azure_common-1.1.25-py2.py3-none-any.whl (12 kB)
Downloading cryptography-3.3.2-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 19.2 MB/s eta 0:00:00
Downloading cffi-1.14.4-cp38-cp38-manylinux1_x86_64.whl (411 kB)
Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
Downloading SQLAlchemy-2.0.23-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 21.4 MB/s eta 0:00:00
Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
Downloading azure_core-1.31.0-py3-none-any.whl (197 kB)
Downloading greenlet-3.1.1-cp38-cp38-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (605 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 606.0/606.0 kB 24.3 MB/s eta 0:00:00
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: pytz, chardet, azure-common, urllib3, typing-extensions, six, pycparser, isodate, idna, greenlet, certifi, SQLAlchemy, requests, python-dateutil, cffi, cryptography, azure-core, azure-storage-common, azure-storage-blob
Successfully installed SQLAlchemy-2.0.23 azure-common-1.1.25 azure-core-1.31.0 azure-storage-blob-12.20.0 azure-storage-common-2.1.0 certifi-2022.12.7 cffi-1.14.4 chardet-3.0.4 cryptography-3.3.2 greenlet-3.1.1 idna-2.9 isodate-0.7.2 pycparser-2.20 python-dateutil-2.8.1 pytz-2020.1 requests-2.25.1 six-1.14.0 typing-extensions-4.12.2 urllib3-1.26.18
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
```

</details>


<details><summary>Wazuh Agent info</summary>

```
bash-4.2# /var/ossec/bin/wazuh-control info 
WAZUH_VERSION="v4.10.0"
WAZUH_REVISION="41003"
WAZUH_TYPE="agent"
```

</details>

<details><summary>ossec.conf</summary>

```
<wodle name="azure-logs">
      <disabled>no</disabled>
      <run_on_start>yes</run_on_start>
      <log_analytics>
          <auth_path>/var/ossec/loganalyticscredentials.txt</auth_path>
          <tenantdomain>wazuh.com</tenantdomain>

          <request>
              <tag>azure-auditlogs</tag>
              <query>AuditLogs</query>
              <workspace>WORKSPACE</workspace>
              <time_offset>1d</time_offset>
          </request>
      </log_analytics>
    
      <graph>

        <auth_path>/var/ossec/graphcredentials.txt</auth_path>
        <tenantdomain>wazuh.com</tenantdomain>

        <request>
            <tag>microsoft-entra_id</tag>
            <query>auditLogs/directoryAudits</query>
            <time_offset>1d</time_offset>
        </request>

      </graph>
  </wodle>
```

</details>


<details><summary>ossec.log</summary>

```
2024/10/29 12:02:02 wazuh-modulesd:azure-logs[6829] wm_azure.c:54 at wm_azure_main(): INFO: Module started.
2024/10/29 12:02:02 wazuh-modulesd:azure-logs[6829] wm_azure.c:74 at wm_azure_main(): INFO: Starting fetching of logs.
2024/10/29 12:02:02 wazuh-modulesd:azure-logs[6829] wm_azure.c:81 at wm_azure_main(): INFO: Starting Log Analytics collection for the domain 'wazuh.com'.
2024/10/29 12:02:02 wazuh-modulesd:azure-logs[6829] wm_azure.c:120 at wm_azure_log_analytics(): DEBUG: Creating argument list.
2024/10/29 12:02:02 wazuh-modulesd:azure-logs[6829] wm_azure.c:172 at wm_azure_log_analytics(): DEBUG: Launching command: wodles/azure/azure-logs --log_analytics --la_auth_path /var/ossec/loganalyticscredentials.txt --la_tenant_domain wazuh.com --la_tag azure-auditlogs --la_query "AuditLogs" --workspace WORKSPACE --la_time_offset 1d --debug 2
2024/10/29 12:02:07 wazuh-modulesd:azure-logs[6829] wm_azure.c:189 at wm_azure_log_analytics(): INFO: Finished Log Analytics collection for request 'azure-auditlogs'.
2024/10/29 12:02:07 wazuh-modulesd:azure-logs[6829] wm_azure.c:83 at wm_azure_main(): INFO: Finished Log Analytics collection for the domain 'wazuh.com'.
2024/10/29 12:02:07 wazuh-modulesd:azure-logs[6829] wm_azure.c:85 at wm_azure_main(): INFO: Starting Graphs log collection for the domain 'wazuh.com'.
2024/10/29 12:02:07 wazuh-modulesd:azure-logs[6829] wm_azure.c:209 at wm_azure_graphs(): DEBUG: Creating argument list.
2024/10/29 12:02:07 wazuh-modulesd:azure-logs[6829] wm_azure.c:259 at wm_azure_graphs(): DEBUG: Launching command: wodles/azure/azure-logs --graph --graph_auth_path /var/ossec/graphcredentials.txt --graph_tenant_domain wazuh.com --graph_tag microsoft-entra_id --graph_query 'auditLogs/directoryAudits' --graph_time_offset 1d --debug 2
2024/10/29 12:02:09 wazuh-modulesd:azure-logs[6829] wm_azure.c:276 at wm_azure_graphs(): INFO: Finished Graphs log collection for request 'microsoft-entra_id'.
2024/10/29 12:02:09 wazuh-modulesd:azure-logs[6829] wm_azure.c:87 at wm_azure_main(): INFO: Finished Graphs log collection for the domain 'wazuh.com'.
2024/10/29 12:02:09 wazuh-modulesd:azure-logs[6829] wm_azure.c:100 at wm_azure_main(): DEBUG: Fetching logs finished.
2024/10/29 12:02:09 wazuh-modulesd:azure-logs[6829] wm_azure.c:70 at wm_azure_main(): DEBUG: Sleeping until: 2024/10/30 12:02:02
```

</details>

Sent events to the Wazuh Server:

```
root@4b1a0eceab51:/# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.10.0"
WAZUH_REVISION="41003"
WAZUH_TYPE="server"
root@4b1a0eceab51:/# grep Azure /var/ossec/logs/archives/archives.log | wc -l     
20
```

## Conclusions

Given the variety of OSs where the Wazuh Agent might be installed, no extensive steps related to the required Python version installation are given. It is up to the user to find the proper steps to achieve the correct installation. Nevertheless, we could modify the output logs when an error arises in the module (`2024/10/23 15:24:03 wazuh-modulesd:azure-logs: ERROR: insights-logs-auditlogs: Returned error code: '1'`).

**Comment by GGP1** [comment]
## Review

The issue was caused by an environment misconfiguration rather than a module bug or dependency conflict. The investigation and execution of the module was successful, there are no changes required from our side. LGTM.

**Comment by RamosFe** [comment]
## Review

The analysis was correctly done, and the error is unrelated to the Azure integration. LGTM
