### ISSUE TITLE
Make Framework and API's installation FHS compliant.

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#26590]
## Description

We need to continue the work done in #26349 making the installation for the server and the API's compatible with the [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html) standard. 

The problem lies in the current way of defining the `WAZUH_PATH`, which is based on searching the framework `directory`. This will soon be obsolete, and we need to define different paths for each purpose.

The proposed hierarchy is:

* Binary files (`wazuh-server`, `wazuh-apid`, `wazuh-comms-apid`) :arrow_right:  `/bin`
* Embedded Python, API's, and server scripts, `installation_uuid` :arrow_right:  `/usr/share/wazuh-server`
* Configuration file (`wazuh-server.yml`), SSL certificates, PEM keys :arrow_right:  `/etc/wazuh-server`
* Cluster and Comms API sockets, PID files :arrow_right:  `/run/wazuh-server`
* Log files :arrow_right:  `/var/log/wazuh-server`
* RBAC DB :arrow_right:  `/var/lib/wazuh-server`

## Plan

- [x] Define the new paths at `framework/wazuh/core/common.py`
- [x] Replace the occurrence of `WAZUH_PATH` with the new paths depending on the case
- [x] Fix the related unit tests after the replacement
- [x] Modify the `src/init/inst-functions.sh` to create the new directories if it does not exist previously.
- [x] Modify the `package/debs/SPECS/debian/rules` and `packages/rpms/SPECS/wazuh-server.spec` to include the new package hierarchy.

**Comment by nico-stefani** [comment]
# Update

I've been replacing the `WAZUH_PATH` with the new file locations in the server and API's code.

**Comment by nico-stefani** [comment]
# Update

I've been continuing with the replacement of `WAZUH_PATH` and I've started to modify the makefiles to make the first testing.

**Comment by nico-stefani** [comment]
# Update

After modifying the installation process the first compliant iteration starts with the new scaffolding. 

```console
[root@ba0300b1abfa pkg]# find / -name wazuh-server -type d
/tmp/wazuh-server
/etc/wazuh-server
/var/log/wazuh-server
/var/lib/wazuh-server
/usr/share/wazuh-server
/run/wazuh-server
```

```console
[root@ba0300b1abfa pkg]# wazuh-server start -rf
Starting cluster in foreground (pid: 9213)
2024/11/04 20:06:30 ERROR: [Cluster] [Main] Error starting wazuh-engined: [Errno 2] No such file or directory: PosixPath('/bin/wazuh-engine')
2024/11/04 20:06:30 INFO: [Cluster] [Main] Started wazuh-apid (pid: 9215)
2024/11/04 20:06:30 INFO: [Cluster] [Main] Started wazuh-comms-apid (pid: 9216)
2024/11/04 20:06:30 ERROR: [Master] [Main] Failed loading SSL context: [SSL] PEM lib (_ssl.c:3900). Using default one.
2024/11/04 20:06:30 INFO: [Local Server] [Main] Serving on /run/wazuh-server/socket/c-internal.sock
2024/11/04 20:06:30 INFO: [Master] [Main] Serving on ('127.0.0.1', 1516)
2024/11/04 20:06:30 INFO: [Master] [Local integrity] Starting.
2024/11/04 20:06:30 INFO: [Master] [Local integrity] Finished in 0.097s. Calculated metadata of 0 files.
2024/11/04 20:06:31 INFO: Starting API in foreground
2024/11/04 20:06:31 INFO: Starting API as root
2024/11/04 20:06:31 INFO: Checking RBAC database integrity...
2024/11/04 20:06:31 INFO: /etc/wazuh-server/api/configuration/security/rbac.db file was detected
2024/11/04 20:06:31 INFO: RBAC database integrity check finished successfully
2024/11/04 20:06:31 INFO: Starting API in foreground
2024/11/04 20:06:31 INFO: Starting API as root
2024/11/04 20:06:31 INFO: Listening on 0.0.0.0:27000
2024/11/04 20:06:31 INFO: Starting gunicorn 22.0.0
2024/11/04 20:06:31 INFO: Listening at: https://0.0.0.0:27000 (9216)
2024/11/04 20:06:31 INFO: Using worker: uvicorn.workers.UvicornWorker
2024/11/04 20:06:31 INFO: Booting worker with pid: 9266
2024/11/04 20:06:31 INFO: Booting worker with pid: 9267
2024/11/04 20:06:31 INFO: Booting worker with pid: 9268
2024/11/04 20:06:31 INFO: Started server process [9216]
2024/11/04 20:06:31 INFO: Waiting for application startup.
2024/11/04 20:06:31 INFO: Application startup complete.
2024/11/04 20:06:31 INFO: Uvicorn running on unix socket /run/wazuh-server/socket/comms-api.sock (Press CTRL+C to quit)
2024/11/04 20:06:31 INFO: Booting worker with pid: 9269
2024/11/04 20:06:31 INFO: Started server process [9269]
2024/11/04 20:06:31 INFO: Waiting for application startup.
2024/11/04 20:06:31 INFO: Application startup complete.
Failed to add operation for GET /lists
2024/11/04 20:06:38 INFO: [Master] [Local integrity] Starting.
2024/11/04 20:06:38 INFO: [Master] [Local integrity] Finished in 0.002s. Calculated metadata of 0 files.
```

**Comment by nico-stefani** [comment]
# Update

I've been working on improvements over the first approach to replace WAZUH_PATH.
Now I'm having trouble syncing files in a cluster environment.

```console
2024/11/05 21:20:17 INFO: [Worker] [Main] Connection from ('172.18.0.2', 54260)
2024/11/05 21:20:17 INFO: [Master] [Local integrity] Starting.
2024/11/05 21:20:17 INFO: [Master] [Local integrity] Finished in 0.001s. Calculated metadata of 0 files.
2024/11/05 21:20:25 INFO: [Master] [Local integrity] Starting.
2024/11/05 21:20:25 INFO: [Master] [Local integrity] Finished in 0.002s. Calculated metadata of 0 files.
2024/11/05 21:20:26 INFO: [Worker worker1] [Integrity check] Starting.
2024/11/05 21:20:26 ERROR: [Worker worker1] [Main] Unhandled error processing request 'b'new_file'': [Errno 2] No such file or directory: '/queue/cluster/worker1/worker1-1730841626.271349-33d1ba5b01a1468ebabe2c50f6f2759c.zip'
Traceback (most recent call last):
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 585, in dispatch
    command, payload = self.process_request(command, payload)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/master.py", line 201, in process_request
    return super().process_request(command, data)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/server.py", line 104, in process_request
    return super().process_request(command, data)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 622, in process_request
    return self.receive_file(data)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 718, in receive_file
    self.in_file[data] = {'fd': open(common.WAZUH_RUN / data.decode(), 'wb'), 'checksum': hashlib.sha256()}
FileNotFoundError: [Errno 2] No such file or directory: '/queue/cluster/worker1/worker1-1730841626.271349-33d1ba5b01a1468ebabe2c50f6f2759c.zip'
```

**Comment by nico-stefani** [comment]
# Update

I've been able to get up and running the cluster, with one worker, and it is working correctly the Integrity checks.

* Master

```console
2024/11/06 18:41:15 INFO: [Cluster] [Main] Started wazuh-engined (pid: 320867)
2024/11/06 18:41:16 INFO: [Cluster] [Main] Started wazuh-apid (pid: 320909)
2024/11/06 18:41:17 INFO: [Cluster] [Main] Started wazuh-comms-apid (pid: 320996)
2024/11/06 18:41:18 INFO: [Local Server] [Main] Serving on /run/wazuh-server/socket/c-internal.sock
2024/11/06 18:41:18 INFO: [Master] [Main] Serving on ('0.0.0.0', 1516)
2024/11/06 18:41:18 INFO: [Master] [Local integrity] Starting.
2024/11/06 18:41:18 INFO: [Master] [Local integrity] Finished in 0.100s. Calculated metadata of 2 files.
2024/11/06 18:41:22 INFO: [Worker] [Main] Connection from ('172.18.0.2', 60458)
2024/11/06 18:41:26 INFO: [Master] [D API] Receiving request: check_token from worker1 (823772)
2024/11/06 18:41:26 INFO: [Master] [D API] Receiving request: get_security_conf from worker1 (680032)
2024/11/06 18:41:26 INFO: [Master] [D API] Receiving request: get_agent_groups from worker1 (560720)
2024/11/06 18:41:26 INFO: [Master] [Local integrity] Starting.
2024/11/06 18:41:26 INFO: [Master] [Local integrity] Finished in 0.003s. Calculated metadata of 2 files.
2024/11/06 18:41:31 INFO: [Worker worker1] [Integrity check] Starting.
2024/11/06 18:41:31 INFO: [Worker worker1] [Integrity check] Finished in 0.004s. Received metadata of 2 files. Sync not required.
2024/11/06 18:41:32 INFO: [Cluster] [Main] Shutting down wazuh-engined (pid: 320867)
2024/11/06 18:41:32 INFO: [Cluster] [Main] Shutting down wazuh-apid (pid: 320909)
2024/11/06 18:41:32 INFO: [Cluster] [Main] Shutting down wazuh-comms-apid (pid: 320996)

2024/11/06 18:41:16 INFO: Starting API as root
2024/11/06 18:41:16 INFO: Checking RBAC database integrity...
2024/11/06 18:41:16 INFO: /var/lib/wazuh-server/rbac.db file was detected
2024/11/06 18:41:16 INFO: RBAC database integrity check finished successfully
2024/11/06 18:41:19 INFO: Listening on 0.0.0.0:55000.
2024/11/06 18:41:19 INFO: Getting installation UID...
2024/11/06 18:41:19 INFO: Getting updates information...
2024/11/06 18:41:23 INFO: wazuh 172.18.0.1 "GET /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.247s: 200
2024/11/06 18:41:32 INFO: Shutdown wazuh-apid server.

2024/11/06 18:41:17 INFO: Starting API as root
2024/11/06 18:41:17 INFO: Listening on 0.0.0.0:27000
2024/11/06 18:41:17 INFO: Starting gunicorn 22.0.0
2024/11/06 18:41:17 INFO: Listening at: https://0.0.0.0:27000 (320996)
2024/11/06 18:41:17 INFO: Using worker: uvicorn.workers.UvicornWorker
2024/11/06 18:41:17 INFO: Booting worker with pid: 321032
2024/11/06 18:41:17 INFO: Started server process [320996]
2024/11/06 18:41:17 INFO: Waiting for application startup.
2024/11/06 18:41:17 INFO: Application startup complete.
2024/11/06 18:41:17 INFO: Uvicorn running on unix socket /run/wazuh-server/socket/comms-api.sock (Press CTRL+C to quit)
2024/11/06 18:41:17 INFO: Booting worker with pid: 321033
2024/11/06 18:41:17 INFO: Started server process [321033]
2024/11/06 18:41:17 INFO: Waiting for application startup.
2024/11/06 18:41:17 INFO: Application startup complete.
2024/11/06 18:41:17 INFO: Booting worker with pid: 321034
2024/11/06 18:41:17 INFO: Started server process [321034]
2024/11/06 18:41:17 INFO: Waiting for application startup.
2024/11/06 18:41:17 INFO: Application startup complete.
2024/11/06 18:41:17 INFO: Booting worker with pid: 321035
2024/11/06 18:41:17 INFO: Started server process [321035]
2024/11/06 18:41:17 INFO: Waiting for application startup.
2024/11/06 18:41:17 INFO: Application startup complete.
2024/11/06 18:41:32 INFO: Handling signal: term
2024/11/06 18:41:32 ERROR: Worker (pid:321032) was sent SIGTERM!
2024/11/06 18:41:32 INFO: Shutting down
2024/11/06 18:41:32 INFO: Error while closing socket [Errno 9] Bad file descriptor
2024/11/06 18:41:32 INFO: Shutting down
2024/11/06 18:41:32 INFO: Error while closing socket [Errno 9] Bad file descriptor
2024/11/06 18:41:32 INFO: Shutting down
2024/11/06 18:41:32 INFO: Error while closing socket [Errno 9] Bad file descriptor
2024/11/06 18:41:32 INFO: Waiting for application shutdown.
2024/11/06 18:41:32 INFO: Application shutdown complete.
2024/11/06 18:41:32 INFO: Finished server process [321035]
2024/11/06 18:41:32 INFO: Worker exiting (pid: 321035)
2024/11/06 18:41:32 INFO: Waiting for application shutdown.
2024/11/06 18:41:32 INFO: Application shutdown complete.
2024/11/06 18:41:32 INFO: Finished server process [321033]
2024/11/06 18:41:32 INFO: Worker exiting (pid: 321033)
2024/11/06 18:41:32 INFO: Waiting for application shutdown.
2024/11/06 18:41:32 INFO: Application shutdown complete.
2024/11/06 18:41:32 INFO: Finished server process [321034]
2024/11/06 18:41:32 INFO: Worker exiting (pid: 321034)
2024/11/06 18:41:32 INFO: Shutting down: Master
2024/11/06 18:41:32 INFO: Shutting down
2024/11/06 18:41:32 INFO: Batcher (pid: 321017) - Received signal SIGTERM, shutting down
2024/11/06 18:41:32 INFO: MuxDemuxQueue (pid: 321014) - Received signal SIGTERM, shutting down
```

* Worker

```console
2024/11/06 18:41:19 INFO: [Cluster] [Main] Started wazuh-engined (pid: 330825)
2024/11/06 18:41:20 INFO: [Cluster] [Main] Started wazuh-apid (pid: 330943)
2024/11/06 18:41:21 INFO: [Cluster] [Main] Started wazuh-comms-apid (pid: 330965)
2024/11/06 18:41:22 INFO: [Local Server] [Main] Serving on /run/wazuh-server/socket/c-internal.sock
2024/11/06 18:41:22 INFO: [Worker worker1] [Main] Successfully connected to master.
2024/11/06 18:41:31 INFO: [Worker worker1] [Integrity check] Starting.
2024/11/06 18:41:31 INFO: [Worker worker1] [Integrity check] Finished in 0.011s. Sync not required.
2024/11/06 18:41:32 INFO: [Worker worker1] [Main] The master closed the connection
2024/11/06 18:41:35 INFO: [Cluster] [Main] Shutting down wazuh-engined (pid: 330825)
2024/11/06 18:41:35 INFO: [Cluster] [Main] Shutting down wazuh-apid (pid: 330943)
2024/11/06 18:41:35 INFO: [Cluster] [Main] Shutting down wazuh-comms-apid (pid: 330965)

2024/11/06 18:41:20 INFO: Starting API as root
2024/11/06 18:41:20 INFO: Checking RBAC database integrity...
2024/11/06 18:41:20 INFO: /var/lib/wazuh-server/rbac.db file was detected
2024/11/06 18:41:20 INFO: RBAC database integrity check finished successfully
2024/11/06 18:41:23 INFO: Listening on 0.0.0.0:55000.
2024/11/06 18:41:26 INFO: wazuh 172.18.0.1 "GET /groups" with parameters {"pretty": "true"} and body {} done in 0.098s: 200
2024/11/06 18:41:35 INFO: Shutdown wazuh-apid server.

2024/11/06 18:41:21 INFO: Starting API as root
2024/11/06 18:41:21 INFO: Listening on 0.0.0.0:27000
2024/11/06 18:41:21 INFO: Starting gunicorn 22.0.0
2024/11/06 18:41:21 INFO: Listening at: https://0.0.0.0:27000 (330965)
2024/11/06 18:41:21 INFO: Using worker: uvicorn.workers.UvicornWorker
2024/11/06 18:41:21 INFO: Booting worker with pid: 331001
2024/11/06 18:41:21 INFO: Started server process [330965]
2024/11/06 18:41:21 INFO: Waiting for application startup.
2024/11/06 18:41:21 INFO: Application startup complete.
2024/11/06 18:41:21 INFO: Uvicorn running on unix socket /run/wazuh-server/socket/comms-api.sock (Press CTRL+C to quit)
2024/11/06 18:41:21 INFO: Booting worker with pid: 331002
2024/11/06 18:41:21 INFO: Started server process [331002]
2024/11/06 18:41:21 INFO: Waiting for application startup.
2024/11/06 18:41:21 INFO: Application startup complete.
2024/11/06 18:41:21 INFO: Booting worker with pid: 331003
2024/11/06 18:41:21 INFO: Started server process [331003]
2024/11/06 18:41:21 INFO: Waiting for application startup.
2024/11/06 18:41:21 INFO: Application startup complete.
2024/11/06 18:41:21 INFO: Booting worker with pid: 331004
2024/11/06 18:41:21 INFO: Started server process [331004]
2024/11/06 18:41:21 INFO: Waiting for application startup.
2024/11/06 18:41:21 INFO: Application startup complete.
2024/11/06 18:41:35 INFO: Handling signal: term
2024/11/06 18:41:35 ERROR: Worker (pid:331001) was sent SIGTERM!
2024/11/06 18:41:35 INFO: Shutting down
2024/11/06 18:41:35 INFO: Error while closing socket [Errno 9] Bad file descriptor
2024/11/06 18:41:35 INFO: Shutting down
2024/11/06 18:41:35 INFO: Error while closing socket [Errno 9] Bad file descriptor
2024/11/06 18:41:35 INFO: Shutting down
2024/11/06 18:41:35 INFO: Error while closing socket [Errno 9] Bad file descriptor
2024/11/06 18:41:35 INFO: Waiting for application shutdown.
2024/11/06 18:41:35 INFO: Application shutdown complete.
2024/11/06 18:41:35 INFO: Finished server process [331003]
2024/11/06 18:41:35 INFO: Worker exiting (pid: 331003)
2024/11/06 18:41:35 INFO: Waiting for application shutdown.
2024/11/06 18:41:35 INFO: Application shutdown complete.
2024/11/06 18:41:35 INFO: Finished server process [331004]
2024/11/06 18:41:35 INFO: Worker exiting (pid: 331004)
2024/11/06 18:41:35 INFO: Waiting for application shutdown.
2024/11/06 18:41:35 INFO: Application shutdown complete.
2024/11/06 18:41:35 INFO: Finished server process [331002]
2024/11/06 18:41:35 INFO: Worker exiting (pid: 331002)
2024/11/06 18:41:36 INFO: Shutting down: Master
2024/11/06 18:41:36 INFO: Shutting down
2024/11/06 18:41:36 INFO: MuxDemuxQueue (pid: 330983) - Received signal SIGTERM, shutting down
2024/11/06 18:41:36 INFO: Batcher (pid: 330987) - Received signal SIGTERM, shutting down
```

* Requests

```
➜  ~ TOKEN=$(curl --silent -u wazuh:wazuh -k -X GET "https://localhost:55050/security/user/authenticate?raw=true")
➜  ~ curl -H "Authorization: Bearer $TOKEN" -X GET -k https://localhost:55051/groups\?pretty\=true
{
   "data": {
      "affected_items": [],
      "total_affected_items": 0,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "No group information was returned",
   "error": 0
}
```

**Comment by nico-stefani** [comment]
# Update

I've been fixing the unit tests and have achieved most of the `wazuh/core/cluster` so far. 

```console
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.1.2, pluggy-1.5.0
rootdir: /home/nstefani/git/wazuh/framework, configfile: pytest.ini
plugins: asyncio-0.18.1, tavern-1.23.5, html-3.1.1, trio-0.8.0, anyio-4.1.0, metadata-3.1.1, cov-4.1.0
asyncio: mode=auto
collected 480 items

framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................... [  3%]
..........                                                               [  6%]
framework/wazuh/core/cluster/hap_helper/tests/test_hap_helper.py ....... [  7%]
................................................                         [ 17%]
framework/wazuh/core/cluster/hap_helper/tests/test_proxy.py ............ [ 20%]
........................................................................ [ 35%]
.....................                                                    [ 39%]
framework/wazuh/core/cluster/hap_helper/tests/test_wazuh.py ..........   [ 41%]
framework/wazuh/core/cluster/tests/test_client.py ................       [ 44%]
framework/wazuh/core/cluster/tests/test_cluster.py ..................... [ 49%]
.............                                                            [ 51%]
framework/wazuh/core/cluster/tests/test_common.py ...................... [ 56%]
..............................................                           [ 66%]
framework/wazuh/core/cluster/tests/test_control.py .......               [ 67%]
framework/wazuh/core/cluster/tests/test_local_client.py ..............   [ 70%]
framework/wazuh/core/cluster/tests/test_local_server.py ................ [ 73%]
..........                                                               [ 75%]
framework/wazuh/core/cluster/tests/test_master.py ...................... [ 80%]
........x.........                                                       [ 84%]
framework/wazuh/core/cluster/tests/test_server.py ...................... [ 88%]
.......                                                                  [ 90%]
framework/wazuh/core/cluster/tests/test_utils.py ....................... [ 95%]
....                                                                     [ 95%]
framework/wazuh/core/cluster/tests/test_worker.py ...............x....   [100%]

================= 478 passed, 2 xfailed, 9 warnings in 12.87s ==================

```

**Comment by nico-stefani** [comment]
# Update

I've complete the fixing of the `framework/` UT's

<details><summary>Full Output</summary>
<p>

```console
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.1.2, pluggy-1.5.0
rootdir: /home/nstefani/git/wazuh/framework, configfile: pytest.ini
plugins: asyncio-0.18.1, tavern-1.23.5, html-3.1.1, trio-0.8.0, anyio-4.1.0, metadata-3.1.1, cov-4.1.0
asyncio: mode=auto
collected 2316 items / 4 skipped

framework/scripts/tests/test_agent_upgrade.py ................           [  0%]
framework/scripts/tests/test_rbac_control.py .........                   [  1%]
framework/scripts/tests/test_wazuh_server.py .....................       [  1%]
framework/wazuh/core/batcher/tests/test_buffer.py ...........            [  2%]
framework/wazuh/core/batcher/tests/test_client.py ...                    [  2%]
framework/wazuh/core/batcher/tests/test_mux_demux.py .........           [  2%]
framework/wazuh/core/batcher/tests/test_timer.py ...                     [  3%]
framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................... [  3%]
..........                                                               [  4%]
framework/wazuh/core/cluster/hap_helper/tests/test_hap_helper.py ....... [  4%]
................................................                         [  6%]
framework/wazuh/core/cluster/hap_helper/tests/test_proxy.py ............ [  7%]
........................................................................ [ 10%]
.....................                                                    [ 11%]
framework/wazuh/core/cluster/hap_helper/tests/test_wazuh.py ..........   [ 11%]
framework/wazuh/core/cluster/tests/test_client.py ................       [ 12%]
framework/wazuh/core/cluster/tests/test_cluster.py ..................... [ 13%]
.............                                                            [ 13%]
framework/wazuh/core/cluster/tests/test_common.py ...................... [ 14%]
..............................................                           [ 16%]
framework/wazuh/core/cluster/tests/test_control.py .......               [ 17%]
framework/wazuh/core/cluster/tests/test_local_client.py ..............   [ 17%]
framework/wazuh/core/cluster/tests/test_local_server.py ................ [ 18%]
..........                                                               [ 18%]
framework/wazuh/core/cluster/tests/test_master.py ...................... [ 19%]
........x.........                                                       [ 20%]
framework/wazuh/core/cluster/tests/test_server.py ...................... [ 21%]
.......                                                                  [ 21%]
framework/wazuh/core/cluster/tests/test_utils.py ....................... [ 22%]
....                                                                     [ 22%]
framework/wazuh/core/cluster/tests/test_worker.py ...............x....   [ 23%]
framework/wazuh/core/engine/tests/test_base.py ..                        [ 23%]
framework/wazuh/core/engine/tests/test_events.py .                       [ 23%]
framework/wazuh/core/engine/tests/test_init.py .........                 [ 24%]
framework/wazuh/core/engine/tests/test_vulnerability.py .                [ 24%]
framework/wazuh/core/indexer/models/test/test_commands.py .              [ 24%]
framework/wazuh/core/indexer/tests/test_agent.py .............           [ 25%]
framework/wazuh/core/indexer/tests/test_base.py ...                      [ 25%]
framework/wazuh/core/indexer/tests/test_bulk.py ...........              [ 25%]
framework/wazuh/core/indexer/tests/test_commands.py ......               [ 25%]
framework/wazuh/core/indexer/tests/test_init.py ..............           [ 26%]
framework/wazuh/core/indexer/tests/test_models.py ......                 [ 26%]
framework/wazuh/core/indexer/tests/test_utils.py ....                    [ 26%]
framework/wazuh/core/tests/test_agent.py ............................... [ 28%]
........................................................................ [ 31%]
...............................                                          [ 32%]
framework/wazuh/core/tests/test_authentication.py .....                  [ 32%]
framework/wazuh/core/tests/test_common.py ........xx                     [ 33%]
framework/wazuh/core/tests/test_configuration.py ..............x...xxxxx [ 34%]
xxxxxxxxxxxxxxxxxxxxxxxxxx.................................              [ 36%]
framework/wazuh/core/tests/test_decoder.py ................              [ 37%]
framework/wazuh/core/tests/test_exception.py ..........                  [ 37%]
framework/wazuh/core/tests/test_input_validator.py ...                   [ 38%]
framework/wazuh/core/tests/test_logtest.py ...                           [ 38%]
framework/wazuh/core/tests/test_manager.py ............................. [ 39%]
...                                                                      [ 39%]
framework/wazuh/core/tests/test_mitre.py .............                   [ 40%]
framework/wazuh/core/tests/test_pyDaemonModule.py .........              [ 40%]
framework/wazuh/core/tests/test_results.py ............................. [ 41%]
...........                                                              [ 42%]
framework/wazuh/core/tests/test_rootcheck.py .............               [ 42%]
framework/wazuh/core/tests/test_rule.py ...................xx..          [ 43%]
framework/wazuh/core/tests/test_sca.py .............................     [ 45%]
framework/wazuh/core/tests/test_security.py .............                [ 45%]
framework/wazuh/core/tests/test_stats.py ..........................      [ 46%]
framework/wazuh/core/tests/test_syscheck.py .......                      [ 47%]
framework/wazuh/core/tests/test_syscollector.py ...                      [ 47%]
framework/wazuh/core/tests/test_task.py ........                         [ 47%]
framework/wazuh/core/tests/test_utils.py ............................... [ 48%]
........................................................................ [ 52%]
........................................................................ [ 55%]
........................................................................ [ 58%]
.....................................................                    [ 60%]
framework/wazuh/core/tests/test_wazuh_queue.py .......................   [ 61%]
framework/wazuh/core/tests/test_wazuh_socket.py ........................ [ 62%]
........                                                                 [ 62%]
framework/wazuh/core/tests/test_wdb.py ...............................   [ 64%]
framework/wazuh/core/tests/test_wlogging.py .................            [ 64%]
framework/wazuh/rbac/tests/test_auth_context.py ..                       [ 65%]
framework/wazuh/rbac/tests/test_decorators.py .......................... [ 66%]
........................................................................ [ 69%]
...........                                                              [ 69%]
framework/wazuh/rbac/tests/test_default_configuration.py ............... [ 70%]
.............................................                            [ 72%]
framework/wazuh/rbac/tests/test_orm.py ................................. [ 73%]
...........................................................              [ 76%]
framework/wazuh/rbac/tests/test_preprocessor.py ...........              [ 76%]
framework/wazuh/tests/test_agent.py sssssssss...s.................ss.... [ 78%]
...........................ssssssssss....ssssssssssss.........           [ 81%]
framework/wazuh/tests/test_ciscat.py sssssssssssssssssssssssssssssssss   [ 82%]
framework/wazuh/tests/test_cluster.py .......sss                         [ 82%]
framework/wazuh/tests/test_decoder.py .................................. [ 84%]
........................                                                 [ 85%]
framework/wazuh/tests/test_event.py ....                                 [ 85%]
framework/wazuh/tests/test_logtest.py ......                             [ 85%]
framework/wazuh/tests/test_manager.py .................................. [ 87%]
..                                                                       [ 87%]
framework/wazuh/tests/test_mitre.py .......                              [ 87%]
framework/wazuh/tests/test_order.py ..                                   [ 87%]
framework/wazuh/tests/test_rootcheck.py sssss........................... [ 89%]
..................                                                       [ 89%]
framework/wazuh/tests/test_rule.py ..................................... [ 91%]
.....................................                                    [ 93%]
framework/wazuh/tests/test_sca.py sssssssssss                            [ 93%]
framework/wazuh/tests/test_security.py ................................. [ 95%]
......................................                                   [ 96%]
framework/wazuh/tests/test_stats.py ............sss                      [ 97%]
framework/wazuh/tests/test_syscheck.py ssssssss..............            [ 98%]
framework/wazuh/tests/test_syscollector.py ssssssssssss                  [ 98%]
framework/wazuh/tests/test_task.py ............................          [100%]

==== 2169 passed, 113 skipped, 38 xfailed, 11 warnings in 388.90s (0:06:28) ====
```

</p>
</details> 

Also, I've opened #26770 to address particular issues of the test cases.

**Comment by nico-stefani** [comment]
# Update

Fixed unit tests for MAPI and CAPI

```console
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.1.2, pluggy-1.5.0
rootdir: /home/nstefani/git/wazuh/api/api, configfile: pytest.ini
plugins: asyncio-0.18.1, tavern-1.23.5, html-3.1.1, trio-0.8.0, anyio-4.1.0, metadata-3.1.1, cov-4.1.0
asyncio: mode=auto
collected 604 items

api/api/controllers/test/test_active_response_controller.py .            [  0%]
api/api/controllers/test/test_agent_controller.py ..........s........... [  3%]
............                                                             [  5%]
api/api/controllers/test/test_cdb_list_controller.py ......              [  6%]
api/api/controllers/test/test_ciscat_controller.py .                     [  6%]
api/api/controllers/test/test_cluster_controller.py .................... [ 10%]
....                                                                     [ 10%]
api/api/controllers/test/test_controller_util.py ..                      [ 11%]
api/api/controllers/test/test_decoder_controller.py .......              [ 12%]
api/api/controllers/test/test_default_controller.py .                    [ 12%]
api/api/controllers/test/test_event_controller.py .                      [ 12%]
api/api/controllers/test/test_experimental_controller.py ............... [ 15%]
                                                                         [ 15%]
api/api/controllers/test/test_manager_controller.py .................... [ 18%]
.                                                                        [ 18%]
api/api/controllers/test/test_mitre_controller.py .......                [ 19%]
api/api/controllers/test/test_order_controller.py .                      [ 20%]
api/api/controllers/test/test_overview_controller.py .                   [ 20%]
api/api/controllers/test/test_rootcheck_controller.py ....               [ 20%]
api/api/controllers/test/test_rule_controller.py ........                [ 22%]
api/api/controllers/test/test_sca_controller.py ..                       [ 22%]
api/api/controllers/test/test_security_controller.py ................... [ 25%]
................................                                         [ 30%]
api/api/controllers/test/test_syscheck_controller.py ....                [ 31%]
api/api/controllers/test/test_syscollector_controller.py .........       [ 33%]
api/api/controllers/test/test_task_controller.py .                       [ 33%]
api/api/models/test/test_model.py ..............................         [ 38%]
api/api/test/test_alogging.py ...............                            [ 40%]
api/api/test/test_authentication.py ........                             [ 42%]
api/api/test/test_configuration.py ..................................... [ 48%]
...........                                                              [ 50%]
api/api/test/test_encoder.py ....                                        [ 50%]
api/api/test/test_error_handler.py ............................          [ 55%]
api/api/test/test_middlewares.py ...................................     [ 61%]
api/api/test/test_signals.py .........                                   [ 62%]
api/api/test/test_uri_parser.py ..........                               [ 64%]
api/api/test/test_util.py .........................................      [ 71%]
api/api/test/test_validator.py ......................................... [ 77%]
........................................................................ [ 89%]
..............................................................           [100%]

================== 603 passed, 1 skipped, 9 warnings in 8.02s ==================
```

```console

```
