### ISSUE TITLE
Create user for Wazuh Server installations

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#26908]
# Description

Currently, the `wazuh-server` binary is required to be run exclusively as `root` to work as expected:
<details>

```console
root@f0162426eefc:/# wazuh-server start -rf
2024/11/19 11:05:06 DEBUG: [Cluster] [Main] Removing '/run/wazuh-server/cluster/'.
2024/11/19 11:05:06 DEBUG: [Cluster] [Main] Removed '/run/wazuh-server/cluster/'.
Starting cluster in foreground (pid: 29)
2024/11/19 11:05:06 INFO: [Cluster] [Main] Generating JWT signing key pair
2024/11/19 11:05:06 INFO: [Cluster] [Main] Started wazuh-engined (pid: 30)
2024/11/19 11:05:06 INFO: [Cluster] [Main] Started wazuh-apid (pid: 31)
2024/11/19 11:05:06 INFO: [Cluster] [Main] Started wazuh-comms-apid (pid: 32)
2024/11/19 11:05:07 INFO: [Local Server] [Main] Serving on /run/wazuh-server/socket/local-server.sock
2024/11/19 11:05:07 DEBUG: [Local Server] [Keep alive] Calculating.
2024/11/19 11:05:07 DEBUG: [Local Server] [Keep alive] Calculated.
2024/11/19 11:05:07 INFO: [Master] [Main] Serving on ('::1', 1516, 0, 0)
2024/11/19 11:05:07 DEBUG: [Master] [Keep alive] Calculating.
2024/11/19 11:05:07 DEBUG: [Master] [Keep alive] Calculated.
2024/11/19 11:05:07 INFO: [Master] [Local integrity] Starting.
2024/11/19 11:05:07 INFO: [Master] [Local integrity] Finished in 0.097s. Calculated metadata of 0 files.
2024/11/19 11:05:07 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2024/11/19 11:05:07 INFO: Generated private key file in /etc/wazuh-server/api/configuration/ssl/server.key
2024/11/19 11:05:07 INFO: Generated certificate file in /etc/wazuh-server/api/configuration/ssl/server.crt
2024/11/19 11:05:07 INFO: Starting API in foreground
2024/11/19 11:05:07 INFO: Starting API as root
2024/11/19 11:05:07 INFO: Checking RBAC database integrity...
2024/11/19 11:05:07 INFO: RBAC database not found. Initializing
2024/11/19 11:05:07 INFO: Starting API in foreground
2024/11/19 11:05:07 INFO: Starting API as root
2024/11/19 11:05:07 INFO: Listening on 0.0.0.0:27000
2024/11/19 11:05:07 INFO: Starting gunicorn 22.0.0
2024/11/19 11:05:07 INFO: Listening at: https://127.0.0.1:27000 (32)
2024/11/19 11:05:07 INFO: Using worker: uvicorn.workers.UvicornWorker
2024/11/19 11:05:07 INFO: Booting worker with pid: 445
2024/11/19 11:05:07 INFO: Booting worker with pid: 446
2024/11/19 11:05:07 INFO: Started server process [32]
2024/11/19 11:05:07 INFO: Waiting for application startup.
2024/11/19 11:05:07 INFO: Application startup complete.
2024/11/19 11:05:07 INFO: Uvicorn running on unix socket /run/wazuh-server/socket/comms-api.sock (Press CTRL+C to quit)
2024/11/19 11:05:07 INFO: Booting worker with pid: 447
2024/11/19 11:05:08 INFO: Started server process [447]
2024/11/19 11:05:08 INFO: Waiting for application startup.
2024/11/19 11:05:08 INFO: Application startup complete.
2024/11/19 11:05:08 INFO: Booting worker with pid: 448
2024/11/19 11:05:08 INFO: Started server process [448]
2024/11/19 11:05:08 INFO: Waiting for application startup.
2024/11/19 11:05:08 INFO: Application startup complete.
2024/11/19 11:05:08 INFO: /var/lib/wazuh-server/rbac.db database created successfully
2024/11/19 11:05:08 INFO: RBAC database integrity check finished successfully
2024/11/19 11:05:11 INFO: Listening on ['0.0.0.0', '::']:55000.
2024/11/19 11:05:11 INFO: Populating installation UID...
2024/11/19 11:05:11 INFO: Getting updates information...
```

</details>

If not, the execution fails:

```console
root@42e2ccd7b782:/# wazuh-server start -f
2024/11/19 11:16:30 DEBUG: [Cluster] [Main] Removing '/run/wazuh-server/cluster/'.
2024/11/19 11:16:30 DEBUG: [Cluster] [Main] Removed '/run/wazuh-server/cluster/'.
Traceback (most recent call last):
  File "/usr/share/wazuh-server/framework/scripts/wazuh_server.py", line 443, in <module>
  File "/usr/share/wazuh-server/framework/scripts/wazuh_server.py", line 368, in main
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/pyDaemonModule.py", line 77, in create_pid
PermissionError: [Errno 13] Permission denied: '/run/wazuh-server/wazuh-server-26.pid'
```

Therefore, we need to:
- [x] Generate the `wazuh-server` user and group at installation time for it to be the one to run the server process by default, without requiring the execution to be with the `root` user. This means the generated and installed resources must belong to the mentioned user. 
- [x] Review every command that can be used with the `wazuh-server` binary (`start`, `stop`, `status`) and their behavior with the new `wazuh-server` user.

**Comment by nico-stefani** [comment]
After the changes introduced in 9b9c6c462056cdee518a63dabbae3a8e43f25bef, I've been able to execute the Wazuh server without the  `-r` flag.

```console
[root@2b56352e5a91 wazuh]# wazuh-server start -f
2024/11/19 20:51:55 DEBUG: [Cluster] [Main] Removing '/run/wazuh-server/cluster/'.
2024/11/19 20:51:55 DEBUG: [Cluster] [Main] Removed '/run/wazuh-server/cluster/'.
Starting cluster in foreground (pid: 578)
2024/11/19 20:51:55 ERROR: [Cluster] [Main] Error starting wazuh-engined: [Errno 2] No such file or directory: PosixPath('/bin/wazuh-engine')
Traceback (most recent call last):
  File "/usr/share/wazuh-server/framework/scripts/wazuh_server.py", line 98, in start_daemon
    p = subprocess.Popen(args)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/bin/wazuh-engine')
2024/11/19 20:51:55 INFO: [Cluster] [Main] Started wazuh-apid (pid: 580)
2024/11/19 20:51:55 INFO: [Cluster] [Main] Started wazuh-comms-apid (pid: 581)
2024/11/19 20:51:55 ERROR: [Master] [Main] Failed loading SSL context: [SSL] PEM lib (_ssl.c:3900). Using default one.
Traceback (most recent call last):
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/common.py", line 1419, in create_ssl_context
    ssl_context.load_cert_chain(
ssl.SSLError: [SSL] PEM lib (_ssl.c:3900)
2024/11/19 20:51:55 INFO: [Local Server] [Main] Serving on /run/wazuh-server/socket/local-server.sock
2024/11/19 20:51:55 DEBUG: [Local Server] [Keep alive] Calculating.
2024/11/19 20:51:55 DEBUG: [Local Server] [Keep alive] Calculated.
2024/11/19 20:51:55 INFO: [Master] [Main] Serving on ('::1', 1516, 0, 0)
2024/11/19 20:51:55 DEBUG: [Master] [Keep alive] Calculating.
2024/11/19 20:51:55 DEBUG: [Master] [Keep alive] Calculated.
2024/11/19 20:51:55 INFO: [Master] [Local integrity] Starting.
2024/11/19 20:51:55 INFO: [Master] [Local integrity] Finished in 0.099s. Calculated metadata of 0 files.
2024/11/19 20:51:56 INFO: Starting API in foreground
2024/11/19 20:51:56 INFO: Checking RBAC database integrity...
2024/11/19 20:51:56 INFO: /var/lib/wazuh-server/rbac.db file was detected
2024/11/19 20:51:56 INFO: RBAC database integrity check finished successfully
wazuh-comms-apid: Non existent process 517, removing from /run/wazuh-server...
2024/11/19 20:51:56 INFO: Starting API in foreground
2024/11/19 20:51:56 INFO: Listening on 0.0.0.0:27000
2024/11/19 20:51:56 INFO: Starting gunicorn 22.0.0
2024/11/19 20:51:56 INFO: Listening at: https://127.0.0.1:27000 (581)
2024/11/19 20:51:56 INFO: Using worker: uvicorn.workers.UvicornWorker
2024/11/19 20:51:56 INFO: Booting worker with pid: 631
2024/11/19 20:51:56 INFO: Started server process [581]
2024/11/19 20:51:56 INFO: Waiting for application startup.
2024/11/19 20:51:56 INFO: Application startup complete.
2024/11/19 20:51:56 INFO: Uvicorn running on unix socket /run/wazuh-server/socket/comms-api.sock (Press CTRL+C to quit)
2024/11/19 20:51:56 INFO: Booting worker with pid: 632
2024/11/19 20:51:56 INFO: Started server process [632]
2024/11/19 20:51:56 INFO: Waiting for application startup.
2024/11/19 20:51:56 INFO: Application startup complete.
2024/11/19 20:51:56 INFO: Booting worker with pid: 633
2024/11/19 20:51:56 INFO: Started server process [633]
2024/11/19 20:51:56 INFO: Waiting for application startup.
2024/11/19 20:51:56 INFO: Application startup complete.
2024/11/19 20:51:56 INFO: Booting worker with pid: 634
2024/11/19 20:51:56 INFO: Started server process [634]
2024/11/19 20:51:56 INFO: Waiting for application startup.
2024/11/19 20:51:56 INFO: Application startup complete.
2024/11/19 20:51:59 INFO: Listening on ['localhost', '::1']:55000.
2024/11/19 20:51:59 INFO: Populating installation UID...
2024/11/19 20:51:59 INFO: Getting updates information...
```

Still, I must test it integrated with the engine and modify the package specs.

**Comment by nico-stefani** [comment]
# Update

I detected a problem installing from sources when I tried to start the engine without the root flag.
The issue is related to two directories that the engine is using, `/sockets` and `queue`, but weren't installed by the `inst-functions.sh` script. So, we don't have control over these to set the correct owner. A new issue will be opened to address it.

Regarding the packages, I modified the `.deb` to set the ownership of directories to the wazuh user. This works but as a pre-requisite, we need to have the user created before the package installation. 
So, I've been working on the preinst script to create the group and user.
These same steps must be replicated in the `.rpm` package.

**Comment by nico-stefani** [comment]
# Update

I've been rebasing with the latest changes of master and adding the installation of `/tmp/wazuh-server` in `inst-function.sh`
