### ISSUE TITLE
Restore wazuh-keystore and rbac_control binaries

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#26936]
# Description

As part of the current iteration in the Wazuh Server 5.0 MVP, we have found that the `wazuh-keystore` and `rbac_control` binaries are no longer part of the server installation. These relevant files should be available in `/usr/share/wazuh-server/bin` along with the rest of Wazuh binary files both for `.deb` and `.rpm` packages.

It is relevant to mention that:
- The `wazuh-keystore` was formerly installed via the `src/init/inst-functions.sh` file (removed in https://github.com/wazuh/wazuh/pull/26254/)
- The `rbac_control` binary was generated in the `framework/Makefile` file (modified in https://github.com/wazuh/wazuh/pull/26591)
- For the `.rpm` package, the files must be included in the `packages/rpms/SPECS/wazuh-server.spec` file.

**Comment by nico-stefani** [comment]
# Update

I tried to build the `keystore` as the first approach to restoring it. This was when I got

```console
root@wazuh-master:/wazuh/src/shared_modules/keystore# cmake -B build -S .
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /wazuh/src/shared_modules/keystore/build
root@wazuh-master:/wazuh/src/shared_modules/keystore# ll
total 40
drwxrwxr-x 1 root root 4096 Nov 21 19:33 ./
drwxrwxr-x 1 root root 4096 Nov 20 17:57 ../
drwxr-xr-x 4 root root 4096 Nov 21 19:33 build/
-rw-rw-r-- 1 root root 1400 Nov 20 17:57 CMakeLists.txt
drwxrwxr-x 2 root root 4096 Nov 20 17:57 include/
drwxrwxr-x 2 root root 4096 Nov 20 17:57 qa/
drwxrwxr-x 2 root root 4096 Nov 20 17:57 src/
drwxrwxr-x 3 root root 4096 Nov 20 17:57 tests/
drwxrwxr-x 2 root root 4096 Nov 20 17:57 testtool/
root@wazuh-master:/wazuh/src/shared_modules/keystore# cmake --build build
[ 16%] Building CXX object CMakeFiles/keystore.dir/src/keyStore.cpp.o
In file included from /wazuh/src/shared_modules/keystore/src/keyStore.cpp:2:
/wazuh/src/shared_modules/utils/evpHelper.hpp:15:10: fatal error: defer.hpp: No such file or directory
   15 | #include "defer.hpp"
      |          ^~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/keystore.dir/build.make:76: CMakeFiles/keystore.dir/src/keyStore.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:102: CMakeFiles/keystore.dir/all] Error 2
gmake: *** [Makefile:101: all] Error 2
```

I need to continue investigating the right way to build it.

Regarding `rbac_control`, It is already included because it is in `framework/scripts` but it is not working.

```console
[root@0e80d90ab4d8 wazuh]# rbac_control change-password
New password for 'wazuh' (skip):
/usr/share/wazuh-server/framework/python/lib/python3.10/concurrent/futures/process.py:252: RuntimeWarning: coroutine 'update_user' was never awaited
  del r
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Error executing API request locally: cannot pickle 'coroutine' object
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/concurrent/futures/process.py", line 211, in _sendback_result
    result_queue.put(_ResultItem(work_id, result=result,
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/multiprocessing/queues.py", line 371, in put
    obj = _ForkingPickler.dumps(obj)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle 'coroutine' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 279, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
TypeError: cannot pickle 'coroutine' object
```

**Comment by nico-stefani** [comment]
# Update

I've been able to get the `rbac_control` running again

```console
[root@f6d39f41f94a wazuh]# rbac_control --help
usage: rbac_control.py [-h] {change-password,factory-reset} ...

Wazuh RBAC tool: manage resources from the Wazuh RBAC database

Arguments:
  {change-password,factory-reset}
    change-password     Change the password for each default user. Empty values will leave the password unchanged.
    factory-reset       Reset the RBAC database to its default state. This will completely wipe your custom RBAC information.

options:
  -h, --help            show this help message and exit
[root@f6d39f41f94a wazuh]# rbac_control change-password
New password for 'wazuh' (skip):
New password for 'wazuh-wui' (skip):
New password for 'agent-init' (skip):
        wazuh: UPDATED
        wazuh-wui: UPDATED
        agent-init: UPDATED
[root@f6d39f41f94a wazuh]# rbac_control factory-reset
This action will completely wipe your RBAC configuration and restart it to default values. Type RESET to proceed: RESET
        Successfully reset RBAC database
[root@f6d39f41f94a wazuh]# ll /var/lib/wazuh-server/
total 120
drwxr-x--- 4 root  wazuh   4096 Oct 18 12:28 engine
drwxr-x--- 2 root  wazuh   4096 Nov 22 13:25 indexer-connector
-rw-rw---- 1 wazuh wazuh     36 Nov 22 13:27 installation_uid
-rw-r----- 1 wazuh wazuh 102400 Nov 22 17:20 rbac.db
drwxr-x--- 2 root  wazuh   4096 Nov 22 13:25 vd
```

**Comment by nico-stefani** [comment]
Awaiting for definitions

**Comment by nico-stefani** [comment]
Awaiting for definitions

**Comment by fdalmaup** [comment]
@nico-stefani, we need to take into account what was mentioned in https://github.com/wazuh/wazuh/pull/29254#pullrequestreview-2781355624 for the `indexer` configuration section.

**Comment by nico-stefani** [comment]
# Update

I've been investigating options to implement the keystore, and I found that from the Python side, there aren't good options that match our requirements.

I think we can continue using the `wazuh-keystore`, adapted in #26971, to store credentials and integrate the [example](https://github.com/wazuh/wazuh/pull/27066#issuecomment-2524843328) into the framework core, to retrieve them.

Regarding the `rbac_control`, the whole functionality was migrated to the indexer in #27706. So, we need to remove any reference to it in the code if it still exists.

**Comment by nico-stefani** [comment]
# Update

* Added class to read the keystore
* Obtain the indexer username and password from the default keystore
