### ISSUE TITLE
Release 4.10.0 - Beta 1 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#26999]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26970                                       |
| **Main footprint metrics issue #** | #26974                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Beta 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-beta1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

**Comment by pro-akim** [comment]
# Analysis report

Compared to: #26661

## Graphs

### Centos

### Manager

### Windows

### Ubuntu

## Logs


<details><summary>Centos</summary>


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-23 04:42:56,553 Couldn't access the file
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jenkins_utils-3.11.0-py3.6.egg/jenkins_utils/monitor.py", line 625, in check_wazuh_processes
    data = parse_state_file(s_file.path)
  File "/usr/local/lib/python3.6/site-packages/jenkins_utils-3.11.0-py3.6.egg/jenkins_utils/monitor.py", line 106, in parse_state_file
    with open(filename) as state_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/var/run/wazuh-agentd.state'

2024-11-23 13:33:43,241 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1619, in _parse_stat_file
    data = f.read()
ProcessLookupError: [Errno 3] No such process
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/22 22:40:25 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/22 22:40:25 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.2.173]:1514/tcp': 'Connection refused'. 
```

- Expected in stress test
```
2024/11/25 00:40:54 wazuh-agentd WARNING: Agent buffer is full: Events may be lost. 
```

</details>



<details><summary>Manager</summary>

- Reported: xxx - New issue
```
2024/11/25 00:40:41 wazuh-modulesd:content-updater WARNING: Error '-1' when downloading file: Could not connect to server. 
```


- Reported: https://github.com/wazuh/wazuh/issues/22565 - Known issue
```
2024/11/22 22:38:34 indexer-connector WARNING: No username and password found in the keystore, using default values. 
2024/11/22 22:38:34 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-2-173.ec2.internal', retrying until the connection is successful. 
2024/11/22 22:39:50 indexer-connector WARNING: Failed to sync agent '001' with the indexer. 
```


- Expected in stress test
```
2024/11/23 13:07:12 wazuh-remoted WARNING: Message queue is full (10). Events may be lost. 
2024/11/22 22:40:25 wazuh-modulesd:content-updater WARNING: The offsets download has been interrupted.
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/6368 - Known issue
```
2024/11/22 22:40:41 wazuh-modulesd:vulnerability-scanner WARNING: The 'feed-update-interval' option at module 'vulnerability-detection' must be at least 1 hour. Automatically set to 60 minutes. 
```
</details>



<details><summary>Windows</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-23 04:44:07,657 Couldn't access the file
Traceback (most recent call last):
  File "C:\Users\Jenkins\AppData\Local\Programs\Python\Python39\lib\site-packages\jenkins_utils-3.11.0-py3.9.egg\jenkins_utils\monitor.py", line 625, in check_wazuh_processes
    data = parse_state_file(s_file.path)
  File "C:\Users\Jenkins\AppData\Local\Programs\Python\Python39\lib\site-packages\jenkins_utils-3.11.0-py3.9.egg\jenkins_utils\monitor.py", line 106, in parse_state_file
    with open(filename) as state_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\ossec-agent\\wazuh-agent.state'
 
```

- Expected in stress test
```
2024/11/24 00:01:08 wazuh-agent WARNING: Agent buffer at 90 %. 
2024/11/24 00:02:28 wazuh-agent WARNING: Agent buffer is full: Events may be lost. 
```
</details>



<details><summary>Ubuntu</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-23 04:54:47,745 Couldn't access the file
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jenkins_utils-3.11.0-py3.8.egg/jenkins_utils/monitor.py", line 625, in check_wazuh_processes
    data = parse_state_file(s_file.path)
  File "/usr/local/lib/python3.8/dist-packages/jenkins_utils-3.11.0-py3.8.egg/jenkins_utils/monitor.py", line 106, in parse_state_file
    with open(filename) as state_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/var/run/wazuh-agentd.state'
```

- Expected in stress test
```
2024/11/23 18:46:50 wazuh-agentd WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '1775' at 'any'. 
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/22 22:40:25 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/22 22:40:25 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.2.173]:1514/tcp': 'Connection refused'. 
2024/11/23 18:46:50 wazuh-agentd WARNING: (1214): Problem receiving message from '172.31.2.173'.
```

Expected in stress test
```
2024/11/25 00:40:46 wazuh-agentd WARNING: Agent buffer is full: Events may be lost. 
2024/11/23 18:46:50 wazuh-agentd WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '1775' at 'any'.  
```
</details>

**Comment by MARCOSD4** [comment]
LGTM
