### ISSUE TITLE
Improve server processes signal handling

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#27265]
## Description

During https://github.com/wazuh/wazuh/issues/27248, we have detected some issues when sending termination and killing signals to the main server process and its subprocesses.

The list is the following:

- When executing the binary on foreground and shutting it down using `Ctrl+C` (which sends a `SIGINT`), we found the following exception

  ```console
  2024/12/11 14:41:23 INFO: [Cluster] [Main] SIGINT received. Shutting down...
  Exception in callback <Handlers.SIG_IGN: 1>()
  handle: <Handle <Handlers.SIG_IGN: 1>()>
  Traceback (most recent call last):
    File "/usr/share/wazuh-server/framework/python/lib/python3.10/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
  TypeError: 'Handlers' object is not callable
  ```

- When stopping the server after having killed one of its processes, the following exception arised

  ```console
  Traceback (most recent call last):
    File "/usr/share/wazuh-server/framework/scripts/wazuh_server.py", line 450, in <module>
      args.func()
    File "/usr/share/wazuh-server/framework/scripts/wazuh_server.py", line 416, in stop
      shutdown_server(server_pid)
    File "/usr/share/wazuh-server/framework/scripts/wazuh_server.py", line 166, in shutdown_server
      pyDaemonModule.delete_child_pids(SERVER_DAEMON_NAME, server_pid, main_logger)
    File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/pyDaemonModule.py", line 137, in delete_child_pids
      for process in psutil.Process(ppid).children(recursive=True):
    File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/psutil/__init__.py", line 332, in __init__
      self._init(pid)
    File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/psutil/__init__.py", line 373, in _init
      raise NoSuchProcess(pid, msg='process PID not found')
  psutil.NoSuchProcess: process PID not found (pid=8384)
  ```

- Killing/terminating the main server process did not kill/terminate its subprocesses
- The Communications API batcher process is not terminating when receiving the `SIGTERM` signal

This issue aims to fix them and improve the processes robustness to avoid similar issues in the future.

### Checks

- [x] The server exits cleanly when receiving the `SIGINT` signal (Ctrl+C)
- [x] The server is stopped successfully even if one or many of its processes was killed
- [x] All subprocesses are terminated when the main server process receives a `SIGTERM` signal
- [x] All subprocesses are killed when the main server process receives a `SIGKILL` signal
- [x] The Communications API batcher processes is terminated on a `SIGTERM` signal
- [x] All of the above is resolved in an environment compiled from sources and and environment using packages

**Comment by fdalmaup** [comment]
Unblocked since it is required for the `wazuh-server` lifecycle management (see https://github.com/wazuh/wazuh/issues/27313#issuecomment-2552221339).

**Comment by nico-stefani** [comment]
# Update

I've been investigating the root cause of the dirty exit of the comms-api when receiving a `SIGINT`, still without success.

Also, I've implemented a process termination when comms-api had an unexpected error.

```console
[root@08277c368165 wazuh]# /usr/share/wazuh-server/bin/wazuh-comms-apid
2024/12/19 18:05:39 INFO: [Communications API] Starting API
2024/12/19 18:05:39 INFO: [Communications API] Listening on localhost:27000
2024/12/19 18:05:39 ERROR: [Communications API] Error when trying to start the Wazuh Communications API. Error 2702 - Ensure the certificates have the correct permissions: [Errno 13] Permission denied: '/etc/wazuh-server/certs/api.key'
2024/12/19 18:05:39 INFO: [Communications API] Shutting down
2024/12/19 18:05:39 INFO: [Communications API] MuxDemuxRunner (pid: 949) - Received signal SIGTERM, shutting down
2024/12/19 18:05:39 INFO: [Communications API] Shutting down MuxDemuxRunner
2024/12/19 18:05:39 INFO: [Communications API] Batcher (pid: 951) - Received signal SIGTERM, shutting down
[root@08277c368165 wazuh]# echo $?
1
```

**Comment by nico-stefani** [comment]
# Update

I've working on the signal handling on the main server process.

I'm having issues handling the `SIGTERM` related to the child processes. When I shut down the server the child processes kept alive and did not exit.

```console
[root@9cf37a24c010 wazuh]# /usr/share/wazuh-server/bin/wazuh-server start
2024/12/20 18:35:26 INFO: [Cluster] [Main] Starting server (pid: 698)
2024/12/20 18:35:27 INFO: [Master] [Main] Configuration server is not available, retrying...
2024/12/20 18:35:27 INFO: [Master] [Config Server] Started server process [698]
2024/12/20 18:35:27 INFO: [Master] [Config Server] Waiting for application startup.
2024/12/20 18:35:27 INFO: [Master] [Config Server] Application startup complete.
2024/12/20 18:35:27 INFO: [Master] [Config Server] Uvicorn running on unix socket /run/wazuh-server/config-server.sock (Press CTRL+C to quit)
...
2024/12/20 18:35:42 INFO: [Cluster] [Main] Shutting down wazuh-apid (pid: 745)
2024/12/20 18:35:42 INFO: [Cluster] [Main] Shutting down wazuh-comms-apid (pid: 705)
2024/12/20 18:35:42 INFO: [Cluster] [Main] Waiting for daemons shutdown.
2024/12/20 18:35:42 INFO: [Communications API] Handling signal: term
2024/12/20 18:35:42 ERROR: [Communications API] Worker (pid:741) was sent SIGTERM!
2024/12/20 18:35:42 INFO: [Communications API] Shutting down
2024/12/20 18:35:42 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/20 18:35:42 INFO: [Communications API] Shutting down
2024/12/20 18:35:42 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/20 18:35:42 INFO: [Communications API] Shutting down
2024/12/20 18:35:42 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/20 18:35:42 INFO: [Communications API] Waiting for application shutdown.
2024/12/20 18:35:42 INFO: [Communications API] Application shutdown complete.
2024/12/20 18:35:42 INFO: [Communications API] Finished server process [742]
2024/12/20 18:35:42 INFO: [Communications API] Worker exiting (pid: 742)
2024/12/20 18:35:42 INFO: [Communications API] Waiting for application shutdown.
2024/12/20 18:35:42 INFO: [Communications API] Application shutdown complete.
2024/12/20 18:35:42 INFO: [Communications API] Finished server process [743]
2024/12/20 18:35:42 INFO: [Communications API] Worker exiting (pid: 743)
2024/12/20 18:35:42 INFO: [Management API] Shutdown wazuh-apid server.
2024/12/20 18:35:42 INFO: [Communications API] Waiting for application shutdown.
2024/12/20 18:35:42 INFO: [Communications API] Application shutdown complete.
2024/12/20 18:35:42 INFO: [Communications API] Finished server process [744]
2024/12/20 18:35:42 INFO: [Communications API] Worker exiting (pid: 744)
2024/12/20 18:35:42 INFO: [Communications API] Shutting down: Master
2024/12/20 18:35:42 INFO: [Communications API] Shutting down
2024/12/20 18:35:42 INFO: [Communications API] MuxDemuxRunner (pid: 723) - Received signal SIGTERM, shutting down
2024/12/20 18:35:42 INFO: [Communications API] Shutting down MuxDemuxRunner
2024/12/20 18:35:42 INFO: [Communications API] Batcher (pid: 725) - Received signal SIGTERM, shutting down
2024/12/20 18:35:48 INFO: [Master] [Local integrity] Starting.
2024/12/20 18:35:48 ERROR: [Master] [Local integrity] Error calculating local file integrity: A child process terminated abruptly, the process pool is not usable anymore
2024/12/20 18:35:48 INFO: [Master] [Local integrity] Finished in 0.000s. Calculated metadata of 2 files.
```
```console
[root@9cf37a24c010 wazuh]# ps auxf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         309  0.0  0.0  13448  2944 pts/1    SNs  18:13   0:00 bash
root         764  0.0  0.0  53352  3712 pts/1    RN+  18:37   0:00  \_ ps auxf
root           1  0.0  0.0  13448  2944 pts/0    SNs  18:13   0:00 bash
root         693  0.0  0.0  13308  2816 pts/0    SN+  18:35   0:00 /bin/sh /usr/share/wazuh-server/bin/wazuh-server start
wazuh-s+     698  1.1  0.4 502384 110688 pts/0   SNl+ 18:35   0:01  \_ /usr/share/wazuh-server/framework/python/bin/python3 /usr/share/wazuh-server/framework/scripts/wazuh_server.py start
wazuh-s+     705  1.1  0.0      0     0 pts/0    ZN+  18:35   0:01      \_ [python3] <defunct>
wazuh-s+     745  2.0  0.0      0     0 pts/0    ZN+  18:35   0:02      \_ [python3] <defunct>
```

even all the `PID` successfully deleted

```console
[root@9cf37a24c010 wazuh]# ll /run/wazuh-server/
total 0
srw-rw-rw- 1 wazuh-server wazuh-server 0 Dec 20 18:35 comms-api.sock
srw-rw-rw- 1 wazuh-server wazuh-server 0 Dec 20 18:35 config-server.sock
srw-rw---- 1 wazuh-server wazuh-server 0 Dec 20 18:35 local-server.sock
```

Regarding `SIGKILL` I realize that this one can not be handled

> signal.SIGKILL
> Kill signal.
> It cannot be caught, blocked, or ignored.

So we need to figure out how to manage the state of the whole server when one process is killed with `-9`.

**Comment by nico-stefani** [comment]
# Update

I've been working on the shutdown of the process pool executor when the server receives a `SIGTERM` signal and I've been able to get it working in `master`. Still, I need to figure out how to replicate the behavior in the worker because the signal is not being propagated.

**Comment by nico-stefani** [comment]
# Update

I've been working on a mechanism to close the asyncio running loop when the server receives a `SIGTERM` to match the behavior with the `SIGINT` signal. With this, we solve the issue with the process pool executor, mentioned above, for master and worker.

Still, I have an unhandled exception to solve to achieve a clean exit.

```console
2024/12/26 17:23:26 INFO: [Cluster] [Main] Starting server (pid: 900)
2024/12/26 17:23:26 INFO: [Master] [Main] Configuration server is not available, retrying...
2024/12/26 17:23:26 INFO: [Master] [Config Server] Started server process [900]
2024/12/26 17:23:26 INFO: [Master] [Config Server] Waiting for application startup.
2024/12/26 17:23:26 INFO: [Master] [Config Server] Application startup complete.
2024/12/26 17:23:26 INFO: [Master] [Config Server] Uvicorn running on unix socket /run/wazuh-server/config-server.sock (Press CTRL+C to quit)
2024/12/26 17:23:27 INFO: [Local Server] [Main] Starting wazuh-engined
2024/12/26 17:23:27 ERROR: [Local Server] [Main] Error starting wazuh-engined: [Errno 2] No such file or directory: PosixPath('/usr/share/wazuh-server/bin/wazuh-engine')
2024/12/26 17:23:27 INFO: [Local Server] [Main] Starting wazuh-comms-apid
2024/12/26 17:23:28 INFO: [Communications API] Starting API
...
2024/12/26 17:23:31 INFO: [Management API] Listening on ['localhost', '::1']:55000.
2024/12/26 17:23:31 INFO: [Management API] Getting installation UID...
2024/12/26 17:23:31 INFO: [Management API] Getting updates information...
Llamado el clean loop
2024/12/26 17:23:31 ERROR: [Cluster] [Main] Unhandled exception: Event loop stopped before Future completed.
2024/12/26 17:23:31 INFO: [Cluster] [Main] Shutting down wazuh-apid (pid: 947)
2024/12/26 17:23:31 INFO: [Cluster] [Main] Shutting down wazuh-comms-apid (pid: 907)
2024/12/26 17:23:31 INFO: [Cluster] [Main] Waiting for daemons shutdown.
2024/12/26 17:23:31 INFO: [Communications API] Handling signal: term
2024/12/26 17:23:31 ERROR: [Communications API] Worker (pid:943) was sent SIGTERM!
2024/12/26 17:23:31 ERROR: [Communications API] Worker (pid:944) was sent SIGTERM!
2024/12/26 17:23:31 INFO: [Communications API] Shutting down
2024/12/26 17:23:31 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/26 17:23:32 INFO: [Communications API] Shutting down
2024/12/26 17:23:32 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/26 17:23:32 INFO: [Communications API] Waiting for application shutdown.
2024/12/26 17:23:32 INFO: [Communications API] Application shutdown complete.
2024/12/26 17:23:32 INFO: [Communications API] Finished server process [945]
2024/12/26 17:23:32 INFO: [Communications API] Worker exiting (pid: 945)
2024/12/26 17:23:32 INFO: [Communications API] Waiting for application shutdown.
2024/12/26 17:23:32 INFO: [Communications API] Application shutdown complete.
2024/12/26 17:23:32 INFO: [Communications API] Finished server process [946]
2024/12/26 17:23:32 INFO: [Management API] Shutdown wazuh-apid server.
2024/12/26 17:23:32 INFO: [Communications API] Worker exiting (pid: 946)
2024/12/26 17:23:32 INFO: [Communications API] Shutting down: Master
2024/12/26 17:23:32 INFO: [Communications API] Shutting down
2024/12/26 17:23:32 INFO: [Communications API] MuxDemuxRunner (pid: 925) - Received signal SIGTERM, shutting down
2024/12/26 17:23:32 INFO: [Communications API] Shutting down MuxDemuxRunner
2024/12/26 17:23:32 INFO: [Communications API] Batcher (pid: 927) - Received signal SIGTERM, shutting down
```

**Comment by nico-stefani** [comment]
# Update

##  The server exits cleanly when receiving the `SIGINT` signal (Ctrl+C)

<details><summary>Details</summary>
<p>

```console
[root@7a074f639fa3 wazuh]# /usr/share/wazuh-server/bin/wazuh-server start
2024/12/27 19:22:25 INFO: [Cluster] [Main] Starting server (pid: 917)
2024/12/27 19:22:26 INFO: [Master] [Main] Configuration server is not available, retrying...
2024/12/27 19:22:26 INFO: [Master] [Config Server] Started server process [917]
2024/12/27 19:22:26 INFO: [Master] [Config Server] Waiting for application startup.
2024/12/27 19:22:26 INFO: [Master] [Config Server] Application startup complete.
2024/12/27 19:22:26 INFO: [Master] [Config Server] Uvicorn running on unix socket /run/wazuh-server/config-server.sock (Press CTRL+C to quit)
2024/12/27 19:22:27 INFO: [Local Server] [Main] Starting wazuh-engined
2024/12/27 19:22:27 ERROR: [Local Server] [Main] Error starting wazuh-engined: [Errno 2] No such file or directory: PosixPath('/usr/share/wazuh-server/bin/wazuh-engine')
2024/12/27 19:22:27 INFO: [Local Server] [Main] Starting wazuh-comms-apid
2024/12/27 19:22:29 INFO: [Communications API] Starting API
2024/12/27 19:22:29 INFO: [Communications API] Listening on localhost:27000
2024/12/27 19:22:29 INFO: [Communications API] Starting gunicorn 22.0.0
2024/12/27 19:22:29 INFO: [Communications API] Listening at: https://127.0.0.1:27000 (924)
2024/12/27 19:22:29 INFO: [Communications API] Using worker: uvicorn.workers.UvicornWorker
2024/12/27 19:22:29 INFO: [Communications API] Booting worker with pid: 960
2024/12/27 19:22:29 INFO: [Communications API] Booting worker with pid: 961
2024/12/27 19:22:29 INFO: [Communications API] Started server process [924]
2024/12/27 19:22:29 INFO: [Communications API] Waiting for application startup.
2024/12/27 19:22:29 INFO: [Communications API] Application startup complete.
2024/12/27 19:22:29 INFO: [Communications API] Uvicorn running on unix socket /run/wazuh-server/comms-api.sock (Press CTRL+C to quit)
2024/12/27 19:22:29 INFO: [Communications API] Booting worker with pid: 962
2024/12/27 19:22:29 INFO: [Communications API] Started server process [962]
2024/12/27 19:22:29 INFO: [Communications API] Waiting for application startup.
2024/12/27 19:22:29 INFO: [Communications API] Application startup complete.
2024/12/27 19:22:29 INFO: [Communications API] Booting worker with pid: 963
2024/12/27 19:22:29 INFO: [Communications API] Started server process [963]
2024/12/27 19:22:29 INFO: [Communications API] Waiting for application startup.
2024/12/27 19:22:29 INFO: [Communications API] Application startup complete.
2024/12/27 19:22:29 INFO: [Local Server] [Main] Started wazuh-comms-apid (pid: 924)
2024/12/27 19:22:29 INFO: [Local Server] [Main] Starting wazuh-apid
2024/12/27 19:22:30 INFO: [Management API] Starting API
2024/12/27 19:22:30 INFO: [Management API] Checking RBAC database integrity...
2024/12/27 19:22:30 INFO: [Management API] /var/lib/wazuh-server/rbac.db file was detected
2024/12/27 19:22:30 INFO: [Management API] RBAC database integrity check finished successfully
2024/12/27 19:22:31 INFO: [Local Server] [Main] Started wazuh-apid (pid: 964)
2024/12/27 19:22:31 ERROR: [Master] [Main] Failed loading SSL context: [SSL] PEM lib (_ssl.c:3900). Using default one.
2024/12/27 19:22:31 INFO: [Local Server] [Main] Serving on /run/wazuh-server/local-server.sock
2024/12/27 19:22:31 INFO: [Master] [Main] Serving on ('127.0.0.1', 1516)
2024/12/27 19:22:31 INFO: [Master] [Local integrity] Starting.
2024/12/27 19:22:31 INFO: [Master] [Local integrity] Finished in 0.003s. Calculated metadata of 2 files.
2024/12/27 19:22:32 INFO: [Management API] Listening on ['localhost', '::1']:55000.
2024/12/27 19:22:32 INFO: [Management API] Getting installation UID...
2024/12/27 19:22:32 INFO: [Management API] Getting updates information...
^C2024/12/27 19:22:36 INFO: [Cluster] [Main] SIGINT received. Shutting down...
2024/12/27 19:22:36 INFO: [Communications API] Handling signal: int
2024/12/27 19:22:36 INFO: [Cluster] [Main] Shutting down wazuh-apid (pid: 964)
2024/12/27 19:22:36 INFO: [Cluster] [Main] Shutting down wazuh-comms-apid (pid: 924)
2024/12/27 19:22:36 INFO: [Cluster] [Main] Waiting for daemons shutdown.
2024/12/27 19:22:36 ERROR: [Communications API] Worker (pid:960) was sent SIGINT!
2024/12/27 19:22:36 ERROR: [Communications API] Worker (pid:961) was sent SIGINT!
2024/12/27 19:22:36 INFO: [Communications API] Shutting down
2024/12/27 19:22:36 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/27 19:22:36 INFO: [Communications API] Shutting down
2024/12/27 19:22:36 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/27 19:22:36 INFO: [Management API] Shutdown wazuh-apid server.
2024/12/27 19:22:36 INFO: [Communications API] Waiting for application shutdown.
2024/12/27 19:22:36 INFO: [Communications API] Application shutdown complete.
2024/12/27 19:22:36 INFO: [Communications API] Finished server process [962]
2024/12/27 19:22:36 INFO: [Communications API] Worker exiting (pid: 962)
2024/12/27 19:22:36 INFO: [Communications API] Waiting for application shutdown.
2024/12/27 19:22:36 INFO: [Communications API] Application shutdown complete.
2024/12/27 19:22:36 INFO: [Communications API] Finished server process [963]
2024/12/27 19:22:36 INFO: [Communications API] Worker exiting (pid: 963)
2024/12/27 19:22:36 INFO: [Communications API] Shutting down: Master
2024/12/27 19:22:36 INFO: [Communications API] Shutting down
2024/12/27 19:22:36 INFO: [Communications API] MuxDemuxRunner (pid: 942) - Received signal SIGTERM, shutting down
2024/12/27 19:22:36 INFO: [Communications API] Shutting down MuxDemuxRunner
2024/12/27 19:22:36 INFO: [Communications API] Batcher (pid: 944) - Received signal SIGTERM, shutting down
```

</p>
</details> 

## All subprocesses are terminated when the main server process receives a `SIGTERM` signal

<details><summary>Details</summary>
<p>

```console
[root@7a074f639fa3 wazuh]# /usr/share/wazuh-server/bin/wazuh-server start
2024/12/27 19:24:37 INFO: [Cluster] [Main] Starting server (pid: 986)
2024/12/27 19:24:38 INFO: [Master] [Main] Configuration server is not available, retrying...
2024/12/27 19:24:38 INFO: [Master] [Config Server] Started server process [986]
2024/12/27 19:24:38 INFO: [Master] [Config Server] Waiting for application startup.
2024/12/27 19:24:38 INFO: [Master] [Config Server] Application startup complete.
2024/12/27 19:24:38 INFO: [Master] [Config Server] Uvicorn running on unix socket /run/wazuh-server/config-server.sock (Press CTRL+C to quit)
2024/12/27 19:24:39 INFO: [Local Server] [Main] Starting wazuh-engined
2024/12/27 19:24:39 ERROR: [Local Server] [Main] Error starting wazuh-engined: [Errno 2] No such file or directory: PosixPath('/usr/share/wazuh-server/bin/wazuh-engine')
2024/12/27 19:24:39 INFO: [Local Server] [Main] Starting wazuh-comms-apid
2024/12/27 19:24:41 INFO: [Communications API] Starting API
2024/12/27 19:24:41 INFO: [Communications API] Listening on localhost:27000
2024/12/27 19:24:41 INFO: [Communications API] Starting gunicorn 22.0.0
2024/12/27 19:24:41 INFO: [Communications API] Listening at: https://127.0.0.1:27000 (993)
2024/12/27 19:24:41 INFO: [Communications API] Using worker: uvicorn.workers.UvicornWorker
2024/12/27 19:24:41 INFO: [Communications API] Booting worker with pid: 1029
2024/12/27 19:24:41 INFO: [Communications API] Booting worker with pid: 1030
2024/12/27 19:24:41 INFO: [Communications API] Started server process [993]
2024/12/27 19:24:41 INFO: [Communications API] Waiting for application startup.
2024/12/27 19:24:41 INFO: [Communications API] Application startup complete.
2024/12/27 19:24:41 INFO: [Communications API] Uvicorn running on unix socket /run/wazuh-server/comms-api.sock (Press CTRL+C to quit)
2024/12/27 19:24:41 INFO: [Communications API] Booting worker with pid: 1031
2024/12/27 19:24:41 INFO: [Communications API] Started server process [1031]
2024/12/27 19:24:41 INFO: [Communications API] Waiting for application startup.
2024/12/27 19:24:41 INFO: [Communications API] Application startup complete.
2024/12/27 19:24:41 INFO: [Communications API] Booting worker with pid: 1032
2024/12/27 19:24:41 INFO: [Communications API] Started server process [1032]
2024/12/27 19:24:41 INFO: [Communications API] Waiting for application startup.
2024/12/27 19:24:41 INFO: [Communications API] Application startup complete.
2024/12/27 19:24:41 INFO: [Local Server] [Main] Started wazuh-comms-apid (pid: 993)
2024/12/27 19:24:41 INFO: [Local Server] [Main] Starting wazuh-apid
2024/12/27 19:24:42 INFO: [Management API] Starting API
2024/12/27 19:24:42 INFO: [Management API] Checking RBAC database integrity...
2024/12/27 19:24:42 INFO: [Management API] /var/lib/wazuh-server/rbac.db file was detected
2024/12/27 19:24:42 INFO: [Management API] RBAC database integrity check finished successfully
2024/12/27 19:24:43 INFO: [Local Server] [Main] Started wazuh-apid (pid: 1033)
2024/12/27 19:24:43 ERROR: [Master] [Main] Failed loading SSL context: [SSL] PEM lib (_ssl.c:3900). Using default one.
2024/12/27 19:24:43 INFO: [Local Server] [Main] Serving on /run/wazuh-server/local-server.sock
2024/12/27 19:24:43 INFO: [Master] [Main] Serving on ('::1', 1516, 0, 0)
2024/12/27 19:24:43 INFO: [Master] [Local integrity] Starting.
2024/12/27 19:24:43 INFO: [Master] [Local integrity] Finished in 0.003s. Calculated metadata of 2 files.
2024/12/27 19:24:44 INFO: [Management API] Listening on ['localhost', '::1']:55000.
2024/12/27 19:24:44 INFO: [Management API] Getting installation UID...
2024/12/27 19:24:44 INFO: [Management API] Getting updates information...
2024/12/27 19:24:51 INFO: [Cluster] [Main] Main loop stopped.
2024/12/27 19:24:51 INFO: [Cluster] [Main] Shutting down wazuh-apid (pid: 1033)
2024/12/27 19:24:51 INFO: [Cluster] [Main] Shutting down wazuh-comms-apid (pid: 993)
2024/12/27 19:24:51 INFO: [Cluster] [Main] Waiting for daemons shutdown.
2024/12/27 19:24:51 INFO: [Communications API] Handling signal: term
2024/12/27 19:24:51 ERROR: [Communications API] Worker (pid:1029) was sent SIGTERM!
2024/12/27 19:24:51 ERROR: [Communications API] Worker (pid:1030) was sent SIGTERM!
2024/12/27 19:24:51 INFO: [Communications API] Shutting down
2024/12/27 19:24:51 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/27 19:24:51 INFO: [Communications API] Shutting down
2024/12/27 19:24:51 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/27 19:24:51 INFO: [Communications API] Waiting for application shutdown.
2024/12/27 19:24:51 INFO: [Communications API] Application shutdown complete.
2024/12/27 19:24:51 INFO: [Communications API] Finished server process [1032]
2024/12/27 19:24:51 INFO: [Communications API] Worker exiting (pid: 1032)
2024/12/27 19:24:51 INFO: [Management API] Shutdown wazuh-apid server.
2024/12/27 19:24:51 INFO: [Communications API] Waiting for application shutdown.
2024/12/27 19:24:51 INFO: [Communications API] Application shutdown complete.
2024/12/27 19:24:51 INFO: [Communications API] Finished server process [1031]
2024/12/27 19:24:51 INFO: [Communications API] Worker exiting (pid: 1031)
2024/12/27 19:24:51 INFO: [Communications API] Shutting down: Master
2024/12/27 19:24:51 INFO: [Communications API] Shutting down
2024/12/27 19:24:51 INFO: [Communications API] MuxDemuxRunner (pid: 1011) - Received signal SIGTERM, shutting down
2024/12/27 19:24:51 INFO: [Communications API] Shutting down MuxDemuxRunner
2024/12/27 19:24:51 INFO: [Communications API] Batcher (pid: 1012) - Received signal SIGTERM, shutting down
```

</p>
</details>

**Comment by nico-stefani** [comment]
# Update

I've been working on a mechanism for detect when one of the server daemons or one of their child processes is down and stop the whole server.

**Comment by nico-stefani** [comment]
# Update

I've implemented a daemon monitor to run in the server process.

It still is pending adding UT's and performing some manual tests.

**Comment by nico-stefani** [comment]
Updated ETA because reviewer is Out of Office
