### ISSUE TITLE
Fetching custom logs from AWS S3 // Broken documentation

### ISSUE THREAD

**Issue by pr3l14t0r** [wazuh/wazuh#27279]
| Affected integration |
|---|
| AWS|

## Description

Ahoy. I got super desperate trying to ingest custom logs from an AWS S3 bucket. The logs are shipped from AWS AppFabric, a service that can ingest Security-Logs from third-party providers like Google-Workspace, Github, Slack, Zoom etc., normalize them to OCSF format and store them either as JSON or Parquet in an S3 bucket. 
In my case i store them as JSON in S3. 

I would really like to share my journey and place a few suggestions for improvement

As far as i do understand, there are two options, using the `aws-s3` wodle:

- Custom [buckets](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#buckets), using `<bucket type="custom">`
- Subscribing to an SQS, described in this shiny documentation: [Custom Logs Buckets](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/custom-buckets.html#custom-logs-buckets)

I run Wazuh version `4.9.1` as Single-Node-Deplyoment on an EC2 machine, using the official AMI. 

My Instance-Role is configured to have access to the corresponding S3 buckets, as well as the SQS queue.
Policies from the Instance-Role:

```yaml
        - PolicyName: ReadS3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - "arn:aws:s3:::the-cloudtrail-bucket"
                  - "arn:aws:s3:::the-cloudtrail-bucket/*"
                  - "arn:aws:s3:::the-custom-log-bucket"
                  - "arn:aws:s3:::the-custom-log-bucket/*"
        - PolicyName: SQSRead
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                Resource: "arn:aws:sqs:REGION:ACCOUNT_ID:my-super-shiny-sqs-queue"
```

In my setup i am using already an connection for ingesting cloudtrail data. So far, so well. 

## Trying with 'subscriber'

At first i did try using the following config:

```xml
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>5m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>
  
    <!-- REDACTED <bucket type="cloudtrail"> -->

    <!-- SQS ingestion config -->
    <subscriber type="buckets">
        <sqs_name>my-super-shiny-sqs-queue</sqs_name>
    </subscriber>
  </wodle>
```

Saved the config and restartet the manager... But nothing happened. So i did [enable debug mode](https://documentation.wazuh.com/current/cloud-security/amazon/services/troubleshooting.html#enabling-debug-mode) to check what happens in the background. From there, i can only see this: 

```text
[REDACTED]
2024/12/12 15:49:17 wazuh-modulesd:aws-s3[13701] wmodules-aws.c:522 at wm_aws_read(): DEBUG: Found a subscriber tag
2024/12/12 15:49:17 wazuh-modulesd:aws-s3[13701] wmodules-aws.c:538 at wm_aws_read(): DEBUG: Creating first subscriber structure
2024/12/12 15:49:17 wazuh-modulesd:aws-s3[13701] wmodules-aws.c:566 at wm_aws_read(): DEBUG: Loop through child nodes
2024/12/12 15:49:17 wazuh-modulesd:aws-s3[13701] wmodules-aws.c:569 at wm_aws_read(): DEBUG: Parse child node: sqs_name
2024/12/12 15:49:17 wazuh-modulesd[13701] main.c:95 at main(): DEBUG: Created new thread for the 'aws-s3' module.
```

but the wodle only launches the command for my cloudtrail bucket. Nothing happens for the SQS queue.. So i dug a bit deeper until i found out how to manually test this, using: 

`wodles/aws/aws-s3 --subscriber buckets --queue my-super-shiny-sqs-queue --debug 2` 

```text
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Error: You must specify a region.
ERROR: Unknown error: You must specify a region.
[...REDACTED BOTO_3 PYTHON TRACE...]
botocore.exceptions.NoRegionError: You must specify a region.
```

Aha! No region specified.. I was curios why, because for the cloudtrail integration i didn't need to specify a region and it would just work. Then i stumbled upon #25124 . 

There, the problem was fixed by adding a default profile. So i went ahead and created file `/root/.aws/credentials` with the following content:
```text
[default]
region=my-aws-region
```

Saved it and executed the above command again. This time i received:

```text
[root@wazuh-server ossec]# wodles/aws/aws-s3 --subscriber buckets --queue my-super-shiny-sqs-queue --debug 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
ERROR: Queue does not exist, verify the given name
``` 

I can double-assure you, that the name (in real life example) is correct. Unfortunately i do not see more information in the logs, so i went ahead and checked in the code where this log message would be written and it lead me [here](https://github.com/wazuh/wazuh/blob/master/wodles/aws/subscribers/sqs_queue.py#L66-L81).
Unfortunately the original boto3 exception is not thrown, which is why i can't find out what is going wrong. So i quickly overwrote the `except` statement, executed the command again and got: 

```text
An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the GetQueueUrl operation: The specified queue does not exist or you do not have access to it.
```

**AHA!** - We are trying to get the Queue URL here. This is unexpected and now the error is clear: I did not add `sqs:GetQueueUrl` as [SQS permission](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-api-permissions-reference.html) in my policy statement above. 

So i went ahead, added the permission and yeeeeeeeeeeeeeeehaw:

```text
[root@wazuh-server ossec]# wodles/aws/aws-s3 --subscriber buckets --queue my-super-shiny-sqs-queue --debug 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: The SQS queue is: https://sqs.REGION.amazonaws.com/ACCOUNT_ID/my-super-shiny-sqs-queue 
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: Retrieving messages from: my-super-shiny-sqs-queue 
DEBUG: The message is: REDACTED
```

### Conclusion

So... i finally managed to get this done. As you see, it's not really a bug. But what would help is the following:

- Add a permission statement to your documentation that would help people setting up permissions and enabled them to use Wazuh SQS integration. Here's my minimum working example of an inline policy: 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sqs:ReceiveMessage",
                "sqs:DeleteMessage",
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl"
            ],
            "Resource": "arn:aws:sqs:REGION:ACCOUNT_ID:my-super-shiny-sqs-queue ",
            "Effect": "Allow"
        }
    ]
}
```
- Do not overwrite / always print `boto3` errors since they are helpful
- Instead of using `sqs_name` in the config, you could directly go for `sqs_url` which can be declared by the user/admin. This would save the `get_url` step.
- Either let `boto3` fetch the region or require the user to set it in the configuration of the Wazuh Manager. 

## Trying with 'custom' bucket type

As another alternative i have tried to ingest logs using the `<bucket type="custom">` configuration. As the documentation states, this would avoid using an SQS queue. 

```xml
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>5m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>
    
<!-- Subscriber and Cloudtrail config have been redacted -->

    <!-- Custom "read from S3" config -->
    <bucket type="custom">
      <name>the-custom-log-bucket</name>
      <!-- per default, only logs from <date-of-execution>:00:00:00 will be parsed -->
      <only_logs_after>2024-NOV-01</only_logs_after>
      <path>AWSAppFabric/AuditLog/OCSF/JSON</path>
    </bucket>

  </wodle>
```

Save, Restart Manager, good thing that the debug logs are still active, because again, i haven't received any logs in Wazuh so i went ahead and executed the wodle manually:

```text
[root@wazuh-server ossec]# wodles/aws/aws-s3 --bucket the-custom-log-bucket --trail_prefix AWSAppFabric/AuditLog/OCSF/JSON --only_logs_after 2024-NOV-01 --type custom --debug 2

DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Marker: AWSAppFabric/AuditLog/OCSF/JSON/2024/11/01
DEBUG: +++ No logs to process in bucket: the-custom-log-bucket
DEBUG: +++ No logs to process in bucket: the-custom-log-bucket
DEBUG: +++ No logs to process in bucket: the-custom-log-bucket
DEBUG: +++ DB Maintenance
DEBUG: +++ Error: database is locked
ERROR: Unknown error: database is locked
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 199, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 98, in main
    bucket.iter_bucket(options.aws_account_id, options.regions)
  File "/var/ossec/wodles/aws/buckets_s3/aws_bucket.py", line 506, in iter_bucket
    self.db_cursor.execute(self.sql_db_optimize)
sqlite3.OperationalError: database is locked
```

Let us ignore the `database is locked` issue for now. Two problems:

Why does the wodle set a marker? And why is it appended to the Prefix? I think this is due to the fact how cloudtrail logs are partitioned, but it wouldn't work in my case. Please adjust the [only_logs_after](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#only-logs-after) documentation so that people know that it is not about the date of an S3Object, but rather about partitioning... 

So.. i removed the `only_logs_before` from the command to test it out: 

```text
wodles/aws/aws-s3 --bucket the-custom-log-bucket --trail_prefix AWSAppFabric/AuditLog/OCSF/JSON --type custom --debug 2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Marker: AWSAppFabric/AuditLog/OCSF/JSON/2024/12/12
DEBUG: +++ No logs to process in bucket: the-custom-log-bucket
```

The wodle again set a marker/ date prefix, this time with todays' date.. 

Also i recognized that the prefix set in the wodle config is transformed to `--trail_prefix` which is not correct since i am not ingesting cloudtrail here.. 

Invoking `wodles/aws/aws-s3 --help` did not reveal another parameter that would have helped me here... 

### Conclusion 

Please enhance the documentation on `<bucket type="custom">` . Clearly state that this can not be used to fetch custom logs from S3, but rather requires logs to be in a date-partition format and that you expect "Cloudtrail"-settings. 

Furthermore clearly state that a date prefix is added always - is it even? At least i got surprised that the date prefix was appended. 

From the current documentation i would expect that given the S3-Bucket name + Path, the wodle would recursively search through a bucket and scan for objects. I could have thought about this because you do not specify a log format, which seemed weird. But i still gave it a try.. 

## Outro

Thanks to all reading through this, thanks to the whole Wazuh team for your awesome work. I hope this helps any possible reader to understand the problem better and to work it out, using SQS queues.. Please note my suggestions in the two `Conclusion` sections. 

Cheers ✌🏼

**Comment by marcinliszka12** [comment]
Hey. Thank you for feedback. In first solution SQS module, the logs files can be in gz compress files? or only plain text?

**Comment by LeHoangMinhQuan** [comment]
Thank you for your effort @pr3l14t0r , I've setup as your flow with sqs subscriber and test with this: 
`sudo /var/ossec/wodles/aws/aws-s3   --subscriber buckets   --queue sj-siem-logs-flow-a-sqs-queue   --debug 2`
it shows the message like:
`DEBUG: The message is: {'Records': [{'eventVersion': '2.5', 'eventSource': 'aws:s3', 'awsRegion': 'ap-southeast-1', 'eventTime': '2026-08-12T07:40:16.739Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': 'AWS:AIDAVRUVTVMDLVEOC675U'}, 'requestParameters': {'sourceIPAddress': '115.75.112.32'}, 'responseElements': {'x-amz-request-id': '5WJYDW9AMYGD6AKQ', 'x-amz-id-2': 'IEJ1IpCkClfmg7idSzegTvO7GjimGXKDHg6+Bkc+Ud5fn3qxmjkvnwCgv43rcybiIJLXJRXiaEYT5zK3OpMkQpL7qsrVwHsfOWzRTdd0EiI='}, 's3': {'s3SchemaVersion': '1.0', 'configurationId': 'siem-logs-flow-a-create-events', 'bucket': {'name': 'siem-logs-flow-a', 'ownerIdentity': {'principalId': 'A14L2UW7BAOBV9'}, 'arn': 'arn:aws:s3:::siem-logs-flow-a'}, 'object': {'key': 'test_login_01.json', 'size': 215, 'eTag': '6abb74316f7447cb4627b244fc35600e', 'versionId': 'lINmSXHi_moP.NcNqp.Etwcyy5GPvv0b', 'sequencer': '006A7C2360B36DE976'}}}]}
DEBUG: Message deleted from queue: siem-logs-flow-a-sqs-queue`

so I assume the logs is ingested by wazuh, but the rules was not triggered although wazuh-logtest filters the logs to rules correctly.

So, i just want to ask whether you can tell more about the logs format you are using and how you can ingest it to Wazuh and shows on Dashboard or alerts.json?

**Comment by LeHoangMinhQuan** [comment]
> Thank you for your effort [@pr3l14t0r](https://github.com/pr3l14t0r) , I've setup as your flow with sqs subscriber and test with this: `sudo /var/ossec/wodles/aws/aws-s3 --subscriber buckets --queue sj-siem-logs-flow-a-sqs-queue --debug 2` it shows the message like: `DEBUG: The message is: {'Records': [{'eventVersion': '2.5', 'eventSource': 'aws:s3', 'awsRegion': 'ap-southeast-1', 'eventTime': '2026-08-12T07:40:16.739Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': 'AWS:AIDAVRUVTVMDLVEOC675U'}, 'requestParameters': {'sourceIPAddress': '115.75.112.32'}, 'responseElements': {'x-amz-request-id': '5WJYDW9AMYGD6AKQ', 'x-amz-id-2': 'IEJ1IpCkClfmg7idSzegTvO7GjimGXKDHg6+Bkc+Ud5fn3qxmjkvnwCgv43rcybiIJLXJRXiaEYT5zK3OpMkQpL7qsrVwHsfOWzRTdd0EiI='}, 's3': {'s3SchemaVersion': '1.0', 'configurationId': 'siem-logs-flow-a-create-events', 'bucket': {'name': 'siem-logs-flow-a', 'ownerIdentity': {'principalId': 'A14L2UW7BAOBV9'}, 'arn': 'arn:aws:s3:::siem-logs-flow-a'}, 'object': {'key': 'test_login_01.json', 'size': 215, 'eTag': '6abb74316f7447cb4627b244fc35600e', 'versionId': 'lINmSXHi_moP.NcNqp.Etwcyy5GPvv0b', 'sequencer': '006A7C2360B36DE976'}}}]} DEBUG: Message deleted from queue: siem-logs-flow-a-sqs-queue`
> 
> so I assume the logs is ingested by wazuh, but the rules was not triggered although wazuh-logtest filters the logs to rules correctly.
> 
> So, i just want to ask whether you can tell more about the logs format you are using and how you can ingest it to Wazuh and shows on Dashboard or alerts.json?

I think i found out my issue:

At first, when running both wazuh-logtest on Wazuh server and ruleset test on Wazuh UI, i used the log like: 

> {"integration": "aws", "aws": {"log_info": {...}, "actor": "bob@smartfit.vn", "action": "login", "target": "smartfit-portal", "outcome": "failure", "source_ip": "203.0.113.11", "timestamp": "2026-08-10T10:01:00Z", "source": "custom"}}

and it successfully filtered the log into the right rule.

However, upload that same logs for SQS to transport to Wazuh leads to errors, since Wazuh automatically wrap the log from SQS with:

> {"integration": "aws", "aws": {our logs live here}}

so my log when reaching Wazuh will become:

> {"integration": "aws", "aws": {{"integration": "aws", "aws": {"log_info": {...}, "actor": "bob@smartfit.vn", "action": "login", "target": "smartfit-portal", "outcome": "failure", "source_ip": "203.0.113.11", "timestamp": "2026-08-10T10:01:00Z", "source": "custom"}}} (nested json logs, which not matched with the field name in my rule)

So, my solution is: 

Log test in Wazuh server and Wazuh UI: 
> {"integration": "aws", "aws": {"log_info": {...}, "actor": "bob@smartfit.vn", "action": "login", "target": "smartfit-portal", "outcome": "failure", "source_ip": "203.0.113.11", "timestamp": "2026-08-10T10:01:00Z", "source": "custom"}}

Log ingest to Wazuh:
Simply this, Wazuh will wrap it later 

> {"actor": "bob@smartfit.vn", "action": "login", "target": "smartfit-portal", "outcome": "failure", "source_ip": "203.0.113.11", "timestamp": "2026-08-10T10:01:00Z"}
