### ISSUE TITLE
Fix empty commands list creation

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#27274]
## Description

When deleting a group that has no agent assigned, the following exception is thrown

```console
2024/12/12 14:48:28 ERROR: [Management API] Error executing API request locally: TransportError(500, 'org.opensearch.action.ActionRequestValidationException: Validation Failed: 1: no requests added;')
Traceback (most recent call last):
...
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/agent.py", line 561, in delete_groups
    response = await indexer_client.commands_manager.create(commands)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/indexer/commands.py", line 46, in create
    response = await self._client.transport.perform_request(
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/opensearchpy/_async/transport.py", line 423, in perform_request
    raise e
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/opensearchpy/_async/transport.py", line 385, in perform_request
    status, headers_response, data = await connection.perform_request(
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/opensearchpy/_async/http_aiohttp.py", line 346, in perform_request
    self._raise_error(
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/opensearchpy/connection/base.py", line 315, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
opensearchpy.exceptions.TransportError: TransportError(500, 'org.opensearch.action.ActionRequestValidationException: Validation Failed: 1: no requests added;')
```

This is because the commands manager expects at least one command in the request to its `POST /commands` endpoint and we are sending an empty list if no agents are assigned to it.

We should skip the commands creation if no agents belong to the group that is being removed.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Modified the logic to avoid sending requests with an empty list of commands.
