### ISSUE TITLE
Exit server execution if a subprocess fails to start

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#27313]
## Description

During the [server E2E tests](https://github.com/wazuh/wazuh/issues/27248), we noticed that if one of the server subprocesses didn't start as expected, the main execution flow continues and initiates the remaining ones.

Initially, we thought this should be the expected behavior because the daemons didn't depend on each other, but after advancements in the feature complete implementation design, all daemons will be related and linked to the others.

This issue aims to change this behavior to exit the script with a code `1` if any of the subprocesses fails during their execution.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by nico-stefani** [comment]
# Update

After implementing a mechanism for exiting after a daemon start failure we can see it working for `wazuh-engined` and `wazuh-apid`

<details><summary>wazuh-engined example</summary>
<p>

```console
root@1a3de75cd578:/wazuh# /usr/share/wazuh-server/bin/wazuh-server start
2024/12/18 15:20:08 INFO: [Cluster] [Main] Starting server (pid: 2685)
2024/12/18 15:20:08 INFO: [Master] [Main] Configuration server is not available, retrying...
2024/12/18 15:20:08 INFO: [Master] [Config Server] Started server process [2685]
2024/12/18 15:20:08 INFO: [Master] [Config Server] Waiting for application startup.
2024/12/18 15:20:08 INFO: [Master] [Config Server] Application startup complete.
2024/12/18 15:20:08 INFO: [Master] [Config Server] Uvicorn running on unix socket /run/wazuh-server/config-server.sock (Press CTRL+C to quit)
2024/12/18 15:20:09 INFO: [Local Server] [Main] Starting wazuh-engined
2024-12-18 15:20:09.567 2691:2691 info: Logging initialized.
2024/12/18 15:20:09 INFO: [Master] [Config Server]  - "GET /api/v1/config?sections=indexer,engine HTTP/1.1" 500
2024/12/18 15:20:09 ERROR: [Master] [Config Server] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/unix_server/config.py", line 36, in get_config
    config = CentralizedConfig.get_config_json(sections=validated_sections)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/wazuh/core/config/client.py", line 159, in get_config_json
    return cls._config.model_dump_json(include=[section.value for section in sections])
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/pydantic/main.py", line 477, in model_dump_json
    return self.__pydantic_serializer__.to_json(
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: PydanticSerializationError: Error calling function `convert_hosts_to_str`: AttributeError: 'NoneType' object has no attribute 'use_ssl'
2024-12-18 15:20:09.575 2691:2691 error: Error loading configuration: Error while loading configuration from API: 'HTTP response code said error' - '500'
2024/12/18 15:20:09 ERROR: [Cluster] [Main] Error starting wazuh-engined: return code 1
2024/12/18 15:20:09 INFO: [Cluster] [Main] Waiting for daemons shutdown.
```

</p>
</details> 

<details><summary>wazuh-apid example</summary>
<p>

```console
root@1a3de75cd578:/wazuh# /usr/share/wazuh-server/bin/wazuh-server start
2024/12/18 15:24:45 INFO: [Cluster] [Main] Starting server (pid: 2699)
2024/12/18 15:24:45 INFO: [Master] [Main] Configuration server is not available, retrying...
2024/12/18 15:24:45 INFO: [Master] [Config Server] Started server process [2699]
2024/12/18 15:24:45 INFO: [Master] [Config Server] Waiting for application startup.
2024/12/18 15:24:45 INFO: [Master] [Config Server] Application startup complete.
2024/12/18 15:24:45 INFO: [Master] [Config Server] Uvicorn running on unix socket /run/wazuh-server/config-server.sock (Press CTRL+C to quit)
2024/12/18 15:24:46 INFO: [Local Server] [Main] Starting wazuh-engined
2024-12-18 15:24:46.983 2705:2705 info: Logging initialized.
2024/12/18 15:24:46 INFO: [Master] [Config Server]  - "GET /api/v1/config?sections=indexer,engine HTTP/1.1" 200
2024-12-18 15:24:46.991 2705:2705 info: Store initialized.
2024-12-18 15:24:46.991 2705:2705 info: RBAC initialized.
2024-12-18 15:24:46.992 2705:2705 info: MetricsManager: Created new scope: (KVDB)
2024-12-18 15:24:47.035 2705:2705 info: KVDB initialized.
2024-12-18 15:24:47.035 2705:2705 info: Geo initialized.
2024-12-18 15:24:47.050 2705:2705 info: Schema initialized.
2024-12-18 15:24:47.061 2705:2705 info: Loaded timezone database version: '2024a'
2024-12-18 15:24:47.065 2705:2705 info: HLP initialized.
2024-12-18 15:24:47.073 2705:2705 info: Indexer Connector initialized.
2024-12-18 15:24:47.073 2705:2705 info: Builder initialized.
2024-12-18 15:24:47.073 2705:2705 info: Catalog initialized.
2024-12-18 15:24:47.073 2705:2705 info: Policy manager initialized.
2024-12-18 15:24:47.073 2705:2705 info: MetricsManager: Created new scope: (EventQueue)
2024-12-18 15:24:47.073 2705:2705 info: MetricsManager: Created new scope: (EventQueueDelta)
2024-12-18 15:24:47.074 2705:2705 info: No flooding file provided, the queue will not be flooded.
2024-12-18 15:24:47.075 2705:2705 info: MetricsManager: Created new scope: (TestQueue)
2024-12-18 15:24:47.075 2705:2705 info: MetricsManager: Created new scope: (TestQueueDelta)
2024-12-18 15:24:47.083 2705:2705 info: No flooding file provided, the queue will not be flooded.
2024-12-18 15:24:47.084 2705:2705 warning: Router: router/tester/0 table is empty
2024-12-18 15:24:47.179 2705:2705 info: Router initialized.
2024-12-18 15:24:47.186 2705:2705 error: Error opening the database: Couldn't find column family: 'vendor_map', trying to re-download the feed.
2024-12-18 15:24:47.186 2705:2705 info: MetricsManager: Created new scope: (endpointAPI)
2024-12-18 15:24:47.186 2705:2705 info: MetricsManager: Created new scope: (endpointAPIRate)
2024-12-18 15:24:47.188 2705:2705 info: Starting the server...
2024/12/18 15:24:48 INFO: [Local Server] [Main] Started wazuh-engined (pid: 2705)
2024/12/18 15:24:48 INFO: [Local Server] [Main] Starting wazuh-comms-apid
2024/12/18 15:24:50 INFO: [Communications API] Starting API
2024/12/18 15:24:50 INFO: [Communications API] Listening on localhost:27000
2024/12/18 15:24:50 INFO: [Communications API] Starting gunicorn 22.0.0
2024/12/18 15:24:50 INFO: [Communications API] Listening at: https://127.0.0.1:27000 (3142)
2024/12/18 15:24:50 INFO: [Communications API] Using worker: uvicorn.workers.UvicornWorker
2024/12/18 15:24:50 INFO: [Communications API] Booting worker with pid: 3190
2024/12/18 15:24:50 INFO: [Communications API] Booting worker with pid: 3191
2024/12/18 15:24:50 INFO: [Communications API] Started server process [3142]
2024/12/18 15:24:50 INFO: [Communications API] Waiting for application startup.
2024/12/18 15:24:50 INFO: [Communications API] Application startup complete.
2024/12/18 15:24:50 INFO: [Communications API] Uvicorn running on unix socket /run/wazuh-server/comms-api.sock (Press CTRL+C to quit)
2024/12/18 15:24:50 INFO: [Communications API] Booting worker with pid: 3192
2024/12/18 15:24:50 INFO: [Communications API] Started server process [3192]
2024/12/18 15:24:50 INFO: [Communications API] Waiting for application startup.
2024/12/18 15:24:50 INFO: [Communications API] Application startup complete.
2024/12/18 15:24:50 INFO: [Communications API] Booting worker with pid: 3193
2024/12/18 15:24:50 INFO: [Communications API] Started server process [3193]
2024/12/18 15:24:50 INFO: [Communications API] Waiting for application startup.
2024/12/18 15:24:50 INFO: [Communications API] Application startup complete.
2024/12/18 15:24:50 INFO: [Local Server] [Main] Started wazuh-comms-apid (pid: 3142)
2024/12/18 15:24:50 INFO: [Local Server] [Main] Starting wazuh-apid
2024/12/18 15:24:51 INFO: [Management API] HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2024/12/18 15:24:51 ERROR: [Management API] 2003 - Error loading SSL/TLS certificates: Ensure the certificates have the correct permissions.
Traceback (most recent call last):
  File "/usr/share/wazuh-server/api/scripts/wazuh_apid.py", line 107, in configure_ssl
    private_key = generate_private_key(config.key)
  File "/usr/share/wazuh-server/framework/python/lib/python3.10/site-packages/api/configuration.py", line 121, in generate_private_key
    with open(private_key_path, 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/etc/wazuh-server/certs/api.key'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/wazuh-server/api/scripts/wazuh_apid.py", line 331, in <module>
    configure_ssl(uvicorn_params, management_config.ssl)
  File "/usr/share/wazuh-server/api/scripts/wazuh_apid.py", line 162, in configure_ssl
    raise error from exc
api.api_exception.APIError: 2003 - Error loading SSL/TLS certificates: Ensure the certificates have the correct permissions.
2024/12/18 15:24:52 ERROR: [Cluster] [Main] Error starting wazuh-apid: return code 1
2024/12/18 15:24:52 INFO: [Cluster] [Main] Shutting down wazuh-engined (pid: 2705)
2024/12/18 15:24:52 INFO: [Cluster] [Main] Shutting down wazuh-comms-apid (pid: 3142)
2024/12/18 15:24:52 INFO: [Cluster] [Main] Waiting for daemons shutdown.
2024/12/18 15:24:52 INFO: [Communications API] Handling signal: term
2024/12/18 15:24:52 ERROR: [Communications API] Worker (pid:3190) was sent SIGTERM!
2024/12/18 15:24:52 ERROR: [Communications API] Worker (pid:3191) was sent SIGTERM!
2024/12/18 15:24:52 INFO: [Communications API] Shutting down
2024/12/18 15:24:52 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/18 15:24:52 INFO: [Communications API] Shutting down
2024/12/18 15:24:52 INFO: [Communications API] Error while closing socket [Errno 9] Bad file descriptor
2024/12/18 15:24:52 INFO: [Communications API] Waiting for application shutdown.
2024/12/18 15:24:52 INFO: [Communications API] Application shutdown complete.
2024/12/18 15:24:52 INFO: [Communications API] Finished server process [3192]
2024/12/18 15:24:52 INFO: [Communications API] Worker exiting (pid: 3192)
2024/12/18 15:24:52 INFO: [Communications API] Waiting for application shutdown.
2024/12/18 15:24:52 INFO: [Communications API] Application shutdown complete.
2024/12/18 15:24:52 INFO: [Communications API] Finished server process [3193]
2024/12/18 15:24:52 INFO: [Communications API] Worker exiting (pid: 3193)
2024/12/18 15:24:52 INFO: [Communications API] Shutting down: Master
2024/12/18 15:24:52 INFO: [Communications API] Shutting down MuxDemuxRunner
```

</p>
</details>

Related to `wazuh-comms-apid` I found a problem with the shutdown of the child processes and the script's exit.
As we can see below, when an error occurs, the server process continues because it never gets the `exit 1` code.

<details><summary>wazuh-comms-apid example</summary>
<p>

```console
root@1a3de75cd578:/wazuh# /usr/share/wazuh-server/bin/wazuh-server start
2024/12/18 15:29:43 INFO: [Cluster] [Main] Starting server (pid: 3222)
2024/12/18 15:29:43 INFO: [Master] [Main] Configuration server is not available, retrying...
2024/12/18 15:29:43 INFO: [Master] [Config Server] Started server process [3222]
2024/12/18 15:29:43 INFO: [Master] [Config Server] Waiting for application startup.
2024/12/18 15:29:43 INFO: [Master] [Config Server] Application startup complete.
2024/12/18 15:29:43 INFO: [Master] [Config Server] Uvicorn running on unix socket /run/wazuh-server/config-server.sock (Press CTRL+C to quit)
2024/12/18 15:29:44 INFO: [Local Server] [Main] Starting wazuh-engined
2024-12-18 15:29:44.661 3228:3228 info: Logging initialized.
2024/12/18 15:29:44 INFO: [Master] [Config Server]  - "GET /api/v1/config?sections=indexer,engine HTTP/1.1" 200
2024-12-18 15:29:44.670 3228:3228 info: Store initialized.
2024-12-18 15:29:44.670 3228:3228 info: RBAC initialized.
2024-12-18 15:29:44.670 3228:3228 info: MetricsManager: Created new scope: (KVDB)
2024-12-18 15:29:44.715 3228:3228 info: KVDB initialized.
2024-12-18 15:29:44.715 3228:3228 info: Geo initialized.
2024-12-18 15:29:44.729 3228:3228 info: Schema initialized.
2024-12-18 15:29:44.741 3228:3228 info: Loaded timezone database version: '2024a'
2024-12-18 15:29:44.745 3228:3228 info: HLP initialized.
2024-12-18 15:29:44.752 3228:3228 info: Indexer Connector initialized.
2024-12-18 15:29:44.752 3228:3228 info: Builder initialized.
2024-12-18 15:29:44.752 3228:3228 info: Catalog initialized.
2024-12-18 15:29:44.752 3228:3228 info: Policy manager initialized.
2024-12-18 15:29:44.752 3228:3228 info: MetricsManager: Created new scope: (EventQueue)
2024-12-18 15:29:44.752 3228:3228 info: MetricsManager: Created new scope: (EventQueueDelta)
2024-12-18 15:29:44.753 3228:3228 info: No flooding file provided, the queue will not be flooded.
2024-12-18 15:29:44.754 3228:3228 info: MetricsManager: Created new scope: (TestQueue)
2024-12-18 15:29:44.754 3228:3228 info: MetricsManager: Created new scope: (TestQueueDelta)
2024-12-18 15:29:44.763 3228:3228 info: No flooding file provided, the queue will not be flooded.
2024-12-18 15:29:44.764 3228:3228 warning: Router: router/tester/0 table is empty
2024-12-18 15:29:44.860 3228:3228 info: Router initialized.
2024-12-18 15:29:44.869 3228:3228 error: Error opening the database: Couldn't find column family: 'vendor_map', trying to re-download the feed.
2024-12-18 15:29:44.869 3228:3228 info: MetricsManager: Created new scope: (endpointAPI)
2024-12-18 15:29:44.869 3228:3228 info: MetricsManager: Created new scope: (endpointAPIRate)
2024-12-18 15:29:44.871 3228:3228 info: Starting the server...
2024/12/18 15:29:46 INFO: [Local Server] [Main] Started wazuh-engined (pid: 3228)
2024/12/18 15:29:46 INFO: [Local Server] [Main] Starting wazuh-comms-apid
2024/12/18 15:29:47 INFO: [Communications API] Starting API
2024/12/18 15:29:47 INFO: [Communications API] Listening on localhost:27000
2024/12/18 15:29:47 ERROR: [Communications API] Error when trying to start the Wazuh Communications API. Error 2702 - Ensure the certificates have the correct permissions: [Errno 13] Permission denied: '/etc/wazuh-server/certs/api.key'
2024/12/18 15:29:47 INFO: [Communications API] Shutting down MuxDemuxRunner
2024/12/18 15:29:48 INFO: [Local Server] [Main] Started wazuh-comms-apid (pid: 3665)
2024/12/18 15:29:48 INFO: [Local Server] [Main] Starting wazuh-apid
2024/12/18 15:29:49 INFO: [Management API] Starting API
2024/12/18 15:29:49 INFO: [Management API] Checking RBAC database integrity...
2024/12/18 15:29:49 INFO: [Management API] /var/lib/wazuh-server/rbac.db file was detected
2024/12/18 15:29:49 INFO: [Management API] RBAC database integrity check finished successfully
2024/12/18 15:29:50 INFO: [Local Server] [Main] Started wazuh-apid (pid: 3721)
2024/12/18 15:29:50 ERROR: [Master] [Main] Failed loading SSL context: [SSL] PEM lib (_ssl.c:3900). Using default one.
2024/12/18 15:29:50 INFO: [Local Server] [Main] Serving on /run/wazuh-server/local-server.sock
2024/12/18 15:29:50 INFO: [Master] [Main] Serving on ('::1', 1516, 0, 0)
2024/12/18 15:29:50 INFO: [Master] [Local integrity] Starting.
2024/12/18 15:29:50 INFO: [Master] [Local integrity] Finished in 0.002s. Calculated metadata of 2 files.
2024/12/18 15:29:50 INFO: [Management API] Listening on ['localhost', '::1']:55000.
2024/12/18 15:29:50 INFO: [Management API] Getting installation UID...
2024/12/18 15:29:50 INFO: [Management API] Getting updates information...
2024/12/18 15:29:58 INFO: [Master] [Local integrity] Starting.
2024/12/18 15:29:58 INFO: [Master] [Local integrity] Finished in 0.002s. Calculated metadata of 2 files.
```

</p>
</details> 

If we call the `wazuh-comms-apid` directly we have a better look at the bahavior

```console
root@1a3de75cd578:/wazuh# /usr/share/wazuh-server/bin/wazuh-comms-apid
2024/12/18 15:32:24 INFO: [Communications API] Starting API
2024/12/18 15:32:24 INFO: [Communications API] Listening on localhost:27000
2024/12/18 15:32:24 ERROR: [Communications API] Error when trying to start the Wazuh Communications API. Error 2702 - Ensure the certificates have the correct permissions: [Errno 13] Permission denied: '/etc/wazuh-server/certs/api.key'
2024/12/18 15:32:24 INFO: [Communications API] Shutting down MuxDemuxRunner
```
```console
root@1a3de75cd578:/wazuh# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   7604  3840 pts/0    SNs  15:07   0:00 bash
root        4759  0.0  0.0   2800  1664 pts/0    SN+  15:32   0:00 /bin/sh /usr/share/wazuh-server/bin/wazuh-comms-apid
wazuh-s+    4764  3.3  0.4 238628 96700 pts/0    SNl+ 15:32   0:01 /usr/share/wazuh-server/framework/python/bin/python3 /usr/share/wazuh-server/apis/scripts/wazuh_comms_apid.py
wazuh-s+    4782  0.0  0.0      0     0 pts/0    ZN+  15:32   0:00 [python3] <defunct>
wazuh-s+    4784  0.0  0.3 160184 73988 pts/0    SN+  15:32   0:00 /usr/share/wazuh-server/framework/python/bin/python3 /usr/share/wazuh-server/apis/scripts/wazuh_comms_apid.py
root        4806  0.0  0.0   7604  4224 pts/1    SNs  15:32   0:00 bash
root        4820  0.0  0.0  10880  4352 pts/1    RN+  15:33   0:00 ps aux
```

We need to decide if we attack the problem here or in #27265
