### ISSUE TITLE
Flask API: Implement CIS-CAT endpoints

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#2840]
This issue is part of https://github.com/wazuh/wazuh/issues/2640.

Pending CIS-CAT endpoints to implement:
- [x] GET/ciscat/{agent_id}/results (06e6698ad6033f319a5e1d56a80f9e3a74737ec6)
- [x] Implement and run ciscat unit test

**Comment by mgmacias95** [comment]
The `search` parameter raised an exception that made the logger break:

```
2019/03/15 15:55:18 INFO:  127.0.0.1 - -  "GET /ciscat/004/results&search=ubuntu HTTP/1.1" 404 -
--- Logging error ---
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 133, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 117, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/ciscat.py", line 19, in get_results_agent
    valid_select_fields=valid_select_fields, table=table, nested=nested, array=array)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/syscollector.py", line 27, in get_item_agent
    search['fields'] = valid_select_fields
TypeError: 'str' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 622, in format
    s = self.formatMessage(record)
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 591, in formatMessage
    return self._style.format(record)
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 441, in format
    return self._fmt.format(**record.__dict__)
KeyError: 'user'
Call stack:
  File "/var/ossec/framework/python/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/var/ossec/framework/python/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/var/ossec/framework/python/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/var/ossec/framework/python/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/var/ossec/framework/python/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/var/ossec/framework/python/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Werkzeug-0.14.1-py3.7.egg/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/var/ossec/framework/python/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Werkzeug-0.14.1-py3.7.egg/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Werkzeug-0.14.1-py3.7.egg/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Werkzeug-0.14.1-py3.7.egg/werkzeug/serving.py", line 258, in execute    application_iter = app(environ, start_response)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/security.py", line 300, in wrapper
    return function(request)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/validation.py", line
347, in wrapper
    return function(request)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/api-3.9.0-py3.7.egg/api/controllers/ciscat_controller.py", line 69,
in get_agents_cistat_results
    data = loop.run_until_complete(dapi.distribute_function())
  File "/var/ossec/framework/python/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/var/ossec/framework/python/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/var/ossec/framework/python/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/var/ossec/framework/python/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 83, in distribute_function
    return await self.forward_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 218, in forward_request
    response = await forward(next(iter(nodes.items())))
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 198, in forward
    response = await self.distribute_function()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 77, in distribute_function
    return await self.execute_local_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 145, in execute_local_request
    self.logger.error("Error executing API request locally: {}".format(e))
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/wlogging.py", line 108, in error
    self._log(logging.ERROR, msg, args, **kws)
Message: "Error executing API request locally: 'str' object does not support item assignment"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 133, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 117, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/ciscat.py", line 19, in get_results_agent
    valid_select_fields=valid_select_fields, table=table, nested=nested, array=array)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/syscollector.py", line 27, in get_item_agent
    search['fields'] = valid_select_fields
TypeError: 'str' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 622, in format
    s = self.formatMessage(record)
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 591, in formatMessage
    return self._style.format(record)
  File "/var/ossec/framework/python/lib/python3.7/logging/__init__.py", line 441, in format
    return self._fmt.format(**record.__dict__)
KeyError: 'user'
Call stack:
  File "/var/ossec/framework/python/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/var/ossec/framework/python/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/var/ossec/framework/python/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/var/ossec/framework/python/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/var/ossec/framework/python/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/var/ossec/framework/python/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Werkzeug-0.14.1-py3.7.egg/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/var/ossec/framework/python/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Werkzeug-0.14.1-py3.7.egg/werkzeug/serving.py", line 328, in handle_one_request
    return self.run_wsgi()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Werkzeug-0.14.1-py3.7.egg/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Werkzeug-0.14.1-py3.7.egg/werkzeug/serving.py", line 258, in execute    application_iter = app(environ, start_response)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/Flask-1.0.2-py3.7.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/security.py", line 300, in wrapper
    return function(request)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/validation.py", line
347, in wrapper
    return function(request)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/connexion-2.2.0-py3.7.egg/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/api-3.9.0-py3.7.egg/api/controllers/ciscat_controller.py", line 69,
in get_agents_cistat_results
    data = loop.run_until_complete(dapi.distribute_function())
  File "/var/ossec/framework/python/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/var/ossec/framework/python/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/var/ossec/framework/python/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/var/ossec/framework/python/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 83, in distribute_function
    return await self.forward_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 218, in forward_request
    response = await forward(next(iter(nodes.items())))
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 198, in forward
    response = await self.distribute_function()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 77, in distribute_function
    return await self.execute_local_request()
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/dapi/dapi.py", line 145, in execute_local_request
    self.logger.error("Error executing API request locally: {}".format(e))
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/wlogging.py", line 108, in error
    self._log(logging.ERROR, msg, args, **kws)
Message: "Error executing API request locally: 'str' object does not support item assignment"
Arguments: ()
2019/03/15 15:55:24 INFO:  127.0.0.1 - -  "GET /ciscat/004/results?search=ubuntu HTTP/1.1" 200 -
```

**Comment by crd1985** [comment]
This issue is blocked by https://github.com/wazuh/wazuh/issues/2843

**Comment by davidjiglesias** [comment]
Status update
## Summary
Today I've finished the implementation of the endpoints and the integration tests for ciscat. 

## Tasks
* [2h] Configure wazuh agent to run CIS-CAT scans
* [4h] Implement and run ciscat_endpoints integrated tests
* [1h] Add changes to ciscat_controller to provide a response matching the spec

## Difficulties
* Configuring CIS-CAT for the agent was difficult as the documentation available in https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/ciscat/ciscat.html?highlight=ciscat is really futile.
```
    LastScan:
      type: object
      properties:
        end:
          type: string
          format: date-time
          description: 'Date when the latest scan finished. If it is in progress, "n/a" will be returned.'
        start:
          type: string
          format: date-time
          description: 'Date when the latest scan started. If no scans have been run, "n/a" will be returned.'
```
## Tests performed
```
==================== 15 passed, 2 warnings in 0.98 seconds =====================
```
## Pending
Implement cache if endpoint requires it

**Comment by davidjiglesias** [comment]
* Unit test results:
```
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.4.2, py-1.8.0, pluggy-0.11.0
rootdir: /opt/project/framework
plugins: tavern-0.26.3collected 1 item

test_ciscat.py .                                                         [100%]

=========================== 1 passed in 0.60 seconds ===========================
```

**Comment by davidjiglesias** [comment]
* Updated and run unit test:
```
============================ test session starts ============================
platform linux -- Python 3.7.2, pytest-4.5.0, py-1.8.0, pluggy-0.11.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin
plugins: tavern-0.26.3, cov-2.7.1
collected 2 items                                                           

unit/test_ciscat.py::TestCiscat::test_get_ciscat_results PASSED       [ 50%]
unit/test_ciscat.py::TestCiscat::test_get_results_agent PASSED        [100%]

========================= 2 passed in 0.12 seconds ==========================
```

**Comment by davidjiglesias** [comment]
Status update
## Summary
Today I've completed the implementation of a test environment for ciscat module. 

## Tasks
* Implement docker environment for automatic CIS-CAT integration tests
* Update and run unit tests
* Update and run integration tests

## Difficulties
* Obtaining an automatic docker environment with a wazuh cluster and  a bunch of agents with cis-cat module active and running

## Tests performed
Integration tests:
```
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.5.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/davidjiglesias/git/wazuh/api
plugins: tavern-0.26.4
collected 9 items                                                              

test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results PASSED [ 11%]
test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results[profile] PASSED [ 22%]
test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results[score] PASSED [ 33%]
test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results[error] PASSED [ 44%]
test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results[fail] PASSED [ 55%]
test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results[benchmark] PASSED [ 66%]
test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results[pass] PASSED [ 77%]
test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results[notchecked] PASSED [ 88%]
test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results[unknown] PASSED [100%]

=============================== warnings summary ===============================
test/integration/test_ciscat_endpoints.tavern.yaml::GET /ciscat/{agent_id}/results
  /home/davidjiglesias/.local/lib/python3.6/site-packages/jwt/api_jwt.py:81: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 9 passed, 1 warnings in 176.52 seconds ====================
```
Unit tests:
```
==================================== test session starts ====================================
platform linux -- Python 3.7.2, pytest-4.5.0, py-1.8.0, pluggy-0.12.0 -- /var/ossec/framework/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /var/ossec/framework/python/bin
plugins: cov-2.7.1, tavern-0.26.4
collected 1 item                                                                            

unit/test_ciscat.py::test_get_ciscat_results PASSED                                   [100%]

================================= 1 passed in 0.11 seconds ==================================
```
Coverage:
```
    Stmts   Miss  Cover   Missing
------------------------------------------------------------------------------------------------------------------------------
/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/ciscat.py       6      0   100%

```
## Pending
