### ISSUE TITLE
Redesign of error handling in new API

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#2843]
Currently, error handling can be improved in the following ways:
* [x] Extend the catalog of http status codes in API responses
* [x] Improve error messages according to best practices:
   * Show relevant information to user
   * Give a clear explanation of what's going on
   * Propose a way to find a solution
* [x] Show full traceback in api.log when an unexpected error occurs, giving useful information to developers.

**Comment by crd1985** [comment]
# Status update
## Summary
Development is almost finished. I'm trying to find a good solution to tell the user the exact node or nodes where there had been any exception. This is very important to report errors effectively without having to search in every cluster.log file or master's api.log.

Below there is an example of error handling without node information:
```
019/04/08 17:15:52 INFO: [Worker worker1] [Agent info] Compressing files
2019/04/08 17:15:52 INFO: [Worker worker1] [Agent info] Sending compressed file to master
2019/04/08 17:15:52 INFO: [Worker worker1] [Agent info] Worker files sent to master.
2019/04/08 17:15:59 INFO: [Worker worker1] [Integrity] Permission to synchronize granted.
2019/04/08 17:15:59 INFO: [Worker worker1] [Integrity] Compressing files
2019/04/08 17:15:59 INFO: [Worker worker1] [Integrity] Sending compressed file to master
2019/04/08 17:15:59 INFO: [Worker worker1] [Integrity] Worker files sent to master.
2019/04/08 17:15:59 INFO: [Worker worker1] [Integrity] The master has verified that the integrity is right.
2019/04/08 17:15:59 INFO: [Cluster] [D API] Receiving request: restart_agents from master (524387)
2019/04/08 17:15:59 ERROR: [Cluster] [D API] Wazuh Internal Error: Fake error
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh/cluster/dapi/dapi.py", line 142, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh/cluster/dapi/dapi.py", line 126, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh/agent.py", line 915, in restart_agents
    raise WazuhInternalError(1000, extra_message="Fake error")
wazuh.exception.WazuhInternalError: Error 1000 - Wazuh Internal Error: Fake error
2019/04/08 17:16:02 INFO: [Worker worker1] [Agent info] Starting to send agent status files
2019/04/08 17:16:02 INFO: [Worker worker1] [Agent info] Permission to synchronize granted.
2019/04/08 17:16:02 INFO: [Worker worker1] [Agent info] Compressing files
2019/04/08 17:16:02 INFO: [Worker worker1] [Agent info] Sending compressed f
```
And this is an example of error reported as an API response:
```
root@e9f9af01b337:/# curl -XPUT "http://localhost:55000/agents/restart"
{
  "detail": "Wazuh Internal Error: Fake error",
  "remediation": null,
  "status": 500,
  "title": "Wazuh Internal Error",
  "type": "about:blank"
}
```

## Difficulties
* I spent a lot of time refactoring dapi.py script in order to remove hardcoded logic dependent on specific endpoints.
* I have had to implement functions to make Exceptions JSON serializable
* I have developed a new `WazuhResult` class to encapsulate the necessary code to merge results among cluster nodes

## Tests performed
Unit tests to ensure JSON encode/decode for `WazuhException`, `WazuhResult` and `DistributedAPI` objects are JSON serializable, which is critical to get cluster working.
```
root@e9f9af01b337:/# /var/ossec/framework/python/bin/pytest /var/ossec/framework/python/lib/python3.7/site-packages/wazuh/cluster/dapi/tests/test_dapi.py 
================================================ test session starts =================================================
platform linux -- Python 3.7.2, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
rootdir: /var/ossec/framework/python/lib/python3.7/site-packages/wazuh/cluster/dapi/tests
collected 7 items                                                                                                    

var/ossec/framework/python/lib/python3.7/site-packages/wazuh/cluster/dapi/tests/test_dapi.py .......           [100%]

============================================== 7 passed in 0.09 seconds ==============================================
```
## Pending
* I will add the exception code to allow API users to differentiate several '500' or '400' errors
* Find a way to combine simultaneous WazuhExceptions in different node in a unique response without violating the standard.
