### ISSUE TITLE
Manager fails to start when installed from /opt package

### ISSUE THREAD

**Issue by juan70** [wazuh/wazuh#2913]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3909 (rc4) | Manager | Packages `/opt` version | Debian 9/CentOS 7 |

Problem description
--
The `/opt` packages of wazuh manager are installed correctly in the right place `/opt/ossec`. But the manager fails to start.

It seems as though `ossec.conf` is expected to be in `/var/ossec` instead of `/opt/ossec`.

The error occurs when installing in `/opt` from an RPM package on CentOS 7 and from a DEB package on Debian 9.

The DEB package has been created today:
```
# cat /etc/ossec-init.conf 
DIRECTORY="/opt/ossec"
NAME="Wazuh"
VERSION="v3.9.0"
REVISION="3909"
DATE="Tue Mar 26 07:15:09 GMT 2019"
TYPE="server"
```
On CentOS7, the package date is `DATE="Mon Mar 25 16:07:58 UTC 2019"` (just yesterday), but VERSION and REVISION are the same.
```
# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-03-26 07:15:31 GMT; 4min 54s ago

Mar 26 07:15:31 deb9man env[27871]:   File "/opt/ossec/framework/scripts/wazuh-clusterd.py", line 151, in <module>
Mar 26 07:15:31 deb9man env[27871]:     cluster_configuration = cluster.read_config(config_file=args.config_file)
Mar 26 07:15:31 deb9man env[27871]:   File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/cluster.py", line 112, in read_config
Mar 26 07:15:31 deb9man env[27871]:     raise WazuhException(3006, e.message)
Mar 26 07:15:31 deb9man env[27871]: wazuh.exception.WazuhException: Error 3006 - Error reading cluster configuration: Error getting configuration: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'
Mar 26 07:15:31 deb9man env[27871]: wazuh-clusterd: Configuration error. Exiting
Mar 26 07:15:31 deb9man systemd[1]: wazuh-manager.service: Control process exited, code=exited status=1
Mar 26 07:15:31 deb9man systemd[1]: Failed to start Wazuh manager.
Mar 26 07:15:31 deb9man systemd[1]: wazuh-manager.service: Unit entered failed state.
Mar 26 07:15:31 deb9man systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
```
```
# journalctl -xe
...
-- Unit wazuh-manager.service has begun starting up.
Mar 26 07:15:31 deb9man env[27871]: Traceback (most recent call last):
Mar 26 07:15:31 deb9man env[27871]:   File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/configuration.py", line 445, in get_ossec_conf
Mar 26 07:15:31 deb9man env[27871]:     xml_data = load_wazuh_xml(conf_file)
Mar 26 07:15:31 deb9man env[27871]:   File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/utils.py", line 494, in load_wazuh_xml
Mar 26 07:15:31 deb9man env[27871]:     with open(xml_path) as f:
Mar 26 07:15:31 deb9man env[27871]: FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'
Mar 26 07:15:31 deb9man env[27871]: During handling of the above exception, another exception occurred:
Mar 26 07:15:31 deb9man env[27871]: Traceback (most recent call last):
Mar 26 07:15:31 deb9man env[27871]:   File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/cluster.py", line 105, in read_config
Mar 26 07:15:31 deb9man env[27871]:     config_cluster = get_ossec_conf(section='cluster', conf_file=config_file)
Mar 26 07:15:31 deb9man env[27871]:   File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/configuration.py", line 450, in get_ossec_conf
Mar 26 07:15:31 deb9man env[27871]:     raise WazuhException(1101, str(e))
Mar 26 07:15:31 deb9man env[27871]: wazuh.exception.WazuhException: Error 1101 - Error getting configuration: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'
Mar 26 07:15:31 deb9man env[27871]: During handling of the above exception, another exception occurred:
Mar 26 07:15:31 deb9man env[27871]: Traceback (most recent call last):
Mar 26 07:15:31 deb9man env[27871]:   File "/opt/ossec/framework/scripts/wazuh-clusterd.py", line 151, in <module>
Mar 26 07:15:31 deb9man env[27871]:     cluster_configuration = cluster.read_config(config_file=args.config_file)
Mar 26 07:15:31 deb9man env[27871]:   File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/cluster/cluster.py", line 112, in read_config
Mar 26 07:15:31 deb9man env[27871]:     raise WazuhException(3006, e.message)
Mar 26 07:15:31 deb9man env[27871]: wazuh.exception.WazuhException: Error 3006 - Error reading cluster configuration: Error getting configuration: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'
Mar 26 07:15:31 deb9man env[27871]: wazuh-clusterd: Configuration error. Exiting
Mar 26 07:15:31 deb9man systemd[1]: wazuh-manager.service: Control process exited, code=exited status=1
Mar 26 07:15:31 deb9man systemd[1]: Failed to start Wazuh manager.
-- Subject: Unit wazuh-manager.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit wazuh-manager.service has failed.
-- 
-- The result is failed.
```

**Comment by Zenidd** [comment]
Hello @juan70,
<br></br>
I have recreated the using packages in both systems:


 - CentOS 7 Wazuh manager status after package install on /opt directory:

```
[root@workerCentos ossec]# /opt/ossec/bin/ossec-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
wazuh-db is running...
ossec-authd is running...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...
[root@workerCentos ossec]# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since jue 2019-05-23 14:20:41 UTC; 2min 56s ago
  Process: 8474 ExecStart=/usr/bin/env ${DIRECTORY}/bin/ossec-control start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-manager.service
           ├─8539 /opt/ossec/bin/ossec-authd
           ├─8546 /opt/ossec/bin/wazuh-db
           ├─8565 /opt/ossec/bin/ossec-execd
           ├─8573 /opt/ossec/bin/ossec-analysisd
           ├─8580 /opt/ossec/bin/ossec-syscheckd
           ├─8588 /opt/ossec/bin/ossec-remoted
           ├─8612 /opt/ossec/bin/ossec-logcollector
           ├─8618 /opt/ossec/bin/ossec-monitord
           └─8624 /opt/ossec/bin/wazuh-modulesd

may 23 14:20:39 workerCentos env[8474]: Started wazuh-db...
may 23 14:20:39 workerCentos env[8474]: Started ossec-execd...
may 23 14:20:39 workerCentos env[8474]: Started ossec-analysisd...
may 23 14:20:39 workerCentos env[8474]: Started ossec-syscheckd...
may 23 14:20:39 workerCentos env[8474]: Started ossec-remoted...
may 23 14:20:39 workerCentos env[8474]: Started ossec-logcollector...
may 23 14:20:39 workerCentos env[8474]: Started ossec-monitord...
may 23 14:20:39 workerCentos env[8474]: Started wazuh-modulesd...
may 23 14:20:41 workerCentos env[8474]: Completed.
may 23 14:20:41 workerCentos systemd[1]: Started Wazuh manager.
```
<br></br>
 - Debian 9 Wazuh manager status after package install on /opt directory:
```
root@debian9Worker:/opt/ossec/bin# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor pr
   Active: active (exited) since Thu 2019-05-23 23:38:50 PDT; 2min 54s ago

May 23 23:38:48 debian9Worker env[27729]: Started wazuh-db...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-execd...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-analysisd...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-syscheckd...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-remoted...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-logcollector...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-monitord...
May 23 23:38:48 debian9Worker env[27729]: Started wazuh-modulesd...
May 23 23:38:50 debian9Worker env[27729]: Completed.
May 23 23:38:50 debian9Worker systemd[1]: Started Wazuh manager.
lines 1-14/14 (END)...skipping...
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2019-05-23 23:38:50 PDT; 2min 54s ago

May 23 23:38:48 debian9Worker env[27729]: Started wazuh-db...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-execd...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-analysisd...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-syscheckd...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-remoted...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-logcollector...
May 23 23:38:48 debian9Worker env[27729]: Started ossec-monitord...
May 23 23:38:48 debian9Worker env[27729]: Started wazuh-modulesd...
May 23 23:38:50 debian9Worker env[27729]: Completed.
May 23 23:38:50 debian9Worker systemd[1]: Started Wazuh manager.


```

Managers installed by packages method on CentOS7 and Debian 9 do not present problems at startup. 
I'm going to close the ticket, feel free to re-open it or create a new one if needed.
<br></br>
Best regards,

Juan Pablo Sáez
