### ISSUE TITLE
Prevent wazuh-clusterd crashing badly when /tmp has no proper permissions 

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#3327]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0-any | wazuh-clusterd | Manager | Any | Any |

`wazuh-clusterd` uses the Python module `criptography` which needs read & write permission to `/tmp` folder (thx @BraulioV for researching, https://github.com/pyca/cryptography/blob/master/vectors/cryptography_vectors/x509/PKITS_data/pkits.ldif). Otherwise, a `MemoryError` is raised when calling https://github.com/wazuh/wazuh/blob/0d45a89a78c3ddd9883810d8dd97d03b28c9cbb4/framework/wazuh/cluster/common.py#L156

Subtasks:
- [x] Add a pre-check to abort clusterd in a smart way and tell the user the problem
- [x] Test it!

**Comment by JmZero** [comment]
Status update
## Summary
I've tried to replicate this error but I haven't succeeded. 
I added a pre-check so that when using the cryptography module and return a `MemoryError` I skipped an exception indicating to the user that the `/tmp` directory doesn't have permissions.

## Tasks
* [3 h] Try to replicate the error
* [30 min] Create new exception and add a pre-check
* [1,5 h] Create unit test.

## Difficulties
* First time I do unit tests

## Pending
* Finish unit testing

**Comment by crd1985** [comment]
The issue is not fully solved. See the following traceback:
```
./bin/wazuh-clusterd -fdd
2019/09/30 14:46:22 wazuh-clusterd: DEBUG: [Cluster] [Main] [Cluster] Removing '/opt/ossec/queue/cluster/'.
2019/09/30 14:46:22 wazuh-clusterd: DEBUG: [Cluster] [Main] [Cluster] Removed '/opt/ossec/queue/cluster/'.
2019/09/30 14:46:22 wazuh-clusterd: INFO: [Local Server] [Main] Serving on /opt/ossec/queue/cluster/c-internal.sock
2019/09/30 14:46:22 wazuh-clusterd: DEBUG: [Local Server] [Keep alive] Calculating.
2019/09/30 14:46:22 wazuh-clusterd: DEBUG: [Local Server] [Keep alive] Calculated.
2019/09/30 14:46:22 wazuh-clusterd: ERROR: [Cluster] [Main] Unhandled exception:
Traceback (most recent call last):
  File "/opt/ossec/framework/scripts/wazuh-clusterd.py", line 179, in <module>
    asyncio.run(main_function(args, cluster_configuration, cluster_items, main_logger))
  File "/opt/ossec/framework/python/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/opt/ossec/framework/python/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/opt/ossec/framework/scripts/wazuh-clusterd.py", line 94, in worker_main
    await asyncio.gather(my_client.start(), my_local_server.start())
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.2-py3.7.egg/wazuh/cluster/client.py", line 86, in start
    ssl=ssl_context)
  File "/opt/ossec/framework/python/lib/python3.7/asyncio/base_events.py", line 986, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/opt/ossec/framework/python/lib/python3.7/asyncio/base_events.py", line 1002, in _create_connection_transport
    protocol = protocol_factory()
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.2-py3.7.egg/wazuh/cluster/client.py", line 84, in <lambda>
    manager=self, **self.extra_args),
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.2-py3.7.egg/wazuh/cluster/worker.py", line 108, in __init__
    super().__init__(**kwargs, tag="Worker")
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.2-py3.7.egg/wazuh/cluster/client.py", line 122, in __init__
    super().__init__(fernet_key=fernet_key, logger=logger, tag="{} {}".format(tag, name), cluster_items=cluster_items)
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.2-py3.7.egg/wazuh/cluster/common.py", line 156, in __init__
    self.my_fernet = cryptography.fernet.Fernet(base64.b64encode(fernet_key.encode())) if fernet_key else None
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/cryptography/fernet.py", line 32, in __init__
    backend = default_backend()
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 18, in <module>
    from cryptography import utils, x509
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/cryptography/x509/extensions.py", line 13, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/asn1crypto/keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/asn1crypto/_int.py", line 43, in <module>
    from ._ffi import (
  File "/opt/ossec/framework/python/lib/python3.7/site-packages/asn1crypto/_ffi.py", line 15, in <module>
    from ctypes import create_string_buffer
  File "/opt/ossec/framework/python/lib/python3.7/ctypes/__init__.py", line 543, in <module>
    _reset_cache()
  File "/opt/ossec/framework/python/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
```
