### ISSUE TITLE
The manager won't compile Python on macOS

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3338]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0 | Manager | Manager/Local | Sources | macOS Mojave |

The compilation procedure fails when building Python:
```shell
$ make TARGET=server
```

```
DYLD_LIBRARY_PATH=/Users/vikman/Wazuh/Projects/wazuh/src/external/cpython CC='gcc' LDSHARED='gcc -bundle -undefined dynamic_lookup -L/Users/vikman/Wazuh/Projects/wazuh/src -lwazuhext -Xlinker -rpath -Xlinker @executable_path/../../../lib   ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES='' _TCLTK_LIBS='' 	./python.exe -E ./setup.py  build
-Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration
flags = -L/Users/vikman/Wazuh/Projects/wazuh/src -lwazuhext -Xlinker -rpath -Xlinker @executable_path/../../../lib py_flags=
-L/Users/vikman/Wazuh/Projects/wazuh/src -lwazuhext -Xlinker -rpath -Xlinker @executable_path/../../../lib
running build
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 2393, in <module>
    main()
  File "./setup.py", line 2388, in main
    "Tools/scripts/2to3", "Tools/scripts/pyvenv"]
  File "/Users/vikman/Wazuh/Projects/wazuh/src/external/cpython/Lib/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/vikman/Wazuh/Projects/wazuh/src/external/cpython/Lib/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/vikman/Wazuh/Projects/wazuh/src/external/cpython/Lib/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/vikman/Wazuh/Projects/wazuh/src/external/cpython/Lib/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/vikman/Wazuh/Projects/wazuh/src/external/cpython/Lib/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/vikman/Wazuh/Projects/wazuh/src/external/cpython/Lib/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/vikman/Wazuh/Projects/wazuh/src/external/cpython/Lib/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "./setup.py", line 258, in build_extensions
    missing = self.detect_modules()
  File "./setup.py", line 1183, in detect_modules
    if host_platform == 'darwin' and is_macosx_sdk_path(d):
  File "./setup.py", line 135, in is_macosx_sdk_path
    return ( (path.startswith('/usr/') and not path.startswith('/usr/local'))
AttributeError: 'NoneType' object has no attribute 'startswith'
make[1]: *** [sharedmods] Error 1
make: *** [build_python] Error 2
```

**Comment by vikman90** [comment]
This problem is due to the macOS [System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection): this feature is preventing the build processes from sharing environment variables.

The `export` command will no longer work here: https://github.com/wazuh/wazuh/blob/v3.9.0/src/Makefile#L1460-L1464
