### ISSUE TITLE
Problem to upgrade agents when the manager is installed in different path than /var/ossec

### ISSUE THREAD

**Issue by jlruizmlg** [wazuh/wazuh#334]
After installing the manager in /opt, if I try to list the agents pending to be upgraded I have an error:

```
[root@centos7 ossec]#/opt/ossec/bin/agent_upgrade -ld
Error 1600: There is no database for selected agent.
Traceback (most recent call last):
  File "./bin/agent_upgrade", line 147, in <module>
    main()
  File "./bin/agent_upgrade", line 49, in main
    list_outdated()
  File "./bin/agent_upgrade", line 37, in list_outdated
    agents = Agent.get_outdated_agents()
  File "./bin/../framework/wazuh/agent.py", line 1691, in get_outdated_agents
    raise WazuhException(1600)
wazuh.exception.WazuhException: Error 1600 - There is no database for selected agent.
```

To fix this problem, I need to edit the file ```/opt/ossec/framework/wazuh/common.py``` and modify 

```
def set_paths_based_on_ossec(o_path='/var/ossec'):
    """
    Set paths based on ossec location.
    :param o_path: OSSEC Path, by default it is '/var/ossec'.
    :return:
    """
```

to this other with the correct path:

```
def set_paths_based_on_ossec(o_path='/opt/ossec'):
    """
    Set paths based on ossec location.
    :param o_path: OSSEC Path, by default it is '/opt/ossec'.
    :return:
    """
```

**Comment by Lifka** [comment]
Hi,

I think the problem is not the Framework.

```
[root@manager wazuh]# /opt/ossec/bin/agent_control -l
2017/12/29 12:07:03 agent_control: CRITICAL: (1226): Error reading XML file '/etc/ossec.conf':  (line 0).
```
