### ISSUE TITLE
Remove body parameters for DELETE requests

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh#3388]
Hi team,

We need to remove body parameters for `DELETE` and `PUT` API requests in order to follow `OpenAPI` standard.

We have body parameters in these requests:

#### `DELETE`

- [x] `/agents`

Example:

- `curl -u foo:bar -k -X DELETE -H "Content-Type:application/json" -d '{"ids":["003","005"]}' "https://127.0.0.1:55000/agents?pretty&older_than=10s&purge"`

- [x] `/agents/group/:group_id`

Example:

- `curl -u foo:bar -X DELETE -H "Content-Type:application/json" -d '{"ids":["001","002"]}' "https://localhost:55000/agents/group/dmz?pretty" -k`

- [x] `/agents/groups`

Example:

- `curl -u foo:bar -k -X DELETE -H "Content-Type:application/json" -d '{"ids":["webserver","database"]}' "https://127.0.0.1:55000/agents/groups?pretty"`

Best regards,

Demetrio.

**Comment by druizz90** [comment]
## Issue update

Below there are examples of `DELETE` requests with parameters in query:

- `/agents`

```bash
# curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents?pretty&ids=003,004,005&older_than=10s&purge"
{
   "error": 0,
   "data": {
      "msg": "All selected agents were removed",
      "affected_agents": [
         "003",
         "004",
         "005"
      ],
      "older_than": "10s",
      "total_affected_agents": 3
   }
}
```

API log (`debug` mode):

```bash
WazuhAPI 2019-05-24 08:46:01 foo: ::ffff:127.0.0.1 DELETE /agents
WazuhAPI 2019-05-24 08:46:01 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"DELETE/agents/","arguments":{"purge":false,"list_agent_ids":["003","004","005"],"older_than":"10s","wait_for_complete":false},"ossec_path":"/var/ossec"}
WazuhAPI 2019-05-24 08:46:01 foo: CMD - Exit code: 0
WazuhAPI 2019-05-24 08:46:01 foo: CMD - STDOUT:
---
{"data": {"msg": "All selected agents were removed", "affected_agents": ["003", "004", "005"], "older_than": "10s", "total_affected_agents": 3}, "error": 0}

---
```

- `/agents/groups`

```bash
# curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents/groups?ids=dmz,webserver,pci&pretty"        
{
   "error": 0,
   "data": {
      "msg": "All selected groups were removed",
      "ids": [
         "dmz",
         "webserver",
         "pci"
      ],
      "affected_agents": []
   }
}
```

API log (`debug` mode):

```bash
WazuhAPI 2019-05-24 08:49:27 foo: ::ffff:127.0.0.1 DELETE /agents/groups
WazuhAPI 2019-05-24 08:49:27 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"DELETE/agents/groups","arguments":{"group_id":["dmz","webserver","pci"],"wait_for_complete":false},"ossec_path":"/var/ossec"}
WazuhAPI 2019-05-24 08:49:27 foo: CMD - Exit code: 0
WazuhAPI 2019-05-24 08:49:27 foo: CMD - STDOUT:
---
{"data": {"msg": "All selected groups were removed", "ids": ["dmz", "webserver", "pci"], "affected_agents": []}, "error": 0}
```

- `/agents/group/:group_id`

```bash
# curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents/group/dmz?ids=002,003,004&pretty"
{
   "error": 0,
   "data": {
      "msg": "All selected agents were removed from group dmz",
      "affected_agents": [
         "002",
         "003",
         "004"
      ]
   }
}
```

API log (`debug` mode):

```bash
WazuhAPI 2019-05-24 08:54:27 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"DELETE/agents/group/:group_id","arguments":{"group_id":"dmz","agent_id_list":["002","003","004"],"wait_for_complete":false},"ossec_path":"/var/ossec"}
WazuhAPI 2019-05-24 08:54:28 foo: CMD - Exit code: 0
WazuhAPI 2019-05-24 08:54:28 foo: CMD - STDOUT:
---
{"data": {"msg": "All selected agents were removed from group dmz", "affected_agents": ["002", "003", "004"]}, "error": 0}
```

**Comment by adri9valle** [comment]
Hi team,

I have tested this API requests in the devTools and the results were the next:


`DELETE /agents/group/test_group?ids=444,666&pretty`

```
{
  "error": 0,
  "data": {
    "msg": "Some agents were not removed from group test_group",
    "failed_ids": [
      {
        "error": {
          "message": "Agent does not exist: 666",
          "code": 1701
        },
        "id": "666"
      }
    ],
    "affected_agents": [
      "444"
    ]
  }
}
```

`DELETE /agents?pretty&ids=444,555,666&older_than=10s&purge`

```
{
  "error": 0,
  "data": {
    "msg": "Some agents were not removed",
    "total_affected_agents": 1,
    "affected_agents": [
      "444"
    ],
    "failed_ids": [
      {
        "error": {
          "message": "Agent does not exist: 555",
          "code": 1701
        },
        "id": "555"
      },
      {
        "error": {
          "message": "Agent does not exist: 666",
          "code": 1701
        },
        "id": "666"
      }
    ],
    "total_failed_ids": 2,
    "older_than": "10s"
  }
}
```

`DELETE /agents/groups?ids=dmz,webserver,pci&pretty`

```
{
  "error": 0,
  "data": {
    "ids": [],
    "msg": "Some groups were not removed",
    "failed_ids": [
      {
        "error": {
          "message": "The group does not exist: dmz",
          "code": 1710
        },
        "id": "dmz"
      },
      {
        "error": {
          "message": "The group does not exist: webserver",
          "code": 1710
        },
        "id": "webserver"
      },
      {
        "error": {
          "message": "The group does not exist: pci",
          "code": 1710
        },
        "id": "pci"
      }
    ],
    "affected_agents": []
  }
}
```

All the requests work fine.

Regards,

**Comment by druizz90** [comment]
## Issue update

#### Mocha tests for agents

```javascript
# mocha test/test_agents.js --timeout=10000


  Agents
    GET/agents
      ✓ Request (362ms)
      ✓ Pagination (489ms)
      ✓ Retrieve all elements with limit=0 (516ms)
      ✓ Sort (603ms)
      ✓ Wrong Sort (722ms)
      ✓ Search (741ms)
      ✓ Selector (851ms)
      ✓ Not allowed selector (951ms)
      ✓ Version (643ms)
      ✓ Os.platform (633ms)
      ✓ Os.version (673ms)
      ✓ ManagerHost (781ms)
      ✓ Filters: status (647ms)
      ✓ Filters: status 2 (573ms)
      ✓ Filters: Invalid filter
      ✓ Filters: Invalid filter - Extra field
      ✓ Filters: older_than (736ms)
      ✓ Filters: group (892ms)
      ✓ Select: single field (930ms)
      ✓ Select: multiple fields (629ms)
      ✓ Select: wrong field (546ms)
      ✓ Select: invalid character
      ✓ Filters: query (670ms)
    GET/agents/summary
      ✓ Request (497ms)
    GET/agents/summary/os
      ✓ Request (578ms)
    GET/agents/outdated
      ✓ Request (572ms)
    GET/agents/:agent_id
      ✓ Request (manager) (496ms)
      ✓ Request (agent) (470ms)
      ✓ Selector (660ms)
      ✓ Not allowed selector (581ms)
      ✓ Params: Bad agent id
      ✓ Errors: No agent (661ms)
      ✓ Select (358ms)
      ✓ Select: wrong field (340ms)
    GET/agents/name/:agent_name
      ✓ Request (421ms)
      ✓ Wrong name (385ms)
      ✓ Selector (464ms)
      ✓ Not allowed selector (384ms)
    GET/agents/:agent_id/key
      ✓ Request (353ms)
      ✓ Params: Bad agent id
      ✓ Errors: No key (406ms)
    PUT/agents/groups/:group_id
      ✓ Request (381ms)
      ✓ Params: Bad group name
      ✓ Params: Group already exists (354ms)
    PUT/agents/:agent_id/group/:group_id
      ✓ Request (385ms)
      ✓ Params: Bad agent name
      ✓ Params: Agent does not exist (330ms)
      ✓ Params: Replace parameter (499ms)
    POST/agents/groups/:group_id/files/:file_name
      ✓ Request (493ms)
      ✓ ErrorOnBadGroup (386ms)
      ✓ ErrorOnEmptyConf
      ✓ OnlyAgentConfAllowed (340ms)
      ✓ InvalidConfDetected
      ✓ WrongConfDetected (440ms)
      1) TooBigXML
    GET/agents/no_group
      ✓ Request (520ms)
      ✓ Pagination (803ms)
      ✓ Retrieve all elements with limit=0 (546ms)
      ✓ Sort (612ms)
      ✓ Search (673ms)
      ✓ Select (496ms)
      ✓ Wrong select (574ms)
      ✓ Filter: status (574ms)
    GET/agents/groups
      ✓ Request (576ms)
      ✓ Retrieve all elements with limit=0 (450ms)
      ✓ Hash algorithm (347ms)
      ✓ Wrong Hash algorithm (326ms)
    GET/agents/groups/:group_id
      ✓ Request (405ms)
      ✓ Params: Bad group name
      ✓ Retrieve all elements with limit=0 (362ms)
      ✓ Select (330ms)
      ✓ Filter: status (321ms)
    GET/agents/groups/:group_id/configuration
      ✓ Request (367ms)
      ✓ Params: Bad group name
      ✓ Retrieve all elements with limit=0 (424ms)
    GET/agents/groups/:group_id/files
      ✓ Request (335ms)
      ✓ Params: Bad group name
      ✓ Retrieve all elements with limit=0 (360ms)
      ✓ Hash algorithm (512ms)
      ✓ Wrong Hash algorithm (374ms)
    GET/agents/groups/:group_id/files/:filename
      ✓ Request (497ms)
      ✓ UsingFormatAgentConfXML (376ms)
      ✓ UsingFormatAgentConfJSON (373ms)
      ✓ UsingFormatRootcheckXML (615ms)
      ✓ UsingFormatRootcheckJSON (449ms)
      ✓ Params: Bad group name
    POST/agents/groups/:group_id/configuration
      ✓ Request (543ms)
      ✓ ErrorOnBadGroup (471ms)
      ✓ ErrorOnEmptyConf
      ✓ InvalidConfDetected
      ✓ WrongConfDetected (549ms)
      2) TooBigXML
    DELETE/agents/:agent_id/group
      ✓ Request (611ms)
      ✓ Errors: ID is not present (497ms)
      ✓ Params: Bad agent id
    DELETE/agents/:agent_id/group/:group_id
      ✓ Request (859ms)
      ✓ Errors: ID is not present (501ms)
      ✓ Errors: Group is not present (615ms)
      ✓ Params: Bad agent id
      ✓ Params: Bad group id (575ms)
    DELETE/agents/groups/:group_id
      ✓ Request (460ms)
      ✓ Params: Bad group id
    PUT/agents/restart
      ✓ Request (697ms)
    PUT/agents/:agent_id/restart
      ✓ Request (753ms)
      ✓ Params: Bad agent id
      ✓ Request (459ms)
    POST/agents/restart
      ✓ Request (286ms)
      ✓ Params: A good id and a bad one (273ms)
      ✓ Params: Bad agent id
      ✓ Request (229ms)
    DELETE/agents
      ✓ Request
      ✓ Filter: older_than, status and ids (3872ms)
      ✓ Errors: Get deleted agent (379ms)
      ✓ Filter: older_than (298ms)
    GET/agents/stats/distinct
      ✓ Request (291ms)
      ✓ Pagination (299ms)
      ✓ Retrieve all elements with limit=0 (339ms)
      ✓ Sort (297ms)
      ✓ Search (248ms)
      ✓ Select (314ms)
      ✓ Wrong select (297ms)
    GET/agents/:agent/config/:component/:configuration
      ✓ Request-Agent-Client (345ms)
      ✓ Request-Agent-Buffer (349ms)
      ✓ Request-Agent-Labels (325ms)
      ✓ Request-Agent-Internal (318ms)
      ✓ Request-Agentless-Agentless (293ms)
      ✓ Request-Analysis-Global (296ms)
      ✓ Request-Analysis-Active-response (283ms)
      ✓ Request-Analysis-Alerts (312ms)
      ✓ Request-Analysis-Command (296ms)
      ✓ Request-Analysis-Internal (296ms)
      ✓ Request-Auth-Auth (326ms)
      ✓ Request-Com-Active-response (362ms)
      ✓ Request-Com-Internal (325ms)
      ✓ Request-Csyslog-Csyslog (314ms)
      ✓ Request-Integrator-Integration (357ms)
      ✓ Request-Logcollector-Localfile (290ms)
      ✓ Request-Logcollector-Socket (359ms)
      ✓ Request-Logcollector-Internal (333ms)
      ✓ Request-Mail-Global (346ms)
      ✓ Request-Mail-Alerts (272ms)
      ✓ Request-Mail-Internal (350ms)
      ✓ Request-Monitor-Internal (358ms)
      ✓ Request-Request-Remote (353ms)
      ✓ Request-Request-Internal (363ms)
      ✓ Request-Syscheck-Syscheck (347ms)
      ✓ Request-Syscheck-Rootcheck (329ms)
      ✓ Request-Syscheck-Internal (294ms)
      ✓ Request-Wmodules-Wmodules (283ms)


  147 passing (1m)
  2 failing

  1) Agents
       POST/agents/groups/:group_id/files/:file_name
         TooBigXML:
     Uncaught AssertionError: expected '701' to be 701
      at Assertion.fail (node_modules/should/cjs/should.js:258:17)
      at Assertion.value (node_modules/should/cjs/should.js:335:19)
      at Test.<anonymous> (test/test_agents.js:1108:39)
      at Test.assert (node_modules/supertest/lib/test.js:179:6)
      at assert (node_modules/supertest/lib/test.js:131:12)
      at /root/wazuh-old/wazuh-api/node_modules/supertest/lib/test.js:128:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:631:3)
      at /root/wazuh-old/wazuh-api/node_modules/superagent/lib/node/index.js:795:18
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:16:7)
      at endReadableNT (_stream_readable.js:1139:12)
      at processTicksAndRejections (internal/process/task_queues.js:81:17)

  2) Agents
       POST/agents/groups/:group_id/configuration
         TooBigXML:
     Uncaught AssertionError: expected '701' to be 701
      at Assertion.fail (node_modules/should/cjs/should.js:258:17)
      at Assertion.value (node_modules/should/cjs/should.js:335:19)
      at Test.<anonymous> (test/test_agents.js:1843:39)
      at Test.assert (node_modules/supertest/lib/test.js:179:6)
      at assert (node_modules/supertest/lib/test.js:131:12)
      at /root/wazuh-old/wazuh-api/node_modules/supertest/lib/test.js:128:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:631:3)
      at /root/wazuh-old/wazuh-api/node_modules/superagent/lib/node/index.js:795:18
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:16:7)
      at endReadableNT (_stream_readable.js:1139:12)
      at processTicksAndRejections (internal/process/task_queues.js:81:17)

   
```
