### ISSUE TITLE
Cluster_control daemon does not work when installing Wazuh in a custom path

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#3498]
Hello Team,

I have realized that when installing the API in a custom path from sources, the `cluster_control` daemon does not work. It throws the following error:

```
Traceback (most recent call last):
  File "/opt/miguel/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.1-py3.7.egg/wazuh/configuration.py", line 450, in get_ossec_conf
    xml_data = load_wazuh_xml(conf_file)
  File "/opt/miguel/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.1-py3.7.egg/wazuh/utils.py", line 494, in load_wazuh_xml
    with open(xml_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miguel/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.1-py3.7.egg/wazuh/cluster/cluster.py", line 105, in read_config
    config_cluster = get_ossec_conf(section='cluster', conf_file=config_file)
  File "/opt/miguel/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.1-py3.7.egg/wazuh/configuration.py", line 455, in get_ossec_conf
    raise WazuhException(1101, str(e))
wazuh.exception.WazuhException: Error 1101 - Requested component does not exist: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miguel/ossec/framework/scripts/cluster_control.py", line 146, in <module>
    cluster_status = cluster.get_status_json()
  File "/opt/miguel/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.1-py3.7.egg/wazuh/cluster/cluster.py", line 174, in get_status_json
    return {"enabled": "no" if check_cluster_status() else "yes",
  File "/opt/miguel/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.1-py3.7.egg/wazuh/cluster/cluster.py", line 170, in check_cluster_status
    return read_config()['disabled']
  File "/opt/miguel/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.1-py3.7.egg/wazuh/cluster/cluster.py", line 112, in read_config
    raise WazuhException(3006, e.message)
wazuh.exception.WazuhException: Error 3006 - Error reading cluster configuration: Requested component does not exist: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'
```

I have the following version and I have installed Wazuh in the following path:

```
 cat /opt/miguel/ossec/api/package.json | grep version
  "version": "3.9.1",

cat /opt/miguel/ossec/etc/ossec-init.conf 
DIRECTORY="/opt/miguel/ossec"
NAME="Wazuh"
VERSION="v3.9.1"
REVISION="3921"
DATE="Thu May 30 06:40:25 PDT 2019"
TYPE="server"

```

Regards,

Miguel Casares

**Comment by crd1985** [comment]
This has been solved in https://github.com/wazuh/wazuh/pull/3548
