### ISSUE TITLE
Process AWS Profile arguments for vpcflowlogs bucket type

### ISSUE THREAD

**Issue by awill1988** [wazuh/wazuh#3730]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3 | wazuh | both | Packages/Sources | all |

Please see proposed feature enhancement to aws wodle here #3729 

We have integrated it using Kubernetes ConfigMap and has allowed us to have only need one set of credentials with role assumption for cross-account access.

For example, vpcflowlogs bucket types will work now when `~./aws/config` and `~./aws/credentials`are present and config looks like:
```
[default]
region = us-east-1

[profile dev]
source_profile = default
role_arn = arn:aws:iam::<account_id>:role/Admin
```

Thanks for your time,
Adam

**Comment by druizz90** [comment]
Hi @awill1988,

Thank you very much for your contribution. We will include your PR as soon as possible.

I tested #3729 and it worked fine.

Before @awill1988 fix, it was not possible to use different profiles for `VPC` service:
```bash
# /var/ossec/wodles/aws/aws-s3 --bucket wazuh-aws-wodle --aws_profile default --trail_prefix vpc --type vpcflow --aws_profile profile2 --skip_on_error --debug 1
DEBUG: +++ Debug mode on - Level: 1
DEBUG: +++ Working on 1XXXXXXX - us-east-1
Unknown error: An error occurred (AuthFailure) when calling the DescribeFlowLogs operation: AWS was not able to validate the provided access credentials
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 2258, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 2226, in main
    bucket.iter_bucket(options.aws_account_id, options.regions)
  File "/var/ossec/wodles/aws/aws-s3.py", line 705, in iter_bucket
    self.iter_regions_and_accounts(account_id, regions)
  File "/var/ossec/wodles/aws/aws-s3.py", line 1387, in iter_regions_and_accounts
    self.secret_key, aws_region)
  File "/var/ossec/wodles/aws/aws-s3.py", line 1333, in get_flow_logs_ids
    flow_logs_ids = list(map(operator.itemgetter('FlowLogId'), ec2_client.describe_flow_logs()['FlowLogs']))
  File "/var/ossec/framework/python/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeFlowLogs operation: AWS was not able to validate the provided access credentials
```

After @awill1988 fix , the wodle works fine:
```bash
# /var/ossec/wodles/aws/aws-s3 --bucket wazuh-aws-wodle --aws_profile default --trail_prefix vpc --type vpcflow --aws_profile profile2 --skip_on_error --debug 1
DEBUG: +++ Debug mode on - Level: 1
DEBUG: +++ Working on 16XXXXX - us-east-1
DEBUG: ++ Skipping previously processed file:
...
```

Best regards,

Demetrio.
