### ISSUE TITLE
Issue with Remote Upgrading

### ISSUE THREAD

**Issue by Theoooooo** [wazuh/wazuh#4192]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2 | Remote Upgrade | Manager | Sources | CentOS 7 |

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3 | Remote Upgrade | Agent | Sources | Windows Server 2016 R2 |

I got issue while trying to remote upgrade my windows Wazuh agent.

The .wpk got send correctly from the manager to the agent but the system can't execute the .bat sended by the manager. 

Manager logs:
```
bin/agent_upgrade -a 020 -f /home/infra/wazuh_agent_v3.10.2_windows.wpk
Error 1716: Error upgrading agent: Cannot execute installer
``` 

Agent logs :
```
2019/11/05 17:01:50 ossec-agent: ERROR: at wm_exec(): CreateProcess(2): The system cannot find the file specified.
2019/11/05 17:01:50 ossec-agent: ERROR: At WCOM upgrade: Error executing command [upgrade\upgrade.sh]
```

Executing the .bat manually with a account with proper right on the system does upgrade wazuh-agent to the corresponded version

**Comment by sergiovp** [comment]
Hello @Theoooooo,

This issue is due to the agent is trying to run upgrade.sh script instead of upgrade.bat as you can see in your log report.

You should manually specify the upgrade.bat script as follows: 
`bin/agent_upgrade -a 020 -f /home/infra/wazuh_agent_v3.10.2_windows.wpk -x upgrade.bat`

We would like to improve it as soon as our workflow allows us, so that by default, it executes upgrade.bat script instead of upgrade.sh.

I hope I helped you, in other case, please, let me know.

Best regards.

**Comment by Theoooooo** [comment]
ahhhh you're right i didn't paid attention to the extention of the file ...
good news it can still be done with a simple option.

But the installation is hanging out indefinitely ...

I just Ctrl+C after 15 minutes just to unlock my ssh session but then i'm not able to send new requests :

```
./agent_upgrade -a 020 -f /home/infra/wazuh_agent_v3.10.2_windows.wpk -x upgrade.bat
Sending WPK: [=========================] 100%
Installation started... Please wait.

^C
[1] [/var/ossec/bin]# ./agent_upgrade -a 020 -f /home/infra/wazuh_agent_v3.10.2_windows.wpk -x upgrade.bat
Error 1715: Error sending WPK file: Cannot send request
```

**Comment by sergiovp** [comment]
Hello @Theoooooo,

It seems something was wrong, perhaps, your agent was down and that's the reason why you are not able to send requests to it.

Normally, it should not take more than approximately one minute to update remotely the agent.

I have reproduced your use case with your environment (Manager in CentOS7 v3.10.2 and upgrade a Windows Server 2016 agent from v3.9.3 to v3.10.2) and everything worked as expected:

~~~
root@ManagerCentOS7:/vagrant/wazuh/src$ agent_upgrade -l
ID    Name                                Version                  
001   WIN-O9VR5NN7C3F                     Wazuh v3.9.3             
~~~

~~~
root@ManagerCentOS7:/vagrant$ agent_upgrade -a 001 -f /vagrant/wazuh_agent_v3.10.2_windows.wpk -x upgrade.bat
Sending WPK: [=========================] 100%   
Installation started... Please wait.
Agent upgraded successfully
~~~

~~~
root@ManagerCentOS7:/vagrant$ agent_upgrade -l
ID    Name                                Version                  
001   WIN-O9VR5NN7C3F                     Wazuh v3.10.2
~~~

![image](https://user-images.githubusercontent.com/36703917/68576313-257bb780-046e-11ea-942e-b32d393d5edc.png)


So, could you check with your agent status and paste both manager and agent logs here, please?

Best regards.

**Comment by Theoooooo** [comment]
Thanks for the answer. Let's dig into this :

I've tested this on a linux agent and it worked properly.
So i checked the logs of my windows agent and as i expected, there is no error showing in the log file as i do the remote upgrade process :
```
2019/11/08 14:30:29 ossec-agent: INFO: Received exit signal.
2019/11/08 14:30:29 ossec-agent: INFO: Exiting...
2019/11/08 14:30:29 ossec-agent: INFO: (1314): Shutdown received. Deleting responses.
2019/11/08 14:30:37 ossec-agent: INFO: Using notify time: 10 and max time to reconnect: 60
2019/11/08 14:30:37 ossec-agent: INFO: Started (pid: 3608).
2019/11/08 14:30:37 ossec-agent: INFO: (1410): Reading authentication keys file.
2019/11/08 14:30:37 ossec-agent: INFO: Trying to connect to server (172.31.27.1:1514/tcp).
2019/11/08 14:30:37 ossec-agent: INFO: Starting file integrity monitoring thread.
2019/11/08 14:30:37 ossec-agent: INFO: (4102): Connected to the server (172.31.27.1:1514/tcp).
2019/11/08 14:30:37 rootcheck: INFO: Started (pid: 3608)
2019/11/08 14:30:37 ossec-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2012 R2 Datacenter [Ver: 6.3.9600] - Wazuh v3.10.2).
```

The agent is undeed started and running because i'm receiving logs from him :
![image](https://user-images.githubusercontent.com/33425208/68655073-a5b62180-052f-11ea-966a-727749a23de4.png)

![image](https://user-images.githubusercontent.com/33425208/68655248-f9c10600-052f-11ea-8034-e52aa0d0285e.png)

Here is the full debug output of the command executed in the manager :
```
./agent_upgrade -a 008 -f /home/infra/wazuh_agent_v3.10.2_windows.wpk -d
Custom WPK file: wazuh_agent_v3.10.2_windows.wpk (2553.669921875 KB)
MSG SENT: 008 com lock_restart -1
RESPONSE: err Cannot send request
Error 1715: Error sending WPK file: Cannot send request
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 167, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 92, in main
    rl_timeout=-1 if args.timeout == None else args.timeout)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.2-py3.7.egg/wazuh/agent.py", line 2403, in upgrade_custom
    sending_result = self._send_custom_wpk_file(file_path, debug, show_progress, chunk_size, rl_timeout)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.2-py3.7.egg/wazuh/agent.py", line 2301, in _send_custom_wpk_file
    raise WazuhException(1715, data.replace("err ",""))
wazuh.exception.WazuhException: Error 1715 - Error sending WPK file: Cannot send request
```

**Comment by sergiovp** [comment]
Hello @Theoooooo,

Excuse me, but I do not entirely understand what you do mean.

In short, you tried to upgrade remotely a Windows agent, the process froze, but the agent got upgraded correctly and now you are not able to upgrade remotely any agent due your last error report. Am I right?

What strikes me most in your error resport is that you are not able to send request to your agent:
~~~
RESPONSE: err Cannot send request
Error 1715: Error sending WPK file: Cannot send request
~~~

Could you check `upgrade.txt` file in your upgraded agent?
This file is located in `C:\Program Files (x86)\ossec-agent\upgrade`.
In my case, as the upgrade was done successfully, this is its content:
~~~
2019-11-13 10:21:47Z - Current version: v3.9.3
2019-11-13 10:21:47Z - Generating backup.
2019-11-13 10:21:51Z - Trying to stop Wazuh service again. Remaining attempts: 5.
2019-11-13 10:21:54Z - Starting upgrade processs.
2019-11-13 10:21:54Z - Waiting for the installation end.
2019-11-13 10:21:56Z - Restarting Wazuh service.
2019-11-13 10:21:57Z - Installation finished.
2019-11-13 10:21:57Z - Process ID: 3316
2019-11-13 10:22:03Z - Reading status file: status='connected'
2019-11-13 10:22:03Z - Upgrade finished successfully.
2019-11-13 10:22:03Z - New version: v3.10.2
~~~

Please, don't forget to use `-x upgrade.bat` option.

Best regards.

**Comment by Theoooooo** [comment]
@sergiovp You get it right, after upgrade my agent and interrupting the process because it was froze on my manager, i'm not able anymore to remote upgrade any agent with the error i posted above.

There is the log inside the upgrade.txt from my Windows agent when i did the remove upgrade process :
```
2019-11-08 14:30:23Z - Current version: v3.9.3
2019-11-08 14:30:23Z - Generating backup.
2019-11-08 14:30:29Z - Trying to stop Wazuh service again. Remaining attempts: 5.
2019-11-08 14:30:31Z - Starting upgrade processs.
2019-11-08 14:30:31Z - Waiting for the installation end.
2019-11-08 14:30:34Z - Waiting for the installation end.
2019-11-08 14:30:36Z - Restarting Wazuh service.
2019-11-08 14:30:37Z - Installation finished.
2019-11-08 14:30:37Z - Process ID: 3608
2019-11-08 14:30:37Z - Reading status file: status='connected'
2019-11-08 14:30:38Z - Upgrade finished successfully.
2019-11-08 14:30:38Z - New version: v3.10.2
```
After the remote upgrade, the agent restarted and connected properly to the wazuh cluster but the process launched from the manager frooze and i wasn't able to exit it without using Ctrl+C

I also retried with the "-x upgrade.bat" option but i still got the same error on the manager.

I restarded both my master and my worker inside my wazuh cluster but i still got the same result if i tried to remote uprgade. The only step i haven't done is restart the VM but i'm not really 
confident about restart a production VM with multiples services on it ...

**Comment by sergiovp** [comment]
Hello @Theoooooo,

I'm not sure about the error source yet.
Perhaps it's due to the asynchronous processes that we use in our cluster. 
Could you try, please, to update the agent using our API?

Here are the related [documentation](https://documentation.wazuh.com/3.10/user-manual/agents/remote-upgrading/upgrading-agent.html#using-the-restful-api).

(You don't need to have the `wpk` file).

I hope it works, in other case, please, let me know.

Best regards.

**Comment by Theoooooo** [comment]
The commands inside the documentation is not working to upgrade the agent. The link must be wrong :
```
curl -u username:password -X GET "http://172.31.27.4:55000/agents/007?pretty"
{
   "error": 0,
   "data": {
      "dateAdd": "2019-10-17 08:36:28",
      "status": "Active",
      "registerIP": "any",
      "group": [
         "default"
      ],
      "os": {
         "build": "14393",
         "major": "10",
         "minor": "0",
         "name": "Microsoft Windows Server 2016 Standard",
         "platform": "windows",
         "uname": "Microsoft Windows Server 2016 Standard",
         "version": "10.0.14393"
      },
      "node_name": "stickylogs-logs01b",
      "manager": "stickylogs-logs01b",
      "lastKeepAlive": "2019-11-14 15:24:58",
      "configSum": "ab73af41699f13fdd81903b5f23d8d00",
      "version": "Wazuh v3.9.3",
      "name": "cyres-pdc03",
      "mergedSum": "276b7a745ee8e6f187f8d26879afe48d",
      "ip": "192.168.2.143",
      "id": "007"
   }
}

curl -u username:password -X GET "http://172.31.27.4:55000/agents/007/upgrade?pretty"
{
   "error": 603,
   "message": "The requested URL was not found on this server"
```

**Comment by sergiovp** [comment]
Hello @Theoooooo

Excuse the lateness.

Your command didn't work due to you use `GET` instead of `PUT`.
So, your command must be
~~~
curl -u username:password -X PUT "http://172.31.27.4:55000/agents/007/upgrade?pretty"`
~~~

As you can see, I get the same error than you using `GET`:
~~~
root@ManagerUbuntu18:/home/vagrant$ curl -u foo:bar -X GET "http://localhost:55000/agents/002/upgrade?pretty"
{
   "error": 603,
   "message": "The requested URL was not found on this server"
}
~~~

But when I use `PUT` I get the following result:
~~~
root@ManagerUbuntu18:/home/vagrant$ curl -u foo:bar -X GET "http://localhost:55000/agents/002/upgrade_result?pretty"
{
   "error": 0,
   "data": "Agent upgraded successfully"
}
~~~

I hope it works.

Best regards.

**Comment by Zenidd** [comment]
Hello again @Theoooooo,

I'm closing this issue due to inactivity. Do not hesitate to reopen it if you keep experiencing issues with the remote agent upgrading. 

On the other hand, for further questions please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

Greetings, JP Sáez

**Comment by Theoooooo** [comment]
Sorry about the inactivity, i got others projets on the way and i didn't have time to properly test the solution you gave me.
If i update the post i will tag you to keep you update

**Comment by Theoooooo** [comment]
@sergiovp Alright i got to get some times on this issue,

No the issue i'm getting is the API throw me timeout after launching the upgrade process :
```
curl -u username:password -X PUT "http://172.31.27.4:55000/agents/019/upgrade?pretty"
{
   "error": 3021,
   "message": "Timeout executing API request"
}
```
Note that the linux agents i've upgraded where inside the same subnet as the manager so there is no conflit of a firewall misconfigured.
But the agent gets undeed upgraded in the process and restarted properly after this.

I also tried to upgrade agents in other subnets (which are able to communicate properly with my manager though the load balancer) and it's working properly with the WAzuhAPI but not with the "agent_upgrade" command :

agent_upgrade output :
```
bin/agent_upgrade -a 032
Error 1715: Error sending WPK file: Cannot send request
```

wazuh_api output :
```
curl -u username:password -X PUT "http://172.31.27.4:55000/agents/032/upgrade?pretty"
{
   "error": 3021,
   "message": "Timeout executing API request"
}
```

And like before, the agent got upgraded with the API properly but i didn't have a good return from the API.

Result of the agent upgrade with the API in Grafana :
![image](https://user-images.githubusercontent.com/33425208/71617261-96ac3100-2bba-11ea-8942-de36f37f0436.png)

I've tested this with **Linux AND Windows** from VM outside the manager subnet and it's working properly.
There is some kind of issue with the "agent_upgrade" command but it's working with the API

I can't try this process on the 2 mentionned VM above because there has been some changes in the FW in there network and there a not able to communicate with my wazuh load balancer anymore. But i will try later.


For the timeout issue with the API, i think i pinpoint the issue : I got a static redirection on the FW to redirect every connection with the destination port 1514-1515 to my LoadBalancer. If the manager communication the upgrade process to the agents with these ports, my manager will never got the answer from the agent because the response got routed to the LoadBalancer.
Or the manager is using another port to communicate with the client and i should check the FW configuration to let this port through my subnet.
On the officiel documentation, i'm only seeing the port 55000 being used by the api and nothing else. We should have the choise to use another port for the upgrade process.

Maybe that's not the issue but i think this is the problem :/

**Comment by Theoooooo** [comment]
@sergiovp 
Another update on the subject, i got agent_upgrade mostly working with the following command :
```
bin/agent_upgrade -a 028 -dF -f /var/ossec/var/upgrade/wazuh_agent_v3.10.2_windows.wpk -x upgrade.bat
```

If i don't specify the file with the "-f" option, the process stop immediately with the following error :
```
bin/agent_upgrade -a 016 -dF -v v3.10.2 --http
Manager version: 3.11.0
Agent version: Wazuh v3.11.0
Agent new version: v3.10.2
WPK file already downloaded: /var/ossec/var/upgrade/wazuh_agent_v3.10.2_linux_x86_64.wpk - SHA1SUM:                                                                                                            216f793e1ccaece72ec2f0c46e54c37e1f9b8606
Upgrade PKG: wazuh_agent_v3.10.2_linux_x86_64.wpk (4877.83203125 KB)
MSG SENT: 016 com lock_restart -1
RESPONSE: err Cannot send request
Error 1715: Error sending WPK file: Cannot send request
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 167, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 121, in main
    rl_timeout=-1 if args.timeout == None else args.timeout, use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.11.0-py3.7.egg/wazuh/agent.p                                                                                                           y", line 2159, in upgrade
    use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.11.0-py3.7.egg/wazuh/agent.p                                                                                                           y", line 2010, in _send_wpk_file
    raise WazuhException(1715, data.replace("err ",""))
wazuh.exception.WazuhException: Error 1715 - Error sending WPK file: Cannot send request
```

Also, the manager is never getting a response from the agent and timeouts occur as the agent does not respond to the upgrade process :
```
bin/agent_upgrade -a 028 -dF -f /var/ossec/var/upgrade/wazuh_agent_v3.10.2_windows.wpk -x upgrade.bat
Custom WPK file: wazuh_agent_v3.10.2_windows.wpk (2553.669921875 KB)
MSG SENT: 028 com lock_restart -1
RESPONSE: ok
MSG SENT: 028 com open wb wazuh_agent_v3.10.2_windows.wpk
RESPONSE: ok
Chunk size: 512 bytes
FILE SHA1: 1141118b0e3548e65031346aa10f65fbf5ad408c
MSG SENT: 028 com close wazuh_agent_v3.10.2_windows.wpk
RESPONSE: ok
MSG SENT: 028 com sha1 wazuh_agent_v3.10.2_windows.wpk
RESPONSE: ok 1141118b0e3548e65031346aa10f65fbf5ad408c
WPK file sent
MSG SENT: 028 com upgrade wazuh_agent_v3.10.2_windows.wpk upgrade.bat
RESPONSE: ok 0
Installation started
MSG SENT: 028 com upgrade_result
RESPONSE: err Cannot read upgrade_result file.
MSG SENT: 028 com upgrade_result
^C
```
But with this, the agent gets undeed upgraded and restarted properly after the process is finished, like the api above : the response is not being received by the manager under my configuration
