### ISSUE TITLE
ossec-dbd failing to start using MySQL

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#4385]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2 | ossec-dbd | Manager/Agent | Sources | Ubuntu 16 / Windows Server |

When setting up an external MySQL database in Windows Server, the ossec-dbd module in the manager generates a Segmentation fault trying to connect to the database.   
The output executing `/var/ossec/bin/ossec-dbd -df` is the following one:
```
2019/12/13 16:09:12 ossec-dbd[9456] rules-config.c:375 at Read_Rules(): DEBUG: Adding rule: ruleset/rules/0625-cisco-asa_rules.xml
2019/12/13 16:09:12 ossec-dbd[9456] rules-config.c:375 at Read_Rules(): DEBUG: Adding rule: ruleset/rules/0195-named_rules.xml
2019/12/13 16:09:12 ossec-dbd[9456] rules-config.c:375 at Read_Rules(): DEBUG: Adding rule: ruleset/rules/0515-exim_rules.xml
2019/12/13 16:09:12 ossec-dbd[9456] rules-config.c:375 at Read_Rules(): DEBUG: Adding rule: ruleset/rules/0305-dropbear_rules.xml
2019/12/13 16:09:12 ossec-dbd[9456] rules-config.c:331 at Read_Rules(): DEBUG: Reading rules folder: etc/rules
2019/12/13 16:09:12 ossec-dbd[9456] rules-config.c:375 at Read_Rules(): DEBUG: Adding rule: etc/rules/local_rules.xml
2019/12/13 16:09:12 ossec-dbd[9456] rules-config.c:389 at Read_Rules(): DEBUG: Decoders added: 100 / excluded: 0
2019/12/13 16:09:12 ossec-dbd[9456] rules-config.c:390 at Read_Rules(): DEBUG: Rules added: 125 / excluded: 1
2019/12/13 16:09:12 ossec-dbd[9456] main.c:187 at main(): DEBUG: Connecting to '192.168.***.**', using 'MySQLadmin', '****************', 'Alerts_DB', 0,'(null)'.
Segmentation fault
```
The configuration used to reproduce this issue is this one:
```xml
  <!--Database -->
  <database_output>
    <hostname>192.168.***.**</hostname>
    <username>MySQLadmin</username>
    <password>****************</password>
    <database>Alerts_DB</database>
    <type>mysql</type>
  </database_output> 
```
The log from mysql is this one:
```
2019-12-13T15:38:42.407769Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2019-12-13T15:38:42.411530Z 0 [Note] /usr/sbin/mysqld (mysqld 5.7.28-0ubuntu0.18.04.4) starting as process 5238 ...
2019-12-13T15:38:42.423507Z 0 [Note] InnoDB: PUNCH HOLE support available
2019-12-13T15:38:42.423572Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-12-13T15:38:42.423593Z 0 [Note] InnoDB: Uses event mutexes
2019-12-13T15:38:42.423612Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2019-12-13T15:38:42.423630Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2019-12-13T15:38:42.423649Z 0 [Note] InnoDB: Using Linux native AIO
2019-12-13T15:38:42.424364Z 0 [Note] InnoDB: Number of pools: 1
2019-12-13T15:38:42.424666Z 0 [Note] InnoDB: Not using CPU crc32 instructions
2019-12-13T15:38:42.429527Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2019-12-13T15:38:42.456022Z 0 [Note] InnoDB: Completed initialization of buffer pool
2019-12-13T15:38:42.461074Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2019-12-13T15:38:42.474812Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2019-12-13T15:38:42.507767Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2019-12-13T15:38:42.507931Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-12-13T15:38:42.642222Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-12-13T15:38:42.644597Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2019-12-13T15:38:42.644641Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2019-12-13T15:38:42.645567Z 0 [Note] InnoDB: Waiting for purge to start
2019-12-13T15:38:42.695949Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 2685567
2019-12-13T15:38:42.696371Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2019-12-13T15:38:42.696788Z 0 [Note] Plugin 'FEDERATED' is disabled.
2019-12-13T15:38:42.702445Z 0 [Note] InnoDB: Buffer pool(s) load completed at 191213 15:38:42
2019-12-13T15:38:42.711730Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2019-12-13T15:38:42.711773Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2019-12-13T15:38:42.713303Z 0 [Warning] CA certificate ca.pem is self signed.
2019-12-13T15:38:42.713396Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2019-12-13T15:38:42.713614Z 0 [Note] Server hostname (bind-address): '192.168.***.**'; port: 3306
2019-12-13T15:38:42.713658Z 0 [Note]   - '192.168.***.**' resolves to '192.168.***.**';
2019-12-13T15:38:42.713736Z 0 [Note] Server socket created on IP: '192.168.***.**'.
2019-12-13T15:38:42.739859Z 0 [Note] Event Scheduler: Loaded 0 events
2019-12-13T15:38:42.740535Z 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '5.7.28-0ubuntu0.18.04.4'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)
2019-12-13T15:41:58.968598Z 2 [Warning] Hostname '******' does not resolve to '192.168.***.**'.
2019-12-13T15:41:58.968621Z 2 [Note] Hostname '******' has the following IP addresses:
2019-12-13T15:41:58.968630Z 2 [Note]  - 127.0.1.1
2019-12-13T15:41:59.135552Z 2 [Note] Bad handshake
2019-12-13T15:42:15.673056Z 3 [Note] Bad handshake
2019-12-13T15:43:35.510265Z 4 [Note] Bad handshake
2019-12-13T15:43:45.275216Z 5 [Note] Bad handshake
2019-12-13T16:07:19.202957Z 6 [Note] Bad handshake
2019-12-13T16:09:12.992976Z 7 [Note] Bad handshake
```
<br>

This issue was reported by an user [here](https://groups.google.com/forum/?#!msg/wazuh/tstoevZVDZk/eSGBkUhXAgAJ).

**Comment by antoniomanuelfr** [comment]
Hi all!!

I have been investigating this issue and it seems that this is an isolated problem with the external libraries of 3.10.2. After testing 3.11.0 the segmentation fault is gone.

This is the backtrace of the segmentation fault:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7837370 in OPENSSL_sk_push () from /var/ossec/lib/libwazuhext.so
(gdb) bt
#0  0x00007ffff7837370 in OPENSSL_sk_push () from /var/ossec/lib/libwazuhext.so
#1  0x00007ffff7847112 in X509_STORE_add_lookup () from /var/ossec/lib/libwazuhext.so
#2  0x00007ffff7846724 in X509_STORE_set_default_paths () from /var/ossec/lib/libwazuhext.so
#3  0x00007ffff6e49394 in ?? () from /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20
#4  0x00007ffff6e49a13 in ?? () from /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20
#5  0x00007ffff6e1c427 in mysql_real_connect () from /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20
#6  0x000055555555ea19 in mysql_osdb_connect (host=0x555555899480 "10.2.0.12", user=0x5555558b1f90 "MySQLadmin", pass=0x5555558b8600 "secret1234", db=0x5555558b8650 "Alerts_DB", port=0, sock=0x0) at os_dbd/db_op.c:191
#7  0x000055555555fbf4 in main (argc=2, argv=0x7fffffffe588) at os_dbd/main.c:199
```

If you are experiencing this problem, please update to at least 3.11.0 and the problem should be gone. In any case, feel free to re-open this issue again if it's necessary. 

Kind regards.
