### ISSUE TITLE
Codepage issue

### ISSUE THREAD

**Issue by Bars7878** [wazuh/wazuh#4386]
Hello! I install wazuh agent 3.10.2 on windows with russian localization. After settings integration with virustotal checks are not performed. I start debugging and found error:

2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:126 at OS_IntegratorD(): DEBUG: jqueue_next()
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:131 at OS_IntegratorD(): DEBUG: sending new alert.
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:263 at OS_IntegratorD(): DEBUG: file /tmp/virustotal-1576593086--1941690450.alert was written.
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:389 at OS_IntegratorD(): DEBUG: Running: /var/ossec/integrations/virustotal /tmp/virustotal-1576593086--1941690450.alert 0150d28ac963e36e8654d9245be4af9389ca959d31eae45eabf7229e6902ae32 debug
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: Traceback (most recent call last):
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: File "/var/ossec/integrations/virustotal.py", line 209, in <module>
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: main(sys.argv)
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: File "/var/ossec/integrations/virustotal.py", line 59, in main
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: json_alert = json.load(alert_file)
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: File "/var/ossec/framework/python/lib/python3.7/json/__init__.py", line 293, in load
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: return loads(fp.read(),
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: File "/var/ossec/framework/python/lib/python3.7/codecs.py", line 322, in decode
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: (result, consumed) = self._buffer_decode(data, self.errors, final)
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 565: invalid start byte
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:410 at OS_IntegratorD(): ERROR: Unable to run integration for virustotal -> /var/ossec/integrations/virustotal
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:411 at OS_IntegratorD(): ERROR: While running virustotal -> /var/ossec/integrations/virustotal. Output: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 565: invalid start byte
 
2019/12/17 14:31:26 ossec-integratord[3765] integrator.c:126 at OS_IntegratorD(): DEBUG: jqueue_next()2019/12/17 14:31:27 ossec-integratord[3765] integrator.c:126 at OS_IntegratorD(): DEBUG: jqueue_next()
 
2019/12/17 14:31:28 ossec-integratord[3765] integrator.c:126 at OS_IntegratorD(): DEBUG: jqueue_next()

As i understanding the cause of the error is {"name":"��������������"

Example a alert file from /tmp/:

{{"timestamp":"2019-12-19T20:14:48.800+0000","rule":{"level":5,"description":"File added to the system.","id":"554","firedtimes":4,"mail":false,"groups":["ossec","syscheck"],"p
ci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"],"hipaa":["164.312.c.1","164.312.c.2"],"nist_800_53":["SI.7"]},"agent":{"id":"022","name":"PC","ip":"172.23.52.29"},"m
anager":{"name":"wazuh"},"id":"1576786488.13835242","full_log":"File 'c:\\!work\\!test\\ssh-ace.txt' was added.\n","syscheck":{"path":"c:\\!work\\!test\\ssh-ace.txt","size_aft
er":"9","win_perm_after":[{"name":"��������������","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_D
ATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES"]},{"name":"�������","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWN
ER","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_DATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES"]},{"name":
"������������","allowed":["READ_CONTROL","SYNCHRONIZE","FILE_READ_DATA","FILE_READ_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES"]},{"name":"��������� ��������","allowed":["DELETE"
,"READ_CONTROL","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_DATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES
"]}],"uid_after":"S-1-5-21-48403399-1996387153-1062149088-32796","md5_after":"00f3ff5919ca7fdfef38e580bdd400df","sha1_after":"0a802c269bd4edbba33b3ee24338fd2f46cbbc0e","sha256
_after":"af3c5c76f30974dc7ee429d7522ccbc16dcccca12ab210c14e980f5dab4a67b5","attrs_after":["ARCHIVE"],"uname_after":"adm","mtime_after":"2019-10-20T11:48:30","event
":"added"},"decoder":{"name":"syscheck_new_entry"},"location":"syscheck"}

In russian localization groups and users named cyrillic:
SYSTEM - СИСТЕМА
ADMINISTRATORS - Администраторы and etc.
screen for example: https://groups.google.com/group/wazuh/attach/74be955ae41b2/vt-error.JPG?part=0.1&view=1&authuser=0

How i can resolve this?

**Comment by Bars7878** [comment]
I upgrade to 3.11 wazuh-master and agent, but the problem persists.

**Comment by Zenidd** [comment]
Hello @Bars7878,

I'm sorry you're having this problem. Thank you for reporting this problem and sending us the debug messages.  We have been able to reproduce the bug and we found other on the way:

These bugs occur in the FIM context, when creating, modifying and removing files with Cyrillic characters in its attributes or names. 

> I upgrade to 3.11 wazuh-master and agent, but the problem persists.

We have just become aware of this problem so, for now, updating Wazuh won't fix the problem.


### Files with entity names containing Cyrillic characters 
The entity details with Cyrillic characters aren't correctly interpreted and written in the alert.(json|log) file.

- Permissions containing Cyrillic characters
![cyrillic1](https://user-images.githubusercontent.com/14923294/71411768-fbabd800-264a-11ea-83f0-a0028205be09.png)

- Alert with entity name missing and filled with `??????????????` after changing permissions
```
{"timestamp":"2019-12-24T12:12:22.049+0100","rule":{"level":7,"description":"Integrity checksum changed.","id":"550","firedtimes":1,"mail":false,"groups":["ossec","syscheck"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"],"hipaa":["164.312.c.1","164.312.c.2"],"nist_800_53":["SI.7"]},"agent":{"id":"001","name":"W10","ip":"192.168.75.141"},"manager":{"name":"nanoPill"},"id":"1577185942.7627733","full_log":"File 'c:\\test\\caracteres\\nuevo documento de texto enriquecido.rtf' checksum changed.\nPermissions changed.\n(Audit) User: 'Администраторы (S-1-5-21-2635242741-4024004514-10403589-1003)'\n(Audit) Process id: '5264'\n(Audit) Process name: 'C:\\Windows\\explorer.exe'\n","syscheck":{"path":"c:\\test\\caracteres\\nuevo documento de texto enriquecido.rtf","size_after":"7","win_perm_before":[{"name":"Administradores","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_DATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES"]},{"name":"SYSTEM","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_DATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES"]},{"name":"Usuarios","allowed":["READ_CONTROL","SYNCHRONIZE","FILE_READ_DATA","FILE_READ_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES"]},{"name":"Usuarios autentificados","allowed":["DELETE","READ_CONTROL","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_DATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES"]}],"win_perm_after":[{"name":"??????????????","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_DATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES"]},{"name":"Administradores","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_DATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES"]},{"name":"SYSTEM","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_DATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES"]},{"name":"Usuarios","allowed":["READ_CONTROL","SYNCHRONIZE","FILE_READ_DATA","FILE_READ_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES"]},{"name":"Usuarios autentificados","allowed":["DELETE","READ_CONTROL","SYNCHRONIZE","FILE_READ_DATA","FILE_WRITE_DATA","FILE_APPEND_DATA","FILE_READ_EA","FILE_WRITE_EA","FILE_EXECUTE","FILE_READ_ATTRIBUTES","FILE_WRITE_ATTRIBUTES"]}],"uid_after":"S-1-5-21-2635242741-4024004514-10403589-1003","md5_after":"8274425de767b30b2fff1124ab54abb5","sha1_after":"2201589aa3ed709b3665e4ff979e10c6ad5137fc","sha256_after":"0d6afb7e939f0936f40afdc759b5a354ea5427ec250a47e7b904ab1ea800a01d","attrs_after":["ARCHIVE"],"uname_after":"??????????????","mtime_after":"2019-12-24T12:10:44","event":"modified","audit":{"user":{"id":"S-1-5-21-2635242741-4024004514-10403589-1003","name":"Администраторы"},"process":{"id":"5264","name":"C:\\Windows\\explorer.exe"}}},"decoder":{"name":"syscheck_integrity_changed"},"location":"syscheck"}
```

### Filenames containing Cyrillic characters
The further log shows that Wazuh has an unexpected behavior when processing handling this event with filename containing Cyrillic chars.
```
2019/12/24 11:30:03 ossec-agent[3960] win_whodata.c:630 at whodata_callback(): DEBUG: (6298): Removed folder event received for 'c:\test\caracteres\bbb?????????????bbb.txt'.
2019/12/24 11:30:03 ossec-agent[3960] win_whodata.c:843 at whodata_callback(): DEBUG: (6245): The '(null)' directory has not been scanned because no new files have been detected. Mask: '100'
```
After this event, there is no related alerts(.json|.log) entry. 

As soon as our workflow allows us, we will work on this issue fix. You can track the fixing progress here. I hope it helps.

Greetings, JP Sáez

**Comment by Bars7878** [comment]
Thank you so much for your assistance.

**Comment by gafbich** [comment]
Good day everyone, is there a solution to the problem with displaying the Cyrillic alphabet?

**Comment by Zenidd** [comment]
Hello again @gafbich, 

Unfortunately we are still working on it. There are a few other issues related to this topic:

- https://github.com/wazuh/wazuh/issues/834
- https://github.com/wazuh/wazuh/issues/2008
- https://github.com/wazuh/wazuh/issues/2514

We already have a PR that aims to solve this, you can keep a track of it here: https://github.com/wazuh/wazuh/pull/2677. 
Sorry for the inconvenience. Maybe you can find useful information from other users with the same scenario in our [#Community Slack channel](https://wazuh.com/community/join-us-on-slack/.)

Regards,

JP

**Comment by Bars7878** [comment]
Hi! I upgrade wazuh to 4.0.1 but virustotal  integration dont cheks added files (rule 554) in Windows with cyrilic localization. Issue still persist. Please, let me know about resolve this?

**Comment by fatiheker** [comment]
Hello folks.

We have same issue with Turkish characters.
![TurkishAlphabetIssue](https://user-images.githubusercontent.com/16756484/110636996-0013d080-81be-11eb-8ef5-9436329c7bf9.jpeg)

**Comment by slayerjk** [comment]
Hi all.

Wazuh version 4.2.5.

I get such events from Russian(Cyrillic) windows version in alerts.json:
```
..."syscheck":{"path":"HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies","mode":"scheduled","arch":"[x32]","win_perm_after":[{"name":"▒▒▒▒▒▒▒","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","READ_DATA","WRITE_DATA","APPEND_DATA","READ_EA","WRITE_EA","EXECUTE"]},{"name":"▒▒▒▒▒▒▒▒▒▒▒▒▒▒","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","READ_DATA","WRITE_DATA","APPEND_DATA","READ_EA","WRITE_EA","EXECUTE"]},{"name":"▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒","allowed":["READ_CONTROL","READ_DATA","READ_EA","WRITE_EA"]},{"name":"▒▒▒ ▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒","allowed":["READ_CONTROL","READ_DATA","READ_EA","WRITE_EA"]},{"name":"S-1-15-3-1024-1065365936-1281604716-3511738428-1654721687-432734479-3232135806-4053264122-3456934681","allowed":["READ_CONTROL","READ_DATA","READ_EA","WRITE_EA"]}],"uid_after":"S-1-5-18","gid_after":"S-1-5-18","uname_after":"▒▒▒▒▒▒▒","gname_after":"▒▒▒▒▒▒▒","mtime_before":"2022-02-15T13:18:11","mtime_after":"2022-02-16T10:13:05","changed_attributes":["mtime"],"event":"modified"},"decoder":{"name":"syscheck_registry_key_modified"},"location":"syscheck"}
```

And Kibana show Russian(Cyrillic) symbols like this:
![image](https://user-images.githubusercontent.com/20660728/154223587-a8797406-f6ba-446c-a39c-6a9039e1f20e.png)
