### ISSUE TITLE
Restore alert from 2.x to 3.x

### ISSUE THREAD

**Issue by demantos** [wazuh/wazuh#526]
I use wazuh 2.x now, and I will upgrade to 3.x.
First I need to test elasticsearch snapshot restore and wazuh alert migration task.
Elasticsearch snapshot restore is successfully but restore_alerts.sh is pending after some index restored.
Here is my state.

Run restore_alerts.sh
```
[root@logbackup wazuh-3.x]# ./restore_alerts.sh 2018-02-01 2018-04-10 localhost ELS2ELS 
### Wazuh - Alerts restoration ###
##### Starting, reindexing alerts from 2018-02-01 to 2018-04-10
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
```

elasticsearch log
```
[2018-04-12T11:08:24,388][INFO ][o.e.c.m.MetaDataCreateIndexService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.01] creating index, cause [auto(bulk api)], templates [wazuh], shards [1]/[0], mappings [wazuh]
[2018-04-12T11:08:24,544][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.01/d-WkGDjqTFemeQ9OBkF2NQ] update_mapping [wazuh]
[2018-04-12T11:08:24,555][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.01/d-WkGDjqTFemeQ9OBkF2NQ] update_mapping [wazuh]
[2018-04-12T11:08:24,628][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.01/d-WkGDjqTFemeQ9OBkF2NQ] update_mapping [wazuh]
[2018-04-12T11:08:24,630][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.01/d-WkGDjqTFemeQ9OBkF2NQ] update_mapping [wazuh]
[2018-04-12T11:08:24,691][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.01/d-WkGDjqTFemeQ9OBkF2NQ] update_mapping [wazuh]
[2018-04-12T11:08:33,503][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.01/d-WkGDjqTFemeQ9OBkF2NQ] update_mapping [wazuh]
[2018-04-12T11:08:37,037][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.01/d-WkGDjqTFemeQ9OBkF2NQ] update_mapping [wazuh]
[2018-04-12T11:08:39,412][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.01/d-WkGDjqTFemeQ9OBkF2NQ] update_mapping [wazuh]
[2018-04-12T11:09:04,394][INFO ][o.e.c.m.MetaDataCreateIndexService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.02] creating index, cause [auto(bulk api)], templates [wazuh], shards [1]/[0], mappings [wazuh]
[2018-04-12T11:09:04,507][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.02/NrBTOgzLQ021lGK2LZg5eQ] update_mapping [wazuh]
[2018-04-12T11:09:04,639][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.02/NrBTOgzLQ021lGK2LZg5eQ] update_mapping [wazuh]
[2018-04-12T11:09:04,705][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.02/NrBTOgzLQ021lGK2LZg5eQ] update_mapping [wazuh]
[2018-04-12T11:09:04,778][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.02/NrBTOgzLQ021lGK2LZg5eQ] update_mapping [wazuh]
[2018-04-12T11:09:06,430][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.02/NrBTOgzLQ021lGK2LZg5eQ] update_mapping [wazuh]
[2018-04-12T11:09:09,177][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.02/NrBTOgzLQ021lGK2LZg5eQ] update_mapping [wazuh]
[2018-04-12T11:09:40,986][INFO ][o.e.c.m.MetaDataCreateIndexService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.03] creating index, cause [auto(bulk api)], templates [wazuh], shards [1]/[0], mappings [wazuh]
[2018-04-12T11:09:41,119][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.03/FJlBscumQNu6Yg5HOq4oHw] update_mapping [wazuh]
[2018-04-12T11:09:41,128][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.03/FJlBscumQNu6Yg5HOq4oHw] update_mapping [wazuh]
[2018-04-12T11:09:41,194][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.03/FJlBscumQNu6Yg5HOq4oHw] update_mapping [wazuh]
[2018-04-12T11:09:42,116][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.03/FJlBscumQNu6Yg5HOq4oHw] update_mapping [wazuh]
[2018-04-12T11:09:51,462][INFO ][o.e.c.m.MetaDataMappingService] [millennium-falcon] [wazuh-alerts-3.x-2018.02.03/FJlBscumQNu6Yg5HOq4oHw] update_mapping [wazuh]
```

above pending state lasts more than 1 hour. 
2018.02.01, 2018.02.02 index is restored less than 1m.
2018.02.03 restore task is pending? or next task is not start?

2.x index state
```
GET /_cat/indices/wazuh-alerts-2018.02.0*?v&s=index:asc
health status index                   uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   wazuh-alerts-2018.02.01 ivud01HOR5G0O3Urnap0hA   5   0     193758            0    172.2mb        172.2mb
green  open   wazuh-alerts-2018.02.02 zOcpTxD4T--Sk1QQKG7ytA   5   0     184444            0    162.7mb        162.7mb
green  open   wazuh-alerts-2018.02.03 XN9Ue0Y4Qs2a1IGozIaLOQ   5   0     138397            0    111.2mb        111.2mb
```

Restored index is here
```
GET /_cat/indices/wazuh-alerts-3.*?v&s=index:asc
health status index                       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   wazuh-alerts-3.x-2018.02.01 d-WkGDjqTFemeQ9OBkF2NQ   1   0     193758            0    116.1mb        116.1mb
green  open   wazuh-alerts-3.x-2018.02.02 NrBTOgzLQ021lGK2LZg5eQ   1   0     184444            0    109.5mb        109.5mb
green  open   wazuh-alerts-3.x-2018.02.03 FJlBscumQNu6Yg5HOq4oHw   1   0     138397            0     77.1mb         77.1mb
```

I think 2018.02.03 index restore task is done because `docs.count` is same.
If so, why next index is not proceeded?
How can I done this restore alerts?

Regards

**Comment by demantos** [comment]
here is logstash log.
```
[2018-04-12T13:34:12,458][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::Mutate", {"rename"=>{"[data2]"=>"[data]"}, "remove_field"=>["data2"], "id"=>"1358d6b6d8b77dc53cf85dc91e7257cec97920bb92ed065dfad94f9b43d77815"}]=>[{"thread_id"=>40, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:90:in `read_batch'"}]}}
[2018-04-12T13:34:17,457][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::Mutate", {"rename"=>{"[data2]"=>"[data]"}, "remove_field"=>["data2"], "id"=>"1358d6b6d8b77dc53cf85dc91e7257cec97920bb92ed065dfad94f9b43d77815"}]=>[{"thread_id"=>40, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:90:in `read_batch'"}]}}
[2018-04-12T13:34:22,458][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::Mutate", {"rename"=>{"[data2]"=>"[data]"}, "remove_field"=>["data2"], "id"=>"1358d6b6d8b77dc53cf85dc91e7257cec97920bb92ed065dfad94f9b43d77815"}]=>[{"thread_id"=>40, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:90:in `read_batch'"}]}}
```
