### ISSUE TITLE
timestamp out of range for platform time_t", "error": 1000

### ISSUE THREAD

**Issue by erepiso** [wazuh/wazuh#5357]
I am having problems to syncronize KIBANA Wazuh APP, with Wazuh-API. 

After configuring /usr/share/kibana/optimize/wazuh/config/wazuh.yml; API  connection fails.

ELK Version: 7.8.0
Wazuh Manager: 3.13.0 + Filebeat
Wazuh Agents: 3.12.3

Some tests: 

**Failed Tests**:
**test1:** 
```
curl -u foo:bar -X GET "http://192.168.10.5:55000/agents/outdated?pretty"
{
   "error": 1000,
   "message": "Internal error"
}

logs/api.log

WazuhAPI 2020-06-29 13:01:23 foo: Sending SIGTERM to CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents/outdated","arguments":{"wait_for_complete":false}}
WazuhAPI 2020-06-29 13:01:37 foo: 192.168.10.5 GET /agents/outdated
WazuhAPI 2020-06-29 13:01:37 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents/outdated","arguments":{"wait_for_complete":false}}
WazuhAPI 2020-06-29 13:01:43 foo: CMD - Exit code: 0
WazuhAPI 2020-06-29 13:01:43 foo: CMD - STDOUT:
---
{"message": "timestamp out of range for platform time_t", "error": 1000}

---
WazuhAPI 2020-06-29 13:01:43 foo: CMD - STDOUT: 73 bytes
WazuhAPI 2020-06-29 13:01:43 foo: timestamp out of range for platform time_t
WazuhAPI 2020-06-29 13:01:43 foo: [192.168.10.5] GET /agents/outdated?pretty - 200 - error: '1000'.

```
**test2:** 
```
curl -u foo:bar http://192.168.10.5:55000/agents/000?pretty
{
"error": 1000,
"message": "Internal error"
}

logs/api.log
WazuhAPI 2020-06-29 13:02:15 foo: 192.168.10.5 GET /agents/:agent_id
WazuhAPI 2020-06-29 13:02:15 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents/:agent_id","arguments":{"agent_id":"000","wait_for_complete":false}}
WazuhAPI 2020-06-29 13:02:21 foo: CMD - Exit code: 0
WazuhAPI 2020-06-29 13:02:21 foo: CMD - STDOUT:
---
{"message": "timestamp out of range for platform time_t", "error": 1000}
---
WazuhAPI 2020-06-29 13:02:21 foo: CMD - STDOUT: 73 bytes
WazuhAPI 2020-06-29 13:02:21 foo: timestamp out of range for platform time_t
WazuhAPI 2020-06-29 13:02:21 foo: [192.168.10.5] GET /agents/000?pretty - 200 - error: '1000'.
```

**TEST THAT WORK:**
```
curl -u foo:bar http://192.168.10.5:55000/agents/001?pretty
{
   "error": 0,
   "data": {
      "os": {
         "arch": "armv7",
         "codename": "buster",
         "major": "10",
……..
          }
}
logs/api.log
WazuhAPI 2020-06-29 13:03:00 foo: 192.168.10.5 GET /agents/:agent_id
WazuhAPI 2020-06-29 13:03:00 foo: CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents/:agent_id","arguments":{"agent_id":"001","wait_for_complete":false}}
WazuhAPI 2020-06-29 13:03:00 foo: Sending SIGTERM to CMD - Command: /var/ossec/framework/python/bin/python3 args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents/:agent_id","arguments":{"agent_id":"000","wait_for_complete":false}}
WazuhAPI 2020-06-29 13:03:06 foo: CMD - Exit code: 0
WazuhAPI 2020-06-29 13:03:06 foo: CMD - STDOUT:
---
{"data": {"os": {"arch": "armv7", "codename": "buster", "major": "10", ……………."error": 0}
---
WazuhAPI 2020-06-29 13:03:06 foo: CMD - STDOUT: 603 bytes
WazuhAPI 2020-06-29 13:03:06 foo: [192.168.10.5] GET /agents/001?pretty - 200 - error: '0'.
```

**Comment by davidjiglesias** [comment]
Hello @erepiso,

Could you please check and provide the output of this command in the same machine where you executed test_2?

`sqlite3 /var/ossec/var/db/global.db "SELECT date_add, last_keepalive FROM agent WHERE id=000"`

I believe there might be an issue with one of those values in your environment. It might help us to identify the problem.

Best regards,

David J. Iglesias

**Comment by erepiso** [comment]
> Hello @erepiso,
> 
> Could you please check and provide the output of this command in the same machine where you executed test_2?
> 
> `sqlite3 /var/ossec/var/db/global.db "SELECT date_add, last_keepalive FROM agent WHERE id=000"`
> 
> I believe there might be an issue with one of those values in your environment. It might help us to identify the problem.
> 
> Best regards,
> 
> David J. Iglesias

Hello David, 

Thank you for your answer, 

this is the result of executing the query: 
```

sqlite3 /var/ossec/var/db/global.db "SELECT date_add, last_keepalive FROM agent WHERE id=000"
1593423706|253402300799
```

**all Info for 000**; maybe ipAddres should be the the one in the interface (where the API is bind?)

```
sqlite3 /var/ossec/var/db/global.db "SELECT * FROM agent WHERE id=000"
0|vozpopuli|127.0.0.1|127.0.0.1||Debian GNU/Linux|10|10||buster||debian|Linux |vozpopuli |4.19.0-9-686-pae |#1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) |i686|i686|Wazuh v3.13.0|||vozpopuli|node01|1593423706|253402300799|updated|0|0|

```
**Info for agent 001:**
```
sqlite3 /var/ossec/var/db/global.db "SELECT date_add, last_keepalive FROM agent WHERE id=001"
0|1593447382
```

Thank you so much
Eduardo.

**Comment by davidjiglesias** [comment]
Hello again @erepiso,

The values from the database do not look to have any issue. This is a very weird error, we usually do not need to come to this, but, could you please try the following:

Open embedded python3 console in the same machine where you performed the queries:
```/var/ossec/framework/python/bin/python3```

Then try:
```
>>> from wazuh.manager import get_info
>>> get_info()
```

You should be getting a dict with the response, like this example:
```
{'path': '/var/ossec', 'version': 'v3.13.0', 'compilation_date': 'Thu Jun 11 08:07:07 UTC 2020', 'type': 'server', 'max_agents': 'N/A', 'openssl_support': 'N/A', 'ruleset_version': '31304', 'tz_offset': '+0000', 'tz_name': 'UTC', 'name': '95aadee0e1d3', 'cluster': {'enabled': 'yes', 'running': 'yes', 'name': 'wazuh', 'node_name': 'master-node', 'node_type': 'master'}}
```
In your case I expect the platform time_t error to raise here, and maybe we can get a better trace of the error.

Thank you.

**Comment by erepiso** [comment]
Thank you for your answer; just one clarification, this is my platform: 

`Linux vozpopuli 4.19.0-9-686-pae #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) i686 GNU/Linux
`

here it is the result of the execution
```

>>> from wazuh.manager import get_info

>>> get_info()

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/manager.py", line 561, in get_info

    manager._load_info_from_DB()

  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 260, in _load_info_from_DB

    data = db_query.run()['items'][0]

  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/utils.py", line 1092, in run

    return self._format_data_into_dictionary()

  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 128, in _format_data_into_dictionary

    self._data = [{key: format_fields(key, value, today, item.get('lastKeepAlive'), item.get('version'))

  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 128, in <listcomp>

    self._data = [{key: format_fields(key, value, today, item.get('lastKeepAlive'), item.get('version'))

  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 128, in <dictcomp>

    self._data = [{key: format_fields(key, value, today, item.get('lastKeepAlive'), item.get('version'))

  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 112, in format_fields

    return Agent.calculate_status(lastKeepAlive, version is None, today)

  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 248, in calculate_status

    last_date = datetime.utcfromtimestamp(last_keep_alive)

OverflowError: timestamp out of range for platform time_t
```

Additionally, after hardcoding some codelines:
- line 248 and 249: 
    * last_date=1593510078
    * difference=0

This is the error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/manager.py", line 561, in get_info
    manager._load_info_from_DB()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 262, in _load_info_from_DB
    data = db_query.run()['items'][0]
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/utils.py", line 1092, in run
    return self._format_data_into_dictionary()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 128, in _format_data_into_dictionary
    self._data = [{key: format_fields(key, value, today, item.get('lastKeepAlive'), item.get('version'))
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 128, in <listcomp>
    self._data = [{key: format_fields(key, value, today, item.get('lastKeepAlive'), item.get('version'))
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 128, in <dictcomp>
    self._data = [{key: format_fields(key, value, today, item.get('lastKeepAlive'), item.get('version'))
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-3.13.0-py3.8.egg/wazuh/agent.py", line 116, in format_fields
    return datetime.utcfromtimestamp(value).strftime("%Y-%m-%d %H:%M:%S")
OverflowError: timestamp out of range for platform time_t
```

Thank you so much!
Eduardo.

**Comment by davidjiglesias** [comment]
Hello @erepiso,

After further investigating the data you have provided it seems as if your platform `time_t` uses a 32 bit signed integer. It means it only support timestamps up to `2147483647`, with date `Tue, 19 Jan 2038 03:14:07 +0000`, while the value for the `last_keepalive` in the database for the manager uses `253402300799`, with date `Fri, 31 Dec 9999 23:59:59 +0000`. This causes the `OverflowError` when trying to obtain a datetime value from that timestamp in your platform.

I have let the Wazuh team know about your problem and they will be further investigating the issue to possibly add support to `time_t` platforms using 32 bit signed integer in future releases.

As a temporary solution, you could do the following to change the value to something your platform would admit:
`sqlite3 /var/ossec/var/db/global.db "UPDATE agent SET last_keepalive=2145916800 WHERE id=000"`

Take into account that this value has to be changed in the Wazuh managers (if you use more than one) and that it will be restored back to the original one if you upgrade the manager or accidentally delete `global.db`.

We are sorry for any inconveniences this may cause.

Best regards and thank you,

David J. Iglesias

**Comment by erepiso** [comment]
Hello David!!! 

Great!!  thank you!! it worked!!! thank you so much!!!!

I will take into account your hightlights. 

Thanks!
Eduardo
