### ISSUE TITLE
[Framework] Add support for new logtest tool

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#5590]
| Working branch |
| - |
| [feature/5590-dev-logtest-framework](https://github.com/wazuh/wazuh/tree/feature/5590-dev-logtest-framework) |

# Description

Hello team. As explained here https://github.com/wazuh/wazuh/issues/5337 and in order to support the new API endpoints requested in https://github.com/wazuh/wazuh/issues/5577, it is needed to create new framework functions that allow the API to use `logtest`.

Those functions should be inside new framework modules called `framework/logtest.py` and `framework/core/logtest.py` 
 
## 1. Check if log raises any alert

It should accept 4 parameters:
- `token`: string 
- `logformat`: string
- `location`: string
- `event`: string

That information should be sent through a local socket (AF_UNIX) that will communicate with logtest after formatting it as the dictionary below:
```JSON
{
    "token": "kTy234Sdvtp7",  
    "event": "Jun 24 11:54:19 eva systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.",  
    "log_format": "syslog",  
    "location": "user->/var/log/syslog"  
}
```

The return of the function should be the response of the socket, which will be a JSON too.

## 2. Delete a saved session 

It should accept 1 parameter:
- `token`: string

The token will be sent to the socket that communicates with `logtest` as in the previous point, but the content of the message has yet to be determined. Logtest (in core) will search if that token exists and if so, will delete the information related to it.

The response of the function should be the one provided by the socket or it may require some kind of treatment not yet established.

Best regards,
Selu.

**Comment by vicferpoy** [comment]
# Status update
The `logtest` log processing has just been implemented. These are some response example we can expect from it:
## Send a message without a token. Receive a new token for your session
```bash
>> echo '{"event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}' | nc -U /var/ossec/queue/ossec/logtest 


{
    "token": "bd83b45f",
    "messages": ["INFO: (7202): Session initialized with token 'bd83b45f'"],
    "output": {
        "timestamp": "2020-08-27T08:36:54.740+0000",
        "rule": {
            "description": "Systemd rules",
            "id": "40700",
            "firedtimes": 1,
            "mail": false,
            "groups": ["local", "systemd"]
        },
        "agent": {
            "id": "000",
            "name": "wazuh-master"
        },
        "manager": {
            "name": "wazuh-master"
        },
        "id": "1598517414.1892559",
        "cluster": {
            "name": "wazuh",
            "node": "master-node"
        },
        "full_log": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.",
        "predecoder": {
            "program_name": "systemd",
            "timestamp": "Jun 24 11:54:19",
            "hostname": "Master"
        },
        "decoder": {
            "name": "systemd"
        },
        "location": "master->/var/log/syslog"
    },
    "alert": false,
    "codemsg": 0
}
```

## Send a message with a valid token. Receive the same token as the session is still active
```bash
>> echo '{"token": "bd83b45f","event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}' | nc -U /var/ossec/queue/ossec/logtest         


{
    "token": "bd83b45f",
    "output": {
        "timestamp": "2020-08-27T08:39:02.471+0000",
        "rule": {
            "description": "Systemd rules",
            "id": "40700",
            "firedtimes": 2,
            "mail": false,
            "groups": ["local", "systemd"]
        },
        "agent": {
            "id": "000",
            "name": "wazuh-master"
        },
        "manager": {
            "name": "wazuh-master"
        },
        "id": "1598517542.1892559",
        "cluster": {
            "name": "wazuh",
            "node": "master-node"
        },
        "full_log": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.",
        "predecoder": {
            "program_name": "systemd",
            "timestamp": "Jun 24 11:54:19",
            "hostname": "Master"
        },
        "decoder": {
            "name": "systemd"
        },
        "location": "master->/var/log/syslog"
    },
    "alert": false,
    "codemsg": 0
}
```

## Send an invalid message
```bash
>> echo '{"token": "4885bbf4","log_format": "syslog","location": "master->/var/log/syslog"}' | nc -U /var/ossec/queue/ossec/logtest 

{
    "messages": ["ERROR: (7313): 'event' JSON field not found or is empty"],
    "codemsg": -2
}
```

**Comment by vicferpoy** [comment]
# Status update
Framework modules have been implemented. These are some examples after passing a `dict` object to the `logtest` framework function:

```bash
>>root@wazuh-master:/# /var/ossec/framework/python/bin/python3 test_logtest.py '{"token": "4885bbf4","log_format": "syslog","location": "master->/var/log/syslog"}'

{'messages': ["ERROR: (7313): 'event' JSON field not found or is empty"], 'codemsg': -2}
```

```bash
>>root@wazuh-master:/# /var/ossec/framework/python/bin/python3 test_logtest.py '{"token": "4885bbf4","event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.","log_format": "syslog","location": "master->/var/log/syslog"}'


{'token': 'f17747ec', 'messages': ["WARNING: (7003): '4885bbf4' token expires.", "INFO: (7202): Session initialized with token 'f17747ec'"], 'output': {'timestamp': '2020-08-27T10:33:21.437+0000', 'rule': {'description': 'Systemd rules', 'id': '40700', 'firedtimes': 1, 'mail': False, 'groups': ['local', 'systemd']}, 'agent': {'id': '000', 'name': 'wazuh-master'}, 'manager': {'name': 'wazuh-master'}, 'id': '1598524401.1893819', 'cluster': {'name': 'wazuh', 'node': 'master-node'}, 'full_log': 'Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.', 'predecoder': {'program_name': 'systemd', 'timestamp': 'Jun 24 11:54:19', 'hostname': 'Master'}, 'decoder': {'name': 'systemd'}, 'location': 'master->/var/log/syslog'}, 'alert': False, 'codemsg': 1}
```

```bash
>>root@wazuh-master:/# /var/ossec/framework/python/bin/python3 test_logtest.py '{"invalid":"invalid"}'

Traceback (most recent call last):
  File "test_logtest.py", line 9, in <module>
    response = get_logtest_output(**logdict)    
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/logtest.py", line 13, in get_logtest_output
    raise WazuhError(7000)
wazuh.core.exception.WazuhError: Error 7000 - Invalid body

```

Pending:
- Add docstrings.
- Add RBAC decorator.
- Add new action/resources for `logtest`.
- Add unit tests.

**Comment by vicferpoy** [comment]
# Status update
New function to end the given token `logtest` session has been implemented. It must receive a `token`. These functions have been tested on their respective development branches:
- https://github.com/wazuh/wazuh/pull/5857
- https://github.com/wazuh/wazuh/pull/5838

**Comment by vicferpoy** [comment]
# Status update
The new communication protocol has been added to the `logtest` socket. We need to adapt the framework functions to send and expect this structure: https://github.com/wazuh/wazuh/issues/5337#issuecomment-700007188

Changes should be minimal.

**Comment by vicferpoy** [comment]
# Status update

Development is finished and the logtest modules have been adapted to the new request/response structure. The two main logtest functions from the framework are `run_logtest` and `end_logtest_session`. Here is a real example using these two.

### Variables
```python
from wazuh.logtest import run_logtest, end_logtest_session

valid_logtest_params = {
    'event': 'Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.',
    'log_format': 'syslog',
    'location': 'master->/var/log/syslog'
}

invalid_logtest_params = {
    'log_format': 'syslog',
    'location': 'master->/var/log/syslog'
}
```

### Logtest response using valid parameters
```python
result = run_logtest(**valid_logtest_params)
print(result)
```

```python
{
    'error': 0,
    'data': {
        'token': 'a88635d7',
        'messages': ["WARNING: (7309): 'null' is not a valid token", "INFO: (7202): Session initialized with token 'a88635d7'"],
        'output': {
            'timestamp': '2020-10-14T12:33:31.555+0000',
            'rule': {
                'description': 'Systemd rules',
                'id': '40700',
                'firedtimes': 1,
                'mail': False,
                'groups': ['local', 'systemd'],
                'level': 0
            },
            'agent': {
                'id': '000',
                'name': 'wazuh-master'
            },
            'manager': {
                'name': 'wazuh-master'
            },
            'id': '1602678811.324985',
            'cluster': {
                'name': 'wazuh',
                'node': 'master-node'
            },
            'full_log': 'Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.',
            'predecoder': {
                'program_name': 'systemd',
                'timestamp': 'Jun 24 11:54:19',
                'hostname': 'Master'
            },
            'decoder': {
                'name': 'systemd'
            },
            'location': 'master->/var/log/syslog'
        },
        'alert': False,
        'codemsg': 1
    }
}
```

We save the session token:
```python
token = result['data']['token']
```

### Logtest response using invalid parameters
```python
try:
    result = run_logtest(**invalid_logtest_params)
except WazuhError as e:
    print(e)
```

```python
Error 7000 - Error trying to get logtest response: (7317): 'event' JSON field value is not valid
```

### Response after trying to end an active logtest session
Using the valid token from the valid response above.

```python
result = end_logtest_session(token=token)
print(result)
```

```python
{
    'error': 0,
    'data': {
        'messages': ["INFO: (7206): The session 'a88635d7' was closed successfully"],
        'codemsg': 0
    }
}
```

### Response after trying to end a non existent logtest session
Using the same token, but that session has been already ended.

```python
result = end_logtest_session(token=token)
print(result)
```

```python
{
    'error': 0,
    'data': {
        'messages': ["ERROR: (7004): No session found for token 'a88635d7'"],
        'codemsg': -1
    }
}
```

Regards,
Víctor.
