### ISSUE TITLE
wazuh-clusterd using  high amounts of CPU

### ISSUE THREAD

**Issue by evilpete** [wazuh/wazuh#601]
After upgrading from 3.2.1-1 to 3.2.2.-1  wazuh-clusterd seems to start consuming a majority of the CPS

```
% ps uaxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ossec    18126 48.7  2.3 112864 49056 ?        R    05:01   3:02 python /var/ossec/bin/wazuh-clusterd
ossec    18146 24.7  0.8 160028 17864 ?        Sl   05:01   1:32   \_ python /var/ossec/bin/wazuh-clusterd
ossec    18154  0.0  2.2 111924 46464 ?        S    05:01   0:00  \_ python /var/ossec/bin/wazuh-clusterd
```
This happened  on all 12 cluster nodes, after revalidating configs / resetting / rebooting the problem cleared itself with the exception of one cluster that had a server down.   

While I'm still investigating the source of the problem, I suspect it is triggered  when a sibling node in a cluster is unreachable causing  a continuous sync loop

**Comment by mgmacias95** [comment]
Hello @evilpete,

We are aware of this bug. It has been solved in branch 3.2 and there will be a release solving it very soon.

You can update your cluster to 3.2 but this update requires a little change in your cluster configuration. **All client nodes must be removed from the `<nodes>` section**.

Best regards,
Marta

**Comment by evilpete** [comment]
The process child process that is using all the CPU is the multiprocessing Manager() object

**Comment by evilpete** [comment]
thanks...  I'll can stop debugging now  :-)

**Comment by evilpete** [comment]
So in 3.2.2.-1  all client node should only list the master node ,
I assume this include the master as well?

**Comment by mgmacias95** [comment]
Hello @evilpete,

It's not necessary since the master doesn't use the `<nodes>` option.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello @evilpete,

Could you update successfully? Did this work for you?

Best regards,
Marta

**Comment by evilpete** [comment]
Sadly no.

after upgrading to package version 3.2.2-1
updating ossec.conf:
    added `<queue_size>16384</queue_size>` to `<remote>` block
    deleted all '<node>' entries  leaving only the Masters 
    restarted nodes and master with the command `ossec-control restart`

sadly the problem still persisted

**Comment by evilpete** [comment]
@mgmacias95 
 Ok, I got it working by doing a new build on a fresh system.

I spotted a few "minor" bugs in with master configurations,  you mentioned that : 

> master doesn't use the <nodes> option.

I noticed this is incorrect.

---------
Problem # 2

If  `<node>` is left  blank in the master ossec.conf  : 

```
    <nodes>
         <node></node>
    </nodes>
```

while the server _appears_ to be running with no errors reported or logged but clusterd fails silently and dies/exits

Also : 

 the command  `cluster_control -l` generated an error:

```
# /var/ossec/bin/cluster_control -l
Traceback (most recent call last):
  File "/var/ossec/bin/cluster_control", line 321, in <module>
    check_cluster_config(cluster_config)
  File "/var/ossec/bin/../framework/wazuh/cluster/cluster.py", line 64, in check_cluster_config
    if len(config['nodes']) == 0:
KeyError: 'nodes'
```

---------
Problem # 2

the master ossec.conf  If  `<node>` is has a IP address that is **not** the master's 


```
    <nodes>
         <node>1.2.3.4</node>
    </nodes>
```

The command cluster_control -l will report the incorrect address  when run on **both** master and client servers :

```
# /var/ossec/bin/cluster_control -l
------------------------------------------------------
Name                   Address         Type    Version
------------------------------------------------------
wazuh-use2-156         10.254.255.156  client  3.2.3
wazuh-use2-182         10.254.255.182  client  3.2.3
wazuh-use2-196         10.254.255.196  client  3.2.3
wazuh-use2-new-master  1.2.3.4         master  3.2.3
------------------------------------------------------
```

**Comment by jesuslinares** [comment]
Hi @evilpete,

Conceptually, it wouldn't be necessary the _nodes_ section in a master node since the client nodes are the ones that connect with the master. The master is just listening. That said, we will include the support for several masters soon, so the list of master nodes will be required in every node, regardless the type.

So, you must include the <nodes> section in every manager with only one entry: the master node.

Regarding the Problem # 2, you are right, we are not validating the IP in the master node. We will fix it.

Thanks for the feedback!.

Regards,
Jesus.

**Comment by mgmacias95** [comment]
Hello @evilpete,

We have officially released Wazuh v3.2.3 which solves this problem and many others the cluster had. Check our docs to update: https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html#upgrading-from-older-versions

Best regards,
Marta

**Comment by evilpete** [comment]
Thanks,  I will do a test deploy this morning..

**Comment by evilpete** [comment]
@mgmacias95 
I deployed 2 clusters across 5 AWS regions each & so far no problems

**Comment by mgmacias95** [comment]
Hello @evilpete,

I love to hear that 😄 🎉  !!! Let me close this issue if your problem is already solved. Don't hesitate to open a new one if you need it.

Best regards,
Marta

**Comment by evilpete** [comment]
@mgmacias95 :

I recently started getting the following errors:
is this related to the previous SSLlib python bug ?

client:cluster.log:

```
2018-07-13 20:58:49,429 INFO    : [Client] [Integrity-S  ]: Start.
2018-07-13 20:58:49,429 INFO    : [Client] [Integrity-S  ]: Asking permission to sync.
2018-07-13 20:58:49,480 INFO    : [Client] [Integrity-S  ]: Permission granted.
2018-07-13 20:58:54,484 INFO    : [Client] [Integrity-S  ]: Reason: 'Interval'
2018-07-13 20:58:54,484 INFO    : [Client] [Integrity-S  ]: Master found: 10.254.255.170.
2018-07-13 20:58:54,484 INFO    : [Client] [Integrity-S  ]: Gathering files.
2018-07-13 20:58:54,486 INFO    : [Client] [Integrity-S  ]: Gathered files: 10.
2018-07-13 20:58:54,487 INFO    : [Client] [Integrity-S  ]: Sending files to master.
2018-07-13 20:58:54,795 INFO    : [Client] [Integrity-S  ]: Sync accepted by the master.
2018-07-13 20:58:54,795 INFO    : [Client] [Integrity-S  ]: Result: Successfully.
2018-07-13 20:58:54,795 INFO    : [Client] [Integrity-S  ]: Locking: Waiting for receiving Master response and process the integrity if necessary.
2018-07-13 20:58:54,895 INFO    : [Client] [Integrity    ]: The master was not able to verify the integrity.
2018-07-13 20:58:54,896 INFO    : [Client] [Integrity-S  ]: Unlocking: Master sent the response and the integrity was processed if necessary.
2018-07-13 20:58:54,896 INFO    : [Client] [Integrity-S  ]: End. Sleeping: 19s.
```


Master:cluster.log:
```
2018-07-13 20:56:45,163 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Reception completed: Time: 0.24s.
2018-07-13 20:56:45,163 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Analyzing client integrity: Start.
2018-07-13 20:56:45,163 ERROR   : [Master] [wazuh-usw2-041] [Integrity-R  ]: Error decompressing data: the JSON object must be str, not 'bytes'
2018-07-13 20:56:45,163 ERROR   : [Master] [wazuh-usw2-041] [Integrity-R  ]: Result: Unknown error: the JSON object must be str, not 'bytes'.
2018-07-13 20:56:45,164 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Sending Sync-Error to client.
2018-07-13 20:56:45,234 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Sync accepted by the client.
2018-07-13 20:56:45,234 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Unlocking 'sync_integrity_free' due to error.
2018-07-13 20:56:45,334 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: End.
```
