### ISSUE TITLE
Framework accepted characters

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#631]
Hello team, currently the framework is crashing with some special characters such French characters (è). This issue is related to https://github.com/wazuh/wazuh-api/issues/80 cause we can have a rule searchable by a standard string, but the rule file contains `è` which causes break the result.

Example:

1. You have a rule using some French characters
2. `curl api:55000/rules?search=sql`  breaks

Regards,
Jesús

**Comment by jesusgn90** [comment]
FYI

```js
{
"error":1000,
"message":"Wazuh-Python Internal Error: 'ascii' codec can't encode character u'\xe0' in position 6: ordinal not in range(128)"
}
```

**Comment by mgmacias95** [comment]
Hello @jesusgn90,

This is the traceback of the error you're showing:
```
Traceback (most recent call last):
  File "/var/ossec/api/models/wazuh-api.py", line 268, in <module>
    data = functions[request['function']](**request['arguments'])
  File "/var/ossec/framework/wazuh/decoder.py", line 194, in get_decoders
    decoders = search_array(decoders, search['value'], search['negation'])
  File "/var/ossec/framework/wazuh/utils.py", line 195, in search_array
    values = get_values(o=item, fields=fields)
  File "/var/ossec/framework/wazuh/utils.py", line 173, in get_values
    strings.extend(get_values(obj[key]))
  File "/var/ossec/framework/wazuh/utils.py", line 173, in get_values
    strings.extend(get_values(obj[key]))
  File "/var/ossec/framework/wazuh/utils.py", line 175, in get_values
    strings.append(str(obj).lower())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 17: ordinal not in range(128)
```

The line that's failing is `str(obj).lower()`. If you try to do this in both python2 and python3 you will get the following results:

```python
Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> str('È').lower()
'\xc3\x88'
```
```python
Python 3.6.5 (default, Apr 10 2018, 17:08:37)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> str('È').lower()
'è'
```

The conclusion here is that we must always work using unicode in python2, not str, as explained [here](https://docs.python.org/2/howto/unicode.html#tips-for-writing-unicode-aware-programs).

Best regards,
Marta
