### ISSUE TITLE
[API] Chown fail when upgrading using API

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#6357]
Hello team,

We should investigate a possible race condition when upgrading agents to 4.0.0:

```
2020/10/20 20:42:03 ERROR: Error executing API request locally: [Errno 1] Operation not permitted: '/var/ossec/var/upgrade/wazuh_agent_v4.0.0_windows.wpk'
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 231, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/var/ossec/framework/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 205, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/rbac/decorators.py", line 417, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/agent.py", line 695, in upgrade_agents
    return Agent(agent_id).upgrade(wpk_repo=wpk_repo, version=version, force=True if int(force) == 1 else False,
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/core/agent.py", line 1381, in upgrade
    sending_result = self._send_wpk_file(wpk_repo=wpk_repo, debug=debug, version=version, force=force,
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/core/agent.py", line 1233, in _send_wpk_file
    _get_wpk = self._get_wpk_file(wpk_repo=wpk_repo, debug=debug, version=version, force=force, use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.0-py3.8.egg/wazuh/core/agent.py", line 1207, in _get_wpk_file
    chown(wpk_file_path, common.ossec_gid(), common.ossec_gid())
PermissionError: [Errno 1] Operation not permitted: '/var/ossec/var/upgrade/wazuh_agent_v4.0.0_windows.wpk'
```

The fail was reported when upgrading from 3.13.2 to 4.0.0 in a Windows 2012 agent. The second try succeeded.

**Comment by AdriiiPRodri** [comment]
## Status update

After investigating this issue, we have concluded that the reason for this error is that there is already a file in the `/var/ossec/var/upgrade` folder with the same name as the new package and that it was downloaded by a different user than the ossec user.

For example, in our tests we downloaded the version 4.0.0 of the linux agent by the root user and moved it to that folder. When the framework tried to download a new package, it was unable to save the result of the download because the downloaded package as root had the following permissions:

```
-rw-r--r-- 1 root root  7914203 Oct 13 08:18 wazuh_agent_v4.0.0_linux_x86_64.wpk
```

In addition, we have modified the way in which we change the permissions of the file generated in an installation. Now the permissions of the new file are set once the file is closed.

Finally, in case of detecting a file already downloaded, its checksum is checked, in case it is different from the one of the downloaded agent package, such file will be deleted because it is possible that it has been tampered or not properly downloaded. In case it cannot be deleted due to lack of permissions, a new file with the current date will be generated and this will be the one installed.

```
root@wazuh-master:/# ls -la /var/ossec/var/upgrade/
total 7744
drwxrwx--- 1 root ossec    4096 Oct 21 12:25 .
drwxr-x--- 1 root ossec    4096 Oct 21 12:21 ..
-rw------- 1 root root  7914203 Oct 13 08:18 wazuh_agent_v4.0.0_linux_x86_64.wpk
-rw-r--r-- 1 root root  7914203 Oct 21 12:25 wazuh_agent_v4.0.0_linux_x86_641603275884.wpk
```

Regards
