### ISSUE TITLE
Error in GET /cluster/{node_id}/stats/analysisd

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#6573]
|Wazuh version|Component|Install type|
|---|---|---|
| master (4.1) | API | Manager | 

## Description

Hello team!

The following error log can be found inside ossec.log when running the endpoint `GET /cluster/{node_id}/stats/analysisd`:
```
2020/11/12 08:38:29 ERROR: Error executing API request locally: While reading from '<???>' [line 101]: option 'dbsync_queue_usage' in section 'root' already exists
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 234, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 208, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/rbac/decorators.py", line 417, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/stats.py", line 180, in get_daemons_stats
    config.read_file(fp)
  File "/var/ossec/framework/python/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/var/ossec/framework/python/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '<???>' [line 101]: option 'dbsync_queue_usage' in section 'root' already exists
2020/11/12 08:38:29 INFO: wazuh 172.23.0.1 "GET /cluster/master-node/stats/analysisd" done in 75.0000000007276ms: 500
```

As a consequence, there are 3 tests inside `test_cluster_endpoints.tavern.yaml` failing. It is necessary to investigate and fix the source of the error.

Regards,
Selu.

**Comment by Selutario** [comment]
Last results of `test_cluster_endpoints.tavern.yaml` in the master branch:

```
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.5', 'Platform': 'Linux-5.4.0-53-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.8.2', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.10.0', 'testinfra': '5.0.0', 'tavern': '1.2.2', 'cov': '2.10.0', 'asyncio': '0.14.0', 'html': '2.0.1'}}
rootdir: /home/selu/Git/wazuh/api/test/integration, inifile: pytest.ini
plugins: metadata-1.10.0, testinfra-5.0.0, tavern-1.2.2, cov-2.10.0, asyncio-0.14.0, html-2.0.1
collecting ... collected 56 items

test_cluster_endpoints.tavern.yaml::GET /cluster/local/config PASSED     [  1%]
test_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED      [  3%]
test_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED       [  5%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED            [  7%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[master-node] PASSED [  8%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker1] PASSED   [ 10%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker2] PASSED   [ 12%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[ip] PASSED [ 14%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[name] PASSED [ 16%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[type] PASSED [ 17%]
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[version] PASSED [ 19%]
test_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED           [ 21%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED [ 23%]
test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation PASSED [ 25%]
test_cluster_endpoints.tavern.yaml::GET /cluster/api/config PASSED       [ 26%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/api/config PASSED       [ 28%]
test_cluster_endpoints.tavern.yaml::DELETE /cluster/api/config PASSED    [ 30%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED [ 32%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files[master-node] PASSED [ 33%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files[worker1] PASSED [ 35%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/files[worker2] PASSED [ 37%]
test_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files[master-node] PASSED [ 39%]
test_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files[worker1] PASSED [ 41%]
test_cluster_endpoints.tavern.yaml::DELETE /cluster/{node_id}/files[worker2] PASSED [ 42%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files[master-node] PASSED [ 44%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files[worker1] PASSED [ 46%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/files[worker2] PASSED [ 48%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/wrong_node/files PASSED [ 50%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[master-node] PASSED [ 51%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker1] PASSED [ 53%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker2] PASSED [ 55%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[master-node] PASSED [ 57%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker1] PASSED [ 58%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker2] PASSED [ 60%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker1] PASSED [ 62%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker2] PASSED [ 64%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[master-node] PASSED [ 66%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker1] PASSED [ 67%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker2] PASSED [ 69%]
test_cluster_endpoints.tavern.yaml::GET /cluster/wrong_node/stats PASSED [ 71%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[master-node] PASSED [ 73%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker1] PASSED [ 75%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker2] PASSED [ 76%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[master-node] PASSED [ 78%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker1] PASSED [ 80%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker2] PASSED [ 82%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[master-node] PASSED [ 83%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker1] PASSED [ 85%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker2] PASSED [ 87%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[master-node] PASSED [ 89%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker1] PASSED [ 91%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker2] PASSED [ 92%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[master-node] PASSED [ 94%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker1] PASSED [ 96%]
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker2] PASSED [ 98%]
test_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED          [100%]

================= 56 passed, 72 warnings in 666.70s (0:11:06) ==================
```

Regards,
Selu.
