### ISSUE TITLE
Investigate and fix API error with GET /syscheck endpoint for Windows registries

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7117]
|Wazuh version|Component|
|---|---|
| 4.0.3 | API |

Hello team,

We should investigate and propose a solution for the error with `GET /syscheck API` call reported in https://github.com/wazuh/wazuh-kibana-app/issues/2736.

Pending tasks:
- [x] Analyze and debug error, replicate
- [x] Investigate and determine why the use case is not covered and detected by the unit tests
- [x] Investigate the behaviour for v3.13.2 to understand if the bug was introduced in v4.0.0 and is a regression
- [x] Investigate the behaviour for v4.1.0 as there have been multiple changes in database and API call https://github.com/wazuh/wazuh/issues/6398
- [x] Propose and develop a solution for the bug, for all API versions where it is confirmed to exist

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
###  **Analyze and debug error, replicate (v4.0.3):**

API petition:
`curl -u wazuh:wazuh -k -X GET "https://127.0.0.1:55000/syscheck/006?file=%5Bx32%5D+HKEY_LOCAL_MACHINE%5CSystem%5CCurrentControlSet%5CServices%5CWinDefend" -H "Authorization: Bearer $TOKEN"`

Error debug:
```
2021/01/08 08:27:35 ERROR: Error executing API request locally: bad escape \S at position 25
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\S'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.3-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 234, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.3-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 208, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.3-py3.8.egg/wazuh/rbac/decorators.py", line 417, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.3-py3.8.egg/wazuh/syscheck.py", line 167, in files
    db_query = WazuhDBQuerySyscheck(agent_id=agent_list[0], offset=offset, limit=limit, sort=sort, search=search,
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.3-py3.8.egg/wazuh/core/utils.py", line 1297, in run
    return self.general_run() if len(str(rbac_ids)) < common.MAX_QUERY_FILTERS_RESERVED_SIZE else \
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.3-py3.8.egg/wazuh/core/utils.py", line 1230, in general_run
    self._get_total_items()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.3-py3.8.egg/wazuh/core/utils.py", line 1193, in _get_total_items
    self.total_items = self.backend.execute(self._default_count_query().format(query_with_select_fields),
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.3-py3.8.egg/wazuh/core/utils.py", line 928, in execute
    query = self._substitute_params(query, request)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.3-py3.8.egg/wazuh/core/utils.py", line 914, in _substitute_params
    query = re.sub(r':\b' + re.escape(str(k)) + r'\b', value, query)
  File "/var/ossec/framework/python/lib/python3.8/re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/var/ossec/framework/python/lib/python3.8/re.py", line 325, in _subx
    template = _compile_repl(template, pattern)
  File "/var/ossec/framework/python/lib/python3.8/re.py", line 316, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/var/ossec/framework/python/lib/python3.8/sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \S at position 25
```

It occurs even with proper URL encoding, further investigation and debugging required.

**Comment by CarlosRS9** [comment]
We have deployed a 3.13.2 environment to check if this issue is present and we can confirm it is not.

**Procedure**

1. Add several windows registry entries on the fim_entry table, like the following one:
```
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\W32Time\SecureTimeLimits\RunTime
```

2. Check if the API returns that entry using the following CURL command:
```
curl -u foo:bar -k -G --data-urlencode "file=x32HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\W32Time\SecureTimeLimits\RunTime" -X GET "https://127.0.0.1:55000/syscheck/001"
```

3. The output of the command confirm us that everything runs as expected:
```
{
    "error": 0,
    "data": {
        "items": [{
            "sha1": "ee2f046b346a88f7d9033faec17c7fa3ad32d33e",
            "type": "registry",
            "size": "",
            "uname": "",
            "gname": "",
            "uid": "",
            "file": "x32HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\W32Time\\SecureTimeLimits\\RunTime",
            "gid": "",
            "sha256": "",
            "date": "2021-01-08 02:17:06",
            "mtime": "2021-01-08 02:12:32",
            "inode": "",
            "md5": "",
            "perm": ""
        }],
        "totalItems": 1
    }
}
```

**Comment by davidjiglesias** [comment]
### **Status update:**
Since python 3.7 https://github.com/python/cpython/commit/9bd85b83f66d31e39282244e455275bd9cd91bb1#diff-a0fc71db3d118bcf5fa27a2eb5d4e9c5:
`Unknown escapes consisting of ``'\'`` and ASCII letter in    regular expressions now are errors.`

During the investigation, we have found the same issue in several places:
```
https://github.com/logpai/logparser/issues/50#issuecomment-541041133
https://github.com/emmett-framework/emmett/issues/227#issue-358491835
https://stackoverflow.com/questions/58328587/python-3-7-4-re-error-bad-escape-s-at-position-0
https://lwn.net/Articles/795546/
```

The error occurs here: https://github.com/wazuh/wazuh/blob/4.0/framework/wazuh/core/utils.py#L914
It happens when we try to replace the paremeters in the query to be sent to wazuh-db.

From re source code:
`This code looks for what's behind a literal \ and tries to replace it by the proper non-ascii character. Obviously S is not in ESCAPES dictionary so the KeyError exception is triggered, then the message you're getting.`

There are 2 possible different solutions:

**1:** Use `\\ `in the API petitions (and proper URL encoding, as always) :
```
root@wazuh-master:/# curl -u wazuh:wazuh -k -X GET "https://127.0.0.1:55000/syscheck/000?pretty=true&file=%5Bx32%5D%20HKEY_LOCAL_MACHINE%5C%5CSystem%5C%5CCurrentControlSet%5C%5CServices%5C%5CW32Time%5C%5CSecureTimeLimits%5C%5CRunTime" -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "sha1": "ee2f046b346a88f7d9033faec17c7fa3ad32d33e",
            "mtime": "2021-01-08T02:12:32Z",
            "changes": 1,
            "date": "2021-01-08T02:17:06Z",
            "file": "[x32] HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\W32Time\\SecureTimeLimits\\RunTime",
            "type": "registry"
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "FIM findings of the agent were returned",
   "error": 0
}
```

**2:** Replace re with regex for its usage here, its the approach in the links above:
``
root@wazuh-master:/# /var/ossec/framework/python/bin/python3
Python 3.8.2 (default, Jan  8 2021, 10:58:49) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import re
>>> query="SELECT COUNT(*) FROM (SELECT gname as 'gname',gid as 'gid',uid as 'uid',md5 as 'md5',attributes as 'attributes',perm as 'perm',sha1 as 'sha1',mtime as 'mtime',sha256 as 'sha256',date as 'date',uname as 'uname',size as 'size',file as 'file',type as 'type',inode as 'inode',changes as 'changes' FROM fim_entry WHERE (file = :file$0 COLLATE NOCASE)  )"
>>> value='\'[x32] HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\W32Time\\SecureTimeLimits\\RunTime\'' 
>>> re.sub(r':\b' + re.escape(str(k)) + r'\b', value, query)
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\S'
>>> import regex as re
>>> re.sub(r':\b' + re.escape(str(k)) + r'\b', value, query)
"SELECT COUNT(*) FROM (SELECT gname as 'gname',gid as 'gid',uid as 'uid',md5 as 'md5',attributes as 'attributes',perm as 'perm',sha1 as 'sha1',mtime as 'mtime',sha256 as 'sha256',date as 'date',uname as 'uname',size as 'size',file as 'file',type as 'type',inode as 'inode',changes as 'changes' FROM fim_entry WHERE (file = '[x32] HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\W32Time\\SecureTimeLimits\\RunTime' COLLATE NOCASE)  )"
```

**Comment by vicferpoy** [comment]
## Status update

| **Fix branch** |
|-|
| [fix-api-syscheck-windows-registries](https://github.com/wazuh/wazuh/tree/fix-api-syscheck-windows-registries) | 

Hello team!

As a temporal fix while we find the best approach, we will use the [regex module](https://pypi.org/project/regex/2020.11.13/) which has an improved `.escape()` method, accepting paths like the following:

`x32HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\W32Time\SecureTimeLimits\RunTime`

This simple fix can be found here:
https://github.com/wazuh/wazuh/blob/7e22490f52e92040fd0c1c53fd373f2349b57eaf/framework/wazuh/core/utils.py#L10

In addition to this, we need to add the `regex` module to the Wazuh embedded python. To do so:
```
/var/ossec/framework/python/bin/pip3 install regex==2020.11.13
```

### Example
#### API request

```
root@wazuh-master:/# curl -k -X GET "https://127.0.0.1:55000/syscheck/006?file=HKEY_LOCAL_MACHINE%5CSystem%5CCurrentControlSet%5CServices%5CW32Time%5CSecureTimeLimits%5CRunTime" -H "Authorization: Bearer $TOKEN"
```


#### Response

```json
{
  "data": {
    "affected_items": [
      {
        "gid": "0",
        "size": 20599,
        "type": "registry",
        "date": "2020-01-10T07:18:38Z",
        "inode": 16393722,
        "md5": "40141b833e183a0ea826ed500e25b8f1",
        "attributes": "0",
        "sha256": "760885b6142d0c6e52df29cffa9026d1cfbc928b9d123979951e3ba547b5937c",
        "gname": "root",
        "perm": "100755",
        "uid": "0",
        "changes": 1,
        "mtime": "2019-05-21T20:12:23Z",
        "file": "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\W32Time\\SecureTimeLimits\\RunTime",
        "sha1": "65792d780476ca9033c230937017532cfd1a4461",
        "uname": "root"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "FIM findings of the agent were returned",
  "error": 0
}
```

### Tests performed
#### Unit tests
```
wazuh/core/cluster/dapi/tests/test_dapi.py
	22 passed, 11 warnings
wazuh/core/cluster/tests/test_cluster.py
	19 passed
wazuh/core/cluster/tests/test_common.py
	7 passed
wazuh/core/cluster/tests/test_control.py
	5 passed
wazuh/core/cluster/tests/test_local_client.py
	1 passed
wazuh/core/cluster/tests/test_utils.py
	7 passed
wazuh/core/cluster/tests/test_worker.py
	16 passed, 2 warnings
wazuh/core/tests/test_active_response.py
	12 passed
wazuh/core/tests/test_agent.py
	187 passed, 11 warnings
wazuh/core/tests/test_cdb_list.py
	33 passed
wazuh/core/tests/test_common.py
	7 passed
wazuh/core/tests/test_configuration.py
	34 passed
wazuh/core/tests/test_decoder.py
	15 passed
wazuh/core/tests/test_input_validator.py
	3 passed
wazuh/core/tests/test_manager.py
	30 passed
wazuh/core/tests/test_ossec_queue.py
	19 passed
wazuh/core/tests/test_pyDaemonModule.py
	6 passed
wazuh/core/tests/test_results.py
	40 passed
wazuh/core/tests/test_rule.py
	21 passed
wazuh/core/tests/test_syscollector.py
	3 passed
wazuh/core/tests/test_utils.py
	204 passed
wazuh/core/tests/test_wazuh_socket.py
	15 passed
wazuh/core/tests/test_wdb.py
	21 passed
wazuh/rbac/tests/test_auth_context.py
	2 passed, 1 warning
wazuh/rbac/tests/test_decorators.py
	105 passed
wazuh/rbac/tests/test_default_configuration.py
	47 passed
wazuh/rbac/tests/test_orm.py
	53 passed
wazuh/rbac/tests/test_preprocessor.py
	11 passed
wazuh/tests/test_active_response.py
	9 passed
wazuh/tests/test_agent.py
	90 passed, 11 warnings
wazuh/tests/test_cdb_list.py
	47 passed
wazuh/tests/test_ciscat.py
	2 passed
wazuh/tests/test_cluster.py
	7 passed
wazuh/tests/test_decoders.py
	31 passed
wazuh/tests/test_group.py
	8 passed
wazuh/tests/test_manager.py
	38 passed
wazuh/tests/test_mitre.py
	180 passed
wazuh/tests/test_rule.py
	52 passed
wazuh/tests/test_sca.py
	7 passed
wazuh/tests/test_security.py
	69 passed, 12 warnings
wazuh/tests/test_stats.py
	13 passed
wazuh/tests/test_syscheck.py
	18 passed
wazuh/tests/test_syscollector.py
	12 passed

```

I added a new one to test this use case:

```python
@pytest.mark.parametrize('agent_id, select, filters, distinct', [
    (['001'], None, None, None),
    (['001'], ['file', 'size', 'mtime'], None, False),
    (['001'], None, {'inode': '15470536'}, True),
    (['001'], ['file', 'size'], {'hash': '15470536'}, False),
    (['001'], None, {'date': '2019-05-21 12:10:20'}, True),
    (['001'], None, {'file': 'HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\W32Time\\SecureTimeLimits\\RunTime'}, True)
])
```

```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1 -- /home/vicferpoy/env/unittest-env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.5', 'Platform': 'Linux-5.8.0-36-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.8.2', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.10.0', 'asyncio': '0.12.0', 'cov': '2.10.1', 'html': '2.0.1'}}
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: metadata-1.10.0, asyncio-0.12.0, cov-2.10.1, html-2.0.1
collected 6 items                                                                                                                                                                           

tests/test_syscheck.py::test_syscheck_files[agent_id0-None-None-None] PASSED                                                                                                          [ 16%]
tests/test_syscheck.py::test_syscheck_files[agent_id1-select1-None-False] PASSED                                                                                                      [ 33%]
tests/test_syscheck.py::test_syscheck_files[agent_id2-None-filters2-True] PASSED                                                                                                      [ 50%]
tests/test_syscheck.py::test_syscheck_files[agent_id3-select3-filters3-False] PASSED                                                                                                  [ 66%]
tests/test_syscheck.py::test_syscheck_files[agent_id4-None-filters4-True] PASSED                                                                                                      [ 83%]
tests/test_syscheck.py::test_syscheck_files[agent_id5-None-filters5-True] PASSED                                                                                                      [100%]

===================================================================================== 6 passed in 0.11s =====================================================================================

```

#### Integration tests

These are the integration tests that could be affected with the change on the `re` module. To try this on local, I added the following line to the **base manager entrypoint**:

```
/var/ossec/framework/python/bin/pip3 install regex==2020.11.13

/var/ossec/bin/ossec-control restart
```

Results:

```
Collected tests [7]:
test_agents_GET_endpoints.tavern.yaml, test_decoders_endpoints.tavern.yaml, test_lists_endpoints.tavern.yaml, test_mitre_endpoints.tavern.yaml, test_overview_endpoints.tavern.yaml, test_syscheck_endpoints.tavern.yaml, test_syscollector_endpoints.tavern.yaml


test_agents_GET_endpoints.tavern.yaml 
	 90 passed, 97 warnings

test_decoders_endpoints.tavern.yaml 
	 23 passed, 29 warnings

test_lists_endpoints.tavern.yaml 
	 2 passed, 4 warnings

test_mitre_endpoints.tavern.yaml 
	 1 passed, 3 warnings

test_overview_endpoints.tavern.yaml 
	 1 passed, 3 warnings

test_syscheck_endpoints.tavern.yaml 
	 35 passed, 39 warnings

test_syscollector_endpoints.tavern.yaml 
	 161 passed, 176 warnings

```

Regards,
Víctor Fernández.
