### ISSUE TITLE
API error "Cluster is not running error" when clustering is disabled

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#7118]
|Wazuh version|Component|
|---|---|
| 4.1.0-rc2 | Wazuh API |

Hello team,

I have found a bug related to the API.

If a cluster's node is disconnected from it by disabling the cluster in the configuration, any API query will fail.

```shellsession
[root@centos rules]# curl -s -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true"
{"title": "Wazuh Internal Error", "detail": "Cluster is not running", "dapi_errors": {"worker": {"error": "Cluster is not running", "logfile": "WAZUH_HOME/logs/api.log"}}, "error": 3012}
```

`api.log`

```python
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 154, in distribute_function
    response = await self.execute_remote_request()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 366, in execute_remote_request
    node_response = await client.execute(command=b'dapi',
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/local_client.py", line 212, in execute
    await self.start()
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.0-py3.8.egg/wazuh/core/cluster/local_client.py", line 149, in start
    raise exception.WazuhInternalError(3012)
wazuh.core.exception.WazuhInternalError: Error 3012 - Cluster is not running
```

_`ossec.log`_ does not present any warning or error.

## Steps to replicate

1. Install an environment with 2 Wazuh manager CentOS 8 (v4.1.0-rc2 )
2. Set up a cluster
3. Start both Wazuh managers
4. Disable cluster mode in the worker node
5. Run any query in the disconnected worker

**Comment by mcarmona99** [comment]
Same problem reported in this issue: https://github.com/wazuh/wazuh/issues/7610
