### ISSUE TITLE
CIS-CAT not reading xccdf .xml

### ISSUE THREAD

**Issue by akhan23wgu** [wazuh/wazuh#7383]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.1-4008 | Wazuh component | Manager | Packages | CentOS Linux release 7.9.2009 (Core), CentOS release 6.6 (Final)|

After loading CIS-CAT, it doesn't seem like the system is able to read either xccdf.xml file for RHEL 7 or RHEL 6. Are these XML's not compatible? Both the CIS-CAT.sh and the XML's were loaded from `CIS-CAT Dissolvable Bundle, v3`.

RHEL 7:

2021/02/04 18:22:17 wazuh-modulesd:ciscat: INFO: Module started.
2021/02/04 18:22:17 wazuh-modulesd:ciscat: INFO: Starting evaluation.
2021/02/04 18:22:17 sca: INFO: Module started.
2021/02/04 18:22:17 wazuh-modulesd:control: INFO: Starting control thread.
2021/02/04 18:22:17 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_rhel7_linux.yml'
2021/02/04 18:22:17 sca: INFO: Starting Security Configuration Assessment scan.
2021/02/04 18:22:17 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_rhel7_linux.yml'
2021/02/04 18:22:17 wazuh-modulesd:ciscat: ERROR: Ignoring content '/var/ossec/wodles/ciscat/benchmarks/CIS_CentOS_Linux_7_Benchmark_v3.0.0-xccdf.xml' due to error (1).
2021/02/04 18:22:17 wazuh-modulesd:ciscat: ERROR: OUTPUT: Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/xml/security/Init
        at org.cisecurity.tools.ciscat.CISCAT.main(SourceFile)
Caused by: java.lang.ClassNotFoundException: org.apache.xml.security.Init
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 1 more

2021/02/04 18:22:17 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/ciscat/benchmarks/CIS_CentOS_Linux_7_Benchmark_v3.0.0-xccdf.xml'
2021/02/04 18:22:17 wazuh-modulesd:ciscat: INFO: Evaluation finished.
2021/02/04 18:22:18 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2021/02/04 18:22:20 ossec-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2021/02/04 18:22:22 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rhel7_linux.yml'
2021/02/04 18:22:22 sca: INFO: Security Configuration Assessment scan finished. Duration: 0 seconds.
2021/02/04 18:22:34 wazuh-modulesd:syscollector: INFO: Evaluation finished.

RHEL 6:

q
2021/02/04 18:18:25 wazuh-modulesd:ciscat: INFO: Module started.
2021/02/04 18:18:25 wazuh-modulesd:ciscat: INFO: Starting evaluation.
2021/02/04 18:18:25 sca: INFO: Module started.
2021/02/04 18:18:25 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_rhel6_linux.yml'
2021/02/04 18:18:25 sca: INFO: Starting Security Configuration Assessment scan.
2021/02/04 18:18:25 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_rhel6_linux.yml'
2021/02/04 18:18:26 wazuh-modulesd:ciscat: ERROR: Ignoring content '/var/ossec/wodles/ciscat/benchmarks/CIS_CentOS_Linux_6_Benchmark_v2.0.2-xccdf.xml' due to error (1).
2021/02/04 18:18:26 wazuh-modulesd:ciscat: ERROR: OUTPUT: Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/xml/security/Init
        at org.cisecurity.tools.ciscat.CISCAT.main(SourceFile)
Caused by: java.lang.ClassNotFoundException: org.apache.xml.security.Init
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 1 more

2021/02/04 18:18:26 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/ciscat/benchmarks/CIS_CentOS_Linux_6_Benchmark_v2.0.2-xccdf.xml'
2021/02/04 18:18:26 wazuh-modulesd:ciscat: INFO: Evaluation finished.
2021/02/04 18:18:26 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2021/02/04 18:18:33 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rhel6_linux.yml'
2021/02/04 18:18:33 sca: INFO: Security Configuration Assessment scan finished. Duration: 0 seconds.
2021/02/04 18:18:34 ossec-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2021/02/04 18:18:44 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2021/02/04 18:18:55 rootcheck: INFO: Ending rootcheck scan.

**Comment by akhan23wgu** [comment]
Related to #6681
