### ISSUE TITLE
Error when upgrading an Ubuntu agent remotely

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#770]
Trying to upgrade an agent remotely by the API and the `agent_upgrade` tool, we get the following error:

```
[root@manager logs]# curl -u foo:bar -X PUT -k "http://127.0.0.1:55000/agents/007/upgrade?pretty"
{
   "error": 1000,
   "message": "Wazuh-Python Internal Error: 'minor'"
}

[root@manager logs]# curl -u foo:bar -X GET -k "http://127.0.0.1:55000/agents/007/upgrade_result?pretty"
{
   "error": 1716,
   "message": "Error upgrading agent: Cannot read upgrade_result file."
}

[root@manager bin]# ./agent_upgrade -a 007 -d
Internal error: 'minor'
Traceback (most recent call last):
  File "./agent_upgrade", line 144, in <module>
    main()
  File "./agent_upgrade", line 99, in main
    upgrade_command_result = agent.upgrade(wpk_repo=args.repository, debug=args.debug, version=args.version, force=args.force, show_progress=print_progress if not args.silent else None, chunk_size=args.chunk_size, rl_timeout=-1 if args.timeout == None else args.timeout)
  File "./../framework/wazuh/agent.py", line 2177, in upgrade
    sending_result = self._send_wpk_file(wpk_repo, debug, version, force, show_progress, chunk_size, rl_timeout)
  File "./../framework/wazuh/agent.py", line 2038, in _send_wpk_file
    _get_wpk = self._get_wpk_file(wpk_repo, debug, version, force)
  File "./../framework/wazuh/agent.py", line 1934, in _get_wpk_file
    versions = self._get_versions(wpk_repo)
  File "./../framework/wazuh/agent.py", line 1900, in _get_versions
    versions_url = wpk_repo + self.os['platform'] + "/" + self.os['major'] + "." + self.os['minor'] + "/" + self.os['arch'] + "/versions"
KeyError: 'minor'
```

**Comment by jesuslinares** [comment]
The fields `'os.minor': 'os_minor'` is missing after this refactor: https://github.com/wazuh/wazuh/pull/743.
