### ISSUE TITLE
Modulesd crashes with segmentation fault

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#7935]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.2 | Vulnerability Detector | Worker manager | Packages | Amazon Linux 2 |

We've been reported that Modulesd has crashed multiple times with error 4 (page fault) in a worker node running on Amazon Linux 2.

|Address|Instruction pointer|Stack pointer|libc-2.26.so offset|
|---|---|---|---|
|0|00007fe5c79a80b1|00007fe5c3c39a68|7fe5c785d000+1a1000|
|0|00007fef622540b1|00007fef5e4e5a68|7fef62109000+1a1000|
|0|00007f75f6a320b1|00007f75f2cc3a68|7f75f68e7000+1a1000|
|0|00007fea9880d0b1|00007fea94a9ea68|7fea986c2000+1a1000|
|0|00007f229525d0b1|00007f228cff8a68|7f2295112000+1a1000|

**Comment by vikman90** [comment]
Assuming the installed version is `glibc-2.26-41`, these are the offending functions:

|IP|Offset|Function address|Function name|
|---|---|---|---|
|00007fe5c79a80b1|7fe5c785d000|0x14b0b1|`__nss_passwd_lookup`|
|00007fef622540b1|7fef62109000|0x14b0b1|`__nss_passwd_lookup`|
|00007f75f6a320b1|7f75f68e7000|0x14b0b1|`__nss_passwd_lookup`|
|00007fea9880d0b1|7fea986c2000|0x14b0b1|`__nss_passwd_lookup`|
|00007f229525d0b1|7f2295112000|0x14b0b1|`__nss_passwd_lookup`|

The symbol address is always `__nss_passwd_lookup`.

These are the surrounding symbols:

```
# nm -D -n /lib64/libc-2.26.so | sort | grep 0012 | tail -n2
# nm -D -n /lib64/libc-2.26.so | sort | grep 0015 | head -n2

0000000000126840 T __nss_group_lookup
0000000000126850 T __nss_passwd_lookup
0000000000156b20 T __libc_freeres
0000000000157270 T __libc_thread_freeres
```

**Comment by vikman90** [comment]
Today, I tried with `objdump`, which returned more accurate data:

```sh
# objdump -DCgl /lib64/libc-2.26.so | grep -a8 14b0b1
000000000014b0a0 <__strlen_avx2>:
__strlen_avx2():
  14b0a0:	89 f9                	mov    %edi,%ecx
  14b0a2:	48 89 fa             	mov    %rdi,%rdx
  14b0a5:	c5 f9 ef c0          	vpxor  %xmm0,%xmm0,%xmm0
  14b0a9:	83 e1 3f             	and    $0x3f,%ecx
  14b0ac:	83 f9 20             	cmp    $0x20,%ecx
  14b0af:	77 1f                	ja     14b0d0 <__strlen_avx2+0x30>
> 14b0b1:	c5 fd 74 0f          	vpcmpeqb (%rdi),%ymm0,%ymm1
  14b0b5:	c5 fd d7 c1          	vpmovmskb %ymm1,%eax
  14b0b9:	85 c0                	test   %eax,%eax
  14b0bb:	0f 85 df 00 00 00    	jne    14b1a0 <__strlen_avx2+0x100>
  14b0c1:	48 83 c7 20          	add    $0x20,%rdi
  14b0c5:	83 e1 1f             	and    $0x1f,%ecx
  14b0c8:	48 83 e7 e0          	and    $0xffffffffffffffe0,%rdi
  14b0cc:	eb 36                	jmp    14b104 <__strlen_avx2+0x64>
  14b0ce:	66 90                	xchg   %ax,%ax
```

## Action plan

- Review changelog and code differences between 4.0.4 and 4.1.2.
-  Look for calls to `strlen()` and check if any of them could send a null parameter.

**Comment by vikman90** [comment]
## Reproducing the issue

- Set up an agent running on macOS.
- Replace the agent database with a custom database file.
- Restart Wazuh DB.
- Restart Modulesd.

### GDB report

```
2021/03/24 09:13:00 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Microsoft Security Update' feed finished successfully.
2021/03/24 09:13:00 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
2021/03/24 09:13:00 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '001' vulnerabilities.

Thread 9 "wazuh-modulesd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffee7fc700 (LWP 5163)]
0x00007ffff68d90b1 in __strlen_avx2 () from /lib64/libc.so.6
```

### Backtrace

```
#0  0x00007ffff68d90b1 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00000000004a19e7 in wm_vuldet_check_specific_package (dbCVE=0x7fffe4023428, feed=FEED_MAC,
    pkg_name=0x7fffe404b4d0 "robo_3t", pkg_source=0x0, pkg_version=0x7fffe404b4f0 "",
    pkg_arch=0x7fffe4086070 "x86_64", pkg_vendor=0x0, cve_table=0x7fffe4085850, name_type=1 '\001',
    vuln_count=0x7fffe40856e0) at wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c:2524
#2  0x000000000049dddc in wm_vuldet_linux_nvd_vulnerabilities (db=0x7fffe4023428, agent=0x7fffe4001bf0,
    cve_table=0x7fffe4085850) at wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c:1736
#3  0x000000000047eb01 in wm_vuldet_report_agent_vulnerabilities (db=0x7fffe4023428, agent=0x7fffe4001bf0,
    flags=0x79a138) at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2040
#4  0x000000000047ed92 in wm_vuldet_check_agent_vulnerabilities (agents=0x7fffe4001bf0, flags=0x79a138,
    ignore_time=300) at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2113
#5  0x000000000049443b in wm_vuldet_run_scan (vuldet=0x79a090)
    at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:7035
#6  0x000000000048a92e in wm_vuldet_main (vuldet=0x79a090)
    at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4635
#7  0x00007ffff6b4040b in start_thread () from /lib64/libpthread.so.0
#8  0x00007ffff687b09f in clone () from /lib64/libc.so.6
```

### Conclusion

- `pkg_version` is empty (`""`), non-null.
- `wm_vuldet_clean_version()` returns null.

[wm_vuln_detector_nvd.c:2524](https://github.com/wazuh/wazuh/blob/v4.1.2/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L2524).
