### ISSUE TITLE
framework 5.0 agent process unification compliant

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8121]
|Wazuh version|Component|
|---|---|
| 5.0.0-0| execd, syscheckd, logcollector |

This issue aims to modify the way in which verifications are made or Wazuh core processes are used in the internal workings of this repository, given the epic: wazuh/wazuh#7981

For this, the following repository occurrences are listed so that they can be analyzed, modified, and/or adapted based on the requirement.

Current: execd, logcollector and syscheckd exist in the Wazuh ecosystem.
Expected: unify the old process behavior under the guardianship of wmodulesd.
Versions in which it should be applied: >= 5.0

Occurrences EXAMPLES:
https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/api/test/integration/env/configurations/manager/manager/healthcheck/master_daemons_check.txt
https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/api/test/integration/env/configurations/base/manager/healthcheck/daemons_check.txt
https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/api/test/integration/env/configurations/manager/manager/healthcheck/worker_daemons_check.txt
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/framework/wazuh/core/cluster/utils.py
https://github.com/wazuh/wazuh/blob/ca5da2adec4f2009291bd73c8a6f6a9e9b2d5cec/framework/wazuh/core/cluster/dapi/dapi.py
https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/api/test/integration/test_agent_GET_endpoints.tavern.yaml
https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/api/test/integration/test_cluster_endpoints.tavern.yaml

https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/api/test/integration/env/configurations/syscheck/agent/healthcheck/healthcheck.py
https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/api/test/integration/env/configurations/syscheck/manager/healthcheck/healthcheck.py
https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/api/test/integration/test_manager_endpoints.tavern.yaml
https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/api/test/integration/test_cluster_endpoints.tavern.yaml
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/framework/wazuh/core/cluster/utils.py
https://github.com/wazuh/wazuh/blob/395bc7b6ad6e17ad7f619cbf9ccf9ee2fc7e65e8/framework/wazuh/tests/test_manager.py

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Dwordcito** [comment]
Hi @davidjiglesias I am writing to ask if they could analyze these changes and for what estimated date could they have them?

**Comment by vicferpoy** [comment]
## Issue update

These will be the branches we will be working on.

| Main branch | Working branch |
|-|-|
| [dev-agent-process-unified](https://github.com/wazuh/wazuh/tree/dev-agent-process-unified) | [feature/8121-framework-agent-process-unification](https://github.com/wazuh/wazuh/tree/feature/8121-framework-agent-process-unification) |

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
## Issue update

Most of the changes have been done. However, there are a few cases where it is not clear what the behaviour will be and thus we need to define it before applying any change. An example would be the following:

https://github.com/wazuh/wazuh/blob/6e92d0d766b10504677bb12de9711027d59c28fa/api/test/integration/test_manager_endpoints.tavern.yaml#L624-L644

All the pending changes have been marked as `TODO`.

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
## Issue update

After a meeting with the team in charge of this process unification we have defined the last required changes. References to components must have the following format now:

```
wazuh-syscheckd -> wazuh-modulesd:syscheck
```

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
## Issue update
Refactor has been finished. All unit and integration tests pass.

### Unit tests
#### API
```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.9.1, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/api
plugins: asyncio-0.14.0, metadata-1.10.0
collected 225 items                                                                                                                                                                         

api/api/test/test_alogging.py ..........                                                                                                                                              [  4%]
api/api/test/test_authentication.py ..........                                                                                                                                        [  8%]
api/api/test/test_configuration.py .........................................                                                                                                          [ 27%]
api/api/test/test_util.py ...................................                                                                                                                         [ 42%]
api/api/test/test_validator.py .................................................................................................................................                      [100%]

============================================================================= 225 passed, 14 warnings in 1.27s ==============================================================================

```

#### Framework
```
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.9.1, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /home/vicferpoy/Desktop/Git/wazuh/framework
plugins: asyncio-0.14.0, metadata-1.10.0
collected 1704 items                                                                                                                                                                        

framework/wazuh/core/cluster/dapi/tests/test_dapi.py .......................                                                                                                          [  1%]
framework/wazuh/core/cluster/tests/test_cluster.py ...................                                                                                                                [  2%]
framework/wazuh/core/cluster/tests/test_common.py .......                                                                                                                             [  2%]
framework/wazuh/core/cluster/tests/test_control.py .....                                                                                                                              [  3%]
framework/wazuh/core/cluster/tests/test_local_client.py .                                                                                                                             [  3%]
framework/wazuh/core/cluster/tests/test_utils.py .......                                                                                                                              [  3%]
framework/wazuh/core/cluster/tests/test_worker.py ................                                                                                                                    [  4%]
framework/wazuh/core/tests/test_active_response.py ..............                                                                                                                     [  5%]
framework/wazuh/core/tests/test_agent.py ............................................................................................................................................ [ 13%]
.................                                                                                                                                                                     [ 14%]
framework/wazuh/core/tests/test_cdb_list.py ......................................                                                                                                    [ 16%]
framework/wazuh/core/tests/test_common.py .......                                                                                                                                     [ 17%]
framework/wazuh/core/tests/test_configuration.py ....................................                                                                                                 [ 19%]
framework/wazuh/core/tests/test_decoder.py ................                                                                                                                           [ 20%]
framework/wazuh/core/tests/test_input_validator.py ...                                                                                                                                [ 20%]
framework/wazuh/core/tests/test_logtest.py ..                                                                                                                                         [ 20%]
framework/wazuh/core/tests/test_manager.py .................                                                                                                                          [ 21%]
framework/wazuh/core/tests/test_pyDaemonModule.py ......                                                                                                                              [ 21%]
framework/wazuh/core/tests/test_results.py ........................................                                                                                                   [ 24%]
framework/wazuh/core/tests/test_rootcheck.py ..........                                                                                                                               [ 24%]
framework/wazuh/core/tests/test_rule.py ......................                                                                                                                        [ 26%]
framework/wazuh/core/tests/test_stats.py ....                                                                                                                                         [ 26%]
framework/wazuh/core/tests/test_syscollector.py ...                                                                                                                                   [ 26%]
framework/wazuh/core/tests/test_utils.py ............................................................................................................................................ [ 34%]
...............................................................................                                                                                                       [ 39%]
framework/wazuh/core/tests/test_vulnerability.py .                                                                                                                                    [ 39%]
framework/wazuh/core/tests/test_wazuh_queue.py ..................                                                                                                                     [ 40%]
framework/wazuh/core/tests/test_wazuh_socket.py ....................                                                                                                                  [ 41%]
framework/wazuh/core/tests/test_wdb.py .....................                                                                                                                          [ 42%]
framework/wazuh/rbac/tests/test_auth_context.py ..                                                                                                                                    [ 43%]
framework/wazuh/rbac/tests/test_decorators.py .........................................................................................................                               [ 49%]
framework/wazuh/rbac/tests/test_default_configuration.py .......................................................                                                                      [ 52%]
framework/wazuh/rbac/tests/test_orm.py ......................................................                                                                                         [ 55%]
framework/wazuh/rbac/tests/test_preprocessor.py ...........                                                                                                                           [ 56%]
framework/wazuh/tests/test_active_response.py ............                                                                                                                            [ 56%]
framework/wazuh/tests/test_agent.py ...................................................................................................                                               [ 62%]
framework/wazuh/tests/test_cdb_list.py .....................................................                                                                                          [ 65%]
framework/wazuh/tests/test_ciscat.py .................................                                                                                                                [ 67%]
framework/wazuh/tests/test_cluster.py .......                                                                                                                                         [ 68%]
framework/wazuh/tests/test_decoder.py ...................................                                                                                                             [ 70%]
framework/wazuh/tests/test_group.py ........                                                                                                                                          [ 70%]
framework/wazuh/tests/test_logtest.py ......                                                                                                                                          [ 71%]
framework/wazuh/tests/test_manager.py ...................                                                                                                                             [ 72%]
framework/wazuh/tests/test_mitre.py ................................................................................................................................................. [ 80%]
...................................                                                                                                                                                   [ 82%]
framework/wazuh/tests/test_rootcheck.py .................................................                                                                                             [ 85%]
framework/wazuh/tests/test_rule.py ........................................................                                                                                           [ 88%]
framework/wazuh/tests/test_sca.py .......                                                                                                                                             [ 89%]
framework/wazuh/tests/test_security.py ...........................................................................                                                                    [ 93%]
framework/wazuh/tests/test_stats.py ................                                                                                                                                  [ 94%]
framework/wazuh/tests/test_syscheck.py ........................                                                                                                                       [ 96%]
framework/wazuh/tests/test_syscollector.py ............                                                                                                                               [ 96%]
framework/wazuh/tests/test_task.py ............................                                                                                                                       [ 98%]
framework/wazuh/tests/test_vulnerability.py ..........................                                                                                                                [100%]

======================================================================= 1704 passed, 14 warnings in 248.34s (0:04:08) =======================================================================

```

### Integration tests
```
test_agent_DELETE_endpoints
	 6 passed, 8 warnings

test_agent_GET_endpoints
	 91 passed, 98 warnings

test_agent_POST_endpoints
	 5 passed, 7 warnings

test_agent_PUT_endpoints
	 10 passed, 12 warnings

test_cluster_endpoints
	 44 passed, 1 xpassed, 58 warnings

test_manager_endpoints
	 31 passed, 34 warnings

test_rbac_black_agent_endpoints
	 41 passed, 43 warnings

test_rbac_black_cluster_endpoints
	 17 passed, 19 warnings

test_rbac_black_manager_endpoints
	 15 passed, 17 warnings

test_rbac_white_agent_endpoints
	 41 passed, 43 warnings

test_rbac_white_cluster_endpoints
	 17 passed, 19 warnings

test_rbac_white_manager_endpoints
	 15 passed, 17 warnings

```

### Pending

Although these tests are passing, I had to change two integration tests to adapt their expected response. These changes do not depend on the API/framework code, so we need to confirm this new extracted data is correct.

#### `GET /agents/{agent_id}/config/logcollector/internal`

The `logcollector` internal section had a `debug` field that is no longer returned.

##### Test

```yaml

  - name: Request-Logcollector-Internal (Manager)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/000/config/logcollector/internal"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      status_code: 200
      json:
        error: !anyint
        data:
          internal:
            logcollector:
              debug: !anyint
              force_reload: !anyint
              input_threads: !anyint
              loop_timeout: !anyint
              max_files: !anyint
              max_lines: !anyint
              open_attempts: !anyint
              queue_size: !anyint
              reload_delay: !anyint
              reload_interval: !anyint
              remote_commands: !anyint
              rlimit_nofile: !anyint
              sample_log_length: !anyint
              sock_fail_time: !anyint
              vcheck_files: !anyint

```
##### API response

```json
{
  "data": {
    "internal": {
      "logcollector": {
        "remote_commands": 0,
        "loop_timeout": 2,
        "open_attempts": 8,
        "vcheck_files": 64,
        "max_lines": 10000,
        "max_files": 1000,
        "sock_fail_time": 300,
        "sample_log_length": 64,
        "queue_size": 1024,
        "input_threads": 4,
        "force_reload": 0,
        "reload_interval": 64,
        "reload_delay": 1000,
        "exclude_files_interval": 86400,
        "state_interval": 5,
        "rlimit_nofile": 0
      }
    }
  },
  "error": 0
}
```

#### `GET /manager/logs/summary`

Manager logs summary no longer have an entry for `wazuh-modulesd:execd` (in the testing environment). We could be missing changes on this file: https://github.com/wazuh/wazuh/blob/feature/8121-framework-agent-process-unification/api/test/integration/env/configurations/manager/manager/configuration_files/ossec-totals-27.log

##### Test

```yaml
  # GET /manager/logs/summary
  - name: Request
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/manager/logs/summary"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      status_code: 200
      json:
        error: !anyint
        data:
          affected_items:
            - sca: !anything
            - wazuh-agentlessd: !anything
            - wazuh-analysisd: !anything
            - wazuh-authd: !anything
            - wazuh-csyslogd: !anything
            - wazuh-db: !anything
            - wazuh-dbd: !anything
            - wazuh-integratord: !anything
            - wazuh-modulesd: !anything
            - wazuh-modulesd:agent-upgrade: !anything
            - wazuh-modulesd:ciscat: !anything
            - wazuh-modulesd:control: !anything
            - wazuh-modulesd:database: !anything
            - wazuh-modulesd:download: !anything
            - wazuh-modulesd:execd: !anything
            - wazuh-modulesd:logcollector: !anything
            - wazuh-modulesd:osquery: !anything
            - wazuh-modulesd:syscheck: !anything
            - wazuh-modulesd:syscollector: !anything
            - wazuh-modulesd:task-manager: !anything
            - wazuh-monitord: !anything
            - wazuh-remoted: !anything
            - wazuh-rootcheck: !anything
          failed_items: []
          total_affected_items: !anyint
          total_failed_items: 0
```

##### API response

```json
{
  "data": {
    "affected_items": [
      {
        "sca": {
          "all": 6,
          "info": 6,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-agentlessd": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-analysisd": {
          "all": 5,
          "info": 5,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-authd": {
          "all": 5,
          "info": 5,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-csyslogd": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-db": {
          "all": 1147,
          "info": 2,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 1145
        }
      },
      {
        "wazuh-dbd": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-integratord": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:agent-upgrade": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:ciscat": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:control": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:database": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:download": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:logcollector": {
          "all": 7,
          "info": 7,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:osquery": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:syscheck": {
          "all": 27,
          "info": 27,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:syscollector": {
          "all": 5,
          "info": 5,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-modulesd:task-manager": {
          "all": 1,
          "info": 1,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-monitord": {
          "all": 2,
          "info": 2,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      },
      {
        "wazuh-remoted": {
          "all": 781,
          "info": 3,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 778
        }
      },
      {
        "wazuh-rootcheck": {
          "all": 2,
          "info": 2,
          "error": 0,
          "critical": 0,
          "warning": 0,
          "debug": 0
        }
      }
    ],
    "total_affected_items": 22,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Log was successfully summarized in specified node",
  "error": 0
}
```

As soon as these changes are justified, we will open a PR.

Regards,
Víctor Fernández

**Comment by Dwordcito** [comment]
@vicferpoy 

Looking at the last message, it is good to mention that in the internal configuration when a debug mode is set, that mode is for the process.

By this, I mean that both execd, logcollector, and syscheckd now use wazuh_modules.debug since it is the process that will manage those unified modules.

**Comment by davidjiglesias** [comment]
Hello @Dwordcito,

I understand the new debug mode for all unified processes is wazuh_modules.debug, but that does not justify that the debug value is not found in the internal configuration, whatever the origin.

Also, the second part about the execd logs is also interesting, because we had logs with this tag before the changes but we don't have them anymore, without changes from our side.

Both cases need further investigation.

**Comment by vicferpoy** [comment]
## Issue update

Hello team,

During some manual testing we have detected that removing all `localfile` sections from the Wazuh configuration file (`ossec.conf`) and restarting makes the `logcollector` socket refuse all connections. In comparison with the `5.0-dev` branch and every `v4.x`, this does not happen. In addition, I noticed the debug field still exists in `5.0-dev`:

`GET /agents/000/config/logcollector/internal`

```json
{
  "data": {
    "internal": {
      "logcollector": {
        "remote_commands": 0,
        "loop_timeout": 2,
        "open_attempts": 8,
        "vcheck_files": 64,
        "max_lines": 10000,
        "max_files": 1000,
        "sock_fail_time": 300,
        "debug": 0,
        "sample_log_length": 64,
        "queue_size": 1024,
        "input_threads": 4,
        "force_reload": 0,
        "reload_interval": 64,
        "reload_delay": 1000,
        "exclude_files_interval": 86400,
        "state_interval": 5,
        "rlimit_nofile": 1100
      }
    }
  },
  "error": 0
}
```

As a consequence of this, if there are not `localfile` sections within the `ossec.conf`, endpoints like the one above (or any endpoint that requires a connection with the `logcollector` socket) will fail:

#### Framework code

https://github.com/wazuh/wazuh/blob/f1656aa27fe4d19d4feda273736fb8e3c5e00303/framework/wazuh/core/configuration.py#L771-L782

#### API response

```json
{
  "title": "Wazuh Internal Error",
  "detail": "Error connecting with socket",
  "dapi_errors": {
    "master-node": {
      "error": "Error connecting with socket",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 1121
}
```

#### Full traceback

```shellsession
2021/04/26 15:01:52 INFO: wazuh 172.24.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.228s: 200
2021/04/26 15:01:52 ERROR: Error connecting with socket
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/core/wazuh_socket.py", line 27, in _connect
    self.s.connect(self.path)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/core/configuration.py", line 780, in get_active_configuration
    s = WazuhSocket(dest_socket)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/core/wazuh_socket.py", line 22, in __init__
    self._connect()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/core/wazuh_socket.py", line 29, in _connect
    raise WazuhException(1013, str(e))
wazuh.core.exception.WazuhException: Error 1013 - Unable to connect with socket: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 253, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 230, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/rbac/decorators.py", line 406, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/agent.py", line 866, in get_agent_config
    return WazuhResult({'data': my_agent.getconfig(component=component, config=config, agent_version=my_agent.version)})
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/core/agent.py", line 1209, in getconfig
    return configuration.get_active_configuration(self.id, component, config)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-5.0.0-py3.9.egg/wazuh/core/configuration.py", line 782, in get_active_configuration
    raise WazuhInternalError(1121)
wazuh.core.exception.WazuhInternalError: Error 1121 - Error connecting with socket
2021/04/26 15:01:52 INFO: wazuh 172.24.0.1 "GET /agents/000/config/logcollector/internal" with parameters {"wait_for_complete": "true"} and body {} done in 0.131s: 500
```

Regards,
Víctor Fernández

**Comment by Dwordcito** [comment]
Thanks for the report, issue created: https://github.com/wazuh/wazuh/issues/8383
