### ISSUE TITLE
Wazuh API requests errors

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#8429]
|Wazuh version|Component|
|---|---|
| 4.1.4-40113 | Wazuh API |

### Description
Hello Team,

I saw errors in Wazuh API requests using the Splunk app. Then I tested with curl from a remote server observing the same result, which points to an issue with the Wazuh API itself.

### Findings
- Ran cluster_control -l and sometimes it throws the following error, but most of the time work as expected:
```
/var/ossec/bin/cluster_control  -l
ERROR: Expecting value: line 1 column 1 (char 0)
```
- Listed the running processes, al seems to be ok
```
# ps aux | grep -P 'wazuh|ossec'
ossec     3787  0.0  0.6 799804 196012 ?       Sl   Apr26   0:52 /u01/ossec/framework/python/bin/python3 /u01/ossec/api/scripts/wazuh-apid.py
root      3827  0.4  0.3 249716 114756 ?       Sl   Apr26  12:51 /var/ossec/bin/ossec-authd
ossec     3844 49.2  0.0 641328 12512 ?        Sl   Apr26 1306:41 /var/ossec/bin/wazuh-db
root      3885  0.0  0.0  34776  1400 ?        Sl   Apr26   0:00 /var/ossec/bin/ossec-execd
ossec     3901  0.0  0.2 4738320 83656 ?       Sl   Apr26   1:03 /var/ossec/bin/ossec-analysisd
root      4099  0.0  0.0  43400  2684 ?        SNl  Apr26   0:02 /var/ossec/bin/ossec-syscheckd
ossecr    4131 58.6  0.9 822800 316180 ?       Sl   Apr26 1556:48 /var/ossec/bin/ossec-remoted
root      4157  0.0  0.0  67548  1440 ?        Sl   Apr26   0:20 /var/ossec/bin/ossec-logcollector
ossec     4172  0.0  0.0  35360  2508 ?        Sl   Apr26   0:34 /var/ossec/bin/ossec-monitord
root      4182 68.1  0.3 624792 119696 ?       Sl   Apr26 1806:17 /var/ossec/bin/wazuh-modulesd
ossec     4245 55.5  5.1 1827872 1631060 ?     R    Apr26 1473:49 /u01/ossec/framework/python/bin/python3 /u01/ossec/framework/scripts/wazuh-clusterd.py
```

### Logs Collected
**No Errors in `ossec.log`**

#### API call (`verbose` enabled) from the remote Server:
```
curl -k -X GET "https://wazuh-manager-master:55000/cluster/configuration/validation" -H "Authorization: Bearer $TOKEN" -v
* About to connect() to wazuh-manager-master port 55000 (#0)
*   Trying 10.46.73.230...
* Connected to wazuh-manager-master (10.46.73.230) port 55000 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=wazuh-api.internal.dominio.com,OU=IT,O=dominio.com Inc.,L=San Francisco,ST=California,C=US
* 	start date: Sep 03 21:56:45 2019 GMT
* 	expire date: Sep 02 21:56:45 2022 GMT
* 	common name: wazuh-api.internal.dominio.com
* 	issuer: CN=ASH-CA-WP1-CA,DC=internal,DC=dominio,DC=com
> GET /cluster/configuration/validation HTTP/1.1
> User-Agent: curl/7.29.0
> Host: wazuh-manager-master:55000
> Accept: */*
> Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9....
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/problem+json; charset=utf-8
< Content-Length: 378
< Date: Wed, 28 Apr 2021 18:59:29 GMT
< Server: Python/3.9 aiohttp/3.7.4
< 
{"title": "Wazuh Internal Error", "detail": "Wazuh Internal Error", "remediation": "Please, check `WAZUH_HOME/logs/ossec.log`, `WAZUH_HOME/logs/cluster.log` and `WAZUH_HOME/logs/api.log` to get more information about the error", "dapi_errors": {"wazuh-manager-master": {"error": "Wazuh Internal Error. See log for more detail", "logfile": "WAZUH_HOME/logs/api.log"}}, "error": 1000}
* Connection #0 to host wazuh-manager-master left intact
```

#### API call from the Wazuh Managerr:
```
curl -k -X GET "https://localhost:55000/cluster/configuration/validation" -H "Authorization: Bearer $TOKEN"
{"title": "Wazuh Internal Error", "detail": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused", "remediation": "Please, restart Wazuh to restore sockets", "dapi_errors": {"wazuh-manager-master": {"error": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused", "logfile": "WAZUH_HOME/logs/api.log"}, "orb-wazuh-lps08": {"error": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused", "logfile": "WAZUH_HOME/logs/cluster.log"}, "orc-wazuh-lps20": {"error": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused", "logfile": "WAZUH_HOME/logs/cluster.log"}, "orb-wazuh-lps02": {"error": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused", "logfile": "WAZUH_HOME/logs/cluster.log"}}, "error": 1013}
```

#### Logs from `SplunkAppForWazuh.log`
```
ERROR: 2021/04/05 17:59:27: 'Error when get auth Wazuh token: 'data''
ERROR: 2021/04/05 17:59:27: 'Error when checking API connection: local variable 'e' referenced before assignment'
ERROR: 2021/04/05 17:59:28: 'Error when get auth Wazuh token: 'data''
ERROR: 2021/04/05 17:59:28: 'Error when checking API connection: local variable 'e' referenced before assignment'
ERROR: 2021/04/05 18:00:07: 'Error when get auth Wazuh token: 'data''
ERROR: 2021/04/05 18:00:07: 'Error when checking API connection: local variable 'e' referenced before assignment'
ERROR: 2021/04/05 18:03:18: 'manager: Cannot connect to API : HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 18:08:11: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 18:08:31: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 18:09:08: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 18:17:21: 'Error getting an API in DB module : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:17:21: 'manager: Error in get_apis endpoint: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:17:21: 'Error when checking API connection: the JSON object must be str, bytes or bytearray, not dict'
ERROR: 2021/04/05 18:17:24: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 18:39:32: 'Error when checking Wazuh version: 'data''
ERROR: 2021/04/05 18:40:18: 'Error getting an API in DB module : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:40:18: 'manager: Error in update_api endpoint: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:40:57: 'api: Error while requesting to Wazuh API: {'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'wazuh-manager-master': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/api.log'}}, 'error': 3021}'
ERROR: 2021/04/05 18:40:57: 'api: Error making API request: {'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'wazuh-manager-master': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/api.log'}}, 'error': 3021}'
ERROR: 2021/04/05 18:41:40: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 18:41:41: 'Error getting an API in DB module : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:41:41: 'manager: Error in get_apis endpoint: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:41:41: 'Error when checking API connection: the JSON object must be str, bytes or bytearray, not dict'
ERROR: 2021/04/05 18:42:25: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 18:42:29: 'Error getting an API in DB module : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:42:29: 'manager: Error in get_apis endpoint: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:42:29: 'Error when checking API connection: the JSON object must be str, bytes or bytearray, not dict'
ERROR: 2021/04/05 18:43:10: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 18:43:32: 'Error getting an API in DB module : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:43:32: 'manager: Error in update_api endpoint: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:44:53: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 18:45:31: 'Error getting an API in DB module : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:45:31: 'manager: Error in update_api endpoint: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:45:41: 'api: Error while requesting to Wazuh API: {'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'wazuh-manager-master': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/api.log'}}, 'error': 3021}'
ERROR: 2021/04/05 18:45:41: 'api: Error making API request: {'title': 'Wazuh Internal Error', 'detail': 'Timeout executing API request', 'dapi_errors': {'wazuh-manager-master': {'error': 'Timeout executing API request', 'logfile': 'WAZUH_HOME/logs/api.log'}}, 'error': 3021}'
ERROR: 2021/04/05 18:48:39: 'Error getting an API in DB module : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 18:48:39: 'api: Error making API request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/05 19:22:19: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 19:22:42: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/05 19:23:02: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/12 00:15:58: 'Error getting an API in DB module : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/12 00:15:58: 'api: Error making API request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/12 18:52:12: 'manager: Cannot connect to API : DAEMONS-NOT-READY'
ERROR: 2021/04/12 18:52:44: 'Error inserting in DB module: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))'
ERROR: 2021/04/12 18:52:44: '{'manager - add_api': "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"}'
ERROR: 2021/04/12 18:52:44: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/12 18:52:45: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/12 18:52:55: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/12 18:53:20: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/12 18:55:19: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/12 18:55:24: 'Error removing an API in DB module: Missing ID in remove DB module'
ERROR: 2021/04/12 18:55:24: 'manager: Error in remove_api endpoint: Missing ID in remove DB module'
ERROR: 2021/04/12 18:55:31: 'Error removing an API in DB module: Missing ID in remove DB module'
ERROR: 2021/04/12 18:55:31: 'manager: Error in remove_api endpoint: Missing ID in remove DB module'
ERROR: 2021/04/12 18:56:11: 'Error removing an API in DB module: Missing ID in remove DB module'
ERROR: 2021/04/12 18:56:11: 'manager: Error in remove_api endpoint: Missing ID in remove DB module'
ERROR: 2021/04/12 18:56:13: 'Error removing an API in DB module: Missing ID in remove DB module'
ERROR: 2021/04/12 18:56:13: 'manager: Error in remove_api endpoint: Missing ID in remove DB module'
ERROR: 2021/04/12 18:56:20: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/12 18:56:22: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/12 18:56:48: 'manager: Cannot connect to API : DAEMONS-NOT-READY'
ERROR: 2021/04/12 18:57:12: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/12 18:57:13: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/12 18:58:52: 'Error when checking API connection: 'userapi''
ERROR: 2021/04/28 18:39:38: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/28 18:40:01: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/28 18:42:45: 'Error when checking Wazuh version: 'data''
ERROR: 2021/04/28 18:46:02: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/28 18:46:24: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/28 18:46:50: 'manager: Cannot connect to API : HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/28 18:46:52: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/28 18:46:52: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
ERROR: 2021/04/28 18:48:18: 'Error when checking API connection: HTTPSConnectionPool(host='wazuh-manager-master', port=55000): Read timed out. (read timeout=20)'
```

#### Logs from `api.log`
```
2021/04/28 18:46:32 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 252, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/04/28 18:46:32 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 252, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/04/28 18:56:34 ERROR: Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/manager.py", line 144, in validate_ossec_conf
    execq_socket.connect(execq_socket_path)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/u01/ossec/framework/python/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 224, in run_local
    data = self.f(**self.f_kwargs)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/rbac/decorators.py", line 406, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/manager.py", line 197, in validation
    response = validate_ossec_conf()
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/manager.py", line 147, in validate_ossec_conf
    raise WazuhInternalError(1013, extra_message=extra_msg)
wazuh.core.exception.WazuhInternalError: Error 1013 - Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused
2021/04/28 18:59:29 ERROR: Unhandled exception: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 149, in distribute_function
    response = await self.forward_request()
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 446, in forward_request
    allowed_nodes = await get_nodes_info(self.get_client(), **filter_node_kwarg)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/rbac/decorators.py", line 319, in async_list_handler
    result = await result
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/cluster.py", line 91, in get_nodes_info
    data = await get_nodes(lc, filter_node=list(nodes), **kwargs)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/control.py", line 52, in get_nodes
    result = json.loads(await lc.execute(command=b'get_nodes',
  File "/u01/ossec/framework/python/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/u01/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/u01/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

#### Logs from `cluster.log`
```
Internal error processing request 'b'sync_i_w_m_e'': Error 3027 - Unknown received task name: 3327919087
2021/04/28 19:05:16 ERROR: [Worker wazuh-manager-worker-20] [Main] Unhandled error processing request 'b'sync_i_w_m_r'': '3327919087'
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/common.py", line 519, in dispatch
    command, payload = self.process_request(command, payload)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/master.py", line 169, in process_request
    return self.process_sync_error_from_worker(command, data)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/master.py", line 482, in process_sync_error_from_worker
    return super().error_receiving_file(error_msg.decode())
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/common.py", line 852, in error_receiving_file
    if os.path.exists(self.sync_tasks[taskname].filename):
KeyError: '3327919087'
```

### Troubleshooting
- Restarted the Wazuh Manager services in the Master Node, without any issues
- Because of a similar issue ([7968](https://github.com/wazuh/wazuh/issues/7968)) I checked the AR configurations:
```
  <active-response>
    <disabled>yes</disabled>
  </active-response>
```

Please let me know if I can give you any other information.
Thank you in advance.

**Comment by vicferpoy** [comment]
# Issue update

Hello team,

I'm going to break down what we got from the findings so far:

## API requests errors

### From remote server

#### Full response

```json
{
  "title": "Wazuh Internal Error",
  "detail": "Wazuh Internal Error",
  "remediation": "Please, check `WAZUH_HOME/logs/ossec.log`, `WAZUH_HOME/logs/cluster.log` and `WAZUH_HOME/logs/api.log` to get more information about the error",
  "dapi_errors": {
    "wazuh-manager-master": {
      "error": "Wazuh Internal Error. See log for more detail",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 1000
}
```

This error requires the full traceback from the `api.log` or/and the `cluster.log`. `ossec.log` is not required in most cases and it would mean that Wazuh core components are failing (not the case here in my opinion). There are some log traces but we cannot really know which ones belong to this API request. Timestamps could help identifying them.

### From the manager itself

#### Full response

```json
{
  "title": "Wazuh Internal Error",
  "detail": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused",
  "remediation": "Please, restart Wazuh to restore sockets",
  "dapi_errors": {
    "wazuh-manager-master": {
      "error": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused",
      "logfile": "WAZUH_HOME/logs/api.log"
    },
    "orb-wazuh-lps08": {
      "error": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "orc-wazuh-lps20": {
      "error": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "orb-wazuh-lps02": {
      "error": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "error": 1013
}
```

As for this response, we can clearly see that there is a connection error with the `execq` socket. This is due to a [reported bug](https://github.com/wazuh/wazuh/issues/7968) with `active-response` that [was fixed](https://github.com/wazuh/wazuh/pull/8535) on later versions.

As Dario commented, `active-response` was disabled. To confirm this behaviour, I tried the same endpoint adding the following `active-response` block to my configuration (v4.1.4):

```xml
  <active-response>
    <disabled>yes</disabled>
  </active-response>
```

This was the response for `GET /manager/configuration/validation`:

```json
{
  "title": "Wazuh Internal Error",
  "detail": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused",
  "remediation": "Please, restart Wazuh to restore sockets",
  "dapi_errors": {
    "master-node": {
      "error": "Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 1013
}
```

Removing the `active-response` block:


```json
{
  "data": {
    "affected_items": [
      {
        "name": "master-node",
        "status": "OK"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Validation was successfully checked in all nodes",
  "error": 0
}
```

### `asyncio.exceptions.CancelledError` error

As for the `CancelledError`, it is a consequence of the `asyncio.TimeoutError`. The task could be cancelled whilst its Timeout is being handled, leading to an uncontrolled exception. We need to **open an issue** for this.

```shell-session
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 252, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/04/28 18:46:32 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError
```

## Cluster errors

### `bin/cluster_control -l` error

```shell-session
2021/04/28 18:59:29 ERROR: Unhandled exception: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 149, in distribute_function
    response = await self.forward_request()
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 446, in forward_request
    allowed_nodes = await get_nodes_info(self.get_client(), **filter_node_kwarg)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/rbac/decorators.py", line 319, in async_list_handler
    result = await result
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/cluster.py", line 91, in get_nodes_info
    data = await get_nodes(lc, filter_node=list(nodes), **kwargs)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/control.py", line 52, in get_nodes
    result = json.loads(await lc.execute(command=b'get_nodes',
  File "/u01/ossec/framework/python/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/u01/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/u01/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

For this we need to further investigate this function execution flow as it is being distributed and it is harder to follow. Expect more updates about this matter in upcoming comments.

### `KeyError` error

Regarding this block, the error which shows up is masking the actual error. It was fixed [here](https://github.com/wazuh/wazuh/pull/8699), so if it happens again we will be able to know what is exactly happening.

```shell-session
Internal error processing request 'b'sync_i_w_m_e'': Error 3027 - Unknown received task name: 3327919087
2021/04/28 19:05:16 ERROR: [Worker wazuh-manager-worker-20] [Main] Unhandled error processing request 'b'sync_i_w_m_r'': '3327919087'
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/common.py", line 519, in dispatch
    command, payload = self.process_request(command, payload)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/master.py", line 169, in process_request
    return self.process_sync_error_from_worker(command, data)
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/master.py", line 482, in process_sync_error_from_worker
    return super().error_receiving_file(error_msg.decode())
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/common.py", line 852, in error_receiving_file
    if os.path.exists(self.sync_tasks[taskname].filename):
KeyError: '3327919087'
```

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
# Issue update

Hello team,

Regarding the following error:

```shellsession
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

After some research, I found that this is an already known error that needs to be fixed: https://github.com/wazuh/wazuh/issues/8721

I will update the issue above with my own findings as I found why it truly fails.

Regards,
Víctor Fernández
