### ISSUE TITLE
Improve sendsync error and API timeout error messages

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#8541]
|Wazuh version|Component|
|---|---|
| master | Cluster/framework |

## Description 

Hi team,

While testing what is the behavior of cluster when agents have enrollment enabled but master's authd service is disabled, I found some problems in the error message logs.

#### 1. Printing the same error twice
As we can see below, if there is an exception on line 694, an error message will be printed (695). However, it will also be printed on line 699:
https://github.com/wazuh/wazuh/blob/0a320a0aedf3c113317b044f365ee916fd3249f0/framework/wazuh/core/cluster/dapi/dapi.py#L694-L700

Therefore, the message is duplicated (first and last line):
```
2021/05/05 10:10:01 ERROR: [Master] [Main] Error in SendSync: Error 1013 - Unable to connect with socket: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/wazuh_socket.py", line 27, in _connect
    self.s.connect(self.path)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 694, in run
    result = await wazuh_sendsync(**request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/wazuh_socket.py", line 278, in wazuh_sendsync
    raise e
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/wazuh_socket.py", line 270, in wazuh_sendsync
    sock = WazuhSocket(daemons[daemon_name]['path'])
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/wazuh_socket.py", line 22, in __init__
    self._connect()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/wazuh_socket.py", line 29, in _connect
    raise WazuhException(1013, str(e))
wazuh.core.exception.WazuhException: Error 1013 - Unable to connect with socket: [Errno 111] Connection refused
2021/05/05 10:10:01 ERROR: [Master] [Main] Error in SendSync: Error 1013 - Unable to connect with socket: [Errno 111] Connection refused
```

The `self.logger.error()` of line 695 should be deleted.

#### 2. There is no enough information
In this case, it is the `authd` service the one which is not available. However, this can't be inferred just by looking at the logs, since it says nothing about the daemon_name (destionation), the source, etc. 

It should be added to the error message in line 696.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hey team!

Although improving the API timeout error messages was also proposed, I think it is not necessary since, after the errors, a log is printed showing the endpoint which was used and its parameters (last line):
```
2021/05/06 07:36:08 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 253, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 255, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/05/06 07:36:08 INFO: wazuh 192.168.128.1 "GET /security/user/authenticate" with parameters {} and body {} done in 10.102s: 500
2021/05/06 07:36:18 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 253, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 255, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/05/06 07:36:18 INFO: wazuh 192.168.128.1 "GET /security/user/authenticate" with parameters {} and body {} done in 10.111s: 500
```

Regards,
Selu.
