### ISSUE TITLE
API Error: `json.loads` does not receive a valid JSON

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh#8721]
|Wazuh version|Component|
|---|---|
| 4.1.5 | Wazuh API |

Hello team,

Checking one of the environments of a cloud client, we found this error in the API logs of its master manager. After restarting the manager everything worked correctly again.

```python
2021/05/18 06:35:21 ERROR: Error handling request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/connexion/apis/aiohttp_api.py", line 50, in problems_middleware
    response = yield from handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 110, in impl
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.1.5-py3.9.egg/api/middlewares.py", line 139, in response_postprocessing
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.1.5-py3.9.egg/api/middlewares.py", line 31, in set_user_name
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.1.5-py3.9.egg/api/middlewares.py", line 114, in security_middleware
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.1.5-py3.9.egg/api/middlewares.py", line 87, in request_logging
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.1.5-py3.9.egg/api/middlewares.py", line 36, in set_secure_headers
    resp = await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/aiohttp_cache/middleware.py", line 59, in cache_middleware
    return await handler(request)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/connexion/decorators/coroutine_wrappers.py", line 23, in wrapper
    connexion_response = yield from connexion_response
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api-4.1.5-py3.9.egg/api/controllers/cluster_controller.py", line 75, in get_cluster_nodes
    nodes = raise_if_exc(await get_system_nodes())
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.5-py3.9.egg/wazuh/core/cluster/control.py", line 180, in get_system_nodes
    result = await get_nodes(lc)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.5-py3.9.egg/wazuh/core/cluster/control.py", line 52, in get_nodes
    result = json.loads(await lc.execute(command=b'get_nodes',
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
# Issue update

Hello team,

This kind of error was detected as well in #8429 . During that issue investigation I could confirm that this error has nothing to do with bytesarrays. The `json.loads` function allows both strings and bytes, but they must contain a valid JSON. This is the main issue.

https://github.com/wazuh/wazuh/blob/0e1e79a070cb7775baa441d376a0bad3d65c14be/framework/wazuh/core/cluster/control.py#L52-L55

The result of `lc.execute` is a string, but not a valid JSON. This is probably due to a timeout doing this request, resulting in the following message:

https://github.com/wazuh/wazuh/blob/0e1e79a070cb7775baa441d376a0bad3d65c14be/framework/wazuh/core/cluster/common.py#L367-L369

```python
>>> import json
>>> json.loads(b'Error sending request: timeout expired.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> 

```

Regards,
Víctor Fernández
