### ISSUE TITLE
Handle `asyncio.CancelledError` in DAPI module

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#8859]
|Wazuh version|Component|
|---|---|
| 4.x | Framework |

Hello team,

As it was reported in #8429 , sometimes the task could be cancelled within the `TimeoutError` exception. This is an atypical situation but we need to investigate if this could happen under more situations and handle them all to prevent long tracebacks and improve the log. 

```shellsession
2021/04/28 18:46:32 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u01/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.4-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 252, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Víctor Fernández

**Comment by vicferpoy** [comment]
# Issue update
Hello team,

After further investigation, we can confirm that this error is caused by the previous exception context. 

`asyncio.wait_for` timeouts are broke down in two steps:
- **Task cancellation**, although if the task is already _awaiting_ something, it will finish that block (and thus finish the synchronous framework functions). 
- **Timeout exception**.

This whole process raises an `asyncio.TimeoutError` exception, but it is possible to catch the `asyncio.CancelledError` exception even though it is not directly raised to add extra logic before the `asyncio.TimeoutError`.

As we were adding the exception context as additional information, the whole traceback would show up in the `api.log`:

https://github.com/wazuh/wazuh/blob/aab8d75e57914923a6c76399c84ebafbdba34719/framework/wazuh/core/cluster/dapi/dapi.py#L266

## Before the fix (forcing a timeout)
```shellsession
2021/06/02 14:26:44 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 253, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 255, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/06/02 14:26:44 INFO: wazuh 172.26.0.1 "GET /agents" with parameters {} and body {} done in 10.052s: 500

```

## After the fix (forcing a timeout)
```shellsession
2021/06/02 14:29:46 ERROR: Timeout executing API request
2021/06/02 14:29:46 INFO: wazuh 172.26.0.1 "GET /agents" with parameters {} and body {} done in 10.046s: 500

```

API responses remain the same:

```json
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master-node": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 3021
}
```

Check the [PEP 409 notes about supressing exception context](https://www.python.org/dev/peps/pep-0409/) for additional information about this topic.

Regards,
Víctor Fernández
