### ISSUE TITLE
wazuh-maild: segmentation fault when JSON alert has more than six hierarchy levels

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#8934]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10 to master(4.3) | `ossec-maild`, `wazuh-maild` | Manager | Any | Any |

Hi team!

Currently `ossec-maild`/ `wazuh-maild` is crashing (segfault) when processing alerts in JSON format (configured by `email_log_source` in `ossec.conf`) with more than 6 levels of hierarchy. 

This is caused in [`PrintTable`](https://github.com/wazuh/wazuh/blob/master/src/os_maild/os_maild_client.c#L724) function that is called recursively to get tabulated alert information, allowing up to 6 levels of tabulation. If alert has more than 6 levels, the function will be called recursively again but using sibling cJSON object, that it's only valid in case of a cJSON array, otherwise will cause segfault.
https://github.com/wazuh/wazuh/blob/93d847aa8a8b5f4de4127d9c6179b5d59f921bfc/src/os_maild/os_maild_client.c#L807-L813

The next log pushed into `alerts.json` will reproduce this scenario.
```json
{"timestamp":"2021-06-08T12:58:32.204+0000","rule":{"level":15,"description":"Some description.","id":"123456","firedtimes":1,"mail":true,"groups":["mygroup"],"pci_dss":["10.6.1","10.2.6"],"gpg13":["10.1"],"gdpr":["IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["AU.6","AU.14","AU.5"],"tsc":["CC7.2","CC7.3","CC6.8"]},"agent":{"id":"001","name":"myagent","ip":""},"data":{"level1":{"level2":{"level3":{"level4":{"level5":{"level6":{"level7":"some inner value"}}}}}}},"manager":{"name":"wazuh-manager"},"id":"1623157112.166520","decoder":{"name":"mydecoder"},"location":"/any/location"}
```

Regards,
Nico

**Comment by jnasselle** [comment]
This issue might be related to #5758

**Comment by vikman90** [comment]
## Backtrace

```
#0  0x000055555556bb7f in PrintTable (item=0x0,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65413, tab=0x55555574c450 "\t\t\t\t\t\t", counter=12)
    at os_maild/os_maild_client.c:739
#1  0x000055555556c081 in PrintTable (item=0x555555794a00,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65413, tab=0x55555574c450 "\t\t\t\t\t\t", counter=12)
    at os_maild/os_maild_client.c:812
#2  0x000055555556c05e in PrintTable (item=0x555555747e60,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65427, tab=0x555555780960 "\t\t\t\t\t", counter=10)
    at os_maild/os_maild_client.c:809
#3  0x000055555556c05e in PrintTable (item=0x555555794ad0,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65440, tab=0x555555740860 "\t\t\t\t", counter=8)
    at os_maild/os_maild_client.c:809
#4  0x000055555556c05e in PrintTable (item=0x5555557783e0,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65452, tab=0x555555792790 "\t\t\t", counter=6)
    at os_maild/os_maild_client.c:809
#5  0x000055555556c05e in PrintTable (item=0x5555557390b0,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65463, tab=0x555555738680 "\t\t", counter=4)
    at os_maild/os_maild_client.c:809
#6  0x000055555556c0b5 in PrintTable (item=0x555555751f10,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65471, tab=0x555555738680 "\t\t", counter=4)
    at os_maild/os_maild_client.c:820
#7  0x000055555556c0b5 in PrintTable (item=0x555555745b50,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65480, tab=0x555555738680 "\t\t", counter=4)
    at os_maild/os_maild_client.c:820
#8  0x000055555556c0b5 in PrintTable (item=0x555555745ba0,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65488, tab=0x555555738680 "\t\t", counter=4)
    at os_maild/os_maild_client.c:820
#9  0x000055555556c05e in PrintTable (item=0x55555573ffb0,
    printed=0x7ffffffeded0 "\t\tTimestamp: \"2021-06-08T12:58:32.204+0000\"\r\n\t\tRule\r\n\t\t\tLevel: 15\r\n\t\t\tDescription: \"Some description.\"\r\n\t\t\tId: \"123456\"\r\n\t\t\tFiredtimes: 1\r\n\t\t\tMail: true\r\n\t\t\tGroups: \"mygroup\" \r\n\t\t\tPci_dss: \"10.6.1\" \"1"..., body_size=65533, tab=0x55555572ca00 "\t", counter=2) at os_maild/os_maild_client.c:809
#10 0x000055555556ae5e in OS_RecvMailQ_JSON (fileq=0x555555766a90, Mail=0x555555718c40 <mail>, msg_sms=0x7fffffffdf40) at os_maild/os_maild_client.c:494
#11 0x0000555555568dd6 in OS_Run (mail=0x555555718c40 <mail>) at os_maild/maild.c:407
#12 0x00005555555686f0 in main (argc=2, argv=0x7fffffffe148) at os_maild/maild.c:222
```

## Rationale

When reaching the top nesting level, the program breaks the recursion and continues parsing the alert on the item's sibling, **assuming that the item has one**. As the sample above has:
```json
"data":{"level1":{"level2":{"level3":{"level4":{"level5":{"level6":{"level7":"some inner value"}}} }}}}
                                                                                                  ^
                                                                                        No sibling for level4.
```

That makes wazuh-maild crash.

## Proposed fix

Let wazuh-maild go through items' next objects (`item->next`) only if such objects exist.
