### ISSUE TITLE
Investigate and fix agent-info sync errors in cluster

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#8935]
|Wazuh version|Component|
|---|---|
| 4.2.1 | Wazuh cluster |

## Description

Hello team,

We have found a series of errors in the logs of a cluster environment with the following characteristics: 
- 25 workers
- 20-25k agents

On the one hand, it seems that there is some error during the handling of the `b'str_upd'` command that is used to receive chunks of a long string. The reason of the error is unknown due to an unhandled KeyError that has already been fixed and merged here https://github.com/wazuh/wazuh/pull/8872:
```
Jun  9 02:23:06 wazuh-master 2021/06/09 02:23:06 ERROR: [Worker wazuh-worker-12] [Main] Unhandled error processing request 'b'str_upd'': b'Error'
Jun  9 02:23:06 wazuh-master Traceback (most recent call last):
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/common.py", line 580, in dispatch
Jun  9 02:23:06 wazuh-master command, payload = self.process_request(command, payload)
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/master.py", line 233, in process_request
Jun  9 02:23:06 wazuh-master return super().process_request(command, data)
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/server.py", line 100, in process_request
Jun  9 02:23:06 wazuh-master return super().process_request(command, data)
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/common.py", line 621, in process_request
Jun  9 02:23:06 wazuh-master return self.str_upd(data)
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/common.py", line 763, in str_upd
Jun  9 02:23:06 wazuh-master self.in_str[name].receive_data(str_data)
Jun  9 02:23:06 wazuh-master KeyError: b'Error'
```

On the other hand, it seems that workers can receive a timeout message when trying to send a string here (on line 184): 
https://github.com/wazuh/wazuh/blob/93d847aa8a8b5f4de4127d9c6179b5d59f921bfc/framework/wazuh/core/cluster/worker.py#L182-L186

If the task_id sent by the worker to the master is `b'Error sending request: timeout expired.'`, the master will not be able to find the string and the following error will appear: 
```
Jun  9 02:25:01 wazuh-master 2021/06/09 02:25:00 ERROR: [Worker wazuh-worker-2] [Main] Error 3035 - String couldn't be found: it should be under task_id b'Error sending request: timeout expired.', but it's empty.
Jun  9 02:25:03 wazuh-master 2021/06/09 02:25:02 ERROR: [Worker wazuh-worker-24] [Main] Error 3035 - String couldn't be found: it should be under task_id b'Error sending request: timeout expired.', but it's empty.
Jun  9 02:25:03 wazuh-master 2021/06/09 02:25:02 ERROR: [Worker wazuh-worker-0] [Main] Error 3035 - String couldn't be found: it should be under task_id b'Error sending request: timeout expired.', but it's empty.
Jun  9 02:25:06 wazuh-master 2021/06/09 02:25:05 ERROR: [Worker wazuh-worker-11] [Main] Error 3035 - String couldn't be found: it should be under task_id b'Error sending request: timeout expired.', but it's empty.

```
### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hey team,

I have found what is the reason for the errors that are seen in the logs of the original post. 

The `agent-info` synchronization process uses the `send_string` protocol to send the agent information from the workers to the master. To do this, in the first place the worker asks the master to reserve memory (in a bytearray) with the size of the information that will be sent, as shown here:
https://github.com/wazuh/wazuh/blob/6434cc9e8aa45a430fbb5fedba306b479207a53b/framework/wazuh/core/cluster/common.py#L480-L481

However, although `send_request()` is expected to return a `task_id`, sometimes if the timeout is reached a message like the following can be received instead:  `b'Error sending request: timeout expired.'`. Therefore, the next step that consists of sending the string to the `task_id` received previously, will fail since task_id is not a real ID but an error message: 
https://github.com/wazuh/wazuh/blob/6434cc9e8aa45a430fbb5fedba306b479207a53b/framework/wazuh/core/cluster/common.py#L483-L486

This causes the first error: 
```
Jun  9 02:23:06 wazuh-master 2021/06/09 02:23:06 ERROR: [Worker wazuh-worker-12] [Main] Unhandled error processing request 'b'str_upd'': b'Error'
Jun  9 02:23:06 wazuh-master Traceback (most recent call last):
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/common.py", line 580, in dispatch
Jun  9 02:23:06 wazuh-master command, payload = self.process_request(command, payload)
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/master.py", line 233, in process_request
Jun  9 02:23:06 wazuh-master return super().process_request(command, data)
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/server.py", line 100, in process_request
Jun  9 02:23:06 wazuh-master return super().process_request(command, data)
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/common.py", line 621, in process_request
Jun  9 02:23:06 wazuh-master return self.str_upd(data)
Jun  9 02:23:06 wazuh-master File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/common.py", line 763, in str_upd
Jun  9 02:23:06 wazuh-master self.in_str[name].receive_data(str_data)
Jun  9 02:23:06 wazuh-master KeyError: b'Error'
```

The problem, beyond the error shown, is that the master may be reserving the space and then never be freed since the synchronization task does not finish. To avoid this, I am creating a new command that in case of error, it will look for a string with the same length as expected and that only contains null characters (`\x00`). If found, it will be removed. 

Best regards,
Selu.
