### ISSUE TITLE
Rootcheck hangs indefinitely on readdir

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#9032]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.1.5 | rootcheck | Agent | Packages | CentOS 7.5 - Kernel: 3.10.0-862.el7.x86_64 - glibc: v2.17 |

An agent on a demo environment has been found to be using 100% of the CPU for an extended time.
![image](https://user-images.githubusercontent.com/20206636/122196493-929bce00-ce97-11eb-98b1-3147673c8b3d.png)

Upon further investigation, it was found that rootcheck was hanging on a syscall to `readdir`
![image](https://user-images.githubusercontent.com/20206636/122196642-b232f680-ce97-11eb-83ef-3c01a7f6499c.png)

At the time rootcheck hanged it was reading a directory inside `/proc` that no longer existed when we get to analyse it
![image](https://user-images.githubusercontent.com/20206636/122197617-a98ef000-ce98-11eb-84f9-0878478be137.png)

FS being used on the machine where the error was found is `xfs`:
![image](https://user-images.githubusercontent.com/20206636/122535546-f7842f00-d023-11eb-8602-0dd54bfdc746.png)

Possible causes of this hang:
- `readdir` is not thread safe, an interaction between multiple threads might be leaving the system in a state that causes the crash.

So far we have not been able to reproduce the error.

**Comment by Molter73** [comment]
I've found a couple of old bugs reported to glibc that look similar to the behavior that we have experienced, they seem to have been disregarded as `not a bug` or fixed on the newer versions, but I think it is worth mentioning them here:
https://sourceware.org/bugzilla/show_bug.cgi?id=14
https://lists.gnu.org/archive/html/bug-glibc/2003-12/msg00027.html

**Comment by vikman90** [comment]
This issue is produced by the same bug as #9737.

## Segmentation fault backtrace

```
#0  0x00007fce31f348ba in __memmove_sse2 () from /lib64/libc.so.6
#1  0x00007fce31f66356 in __getdents64 () from /lib64/libc.so.6
#2  0x00007fce31f65f11 in readdir64 () from /lib64/libc.so.6
#3  0x000000000041f118 in read_proc_dir (dir_name=dir_name@entry=0x7fce30c8cd90 "/proc/29043",
    pid=pid@entry=0x7fce30c8dde0 "18213", position=position@entry=1) at rootcheck/check_rc_readproc.c:60
#4  0x000000000041f09e in read_proc_file (file_name=file_name@entry=0x7fce30c8cd90 "/proc/29043",
    pid=pid@entry=0x7fce30c8dde0 "18213", position=position@entry=1) at rootcheck/check_rc_readproc.c:38
#5  0x000000000041f18d in read_proc_dir (dir_name=dir_name@entry=0x48fda3 "/proc",
    pid=pid@entry=0x7fce30c8dde0 "18213", position=position@entry=0) at rootcheck/check_rc_readproc.c:85
#6  0x000000000041f2eb in check_rc_readproc (pid=pid@entry=18213) at rootcheck/check_rc_readproc.c:123
#7  0x000000000041c097 in loop_all_pids (max_pid=32768, _total=<synthetic pointer>, _errors=<synthetic pointer>,
    ps=0x7fce30c8de60 "/bin/ps") at rootcheck/check_rc_pids.c:259
#8  check_rc_pids () at rootcheck/check_rc_pids.c:311
#9  0x000000000041b861 in run_rk_check () at rootcheck/run_rk_check.c:245
#10 0x000000000041ba55 in w_rootcheck_thread (args=0x6c5e60 <syscheck>) at rootcheck/run_rk_check.c:320
#11 0x00007fce3227aea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007fce31fa39fd in clone () from /lib64/libc.so.6
```

## Isolating the bug

We isolated the bug in a standalone program:

<details>
<summary>readproc.c</summary>

```c
// August 20, 2021
// gcc -std=c99 -D_POSIX_C_SOURCE=200112L -g -O2 -o readproc readproc.c
​
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <sys/types.h>
#include <dirent.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdbool.h>
#include <errno.h>
#include <ctype.h>
#include <limits.h>
​
#define PROC 0
#define PID  1
#define TASK 2
​
#define MAX_PID 32768
​
/* Prototypes */
static int read_proc_file(const char *file_name, const char *pid, int position);
static int read_proc_dir(const char *dir_name, const char *pid, int position);
​
bool is_file(char *file_name) {
    struct  stat statbuf;
    bool    ret = false;
    FILE    *fp = NULL;
    DIR     *dp = NULL;
​
    if (!file_name) {
        return ret;
    }
​
    dp = opendir(file_name);
    if (dp != NULL) {
        closedir(dp);
        ret = true;
    } else if (errno == ENOTDIR) {
        ret = true;
    }
​
    /* Trying other calls */
    if (stat(file_name, &statbuf) < 0 && access(file_name, F_OK) < 0 && ((fp = fopen(file_name, "r")) == NULL)) {
        return ret;
    }
​
    if (fp != NULL) {
        ret = true;
        fclose(fp);
    }
​
    return ret;
}
​
int read_proc_file(const char *file_name, const char *pid, int position) {
    struct stat statbuf;
​
    if (lstat(file_name, &statbuf) < 0) {
        return -1;
    }
​
    /* If directory, read the directory */
    if (S_ISDIR(statbuf.st_mode)) {
        return read_proc_dir(file_name, pid, position);
    }
​
    return 0;
}
​
int read_proc_dir(const char *dir_name, const char *pid, int position) {
    DIR * dp;
    struct dirent * entry = NULL;
    int proc_pid_found = 0;
​
    if (dir_name == NULL || strlen(dir_name) > PATH_MAX) {
        return -1;
    }
​
    /* Open the directory */
    dp = opendir(dir_name);
    if (dp == NULL) {
        return 0;
    }
​
    while ((entry = readdir(dp)) != NULL) {
        char f_name[PATH_MAX + 2];
​
        /* Ignore . and ..  */
        if (strcmp(entry->d_name, ".")  == 0 || strcmp(entry->d_name, "..") == 0) {
            continue;
        }
​
        if (position == PROC) {
            char *tmp_str;
​
            tmp_str = entry->d_name;
            while (*tmp_str != '\0') {
                if (!isdigit((int)*tmp_str)) {
                    break;
                }
                tmp_str++;
            }
​
            if (*tmp_str != '\0') {
                continue;
            }
​
            snprintf(f_name, PATH_MAX + 1, "%s/%s", dir_name, entry->d_name);
            proc_pid_found = read_proc_file(f_name, pid, position + 1);
        } else if (position == PID) {
            if (strcmp(entry->d_name, "task") == 0) {
                snprintf(f_name, PATH_MAX + 1, "%s/%s", dir_name, entry->d_name);
                proc_pid_found = read_proc_file(f_name, pid, position + 1);
            }
        } else if (position == TASK) {
            /* Check under proc/pid/task/lwp */
            if (strcmp(entry->d_name, pid) == 0) {
                proc_pid_found = 1;
            }
        } else {
            break;
        }
​
        if (proc_pid_found == 1) {
            break;
        }
    }
​
    closedir(dp);
​
    return proc_pid_found;
}
​
/*  Read the /proc directory (if present) and check if it can find
 *  the given pid (as a pid or as a thread)
 */
int check_rc_readproc(int pid)
{
    char char_pid[32];
​
    /* NL threads */
    snprintf(char_pid, 31, "/proc/.%d", pid);
    if (is_file(char_pid)) {
        return 1;
    }
​
    snprintf(char_pid, 31, "%d", pid);
    return read_proc_dir("/proc", char_pid, PROC);
}
​
int main() {
    for (;;) {
        for (int pid = 1; pid < MAX_PID; pid++) {
            switch (check_rc_readproc(pid)) {
            case -1:
                fprintf(stderr, "PID %d: error.\n", pid);
                break;
​
            case 0:
                break;
​
            default:
                printf("PID %d: found.\n", pid);
            }
        }
​
        fprintf(stderr, "================================== Scan ended ==================================\n");
    }
​
    return EXIT_SUCCESS;
}
```

</details>

## Producing the problem

We found that we can cause the problem quickly if we run ephemeral programs, like:

```shell
for i in {1..8}; do while true; do /bin/echo Hello > /dev/null; done & done
```
### Infinite loop (Valgrind)

```
==16638==    at 0x4C314C8: __GI_memmove (vg_replace_strmem.c:1273)
==16638==    by 0x4EF8355: __getdents (in /usr/lib64/libc-2.17.so)
==16638==    by 0x4EF7F10: readdir (in /usr/lib64/libc-2.17.so)
==16638==    by 0x400B3F: read_proc_dir (readproc.c:88)
==16638==    by 0x400ABD: read_proc_file (readproc.c:67)
==16638==    by 0x400BBD: read_proc_dir (readproc.c:112)
==16638==    by 0x400D80: check_rc_readproc (readproc.c:151)
==16638==    by 0x400933: main (readproc.c:157)
```

### Segmentation fault (strace)

```
lstat("/proc/28675/task", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
openat(AT_FDCWD, "/proc/28675/task", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 5
getdents(5strace: umoven: short read (69440 < 1048576) @0x13550c0
, 0x13550c0, 32768)           = 4294967294
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1366000} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

## Cause of the bug

We managed to relate this problem to [Diamorphine](https://github.com/m0nad/Diamorphine) kernel module installed in the system.

- With Diamorphine installed, the problem occurs in few seconds.
- Without Diamorphine installed, we did never see the issue.
