### ISSUE TITLE
Possible segmentation fault in development branch `6734-alas-support`

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#9048]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.0 | Modulesd | Manager | Sources | Tested on Debian 10|

As part of the issue https://github.com/wazuh/wazuh-qa/issues/1248

We have been doing some tests and we have detected a possible segmentation fault.

We need to check that when you delete a tag of the feed, the provider database updates correctly or shows an error message. When we tried to delete `references`, `vulnerabilites` or `fixed_packages`, the database update starts but then, the `modulesd` proccess stops.

## Steps to reproduce

- Install the package.
- Disable everything except vulnerability detector.
- Enable Amazon Linux support.
- Add a custom feed without the `references`, `vulnerabilites` or `fixed_packages` tag, for example [this custom feed](https://gist.github.com/juliamagan/78f6ef96797107433cf5a9a4761f0c16).
- For Amazon Linux 1 and 2 add the path of the custom feed:
```
    <!-- Amazon Linux OS vulnerabilities -->
    <provider name="alas">
      <enabled>yes</enabled>
      <os path="/tmp/custom_feed.json">amazon-linux</os>
      <update_interval>1h</update_interval>
    </provider>
```
- Start the manager.

## Log example:

When we try to restart the wazuh manager we get:
```
root@debian10:/tmp/wazuh-qa# /var/ossec/bin/wazuh-control restart
wazuh-clusterd not running...
wazuh-modulesd: Process 17379 not used by Wazuh, removing...
wazuh-modulesd: Process 2314 not used by Wazuh, removing...
wazuh-modulesd: Process 23278 not used by Wazuh, removing...
wazuh-modulesd: Process 25392 not used by Wazuh, removing...
wazuh-modulesd: Process 2888 not used by Wazuh, removing...
wazuh-modulesd: Process 6208 not used by Wazuh, removing...
wazuh-modulesd not running...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
wazuh-authd not running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.3.0 Stopped
Starting Wazuh v4.3.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2021/06/17 08:42:46 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
2021/06/17 08:42:50 wazuh-syscheckd: INFO: (6001): File integrity monitoring disabled.
2021/06/17 08:42:50 rootcheck: INFO: Rootcheck disabled.
Started wazuh-syscheckd...
Started wazuh-remoted...
2021/06/17 08:42:52 wazuh-logcollector: INFO: (1905): No file configured to monitor.
Started wazuh-logcollector...
Started wazuh-monitord...
wazuh-modulesd: Process 32748 not used by Wazuh, removing...
wazuh-modulesd did not start correctly.
```
And if we take a look at `/var/ossec/logs/ossec.log`:

```
root@debian10:/home/vagrant# tail -f /var/ossec/logs/ossec.log | grep modulesd
2021/06/17 08:42:54 wazuh-modulesd: INFO: Started (pid: 32748).
2021/06/17 08:42:54 wazuh-modulesd:syscollector: INFO: Module disabled. Exiting...
2021/06/17 08:42:54 wazuh-modulesd:database: INFO: Module started.
2021/06/17 08:42:54 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2021/06/17 08:42:54 wazuh-modulesd:download: INFO: Module started.
2021/06/17 08:42:54 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2021/06/17 08:42:54 wazuh-modulesd:control: INFO: Starting control thread.
2021/06/17 08:42:54 wazuh-modulesd:task-manager: INFO: (8200): Module Task Manager started.
2021/06/17 08:42:54 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2021/06/17 08:42:54 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Amazon Linux 1' database update.
```

After the last line, we can appreciate that `modulesd` is not running anymore.

```
root@debian10:/home/vagrant# ps aux | grep ossec
root      2957  0.9  0.3   6148  3200 pts/2    S+   08:13   0:17 watch -n0 ps aux | grep ossec
root      4737  0.0  0.0   6148   708 pts/2    S+   08:45   0:00 watch -n0 ps aux | grep ossec
root      4738  0.0  0.0   2388   760 pts/2    S+   08:45   0:00 sh -c ps aux | grep ossec
root      4740  0.0  0.0   6076   892 pts/2    S+   08:45   0:00 grep ossec
root     31413  0.0  0.0   5292   748 pts/1    S+   08:42   0:00 tail -f /var/ossec/logs/ossec.log
wazuh    32312  6.3  9.5 290880 96300 ?        Sl   08:42   0:08 /var/ossec/framework/python/bin/python3 /vwazuh    32372  0.2  0.8 693428  8296 ?        Sl   08:42   0:00 /var/ossec/bin/wazuh-db
root     32430  0.0  0.3  22692  3060 ?        Sl   08:42   0:00 /var/ossec/bin/wazuh-execd
wazuh    32477  0.5  2.2 599404 22572 ?        Sl   08:42   0:00 /var/ossec/bin/wazuh-analysisd
root     32521  0.0  0.5  31460  5180 ?        SNl  08:42   0:00 /var/ossec/bin/wazuh-syscheckd
wazuh    32590  0.3  0.4 507324  4528 ?        Sl   08:42   0:00 /var/ossec/bin/wazuh-remoted
root     32653  0.0  0.4 129260  4248 ?        Sl   08:42   0:00 /var/ossec/bin/wazuh-logcollector
wazuh    32704  0.0  0.3  22768  3444 ?        Sl   08:42   0:00 /var/ossec/bin/wazuh-monitord
```
We've managed to generate a coredump traceback of the error:
```
root@debian10:/tmp/wazuh-qa# gdb "/var/ossec/bin/wazuh-modulesd"
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /var/ossec/bin/wazuh-modulesd...done.
(gdb) run
Starting program: /var/ossec/bin/wazuh-modulesd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 6287]
[Inferior 1 (process 6251) exited normally]
(gdb) set follow-fork-mode child
(gdb) run
Starting program: /var/ossec/bin/wazuh-modulesd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Attaching after Thread 0x7ffff7418740 (LWP 6899) fork to child process 6920]
[New inferior 2 (process 6920)]
[Detaching after fork from parent process 6899]
[Inferior 1 (process 6899) detached]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Attaching after Thread 0x7ffff7418740 (LWP 6920) fork to child process 6921]
[New inferior 3 (process 6921)]
[Detaching after fork from parent process 6920]
[Inferior 2 (process 6920) detached]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7402700 (LWP 6926)]
[New Thread 0x7ffff6c01700 (LWP 6927)]
[New Thread 0x7ffff6400700 (LWP 6928)]
[New Thread 0x7ffff5bff700 (LWP 6929)]
[New Thread 0x7ffff53fe700 (LWP 6930)]
[New Thread 0x7ffff4bfd700 (LWP 6931)]
[Thread 0x7ffff5bff700 (LWP 6929) exited]
[New Thread 0x7fffe7fff700 (LWP 6932)]
[New Thread 0x7fffe77fe700 (LWP 6933)]
[Thread 0x7ffff4bfd700 (LWP 6931) exited]
[Thread 0x7ffff6400700 (LWP 6928) exited]
[New Thread 0x7fffe6ffd700 (LWP 6934)]
[Thread 0x7fffe7fff700 (LWP 6932) exited]
[New Thread 0x7fffe67fc700 (LWP 6935)]
[New Thread 0x7fffe5ffb700 (LWP 6936)]
[New Thread 0x7fffe57fa700 (LWP 6937)]
[New Thread 0x7fffe4ff9700 (LWP 6938)]

Thread 3.9 "wazuh-modulesd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe77fe700 (LWP 6933)]
0x000055555560f5dc in wm_vuldet_insert_ALAS (db=0x7fffd4075058, vul_it=0x7fffd407a0d0, target=0x55555567c202 "Amazon-Linux")
    at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:8258
8258    wazuh_modules/vulnerability_detector/wm_vuln_detector.c: No such file or directory.
(gdb) bt
#0  0x000055555560f5dc in wm_vuldet_insert_ALAS (db=0x7fffd4075058, vul_it=0x7fffd407a0d0, target=0x55555567c202 "Amazon-Linux")
    at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:8258
#1  0x00005555555f6153 in wm_vuldet_insert (parsed_oval=0x7fffe77fdd30, update=0x5555556f57b0)
    at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2688
#2  0x00005555555fd252 in wm_vuldet_index_feed (update=0x5555556f57b0) at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:3923
#3  0x00005555555ec891 in wm_vuldet_sync_feed (upd=0x5555556f57b0, need_update=0x7fffe77fdea3 "\001\v")
    at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:565
#4  0x00005555555f4e71 in wm_vuldet_update_feed (upd=0x5555556f57b0, updated=0x7fffe77fdea3 "\001\v")
    at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2406
#5  0x00005555555fe311 in wm_vuldet_check_feed (upd=0x5555556f57b0, updated=0x7fffe77fdea3 "\001\v")
    at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4241
#6  0x00005555555fe872 in wm_vuldet_run_update (updates=0x5555556f4948) at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4337
#7  0x0000555555601ac0 in wm_vuldet_main (vuldet=0x5555556f4940) at wazuh_modules/vulnerability_detector/wm_vuln_detector.c:4971
#8  0x00007ffff75e5fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007ffff75164cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by mdengra** [comment]
Hi, I have found the same compression when the feed is missing the vulnerabilities array, a possible segmentation fault in modulesd.
