### ISSUE TITLE
Error when adding agent with `add_manual` (API) if client.keys is empty

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#9053]
|Wazuh version|Component|
|---|---|
| master | Wazuh API |

## Description

Hello team,

I have encountered the following error in the `api.log` when trying to add an agent in an empty `client.keys` file when `wazuh-authd` is not running: 

```
2021/06/17 14:20:42 ERROR: Error registering a new agent: cannot mmap an empty file
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/agent.py", line 716, in _add
    self._add_manual(name, ip, id, key, force)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/agent.py", line 868, in _add_manual
    with mmap.mmap(f_k.fileno(), length=0, access=mmap.ACCESS_READ) as file_client:
ValueError: cannot mmap an empty file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 254, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 232, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/rbac/decorators.py", line 406, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/agent.py", line 391, in add_agent
    new_agent = Agent(name=name, ip=ip, id=agent_id, key=key, force=force_time, use_only_authd=use_only_authd)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/agent.py", line 360, in __init__
    self._add(name=name, ip=ip, id=id, key=key, force=force, use_only_authd=use_only_authd)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/agent.py", line 722, in _add
    raise WazuhInternalError(1725, extra_message=str(e))
wazuh.core.exception.WazuhInternalError: Error 1725 - Error registering a new agent: cannot mmap an empty file
2021/06/17 14:20:42 INFO: wazuh 192.168.160.1 "POST /agents" with parameters {"wait_for_complete": "true"} and body {"name": "test", "ip": "any"} done in 1.889s: 500
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.

**Comment by davidjiglesias** [comment]
Add manual has been deprecated in Wazuh v4.3.0 https://github.com/wazuh/wazuh/issues/10395
