### ISSUE TITLE
Can't retrieve agents in cluster_control

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#948]
Hello team,

Trying to run `cluster_control -a` ends up in the following error in the cluster:
```
2018-07-16 16:28:26,583 DEBUG   : [Transport-InternalSocket] Incoming connection from ''''.
2018-07-16 16:28:26,584 DEBUG   : [Transport-I] Forwarding request to master of cluster 'get_agents' - 'b'all%--%all%--%0%--%500''
2018-07-16 16:28:26,584 ERROR   : [Transport-Handler] Error processing command 'get_agents': ''>' not supported between instances of 'str' and 'int''.
Traceback (most recent call last):
  File "/var/ossec/bin/../framework/wazuh/cluster/communication.py", line 388, in dispatch
    return self.process_request(command, payload)
  File "/var/ossec/bin/../framework/wazuh/cluster/master.py", line 688, in process_request
    response = get_agents_status(filter_status, filter_nodes, offset, limit)
  File "/var/ossec/bin/../framework/wazuh/cluster/cluster.py", line 456, in get_agents_status
    offset=offset)
  File "/var/ossec/bin/../framework/wazuh/agent.py", line 984, in get_agents_overview
    if limit > common.maximum_database_limit:
TypeError: '>' not supported between instances of 'str' and 'int'
```

Best regards,
Marta

**Comment by mgmacias95** [comment]
Fixed in #949.
